In [2]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
DATA_DIR = PROJECT_ROOT / "data" / "raw"

print("Project Root:", PROJECT_ROOT)
print("Data Directory:", DATA_DIR)

Project Root: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge
Data Directory: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\data\raw

## Step 1 – Load Both Datasets

Load the English and Japanese CSV files.

The English dataset has already been explored in Notebook 01.

In this notebook, the English dataset is used only as the reference for comparison.

In [4]:
english = pd.read_csv(DATA_DIR / "EN_Card_Data.csv")
japanese = pd.read_csv(DATA_DIR / "JP_Card_Data.csv")

print("Datasets loaded successfully.")

Datasets loaded successfully.

## Step 2 – Compare Dataset Dimensions

Verify that both datasets contain the same number of rows and columns.

In [5]:
print("English Dataset:", english.shape)
print("Japanese Dataset:", japanese.shape)

English Dataset: (2022, 17)
Japanese Dataset: (2022, 17)

## Step 3 – Compare Column Names

Before analyzing the Japanese dataset, we must verify that both datasets share the exact same schema.

If the column names match, the same preprocessing and feature engineering pipeline can be used for both datasets.

In [6]:
english.columns

Index(['Card ID', 'Card Name', 'Expansion', 'Collection No.',
       'Stage (Pokémon)/Type (Energy and Trainer)', 'Rule', 'Category',
       'Previous stage', 'HP', 'Type', 'Weakness', 'Resistance (Type)',
       'Retreat', 'Move Name', 'Cost', 'Damage', 'Effect Explanation'],
      dtype='str')

In [7]:
japanese.columns

Index(['カード ID', 'カード名', 'エキスパンションマーク', 'コレクション番号',
       'ポケモンの進化の段階/エネルギー・トレーナーズの種類', 'ルール', 'カテゴリ', '進化前', 'HP', 'タイプ', '弱点',
       '抵抗力', 'にげる', 'ワザ名', 'コスト', 'ダメージ', '効果の説明'],
      dtype='str')

In [8]:
english.columns.equals(japanese.columns)

False

## Observation 2

Although the English and Japanese datasets contain the same number of columns, the column names are translated into their respective languages.

This is expected because the Japanese dataset is intended for Japanese players.

The identical dataset dimensions suggest that both files describe the same information using different languages.

## Step 4 – Compare Data Types

Even though the column names are translated, we expect the data types to remain consistent.

Matching data types indicate that both datasets can be processed using the same feature engineering pipeline.

In [10]:
english.dtypes

Card ID                                        int64
Card Name                                        str
Expansion                                        str
Collection No.                                 int64
Stage (Pokémon)/Type (Energy and Trainer)        str
Rule                                             str
Category                                         str
Previous stage                                   str
HP                                           float64
Type                                             str
Weakness                                         str
Resistance (Type)                                str
Retreat                                      float64
Move Name                                        str
Cost                                             str
Damage                                           str
Effect Explanation                               str
dtype: object

In [11]:
japanese.dtypes

カード ID                          int64
カード名                              str
エキスパンションマーク                       str
コレクション番号                          str
ポケモンの進化の段階/エネルギー・トレーナーズの種類        str
ルール                               str
カテゴリ                              str
進化前                               str
HP                            float64
タイプ                               str
弱点                                str
抵抗力                               str
にげる                           float64
ワザ名                               str
コスト                               str
ダメージ                              str
効果の説明                             str
dtype: object

In [12]:
print("English dtypes")
print(english.dtypes)

print("\nJapanese dtypes")
print(japanese.dtypes)

English dtypes
Card ID                                        int64
Card Name                                        str
Expansion                                        str
Collection No.                                 int64
Stage (Pokémon)/Type (Energy and Trainer)        str
Rule                                             str
Category                                         str
Previous stage                                   str
HP                                           float64
Type                                             str
Weakness                                         str
Resistance (Type)                                str
Retreat                                      float64
Move Name                                        str
Cost                                             str
Damage                                           str
Effect Explanation                               str
dtype: object

Japanese dtypes
カード ID                          int64
カード名                              str
エキスパンションマーク                       str
コレクション番号                          str
ポケモンの進化の段階/エネルギー・トレーナーズの種類        str
ルール                               str
カテゴリ                              str
進化前                               str
HP                            float64
タイプ                               str
弱点                                str
抵抗力                               str
にげる                           float64
ワザ名                               str
コスト                               str
ダメージ                              str
効果の説明                             str
dtype: object

## Observation 3

Both datasets share the same structural layout and data types.

The only major difference is that the Japanese dataset contains translated field names and translated card content.

This confirms that a language-independent preprocessing pipeline can be developed for the AI Battle Agent.

## Step 5 – Compare Basic Statistics

Before comparing individual cards, we first compare the overall statistics of both datasets.

This helps verify that both files contain the same amount of information and confirms that they represent the same collection of Pokémon cards in different languages.

In [13]:
print("English Dataset")
english.describe(include="all")

English Dataset

,Card ID,Card Name,Expansion,Collection No.,Stage (Pokémon)/Type (Energy and Trainer),Rule,Category,Previous stage,HP,Type,Weakness,Resistance (Type),Retreat,Move Name,Cost,Damage,Effect Explanation
count,2022.000000,2022,2012,2022.000000,2022,353,392,857,1815.000000,1825,1734,376,1748.000000,1811,1556,1285,1481
unique,NaN,1096,19,NaN,9,3,25,356,NaN,14,8,2,NaN,1226,127,45,1017
top,NaN,Eevee,DRI,NaN,Basic Pokémon,Pokémon ex,Trainer's Pokémon（Team Rocket）,Eevee,NaN,{G},{R},{F},NaN,[Tera],●,30,"As long as this Pokémon is on your Bench, prev..."
freq,NaN,6,279,NaN,958,270,85,32,NaN,257,361,266,NaN,29,263,189,29
mean,587.663699,NaN,NaN,70.745796,NaN,NaN,NaN,NaN,131.289256,NaN,NaN,NaN,1.740275,NaN,NaN,NaN,NaN
std,353.139066,NaN,NaN,48.271936,NaN,NaN,NaN,NaN,73.287066,NaN,NaN,NaN,0.858002,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,274.250000,NaN,NaN,31.000000,NaN,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
50%,576.000000,NaN,NaN,62.000000,NaN,NaN,NaN,NaN,110.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
75%,886.000000,NaN,NaN,106.000000,NaN,NaN,NaN,NaN,150.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
max,1267.000000,NaN,NaN,215.000000,NaN,NaN,NaN,NaN,380.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN

In [14]:
print("Japanese Dataset")
japanese.describe(include="all")

Japanese Dataset

,カード ID,カード名,エキスパンションマーク,コレクション番号,ポケモンの進化の段階/エネルギー・トレーナーズの種類,ルール,カテゴリ,進化前,HP,タイプ,弱点,抵抗力,にげる,ワザ名,コスト,ダメージ,効果の説明
count,2022.000000,2022,2014,2022,2022,353,392,857,1815.000000,1825,1734,376,1748.000000,1811,1556,1285,1481
unique,NaN,1096,32,1113,9,3,31,356,NaN,14,8,2,NaN,1225,127,45,1014
top,NaN,イーブイ,MC,011/063,ポケモン/たね,ex,テラスタル(ステラ),イーブイ,NaN,草,炎,闘,NaN,テラスタル,●,30,このポケモンは、ベンチにいるかぎり、ワザのダメージを受けない。
freq,NaN,6,840,6,958,270,60,32,NaN,257,361,266,NaN,32,263,189,32
mean,587.663699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.289256,NaN,NaN,NaN,1.740275,NaN,NaN,NaN,NaN
std,353.139066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.287066,NaN,NaN,NaN,0.858002,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,274.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
50%,576.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
75%,886.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
max,1267.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN

## Observation 4

The English and Japanese datasets share identical dimensions and numerical statistics.

However, several categorical fields differ because they are localized for different Pokémon TCG releases.

For example:

- Expansion names differ.
- Collection numbering differs.
- Card text is translated.
- Category names are localized.

These differences are expected and do not affect the overall dataset structure.

The numerical attributes (such as HP and Retreat Cost) remain consistent, making it possible to build a language-independent AI preprocessing pipeline.

## Step 6 – Compare Missing Values

Many Pokémon TCG fields are optional.

For example:

- Energy cards do not have HP.
- Trainer cards do not have attacks.
- Stadium cards do not have Retreat Cost.

The missing-value pattern should therefore be nearly identical between the English and Japanese datasets.

In [15]:
english.isnull().sum()

Card ID                                         0
Card Name                                       0
Expansion                                      10
Collection No.                                  0
Stage (Pokémon)/Type (Energy and Trainer)       0
Rule                                         1669
Category                                     1630
Previous stage                               1165
HP                                            207
Type                                          197
Weakness                                      288
Resistance (Type)                            1646
Retreat                                       274
Move Name                                     211
Cost                                          466
Damage                                        737
Effect Explanation                            541
dtype: int64

In [16]:
japanese.isnull().sum()

カード ID                           0
カード名                             0
エキスパンションマーク                      8
コレクション番号                         0
ポケモンの進化の段階/エネルギー・トレーナーズの種類       0
ルール                           1669
カテゴリ                          1630
進化前                           1165
HP                             207
タイプ                            197
弱点                             288
抵抗力                           1646
にげる                            274
ワザ名                            211
コスト                            466
ダメージ                           737
効果の説明                          541
dtype: int64

In [17]:
comparison = pd.DataFrame({
    "English Missing": english.isnull().sum(),
    "Japanese Missing": japanese.isnull().sum()
})

comparison

                                           English Missing  Japanese Missing
Card ID                                                0.0               NaN
Card Name                                              0.0               NaN
Category                                            1630.0               NaN
Collection No.                                         0.0               NaN
Cost                                                 466.0               NaN
Damage                                               737.0               NaN
Effect Explanation                                   541.0               NaN
Expansion                                             10.0               NaN
HP                                                   207.0             207.0
Move Name                                            211.0               NaN
Previous stage                                      1165.0               NaN
Resistance (Type)                                   1646.0               NaN
Retreat                                              274.0               NaN
Rule                                                1669.0               NaN
Stage (Pokémon)/Type (Energy and Trainer)              0.0               NaN
Type                                                 197.0               NaN
Weakness                                             288.0               NaN
にげる                                                    NaN             274.0
エキスパンションマーク                                            NaN               8.0
カテゴリ                                                   NaN            1630.0
カード ID                                                 NaN               0.0
カード名                                                   NaN               0.0
コスト                                                    NaN             466.0
コレクション番号                                               NaN               0.0
タイプ                                                    NaN             197.0
ダメージ                                                   NaN             737.0
ポケモンの進化の段階/エネルギー・トレーナーズの種類                             NaN               0.0
ルール                                                    NaN            1669.0
ワザ名                                                    NaN             211.0
効果の説明                                                  NaN             541.0
弱点                                                     NaN             288.0
抵抗力                                                    NaN            1646.0
進化前                                                    NaN            1165.0

In [20]:
comparison = pd.DataFrame({
    "English Column": english.columns,
    "Japanese Column": japanese.columns,
    "English Missing": english.isnull().sum().values,
    "Japanese Missing": japanese.isnull().sum().values
})

comparison

,English Column,Japanese Column,English Missing,Japanese Missing
0,Card ID,カード ID,0,0
1,Card Name,カード名,0,0
2,Expansion,エキスパンションマーク,10,8
3,Collection No.,コレクション番号,0,0
4,Stage (Pokémon)/Type (Energy and Trainer),ポケモンの進化の段階/エネルギー・トレーナーズの種類,0,0
5,Rule,ルール,1669,1669
6,Category,カテゴリ,1630,1630
7,Previous stage,進化前,1165,1165
8,HP,HP,207,207
9,Type,タイプ,197,197
10,Weakness,弱点,288,288
11,Resistance (Type),抵抗力,1646,1646
12,Retreat,にげる,274,274
13,Move Name,ワザ名,211,211
14,Cost,コスト,466,466
15,Damage,ダメージ,737,737
16,Effect Explanation,効果の説明,541,541

In [21]:
comparison["Difference"] = (
    comparison["English Missing"]
    - comparison["Japanese Missing"]
)

comparison

,English Column,Japanese Column,English Missing,Japanese Missing,Difference
0,Card ID,カード ID,0,0,0
1,Card Name,カード名,0,0,0
2,Expansion,エキスパンションマーク,10,8,2
3,Collection No.,コレクション番号,0,0,0
4,Stage (Pokémon)/Type (Energy and Trainer),ポケモンの進化の段階/エネルギー・トレーナーズの種類,0,0,0
5,Rule,ルール,1669,1669,0
6,Category,カテゴリ,1630,1630,0
7,Previous stage,進化前,1165,1165,0
8,HP,HP,207,207,0
9,Type,タイプ,197,197,0
10,Weakness,弱点,288,288,0
11,Resistance (Type),抵抗力,1646,1646,0
12,Retreat,にげる,274,274,0
13,Move Name,ワザ名,211,211,0
14,Cost,コスト,466,466,0
15,Damage,ダメージ,737,737,0
16,Effect Explanation,効果の説明,541,541,0

## Observation 5

The English and Japanese datasets exhibit very similar missing-value patterns.

Most structural fields have identical or nearly identical counts of missing values.

Small differences (such as Expansion) are expected because the English and Japanese Pokémon TCG releases contain localized metadata.

Overall, both datasets preserve the same underlying card structure, allowing a common preprocessing pipeline to support multilingual analysis.

# Step 7 – Compare Equivalent Cards

## Objective

The previous analyses verified that both datasets have similar structures.

In this section, we compare sample cards from both datasets to observe how Pokémon card information is represented in English and Japanese.

Rather than focusing on translation quality, our goal is to verify that both datasets describe the same game mechanics using different languages.

In [22]:
english.head(3)

,Card ID,Card Name,Expansion,Collection No.,Stage (Pokémon)/Type (Energy and Trainer),Rule,Category,Previous stage,HP,Type,Weakness,Resistance (Type),Retreat,Move Name,Cost,Damage,Effect Explanation
0,1,Basic {G} Energy,SVE,1,Basic Energy,NaN,NaN,NaN,NaN,{G},NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Basic {R} Energy,SVE,2,Basic Energy,NaN,NaN,NaN,NaN,{R},NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Basic {W} Energy,SVE,3,Basic Energy,NaN,NaN,NaN,NaN,{W},NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
japanese.head(3)

,カード ID,カード名,エキスパンションマーク,コレクション番号,ポケモンの進化の段階/エネルギー・トレーナーズの種類,ルール,カテゴリ,進化前,HP,タイプ,弱点,抵抗力,にげる,ワザ名,コスト,ダメージ,効果の説明
0,1,基本【草】エネルギー,NaN,GRA,基本エネルギー,NaN,NaN,NaN,NaN,草,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,基本【炎】エネルギー,NaN,FIR,基本エネルギー,NaN,NaN,NaN,NaN,炎,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,基本【水】エネルギー,NaN,WAT,基本エネルギー,NaN,NaN,NaN,NaN,水,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Observation 6

Although the text is written in different languages, both datasets follow the same logical structure.

Each record contains:

- Card identifier
- Card name
- Expansion
- Card stage
- HP
- Pokémon type
- Weakness
- Resistance
- Retreat Cost
- Move information

This confirms that both datasets represent equivalent Pokémon Trading Card Game data.

# Notebook Summary

## Objective

Compare the English and Japanese Pokémon TCG datasets.

## Findings

✔ Both datasets contain 2,022 records.

✔ Both datasets contain 17 primary features.

✔ Both datasets share the same logical structure.

✔ Numerical attributes are consistent.

✔ Text fields are localized into different languages.

✔ Missing-value patterns are nearly identical.

## Conclusion

The English and Japanese datasets describe the same Pokémon Trading Card Game collection while supporting different languages.

Therefore, a single preprocessing pipeline can be developed for multilingual AI battle analysis.