In [1]:
# ==========================================================================================
# NOTEBOOK 60 — LARGE-SCALE SIDE-NEUTRAL COMPETITIVE BENCHMARKING
# SECTION 1A — PROJECT SETUP AND NOTEBOOK 59 HANDOFF VALIDATION
# ==========================================================================================

from pathlib import Path
import json
import sys

import numpy as np
import pandas as pd


print("=" * 100)
print("NOTEBOOK 60 — LARGE-SCALE SIDE-NEUTRAL COMPETITIVE BENCHMARKING")
print("SECTION 1A — PROJECT SETUP AND NOTEBOOK 59 HANDOFF VALIDATION")
print("=" * 100)


# ==========================================================================================
# 1. Project paths
# ==========================================================================================

PROJECT_ROOT = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

NOTEBOOK59_OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "notebook59"
)

NOTEBOOK59_ARTIFACT_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "notebook59"
)

NOTEBOOK59_REPORT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "notebook59"
)

NOTEBOOK60_OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "notebook60"
)

NOTEBOOK60_ARTIFACT_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "notebook60"
)

NOTEBOOK60_REPORT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "notebook60"
)


for directory in [
    NOTEBOOK60_OUTPUT_DIR,
    NOTEBOOK60_ARTIFACT_DIR,
    NOTEBOOK60_REPORT_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )


if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


print("\nPROJECT ROOT")
print("-" * 100)
print(PROJECT_ROOT)

print("\nNOTEBOOK 59 OUTPUT DIRECTORY")
print("-" * 100)
print(NOTEBOOK59_OUTPUT_DIR)

print("\nNOTEBOOK 59 ARTIFACT DIRECTORY")
print("-" * 100)
print(NOTEBOOK59_ARTIFACT_DIR)

print("\nNOTEBOOK 59 REPORT DIRECTORY")
print("-" * 100)
print(NOTEBOOK59_REPORT_DIR)

print("\nNOTEBOOK 60 OUTPUT DIRECTORY")
print("-" * 100)
print(NOTEBOOK60_OUTPUT_DIR)


# ==========================================================================================
# 2. Required Notebook 59 handoff files
# ==========================================================================================

NOTEBOOK59_REQUIRED_FILES = {
    "battle_results":
        NOTEBOOK59_OUTPUT_DIR
        / "r3_controlled_battle_results.csv",

    "card_ranking":
        NOTEBOOK59_OUTPUT_DIR
        / "r3_controlled_card_ranking.csv",

    "pairwise_summary":
        NOTEBOOK59_OUTPUT_DIR
        / "r3_pairwise_matchup_summary.csv",

    "side_summary":
        NOTEBOOK59_OUTPUT_DIR
        / "r3_starting_side_summary.csv",

    "action_usage":
        NOTEBOOK59_OUTPUT_DIR
        / "r3_action_usage.csv",

    "integration_summary":
        NOTEBOOK59_OUTPUT_DIR
        / "notebook59_r3_live_integration_summary.json",
}


artifact_rows_60 = []

for artifact_name, artifact_path in (
    NOTEBOOK59_REQUIRED_FILES.items()
):

    artifact_rows_60.append(
        {
            "artifact":
                artifact_name,

            "path":
                str(
                    artifact_path
                ),

            "exists":
                artifact_path.exists(),

            "size_bytes":
                (
                    artifact_path.stat().st_size
                    if artifact_path.exists()
                    else 0
                ),
        }
    )


section1a_artifact_df = pd.DataFrame(
    artifact_rows_60
)


print("\nNOTEBOOK 59 HANDOFF FILES")
print("-" * 100)

display(
    section1a_artifact_df
)


assert section1a_artifact_df[
    "exists"
].all(), (
    "One or more Notebook 59 handoff files are missing."
)

assert section1a_artifact_df[
    "size_bytes"
].gt(0).all(), (
    "One or more Notebook 59 handoff files are empty."
)


# ==========================================================================================
# 3. Load Notebook 59 integration summary
# ==========================================================================================

with open(
    NOTEBOOK59_REQUIRED_FILES[
        "integration_summary"
    ],
    "r",
    encoding="utf-8",
) as file:

    notebook59_summary_60 = json.load(
        file
    )


print("\nNOTEBOOK 59 INTEGRATION SUMMARY")
print("-" * 100)

for key, value in notebook59_summary_60.items():

    if key == "controlled_ranking":
        continue

    print(
        f"{key}: {value}"
    )


# ==========================================================================================
# 4. Hard handoff gates
# ==========================================================================================

assert (
    notebook59_summary_60[
        "integration_status"
    ]
    ==
    "PASSED"
), (
    "Notebook 59 integration status is not PASSED."
)

assert (
    notebook59_summary_60[
        "benchmark_status"
    ]
    ==
    "READY_FOR_NOTEBOOK_60"
), (
    "Notebook 59 is not marked READY_FOR_NOTEBOOK_60."
)

assert (
    notebook59_summary_60[
        "production_strategy"
    ]
    ==
    "R3_STATE_CENTRIC_POLICY"
)

assert (
    notebook59_summary_60[
        "production_model_type"
    ]
    ==
    "RandomForestClassifier"
)

assert int(
    notebook59_summary_60[
        "retained_feature_count"
    ]
) == 46

assert int(
    notebook59_summary_60[
        "fallback_decisions"
    ]
) == 0

assert np.isclose(
    float(
        notebook59_summary_60[
            "model_driven_rate"
        ]
    ),
    1.0,
)


# ==========================================================================================
# 5. Load Notebook 59 benchmark handoff tables
# ==========================================================================================

notebook59_battle_results_df = pd.read_csv(
    NOTEBOOK59_REQUIRED_FILES[
        "battle_results"
    ]
)

notebook59_card_ranking_df = pd.read_csv(
    NOTEBOOK59_REQUIRED_FILES[
        "card_ranking"
    ]
)

notebook59_pairwise_df = pd.read_csv(
    NOTEBOOK59_REQUIRED_FILES[
        "pairwise_summary"
    ]
)

notebook59_side_summary_df = pd.read_csv(
    NOTEBOOK59_REQUIRED_FILES[
        "side_summary"
    ]
)

notebook59_action_usage_df = pd.read_csv(
    NOTEBOOK59_REQUIRED_FILES[
        "action_usage"
    ]
)


print("\nNOTEBOOK 59 CONTROLLED CARD RANKING")
print("-" * 100)

display(
    notebook59_card_ranking_df
)


# ==========================================================================================
# 6. Notebook 60 mission lock
# ==========================================================================================

NOTEBOOK60_OBJECTIVES = {
    "retrain_r3":
        False,

    "modify_frozen_r3_model":
        False,

    "large_scale_benchmarking":
        True,

    "side_neutral_evaluation":
        True,

    "matchup_robustness":
        True,

    "baseline_comparison":
        True,

    "submission_readiness_evidence":
        True,
}


print("\nNOTEBOOK 60 MISSION")
print("-" * 100)

for objective, enabled in (
    NOTEBOOK60_OBJECTIVES.items()
):

    print(
        f"{objective:<35}: {enabled}"
    )


assert (
    NOTEBOOK60_OBJECTIVES[
        "retrain_r3"
    ]
    is False
)

assert (
    NOTEBOOK60_OBJECTIVES[
        "modify_frozen_r3_model"
    ]
    is False
)


# ==========================================================================================
# 7. Final validation
# ==========================================================================================

section1a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "NB59 handoff files present",

            "passed":
                section1a_artifact_df[
                    "exists"
                ].all(),
        },

        {
            "validation":
                "NB59 integration passed",

            "passed":
                (
                    notebook59_summary_60[
                        "integration_status"
                    ]
                    ==
                    "PASSED"
                ),
        },

        {
            "validation":
                "NB59 ready for NB60",

            "passed":
                (
                    notebook59_summary_60[
                        "benchmark_status"
                    ]
                    ==
                    "READY_FOR_NOTEBOOK_60"
                ),
        },

        {
            "validation":
                "R3 strategy confirmed",

            "passed":
                (
                    notebook59_summary_60[
                        "production_strategy"
                    ]
                    ==
                    "R3_STATE_CENTRIC_POLICY"
                ),
        },

        {
            "validation":
                "46 feature contract confirmed",

            "passed":
                (
                    int(
                        notebook59_summary_60[
                            "retained_feature_count"
                        ]
                    )
                    == 46
                ),
        },

        {
            "validation":
                "zero fallback handoff",

            "passed":
                (
                    int(
                        notebook59_summary_60[
                            "fallback_decisions"
                        ]
                    )
                    == 0
                ),
        },
    ]
)


print("\nSECTION 1A VALIDATION")
print("-" * 100)

display(
    section1a_validation_df
)


assert section1a_validation_df[
    "passed"
].all()


print("\n" + "=" * 100)

print("✅ NOTEBOOK 59 HANDOFF FILES FOUND")
print("✅ NOTEBOOK 59 INTEGRATION STATUS CONFIRMED")
print("✅ APPROVED R3 STRATEGY CONFIRMED")
print("✅ 46-FEATURE CONTRACT CONFIRMED")
print("✅ ZERO-FALLBACK HANDOFF CONFIRMED")
print("✅ NOTEBOOK 60 OUTPUT / ARTIFACT / REPORT DIRECTORIES READY")
print("✅ NOTEBOOK 60 MISSION LOCKED")
print("✅ SECTION 1A COMPLETE")

print("=" * 100)

====================================================================================================
NOTEBOOK 60 — LARGE-SCALE SIDE-NEUTRAL COMPETITIVE BENCHMARKING
SECTION 1A — PROJECT SETUP AND NOTEBOOK 59 HANDOFF VALIDATION
====================================================================================================

PROJECT ROOT
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge

NOTEBOOK 59 OUTPUT DIRECTORY
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook59

NOTEBOOK 59 ARTIFACT DIRECTORY
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\artifacts\notebook59

NOTEBOOK 59 REPORT DIRECTORY
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook59

NOTEBOOK 60 OUTPUT DIRECTORY
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60

NOTEBOOK 59 HANDOFF FILES
----------------------------------------------------------------------------------------------------

,artifact,path,exists,size_bytes
0,battle_results,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,1685
1,card_ranking,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,170
2,pairwise_summary,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,328
3,side_summary,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,153
4,action_usage,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,162
5,integration_summary,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,True,1371

NOTEBOOK 59 INTEGRATION SUMMARY
----------------------------------------------------------------------------------------------------
notebook: 59
purpose: R3 live simulator integration and controlled competitive validation
production_strategy: R3_STATE_CENTRIC_POLICY
production_model_type: RandomForestClassifier
retained_feature_count: 46
model_class_count: 6
model_classes: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
controlled_battles: 12
total_live_decisions: 86
model_driven_decisions: 86
fallback_decisions: 0
model_driven_rate: 1.0
fallback_rate: 0.0
terminal_battle_rate: 1.0
average_battle_turns: 7.166666666666667
pairwise_winner_side_consistency: 1.0
integration_status: PASSED
benchmark_status: READY_FOR_NOTEBOOK_60
created_at: 2026-08-08T17:15:48

NOTEBOOK 59 CONTROLLED CARD RANKING
----------------------------------------------------------------------------------------------------

   rank        card  battles  wins  losses  draws  win_rate
0     1  Charmander        6     6       0      0  1.000000
1     2       Eevee        6     4       2      0  0.666667
2     3   Bulbasaur        6     2       4      0  0.333333
3     4      Meowth        6     0       6      0  0.000000

NOTEBOOK 60 MISSION
----------------------------------------------------------------------------------------------------
retrain_r3                         : False
modify_frozen_r3_model             : False
large_scale_benchmarking           : True
side_neutral_evaluation            : True
matchup_robustness                 : True
baseline_comparison                : True
submission_readiness_evidence      : True

SECTION 1A VALIDATION
----------------------------------------------------------------------------------------------------

                      validation  passed
0     NB59 handoff files present    True
1        NB59 integration passed    True
2            NB59 ready for NB60    True
3          R3 strategy confirmed    True
4  46 feature contract confirmed    True
5          zero fallback handoff    True

====================================================================================================
✅ NOTEBOOK 59 HANDOFF FILES FOUND
✅ NOTEBOOK 59 INTEGRATION STATUS CONFIRMED
✅ APPROVED R3 STRATEGY CONFIRMED
✅ 46-FEATURE CONTRACT CONFIRMED
✅ ZERO-FALLBACK HANDOFF CONFIRMED
✅ NOTEBOOK 60 OUTPUT / ARTIFACT / REPORT DIRECTORIES READY
✅ NOTEBOOK 60 MISSION LOCKED
✅ SECTION 1A COMPLETE
====================================================================================================

In [2]:
# ==========================================================================================
# SECTION 1B — RECOVER ESTABLISHED PROJECT BASELINE BENCHMARKS
# ==========================================================================================

print("=" * 100)
print("SECTION 1B — RECOVER ESTABLISHED PROJECT BASELINE BENCHMARKS")
print("=" * 100)

from pathlib import Path
import json
import re

import pandas as pd


# ==========================================================================================
# 1. Search locations
# ==========================================================================================

SEARCH_ROOTS_1B = [
    PROJECT_ROOT / "outputs",
    PROJECT_ROOT / "artifacts",
    PROJECT_ROOT / "reports",
    PROJECT_ROOT / "scripts",
]


# ==========================================================================================
# 2. Baseline search targets
#
# We are looking for the established side-neutral benchmark family:
#
#   side-neutral
#   first / player-first
#   second / opponent-first
#   win rate
#
# We do not hard-code the final baseline values here.
# We recover them from project evidence.
# ==========================================================================================

SEARCH_TERMS_1B = [
    "side-neutral",
    "side neutral",
    "side_neutral",
    "first",
    "second",
    "win rate",
    "win_rate",
    "baseline",
    "benchmark",
]


baseline_match_records_1b = []


for search_root in SEARCH_ROOTS_1B:

    if not search_root.exists():
        continue

    for file_path in search_root.rglob("*"):

        if not file_path.is_file():
            continue

        if "__pycache__" in file_path.parts:
            continue

        if file_path.suffix.lower() not in {
            ".py",
            ".txt",
            ".json",
            ".csv",
            ".md",
        }:
            continue

        try:

            source_text = file_path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            )

        except Exception:
            continue

        source_lower = source_text.lower()

        matched_terms = [
            term
            for term in SEARCH_TERMS_1B
            if term.lower() in source_lower
        ]

        if not matched_terms:
            continue

        # ------------------------------------------------------------------
        # Find lines most likely to contain actual benchmark values
        # ------------------------------------------------------------------

        source_lines = source_text.splitlines()

        relevant_lines = []

        for line_number, line in enumerate(
            source_lines,
            start=1,
        ):

            line_lower = line.lower()

            if any(
                term.lower() in line_lower
                for term in SEARCH_TERMS_1B
            ):

                relevant_lines.append(
                    {
                        "line_number":
                            line_number,

                        "line":
                            line.strip(),
                    }
                )

        baseline_match_records_1b.append(
            {
                "file":
                    str(
                        file_path.relative_to(
                            PROJECT_ROOT
                        )
                    ),

                "matched_terms":
                    matched_terms,

                "relevant_lines":
                    relevant_lines[:50],
            }
        )


# ==========================================================================================
# 3. Summary table
# ==========================================================================================

baseline_summary_rows_1b = []

for record in baseline_match_records_1b:

    baseline_summary_rows_1b.append(
        {
            "file":
                record["file"],

            "matched_terms":
                ", ".join(
                    record["matched_terms"]
                ),

            "relevant_line_count":
                len(
                    record["relevant_lines"]
                ),
        }
    )


section1b_baseline_search_df = pd.DataFrame(
    baseline_summary_rows_1b
)


print("\nBASELINE / BENCHMARK SEARCH RESULTS")
print("-" * 100)

if section1b_baseline_search_df.empty:

    print(
        "No baseline benchmark references found."
    )

else:

    display(
        section1b_baseline_search_df
        .sort_values(
            "relevant_line_count",
            ascending=False,
        )
        .reset_index(
            drop=True
        )
    )


# ==========================================================================================
# 4. Print detailed candidate evidence
# ==========================================================================================

print("\nDETAILED BASELINE EVIDENCE")
print("-" * 100)

for index, record in enumerate(
    baseline_match_records_1b[:30],
    start=1,
):

    print("\n" + "=" * 100)

    print(
        f"CANDIDATE {index}"
    )

    print(
        "FILE:",
        record["file"],
    )

    print(
        "MATCHED TERMS:",
        record["matched_terms"],
    )

    print("-" * 100)

    for line_record in record[
        "relevant_lines"
    ]:

        print(
            f"{line_record['line_number']:>5}: "
            f"{line_record['line']}"
        )


# ==========================================================================================
# 5. Search specifically for percentage-like benchmark values
# ==========================================================================================

percentage_records_1b = []

percentage_pattern_1b = re.compile(
    r"""
    (?P<label>
        side[-_\s]*neutral |
        first |
        second |
        player[-_\s]*first |
        opponent[-_\s]*first |
        win[-_\s]*rate
    )
    [^0-9]{0,40}
    (?P<value>
        \d{1,3}(?:\.\d+)?
    )
    \s*
    (?P<percent>%?)
    """,
    flags=re.IGNORECASE | re.VERBOSE,
)


for record in baseline_match_records_1b:

    file_path = (
        PROJECT_ROOT
        / record["file"]
    )

    try:

        source_text = file_path.read_text(
            encoding="utf-8-sig",
            errors="ignore",
        )

    except Exception:
        continue

    for line_number, line in enumerate(
        source_text.splitlines(),
        start=1,
    ):

        for match in percentage_pattern_1b.finditer(
            line
        ):

            percentage_records_1b.append(
                {
                    "file":
                        record["file"],

                    "line_number":
                        line_number,

                    "label":
                        match.group(
                            "label"
                        ),

                    "value":
                        match.group(
                            "value"
                        ),

                    "percent_symbol":
                        match.group(
                            "percent"
                        ),

                    "source_line":
                        line.strip(),
                }
            )


section1b_percentage_candidates_df = pd.DataFrame(
    percentage_records_1b
)


print("\nPERCENTAGE / RATE CANDIDATES")
print("-" * 100)

if section1b_percentage_candidates_df.empty:

    print(
        "No percentage-like baseline candidates found."
    )

else:

    display(
        section1b_percentage_candidates_df
        .drop_duplicates()
        .reset_index(
            drop=True
        )
    )


# ==========================================================================================
# 6. Search for known baseline benchmark structure in filenames
# ==========================================================================================

filename_candidates_1b = []

for search_root in SEARCH_ROOTS_1B:

    if not search_root.exists():
        continue

    for file_path in search_root.rglob("*"):

        if not file_path.is_file():
            continue

        filename_lower = file_path.name.lower()

        if any(
            token in filename_lower
            for token in [
                "benchmark",
                "baseline",
                "evaluation",
                "side_neutral",
                "side-neutral",
                "competitive",
            ]
        ):

            filename_candidates_1b.append(
                {
                    "file":
                        str(
                            file_path.relative_to(
                                PROJECT_ROOT
                            )
                        ),

                    "size_bytes":
                        file_path.stat().st_size,
                }
            )


section1b_filename_candidates_df = pd.DataFrame(
    filename_candidates_1b
)


print("\nBENCHMARK-RELATED PROJECT FILES")
print("-" * 100)

if section1b_filename_candidates_df.empty:

    print(
        "No benchmark-related filenames found."
    )

else:

    display(
        section1b_filename_candidates_df
        .drop_duplicates()
        .reset_index(
            drop=True
        )
    )


# ==========================================================================================
# 7. Completion
# ==========================================================================================

print("\n" + "=" * 100)

print("✅ PROJECT OUTPUTS SEARCHED")
print("✅ PROJECT ARTIFACTS SEARCHED")
print("✅ PROJECT REPORTS SEARCHED")
print("✅ PROJECT SCRIPTS SEARCHED")
print("✅ BASELINE / BENCHMARK REFERENCES COLLECTED")
print("✅ PERCENTAGE-LIKE CANDIDATES COLLECTED")
print("✅ SECTION 1B COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 1B — RECOVER ESTABLISHED PROJECT BASELINE BENCHMARKS
====================================================================================================

BASELINE / BENCHMARK SEARCH RESULTS
----------------------------------------------------------------------------------------------------

,file,matched_terms,relevant_line_count
0,scripts\54_tournament_strength_optimization_cl...,"side-neutral, side_neutral, first, second, win...",50
1,scripts\54_tournament_strength_optimization_CO...,"side-neutral, side_neutral, first, second, win...",50
2,scripts\55_controlled_feature_ablation_retrain...,"side neutral, first, second, win_rate, baseline",50
3,scripts\54_tournament_strength_optimization_CO...,"side-neutral, side_neutral, first, second, win...",50
4,scripts\55_controlled_feature_ablation_retrain...,"side neutral, first, second, win_rate, baseline",50
...,...,...,...
449,reports\notebook49\section7\section7a_state_ru...,second,1
450,reports\notebook49\section7\section7a_runtime_...,second,1
451,reports\notebook47\competitive_policy_training...,second,1
452,reports\notebook46\first_real_expert_search.json,second,1
453,reports\notebook36\production_classes.csv,benchmark,1

DETAILED BASELINE EVIDENCE
----------------------------------------------------------------------------------------------------

====================================================================================================
CANDIDATE 1
FILE: outputs\notebook59\notebook59_r3_live_integration_summary.json
MATCHED TERMS: ['win_rate', 'benchmark']
----------------------------------------------------------------------------------------------------
   31: "win_rate": 1.0
   38: "win_rate": 0.6666666666666666
   45: "win_rate": 0.3333333333333333
   52: "win_rate": 0.0
   56: "benchmark_status": "READY_FOR_NOTEBOOK_60",

====================================================================================================
CANDIDATE 2
FILE: outputs\notebook59\r3_controlled_card_ranking.csv
MATCHED TERMS: ['win_rate']
----------------------------------------------------------------------------------------------------
    1: rank,card,battles,wins,losses,draws,win_rate

====================================================================================================
CANDIDATE 3
FILE: outputs\notebook59\r3_starting_side_summary.csv
MATCHED TERMS: ['win_rate']
----------------------------------------------------------------------------------------------------
    1: starting_side,battles,starter_wins,starter_win_rate,average_turns

====================================================================================================
CANDIDATE 4
FILE: artifacts\notebook55\section2c_strategy_feature_indices_and_names.json
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    3: "R0_CURRENT_BASELINE": [
  233: "R0_CURRENT_BASELINE": [

====================================================================================================
CANDIDATE 5
FILE: artifacts\notebook57\notebook57_summary.json
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    7: "R0_CURRENT_BASELINE",

====================================================================================================
CANDIDATE 6
FILE: artifacts\notebook57\section3a_feature_importance.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_CURRENT_BASELINE,49,categorical__legal_move_signature_ascension,0.05449979700429139,1,5.449979700429139,categorical,legal_move_signature_ascension
    3: R0_CURRENT_BASELINE,53,categorical__legal_move_signature_pass,0.04839845613686418,2,4.839845613686418,categorical,legal_move_signature_pass
    4: R0_CURRENT_BASELINE,22,numeric__is_legal__pass,0.04722155429519175,3,4.722155429519175,numeric,is_legal__pass
    5: R0_CURRENT_BASELINE,27,numeric__active_card_can_use__live_coal,0.039745023120865246,4,3.9745023120865244,numeric,active_card_can_use__live_coal
    6: R0_CURRENT_BASELINE,42,categorical__active_card_Charmander,0.03878718231524732,5,3.878718231524732,categorical,active_card_Charmander
    7: R0_CURRENT_BASELINE,21,numeric__is_legal__live_coal,0.038187332016559807,6,3.8187332016559807,numeric,is_legal__live_coal
    8: R0_CURRENT_BASELINE,41,categorical__active_card_Bulbasaur,0.036166827943375626,7,3.616682794337563,categorical,active_card_Bulbasaur
    9: R0_CURRENT_BASELINE,20,numeric__is_legal__bind_down,0.034920246546350224,8,3.4920246546350224,numeric,is_legal__bind_down
   10: R0_CURRENT_BASELINE,19,numeric__is_legal__ascension,0.03412478603373445,9,3.412478603373445,numeric,is_legal__ascension
   11: R0_CURRENT_BASELINE,51,categorical__legal_move_signature_bind down,0.03394547891764955,10,3.394547891764955,categorical,legal_move_signature_bind down
   12: R0_CURRENT_BASELINE,28,numeric__active_card_can_use__pass,0.03352666669100351,11,3.352666669100351,numeric,active_card_can_use__pass
   13: R0_CURRENT_BASELINE,52,categorical__legal_move_signature_live coal,0.031564561242200716,12,3.1564561242200715,categorical,legal_move_signature_live coal
   14: R0_CURRENT_BASELINE,18,numeric__model_choice_required_flag,0.030994978973058095,13,3.0994978973058096,numeric,model_choice_required_flag
   15: R0_CURRENT_BASELINE,17,numeric__multi_legal_move_flag,0.028611627026524446,14,2.8611627026524444,numeric,multi_legal_move_flag
   16: R0_CURRENT_BASELINE,23,numeric__is_legal__quick_attack,0.028418312623468743,15,2.8418312623468744,numeric,is_legal__quick_attack
   17: R0_CURRENT_BASELINE,26,numeric__active_card_can_use__bind_down,0.026991251216699003,16,2.6991251216699004,numeric,active_card_can_use__bind_down
   18: R0_CURRENT_BASELINE,12,numeric__acting_damage,0.02688039693402022,17,2.688039693402022,numeric,acting_damage
   19: R0_CURRENT_BASELINE,7,numeric__recomputed_legal_move_count,0.025874350299871285,18,2.5874350299871285,numeric,recomputed_legal_move_count
   20: R0_CURRENT_BASELINE,61,categorical__damage_band_HIGH_DAMAGE,0.025206306720251016,19,2.5206306720251015,categorical,damage_band_HIGH_DAMAGE
   21: R0_CURRENT_BASELINE,50,categorical__legal_move_signature_ascension | quick attack,0.024727664212302127,20,2.4727664212302125,categorical,legal_move_signature_ascension | quick attack
   22: R0_CURRENT_BASELINE,14,numeric__damage_difference,0.024572521877175978,21,2.457252187717598,numeric,damage_difference
   23: R0_CURRENT_BASELINE,16,numeric__single_legal_move_flag,0.02428410197880131,22,2.428410197880131,numeric,single_legal_move_flag
   24: R0_CURRENT_BASELINE,54,categorical__legal_move_signature_tuck tail,0.02319413496166711,23,2.3194134961667108,categorical,legal_move_signature_tuck tail
   25: R0_CURRENT_BASELINE,24,numeric__is_legal__tuck_tail,0.02235945178974904,24,2.235945178974904,numeric,is_legal__tuck_tail
   26: R0_CURRENT_BASELINE,15,numeric__absolute_damage_difference,0.019286859905629526,25,1.9286859905629525,numeric,absolute_damage_difference
   27: R0_CURRENT_BASELINE,3,numeric__player_damage,0.012877161080213584,26,1.2877161080213584,numeric,player_damage
   28: R0_CURRENT_BASELINE,8,numeric__acting_energy,0.012824873033617432,27,1.2824873033617432,numeric,acting_energy
   29: R0_CURRENT_BASELINE,33,categorical__side_mode_FLIP,0.011944441800691178,28,1.194444180069118,categorical,side_mode_FLIP
   30: R0_CURRENT_BASELINE,47,categorical__inactive_card_Eevee,0.011718671772956997,29,1.1718671772956997,categorical,inactive_card_Eevee
   31: R0_CURRENT_BASELINE,25,numeric__active_card_can_use__ascension,0.010588879553898967,30,1.0588879553898967,numeric,active_card_can_use__ascension
   32: R0_CURRENT_BASELINE,43,categorical__active_card_Eevee,0.010387669879507785,31,1.0387669879507784,categorical,active_card_Eevee
   33: R0_CURRENT_BASELINE,29,numeric__active_card_can_use__quick_attack,0.009477987997493992,32,0.9477987997493992,numeric,active_card_can_use__quick_attack
   34: R0_CURRENT_BASELINE,2,numeric__opponent_energy,0.00914249325314893,33,0.914249325314893,numeric,opponent_energy
   35: R0_CURRENT_BASELINE,34,categorical__side_mode_PRESERVE,0.008857983410778727,34,0.8857983410778727,categorical,side_mode_PRESERVE
   36: R0_CURRENT_BASELINE,59,categorical__energy_band_READY,0.008131806014026412,35,0.8131806014026413,categorical,energy_band_READY
   37: R0_CURRENT_BASELINE,44,categorical__active_card_Meowth,0.007925693274709126,36,0.7925693274709126,categorical,active_card_Meowth
   38: R0_CURRENT_BASELINE,6,numeric__hand_size,0.007001490321288065,37,0.7001490321288064,numeric,hand_size
   39: R0_CURRENT_BASELINE,13,numeric__defending_damage,0.007000276011686795,38,0.7000276011686796,numeric,defending_damage
   40: R0_CURRENT_BASELINE,30,numeric__active_card_can_use__tuck_tail,0.0068625222977905945,39,0.6862522297790594,numeric,active_card_can_use__tuck_tail
   41: R0_CURRENT_BASELINE,58,categorical__energy_band_LOW,0.006843447273126755,40,0.6843447273126755,categorical,energy_band_LOW
   42: R0_CURRENT_BASELINE,35,categorical__player_card_Bulbasaur,0.006800404505808597,41,0.6800404505808597,categorical,player_card_Bulbasaur
   43: R0_CURRENT_BASELINE,0,numeric__turn_number,0.006311689883094547,42,0.6311689883094547,numeric,turn_number
   44: R0_CURRENT_BASELINE,1,numeric__player_energy,0.006211947941157503,43,0.6211947941157503,numeric,player_energy
   45: R0_CURRENT_BASELINE,60,categorical__energy_band_ZERO,0.006180617618801085,44,0.6180617618801085,categorical,energy_band_ZERO
   46: R0_CURRENT_BASELINE,9,numeric__defending_energy,0.0059299044397129064,45,0.5929904439712906,numeric,defending_energy
   47: R0_CURRENT_BASELINE,4,numeric__opponent_damage,0.005098140234767254,46,0.5098140234767254,numeric,opponent_damage
   48: R0_CURRENT_BASELINE,38,categorical__player_card_Meowth,0.004670039928174495,47,0.4670039928174495,categorical,player_card_Meowth
   49: R0_CURRENT_BASELINE,5,numeric__prize_cards_remaining,0.004122921991834085,48,0.41229219918340854,numeric,prize_cards_remaining
   50: R0_CURRENT_BASELINE,32,categorical__current_side_Player,0.002179479931220695,49,0.2179479931220695,categorical,current_side_Player
   51: R0_CURRENT_BASELINE,56,categorical__battle_phase_LATE,0.001844377406287528,50,0.18443774062875282,categorical,battle_phase_LATE

====================================================================================================
CANDIDATE 7
FILE: artifacts\notebook57\section3c_feature_type_importance.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_CURRENT_BASELINE,categorical,33,0.40961501741647127,0.012412576285347615,0.05449979700429139,40.961501741647126
    3: R0_CURRENT_BASELINE,numeric,31,0.5903849825835287,0.019044676857533183,0.04722155429519175,59.03849825835287

====================================================================================================
CANDIDATE 8
FILE: artifacts\notebook57\section3c_importance_concentration.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_CURRENT_BASELINE,64,0.05449979700429139,0.2286520128724599,0.4059966843301296,0.5591128308863851,0.8886778026445482,0.029286966315719504,34.144881693098384

====================================================================================================
CANDIDATE 9
FILE: artifacts\notebook57\section4a_ablation_transition_summary.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,6,0.21633009247497506,0.036055015412495846,0.05449979700429139,21.633009247497505

====================================================================================================
CANDIDATE 10
FILE: artifacts\notebook57\section4a_removed_feature_attribution.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_ascension,categorical,0.05449979700429139,5.449979700429139
    3: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_pass,categorical,0.04839845613686418,4.839845613686418
    4: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_bind down,categorical,0.03394547891764955,3.394547891764955
    5: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_live coal,categorical,0.031564561242200716,3.1564561242200715
    6: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_ascension | quick attack,categorical,0.024727664212302127,2.4727664212302125
    7: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,categorical__legal_move_signature_tuck tail,categorical,0.02319413496166711,2.3194134961667108

====================================================================================================
CANDIDATE 11
FILE: artifacts\notebook57\section4b_removed_importance_probability_drift.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_TO_R1,R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,legal_signature,6,0.21633009247497506,21.633009247497505,0.07242391304347827,0.072,0.118,0.1472391304347826,92,85,0,0.3347842744155265,0.6806225095651689,0.5,0.46195652173913043,0.0

====================================================================================================
CANDIDATE 12
FILE: artifacts\notebook57\section5a_case_drift_pair_summary.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,184,0.10693478260869567,0.108,0.168,0.21993478260869567,0.34,0
    3: R0_CURRENT_BASELINE,R1_REMOVE_LEGAL_SIGNATURE,184,0.07242391304347827,0.072,0.118,0.1472391304347826,0.23999999999999996,0
    4: R0_CURRENT_BASELINE,R2_REMOVE_SIGNATURE_AND_COMPATIBILITY,184,0.05647826086956522,0.050000000000000024,0.094,0.11580434782608695,0.19200000000000006,0

====================================================================================================
CANDIDATE 13
FILE: artifacts\notebook57\section5a_case_probability_drift.csv
MATCHED TERMS: ['baseline']
----------------------------------------------------------------------------------------------------
    2: 4WE_PAIR_014_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.168,0.05666666666666667,0.34,Quick Attack,Quick Attack,True,0.168,0.05666666666666667,0.34,1
    3: 4WE_PAIR_019_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.168,0.05666666666666667,0.34,Quick Attack,Quick Attack,True,0.168,0.05666666666666667,0.34,2
    4: 4WE_PAIR_002_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,3
    5: 4WE_PAIR_009_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,4
    6: 4WE_PAIR_013_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,5
    7: 4WE_PAIR_014_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,6
    8: 4WE_PAIR_018_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,7
    9: 4WE_PAIR_019_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.166,0.056,0.336,Quick Attack,Quick Attack,True,0.166,0.056,0.336,8
   10: 4WE_PAIR_002_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.056,0.336,Quick Attack,Quick Attack,True,0.164,0.056,0.336,9
   11: 4WE_PAIR_009_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.056,0.336,Quick Attack,Quick Attack,True,0.164,0.056,0.336,10
   12: 4WE_PAIR_001_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,11
   13: 4WE_PAIR_003_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,12
   14: 4WE_PAIR_008_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,13
   15: 4WE_PAIR_010_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,14
   16: 4WE_PAIR_013_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,15
   17: 4WE_PAIR_018_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.164,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.164,0.05533333333333334,0.332,16
   18: 4WE_PAIR_001_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.162,0.05533333333333334,0.332,17
   19: 4WE_PAIR_008_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05533333333333334,0.332,Quick Attack,Quick Attack,True,0.162,0.05533333333333334,0.332,18
   20: 4WE_PAIR_002_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,19
   21: 4WE_PAIR_003_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,20
   22: 4WE_PAIR_004_V03__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,21
   23: 4WE_PAIR_009_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,22
   24: 4WE_PAIR_010_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,23
   25: 4WE_PAIR_014_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,24
   26: 4WE_PAIR_014_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,25
   27: 4WE_PAIR_019_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,26
   28: 4WE_PAIR_019_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.162,0.05466666666666667,0.328,Quick Attack,Quick Attack,True,0.162,0.05466666666666667,0.328,27
   29: 4WE_PAIR_001_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,28
   30: 4WE_PAIR_004_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,29
   31: 4WE_PAIR_008_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,30
   32: 4WE_PAIR_013_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,31
   33: 4WE_PAIR_013_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,32
   34: 4WE_PAIR_018_V02__OPPONENT,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,33
   35: 4WE_PAIR_018_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.16,0.054,0.324,Quick Attack,Quick Attack,True,0.16,0.054,0.324,34
   36: 4WE_PAIR_002_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.158,0.054,0.324,Quick Attack,Quick Attack,True,0.158,0.054,0.324,35
   37: 4WE_PAIR_003_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.158,0.054,0.324,Quick Attack,Quick Attack,True,0.158,0.054,0.324,36
   38: 4WE_PAIR_003_V03__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.158,0.054,0.324,Quick Attack,Quick Attack,True,0.158,0.054,0.324,37
   39: 4WE_PAIR_009_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.158,0.054,0.324,Quick Attack,Quick Attack,True,0.158,0.054,0.324,38
   40: 4WE_PAIR_010_V02__PLAYER,R0_CURRENT_BASELINE,R3_STATE_CENTRIC_POLICY,0.158,0.054,0.324,Quick Attack,Quick Attack,True,0.158,0.054,0.324,39

,file,line_number,label,value,percent_symbol,source_line
0,outputs\notebook59\notebook59_r3_live_integrat...,31,win_rate,1.0,,"""win_rate"": 1.0"
1,outputs\notebook59\notebook59_r3_live_integrat...,38,win_rate,0.6666666666666666,,"""win_rate"": 0.6666666666666666"
2,outputs\notebook59\notebook59_r3_live_integrat...,45,win_rate,0.3333333333333333,,"""win_rate"": 0.3333333333333333"
3,outputs\notebook59\notebook59_r3_live_integrat...,52,win_rate,0.0,,"""win_rate"": 0.0"
4,artifacts\notebook59\notebook59_r3_live_integr...,31,win_rate,1.0,,"""win_rate"": 1.0"
...,...,...,...,...,...,...
4709,scripts\55_controlled_feature_ablation_retrain...,6076,second,3,,"f""{training_seconds:.3f}"","
4710,scripts\57_probability_attribution_and_feature...,472,first,15,,"f"" first columns={list(matrix_object.columns[..."
4711,scripts\57_probability_attribution_and_feature...,989,First,10,,"print(""\nFirst 10 positional differences:"")"
4712,scripts\59_live_competitive_evaluation.py,9749,FIRST,3,,# SECTION 7E.1 — RUN FIRST CONTROLLED MULTI-TU...
4713,scripts\59_live_competitive_evaluation.py,9753,FIRST,3,,"print(""SECTION 7E.1 — RUN FIRST CONTROLLED MUL..."

BENCHMARK-RELATED PROJECT FILES
----------------------------------------------------------------------------------------------------

                                                 file  size_bytes
0   artifacts\notebook56\notebook56_controlled_pol...      432142
1   artifacts\notebook58\notebook58_final_competit...       71062
2   artifacts\notebook55\notebook56\notebook56_con...      432142
3         reports\Notebook15\notebook15_benchmark.csv        1633
4        reports\notebook26\tournament_benchmark.json       38001
..                                                ...         ...
73  scripts\__pycache__\26_production_agent_benchm...       11382
74  scripts\__pycache__\32_mixed_opponent_self_pla...       50426
75  scripts\__pycache__\46_competitive_policy_data...      114063
76  scripts\__pycache__\47_competitive_policy_trai...       95131
77  scripts\__pycache__\48_tournament_evaluation_a...       79899

[78 rows x 2 columns]

====================================================================================================
✅ PROJECT OUTPUTS SEARCHED
✅ PROJECT ARTIFACTS SEARCHED
✅ PROJECT REPORTS SEARCHED
✅ PROJECT SCRIPTS SEARCHED
✅ BASELINE / BENCHMARK REFERENCES COLLECTED
✅ PERCENTAGE-LIKE CANDIDATES COLLECTED
✅ SECTION 1B COMPLETE
====================================================================================================

In [3]:
# ==========================================================================================
# SECTION 1C — RESOLVE AUTHORITATIVE HISTORICAL COMPETITIVE BASELINE
# ==========================================================================================

print("=" * 100)
print("SECTION 1C — RESOLVE AUTHORITATIVE HISTORICAL COMPETITIVE BASELINE")
print("=" * 100)

from pathlib import Path
import re
import pandas as pd


# ==========================================================================================
# 1. Prioritize later competitive notebooks/scripts
# ==========================================================================================

PRIORITY_NOTEBOOK_NUMBERS_1C = list(range(48, 59))

priority_files_1c = []

for base_dir in [
    PROJECT_ROOT / "outputs",
    PROJECT_ROOT / "artifacts",
    PROJECT_ROOT / "reports",
    PROJECT_ROOT / "scripts",
]:

    if not base_dir.exists():
        continue

    for path in base_dir.rglob("*"):

        if not path.is_file():
            continue

        if "__pycache__" in path.parts:
            continue

        if path.suffix.lower() not in {
            ".py",
            ".txt",
            ".json",
            ".csv",
            ".md",
        }:
            continue

        relative = str(path.relative_to(PROJECT_ROOT)).lower()

        notebook_match = re.search(
            r"(?:notebook|^|\\)(\d{2})[_\\]",
            relative
        )

        notebook_number = None

        if notebook_match:
            try:
                notebook_number = int(notebook_match.group(1))
            except Exception:
                pass

        if (
            notebook_number in PRIORITY_NOTEBOOK_NUMBERS_1C
            or any(
                f"notebook{n}" in relative
                or f"\\{n}_" in relative
                for n in PRIORITY_NOTEBOOK_NUMBERS_1C
            )
        ):
            priority_files_1c.append(path)


priority_files_1c = sorted(set(priority_files_1c))

print(f"\nPriority files found: {len(priority_files_1c)}")


# ==========================================================================================
# 2. Look specifically for competitive win-rate language
# ==========================================================================================

TARGET_PATTERNS_1C = [
    r"side[\s_-]*neutral",
    r"first[\s_-]*(?:side|player|win|rate)",
    r"second[\s_-]*(?:side|player|win|rate)",
    r"player[\s_-]*first",
    r"opponent[\s_-]*first",
    r"starting[\s_-]*side",
    r"win[\s_-]*rate",
    r"competitive[\s_-]*(?:win|rate|evaluation|benchmark)",
    r"tournament[\s_-]*(?:win|rate|evaluation|benchmark)",
]

compiled_patterns_1c = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in TARGET_PATTERNS_1C
]


candidate_rows_1c = []

for path in priority_files_1c:

    try:
        text = path.read_text(
            encoding="utf-8-sig",
            errors="ignore"
        )
    except Exception:
        continue

    lines = text.splitlines()

    for line_number, line in enumerate(lines, start=1):

        if not any(
            pattern.search(line)
            for pattern in compiled_patterns_1c
        ):
            continue

        # Require some numerical evidence.
        numbers = re.findall(
            r"(?<![\w.])\d+(?:\.\d+)?%?",
            line
        )

        if not numbers:
            continue

        candidate_rows_1c.append(
            {
                "file": str(path.relative_to(PROJECT_ROOT)),
                "line_number": line_number,
                "source_line": line.strip(),
            }
        )


section1c_candidates_df = pd.DataFrame(candidate_rows_1c)


print("\nCOMPETITIVE BASELINE CANDIDATES")
print("-" * 100)

if section1c_candidates_df.empty:

    print("No competitive baseline candidates found.")

else:

    display(
        section1c_candidates_df
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 3. Search explicitly for the known historical neighborhood
#
# Earlier project evidence placed the benchmark approximately around:
#   side-neutral ≈ mid-60%
#   first        ≈ mid/high-80%
#   second       ≈ low-40%
#
# IMPORTANT:
# These ranges are ONLY search filters.
# They are NOT being declared as Notebook 60 baseline values.
# ==========================================================================================

historical_value_rows_1c = []

for path in priority_files_1c:

    try:
        text = path.read_text(
            encoding="utf-8-sig",
            errors="ignore"
        )
    except Exception:
        continue

    lines = text.splitlines()

    for line_number, line in enumerate(lines, start=1):

        line_lower = line.lower()

        if not any(
            key in line_lower
            for key in [
                "side-neutral",
                "side neutral",
                "side_neutral",
                "first",
                "second",
                "win rate",
                "win_rate",
            ]
        ):
            continue

        numeric_tokens = re.findall(
            r"\d+(?:\.\d+)?",
            line
        )

        numeric_values = []

        for token in numeric_tokens:

            try:
                numeric_values.append(float(token))
            except Exception:
                pass

        # Detect either percentages (e.g. 64.67)
        # or proportions (e.g. 0.6467).
        plausible = any(
            (
                35.0 <= value <= 95.0
                or 0.35 <= value <= 0.95
            )
            for value in numeric_values
        )

        if plausible:

            historical_value_rows_1c.append(
                {
                    "file": str(
                        path.relative_to(PROJECT_ROOT)
                    ),
                    "line_number": line_number,
                    "source_line": line.strip(),
                }
            )


section1c_historical_values_df = pd.DataFrame(
    historical_value_rows_1c
)


print("\nPLAUSIBLE HISTORICAL COMPETITIVE VALUES")
print("-" * 100)

if section1c_historical_values_df.empty:

    print("No plausible historical values found.")

else:

    display(
        section1c_historical_values_df
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 4. Rank source files by evidence density
# ==========================================================================================

if not section1c_historical_values_df.empty:

    section1c_source_ranking_df = (
        section1c_historical_values_df
        .groupby("file")
        .size()
        .reset_index(name="matching_lines")
        .sort_values(
            "matching_lines",
            ascending=False
        )
        .reset_index(drop=True)
    )

else:

    section1c_source_ranking_df = pd.DataFrame(
        columns=[
            "file",
            "matching_lines",
        ]
    )


print("\nSOURCE EVIDENCE RANKING")
print("-" * 100)

display(section1c_source_ranking_df.head(30))


# ==========================================================================================
# 5. Print top source evidence in readable form
# ==========================================================================================

print("\nTOP SOURCE EVIDENCE")
print("-" * 100)

if not section1c_source_ranking_df.empty:

    top_sources_1c = (
        section1c_source_ranking_df
        .head(10)["file"]
        .tolist()
    )

    for source in top_sources_1c:

        print("\n" + "=" * 100)
        print(source)
        print("-" * 100)

        source_rows = (
            section1c_historical_values_df[
                section1c_historical_values_df["file"]
                == source
            ]
            .head(30)
        )

        for _, row in source_rows.iterrows():

            print(
                f"{int(row['line_number']):>6}: "
                f"{row['source_line']}"
            )


# ==========================================================================================
# 6. Validation
# ==========================================================================================

section1c_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "priority competitive files found",
            "observed":
                len(priority_files_1c),
            "passed":
                len(priority_files_1c) > 0,
        },
        {
            "validation":
                "competitive candidate lines found",
            "observed":
                len(section1c_candidates_df),
            "passed":
                len(section1c_candidates_df) > 0,
        },
        {
            "validation":
                "historical value candidates found",
            "observed":
                len(section1c_historical_values_df),
            "passed":
                len(section1c_historical_values_df) > 0,
        },
    ]
)


print("\nSECTION 1C VALIDATION")
print("-" * 100)

display(section1c_validation_df)


print("\n" + "=" * 100)

if section1c_validation_df["passed"].all():

    print("✅ PRIORITY COMPETITIVE HISTORY RECOVERED")
    print("✅ NUMERICAL BENCHMARK EVIDENCE FOUND")
    print("✅ READY TO LOCK AUTHORITATIVE BASELINE")

else:

    print("⚠️ ADDITIONAL BASELINE RECOVERY REQUIRED")

print("✅ SECTION 1C COMPLETE")
print("=" * 100)

====================================================================================================
SECTION 1C — RESOLVE AUTHORITATIVE HISTORICAL COMPETITIVE BASELINE
====================================================================================================

Priority files found: 888

COMPETITIVE BASELINE CANDIDATES
----------------------------------------------------------------------------------------------------

,file,line_number,source_line
0,reports\notebook48\competitive_policy_baseline...,6,"""competitive_wins"": 194,"
1,reports\notebook48\competitive_policy_baseline...,10,"""overall_win_rate"": 0.6466666666666666,"
2,reports\notebook48\competitive_policy_baseline...,19,"""competitive_wins"": 58,"
3,reports\notebook48\competitive_policy_baseline...,27,"""win_rate"": 0.58,"
4,reports\notebook48\competitive_policy_baseline...,34,"""competitive_wins"": 58,"
...,...,...,...
130,scripts\53_legality_aware_policy_optimization.py,13507,# #### This section evaluates the Notebook 53 ...
131,scripts\53_legality_aware_policy_optimization.py,21237,"""Improve tournament win rate while preserving ..."
132,scripts\54_tournament_strength_optimization_cl...,23,# 1. Improve tournament win rate.
133,scripts\54_tournament_strength_optimization_CO...,23,# 1. Improve tournament win rate.
134,scripts\54_tournament_strength_optimization_CO...,23,# 1. Improve tournament win rate.

PLAUSIBLE HISTORICAL COMPETITIVE VALUES
----------------------------------------------------------------------------------------------------

,file,line_number,source_line
0,reports\notebook48\competitive_policy_baseline...,10,"""overall_win_rate"": 0.6466666666666666,"
1,reports\notebook48\competitive_policy_baseline...,27,"""win_rate"": 0.58,"
2,reports\notebook48\competitive_policy_baseline...,42,"""win_rate"": 0.58,"
3,reports\notebook48\competitive_policy_baseline...,57,"""win_rate"": 0.78,"
4,reports\notebook48\competitive_policy_baseline...,83,"""win_rate"": 0.84"
...,...,...,...
4446,scripts\54_tournament_strength_optimization_cl...,67941,"""Run the permanent Notebook 54 report-path cel..."
4447,scripts\54_tournament_strength_optimization_CO...,40294,"""Rerun the Notebook 53 adapter-loading section..."
4448,scripts\54_tournament_strength_optimization_CO...,67941,"""Run the permanent Notebook 54 report-path cel..."
4449,scripts\54_tournament_strength_optimization_CO...,40294,"""Rerun the Notebook 53 adapter-loading section..."
4450,scripts\54_tournament_strength_optimization_CO...,67941,"""Run the permanent Notebook 54 report-path cel..."

SOURCE EVIDENCE RANKING
----------------------------------------------------------------------------------------------------

                                                 file  matching_lines
0   reports\notebook49\section8\batch_search\secti...            1060
1   reports\notebook49\section8\policy_dataset\sec...            1060
2   reports\notebook53\section4\section4b_legality...            1060
3   reports\notebook50\section2\dataset_splits\sec...             740
4   reports\notebook50\section2\dataset_splits\sec...             160
5   reports\notebook50\section2\dataset_splits\sec...             160
6   reports\notebook54\section3\section3b_discover...              76
7   reports\notebook50\section1\environment_and_ha...              20
8   reports\notebook54\section4\section4e_tourname...              10
9   reports\notebook48\competitive_policy_baseline...               8
10  reports\notebook54\section3\section3b_structur...               7
11  reports\notebook48\competitive_policy_elo_summ...               7
12  reports\notebook48\final_competitive_strength_...               6
13  scripts\48_tournament_evaluation_and_elo_bench...               6
14  reports\notebook54\section4\section4f_upstream...               5
15  reports\notebook54\section4\section4d_strict_c...               4
16  reports\notebook51\section7\section7a_artifact...               4
17  reports\notebook48\final_competitive_recommend...               4
18  reports\notebook54\section3\section3b_structur...               4
19  reports\notebook52\section6\section6b_benchmar...               3
20  reports\notebook52\section7\section7a_final_to...               3
21  reports\notebook52\section6\section6a_dashboar...               3
22  reports\notebook54\section4\section4j_upstream...               3
23  reports\notebook52\section7\section7a_handoff_...               3
24  reports\notebook48\final_competitive_strength_...               3
25  reports\notebook52\section4\analysis\section4b...               2
26  scripts\49_side_balanced_search_guided_self_pl...               2
27  scripts\54_tournament_strength_optimization_cl...               2
28  scripts\54_tournament_strength_optimization_CO...               2
29  scripts\54_tournament_strength_optimization_CO...               2

TOP SOURCE EVIDENCE
----------------------------------------------------------------------------------------------------

====================================================================================================
reports\notebook49\section8\batch_search\section8b_search_labels.csv
----------------------------------------------------------------------------------------------------
     2: NB48_LOSS_10__balanced_midgame__b38b454597c7,NB48_LOSS_10,balanced_midgame,PRESERVE,Opponent,Opponent,Opponent,Random Baseline,Bulbasaur,Eevee,5,2,2,20.0,12.5,4,5,1,"[""Ascension""]",4,0.005650399980368093,SearchResult,src.engine.advanced_search,Ascension,"[""Ascension"", 0.0, 1, ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""]",-40.0,4,,False,"[{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}]","[[[[""650"", ""Bulbasaur""], 60.0, 2, ""None"", 20.0, true], [], 4, 5], [[[""43"", ""Eevee""], 37.5, 2, ""None"", 12.5, true], [], 4, 5], 5, ""Opponent""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, ""score"": -40.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 5, ""leaf_nodes"": 1, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 0, ""transposition_stores"": 4, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0004875999875366688, ""depth_nodes"": {""4"": 5}, ""depth_times"": {""4"": 0.0004875999875366688}}}}}",COMPLETED
     3: NB48_LOSS_10__counterfactual_side_early__d862febbde1a,NB48_LOSS_10,counterfactual_side_early,FLIP,Opponent,Player,Player,Random Baseline,Bulbasaur,Eevee,3,1,1,8.0,5.0,5,6,1,"[""Bind Down""]",4,0.006234500004211441,SearchResult,src.engine.advanced_search,Bind Down,"[""Bind Down"", 10.0, 1, ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""]",40.0,4,,False,"[{""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}]","[[[[""650"", ""Bulbasaur""], 72.0, 1, ""None"", 8.0, true], [], 5, 6], [[[""43"", ""Eevee""], 45.0, 1, ""None"", 5.0, true], [], 5, 6], 3, ""Player""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, ""score"": 40.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 5, ""leaf_nodes"": 1, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 0, ""transposition_stores"": 4, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0004838000168092549, ""depth_nodes"": {""4"": 5}, ""depth_times"": {""4"": 0.0004838000168092549}}}}}",COMPLETED
     4: NB48_LOSS_10__counterfactual_side_late__8c8e50dd4698,NB48_LOSS_10,counterfactual_side_late,FLIP,Opponent,Player,Player,Random Baseline,Bulbasaur,Eevee,8,3,3,36.0,22.5,3,4,1,"[""Bind Down""]",4,0.006172699999297038,SearchResult,src.engine.advanced_search,Bind Down,"[""Bind Down"", 10.0, 1, ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""]",-10.0,4,,False,"[{""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}]","[[[[""650"", ""Bulbasaur""], 44.0, 3, ""None"", 36.0, true], [], 3, 4], [[[""43"", ""Eevee""], 27.5, 3, ""None"", 22.5, true], [], 3, 4], 8, ""Player""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, ""score"": -10.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 10, ""leaf_nodes"": 4, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 0, ""transposition_stores"": 6, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0010363000037614256, ""depth_nodes"": {""4"": 10}, ""depth_times"": {""4"": 0.0010363000037614256}}}}}",COMPLETED
     5: NB48_LOSS_10__critical_hp_decision__437af3f25399,NB48_LOSS_10,critical_hp_decision,PRESERVE,Opponent,Opponent,Opponent,Random Baseline,Bulbasaur,Eevee,10,4,4,56.0,27.5,2,3,2,"[""Ascension"", ""Quick Attack""]",4,0.006461700017098337,SearchResult,src.engine.advanced_search,Quick Attack,"[""Quick Attack"", 20.0, 3, ""Flip a coin. If heads, this attack does 20 more damage.""]",565.0,4,,False,"[{""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}]","[[[[""650"", ""Bulbasaur""], 24.0, 4, ""None"", 56.0, true], [], 2, 3], [[[""43"", ""Eevee""], 22.5, 4, ""None"", 27.5, true], [], 2, 3], 10, ""Opponent""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, ""score"": 565.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 11, ""leaf_nodes"": 2, ""terminal_nodes"": 1, ""cutoffs"": 0, ""transposition_hits"": 1, ""transposition_stores"": 7, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0011254000128246844, ""depth_nodes"": {""4"": 11}, ""depth_times"": {""4"": 0.0011254000128246844}}}}}",COMPLETED
     6: NB48_LOSS_10__early_pressure__86616f3937c2,NB48_LOSS_10,early_pressure,PRESERVE,Opponent,Opponent,Opponent,Random Baseline,Bulbasaur,Eevee,3,1,2,12.0,2.5,5,6,1,"[""Ascension""]",4,0.006606900016777217,SearchResult,src.engine.advanced_search,Ascension,"[""Ascension"", 0.0, 1, ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""]",-22.0,4,,False,"[{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}]","[[[[""650"", ""Bulbasaur""], 68.0, 1, ""None"", 12.0, true], [], 5, 6], [[[""43"", ""Eevee""], 47.5, 2, ""None"", 2.5, true], [], 5, 6], 3, ""Opponent""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, ""score"": -22.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 5, ""leaf_nodes"": 1, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 0, ""transposition_stores"": 4, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0004928000271320343, ""depth_nodes"": {""4"": 5}, ""depth_times"": {""4"": 0.0004928000271320343}}}}}",COMPLETED
     7: NB48_LOSS_10__late_game_prize_pressure__7a59d0987687,NB48_LOSS_10,late_game_prize_pressure,PRESERVE,Opponent,Opponent,Opponent,Random Baseline,Bulbasaur,Eevee,9,3,3,32.0,20.0,2,3,2,"[""Ascension"", ""Quick Attack""]",4,0.006451399996876717,SearchResult,src.engine.advanced_search,Quick Attack,"[""Quick Attack"", 20.0, 3, ""Flip a coin. If heads, this attack does 20 more damage.""]",10.0,4,,False,"[{""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}]","[[[[""650"", ""Bulbasaur""], 48.0, 3, ""None"", 32.0, true], [], 2, 3], [[[""43"", ""Eevee""], 30.0, 3, ""None"", 20.0, true], [], 2, 3], 9, ""Opponent""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, ""score"": 10.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Quick Attack"", ""damage"": 20.0, ""energy_cost"": 3, ""effect"": ""Flip a coin. If heads, this attack does 20 more damage.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 12, ""leaf_nodes"": 3, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 1, ""transposition_stores"": 8, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.0012670999858528376, ""depth_nodes"": {""4"": 12}, ""depth_times"": {""4"": 0.0012670999858528376}}}}}",COMPLETED
     8: NB48_LOSS_10__opening_one_energy__1ebb255cddbe,NB48_LOSS_10,opening_one_energy,PRESERVE,Opponent,Opponent,Opponent,Random Baseline,Bulbasaur,Eevee,2,1,1,0.0,0.0,6,6,1,"[""Ascension""]",4,0.005609799991361797,SearchResult,src.engine.advanced_search,Ascension,"[""Ascension"", 0.0, 1, ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""]",-40.0,4,,False,"[{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}]","[[[[""650"", ""Bulbasaur""], 80.0, 1, ""None"", 0.0, true], [], 6, 6], [[[""43"", ""Eevee""], 50.0, 1, ""None"", 0.0, true], [], 6, 6], 2, ""Opponent""]","{""__type__"": ""SearchResult"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""best_move"": {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, ""score"": -40.0, ""completed_depth"": 4, ""principal_variation"": [{""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}, {""name"": ""Ascension"", ""damage"": 0.0, ""energy_cost"": 1, ""effect"": ""Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon to evolve it. Then, shuffle your deck.""}, {""name"": ""Bind Down"", ""damage"": 10.0, ""energy_cost"": 1, ""effect"": ""During your opponent’s next turn, the Defending Pokémon can’t retreat.""}], ""stats"": {""__type__"": ""SearchStats"", ""__module__"": ""src.engine.advanced_search"", ""attributes"": {""nodes"": 5, ""leaf_nodes"": 1, ""terminal_nodes"": 0, ""cutoffs"": 0, ""transposition_hits"": 0, ""transposition_stores"": 4, ""transposition_cutoffs"": 0, ""killer_hits"": 0, ""killer_stores"": 0, ""history_hits"": 0, ""history_updates"": 0, ""completed_depth"": 4, ""elapsed_seconds"": 0.00048749998677521944, ""depth_nodes"": {""4"": 5}, ""depth_times"": {""4"": 0.00048749998677521944}}}}}",COMPLETED

                          validation  observed  passed
0   priority competitive files found       888    True
1  competitive candidate lines found       135    True
2  historical value candidates found      4451    True

====================================================================================================
✅ PRIORITY COMPETITIVE HISTORY RECOVERED
✅ NUMERICAL BENCHMARK EVIDENCE FOUND
✅ READY TO LOCK AUTHORITATIVE BASELINE
✅ SECTION 1C COMPLETE
====================================================================================================

In [6]:
# ==========================================================================================
# SECTION 1D — LOAD AND FREEZE AUTHORITATIVE NOTEBOOK 48 COMPETITIVE BASELINE
# ==========================================================================================

print("=" * 100)
print("SECTION 1D — LOAD AND FREEZE AUTHORITATIVE NOTEBOOK 48 COMPETITIVE BASELINE")
print("=" * 100)

from pathlib import Path
import json
import pandas as pd


# ------------------------------------------------------------------------------------------
# 1. Locate authoritative Notebook 48 baseline report
# ------------------------------------------------------------------------------------------

NOTEBOOK48_BASELINE_FILE = (
    PROJECT_ROOT
    / "reports"
    / "notebook48"
    / "competitive_policy_baseline_tournament_summary.json"
)

print("\nAUTHORITATIVE BASELINE SOURCE")
print("-" * 100)
print(NOTEBOOK48_BASELINE_FILE)

assert NOTEBOOK48_BASELINE_FILE.exists(), (
    f"Notebook 48 baseline file not found: "
    f"{NOTEBOOK48_BASELINE_FILE}"
)

assert NOTEBOOK48_BASELINE_FILE.stat().st_size > 0


# ------------------------------------------------------------------------------------------
# 2. Load original report exactly as stored
# ------------------------------------------------------------------------------------------

with open(
    NOTEBOOK48_BASELINE_FILE,
    "r",
    encoding="utf-8",
) as file:

    notebook48_baseline_raw = json.load(file)


print("\nTOP-LEVEL NOTEBOOK 48 BASELINE CONTENT")
print("-" * 100)

for key, value in notebook48_baseline_raw.items():

    if isinstance(
        value,
        (dict, list),
    ):
        print(
            f"{key:35}: "
            f"{type(value).__name__}"
        )

    else:
        print(
            f"{key:35}: {value}"
        )


# ------------------------------------------------------------------------------------------
# 3. Recursively flatten report
#
# This prevents us from guessing what the 0.58, 0.78, 0.84, 0.92 values mean.
# We preserve their exact JSON paths.
# ------------------------------------------------------------------------------------------

def flatten_json_1d(
    obj,
    parent_path="root",
):

    rows = []

    if isinstance(obj, dict):

        for key, value in obj.items():

            child_path = (
                f"{parent_path}.{key}"
            )

            rows.extend(
                flatten_json_1d(
                    value,
                    child_path,
                )
            )

    elif isinstance(obj, list):

        for index, value in enumerate(obj):

            child_path = (
                f"{parent_path}[{index}]"
            )

            rows.extend(
                flatten_json_1d(
                    value,
                    child_path,
                )
            )

    else:

        rows.append(
            {
                "json_path": parent_path,
                "value": obj,
                "value_type":
                    type(obj).__name__,
            }
        )

    return rows


notebook48_flat_df = pd.DataFrame(
    flatten_json_1d(
        notebook48_baseline_raw
    )
)


print("\nFLATTENED NOTEBOOK 48 BASELINE")
print("-" * 100)

display(
    notebook48_flat_df
)


# ------------------------------------------------------------------------------------------
# 4. Extract all rate / side / win / battle fields
# ------------------------------------------------------------------------------------------

benchmark_keywords_1d = [
    "win",
    "rate",
    "first",
    "second",
    "side",
    "battle",
    "match",
    "draw",
    "loss",
]

benchmark_mask_1d = (
    notebook48_flat_df[
        "json_path"
    ]
    .str.lower()
    .apply(
        lambda path:
            any(
                keyword in path
                for keyword
                in benchmark_keywords_1d
            )
    )
)

notebook48_benchmark_fields_df = (
    notebook48_flat_df[
        benchmark_mask_1d
    ]
    .copy()
    .reset_index(drop=True)
)


print("\nNOTEBOOK 48 COMPETITIVE BENCHMARK FIELDS")
print("-" * 100)

display(
    notebook48_benchmark_fields_df
)


# ------------------------------------------------------------------------------------------
# 5. Confirm authoritative overall baseline
# ------------------------------------------------------------------------------------------

assert "overall_win_rate" in notebook48_baseline_raw, (
    "overall_win_rate missing from Notebook 48 baseline report."
)

NOTEBOOK48_OVERALL_WIN_RATE = float(
    notebook48_baseline_raw[
        "overall_win_rate"
    ]
)

assert (
    0.0
    <= NOTEBOOK48_OVERALL_WIN_RATE
    <= 1.0
)

print("\nAUTHORITATIVE HISTORICAL OVERALL WIN RATE")
print("-" * 100)

print(
    f"Notebook 48 overall win rate : "
    f"{NOTEBOOK48_OVERALL_WIN_RATE:.6f}"
)

print(
    f"Notebook 48 overall win rate : "
    f"{NOTEBOOK48_OVERALL_WIN_RATE:.2%}"
)


# ------------------------------------------------------------------------------------------
# 6. Preserve complete source report inside Notebook 60
# ------------------------------------------------------------------------------------------

NOTEBOOK60_BASELINE_COPY_FILE = (
    REPORTS_60_DIR
    / "section1d_notebook48_authoritative_baseline.json"
)

NOTEBOOK60_BASELINE_FIELDS_FILE = (
    REPORTS_60_DIR
    / "section1d_notebook48_baseline_fields.csv"
)

NOTEBOOK60_BASELINE_SUMMARY_FILE = (
    REPORTS_60_DIR
    / "section1d_baseline_lock_summary.json"
)


with open(
    NOTEBOOK60_BASELINE_COPY_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        notebook48_baseline_raw,
        file,
        indent=2,
        ensure_ascii=False,
    )


notebook48_benchmark_fields_df.to_csv(
    NOTEBOOK60_BASELINE_FIELDS_FILE,
    index=False,
)


notebook60_baseline_lock_summary = {
    "source_notebook": 48,
    "source_file":
        str(NOTEBOOK48_BASELINE_FILE),
    "baseline_type":
        "competitive_policy_baseline_tournament",
    "overall_win_rate":
        NOTEBOOK48_OVERALL_WIN_RATE,
    "overall_win_rate_percent":
        NOTEBOOK48_OVERALL_WIN_RATE * 100.0,
    "baseline_locked":
        True,
    "r3_model_modified":
        False,
    "r3_retrained":
        False,
}


with open(
    NOTEBOOK60_BASELINE_SUMMARY_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        notebook60_baseline_lock_summary,
        file,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------------------------------------
# 7. Validate saved evidence
# ------------------------------------------------------------------------------------------

section1d_saved_files = [
    NOTEBOOK60_BASELINE_COPY_FILE,
    NOTEBOOK60_BASELINE_FIELDS_FILE,
    NOTEBOOK60_BASELINE_SUMMARY_FILE,
]

section1d_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 48 baseline source exists",
            "passed":
                NOTEBOOK48_BASELINE_FILE.exists(),
        },
        {
            "validation":
                "overall win rate recovered",
            "passed":
                0.0
                <= NOTEBOOK48_OVERALL_WIN_RATE
                <= 1.0,
        },
        {
            "validation":
                "historical baseline copied to NB60",
            "passed":
                NOTEBOOK60_BASELINE_COPY_FILE.exists(),
        },
        {
            "validation":
                "benchmark field inventory saved",
            "passed":
                NOTEBOOK60_BASELINE_FIELDS_FILE.exists(),
        },
        {
            "validation":
                "baseline lock summary saved",
            "passed":
                NOTEBOOK60_BASELINE_SUMMARY_FILE.exists(),
        },
    ]
)


print("\nSECTION 1D VALIDATION")
print("-" * 100)

display(
    section1d_validation_df
)


assert section1d_validation_df[
    "passed"
].all()


print("\nSAVED NOTEBOOK 60 BASELINE EVIDENCE")
print("-" * 100)

for file_path in section1d_saved_files:

    print(file_path)


print("\n" + "=" * 100)
print("✅ NOTEBOOK 48 AUTHORITATIVE BASELINE LOADED")
print(
    f"✅ HISTORICAL OVERALL WIN RATE LOCKED: "
    f"{NOTEBOOK48_OVERALL_WIN_RATE:.2%}"
)
print("✅ COMPLETE BASELINE STRUCTURE PRESERVED")
print("✅ NO R3 RETRAINING OR MODEL MODIFICATION")
print("✅ SECTION 1D COMPLETE")
print("=" * 100)

====================================================================================================
SECTION 1D — LOAD AND FREEZE AUTHORITATIVE NOTEBOOK 48 COMPETITIVE BASELINE
====================================================================================================

AUTHORITATIVE BASELINE SOURCE
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook48\competitive_policy_baseline_tournament_summary.json

TOP-LEVEL NOTEBOOK 48 BASELINE CONTENT
----------------------------------------------------------------------------------------------------
scheduled_matches                  : 300
successful_matches                 : 300
failed_matches                     : 0
matches_per_baseline               : 100
competitive_wins                   : 194
competitive_losses                 : 106
draws                              : 0
overall_score                      : 0.6466666666666666
overall_win_rate                   : 0.6466666666666666
average_turns                      : 3.533333333333333
fallback_count                     : 0
elapsed_seconds                    : 2.0785619999514893
matches_per_second                 : 144.3305516058706
baseline_results                   : list
side_results                       : list
results_file                       : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\data\tournaments\competitive_policy_baseline_tournament.csv
failure_file                       : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook48\competitive_policy_baseline_tournament_failures.json

FLATTENED NOTEBOOK 48 BASELINE
----------------------------------------------------------------------------------------------------

,json_path,value,value_type
0,root.scheduled_matches,300,int
1,root.successful_matches,300,int
2,root.failed_matches,0,int
3,root.matches_per_baseline,100,int
4,root.competitive_wins,194,int
...,...,...,...
103,root.side_results[5].score,0.92,float
104,root.side_results[5].average_turns,3.42,float
105,root.side_results[5].win_rate,0.92,float
106,root.results_file,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,str
107,root.failure_file,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,str

NOTEBOOK 48 COMPETITIVE BENCHMARK FIELDS
----------------------------------------------------------------------------------------------------

                             json_path value value_type
0               root.scheduled_matches   300        int
1              root.successful_matches   300        int
2                  root.failed_matches     0        int
3            root.matches_per_baseline   100        int
4                root.competitive_wins   194        int
..                                 ...   ...        ...
83         root.side_results[5].losses     4        int
84          root.side_results[5].draws     0        int
85          root.side_results[5].score  0.92      float
86  root.side_results[5].average_turns  3.42      float
87       root.side_results[5].win_rate  0.92      float

[88 rows x 3 columns]

AUTHORITATIVE HISTORICAL OVERALL WIN RATE
----------------------------------------------------------------------------------------------------
Notebook 48 overall win rate : 0.646667
Notebook 48 overall win rate : 64.67%

SECTION 1D VALIDATION
----------------------------------------------------------------------------------------------------

                           validation  passed
0  Notebook 48 baseline source exists    True
1          overall win rate recovered    True
2  historical baseline copied to NB60    True
3     benchmark field inventory saved    True
4         baseline lock summary saved    True

SAVED NOTEBOOK 60 BASELINE EVIDENCE
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section1d_notebook48_authoritative_baseline.json
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section1d_notebook48_baseline_fields.csv
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section1d_baseline_lock_summary.json

====================================================================================================
✅ NOTEBOOK 48 AUTHORITATIVE BASELINE LOADED
✅ HISTORICAL OVERALL WIN RATE LOCKED: 64.67%
✅ COMPLETE BASELINE STRUCTURE PRESERVED
✅ NO R3 RETRAINING OR MODEL MODIFICATION
✅ SECTION 1D COMPLETE
====================================================================================================

In [5]:
# ==========================================================================================
# SECTION 1D.1 — REPAIR NOTEBOOK 60 REPORT DIRECTORY ALIAS
# ==========================================================================================

REPORTS_60_DIR = NOTEBOOK60_REPORT_DIR

print("REPORTS_60_DIR:")
print(REPORTS_60_DIR)

assert REPORTS_60_DIR.exists()

print("✅ NOTEBOOK 60 REPORT DIRECTORY ALIAS RESTORED")
print("✅ SECTION 1D.1 COMPLETE")

REPORTS_60_DIR:
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60
✅ NOTEBOOK 60 REPORT DIRECTORY ALIAS RESTORED
✅ SECTION 1D.1 COMPLETE

In [7]:
# ==========================================================================================
# SECTION 2A — RECONSTRUCT AUTHORITATIVE NOTEBOOK 48 BENCHMARK DESIGN
# ==========================================================================================

print("=" * 100)
print("SECTION 2A — RECONSTRUCT AUTHORITATIVE NOTEBOOK 48 BENCHMARK DESIGN")
print("=" * 100)

import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Confirm locked historical experiment dimensions
# ==========================================================================================

historical_scheduled_matches_2a = int(
    notebook48_baseline_raw[
        "scheduled_matches"
    ]
)

historical_successful_matches_2a = int(
    notebook48_baseline_raw[
        "successful_matches"
    ]
)

historical_failed_matches_2a = int(
    notebook48_baseline_raw[
        "failed_matches"
    ]
)

historical_matches_per_baseline_2a = int(
    notebook48_baseline_raw[
        "matches_per_baseline"
    ]
)


print("\nHISTORICAL EXPERIMENT SIZE")
print("-" * 100)

print(
    "Scheduled matches       :",
    historical_scheduled_matches_2a,
)

print(
    "Successful matches      :",
    historical_successful_matches_2a,
)

print(
    "Failed matches          :",
    historical_failed_matches_2a,
)

print(
    "Matches per baseline    :",
    historical_matches_per_baseline_2a,
)


# ==========================================================================================
# 2. Inspect baseline_results exactly
# ==========================================================================================

baseline_results_raw_2a = (
    notebook48_baseline_raw[
        "baseline_results"
    ]
)

print("\nBASELINE RESULT RECORD COUNT")
print("-" * 100)

print(
    len(
        baseline_results_raw_2a
    )
)


section2a_baseline_results_df = pd.DataFrame(
    baseline_results_raw_2a
)


print("\nAUTHORITATIVE BASELINE RESULTS")
print("-" * 100)

display(
    section2a_baseline_results_df
)


# ==========================================================================================
# 3. Inspect side_results exactly
# ==========================================================================================

side_results_raw_2a = (
    notebook48_baseline_raw[
        "side_results"
    ]
)

print("\nSIDE RESULT RECORD COUNT")
print("-" * 100)

print(
    len(
        side_results_raw_2a
    )
)


section2a_side_results_df = pd.DataFrame(
    side_results_raw_2a
)


print("\nAUTHORITATIVE SIDE RESULTS")
print("-" * 100)

display(
    section2a_side_results_df
)


# ==========================================================================================
# 4. Inventory schemas without assuming field names
# ==========================================================================================

print("\nBASELINE RESULT COLUMNS")
print("-" * 100)

for column in section2a_baseline_results_df.columns:
    print(column)


print("\nSIDE RESULT COLUMNS")
print("-" * 100)

for column in section2a_side_results_df.columns:
    print(column)


# ==========================================================================================
# 5. Identify categorical descriptor columns
# ==========================================================================================

baseline_descriptor_columns_2a = []

for column in section2a_baseline_results_df.columns:

    if (
        section2a_baseline_results_df[
            column
        ].dtype
        ==
        object
    ):
        baseline_descriptor_columns_2a.append(
            column
        )


side_descriptor_columns_2a = []

for column in section2a_side_results_df.columns:

    if (
        section2a_side_results_df[
            column
        ].dtype
        ==
        object
    ):
        side_descriptor_columns_2a.append(
            column
        )


print("\nBASELINE DESCRIPTOR COLUMNS")
print("-" * 100)

print(
    baseline_descriptor_columns_2a
)


print("\nSIDE DESCRIPTOR COLUMNS")
print("-" * 100)

print(
    side_descriptor_columns_2a
)


# ==========================================================================================
# 6. Display unique descriptor values
# ==========================================================================================

print("\nBASELINE DESCRIPTOR VALUES")
print("-" * 100)

for column in baseline_descriptor_columns_2a:

    print(
        f"\n{column}:"
    )

    print(
        section2a_baseline_results_df[
            column
        ]
        .dropna()
        .unique()
        .tolist()
    )


print("\nSIDE DESCRIPTOR VALUES")
print("-" * 100)

for column in side_descriptor_columns_2a:

    print(
        f"\n{column}:"
    )

    print(
        section2a_side_results_df[
            column
        ]
        .dropna()
        .unique()
        .tolist()
    )


# ==========================================================================================
# 7. Check historical totals reconstructed from baseline rows
# ==========================================================================================

numeric_columns_2a = [
    "matches",
    "wins",
    "losses",
    "draws",
]

historical_totals_from_rows_2a = {}


for column in numeric_columns_2a:

    if column in section2a_baseline_results_df.columns:

        historical_totals_from_rows_2a[
            column
        ] = int(
            section2a_baseline_results_df[
                column
            ].sum()
        )


print("\nRECONSTRUCTED BASELINE TOTALS")
print("-" * 100)

for key, value in (
    historical_totals_from_rows_2a.items()
):

    print(
        f"{key:<12}: {value}"
    )


# ==========================================================================================
# 8. Verify overall historical score from component rows
# ==========================================================================================

if (
    "wins"
    in section2a_baseline_results_df.columns
    and
    "matches"
    in section2a_baseline_results_df.columns
):

    reconstructed_win_rate_2a = (
        section2a_baseline_results_df[
            "wins"
        ].sum()
        /
        section2a_baseline_results_df[
            "matches"
        ].sum()
    )

else:

    reconstructed_win_rate_2a = np.nan


print("\nHISTORICAL RATE RECONSTRUCTION")
print("-" * 100)

print(
    "Stored overall win rate       :",
    NOTEBOOK48_OVERALL_WIN_RATE,
)

print(
    "Reconstructed overall win rate:",
    reconstructed_win_rate_2a,
)


# ==========================================================================================
# 9. Define Notebook 60 benchmark-design lock
# ==========================================================================================

NOTEBOOK60_BENCHMARK_DESIGN = {
    "historical_source_notebook":
        48,

    "historical_total_matches":
        historical_scheduled_matches_2a,

    "historical_matches_per_baseline":
        historical_matches_per_baseline_2a,

    "historical_baseline_count":
        len(
            section2a_baseline_results_df
        ),

    "historical_side_result_count":
        len(
            section2a_side_results_df
        ),

    "historical_overall_win_rate":
        float(
            NOTEBOOK48_OVERALL_WIN_RATE
        ),

    "r3_retraining_allowed":
        False,

    "r3_model_modification_allowed":
        False,

    "comparison_mode":
        "MATCH_HISTORICAL_BENCHMARK_STRUCTURE",
}


print("\nNOTEBOOK 60 BENCHMARK DESIGN LOCK")
print("-" * 100)

for key, value in (
    NOTEBOOK60_BENCHMARK_DESIGN.items()
):

    print(
        f"{key:<40}: {value}"
    )


# ==========================================================================================
# 10. Save reconstructed benchmark design
# ==========================================================================================

SECTION2A_BASELINE_RESULTS_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2a_historical_baseline_results.csv"
)

SECTION2A_SIDE_RESULTS_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2a_historical_side_results.csv"
)

SECTION2A_DESIGN_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2a_benchmark_design.json"
)


section2a_baseline_results_df.to_csv(
    SECTION2A_BASELINE_RESULTS_FILE,
    index=False,
)

section2a_side_results_df.to_csv(
    SECTION2A_SIDE_RESULTS_FILE,
    index=False,
)


with open(
    SECTION2A_DESIGN_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        NOTEBOOK60_BENCHMARK_DESIGN,
        file,
        indent=2,
    )


# ==========================================================================================
# 11. Validation gates
# ==========================================================================================

section2a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical total = 300",

            "observed":
                historical_scheduled_matches_2a,

            "expected":
                300,

            "passed":
                historical_scheduled_matches_2a
                == 300,
        },

        {
            "validation":
                "historical successful = 300",

            "observed":
                historical_successful_matches_2a,

            "expected":
                300,

            "passed":
                historical_successful_matches_2a
                == 300,
        },

        {
            "validation":
                "historical failures = 0",

            "observed":
                historical_failed_matches_2a,

            "expected":
                0,

            "passed":
                historical_failed_matches_2a
                == 0,
        },

        {
            "validation":
                "matches per baseline = 100",

            "observed":
                historical_matches_per_baseline_2a,

            "expected":
                100,

            "passed":
                historical_matches_per_baseline_2a
                == 100,
        },

        {
            "validation":
                "baseline result records recovered",

            "observed":
                len(
                    section2a_baseline_results_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2a_baseline_results_df
                ) > 0,
        },

        {
            "validation":
                "side result records recovered",

            "observed":
                len(
                    section2a_side_results_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2a_side_results_df
                ) > 0,
        },

        {
            "validation":
                "overall win rate preserved",

            "observed":
                NOTEBOOK48_OVERALL_WIN_RATE,

            "expected":
                0.6466666666666666,

            "passed":
                np.isclose(
                    NOTEBOOK48_OVERALL_WIN_RATE,
                    0.6466666666666666,
                ),
        },
    ]
)


print("\nSECTION 2A VALIDATION")
print("-" * 100)

display(
    section2a_validation_df
)


assert (
    section2a_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ NOTEBOOK 48 BENCHMARK STRUCTURE RECOVERED")
print("✅ BASELINE RESULT GROUPS RECOVERED")
print("✅ SIDE-SPECIFIC RESULT GROUPS RECOVERED")
print("✅ 300-MATCH HISTORICAL DESIGN CONFIRMED")
print("✅ 100 MATCHES PER BASELINE CONFIRMED")
print("✅ 64.67% HISTORICAL OVERALL RATE PRESERVED")
print("✅ NOTEBOOK 60 BENCHMARK DESIGN LOCKED")
print("✅ SECTION 2A COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2A — RECONSTRUCT AUTHORITATIVE NOTEBOOK 48 BENCHMARK DESIGN
====================================================================================================

HISTORICAL EXPERIMENT SIZE
----------------------------------------------------------------------------------------------------
Scheduled matches       : 300
Successful matches      : 300
Failed matches          : 0
Matches per baseline    : 100

BASELINE RESULT RECORD COUNT
----------------------------------------------------------------------------------------------------
3

AUTHORITATIVE BASELINE RESULTS
----------------------------------------------------------------------------------------------------

,baseline_name,matches,competitive_wins,competitive_losses,draws,score,average_turns,median_turns,average_seconds,fallback_count,win_rate,loss_rate,draw_rate
0,Depth-6 Search Baseline,100,58,42,0,0.58,3.74,3.5,0.003742,0,0.58,0.42,0.0
1,Greedy Damage Baseline,100,58,42,0,0.58,3.26,3.0,0.001227,0,0.58,0.42,0.0
2,Random Baseline,100,78,22,0,0.78,3.60,3.0,0.001539,0,0.78,0.22,0.0

SIDE RESULT RECORD COUNT
----------------------------------------------------------------------------------------------------
6

AUTHORITATIVE SIDE RESULTS
----------------------------------------------------------------------------------------------------

,baseline_name,evaluated_agent_side,matches,wins,losses,draws,score,average_turns,win_rate
0,Depth-6 Search Baseline,Opponent,50,16,34,0,0.32,4.14,0.32
1,Depth-6 Search Baseline,Player,50,42,8,0,0.84,3.34,0.84
2,Greedy Damage Baseline,Opponent,50,16,34,0,0.32,3.18,0.32
3,Greedy Damage Baseline,Player,50,42,8,0,0.84,3.34,0.84
4,Random Baseline,Opponent,50,32,18,0,0.64,3.78,0.64
5,Random Baseline,Player,50,46,4,0,0.92,3.42,0.92

BASELINE RESULT COLUMNS
----------------------------------------------------------------------------------------------------
baseline_name
matches
competitive_wins
competitive_losses
draws
score
average_turns
median_turns
average_seconds
fallback_count
win_rate
loss_rate
draw_rate

SIDE RESULT COLUMNS
----------------------------------------------------------------------------------------------------
baseline_name
evaluated_agent_side
matches
wins
losses
draws
score
average_turns
win_rate

BASELINE DESCRIPTOR COLUMNS
----------------------------------------------------------------------------------------------------
[]

SIDE DESCRIPTOR COLUMNS
----------------------------------------------------------------------------------------------------
[]

BASELINE DESCRIPTOR VALUES
----------------------------------------------------------------------------------------------------

SIDE DESCRIPTOR VALUES
----------------------------------------------------------------------------------------------------

RECONSTRUCTED BASELINE TOTALS
----------------------------------------------------------------------------------------------------
matches     : 300
draws       : 0

HISTORICAL RATE RECONSTRUCTION
----------------------------------------------------------------------------------------------------
Stored overall win rate       : 0.6466666666666666
Reconstructed overall win rate: nan

NOTEBOOK 60 BENCHMARK DESIGN LOCK
----------------------------------------------------------------------------------------------------
historical_source_notebook              : 48
historical_total_matches                : 300
historical_matches_per_baseline         : 100
historical_baseline_count               : 3
historical_side_result_count            : 6
historical_overall_win_rate             : 0.6466666666666666
r3_retraining_allowed                   : False
r3_model_modification_allowed           : False
comparison_mode                         : MATCH_HISTORICAL_BENCHMARK_STRUCTURE

SECTION 2A VALIDATION
----------------------------------------------------------------------------------------------------

                          validation    observed  expected  passed
0             historical total = 300  300.000000       300    True
1        historical successful = 300  300.000000       300    True
2            historical failures = 0    0.000000         0    True
3         matches per baseline = 100  100.000000       100    True
4  baseline result records recovered    3.000000       > 0    True
5      side result records recovered    6.000000       > 0    True
6         overall win rate preserved    0.646667  0.646667    True

====================================================================================================
✅ NOTEBOOK 48 BENCHMARK STRUCTURE RECOVERED
✅ BASELINE RESULT GROUPS RECOVERED
✅ SIDE-SPECIFIC RESULT GROUPS RECOVERED
✅ 300-MATCH HISTORICAL DESIGN CONFIRMED
✅ 100 MATCHES PER BASELINE CONFIRMED
✅ 64.67% HISTORICAL OVERALL RATE PRESERVED
✅ NOTEBOOK 60 BENCHMARK DESIGN LOCKED
✅ SECTION 2A COMPLETE
====================================================================================================

In [8]:
# ==========================================================================================
# SECTION 2A.1 — NORMALIZE AND LOCK HISTORICAL BENCHMARK TARGETS
# ==========================================================================================

print("=" * 100)
print("SECTION 2A.1 — NORMALIZE AND LOCK HISTORICAL BENCHMARK TARGETS")
print("=" * 100)

import pandas as pd
import numpy as np
import json


# ==========================================================================================
# 1. Explicit descriptor columns from recovered authoritative schema
# ==========================================================================================

BASELINE_NAME_COLUMN_2A1 = "baseline_name"
SIDE_COLUMN_2A1 = "evaluated_agent_side"

assert (
    BASELINE_NAME_COLUMN_2A1
    in section2a_baseline_results_df.columns
)

assert (
    BASELINE_NAME_COLUMN_2A1
    in section2a_side_results_df.columns
)

assert (
    SIDE_COLUMN_2A1
    in section2a_side_results_df.columns
)


baseline_names_2a1 = (
    section2a_baseline_results_df[
        BASELINE_NAME_COLUMN_2A1
    ]
    .astype(str)
    .tolist()
)

evaluated_sides_2a1 = sorted(
    section2a_side_results_df[
        SIDE_COLUMN_2A1
    ]
    .astype(str)
    .unique()
    .tolist()
)


print("\nAUTHORITATIVE BASELINES")
print("-" * 100)

for name in baseline_names_2a1:
    print(name)


print("\nAUTHORITATIVE EVALUATED SIDES")
print("-" * 100)

for side in evaluated_sides_2a1:
    print(side)


# ==========================================================================================
# 2. Correctly reconstruct global Notebook 48 totals
# ==========================================================================================

historical_total_wins_2a1 = int(
    section2a_baseline_results_df[
        "competitive_wins"
    ].sum()
)

historical_total_losses_2a1 = int(
    section2a_baseline_results_df[
        "competitive_losses"
    ].sum()
)

historical_total_draws_2a1 = int(
    section2a_baseline_results_df[
        "draws"
    ].sum()
)

historical_total_matches_2a1 = int(
    section2a_baseline_results_df[
        "matches"
    ].sum()
)


historical_reconstructed_win_rate_2a1 = (
    historical_total_wins_2a1
    /
    historical_total_matches_2a1
)


print("\nRECONSTRUCTED HISTORICAL TOTALS")
print("-" * 100)

print(
    "Matches :",
    historical_total_matches_2a1,
)

print(
    "Wins    :",
    historical_total_wins_2a1,
)

print(
    "Losses  :",
    historical_total_losses_2a1,
)

print(
    "Draws   :",
    historical_total_draws_2a1,
)

print(
    "Win rate:",
    historical_reconstructed_win_rate_2a1,
)

print(
    "Win rate:",
    f"{historical_reconstructed_win_rate_2a1:.2%}",
)


assert (
    historical_total_matches_2a1
    ==
    300
)

assert (
    historical_total_wins_2a1
    ==
    194
)

assert (
    historical_total_losses_2a1
    ==
    106
)

assert (
    historical_total_draws_2a1
    ==
    0
)

assert np.isclose(
    historical_reconstructed_win_rate_2a1,
    NOTEBOOK48_OVERALL_WIN_RATE,
)


# ==========================================================================================
# 3. Build exact side-neutral benchmark table
# ==========================================================================================

historical_baseline_targets_2a1 = (
    section2a_baseline_results_df[
        [
            "baseline_name",
            "matches",
            "competitive_wins",
            "competitive_losses",
            "draws",
            "win_rate",
            "average_turns",
            "fallback_count",
        ]
    ]
    .copy()
)


historical_baseline_targets_2a1 = (
    historical_baseline_targets_2a1
    .rename(
        columns={
            "competitive_wins":
                "r3_reference_wins",

            "competitive_losses":
                "r3_reference_losses",

            "win_rate":
                "historical_side_neutral_win_rate",

            "average_turns":
                "historical_average_turns",

            "fallback_count":
                "historical_fallback_count",
        }
    )
)


print("\nLOCKED SIDE-NEUTRAL HISTORICAL TARGETS")
print("-" * 100)

display(
    historical_baseline_targets_2a1
)


# ==========================================================================================
# 4. Pivot side-specific historical results
# ==========================================================================================

side_win_rate_pivot_2a1 = (
    section2a_side_results_df
    .pivot(
        index="baseline_name",
        columns="evaluated_agent_side",
        values="win_rate",
    )
    .reset_index()
)


side_win_rate_pivot_2a1.columns.name = None


side_win_rate_pivot_2a1 = (
    side_win_rate_pivot_2a1
    .rename(
        columns={
            "Player":
                "historical_player_side_win_rate",

            "Opponent":
                "historical_opponent_side_win_rate",
        }
    )
)


historical_comparison_targets_2a1 = (
    historical_baseline_targets_2a1
    .merge(
        side_win_rate_pivot_2a1,
        on="baseline_name",
        how="left",
    )
)


historical_comparison_targets_2a1[
    "historical_side_average"
] = (
    (
        historical_comparison_targets_2a1[
            "historical_player_side_win_rate"
        ]
        +
        historical_comparison_targets_2a1[
            "historical_opponent_side_win_rate"
        ]
    )
    /
    2.0
)


historical_comparison_targets_2a1[
    "side_average_matches_side_neutral"
] = np.isclose(
    historical_comparison_targets_2a1[
        "historical_side_average"
    ],
    historical_comparison_targets_2a1[
        "historical_side_neutral_win_rate"
    ],
)


print("\nFULL HISTORICAL COMPARISON TARGETS")
print("-" * 100)

display(
    historical_comparison_targets_2a1
)


# ==========================================================================================
# 5. Global starting-side benchmark
#
# Aggregate the six historical side rows.
# ==========================================================================================

historical_side_aggregate_2a1 = (
    section2a_side_results_df
    .groupby(
        "evaluated_agent_side",
        as_index=False,
    )
    .agg(
        matches=(
            "matches",
            "sum",
        ),

        wins=(
            "wins",
            "sum",
        ),

        losses=(
            "losses",
            "sum",
        ),

        draws=(
            "draws",
            "sum",
        ),
    )
)


historical_side_aggregate_2a1[
    "win_rate"
] = (
    historical_side_aggregate_2a1[
        "wins"
    ]
    /
    historical_side_aggregate_2a1[
        "matches"
    ]
)


print("\nGLOBAL HISTORICAL SIDE PERFORMANCE")
print("-" * 100)

display(
    historical_side_aggregate_2a1
)


# ==========================================================================================
# 6. Lock authoritative benchmark constants
# ==========================================================================================

NOTEBOOK60_HISTORICAL_BASELINE = {
    "overall": {
        "matches":
            300,

        "wins":
            194,

        "losses":
            106,

        "draws":
            0,

        "win_rate":
            float(
                historical_reconstructed_win_rate_2a1
            ),
    },

    "baseline_win_rates": {
        row["baseline_name"]:
            float(
                row[
                    "historical_side_neutral_win_rate"
                ]
            )

        for _, row
        in historical_comparison_targets_2a1.iterrows()
    },

    "player_side": {
        "matches":
            int(
                historical_side_aggregate_2a1.loc[
                    historical_side_aggregate_2a1[
                        "evaluated_agent_side"
                    ] == "Player",
                    "matches",
                ].iloc[0]
            ),

        "win_rate":
            float(
                historical_side_aggregate_2a1.loc[
                    historical_side_aggregate_2a1[
                        "evaluated_agent_side"
                    ] == "Player",
                    "win_rate",
                ].iloc[0]
            ),
    },

    "opponent_side": {
        "matches":
            int(
                historical_side_aggregate_2a1.loc[
                    historical_side_aggregate_2a1[
                        "evaluated_agent_side"
                    ] == "Opponent",
                    "matches",
                ].iloc[0]
            ),

        "win_rate":
            float(
                historical_side_aggregate_2a1.loc[
                    historical_side_aggregate_2a1[
                        "evaluated_agent_side"
                    ] == "Opponent",
                    "win_rate",
                ].iloc[0]
            ),
    },
}


print("\nLOCKED NOTEBOOK 60 HISTORICAL BASELINE")
print("-" * 100)

print(
    json.dumps(
        NOTEBOOK60_HISTORICAL_BASELINE,
        indent=2,
    )
)


# ==========================================================================================
# 7. Save normalized historical target package
# ==========================================================================================

SECTION2A1_TARGETS_CSV = (
    NOTEBOOK60_REPORT_DIR
    / "section2a1_historical_comparison_targets.csv"
)

SECTION2A1_SIDE_CSV = (
    NOTEBOOK60_REPORT_DIR
    / "section2a1_historical_side_aggregate.csv"
)

SECTION2A1_LOCK_JSON = (
    NOTEBOOK60_REPORT_DIR
    / "section2a1_historical_baseline_lock.json"
)


historical_comparison_targets_2a1.to_csv(
    SECTION2A1_TARGETS_CSV,
    index=False,
)

historical_side_aggregate_2a1.to_csv(
    SECTION2A1_SIDE_CSV,
    index=False,
)


with open(
    SECTION2A1_LOCK_JSON,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        NOTEBOOK60_HISTORICAL_BASELINE,
        file,
        indent=2,
    )


# ==========================================================================================
# 8. Validation gates
# ==========================================================================================

section2a1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "three historical baselines",

            "observed":
                len(
                    historical_comparison_targets_2a1
                ),

            "expected":
                3,

            "passed":
                len(
                    historical_comparison_targets_2a1
                ) == 3,
        },

        {
            "validation":
                "two evaluated sides",

            "observed":
                evaluated_sides_2a1,

            "expected":
                [
                    "Opponent",
                    "Player",
                ],

            "passed":
                evaluated_sides_2a1
                ==
                [
                    "Opponent",
                    "Player",
                ],
        },

        {
            "validation":
                "overall wins reconstructed",

            "observed":
                historical_total_wins_2a1,

            "expected":
                194,

            "passed":
                historical_total_wins_2a1
                == 194,
        },

        {
            "validation":
                "overall losses reconstructed",

            "observed":
                historical_total_losses_2a1,

            "expected":
                106,

            "passed":
                historical_total_losses_2a1
                == 106,
        },

        {
            "validation":
                "overall rate reconstructed",

            "observed":
                historical_reconstructed_win_rate_2a1,

            "expected":
                NOTEBOOK48_OVERALL_WIN_RATE,

            "passed":
                np.isclose(
                    historical_reconstructed_win_rate_2a1,
                    NOTEBOOK48_OVERALL_WIN_RATE,
                ),
        },

        {
            "validation":
                "side averages reproduce baseline rates",

            "observed":
                bool(
                    historical_comparison_targets_2a1[
                        "side_average_matches_side_neutral"
                    ].all()
                ),

            "expected":
                True,

            "passed":
                bool(
                    historical_comparison_targets_2a1[
                        "side_average_matches_side_neutral"
                    ].all()
                ),
        },

        {
            "validation":
                "historical target package saved",

            "observed":
                all(
                    path.exists()
                    for path in [
                        SECTION2A1_TARGETS_CSV,
                        SECTION2A1_SIDE_CSV,
                        SECTION2A1_LOCK_JSON,
                    ]
                ),

            "expected":
                True,

            "passed":
                all(
                    path.exists()
                    for path in [
                        SECTION2A1_TARGETS_CSV,
                        SECTION2A1_SIDE_CSV,
                        SECTION2A1_LOCK_JSON,
                    ]
                ),
        },
    ]
)


print("\nSECTION 2A.1 VALIDATION")
print("-" * 100)

display(
    section2a1_validation_df
)


assert (
    section2a1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ HISTORICAL SCHEMA NORMALIZED")
print("✅ 194 / 300 HISTORICAL WINS RECONSTRUCTED")
print("✅ 64.67% OVERALL BASELINE RECONFIRMED")
print("✅ THREE BASELINE TARGETS LOCKED")
print("✅ PLAYER / OPPONENT SIDE TARGETS LOCKED")
print("✅ SIDE-NEUTRAL RATE RECONSTRUCTION VERIFIED")
print("✅ HISTORICAL TARGET PACKAGE SAVED")
print("✅ SECTION 2A.1 COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2A.1 — NORMALIZE AND LOCK HISTORICAL BENCHMARK TARGETS
====================================================================================================

AUTHORITATIVE BASELINES
----------------------------------------------------------------------------------------------------
Depth-6 Search Baseline
Greedy Damage Baseline
Random Baseline

AUTHORITATIVE EVALUATED SIDES
----------------------------------------------------------------------------------------------------
Opponent
Player

RECONSTRUCTED HISTORICAL TOTALS
----------------------------------------------------------------------------------------------------
Matches : 300
Wins    : 194
Losses  : 106
Draws   : 0
Win rate: 0.6466666666666666
Win rate: 64.67%

LOCKED SIDE-NEUTRAL HISTORICAL TARGETS
----------------------------------------------------------------------------------------------------

,baseline_name,matches,r3_reference_wins,r3_reference_losses,draws,historical_side_neutral_win_rate,historical_average_turns,historical_fallback_count
0,Depth-6 Search Baseline,100,58,42,0,0.58,3.74,0
1,Greedy Damage Baseline,100,58,42,0,0.58,3.26,0
2,Random Baseline,100,78,22,0,0.78,3.60,0

FULL HISTORICAL COMPARISON TARGETS
----------------------------------------------------------------------------------------------------

,baseline_name,matches,r3_reference_wins,r3_reference_losses,draws,historical_side_neutral_win_rate,historical_average_turns,historical_fallback_count,historical_opponent_side_win_rate,historical_player_side_win_rate,historical_side_average,side_average_matches_side_neutral
0,Depth-6 Search Baseline,100,58,42,0,0.58,3.74,0,0.32,0.84,0.58,True
1,Greedy Damage Baseline,100,58,42,0,0.58,3.26,0,0.32,0.84,0.58,True
2,Random Baseline,100,78,22,0,0.78,3.60,0,0.64,0.92,0.78,True

GLOBAL HISTORICAL SIDE PERFORMANCE
----------------------------------------------------------------------------------------------------

  evaluated_agent_side  matches  wins  losses  draws  win_rate
0             Opponent      150    64      86      0  0.426667
1               Player      150   130      20      0  0.866667

LOCKED NOTEBOOK 60 HISTORICAL BASELINE
----------------------------------------------------------------------------------------------------
{
  "overall": {
    "matches": 300,
    "wins": 194,
    "losses": 106,
    "draws": 0,
    "win_rate": 0.6466666666666666
  },
  "baseline_win_rates": {
    "Depth-6 Search Baseline": 0.58,
    "Greedy Damage Baseline": 0.58,
    "Random Baseline": 0.78
  },
  "player_side": {
    "matches": 150,
    "win_rate": 0.8666666666666667
  },
  "opponent_side": {
    "matches": 150,
    "win_rate": 0.4266666666666667
  }
}

SECTION 2A.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,three historical baselines,3,3,True
1,two evaluated sides,"[Opponent, Player]","[Opponent, Player]",True
2,overall wins reconstructed,194,194,True
3,overall losses reconstructed,106,106,True
4,overall rate reconstructed,0.646667,0.646667,True
5,side averages reproduce baseline rates,True,True,True
6,historical target package saved,True,True,True

====================================================================================================
✅ HISTORICAL SCHEMA NORMALIZED
✅ 194 / 300 HISTORICAL WINS RECONSTRUCTED
✅ 64.67% OVERALL BASELINE RECONFIRMED
✅ THREE BASELINE TARGETS LOCKED
✅ PLAYER / OPPONENT SIDE TARGETS LOCKED
✅ SIDE-NEUTRAL RATE RECONSTRUCTION VERIFIED
✅ HISTORICAL TARGET PACKAGE SAVED
✅ SECTION 2A.1 COMPLETE
====================================================================================================

In [9]:
# ==========================================================================================
# SECTION 2B — RECOVER NOTEBOOK 48 BASELINE AGENTS AND TOURNAMENT HARNESS
# ==========================================================================================

print("=" * 100)
print("SECTION 2B — RECOVER NOTEBOOK 48 BASELINE AGENTS AND TOURNAMENT HARNESS")
print("=" * 100)

from pathlib import Path
import ast
import inspect
import re
import pandas as pd


# ==========================================================================================
# 1. Search priority sources around Notebook 48
# ==========================================================================================

SEARCH_ROOTS_2B = [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
    PROJECT_ROOT / "reports" / "notebook48",
    PROJECT_ROOT / "artifacts" / "notebook48",
    PROJECT_ROOT / "outputs" / "notebook48",
]

BASELINE_NAMES_2B = [
    "Depth-6 Search Baseline",
    "Greedy Damage Baseline",
    "Random Baseline",
]

SEARCH_TERMS_2B = [
    "Depth-6 Search Baseline",
    "Greedy Damage Baseline",
    "Random Baseline",
    "competitive_policy_baseline_tournament",
    "baseline_tournament",
    "greedy",
    "random",
    "depth",
]


candidate_files_2b = []


for root in SEARCH_ROOTS_2B:

    if not root.exists():
        continue

    for path in root.rglob("*"):

        if not path.is_file():
            continue

        if "__pycache__" in path.parts:
            continue

        if path.suffix.lower() not in {
            ".py",
            ".json",
            ".txt",
            ".md",
            ".csv",
        }:
            continue

        try:

            text = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            )

        except Exception:
            continue

        text_lower = text.lower()

        matched_terms = [
            term
            for term in SEARCH_TERMS_2B
            if term.lower() in text_lower
        ]

        if not matched_terms:
            continue

        candidate_files_2b.append(
            {
                "file":
                    str(
                        path.relative_to(
                            PROJECT_ROOT
                        )
                    ),

                "matched_terms":
                    matched_terms,

                "size_bytes":
                    path.stat().st_size,
            }
        )


section2b_candidate_files_df = pd.DataFrame(
    candidate_files_2b
)


print("\nNOTEBOOK 48 BASELINE / HARNESS CANDIDATE FILES")
print("-" * 100)

display(
    section2b_candidate_files_df
    .drop_duplicates(
        subset=["file"]
    )
    .reset_index(drop=True)
)


# ==========================================================================================
# 2. Search Python sources for class/function definitions
# ==========================================================================================

definition_rows_2b = []


for root in [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
]:

    if not root.exists():
        continue

    for path in root.rglob("*.py"):

        if "__pycache__" in path.parts:
            continue

        try:

            source_text = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            )

            tree = ast.parse(
                source_text
            )

        except Exception:
            continue


        # ------------------------------------------------------------------
        # Keep only files containing Notebook 48 benchmark terminology
        # ------------------------------------------------------------------

        lower_text = source_text.lower()

        if not any(
            term.lower() in lower_text
            for term in SEARCH_TERMS_2B
        ):
            continue


        for node in ast.walk(tree):

            if isinstance(
                node,
                ast.ClassDef,
            ):

                source_segment = ast.get_source_segment(
                    source_text,
                    node,
                )

                source_segment_lower = (
                    source_segment.lower()
                    if source_segment
                    else ""
                )

                if any(
                    token in (
                        node.name.lower()
                        + " "
                        + source_segment_lower
                    )
                    for token in [
                        "baseline",
                        "greedy",
                        "random",
                        "search",
                        "agent",
                    ]
                ):

                    definition_rows_2b.append(
                        {
                            "file":
                                str(
                                    path.relative_to(
                                        PROJECT_ROOT
                                    )
                                ),

                            "object_type":
                                "CLASS",

                            "name":
                                node.name,

                            "line_number":
                                node.lineno,

                            "source":
                                source_segment,
                        }
                    )


            elif isinstance(
                node,
                (
                    ast.FunctionDef,
                    ast.AsyncFunctionDef,
                ),
            ):

                source_segment = ast.get_source_segment(
                    source_text,
                    node,
                )

                source_segment_lower = (
                    source_segment.lower()
                    if source_segment
                    else ""
                )

                if any(
                    token in (
                        node.name.lower()
                        + " "
                        + source_segment_lower
                    )
                    for token in [
                        "baseline",
                        "greedy",
                        "random",
                        "search",
                        "tournament",
                        "match",
                        "battle",
                    ]
                ):

                    definition_rows_2b.append(
                        {
                            "file":
                                str(
                                    path.relative_to(
                                        PROJECT_ROOT
                                    )
                                ),

                            "object_type":
                                "FUNCTION",

                            "name":
                                node.name,

                            "line_number":
                                node.lineno,

                            "source":
                                source_segment,
                        }
                    )


section2b_definitions_df = pd.DataFrame(
    definition_rows_2b
)


print("\nCANDIDATE BASELINE / TOURNAMENT DEFINITIONS")
print("-" * 100)

if section2b_definitions_df.empty:

    print(
        "No candidate class/function definitions found."
    )

else:

    display(
        section2b_definitions_df[
            [
                "file",
                "object_type",
                "name",
                "line_number",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 3. Search exact baseline labels and surrounding context
# ==========================================================================================

baseline_context_rows_2b = []


for root in [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
]:

    if not root.exists():
        continue

    for path in root.rglob("*.py"):

        if "__pycache__" in path.parts:
            continue

        try:

            lines = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            ).splitlines()

        except Exception:
            continue


        for line_index, line in enumerate(
            lines
        ):

            if not any(
                name.lower()
                in line.lower()
                for name in BASELINE_NAMES_2B
            ):
                continue


            start = max(
                0,
                line_index - 20,
            )

            end = min(
                len(lines),
                line_index + 35,
            )


            baseline_context_rows_2b.append(
                {
                    "file":
                        str(
                            path.relative_to(
                                PROJECT_ROOT
                            )
                        ),

                    "line_number":
                        line_index + 1,

                    "matched_line":
                        line.strip(),

                    "context":
                        "\n".join(
                            lines[start:end]
                        ),
                }
            )


section2b_baseline_context_df = pd.DataFrame(
    baseline_context_rows_2b
)


print("\nEXACT BASELINE LABEL CONTEXTS")
print("-" * 100)

if section2b_baseline_context_df.empty:

    print(
        "No exact baseline labels found in Python sources."
    )

else:

    for index, row in (
        section2b_baseline_context_df
        .head(30)
        .iterrows()
    ):

        print("\n" + "=" * 100)

        print(
            "FILE:",
            row["file"],
        )

        print(
            "LINE:",
            row["line_number"],
        )

        print(
            "MATCH:",
            row["matched_line"],
        )

        print("-" * 100)

        print(
            row["context"]
        )


# ==========================================================================================
# 4. Search specifically for likely harness function names
# ==========================================================================================

HARNESS_NAME_TOKENS_2B = [
    "tournament",
    "baseline",
    "evaluate",
    "benchmark",
    "match",
    "simulate",
]


harness_candidates_2b = []


if not section2b_definitions_df.empty:

    for _, row in (
        section2b_definitions_df.iterrows()
    ):

        name_lower = str(
            row["name"]
        ).lower()

        source_lower = str(
            row["source"]
        ).lower()

        if any(
            token in name_lower
            for token in HARNESS_NAME_TOKENS_2B
        ):

            harness_candidates_2b.append(
                row.to_dict()
            )

        elif (
            "matches_per_baseline"
            in source_lower
            or
            "baseline_results"
            in source_lower
            or
            "side_results"
            in source_lower
        ):

            harness_candidates_2b.append(
                row.to_dict()
            )


section2b_harness_candidates_df = pd.DataFrame(
    harness_candidates_2b
)


print("\nTOURNAMENT HARNESS CANDIDATES")
print("-" * 100)

if section2b_harness_candidates_df.empty:

    print(
        "No tournament harness candidates found."
    )

else:

    display(
        section2b_harness_candidates_df[
            [
                "file",
                "object_type",
                "name",
                "line_number",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 5. Print source for top harness candidates
# ==========================================================================================

print("\nTOP HARNESS SOURCE")
print("-" * 100)

if not section2b_harness_candidates_df.empty:

    for index, row in (
        section2b_harness_candidates_df
        .head(15)
        .iterrows()
    ):

        print("\n" + "=" * 100)

        print(
            "FILE:",
            row["file"],
        )

        print(
            "OBJECT:",
            row["name"],
        )

        print("-" * 100)

        print(
            row["source"]
        )


# ==========================================================================================
# 6. Validation
# ==========================================================================================

section2b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "baseline-related files found",

            "observed":
                len(
                    section2b_candidate_files_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2b_candidate_files_df
                ) > 0,
        },

        {
            "validation":
                "baseline/harness definitions found",

            "observed":
                len(
                    section2b_definitions_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2b_definitions_df
                ) > 0,
        },

        {
            "validation":
                "exact baseline contexts found",

            "observed":
                len(
                    section2b_baseline_context_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2b_baseline_context_df
                ) > 0,
        },

        {
            "validation":
                "tournament harness candidates found",

            "observed":
                len(
                    section2b_harness_candidates_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2b_harness_candidates_df
                ) > 0,
        },
    ]
)


print("\nSECTION 2B VALIDATION")
print("-" * 100)

display(
    section2b_validation_df
)


print("\n" + "=" * 100)

if section2b_validation_df[
    "passed"
].all():

    print("✅ HISTORICAL BASELINE IMPLEMENTATIONS LOCATED")
    print("✅ TOURNAMENT HARNESS CANDIDATES LOCATED")
    print("✅ READY TO RECONSTRUCT FAIR R3 BENCHMARK")

else:

    print("⚠️ ADDITIONAL HARNESS RECOVERY REQUIRED")

print("✅ SECTION 2B COMPLETE")
print("=" * 100)

====================================================================================================
SECTION 2B — RECOVER NOTEBOOK 48 BASELINE AGENTS AND TOURNAMENT HARNESS
====================================================================================================

NOTEBOOK 48 BASELINE / HARNESS CANDIDATE FILES
----------------------------------------------------------------------------------------------------

,file,matched_terms,size_bytes
0,scripts\03_feature_engineering.py,[random],19930
1,scripts\04_card_knowledge_base.py,[random],11369
2,scripts\05_deck_builder.py,[random],14368
3,scripts\06_pdf_reference_validation.py,[random],5885
4,scripts\07_battle_engine.py,[random],55211
...,...,...,...
82,reports\notebook48\final_competitive_recommend...,"[Depth-6 Search Baseline, Random Baseline, gre...",1149
83,reports\notebook48\final_competitive_strength_...,"[Depth-6 Search Baseline, greedy, random, depth]",3101
84,reports\notebook48\final_competitive_strength_...,"[Random Baseline, greedy, random, depth]",424
85,reports\notebook48\tournament_match_adapter_su...,"[Depth-6 Search Baseline, Greedy Damage Baseli...",2019
86,reports\notebook48\tournament_setup_summary.json,"[random, depth]",1548

CANDIDATE BASELINE / TOURNAMENT DEFINITIONS
----------------------------------------------------------------------------------------------------

,file,object_type,name,line_number
0,scripts\05_deck_builder.py,FUNCTION,validate_deck,277
1,scripts\05_deck_builder.py,FUNCTION,build_type_deck,498
2,scripts\07_battle_engine.py,FUNCTION,first_card_by_category,112
3,scripts\07_battle_engine.py,FUNCTION,prepare_deck,167
4,scripts\07_battle_engine.py,FUNCTION,draw_valid_opening_hand,303
...,...,...,...,...
506,src\tournament\match.py,FUNCTION,__post_init__,21
507,src\tournament\runner.py,FUNCTION,run_two_agent_match,18
508,src\training\dataset.py,FUNCTION,replay_to_dataframe,23
509,src\training\replay.py,CLASS,ReplayStep,8
510,src\training\replay.py,FUNCTION,add_step,36

EXACT BASELINE LABEL CONTEXTS
----------------------------------------------------------------------------------------------------

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 1879
MATCH: # 3.5 â€” Random baseline agent
----------------------------------------------------------------------------------------------------
    ):
        value = getattr(
            move,
            attribute_name,
            None,
        )

        if value is not None:
            try:
                return float(value or 0.0)
            except (
                TypeError,
                ValueError,
            ):
                return 0.0

    return 0.0


# ------------------------------------------------------------
# 3.5 â€” Random baseline agent
# ------------------------------------------------------------

class RandomLegalMoveAgent:
    def __init__(
        self,
        seed: int = RANDOM_SEED,
        name: str = "Random Legal Agent",
    ) -> None:
        self.name = name
        self.random = random.Random(
            seed
        )
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 1983
MATCH: # 3.6 â€” Greedy damage baseline
----------------------------------------------------------------------------------------------------
                    confidence,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision


# ------------------------------------------------------------
# 3.6 â€” Greedy damage baseline
# ------------------------------------------------------------

class GreedyDamageAgent:
    def __init__(
        self,
        name: str = "Greedy Damage Agent",
    ) -> None:
        self.name = name
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )


====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2964
MATCH: "Random Baseline",
----------------------------------------------------------------------------------------------------
competitive_tournament_agent = (
    CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )
)

random_baseline_agent = (
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2971
MATCH: "Greedy Damage Baseline",
----------------------------------------------------------------------------------------------------
        ),

        name=
            "Competitive Policy",
    )
)

random_baseline_agent = (
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2981
MATCH: "Depth-6 Search Baseline",
----------------------------------------------------------------------------------------------------
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],
    start=1,
):
    smoke_result = run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3201
MATCH: # - Random Baseline
----------------------------------------------------------------------------------------------------

assert smoke_test_df[
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#
# #### Each pairing uses multiple card matchups and both evaluated-agent sides.

# In[6]:


# ============================================================
# NOTEBOOK 48
# SECTION 4 â€” FULL BASELINE TOURNAMENT
# ============================================================


import dataclasses
import json
import math
import random
import time
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 4.3 â€” Tournament configuration
# ------------------------------------------------------------

TOURNAMENT_MATCHES_PER_BASELINE = (
    INITIAL_MATCHES_PER_PAIRING
)


====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3202
MATCH: # - Greedy Damage Baseline
----------------------------------------------------------------------------------------------------
assert smoke_test_df[
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#
# #### Each pairing uses multiple card matchups and both evaluated-agent sides.

# In[6]:


# ============================================================
# NOTEBOOK 48
# SECTION 4 â€” FULL BASELINE TOURNAMENT
# ============================================================


import dataclasses
import json
import math
import random
import time
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 4.3 â€” Tournament configuration
# ------------------------------------------------------------

TOURNAMENT_MATCHES_PER_BASELINE = (
    INITIAL_MATCHES_PER_PAIRING
)

TOURNAMENT_PROGRESS_INTERVAL = 25

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3203
MATCH: # - Depth-6 Search Baseline
----------------------------------------------------------------------------------------------------
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#
# #### Each pairing uses multiple card matchups and both evaluated-agent sides.

# In[6]:


# ============================================================
# NOTEBOOK 48
# SECTION 4 â€” FULL BASELINE TOURNAMENT
# ============================================================


import dataclasses
import json
import math
import random
import time
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 4.3 â€” Tournament configuration
# ------------------------------------------------------------

TOURNAMENT_MATCHES_PER_BASELINE = (
    INITIAL_MATCHES_PER_PAIRING
)

TOURNAMENT_PROGRESS_INTERVAL = 25


====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3286
MATCH: name="Random Baseline",
----------------------------------------------------------------------------------------------------

def create_competitive_agent() -> CompetitivePolicyAgent:
    return CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )


def create_random_baseline(
    seed: int,
) -> RandomLegalMoveAgent:
    return RandomLegalMoveAgent(
        seed=seed,
        name="Random Baseline",
    )


def create_greedy_baseline() -> GreedyDamageAgent:
    return GreedyDamageAgent(
        name="Greedy Damage Baseline",
    )


def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3292
MATCH: name="Greedy Damage Baseline",
----------------------------------------------------------------------------------------------------
        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )


def create_random_baseline(
    seed: int,
) -> RandomLegalMoveAgent:
    return RandomLegalMoveAgent(
        seed=seed,
        name="Random Baseline",
    )


def create_greedy_baseline() -> GreedyDamageAgent:
    return GreedyDamageAgent(
        name="Greedy Damage Baseline",
    )


def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


# ------------------------------------------------------------
# 4.5 â€” Balanced tournament schedule
# ------------------------------------------------------------


====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3302
MATCH: "Depth-6 Search Baseline",
----------------------------------------------------------------------------------------------------
    seed: int,
) -> RandomLegalMoveAgent:
    return RandomLegalMoveAgent(
        seed=seed,
        name="Random Baseline",
    )


def create_greedy_baseline() -> GreedyDamageAgent:
    return GreedyDamageAgent(
        name="Greedy Damage Baseline",
    )


def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


# ------------------------------------------------------------
# 4.5 â€” Balanced tournament schedule
# ------------------------------------------------------------

def build_balanced_schedule(
    baseline_name: str,
    match_count: int,
) -> list[dict[str, Any]]:
    schedule = []

    card_count = len(
        TOURNAMENT_CARD_TEMPLATES
    )


====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3307
MATCH: "Random Baseline":
----------------------------------------------------------------------------------------------------
    )


def create_greedy_baseline() -> GreedyDamageAgent:
    return GreedyDamageAgent(
        name="Greedy Damage Baseline",
    )


def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


# ------------------------------------------------------------
# 4.5 â€” Balanced tournament schedule
# ------------------------------------------------------------

def build_balanced_schedule(
    baseline_name: str,
    match_count: int,
) -> list[dict[str, Any]]:
    schedule = []

    card_count = len(
        TOURNAMENT_CARD_TEMPLATES
    )

    for match_index in range(
        match_count
    ):
        evaluated_side = (
            "Player"

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3313
MATCH: "Greedy Damage Baseline":
----------------------------------------------------------------------------------------------------
    )


def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


# ------------------------------------------------------------
# 4.5 â€” Balanced tournament schedule
# ------------------------------------------------------------

def build_balanced_schedule(
    baseline_name: str,
    match_count: int,
) -> list[dict[str, Any]]:
    schedule = []

    card_count = len(
        TOURNAMENT_CARD_TEMPLATES
    )

    for match_index in range(
        match_count
    ):
        evaluated_side = (
            "Player"
            if match_index % 2 == 0
            else "Opponent"
        )

        starting_side = (
            "Player"

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3317
MATCH: "Depth-6 Search Baseline":
----------------------------------------------------------------------------------------------------
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )


baseline_factories = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


# ------------------------------------------------------------
# 4.5 â€” Balanced tournament schedule
# ------------------------------------------------------------

def build_balanced_schedule(
    baseline_name: str,
    match_count: int,
) -> list[dict[str, Any]]:
    schedule = []

    card_count = len(
        TOURNAMENT_CARD_TEMPLATES
    )

    for match_index in range(
        match_count
    ):
        evaluated_side = (
            "Player"
            if match_index % 2 == 0
            else "Opponent"
        )

        starting_side = (
            "Player"
            if (
                match_index // 2
            ) % 2 == 0
            else "Opponent"


,file,object_type,name,line_number
0,scripts\08_ai_decision_agent.py,FUNCTION,evaluate_pokemon,352
1,scripts\09_strategic_battle_ai.py,FUNCTION,evaluate_future_prize_value,644
2,scripts\09_strategic_battle_ai.py,FUNCTION,evaluate_pokemon_long_term_plan,1041
3,scripts\09_strategic_battle_ai.py,FUNCTION,evaluate_all_player_pokemon,1076
4,scripts\09_strategic_battle_ai.py,FUNCTION,evaluate_strategic_switch,1286
...,...,...,...,...
64,src\tournament\manager.py,CLASS,TournamentManager,59
65,src\tournament\manager.py,FUNCTION,matches_played,98
66,src\tournament\manager.py,FUNCTION,run_match,117
67,src\tournament\match.py,CLASS,TournamentMatch,11
68,src\tournament\runner.py,FUNCTION,run_two_agent_match,18

TOP HARNESS SOURCE
----------------------------------------------------------------------------------------------------

====================================================================================================
FILE: scripts\08_ai_decision_agent.py
OBJECT: evaluate_pokemon
----------------------------------------------------------------------------------------------------
def evaluate_pokemon(pokemon: PokemonState):
    """
    Computes a heuristic score for a Pokémon.
    Higher scores indicate a stronger battle position.
    """

    score = 0.0

    card = pokemon.card

    # --------------------------
    # Remaining HP
    # --------------------------
    max_hp = float(card.get("hp", 0) or 0)

    if max_hp > 0:
        hp_ratio = pokemon.current_hp / max_hp
        score += hp_ratio * 40

    # --------------------------
    # Overall card quality
    # --------------------------
    score += float(card.get("overall_score", 0))

    # --------------------------
    # Attached Energy
    # --------------------------
    score += pokemon.attached_energy * 10

    # --------------------------
    # Active Bonus
    # --------------------------
    if pokemon.is_active:
        score += 5

    # --------------------------
    # Status Penalty
    # --------------------------
    if pokemon.status is not None:
        score -= 15

    return round(score, 2)

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: evaluate_future_prize_value
----------------------------------------------------------------------------------------------------
def evaluate_future_prize_value(
    planner: StrategicBattlePlanner,
    attacker: PokemonState,
    defender: PokemonState,
):
    """
    Estimate the strategic reward of future knockouts.
    """

    forecast = forecast_knockout_opportunities(
        planner,
        attacker,
        defender,
    )

    prize_values = []

    for attack in forecast:

        prize_reward = 0

        if attack["can_knock_out"]:

            prize_reward = 300

            if attack["knockout_turn"] is not None:
                prize_reward -= attack["knockout_turn"] * 20

        prize_values.append({

            **attack,

            "prize_reward": prize_reward,

            "strategic_value":
                attack["damage"] + prize_reward

        })

    return prize_values

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: evaluate_pokemon_long_term_plan
----------------------------------------------------------------------------------------------------
def evaluate_pokemon_long_term_plan(
    planner: StrategicBattlePlanner,
    pokemon: PokemonState,
    defender: PokemonState,
):
    """
    Evaluate the best long-term attack plan for one Pokémon.
    """

    best_plan = choose_best_multi_turn_plan(
        planner,
        pokemon,
        defender,
    )

    if best_plan is None:
        return {
            "pokemon": pokemon,
            "name": pokemon.card.get("name", "Unknown Pokémon"),
            "best_plan": None,
            "plan_score": -1000.0,
            "first_usable_turn": None,
            "can_knock_out": False,
        }

    return {
        "pokemon": pokemon,
        "name": pokemon.card.get("name", "Unknown Pokémon"),
        "best_plan": best_plan,
        "plan_score": best_plan["plan_score"],
        "first_usable_turn": best_plan["first_usable_turn"],
        "can_knock_out": best_plan["can_knock_out"],
    }

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: evaluate_all_player_pokemon
----------------------------------------------------------------------------------------------------
def evaluate_all_player_pokemon(
    planner: StrategicBattlePlanner,
    player_state: PlayerState,
    defender: PokemonState,
):
    """
    Evaluate the Active Pokémon and every Benched Pokémon.
    """

    candidates = [
        player_state.active,
        *player_state.bench,
    ]

    evaluations = []

    for pokemon in candidates:
        evaluation = evaluate_pokemon_long_term_plan(
            planner,
            pokemon,
            defender,
        )

        evaluation["role"] = (
            "Active"
            if pokemon.is_active
            else "Bench"
        )

        evaluations.append(evaluation)

    return evaluations

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: evaluate_strategic_switch
----------------------------------------------------------------------------------------------------
def evaluate_strategic_switch(
    planner: StrategicBattlePlanner,
    player_state: PlayerState,
    defender: PokemonState,
    switching_penalty=40,
    minimum_improvement=25,
):
    """
    Decide whether switching to a Bench Pokémon is strategically justified.
    """

    best_choice, candidates = choose_best_strategic_pokemon(
        planner,
        player_state,
        defender,
        switching_penalty=switching_penalty,
    )

    active_evaluation = next(
        candidate
        for candidate in candidates
        if candidate["role"] == "Active"
    )

    improvement = (
        best_choice["adjusted_score"]
        - active_evaluation["adjusted_score"]
    )

    should_switch = (
        best_choice["role"] == "Bench"
        and improvement >= minimum_improvement
    )

    if should_switch:
        reason = (
            f"Switch to {best_choice['name']} because its "
            f"adjusted strategic score is "
            f"{improvement:.2f} points higher than the "
            f"current Active Pokémon."
        )
    else:
        reason = (
            f"Keep {active_evaluation['name']} Active. "
            f"No Bench Pokémon improves the strategic "
            f"outlook by at least {minimum_improvement} points."
        )

    return {
        "should_switch": should_switch,
        "target": (
            best_choice["pokemon"]
            if should_switch
            else None
        ),
        "best_choice": best_choice,
        "active_evaluation": active_evaluation,
        "improvement": round(improvement, 2),
        "reason": reason,
        "candidates": candidates,
    }

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: simulate_future_state
----------------------------------------------------------------------------------------------------
def simulate_future_state(
    battle_state,
    damage,
):

    future = deepcopy(battle_state)

    opponent = future.opponent.active

    opponent.current_hp = max(
        0,
        opponent.current_hp - damage,
    )

    return future

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: evaluate_future_state
----------------------------------------------------------------------------------------------------
def evaluate_future_state(future_battle: BattleState):
    """
    Score a future battle position from the player's perspective.

    Positive scores favor the player.
    Negative scores favor the opponent.
    """

    player_active = future_battle.player.active
    opponent_active = future_battle.opponent.active

    player_max_hp = float(
        player_active.card.get("hp", 0) or 0
    )

    opponent_max_hp = float(
        opponent_active.card.get("hp", 0) or 0
    )

    player_hp_ratio = (
        player_active.current_hp / player_max_hp
        if player_max_hp > 0
        else 0
    )

    opponent_hp_ratio = (
        opponent_active.current_hp / opponent_max_hp
        if opponent_max_hp > 0
        else 0
    )

    score = 0.0

    # Reward preserving the player's Active Pokémon.
    score += player_hp_ratio * 100

    # Reward damaging the opponent.
    score += (1 - opponent_hp_ratio) * 100

    # Large reward for a Knock Out.
    if opponent_active.current_hp <= 0:
        score += 500

    # Large penalty if the player's Active Pokémon is Knocked Out.
    if player_active.current_hp <= 0:
        score -= 500

    return round(score, 2)

====================================================================================================
FILE: scripts\09_strategic_battle_ai.py
OBJECT: simulate_future_state
----------------------------------------------------------------------------------------------------
def simulate_future_state(
    battle_state: BattleState,
    damage: float,
):
    """
    Create a copied battle state and apply attack damage
    to the opponent's Active Pokémon.
    """

    future_state = deepcopy(battle_state)

    future_opponent = (
        future_state.opponent.active
    )

    future_opponent.current_hp = max(
        0.0,
        future_opponent.current_hp - damage,
    )

    future_state.turn_number += 1

    return future_state

====================================================================================================
FILE: scripts\10_minimax_opponent_ai.py
OBJECT: evaluate_position
----------------------------------------------------------------------------------------------------
def evaluate_position(
    battle_state: BattleState,
):
    """
    Evaluate a battle position from the Player's perspective.

    Positive score:
        position favors the Player.

    Negative score:
        position favors the Opponent.
    """

    player_active = battle_state.player.active
    opponent_active = battle_state.opponent.active

    player_max_hp = safe_max_hp(
        player_active
    )

    opponent_max_hp = safe_max_hp(
        opponent_active
    )

    player_hp_ratio = (
        player_active.current_hp / player_max_hp
        if player_max_hp > 0
        else 0.0
    )

    opponent_hp_ratio = (
        opponent_active.current_hp / opponent_max_hp
        if opponent_max_hp > 0
        else 0.0
    )

    score = 0.0

    # Preserve the Player's Active Pokémon.
    score += player_hp_ratio * 100

    # Reward damage already dealt to the Opponent.
    score += (1 - opponent_hp_ratio) * 100

    # Penalize damage already taken by the Player.
    score -= (1 - player_hp_ratio) * 100

    # Energy advantage.
    energy_difference = (
        player_active.attached_energy
        - opponent_active.attached_energy
    )

    score += energy_difference * 15

    # Bench health advantage.
    player_bench_hp = total_bench_hp(
        battle_state.player.bench
    )

    opponent_bench_hp = total_bench_hp(
        battle_state.opponent.bench
    )

    score += (
        player_bench_hp
        - opponent_bench_hp
    ) * 0.10

    # Prize progress.
    player_prizes_taken = (
        6
        - battle_state.player.prize_cards_remaining
    )

    opponent_prizes_taken = (
        6
        - battle_state.opponent.prize_cards_remaining
    )

    score += (
        player_prizes_taken
        - opponent_prizes_taken
    ) * 150

    # Terminal Knock Out bonuses.
    if opponent_active.current_hp <= 0:
        score += 500

    if player_active.current_hp <= 0:
        score -= 500

    return round(score, 2)

====================================================================================================
FILE: scripts\10_minimax_opponent_ai.py
OBJECT: evaluate_root_moves
----------------------------------------------------------------------------------------------------
def evaluate_root_moves(
    battle_state: BattleState,
    depth: int,
):
    """
    Evaluate every legal move from the root battle state.
    """

    if battle_state.current_player != "Player":
        raise ValueError(
            "Root move evaluation requires "
            "current_player='Player'."
        )

    results = []

    legal_moves = get_current_legal_moves(
        battle_state
    )

    for move in legal_moves:
        future_state = apply_move(
            battle_state,
            move,
        )

        score = minimax(
            future_state,
            depth=max(depth - 1, 0),
        )

        results.append({
            "move": move,
            "score": round(score, 2),
            "future_state": future_state,
        })

    return sorted(
        results,
        key=lambda result: (
            result["score"],
            result["move"]["damage"],
            -result["move"]["energy_cost"],
        ),
        reverse=True,
    )

====================================================================================================
FILE: scripts\11_advanced_search_engine.py
OBJECT: EngineBenchmarkResult
----------------------------------------------------------------------------------------------------
class EngineBenchmarkResult:
    """One completed search-engine benchmark."""

    engine_name: str
    best_move: str
    score: float
    completed_depth: int

    nodes: int
    leaf_nodes: int
    terminal_nodes: int
    cutoffs: int

    transposition_hits: int
    killer_hits: int
    history_hits: int

    elapsed_seconds: float
    nodes_per_second: float

    principal_variation: List[str]

    def as_dict(self) -> Dict[str, Any]:
        return {
            "engine": self.engine_name,
            "best_move": self.best_move,
            "score": self.score,
            "depth": self.completed_depth,
            "nodes": self.nodes,
            "leaf_nodes": self.leaf_nodes,
            "terminal_nodes": self.terminal_nodes,
            "cutoffs": self.cutoffs,
            "tt_hits": self.transposition_hits,
            "killer_hits": self.killer_hits,
            "history_hits": self.history_hits,
            "elapsed_seconds": round(
                self.elapsed_seconds,
                6,
            ),
            "nodes_per_second": round(
                self.nodes_per_second,
                2,
            ),
            "principal_variation": (
                " â†’ ".join(self.principal_variation)
            ),
        }

====================================================================================================
FILE: scripts\11_advanced_search_engine.py
OBJECT: benchmark_engine
----------------------------------------------------------------------------------------------------
def benchmark_engine(
    engine_name: str,
    engine: AdvancedSearchEngine,
    state: BattleState,
    depth: int,
) -> EngineBenchmarkResult:
    """
    Run one fixed-depth benchmark and return a normalized result.
    """

    result = engine.search_depth(
        state=state,
        depth=depth,
        clear_table=True,
        clear_killers=True,
        clear_history=True,
    )

    best_move_name = (
        engine.move_to_string(result.best_move)
        if result.best_move is not None
        else "None"
    )

    pv_names = [
        engine.move_to_string(move)
        for move in result.principal_variation
    ]

    return EngineBenchmarkResult(
        engine_name=engine_name,
        best_move=best_move_name,
        score=float(result.score),
        completed_depth=result.completed_depth,

        nodes=result.stats.nodes,
        leaf_nodes=result.stats.leaf_nodes,
        terminal_nodes=result.stats.terminal_nodes,
        cutoffs=result.stats.cutoffs,

        transposition_hits=(
            result.stats.transposition_hits
        ),
        killer_hits=result.stats.killer_hits,
        history_hits=result.stats.history_hits,

        elapsed_seconds=result.stats.elapsed_seconds,
        nodes_per_second=(
            result.stats.nodes_per_second
        ),

        principal_variation=pv_names,
    )

====================================================================================================
FILE: scripts\12_integrated_battle_agent.py
OBJECT: simulate_ai_battle
----------------------------------------------------------------------------------------------------
def simulate_ai_battle(
    initial_state: BattleState,
    agent: PokemonBattleAgent,
    search_depth: int = 6,
    max_turns: int = 20,
    verbose: bool = True,
) -> BattleSimulationResult:

    current_state = deepcopy(initial_state)
    turn_records = []

    for _ in range(max_turns):

        winner = determine_battle_winner(current_state)

        if winner is not None:
            return BattleSimulationResult(
                final_state=current_state,
                turns=turn_records,
                winner=winner,
                stop_reason="Battle reached a terminal state.",
            )

        acting_side = current_state.current_player

        if acting_side == "Player":
            active_pokemon = current_state.player.active
        elif acting_side == "Opponent":
            active_pokemon = current_state.opponent.active
        else:
            raise ValueError(
                "current_player must be 'Player' or 'Opponent'."
            )

        decision = agent.choose_move(
            state=current_state,
            depth=search_depth,
        )

        next_state = apply_move(
            current_state,
            decision.move,
        )

        record = BattleTurnRecord(
            turn_number=current_state.turn_number,
            acting_side=acting_side,
            pokemon_name=active_pokemon.card["name"],
            move_name=decision.move["name"],
            damage=float(
                decision.move.get("damage", 0) or 0
            ),
            score=decision.score,
            search_depth=decision.search_depth,
            nodes=decision.nodes,
            player_hp_after=next_state.player.active.current_hp,
            opponent_hp_after=next_state.opponent.active.current_hp,
            next_side=next_state.current_player,
        )

        turn_records.append(record)

        if verbose:
            print(
                f"Turn {record.turn_number}: "
                f"{record.acting_side} — "
                f"{record.pokemon_name} used "
                f"{record.move_name}"
            )
            print(
                f"  Player HP: {record.player_hp_after} | "
                f"Opponent HP: {record.opponent_hp_after}"
            )

        current_state = next_state

    winner = determine_battle_winner(current_state)

    return BattleSimulationResult(
        final_state=current_state,
        turns=turn_records,
        winner=winner,
        stop_reason=(
            "Maximum turn limit reached."
            if winner is None
            else "Battle reached a terminal state."
        ),
    )

====================================================================================================
FILE: scripts\13_tournament_self_play_evaluation.py
OBJECT: run_match
----------------------------------------------------------------------------------------------------
def run_match(
    match: TournamentMatch,
    initial_state: BattleState,
):

    simulation = simulate_ai_battle(
        initial_state=initial_state,
        agent=match.player_agent,
        search_depth=match.search_depth,
        max_turns=match.max_turns,
        verbose=False,
    )

    winner = determine_battle_winner(
        simulation.final_state
    )

    winner_name = (
        match.player_name
        if winner == "Player"
        else match.opponent_name
    )

    return TournamentResult(
        winner=winner_name,
        turns=len(simulation.turns),
        final_score=simulation.final_state.player.active.current_hp
        - simulation.final_state.opponent.active.current_hp,
        transcript=create_battle_transcript(simulation),
    )

====================================================================================================
FILE: scripts\13_tournament_self_play_evaluation.py
OBJECT: run_match_series

                            validation  observed expected  passed
0         baseline-related files found        87      > 0    True
1   baseline/harness definitions found       511      > 0    True
2        exact baseline contexts found        22      > 0    True
3  tournament harness candidates found        69      > 0    True

====================================================================================================
✅ HISTORICAL BASELINE IMPLEMENTATIONS LOCATED
✅ TOURNAMENT HARNESS CANDIDATES LOCATED
✅ READY TO RECONSTRUCT FAIR R3 BENCHMARK
✅ SECTION 2B COMPLETE
====================================================================================================

In [10]:
# ==========================================================================================
# SECTION 2C — RESOLVE EXACT NOTEBOOK 48 BASELINE AGENTS AND HARNESS PARAMETERS
# ==========================================================================================

print("=" * 100)
print("SECTION 2C — RESOLVE EXACT NOTEBOOK 48 BASELINE AGENTS AND HARNESS PARAMETERS")
print("=" * 100)

from pathlib import Path
import ast
import re
import pandas as pd


# ==========================================================================================
# 1. Exact historical baseline labels
# ==========================================================================================

BASELINE_LABELS_2C = [
    "Depth-6 Search Baseline",
    "Greedy Damage Baseline",
    "Random Baseline",
]


# ==========================================================================================
# 2. Search exact baseline labels in Python sources and capture surrounding code
# ==========================================================================================

exact_context_rows_2c = []

for root in [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
]:

    if not root.exists():
        continue

    for path in root.rglob("*.py"):

        if "__pycache__" in path.parts:
            continue

        try:
            lines = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            ).splitlines()

        except Exception:
            continue

        for idx, line in enumerate(lines):

            if not any(
                label.lower() in line.lower()
                for label in BASELINE_LABELS_2C
            ):
                continue

            start = max(
                0,
                idx - 40,
            )

            end = min(
                len(lines),
                idx + 80,
            )

            exact_context_rows_2c.append(
                {
                    "file":
                        str(
                            path.relative_to(
                                PROJECT_ROOT
                            )
                        ),

                    "line_number":
                        idx + 1,

                    "matched_line":
                        line.strip(),

                    "context":
                        "\n".join(
                            lines[start:end]
                        ),
                }
            )


section2c_exact_context_df = pd.DataFrame(
    exact_context_rows_2c
)


print("\nEXACT BASELINE SOURCE CONTEXTS")
print("-" * 100)

if section2c_exact_context_df.empty:

    print(
        "No exact baseline source contexts found."
    )

else:

    display(
        section2c_exact_context_df[
            [
                "file",
                "line_number",
                "matched_line",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 3. Print exact baseline contexts in readable form
# ==========================================================================================

print("\nDETAILED EXACT BASELINE CONTEXTS")
print("-" * 100)

for _, row in (
    section2c_exact_context_df
    .drop_duplicates(
        subset=[
            "file",
            "line_number",
        ]
    )
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        "FILE:",
        row["file"],
    )

    print(
        "LINE:",
        row["line_number"],
    )

    print(
        "MATCH:",
        row["matched_line"],
    )

    print("-" * 100)

    print(
        row["context"]
    )


# ==========================================================================================
# 4. Search for historical tournament configuration values
# ==========================================================================================

CONFIG_PATTERNS_2C = [
    "matches_per_baseline",
    "number_of_matches",
    "alternate_starting_side",
    "search_depth",
    "max_turns",
    "baseline_name",
    "evaluated_agent_side",
    "Depth-6 Search Baseline",
    "Greedy Damage Baseline",
    "Random Baseline",
]


config_rows_2c = []


for root in [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
]:

    if not root.exists():
        continue

    for path in root.rglob("*.py"):

        if "__pycache__" in path.parts:
            continue

        try:

            lines = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            ).splitlines()

        except Exception:
            continue


        for line_number, line in enumerate(
            lines,
            start=1,
        ):

            line_lower = line.lower()

            if not any(
                pattern.lower() in line_lower
                for pattern in CONFIG_PATTERNS_2C
            ):
                continue

            config_rows_2c.append(
                {
                    "file":
                        str(
                            path.relative_to(
                                PROJECT_ROOT
                            )
                        ),

                    "line_number":
                        line_number,

                    "source_line":
                        line.strip(),
                }
            )


section2c_config_lines_df = pd.DataFrame(
    config_rows_2c
)


print("\nHISTORICAL HARNESS CONFIGURATION LINES")
print("-" * 100)

display(
    section2c_config_lines_df
    .drop_duplicates()
    .reset_index(drop=True)
)


# ==========================================================================================
# 5. Find likely baseline agent classes/functions
# ==========================================================================================

TARGET_AGENT_TOKENS_2C = [
    "greedy",
    "random",
    "search",
    "baseline",
]


agent_definition_rows_2c = []


for root in [
    PROJECT_ROOT / "scripts",
    PROJECT_ROOT / "src",
]:

    if not root.exists():
        continue

    for path in root.rglob("*.py"):

        if "__pycache__" in path.parts:
            continue

        try:

            source_text = path.read_text(
                encoding="utf-8-sig",
                errors="ignore",
            )

            tree = ast.parse(
                source_text
            )

        except Exception:
            continue


        for node in ast.walk(tree):

            if not isinstance(
                node,
                (
                    ast.ClassDef,
                    ast.FunctionDef,
                    ast.AsyncFunctionDef,
                ),
            ):
                continue

            name_lower = node.name.lower()

            if not any(
                token in name_lower
                for token in TARGET_AGENT_TOKENS_2C
            ):
                continue

            source_segment = ast.get_source_segment(
                source_text,
                node,
            )

            agent_definition_rows_2c.append(
                {
                    "file":
                        str(
                            path.relative_to(
                                PROJECT_ROOT
                            )
                        ),

                    "object_type":
                        (
                            "CLASS"
                            if isinstance(
                                node,
                                ast.ClassDef
                            )
                            else
                            "FUNCTION"
                        ),

                    "name":
                        node.name,

                    "line_number":
                        node.lineno,

                    "source":
                        source_segment,
                }
            )


section2c_agent_definitions_df = pd.DataFrame(
    agent_definition_rows_2c
)


print("\nBASELINE AGENT DEFINITION CANDIDATES")
print("-" * 100)

if section2c_agent_definitions_df.empty:

    print(
        "No baseline agent definitions found."
    )

else:

    display(
        section2c_agent_definitions_df[
            [
                "file",
                "object_type",
                "name",
                "line_number",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 6. Narrow to files containing exact historical labels
# ==========================================================================================

exact_files_2c = sorted(
    section2c_exact_context_df[
        "file"
    ]
    .dropna()
    .unique()
    .tolist()
)


print("\nFILES CONTAINING EXACT HISTORICAL LABELS")
print("-" * 100)

for file_name in exact_files_2c:
    print(file_name)


# ==========================================================================================
# 7. Extract source from exact historical files
# ==========================================================================================

exact_file_definition_rows_2c = []


for relative_file in exact_files_2c:

    path = (
        PROJECT_ROOT
        / relative_file
    )

    if path.suffix.lower() != ".py":
        continue

    try:

        source_text = path.read_text(
            encoding="utf-8-sig",
            errors="ignore",
        )

        tree = ast.parse(
            source_text
        )

    except Exception:
        continue


    for node in ast.walk(tree):

        if not isinstance(
            node,
            (
                ast.ClassDef,
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        ):
            continue

        source_segment = ast.get_source_segment(
            source_text,
            node,
        )

        if source_segment is None:
            continue

        source_lower = source_segment.lower()

        if any(
            label.lower() in source_lower
            for label in BASELINE_LABELS_2C
        ) or any(
            token in node.name.lower()
            for token in [
                "baseline",
                "tournament",
                "match",
                "evaluate",
                "greedy",
                "random",
                "search",
            ]
        ):

            exact_file_definition_rows_2c.append(
                {
                    "file":
                        relative_file,

                    "object_type":
                        (
                            "CLASS"
                            if isinstance(
                                node,
                                ast.ClassDef
                            )
                            else
                            "FUNCTION"
                        ),

                    "name":
                        node.name,

                    "line_number":
                        node.lineno,

                    "source":
                        source_segment,
                }
            )


section2c_exact_file_definitions_df = pd.DataFrame(
    exact_file_definition_rows_2c
)


print("\nDEFINITIONS FROM EXACT HISTORICAL FILES")
print("-" * 100)

if section2c_exact_file_definitions_df.empty:

    print(
        "No definitions extracted from exact files."
    )

else:

    display(
        section2c_exact_file_definitions_df[
            [
                "file",
                "object_type",
                "name",
                "line_number",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ==========================================================================================
# 8. Print top exact historical source definitions
# ==========================================================================================

print("\nTOP EXACT HISTORICAL SOURCE DEFINITIONS")
print("-" * 100)

for _, row in (
    section2c_exact_file_definitions_df
    .head(25)
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        "FILE:",
        row["file"],
    )

    print(
        "OBJECT:",
        row["name"],
    )

    print("-" * 100)

    print(
        row["source"]
    )


# ==========================================================================================
# 9. Confirm known historical harness structure
# ==========================================================================================

historical_harness_lock_2c = {
    "total_matches":
        300,

    "baseline_count":
        3,

    "matches_per_baseline":
        100,

    "matches_per_side_per_baseline":
        50,

    "sides":
        [
            "Player",
            "Opponent",
        ],

    "alternate_starting_side":
        True,

    "depth_search_baseline_label":
        "Depth-6 Search Baseline",

    "greedy_baseline_label":
        "Greedy Damage Baseline",

    "random_baseline_label":
        "Random Baseline",

    "r3_retraining":
        False,

    "r3_model_modification":
        False,
}


print("\nHISTORICAL HARNESS LOCK")
print("-" * 100)

for key, value in (
    historical_harness_lock_2c.items()
):

    print(
        f"{key:<40}: {value}"
    )


# ==========================================================================================
# 10. Save evidence
# ==========================================================================================

SECTION2C_CONTEXT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2c_exact_baseline_contexts.csv"
)

SECTION2C_CONFIG_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2c_harness_configuration_lines.csv"
)

SECTION2C_AGENT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2c_baseline_agent_definitions.csv"
)

SECTION2C_LOCK_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2c_historical_harness_lock.json"
)


section2c_exact_context_df.to_csv(
    SECTION2C_CONTEXT_FILE,
    index=False,
)

section2c_config_lines_df.to_csv(
    SECTION2C_CONFIG_FILE,
    index=False,
)

section2c_agent_definitions_df.to_csv(
    SECTION2C_AGENT_FILE,
    index=False,
)


with open(
    SECTION2C_LOCK_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        historical_harness_lock_2c,
        file,
        indent=2,
    )


# ==========================================================================================
# 11. Validation
# ==========================================================================================

section2c_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exact historical labels found",

            "observed":
                len(
                    section2c_exact_context_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2c_exact_context_df
                ) > 0,
        },

        {
            "validation":
                "historical config lines found",

            "observed":
                len(
                    section2c_config_lines_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2c_config_lines_df
                ) > 0,
        },

        {
            "validation":
                "baseline agent candidates found",

            "observed":
                len(
                    section2c_agent_definitions_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2c_agent_definitions_df
                ) > 0,
        },

        {
            "validation":
                "exact historical files identified",

            "observed":
                len(
                    exact_files_2c
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    exact_files_2c
                ) > 0,
        },

        {
            "validation":
                "historical harness lock saved",

            "observed":
                SECTION2C_LOCK_FILE.exists(),

            "expected":
                True,

            "passed":
                SECTION2C_LOCK_FILE.exists(),
        },
    ]
)


print("\nSECTION 2C VALIDATION")
print("-" * 100)

display(
    section2c_validation_df
)


assert (
    section2c_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 48 BASELINE LABELS RECOVERED")
print("✅ HISTORICAL HARNESS PARAMETERS RECOVERED")
print("✅ BASELINE AGENT CANDIDATES IDENTIFIED")
print("✅ EXACT HISTORICAL SOURCE FILES IDENTIFIED")
print("✅ 300 / 100 / 50+50 MATCH STRUCTURE LOCKED")
print("✅ NO R3 RETRAINING OR MODEL MODIFICATION")
print("✅ SECTION 2C COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2C — RESOLVE EXACT NOTEBOOK 48 BASELINE AGENTS AND HARNESS PARAMETERS
====================================================================================================

EXACT BASELINE SOURCE CONTEXTS
----------------------------------------------------------------------------------------------------

,file,line_number,matched_line
0,scripts\48_tournament_evaluation_and_elo_bench...,1879,# 3.5 â€” Random baseline agent
1,scripts\48_tournament_evaluation_and_elo_bench...,1983,# 3.6 â€” Greedy damage baseline
2,scripts\48_tournament_evaluation_and_elo_bench...,2964,"""Random Baseline"","
3,scripts\48_tournament_evaluation_and_elo_bench...,2971,"""Greedy Damage Baseline"","
4,scripts\48_tournament_evaluation_and_elo_bench...,2981,"""Depth-6 Search Baseline"","
5,scripts\48_tournament_evaluation_and_elo_bench...,3201,# - Random Baseline
6,scripts\48_tournament_evaluation_and_elo_bench...,3202,# - Greedy Damage Baseline
7,scripts\48_tournament_evaluation_and_elo_bench...,3203,# - Depth-6 Search Baseline
8,scripts\48_tournament_evaluation_and_elo_bench...,3286,"name=""Random Baseline"","
9,scripts\48_tournament_evaluation_and_elo_bench...,3292,"name=""Greedy Damage Baseline"","
10,scripts\48_tournament_evaluation_and_elo_bench...,3302,"""Depth-6 Search Baseline"","
11,scripts\48_tournament_evaluation_and_elo_bench...,3307,"""Random Baseline"":"
12,scripts\48_tournament_evaluation_and_elo_bench...,3313,"""Greedy Damage Baseline"":"
13,scripts\48_tournament_evaluation_and_elo_bench...,3317,"""Depth-6 Search Baseline"":"
14,scripts\48_tournament_evaluation_and_elo_bench...,5190,"== ""Random Baseline"""
15,scripts\48_tournament_evaluation_and_elo_bench...,5197,"== ""Greedy Damage Baseline"""
16,scripts\48_tournament_evaluation_and_elo_bench...,5204,"== ""Depth-6 Search Baseline"""
17,scripts\48_tournament_evaluation_and_elo_bench...,5299,"""the depth-6 search baseline."""
18,scripts\48_tournament_evaluation_and_elo_bench...,5368,"f""Win rate against the depth-6 search baseline """
19,scripts\48_tournament_evaluation_and_elo_bench...,5474,"""Random baseline win rate"","
20,scripts\48_tournament_evaluation_and_elo_bench...,5743,Random baseline win rate: {random_win_rate:.4f}
21,scripts\49_side_balanced_search_guided_self_pl...,16,# - Improve performance against the Depth-6 Se...

DETAILED EXACT BASELINE CONTEXTS
----------------------------------------------------------------------------------------------------

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 1879
MATCH: # 3.5 â€” Random baseline agent
----------------------------------------------------------------------------------------------------
            "damage_numeric",
            "base_damage",
        ):
            if key in move:
                try:
                    return float(
                        move[key] or 0.0
                    )
                except (
                    TypeError,
                    ValueError,
                ):
                    return 0.0

        return 0.0

    for attribute_name in (
        "damage",
        "damage_numeric",
        "base_damage",
    ):
        value = getattr(
            move,
            attribute_name,
            None,
        )

        if value is not None:
            try:
                return float(value or 0.0)
            except (
                TypeError,
                ValueError,
            ):
                return 0.0

    return 0.0


# ------------------------------------------------------------
# 3.5 â€” Random baseline agent
# ------------------------------------------------------------

class RandomLegalMoveAgent:
    def __init__(
        self,
        seed: int = RANDOM_SEED,
        name: str = "Random Legal Agent",
    ) -> None:
        self.name = name
        self.random = random.Random(
            seed
        )
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_move = (
            self.random.choice(
                legal_moves
            )
        )

        confidence = (
            1.0
            / len(legal_moves)
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    confidence,

                search_depth=int(
                    depth or 0
                ),

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 1983
MATCH: # 3.6 â€” Greedy damage baseline
----------------------------------------------------------------------------------------------------
        confidence = (
            1.0
            / len(legal_moves)
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    confidence,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=
                    confidence,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision


# ------------------------------------------------------------
# 3.6 â€” Greedy damage baseline
# ------------------------------------------------------------

class GreedyDamageAgent:
    def __init__(
        self,
        name: str = "Greedy Damage Agent",
    ) -> None:
        self.name = name
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_index = max(
            range(
                len(legal_moves)
            ),
            key=lambda index: (
                tournament_move_damage(
                    legal_moves[index]
                ),
                -index,
            ),
        )

        selected_move = (
            legal_moves[
                selected_index
            ]
        )

        maximum_damage = (
            tournament_move_damage(
                selected_move
            )
        )

        self.last_decision = (
            TournamentDecision(

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2964
MATCH: "Random Baseline",
----------------------------------------------------------------------------------------------------
                agent_result
            ),

        fallback_count=
            int(
                side_agent
                .fallback_count
            ),

        elapsed_seconds=
            float(
                elapsed_seconds
            ),
    )


# ------------------------------------------------------------
# 3.12 â€” Instantiate agents
# ------------------------------------------------------------

competitive_tournament_agent = (
    CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )
)

random_baseline_agent = (
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],
    start=1,
):
    smoke_result = run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=
            baseline_agent,

        player_card=
            smoke_player_card,

        opponent_card=
            smoke_opponent_card,

        starting_side=
            "Player",

        evaluated_agent_side=
            "Player",

        max_turns=
            20,

        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        verbose=False,
    )

    smoke_test_results.append(
        dataclasses.asdict(
            smoke_result
        )
    )

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2971
MATCH: "Greedy Damage Baseline",
----------------------------------------------------------------------------------------------------
            ),

        elapsed_seconds=
            float(
                elapsed_seconds
            ),
    )


# ------------------------------------------------------------
# 3.12 â€” Instantiate agents
# ------------------------------------------------------------

competitive_tournament_agent = (
    CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )
)

random_baseline_agent = (
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],
    start=1,
):
    smoke_result = run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=
            baseline_agent,

        player_card=
            smoke_player_card,

        opponent_card=
            smoke_opponent_card,

        starting_side=
            "Player",

        evaluated_agent_side=
            "Player",

        max_turns=
            20,

        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        verbose=False,
    )

    smoke_test_results.append(
        dataclasses.asdict(
            smoke_result
        )
    )


smoke_test_df = pd.DataFrame(
    smoke_test_results
)



====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 2981
MATCH: "Depth-6 Search Baseline",
----------------------------------------------------------------------------------------------------
# 3.12 â€” Instantiate agents
# ------------------------------------------------------------

competitive_tournament_agent = (
    CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )
)

random_baseline_agent = (
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],
    start=1,
):
    smoke_result = run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=
            baseline_agent,

        player_card=
            smoke_player_card,

        opponent_card=
            smoke_opponent_card,

        starting_side=
            "Player",

        evaluated_agent_side=
            "Player",

        max_turns=
            20,

        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        verbose=False,
    )

    smoke_test_results.append(
        dataclasses.asdict(
            smoke_result
        )
    )


smoke_test_df = pd.DataFrame(
    smoke_test_results
)


# ------------------------------------------------------------
# 3.14 â€” Save adapter report
# ------------------------------------------------------------

MATCH_ADAPTER_REPORT_FILE = (
    NOTEBOOK48_REPORT_DIR
    / "tournament_match_adapter_summary.json"
)

match_adapter_report = {

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3201
MATCH: # - Random Baseline
----------------------------------------------------------------------------------------------------

assert MATCH_ADAPTER_REPORT_FILE.exists()

assert len(
    smoke_test_df
) == 3

assert (
    smoke_test_df[
        "turns"
    ]
    > 0
).all()

assert (
    smoke_test_df[
        "fallback_count"
    ]
    == 0
).all()

assert smoke_test_df[
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#
# #### Each pairing uses multiple card matchups and both evaluated-agent sides.

# In[6]:


# ============================================================
# NOTEBOOK 48
# SECTION 4 â€” FULL BASELINE TOURNAMENT
# ============================================================


import dataclasses
import json
import math
import random
import time
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 4.3 â€” Tournament configuration
# ------------------------------------------------------------

TOURNAMENT_MATCHES_PER_BASELINE = (
    INITIAL_MATCHES_PER_PAIRING
)

TOURNAMENT_PROGRESS_INTERVAL = 25

TOURNAMENT_RESULTS_FILE = (
    TOURNAMENT_DATA_DIR
    / "competitive_policy_baseline_tournament.csv"
)

TOURNAMENT_SUMMARY_FILE = (
    NOTEBOOK48_REPORT_DIR
    / "competitive_policy_baseline_tournament_summary.json"
)

TOURNAMENT_FAILURE_FILE = (
    NOTEBOOK48_REPORT_DIR
    / "competitive_policy_baseline_tournament_failures.json"
)

TOURNAMENT_RANDOM_SEED = 4804

tournament_random = random.Random(
    TOURNAMENT_RANDOM_SEED
)


# ------------------------------------------------------------
# 4.4 â€” Fresh-agent factory
#
# New instances prevent state, random-generator, or search
# tables from leaking between matches.
# ------------------------------------------------------------

def create_competitive_agent() -> CompetitivePolicyAgent:
    return CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )



====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3202
MATCH: # - Greedy Damage Baseline
----------------------------------------------------------------------------------------------------
assert MATCH_ADAPTER_REPORT_FILE.exists()

assert len(
    smoke_test_df
) == 3

assert (
    smoke_test_df[
        "turns"
    ]
    > 0
).all()

assert (
    smoke_test_df[
        "fallback_count"
    ]
    == 0
).all()

assert smoke_test_df[
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#
# #### Each pairing uses multiple card matchups and both evaluated-agent sides.

# In[6]:


# ============================================================
# NOTEBOOK 48
# SECTION 4 â€” FULL BASELINE TOURNAMENT
# ============================================================


import dataclasses
import json
import math
import random
import time
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 4.3 â€” Tournament configuration
# ------------------------------------------------------------

TOURNAMENT_MATCHES_PER_BASELINE = (
    INITIAL_MATCHES_PER_PAIRING
)

TOURNAMENT_PROGRESS_INTERVAL = 25

TOURNAMENT_RESULTS_FILE = (
    TOURNAMENT_DATA_DIR
    / "competitive_policy_baseline_tournament.csv"
)

TOURNAMENT_SUMMARY_FILE = (
    NOTEBOOK48_REPORT_DIR
    / "competitive_policy_baseline_tournament_summary.json"
)

TOURNAMENT_FAILURE_FILE = (
    NOTEBOOK48_REPORT_DIR
    / "competitive_policy_baseline_tournament_failures.json"
)

TOURNAMENT_RANDOM_SEED = 4804

tournament_random = random.Random(
    TOURNAMENT_RANDOM_SEED
)


# ------------------------------------------------------------
# 4.4 â€” Fresh-agent factory
#
# New instances prevent state, random-generator, or search
# tables from leaking between matches.
# ------------------------------------------------------------

def create_competitive_agent() -> CompetitivePolicyAgent:
    return CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )


def create_random_baseline(

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
LINE: 3203
MATCH: # - Depth-6 Search Baseline
----------------------------------------------------------------------------------------------------

assert len(
    smoke_test_df
) == 3

assert (
    smoke_test_df[
        "turns"
    ]
    > 0
).all()

assert (
    smoke_test_df[
        "fallback_count"
    ]
    == 0
).all()

assert smoke_test_df[
    "agent_result"
].between(
    0.0,
    1.0,
).all()

print()
print(
    "âœ… SECTION 3 TOURNAMENT MATCH ADAPTER PASSED"
)


# ## Section 4 â€” Full Baseline Tournament
#
# #### Run repeated side-swapped matches between the Competitive Policy agent and each baseline.
#
# #### The tournament evaluates:
#
# - Random Baseline
# - Greedy Damage Baseline
# - Depth-6 Search Baseline
#

,file,line_number,source_line
0,scripts\07_battle_engine.py,1766,"max_turns=200,"
1,scripts\07_battle_engine.py,1777,and turns_completed < max_turns
2,scripts\07_battle_engine.py,1797,turns_completed >= max_turns
3,scripts\07_battle_engine.py,1906,"max_turns=200,"
4,scripts\07_battle_engine.py,2003,"max_turns=200,"
...,...,...,...
583,src\tournament\runner.py,52,"depth=match.search_depth,"
584,src\tournament\runner.py,69,"search_depth=decision.search_depth,"
585,src\training\dataset.py,17,"""search_depth"","
586,src\training\dataset.py,42,"""search_depth"": step.search_depth,"
587,src\training\replay.py,20,search_depth: int = 0

BASELINE AGENT DEFINITION CANDIDATES
----------------------------------------------------------------------------------------------------

,file,object_type,name,line_number
0,scripts\10_minimax_opponent_ai.py,CLASS,SearchStatistics,1419
1,scripts\11_advanced_search_engine.py,CLASS,SearchStats,106
2,scripts\11_advanced_search_engine.py,CLASS,SearchResult,170
3,scripts\11_advanced_search_engine.py,CLASS,AdvancedSearchEngine,222
4,scripts\11_advanced_search_engine.py,CLASS,SearchStats,883
5,scripts\11_advanced_search_engine.py,CLASS,AdvancedSearchEngine,978
6,scripts\11_advanced_search_engine.py,CLASS,AdvancedSearchEngine,2923
7,scripts\11_advanced_search_engine.py,CLASS,SearchStats,4078
8,scripts\11_advanced_search_engine.py,CLASS,AdvancedSearchEngine,4201
9,scripts\11_advanced_search_engine.py,CLASS,SearchStats,5188
10,scripts\11_advanced_search_engine.py,CLASS,AdvancedSearchEngine,5304
11,scripts\11_advanced_search_engine.py,CLASS,SearchTimeLimit,6818
12,scripts\11_advanced_search_engine.py,FUNCTION,search_for_time,6883
13,scripts\11_advanced_search_engine.py,FUNCTION,search_depth,430
14,scripts\11_advanced_search_engine.py,FUNCTION,search_depth,1301
15,scripts\11_advanced_search_engine.py,FUNCTION,search_depth,3495
16,scripts\11_advanced_search_engine.py,FUNCTION,search_depth,4796
17,scripts\11_advanced_search_engine.py,FUNCTION,search_depth,6139
18,scripts\16_kaggle_submission_compatibility.py,FUNCTION,create_baseline_build,551
19,scripts\17_official_card_knowledge_base.py,FUNCTION,search_names,1216
20,scripts\32_mixed_opponent_self_play_benchmarks.py,FUNCTION,baseline_match_factory,1075
21,scripts\32_mixed_opponent_self_play_benchmarks.py,CLASS,PolicySearchEngineAdapter,1364
22,scripts\32_mixed_opponent_self_play_benchmarks.py,FUNCTION,search_depth,1372
23,scripts\46_competitive_policy_dataset_generati...,FUNCTION,create_random_battle_state,4217
24,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,RandomLegalMoveAgent,1882
25,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,GreedyDamageAgent,1986
26,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,SearchAgentAdapter,2329
27,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_random_baseline,3281
28,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_greedy_baseline,3290
29,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_search_baseline,3296
30,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,baseline_strength_weight,2532
31,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,get_baseline_strength,6319
32,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,parse_search_result,13697
33,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,search_one_variant,14128
34,src\agents\policies.py,CLASS,RandomPolicy,48
35,src\agents\policies.py,CLASS,GreedyPolicy,70
36,src\agents\policies.py,CLASS,SearchPolicy,136
37,src\card_database\notebook17_export.py,FUNCTION,search_names,1216
38,src\card_database\repository.py,FUNCTION,search_names,77
39,src\card_database\search.py,FUNCTION,search_cards,26
40,src\engine\advanced_search.py,CLASS,SearchStats,138
41,src\engine\advanced_search.py,CLASS,SearchResult,196
42,src\engine\advanced_search.py,CLASS,AdvancedSearchEngine,214
43,src\engine\advanced_search.py,FUNCTION,search_for_time,640
44,src\engine\advanced_search.py,FUNCTION,search_depth,534
45,src\engine\timer.py,CLASS,SearchTimeLimit,10
46,src\observation_adapter\policy_search_adapter.py,CLASS,PolicySearchEngineAdapter,12
47,src\observation_adapter\policy_search_adapter.py,FUNCTION,search_depth,19
48,src\ppo\ppo_policy_engine.py,FUNCTION,search_depth,504

FILES CONTAINING EXACT HISTORICAL LABELS
----------------------------------------------------------------------------------------------------
scripts\48_tournament_evaluation_and_elo_benchmarking.py
scripts\49_side_balanced_search_guided_self_play.py

DEFINITIONS FROM EXACT HISTORICAL FILES
----------------------------------------------------------------------------------------------------

,file,object_type,name,line_number
0,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,TournamentDecision,1789
1,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,tournament_move_name,1805
2,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,tournament_move_damage,1833
3,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,RandomLegalMoveAgent,1882
4,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,GreedyDamageAgent,1986
5,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,tournament_state_key,2114
6,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,tournament_move_key,2267
7,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,SearchAgentAdapter,2329
8,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_tournament_state,2591
9,scripts\48_tournament_evaluation_and_elo_bench...,CLASS,TournamentMatchResult,2677
10,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,run_tournament_match,2696
11,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_random_baseline,3281
12,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_greedy_baseline,3290
13,scripts\48_tournament_evaluation_and_elo_bench...,FUNCTION,create_search_baseline,3296
14,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,baseline_strength_weight,2532
15,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,get_baseline_strength,6319
16,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,parse_search_result,13697
17,scripts\49_side_balanced_search_guided_self_pl...,FUNCTION,search_one_variant,14128

TOP EXACT HISTORICAL SOURCE DEFINITIONS
----------------------------------------------------------------------------------------------------

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: TournamentDecision
----------------------------------------------------------------------------------------------------
class TournamentDecision:
    move: Any
    score: float
    search_depth: int
    nodes: int

    confidence: float = 0.0
    selected_move_name: str | None = None
    fallback: bool = False
    reason: str | None = None

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: tournament_move_name
----------------------------------------------------------------------------------------------------
def tournament_move_name(
    move: Any,
) -> str:
    if isinstance(move, dict):
        return str(
            move.get("name")
            or move.get("Move Name")
            or move.get("move_name")
            or move
        )

    for attribute_name in (
        "name",
        "move_name",
        "attack_name",
    ):
        value = getattr(
            move,
            attribute_name,
            None,
        )

        if value is not None:
            return str(value)

    return str(move)

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: tournament_move_damage
----------------------------------------------------------------------------------------------------
def tournament_move_damage(
    move: Any,
) -> float:
    if isinstance(move, dict):
        for key in (
            "damage",
            "damage_numeric",
            "base_damage",
        ):
            if key in move:
                try:
                    return float(
                        move[key] or 0.0
                    )
                except (
                    TypeError,
                    ValueError,
                ):
                    return 0.0

        return 0.0

    for attribute_name in (
        "damage",
        "damage_numeric",
        "base_damage",
    ):
        value = getattr(
            move,
            attribute_name,
            None,
        )

        if value is not None:
            try:
                return float(value or 0.0)
            except (
                TypeError,
                ValueError,
            ):
                return 0.0

    return 0.0

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: RandomLegalMoveAgent
----------------------------------------------------------------------------------------------------
class RandomLegalMoveAgent:
    def __init__(
        self,
        seed: int = RANDOM_SEED,
        name: str = "Random Legal Agent",
    ) -> None:
        self.name = name
        self.random = random.Random(
            seed
        )
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_move = (
            self.random.choice(
                legal_moves
            )
        )

        confidence = (
            1.0
            / len(legal_moves)
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    confidence,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=
                    confidence,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: GreedyDamageAgent
----------------------------------------------------------------------------------------------------
class GreedyDamageAgent:
    def __init__(
        self,
        name: str = "Greedy Damage Agent",
    ) -> None:
        self.name = name
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_index = max(
            range(
                len(legal_moves)
            ),
            key=lambda index: (
                tournament_move_damage(
                    legal_moves[index]
                ),
                -index,
            ),
        )

        selected_move = (
            legal_moves[
                selected_index
            ]
        )

        maximum_damage = (
            tournament_move_damage(
                selected_move
            )
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    maximum_damage,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=1.0,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: tournament_state_key
----------------------------------------------------------------------------------------------------
def tournament_state_key(
    state: BattleState,
) -> tuple:
    def pokemon_key(
        pokemon: Any,
    ) -> tuple | None:
        if pokemon is None:
            return None

        card = getattr(
            pokemon,
            "card",
            None,
        )

        if isinstance(
            card,
            dict,
        ):
            card_name = (
                card.get("name")
                or card.get("Name")
                or ""
            )
        else:
            card_name = getattr(
                card,
                "name",
                "",
            )

        return (
            str(card_name),

            float(
                getattr(
                    pokemon,
                    "current_hp",
                    0.0,
                )
            ),

            int(
                getattr(
                    pokemon,
                    "attached_energy",
                    0,
                )
            ),

            str(
                getattr(
                    pokemon,
                    "status",
                    None,
                )
            ),

            float(
                getattr(
                    pokemon,
                    "damage",
                    0.0,
                )
            ),

            bool(
                getattr(
                    pokemon,
                    "is_active",
                    False,
                )
            ),
        )

    def player_key(
        player: Any,
    ) -> tuple | None:
        if player is None:
            return None

        bench = getattr(
            player,
            "bench",
            [],
        )

        return (
            pokemon_key(
                getattr(
                    player,
                    "active",
                    None,
                )
            ),

            tuple(
                pokemon_key(pokemon)
                for pokemon in bench
            ),

            int(
                getattr(
                    player,
                    "prize_cards_remaining",
                    0,
                )
            ),

            int(
                getattr(
                    player,
                    "hand_size",
                    0,
                )
            ),
        )

    return (
        player_key(
            getattr(
                state,
                "player",
                None,
            )
        ),

        player_key(
            getattr(
                state,
                "opponent",
                None,
            )
        ),

        int(
            getattr(
                state,
                "turn_number",
                0,
            )
        ),

        str(
            getattr(
                state,
                "current_player",
                "",
            )
        ),
    )

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: tournament_move_key
----------------------------------------------------------------------------------------------------
def tournament_move_key(
    move: Any,
) -> tuple:
    if isinstance(
        move,
        dict,
    ):
        return (
            tournament_move_name(
                move
            ),

            tournament_move_damage(
                move
            ),

            int(
                move.get(
                    "energy_cost",
                    move.get(
                        "cost",
                        0,
                    ),
                )
                or 0
            ),

            repr(
                sorted(
                    move.items(),
                    key=lambda item:
                        str(item[0]),
                )
            ),
        )

    return (
        tournament_move_name(
            move
        ),

        tournament_move_damage(
            move
        ),

        int(
            getattr(
                move,
                "energy_cost",
                getattr(
                    move,
                    "cost",
                    0,
                ),
            )
            or 0
        ),

        repr(move),
    )

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: SearchAgentAdapter
----------------------------------------------------------------------------------------------------
class SearchAgentAdapter:
    def __init__(
        self,
        search_depth: int =
            SIMULATOR_SEARCH_DEPTH,
        name: str =
            "Production Search Agent",
    ) -> None:
        self.name = name

        self.search_depth = int(
            search_depth
        )

        self.search_engine = (
            AdvancedSearchEngine(
                generate_moves=
                    generate_moves_adapter,

                apply_move=
                    apply_move,

                evaluate_state=
                    evaluate_state_adapter,

                is_terminal=
                    terminal_state_adapter,

                current_player=
                    current_player_adapter,

                state_key=
                    tournament_state_key,

                move_key=
                    tournament_move_key,
            )
        )

        self.inner_agent = (
            PokemonBattleAgent(
                engine=
                    self.search_engine
            )
        )

        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> Any:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        resolved_depth = int(
            depth
            if depth is not None
            else self.search_depth
        )

        self.last_decision = (
            self.inner_agent
            .choose_move(
                state=
                    resolved_state,

                depth=
                    resolved_depth,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> Any:
        return self.last_decision

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: create_tournament_state
----------------------------------------------------------------------------------------------------
def create_tournament_state(
    player_card: dict[str, Any],
    opponent_card: dict[str, Any],
    starting_side: str = "Player",
    player_energy: int = 3,
    opponent_energy: int = 3,
) -> BattleState:
    player_card_copy = copy.deepcopy(
        player_card
    )

    opponent_card_copy = copy.deepcopy(
        opponent_card
    )

    return BattleState(
        player=PlayerState(
            active=PokemonState(
                card=
                    player_card_copy,

                current_hp=float(
                    player_card_copy[
                        "hp"
                    ]
                ),

                attached_energy=int(
                    player_energy
                ),

                status=None,

                damage=0.0,

                is_active=True,
            ),

            bench=[],

            prize_cards_remaining=1,

            hand_size=7,
        ),

        opponent=PlayerState(
            active=PokemonState(
                card=
                    opponent_card_copy,

                current_hp=float(
                    opponent_card_copy[
                        "hp"
                    ]
                ),

                attached_energy=int(
                    opponent_energy
                ),

                status=None,

                damage=0.0,

                is_active=True,
            ),

            bench=[],

            prize_cards_remaining=1,

            hand_size=7,
        ),

        turn_number=1,

        current_player=
            starting_side,
    )

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: TournamentMatchResult
----------------------------------------------------------------------------------------------------
class TournamentMatchResult:
    match_id: int
    agent_name: str
    baseline_name: str
    player_card: str
    opponent_card: str
    starting_side: str
    winner: str | None
    turns: int
    stop_reason: str | None
    agent_result: float
    fallback_count: int
    elapsed_seconds: float

====================================================================================================
FILE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
OBJECT: run_tournament_match
----------------------------------------------------------------------------------------------------
def run_tournament_match(
    match_id: int,
    evaluated_agent: Any,
    baseline_agent: Any,
    player_card: dict[str, Any],
    opponent_card: dict[str, Any],
    starting_side: str,
    evaluated_agent_side: str,
    max_turns: int =
        MAX_TURNS_PER_MATCH,
    search_depth: int =
        SIMULATOR_SEARCH_DEPTH,
    verbose: bool =
        VERBOSE_MATCHES,
) -> TournamentMatchResult:
    if evaluated_agent_side not in {
        "Player",
        "Opponent",
    }:
        raise ValueError(
            "evaluated_agent_side must be "
            "'Player' or 'Opponent'."
        )

    initial_state = (
        create_tournament_state(
            player_card=
                player_card,

            opponent_card=
                opponent_card,

            starting_side=
                starting_side,
        )
    )

    class SideAwareAgent:
        def __init__(
            self,
            player_agent: Any,
            opponent_agent: Any,
        ) -> None:
            self.player_agent = (
                player_agent
            )

            self.opponent_agent = (
                opponent_agent
            )

            self.fallback_count = 0

        def choose_move(
            self,
            state: Any = None,
            depth: int | None = None,
            battle_state: Any = None,
            **kwargs: Any,
        ) -> Any:
            resolved_state = (
                state
                if state is not None
                else battle_state
            )

            if resolved_state is None:
                raise ValueError(
                    "A battle state is required."
                )

            side = str(
                resolved_state
                .current_player
            )

            selected_agent = (
                self.player_agent
                if side == "Player"
                else self.opponent_agent
            )

            decision = (
                selected_agent
                .choose_move(
                    state=
                        resolved_state,

                    depth=
                        depth,
                )
            )

            if bool(
                getattr(
                    decision,
                    "fallback",
                    False,
                )
            ):
                self.fallback_count += 1


                          validation observed expected  passed
0      exact historical labels found       22      > 0    True
1      historical config lines found      588      > 0    True
2    baseline agent candidates found       49      > 0    True
3  exact historical files identified        2      > 0    True
4      historical harness lock saved     True     True    True

====================================================================================================
✅ EXACT NOTEBOOK 48 BASELINE LABELS RECOVERED
✅ HISTORICAL HARNESS PARAMETERS RECOVERED
✅ BASELINE AGENT CANDIDATES IDENTIFIED
✅ EXACT HISTORICAL SOURCE FILES IDENTIFIED
✅ 300 / 100 / 50+50 MATCH STRUCTURE LOCKED
✅ NO R3 RETRAINING OR MODEL MODIFICATION
✅ SECTION 2C COMPLETE
====================================================================================================

In [11]:
# ==========================================================================================
# SECTION 2D — INSPECT EXACT NOTEBOOK 48 BENCHMARK IMPLEMENTATION
# ==========================================================================================

print("=" * 100)
print("SECTION 2D — INSPECT EXACT NOTEBOOK 48 BENCHMARK IMPLEMENTATION")
print("=" * 100)

from pathlib import Path
import ast
import pandas as pd


# ==========================================================================================
# 1. Authoritative Notebook 48 script
# ==========================================================================================

NOTEBOOK48_SCRIPT_2D = (
    PROJECT_ROOT
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py"
)

print("\nAUTHORITATIVE SCRIPT")
print("-" * 100)
print(NOTEBOOK48_SCRIPT_2D)

assert NOTEBOOK48_SCRIPT_2D.exists()
assert NOTEBOOK48_SCRIPT_2D.stat().st_size > 0


source_2d = NOTEBOOK48_SCRIPT_2D.read_text(
    encoding="utf-8-sig",
    errors="ignore",
)

tree_2d = ast.parse(source_2d)


# ==========================================================================================
# 2. Exact historical objects required for fair reproduction
# ==========================================================================================

TARGET_OBJECTS_2D = [
    "TournamentDecision",
    "tournament_move_name",
    "tournament_move_damage",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "tournament_state_key",
    "tournament_move_key",
    "SearchAgentAdapter",
    "create_tournament_state",
    "TournamentMatchResult",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


# ==========================================================================================
# 3. Extract exact AST definitions
# ==========================================================================================

objects_2d = {}


for node in tree_2d.body:

    if isinstance(
        node,
        (
            ast.ClassDef,
            ast.FunctionDef,
            ast.AsyncFunctionDef,
        ),
    ):

        if node.name not in TARGET_OBJECTS_2D:
            continue

        source_segment = ast.get_source_segment(
            source_2d,
            node,
        )

        objects_2d[node.name] = {
            "name":
                node.name,

            "object_type":
                (
                    "CLASS"
                    if isinstance(
                        node,
                        ast.ClassDef,
                    )
                    else
                    "FUNCTION"
                ),

            "line_number":
                node.lineno,

            "source":
                source_segment,
        }


section2d_object_inventory_df = pd.DataFrame(
    [
        {
            "name":
                name,

            "object_type":
                data["object_type"],

            "line_number":
                data["line_number"],

            "recovered":
                bool(
                    data["source"]
                ),
        }

        for name, data
        in objects_2d.items()
    ]
)


print("\nEXACT HISTORICAL OBJECT INVENTORY")
print("-" * 100)

display(
    section2d_object_inventory_df
    .sort_values(
        "line_number"
    )
    .reset_index(
        drop=True
    )
)


# ==========================================================================================
# 4. Require every critical object
# ==========================================================================================

CRITICAL_OBJECTS_2D = [
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
    "create_tournament_state",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


missing_critical_2d = [
    name
    for name in CRITICAL_OBJECTS_2D
    if name not in objects_2d
]


print("\nCRITICAL OBJECT CHECK")
print("-" * 100)

if missing_critical_2d:

    print(
        "Missing:",
        missing_critical_2d,
    )

else:

    print(
        "All critical historical benchmark objects recovered."
    )


assert not missing_critical_2d


# ==========================================================================================
# 5. Print ONLY the exact baseline factories first
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT BASELINE FACTORY IMPLEMENTATIONS")
print("=" * 100)


for name in [
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]:

    print("\n" + "-" * 100)
    print(name)
    print("-" * 100)

    print(
        objects_2d[
            name
        ][
            "source"
        ]
    )


# ==========================================================================================
# 6. Print exact baseline agent classes
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT BASELINE AGENT IMPLEMENTATIONS")
print("=" * 100)


for name in [
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
]:

    print("\n" + "-" * 100)
    print(name)
    print("-" * 100)

    print(
        objects_2d[
            name
        ][
            "source"
        ]
    )


# ==========================================================================================
# 7. Print exact historical tournament-state builder
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT TOURNAMENT STATE BUILDER")
print("=" * 100)

print(
    objects_2d[
        "create_tournament_state"
    ][
        "source"
    ]
)


# ==========================================================================================
# 8. Print exact historical tournament-match runner
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT TOURNAMENT MATCH RUNNER")
print("=" * 100)

print(
    objects_2d[
        "run_tournament_match"
    ][
        "source"
    ]
)


# ==========================================================================================
# 9. Discover direct global dependencies for critical objects
# ==========================================================================================

defined_names_2d = set(
    objects_2d.keys()
)

dependency_rows_2d = []


for object_name in CRITICAL_OBJECTS_2D:

    object_source = (
        objects_2d[
            object_name
        ][
            "source"
        ]
    )

    object_tree = ast.parse(
        object_source
    )

    referenced_names = {
        node.id
        for node in ast.walk(
            object_tree
        )
        if isinstance(
            node,
            ast.Name,
        )
    }

    local_names = set()

    for node in ast.walk(
        object_tree
    ):

        if isinstance(
            node,
            ast.arg,
        ):
            local_names.add(
                node.arg
            )

        elif isinstance(
            node,
            (
                ast.FunctionDef,
                ast.ClassDef,
            ),
        ):
            local_names.add(
                node.name
            )

    probable_globals = sorted(
        referenced_names
        -
        local_names
        -
        {
            "self",
            "True",
            "False",
            "None",
        }
    )

    dependency_rows_2d.append(
        {
            "object":
                object_name,

            "probable_global_dependencies":
                probable_globals,
        }
    )


section2d_dependency_df = pd.DataFrame(
    dependency_rows_2d
)


print("\nPROBABLE GLOBAL DEPENDENCIES")
print("-" * 100)

display(
    section2d_dependency_df
)


# ==========================================================================================
# 10. Save exact historical implementation evidence
# ==========================================================================================

SECTION2D_INVENTORY_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2d_historical_object_inventory.csv"
)

SECTION2D_DEPENDENCY_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2d_historical_object_dependencies.csv"
)

SECTION2D_SOURCE_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2d_exact_historical_benchmark_source.txt"
)


section2d_object_inventory_df.to_csv(
    SECTION2D_INVENTORY_FILE,
    index=False,
)

section2d_dependency_df.to_csv(
    SECTION2D_DEPENDENCY_FILE,
    index=False,
)


with open(
    SECTION2D_SOURCE_FILE,
    "w",
    encoding="utf-8",
) as file:

    for name in TARGET_OBJECTS_2D:

        if name not in objects_2d:
            continue

        file.write(
            "\n"
            + "=" * 100
            + "\n"
        )

        file.write(
            name
            + "\n"
        )

        file.write(
            "=" * 100
            + "\n\n"
        )

        file.write(
            objects_2d[
                name
            ][
                "source"
            ]
        )

        file.write(
            "\n\n"
        )


# ==========================================================================================
# 11. Validation
# ==========================================================================================

section2d_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "authoritative script exists",

            "passed":
                NOTEBOOK48_SCRIPT_2D.exists(),
        },

        {
            "validation":
                "random baseline recovered",

            "passed":
                "RandomLegalMoveAgent"
                in objects_2d,
        },

        {
            "validation":
                "greedy baseline recovered",

            "passed":
                "GreedyDamageAgent"
                in objects_2d,
        },

        {
            "validation":
                "search baseline recovered",

            "passed":
                "SearchAgentAdapter"
                in objects_2d,
        },

        {
            "validation":
                "state builder recovered",

            "passed":
                "create_tournament_state"
                in objects_2d,
        },

        {
            "validation":
                "match runner recovered",

            "passed":
                "run_tournament_match"
                in objects_2d,
        },

        {
            "validation":
                "three baseline factories recovered",

            "passed":
                all(
                    name in objects_2d
                    for name in [
                        "create_random_baseline",
                        "create_greedy_baseline",
                        "create_search_baseline",
                    ]
                ),
        },

        {
            "validation":
                "source evidence saved",

            "passed":
                SECTION2D_SOURCE_FILE.exists(),
        },
    ]
)


print("\nSECTION 2D VALIDATION")
print("-" * 100)

display(
    section2d_validation_df
)


assert (
    section2d_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT RANDOM BASELINE IMPLEMENTATION RECOVERED")
print("✅ EXACT GREEDY BASELINE IMPLEMENTATION RECOVERED")
print("✅ EXACT DEPTH-6 SEARCH ADAPTER RECOVERED")
print("✅ EXACT TOURNAMENT STATE BUILDER RECOVERED")
print("✅ EXACT HISTORICAL MATCH RUNNER RECOVERED")
print("✅ THREE BASELINE FACTORIES RECOVERED")
print("✅ DEPENDENCIES INVENTORIED")
print("✅ NO HISTORICAL SCRIPT EXECUTED")
print("✅ SECTION 2D COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2D — INSPECT EXACT NOTEBOOK 48 BENCHMARK IMPLEMENTATION
====================================================================================================

AUTHORITATIVE SCRIPT
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\48_tournament_evaluation_and_elo_benchmarking.py

EXACT HISTORICAL OBJECT INVENTORY
----------------------------------------------------------------------------------------------------

                       name object_type  line_number  recovered
0        TournamentDecision       CLASS         1789       True
1      tournament_move_name    FUNCTION         1805       True
2    tournament_move_damage    FUNCTION         1833       True
3      RandomLegalMoveAgent       CLASS         1882       True
4         GreedyDamageAgent       CLASS         1986       True
5      tournament_state_key    FUNCTION         2114       True
6       tournament_move_key    FUNCTION         2267       True
7        SearchAgentAdapter       CLASS         2329       True
8   create_tournament_state    FUNCTION         2591       True
9     TournamentMatchResult       CLASS         2677       True
10     run_tournament_match    FUNCTION         2696       True
11   create_random_baseline    FUNCTION         3281       True
12   create_greedy_baseline    FUNCTION         3290       True
13   create_search_baseline    FUNCTION         3296       True

CRITICAL OBJECT CHECK
----------------------------------------------------------------------------------------------------
All critical historical benchmark objects recovered.

====================================================================================================
EXACT BASELINE FACTORY IMPLEMENTATIONS
====================================================================================================

----------------------------------------------------------------------------------------------------
create_random_baseline
----------------------------------------------------------------------------------------------------
def create_random_baseline(
    seed: int,
) -> RandomLegalMoveAgent:
    return RandomLegalMoveAgent(
        seed=seed,
        name="Random Baseline",
    )

----------------------------------------------------------------------------------------------------
create_greedy_baseline
----------------------------------------------------------------------------------------------------
def create_greedy_baseline() -> GreedyDamageAgent:
    return GreedyDamageAgent(
        name="Greedy Damage Baseline",
    )

----------------------------------------------------------------------------------------------------
create_search_baseline
----------------------------------------------------------------------------------------------------
def create_search_baseline() -> SearchAgentAdapter:
    return SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )

====================================================================================================
EXACT BASELINE AGENT IMPLEMENTATIONS
====================================================================================================

----------------------------------------------------------------------------------------------------
RandomLegalMoveAgent
----------------------------------------------------------------------------------------------------
class RandomLegalMoveAgent:
    def __init__(
        self,
        seed: int = RANDOM_SEED,
        name: str = "Random Legal Agent",
    ) -> None:
        self.name = name
        self.random = random.Random(
            seed
        )
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_move = (
            self.random.choice(
                legal_moves
            )
        )

        confidence = (
            1.0
            / len(legal_moves)
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    confidence,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=
                    confidence,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision

----------------------------------------------------------------------------------------------------
GreedyDamageAgent
----------------------------------------------------------------------------------------------------
class GreedyDamageAgent:
    def __init__(
        self,
        name: str = "Greedy Damage Agent",
    ) -> None:
        self.name = name
        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_index = max(
            range(
                len(legal_moves)
            ),
            key=lambda index: (
                tournament_move_damage(
                    legal_moves[index]
                ),
                -index,
            ),
        )

        selected_move = (
            legal_moves[
                selected_index
            ]
        )

        maximum_damage = (
            tournament_move_damage(
                selected_move
            )
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    maximum_damage,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=1.0,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> TournamentDecision | None:
        return self.last_decision

----------------------------------------------------------------------------------------------------
SearchAgentAdapter
----------------------------------------------------------------------------------------------------
class SearchAgentAdapter:
    def __init__(
        self,
        search_depth: int =
            SIMULATOR_SEARCH_DEPTH,
        name: str =
            "Production Search Agent",
    ) -> None:
        self.name = name

        self.search_depth = int(
            search_depth
        )

        self.search_engine = (
            AdvancedSearchEngine(
                generate_moves=
                    generate_moves_adapter,

                apply_move=
                    apply_move,

                evaluate_state=
                    evaluate_state_adapter,

                is_terminal=
                    terminal_state_adapter,

                current_player=
                    current_player_adapter,

                state_key=
                    tournament_state_key,

                move_key=
                    tournament_move_key,
            )
        )

        self.inner_agent = (
            PokemonBattleAgent(
                engine=
                    self.search_engine
            )
        )

        self.last_decision = None

    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> Any:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        resolved_depth = int(
            depth
            if depth is not None
            else self.search_depth
        )

        self.last_decision = (
            self.inner_agent
            .choose_move(
                state=
                    resolved_state,

                depth=
                    resolved_depth,
            )
        )

        return self.last_decision

    def get_last_decision(
        self,
    ) -> Any:
        return self.last_decision

====================================================================================================
EXACT TOURNAMENT STATE BUILDER
====================================================================================================
def create_tournament_state(
    player_card: dict[str, Any],
    opponent_card: dict[str, Any],
    starting_side: str = "Player",
    player_energy: int = 3,
    opponent_energy: int = 3,
) -> BattleState:
    player_card_copy = copy.deepcopy(
        player_card
    )

    opponent_card_copy = copy.deepcopy(
        opponent_card
    )

    return BattleState(
        player=PlayerState(
            active=PokemonState(
                card=
                    player_card_copy,

                current_hp=float(
                    player_card_copy[
                        "hp"
                    ]
                ),

                attached_energy=int(
                    player_energy
                ),

                status=None,

                damage=0.0,

                is_active=True,
            ),

            bench=[],

            prize_cards_remaining=1,

            hand_size=7,
        ),

        opponent=PlayerState(
            active=PokemonState(
                card=
                    opponent_card_copy,

                current_hp=float(
                    opponent_card_copy[
                        "hp"
                    ]
                ),

                attached_energy=int(
                    opponent_energy
                ),

                status=None,

                damage=0.0,

                is_active=True,
            ),

            bench=[],

            prize_cards_remaining=1,

            hand_size=7,
        ),

        turn_number=1,

        current_player=
            starting_side,
    )

====================================================================================================
EXACT TOURNAMENT MATCH RUNNER
====================================================================================================
def run_tournament_match(
    match_id: int,
    evaluated_agent: Any,
    baseline_agent: Any,
    player_card: dict[str, Any],
    opponent_card: dict[str, Any],
    starting_side: str,
    evaluated_agent_side: str,
    max_turns: int =
        MAX_TURNS_PER_MATCH,
    search_depth: int =
        SIMULATOR_SEARCH_DEPTH,
    verbose: bool =
        VERBOSE_MATCHES,
) -> TournamentMatchResult:
    if evaluated_agent_side not in {
        "Player",
        "Opponent",
    }:
        raise ValueError(
            "evaluated_agent_side must be "
            "'Player' or 'Opponent'."
        )

    initial_state = (
        create_tournament_state(
            player_card=
                player_card,

            opponent_card=
                opponent_card,

            starting_side=
                starting_side,
        )
    )

    class SideAwareAgent:
        def __init__(
            self,
            player_agent: Any,
            opponent_agent: Any,
        ) -> None:
            self.player_agent = (
                player_agent
            )

            self.opponent_agent = (
                opponent_agent
            )

            self.fallback_count = 0

        def choose_move(
            self,
            state: Any = None,
            depth: int | None = None,
            battle_state: Any = None,
            **kwargs: Any,
        ) -> Any:
            resolved_state = (
                state
                if state is not None
                else battle_state
            )

            if resolved_state is None:
                raise ValueError(
                    "A battle state is required."
                )

            side = str(
                resolved_state
                .current_player
            )

            selected_agent = (
                self.player_agent
                if side == "Player"
                else self.opponent_agent
            )

            decision = (
                selected_agent
                .choose_move(
                    state=
                        resolved_state,

                    depth=
                        depth,
                )
            )

            if bool(
                getattr(
                    decision,
                    "fallback",
                    False,
                )
            ):
                self.fallback_count += 1

            return decision

    if evaluated_agent_side == "Player":
        side_agent = SideAwareAgent(
            player_agent=
                evaluated_agent,

            opponent_agent=
                baseline_agent,
        )

    else:
        side_agent = SideAwareAgent(
            player_agent=
                baseline_agent,

            opponent_agent=
                evaluated_agent,
        )

    start_time = time.perf_counter()

    simulation = simulate_ai_battle(
        initial_state=
            initial_state,

        agent=
            side_agent,

        search_depth=
            search_depth,

        max_turns=
            max_turns,

        verbose=
            verbose,
    )

    elapsed_seconds = (
        time.perf_counter()
        - start_time
    )

    winner = getattr(
        simulation,
        "winner",
        None,
    )

    turns = getattr(
        simulation,
        "turns",
        [],
    )

    stop_reason = getattr(
        simulation,
        "stop_reason",
        None,
    )

    if winner is None:
        agent_result = 0.5

    elif winner == evaluated_agent_side:
        agent_result = 1.0

    else:
        agent_result = 0.0

    return TournamentMatchResult(
        match_id=
            int(match_id),

        agent_name=
            str(
                getattr(
                    evaluated_agent,
                    "name",
                    type(
                        evaluated_agent
                    ).__name__,
                )
            ),

        baseline_name=
            str(
                getattr(
                    baseline_agent,
                    "name",
                    type(
                        baseline_agent
                    ).__name__,
                )
            ),

        player_card=
            str(
                player_card[
                    "name"
                ]
            ),

        opponent_card=
            str(
                opponent_card[
                    "name"
                ]
            ),

        starting_side=
            str(
                starting_side
            ),

        winner=winner,

        turns=
            len(turns),

        stop_reason=
            stop_reason,

        agent_result=
            float(
                agent_result
            ),

        fallback_count=
            int(
                side_agent
                .fallback_count
            ),

        elapsed_seconds=
            float(
                elapsed_seconds
            ),
    )

PROBABLE GLOBAL DEPENDENCIES
----------------------------------------------------------------------------------------------------

                    object                       probable_global_dependencies
0     RandomLegalMoveAgent  [Any, RANDOM_SEED, TournamentDecision, ValueEr...
1        GreedyDamageAgent  [Any, TournamentDecision, ValueError, get_curr...
2       SearchAgentAdapter  [AdvancedSearchEngine, Any, PokemonBattleAgent...
3  create_tournament_state  [Any, BattleState, PlayerState, PokemonState, ...
4     run_tournament_match  [Any, MAX_TURNS_PER_MATCH, SIMULATOR_SEARCH_DE...
5   create_random_baseline                        [RandomLegalMoveAgent, int]
6   create_greedy_baseline                                [GreedyDamageAgent]
7   create_search_baseline       [SIMULATOR_SEARCH_DEPTH, SearchAgentAdapter]

SECTION 2D VALIDATION
----------------------------------------------------------------------------------------------------

                           validation  passed
0         authoritative script exists    True
1           random baseline recovered    True
2           greedy baseline recovered    True
3           search baseline recovered    True
4             state builder recovered    True
5              match runner recovered    True
6  three baseline factories recovered    True
7               source evidence saved    True

====================================================================================================
✅ EXACT RANDOM BASELINE IMPLEMENTATION RECOVERED
✅ EXACT GREEDY BASELINE IMPLEMENTATION RECOVERED
✅ EXACT DEPTH-6 SEARCH ADAPTER RECOVERED
✅ EXACT TOURNAMENT STATE BUILDER RECOVERED
✅ EXACT HISTORICAL MATCH RUNNER RECOVERED
✅ THREE BASELINE FACTORIES RECOVERED
✅ DEPENDENCIES INVENTORIED
✅ NO HISTORICAL SCRIPT EXECUTED
✅ SECTION 2D COMPLETE
====================================================================================================

In [12]:
# ==========================================================================================
# SECTION 2E — SAFELY LOAD EXACT HISTORICAL BASELINE OBJECTS
# ==========================================================================================

print("=" * 100)
print("SECTION 2E — SAFELY LOAD EXACT HISTORICAL BASELINE OBJECTS")
print("=" * 100)

import ast
import builtins
import types
import pandas as pd


# ==========================================================================================
# 1. Parse the authoritative Notebook 48 script
# ==========================================================================================

source_2e = NOTEBOOK48_SCRIPT_2D.read_text(
    encoding="utf-8-sig",
    errors="ignore",
)

tree_2e = ast.parse(
    source_2e
)


# ==========================================================================================
# 2. Build top-level definition inventory
#
# IMPORTANT:
# We are NOT executing the exported Notebook 48 script.
# We only recover:
#   - imports
#   - simple constants
#   - class definitions
#   - function definitions
# required by the historical benchmark objects.
# ==========================================================================================

top_level_nodes_2e = {}

import_nodes_2e = []

assignment_nodes_2e = []


for node in tree_2e.body:

    if isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        import_nodes_2e.append(
            node
        )

    elif isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        top_level_nodes_2e[
            node.name
        ] = node

    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        assignment_nodes_2e.append(
            node
        )


print("\nTOP-LEVEL SOURCE INVENTORY")
print("-" * 100)

print(
    "Imports       :",
    len(
        import_nodes_2e
    ),
)

print(
    "Definitions   :",
    len(
        top_level_nodes_2e
    ),
)

print(
    "Assignments   :",
    len(
        assignment_nodes_2e
    ),
)


# ==========================================================================================
# 3. Helper — assigned names
# ==========================================================================================

def assigned_names_2e(
    node,
):

    names = []

    if isinstance(
        node,
        ast.Assign,
    ):

        targets = node.targets

    elif isinstance(
        node,
        ast.AnnAssign,
    ):

        targets = [
            node.target
        ]

    else:

        return names


    for target in targets:

        if isinstance(
            target,
            ast.Name,
        ):

            names.append(
                target.id
            )

        elif isinstance(
            target,
            (
                ast.Tuple,
                ast.List,
            ),
        ):

            for element in target.elts:

                if isinstance(
                    element,
                    ast.Name,
                ):

                    names.append(
                        element.id
                    )

    return names


assignment_map_2e = {}

for node in assignment_nodes_2e:

    for name in assigned_names_2e(
        node
    ):

        assignment_map_2e[
            name
        ] = node


# ==========================================================================================
# 4. Dependency analysis
# ==========================================================================================

def referenced_names_2e(
    node,
):

    return {
        child.id
        for child in ast.walk(
            node
        )
        if isinstance(
            child,
            ast.Name,
        )
    }


TARGETS_2E = [
    "TournamentDecision",
    "tournament_move_name",
    "tournament_move_damage",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "tournament_state_key",
    "tournament_move_key",
    "SearchAgentAdapter",
    "create_tournament_state",
    "TournamentMatchResult",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


required_definitions_2e = set(
    TARGETS_2E
)

required_assignments_2e = set()


# ------------------------------------------------------------------------------------------
# Repeatedly discover historical definitions/constants referenced by target objects.
# ------------------------------------------------------------------------------------------

changed_2e = True


while changed_2e:

    changed_2e = False

    current_names = list(
        required_definitions_2e
    )

    for name in current_names:

        node = top_level_nodes_2e.get(
            name
        )

        if node is None:
            continue

        refs = referenced_names_2e(
            node
        )

        for ref in refs:

            if (
                ref in top_level_nodes_2e
                and
                ref not in required_definitions_2e
            ):

                required_definitions_2e.add(
                    ref
                )

                changed_2e = True

            if (
                ref in assignment_map_2e
                and
                ref not in required_assignments_2e
            ):

                required_assignments_2e.add(
                    ref
                )

                changed_2e = True


print("\nDEPENDENCY CLOSURE")
print("-" * 100)

print(
    "Required definitions:",
    len(
        required_definitions_2e
    ),
)

print(
    "Required constants:",
    len(
        required_assignments_2e
    ),
)


# ==========================================================================================
# 5. Create isolated historical namespace
# ==========================================================================================

historical_ns_2e = {
    "__builtins__":
        builtins.__dict__,

    "__name__":
        "notebook48_historical_benchmark_recovery",
}


# ==========================================================================================
# 6. Load imports individually
#
# Import failures are recorded rather than crashing immediately because exported notebooks
# can contain unrelated optional imports that the benchmark itself does not use.
# ==========================================================================================

import_results_2e = []


for node in import_nodes_2e:

    module_2e = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module_2e
    )

    source_line_2e = ast.get_source_segment(
        source_2e,
        node,
    )

    try:

        exec(
            compile(
                module_2e,
                filename=str(
                    NOTEBOOK48_SCRIPT_2D
                ),
                mode="exec",
            ),
            historical_ns_2e,
        )

        import_results_2e.append(
            {
                "import":
                    source_line_2e,

                "loaded":
                    True,

                "error":
                    None,
            }
        )

    except Exception as exc:

        import_results_2e.append(
            {
                "import":
                    source_line_2e,

                "loaded":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section2e_import_df = pd.DataFrame(
    import_results_2e
)


print("\nIMPORT RECOVERY")
print("-" * 100)

print(
    "Successful imports:",
    int(
        section2e_import_df[
            "loaded"
        ].sum()
    ),
)

print(
    "Skipped/failed imports:",
    int(
        (
            ~section2e_import_df[
                "loaded"
            ]
        ).sum()
    ),
)


# ==========================================================================================
# 7. Execute required historical constants in original source order
#
# Only assignments whose names were identified by dependency analysis are considered.
# Failures are reported rather than silently replaced.
# ==========================================================================================

constant_results_2e = []


for node in assignment_nodes_2e:

    names = assigned_names_2e(
        node
    )

    relevant_names = [
        name
        for name in names
        if name in required_assignments_2e
    ]

    if not relevant_names:
        continue

    module_2e = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module_2e
    )

    try:

        exec(
            compile(
                module_2e,
                filename=str(
                    NOTEBOOK48_SCRIPT_2D
                ),
                mode="exec",
            ),
            historical_ns_2e,
        )

        for name in relevant_names:

            constant_results_2e.append(
                {
                    "name":
                        name,

                    "loaded":
                        name
                        in historical_ns_2e,

                    "value":
                        repr(
                            historical_ns_2e.get(
                                name
                            )
                        )[:200],

                    "error":
                        None,
                }
            )

    except Exception as exc:

        for name in relevant_names:

            constant_results_2e.append(
                {
                    "name":
                        name,

                    "loaded":
                        False,

                    "value":
                        None,

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


section2e_constant_df = pd.DataFrame(
    constant_results_2e
)


print("\nHISTORICAL CONSTANT RECOVERY")
print("-" * 100)

if section2e_constant_df.empty:

    print(
        "No required historical constants detected."
    )

else:

    display(
        section2e_constant_df
    )


# ==========================================================================================
# 8. Execute required definitions in original source order
# ==========================================================================================

definition_results_2e = []


for node in tree_2e.body:

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        continue

    if (
        node.name
        not in required_definitions_2e
    ):
        continue

    module_2e = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module_2e
    )

    try:

        exec(
            compile(
                module_2e,
                filename=str(
                    NOTEBOOK48_SCRIPT_2D
                ),
                mode="exec",
            ),
            historical_ns_2e,
        )

        definition_results_2e.append(
            {
                "name":
                    node.name,

                "loaded":
                    node.name
                    in historical_ns_2e,

                "error":
                    None,
            }
        )

    except Exception as exc:

        definition_results_2e.append(
            {
                "name":
                    node.name,

                "loaded":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section2e_definition_df = pd.DataFrame(
    definition_results_2e
)


print("\nHISTORICAL DEFINITION RECOVERY")
print("-" * 100)

display(
    section2e_definition_df
)


# ==========================================================================================
# 9. Critical-object validation
# ==========================================================================================

critical_status_2e = []


for name in TARGETS_2E:

    obj = historical_ns_2e.get(
        name
    )

    critical_status_2e.append(
        {
            "object":
                name,

            "available":
                obj is not None,

            "callable":
                callable(
                    obj
                )
                if obj is not None
                else False,
        }
    )


section2e_critical_df = pd.DataFrame(
    critical_status_2e
)


print("\nCRITICAL HISTORICAL OBJECT STATUS")
print("-" * 100)

display(
    section2e_critical_df
)


assert section2e_critical_df[
    "available"
].all(), (
    "One or more exact Notebook 48 benchmark objects could not be loaded."
)


# ==========================================================================================
# 10. Bind exact historical objects locally
# ==========================================================================================

TournamentDecision_2e = (
    historical_ns_2e[
        "TournamentDecision"
    ]
)

RandomLegalMoveAgent_2e = (
    historical_ns_2e[
        "RandomLegalMoveAgent"
    ]
)

GreedyDamageAgent_2e = (
    historical_ns_2e[
        "GreedyDamageAgent"
    ]
)

SearchAgentAdapter_2e = (
    historical_ns_2e[
        "SearchAgentAdapter"
    ]
)

create_tournament_state_2e = (
    historical_ns_2e[
        "create_tournament_state"
    ]
)

TournamentMatchResult_2e = (
    historical_ns_2e[
        "TournamentMatchResult"
    ]
)

run_tournament_match_2e = (
    historical_ns_2e[
        "run_tournament_match"
    ]
)

create_random_baseline_2e = (
    historical_ns_2e[
        "create_random_baseline"
    ]
)

create_greedy_baseline_2e = (
    historical_ns_2e[
        "create_greedy_baseline"
    ]
)

create_search_baseline_2e = (
    historical_ns_2e[
        "create_search_baseline"
    ]
)


# ==========================================================================================
# 11. Instantiate historical baselines
# ==========================================================================================

print("\nINSTANTIATING HISTORICAL BASELINES")
print("-" * 100)


baseline_instances_2e = {}

baseline_creation_results_2e = []


baseline_factories_2e = {
    "Random Baseline":
        create_random_baseline_2e,

    "Greedy Damage Baseline":
        create_greedy_baseline_2e,

    "Depth-6 Search Baseline":
        create_search_baseline_2e,
}


for baseline_name, factory in (
    baseline_factories_2e.items()
):

    try:

        agent = factory()

        baseline_instances_2e[
            baseline_name
        ] = agent

        baseline_creation_results_2e.append(
            {
                "baseline":
                    baseline_name,

                "created":
                    True,

                "type":
                    type(
                        agent
                    ).__name__,

                "error":
                    None,
            }
        )

    except Exception as exc:

        baseline_creation_results_2e.append(
            {
                "baseline":
                    baseline_name,

                "created":
                    False,

                "type":
                    None,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section2e_baseline_creation_df = pd.DataFrame(
    baseline_creation_results_2e
)


display(
    section2e_baseline_creation_df
)


# ==========================================================================================
# 12. Do NOT substitute or recreate failed baselines
# ==========================================================================================

all_baselines_created_2e = bool(
    section2e_baseline_creation_df[
        "created"
    ].all()
)


print("\nBASELINE CREATION STATUS")
print("-" * 100)

if all_baselines_created_2e:

    print(
        "✅ All three exact Notebook 48 baseline agents instantiated."
    )

else:

    print(
        "⚠️ One or more exact historical baselines could not yet be instantiated."
    )

    print(
        "No fallback or replacement implementation has been used."
    )


# ==========================================================================================
# 13. Save loader evidence
# ==========================================================================================

SECTION2E_IMPORT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2e_import_recovery.csv"
)

SECTION2E_CONSTANT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2e_constant_recovery.csv"
)

SECTION2E_DEFINITION_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2e_definition_recovery.csv"
)

SECTION2E_BASELINE_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2e_baseline_creation.csv"
)


section2e_import_df.to_csv(
    SECTION2E_IMPORT_FILE,
    index=False,
)

section2e_constant_df.to_csv(
    SECTION2E_CONSTANT_FILE,
    index=False,
)

section2e_definition_df.to_csv(
    SECTION2E_DEFINITION_FILE,
    index=False,
)

section2e_baseline_creation_df.to_csv(
    SECTION2E_BASELINE_FILE,
    index=False,
)


# ==========================================================================================
# 14. Validation
# ==========================================================================================

section2e_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical namespace created",

            "passed":
                isinstance(
                    historical_ns_2e,
                    dict,
                ),
        },

        {
            "validation":
                "all critical objects loaded",

            "passed":
                bool(
                    section2e_critical_df[
                        "available"
                    ].all()
                ),
        },

        {
            "validation":
                "random baseline created",

            "passed":
                bool(
                    section2e_baseline_creation_df.loc[
                        section2e_baseline_creation_df[
                            "baseline"
                        ]
                        ==
                        "Random Baseline",
                        "created",
                    ].iloc[0]
                ),
        },

        {
            "validation":
                "greedy baseline created",

            "passed":
                bool(
                    section2e_baseline_creation_df.loc[
                        section2e_baseline_creation_df[
                            "baseline"
                        ]
                        ==
                        "Greedy Damage Baseline",
                        "created",
                    ].iloc[0]
                ),
        },

        {
            "validation":
                "depth-6 search baseline created",

            "passed":
                bool(
                    section2e_baseline_creation_df.loc[
                        section2e_baseline_creation_df[
                            "baseline"
                        ]
                        ==
                        "Depth-6 Search Baseline",
                        "created",
                    ].iloc[0]
                ),
        },

        {
            "validation":
                "no historical script executed",

            "passed":
                True,
        },
    ]
)


print("\nSECTION 2E VALIDATION")
print("-" * 100)

display(
    section2e_validation_df
)


if section2e_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print("✅ EXACT NOTEBOOK 48 OBJECTS LOADED SAFELY")
    print("✅ RANDOM BASELINE INSTANTIATED")
    print("✅ GREEDY DAMAGE BASELINE INSTANTIATED")
    print("✅ DEPTH-6 SEARCH BASELINE INSTANTIATED")
    print("✅ NO SUBSTITUTE BASELINE IMPLEMENTATIONS USED")
    print("✅ NO HISTORICAL TOURNAMENT EXECUTED")
    print("✅ SECTION 2E COMPLETE")

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print("⚠️ SECTION 2E REQUIRES DEPENDENCY REPAIR")
    print("⚠️ DO NOT RUN ANY BENCHMARK YET")
    print("=" * 100)

====================================================================================================
SECTION 2E — SAFELY LOAD EXACT HISTORICAL BASELINE OBJECTS
====================================================================================================

TOP-LEVEL SOURCE INVENTORY
----------------------------------------------------------------------------------------------------
Imports       : 59
Definitions   : 25
Assignments   : 155

DEPENDENCY CLOSURE
----------------------------------------------------------------------------------------------------
Required definitions: 14
Required constants: 4

IMPORT RECOVERY
----------------------------------------------------------------------------------------------------
Successful imports: 57
Skipped/failed imports: 2

HISTORICAL CONSTANT RECOVERY
----------------------------------------------------------------------------------------------------

                     name  loaded  value error
0             RANDOM_SEED    True   4801  None
1     MAX_TURNS_PER_MATCH    True     50  None
2  SIMULATOR_SEARCH_DEPTH    True      6  None
3         VERBOSE_MATCHES    True  False  None

HISTORICAL DEFINITION RECOVERY
----------------------------------------------------------------------------------------------------

                       name  loaded error
0        TournamentDecision    True  None
1      tournament_move_name    True  None
2    tournament_move_damage    True  None
3      RandomLegalMoveAgent    True  None
4         GreedyDamageAgent    True  None
5      tournament_state_key    True  None
6       tournament_move_key    True  None
7        SearchAgentAdapter    True  None
8   create_tournament_state    True  None
9     TournamentMatchResult    True  None
10     run_tournament_match    True  None
11   create_random_baseline    True  None
12   create_greedy_baseline    True  None
13   create_search_baseline    True  None

CRITICAL HISTORICAL OBJECT STATUS
----------------------------------------------------------------------------------------------------

                     object  available  callable
0        TournamentDecision       True      True
1      tournament_move_name       True      True
2    tournament_move_damage       True      True
3      RandomLegalMoveAgent       True      True
4         GreedyDamageAgent       True      True
5      tournament_state_key       True      True
6       tournament_move_key       True      True
7        SearchAgentAdapter       True      True
8   create_tournament_state       True      True
9     TournamentMatchResult       True      True
10     run_tournament_match       True      True
11   create_random_baseline       True      True
12   create_greedy_baseline       True      True
13   create_search_baseline       True      True

INSTANTIATING HISTORICAL BASELINES
----------------------------------------------------------------------------------------------------

,baseline,created,type,error
0,Random Baseline,False,NaN,TypeError: create_random_baseline() missing 1 ...
1,Greedy Damage Baseline,True,GreedyDamageAgent,NaN
2,Depth-6 Search Baseline,True,SearchAgentAdapter,NaN

BASELINE CREATION STATUS
----------------------------------------------------------------------------------------------------
⚠️ One or more exact historical baselines could not yet be instantiated.
No fallback or replacement implementation has been used.

SECTION 2E VALIDATION
----------------------------------------------------------------------------------------------------

                        validation  passed
0     historical namespace created    True
1      all critical objects loaded    True
2          random baseline created   False
3          greedy baseline created    True
4  depth-6 search baseline created    True
5    no historical script executed    True

====================================================================================================
⚠️ SECTION 2E REQUIRES DEPENDENCY REPAIR
⚠️ DO NOT RUN ANY BENCHMARK YET
====================================================================================================

In [13]:
# ==========================================================================================
# SECTION 2E.1 — REPAIR RANDOM BASELINE FACTORY CALL
# ==========================================================================================

print("=" * 100)
print("SECTION 2E.1 — REPAIR RANDOM BASELINE FACTORY CALL")
print("=" * 100)

import inspect
import pandas as pd


# ==========================================================================================
# 1. Inspect exact factory signature
# ==========================================================================================

print("\nRANDOM BASELINE FACTORY SIGNATURE")
print("-" * 100)

random_factory_signature_2e1 = inspect.signature(
    create_random_baseline_2e
)

print(
    random_factory_signature_2e1
)


print("\nRANDOM BASELINE FACTORY SOURCE")
print("-" * 100)

print(
    objects_2d[
        "create_random_baseline"
    ][
        "source"
    ]
)


# ==========================================================================================
# 2. Confirm historical seed
# ==========================================================================================

historical_random_seed_2e1 = int(
    historical_ns_2e[
        "RANDOM_SEED"
    ]
)

print("\nHISTORICAL RANDOM SEED")
print("-" * 100)

print(
    historical_random_seed_2e1
)

assert (
    historical_random_seed_2e1
    == 4801
)


# ==========================================================================================
# 3. Instantiate exact random baseline using historical factory contract
# ==========================================================================================

random_baseline_error_2e1 = None
random_baseline_2e1 = None


try:

    random_baseline_2e1 = (
        create_random_baseline_2e(
            historical_random_seed_2e1
        )
    )

except Exception as exc:

    random_baseline_error_2e1 = (
        f"{type(exc).__name__}: {exc}"
    )


print("\nRANDOM BASELINE CREATION")
print("-" * 100)

print(
    "Created:",
    random_baseline_2e1 is not None,
)

print(
    "Type:",
    (
        type(
            random_baseline_2e1
        ).__name__
        if random_baseline_2e1 is not None
        else None
    ),
)

print(
    "Error:",
    random_baseline_error_2e1,
)


assert (
    random_baseline_2e1
    is not None
), (
    random_baseline_error_2e1
)


# ==========================================================================================
# 4. Update historical baseline instance registry
# ==========================================================================================

baseline_instances_2e[
    "Random Baseline"
] = random_baseline_2e1


# ==========================================================================================
# 5. Rebuild baseline creation table
# ==========================================================================================

section2e_baseline_creation_df = pd.DataFrame(
    [
        {
            "baseline":
                "Random Baseline",

            "created":
                (
                    "Random Baseline"
                    in baseline_instances_2e
                ),

            "type":
                type(
                    baseline_instances_2e[
                        "Random Baseline"
                    ]
                ).__name__,

            "error":
                None,
        },

        {
            "baseline":
                "Greedy Damage Baseline",

            "created":
                (
                    "Greedy Damage Baseline"
                    in baseline_instances_2e
                ),

            "type":
                type(
                    baseline_instances_2e[
                        "Greedy Damage Baseline"
                    ]
                ).__name__,

            "error":
                None,
        },

        {
            "baseline":
                "Depth-6 Search Baseline",

            "created":
                (
                    "Depth-6 Search Baseline"
                    in baseline_instances_2e
                ),

            "type":
                type(
                    baseline_instances_2e[
                        "Depth-6 Search Baseline"
                    ]
                ).__name__,

            "error":
                None,
        },
    ]
)


print("\nUPDATED BASELINE CREATION STATUS")
print("-" * 100)

display(
    section2e_baseline_creation_df
)


# ==========================================================================================
# 6. Final repair validation
# ==========================================================================================

section2e1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical random seed recovered",

            "passed":
                (
                    historical_random_seed_2e1
                    == 4801
                ),
        },

        {
            "validation":
                "random baseline instantiated",

            "passed":
                (
                    random_baseline_2e1
                    is not None
                ),
        },

        {
            "validation":
                "all three historical baselines available",

            "passed":
                all(
                    name
                    in baseline_instances_2e
                    for name in [
                        "Random Baseline",
                        "Greedy Damage Baseline",
                        "Depth-6 Search Baseline",
                    ]
                ),
        },
    ]
)


print("\nSECTION 2E.1 VALIDATION")
print("-" * 100)

display(
    section2e1_validation_df
)


assert (
    section2e1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT RANDOM BASELINE FACTORY CONTRACT VERIFIED")
print("✅ HISTORICAL RANDOM SEED = 4801")
print("✅ RANDOM BASELINE INSTANTIATED")
print("✅ GREEDY DAMAGE BASELINE STILL AVAILABLE")
print("✅ DEPTH-6 SEARCH BASELINE STILL AVAILABLE")
print("✅ ALL THREE HISTORICAL BASELINES READY")
print("✅ SECTION 2E.1 COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2E.1 — REPAIR RANDOM BASELINE FACTORY CALL
====================================================================================================

RANDOM BASELINE FACTORY SIGNATURE
----------------------------------------------------------------------------------------------------
(seed: int) -> notebook48_historical_benchmark_recovery.RandomLegalMoveAgent

RANDOM BASELINE FACTORY SOURCE
----------------------------------------------------------------------------------------------------
def create_random_baseline(
    seed: int,
) -> RandomLegalMoveAgent:
    return RandomLegalMoveAgent(
        seed=seed,
        name="Random Baseline",
    )

HISTORICAL RANDOM SEED
----------------------------------------------------------------------------------------------------
4801

RANDOM BASELINE CREATION
----------------------------------------------------------------------------------------------------
Created: True
Type: RandomLegalMoveAgent
Error: None

UPDATED BASELINE CREATION STATUS
----------------------------------------------------------------------------------------------------

                  baseline  created                  type error
0          Random Baseline     True  RandomLegalMoveAgent  None
1   Greedy Damage Baseline     True     GreedyDamageAgent  None
2  Depth-6 Search Baseline     True    SearchAgentAdapter  None

SECTION 2E.1 VALIDATION
----------------------------------------------------------------------------------------------------

                                 validation  passed
0          historical random seed recovered    True
1              random baseline instantiated    True
2  all three historical baselines available    True

====================================================================================================
✅ EXACT RANDOM BASELINE FACTORY CONTRACT VERIFIED
✅ HISTORICAL RANDOM SEED = 4801
✅ RANDOM BASELINE INSTANTIATED
✅ GREEDY DAMAGE BASELINE STILL AVAILABLE
✅ DEPTH-6 SEARCH BASELINE STILL AVAILABLE
✅ ALL THREE HISTORICAL BASELINES READY
✅ SECTION 2E.1 COMPLETE
====================================================================================================

In [14]:
# ==========================================================================================
# SECTION 2F — HISTORICAL HARNESS SMOKE TEST
# ==========================================================================================

print("=" * 100)
print("SECTION 2F — HISTORICAL HARNESS SMOKE TEST")
print("=" * 100)

from copy import deepcopy
import pandas as pd


# ==========================================================================================
# 1. Historical smoke-test design
# ==========================================================================================

SMOKE_BASELINES_2F = [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]

SMOKE_SIDES_2F = [
    "Player",
    "Opponent",
]

print("\nSMOKE TEST DESIGN")
print("-" * 100)

print("Baselines :", SMOKE_BASELINES_2F)
print("Sides     :", SMOKE_SIDES_2F)
print("Matches   :", len(SMOKE_BASELINES_2F) * len(SMOKE_SIDES_2F))


# ==========================================================================================
# 2. Inspect exact function signatures
# ==========================================================================================

import inspect

print("\nCREATE_TOURNAMENT_STATE SIGNATURE")
print("-" * 100)
print(
    inspect.signature(
        create_tournament_state_2e
    )
)

print("\nRUN_TOURNAMENT_MATCH SIGNATURE")
print("-" * 100)
print(
    inspect.signature(
        run_tournament_match_2e
    )
)


# ==========================================================================================
# 3. Build smoke-test initial states
#
# IMPORTANT:
# We use the exact historical state builder.
# ==========================================================================================

smoke_states_2f = {}

for side in SMOKE_SIDES_2F:

    try:

        smoke_states_2f[
            side
        ] = create_tournament_state_2e(
            starting_side=side
        )

    except TypeError:

        # Some historical exports may use starting_player instead.
        smoke_states_2f[
            side
        ] = create_tournament_state_2e(
            starting_player=side
        )


print("\nHISTORICAL TEST STATES")
print("-" * 100)

for side, state in smoke_states_2f.items():

    print(
        side,
        "->",
        type(state).__name__,
    )


assert all(
    state is not None
    for state in smoke_states_2f.values()
)


# ==========================================================================================
# 4. Helper — build historical match invocation safely
#
# We inspect the recovered runner signature so we do not guess parameter names.
# ==========================================================================================

run_match_signature_2f = inspect.signature(
    run_tournament_match_2e
)

run_match_parameters_2f = list(
    run_match_signature_2f.parameters.keys()
)


print("\nRUNNER PARAMETERS")
print("-" * 100)
print(run_match_parameters_2f)


# ==========================================================================================
# 5. Run six tiny historical matches
# ==========================================================================================

smoke_results_2f = []


for baseline_name in SMOKE_BASELINES_2F:

    baseline_agent = (
        baseline_instances_2e[
            baseline_name
        ]
    )

    for evaluated_side in SMOKE_SIDES_2F:

        print(
            f"\nRunning: "
            f"{baseline_name} | "
            f"Evaluated side: {evaluated_side}"
        )

        initial_state = deepcopy(
            smoke_states_2f[
                evaluated_side
            ]
        )

        kwargs_2f = {}


        # ------------------------------------------------------------------
        # State
        # ------------------------------------------------------------------

        if "initial_state" in run_match_parameters_2f:

            kwargs_2f[
                "initial_state"
            ] = initial_state

        elif "state" in run_match_parameters_2f:

            kwargs_2f[
                "state"
            ] = initial_state


        # ------------------------------------------------------------------
        # Baseline/opponent agent
        # ------------------------------------------------------------------

        if "baseline_agent" in run_match_parameters_2f:

            kwargs_2f[
                "baseline_agent"
            ] = baseline_agent

        elif "opponent_agent" in run_match_parameters_2f:

            kwargs_2f[
                "opponent_agent"
            ] = baseline_agent

        elif "opponent" in run_match_parameters_2f:

            kwargs_2f[
                "opponent"
            ] = baseline_agent


        # ------------------------------------------------------------------
        # Evaluated side
        # ------------------------------------------------------------------

        if "evaluated_agent_side" in run_match_parameters_2f:

            kwargs_2f[
                "evaluated_agent_side"
            ] = evaluated_side

        elif "competitive_side" in run_match_parameters_2f:

            kwargs_2f[
                "competitive_side"
            ] = evaluated_side

        elif "player_side" in run_match_parameters_2f:

            kwargs_2f[
                "player_side"
            ] = evaluated_side


        # ------------------------------------------------------------------
        # Historical depth / turn controls if exposed
        # ------------------------------------------------------------------

        if "search_depth" in run_match_parameters_2f:

            kwargs_2f[
                "search_depth"
            ] = int(
                historical_ns_2e[
                    "SIMULATOR_SEARCH_DEPTH"
                ]
            )

        if "max_turns" in run_match_parameters_2f:

            kwargs_2f[
                "max_turns"
            ] = int(
                historical_ns_2e[
                    "MAX_TURNS_PER_MATCH"
                ]
            )

        if "verbose" in run_match_parameters_2f:

            kwargs_2f[
                "verbose"
            ] = False


        try:

            result = run_tournament_match_2e(
                **kwargs_2f
            )

            smoke_results_2f.append(
                {
                    "baseline":
                        baseline_name,

                    "evaluated_side":
                        evaluated_side,

                    "success":
                        True,

                    "result_type":
                        type(
                            result
                        ).__name__,

                    "winner":
                        getattr(
                            result,
                            "winner",
                            None,
                        ),

                    "turns":
                        getattr(
                            result,
                            "turns",
                            None,
                        ),

                    "fallback":
                        getattr(
                            result,
                            "fallback",
                            None,
                        ),

                    "error":
                        None,
                }
            )

        except Exception as exc:

            smoke_results_2f.append(
                {
                    "baseline":
                        baseline_name,

                    "evaluated_side":
                        evaluated_side,

                    "success":
                        False,

                    "result_type":
                        None,

                    "winner":
                        None,

                    "turns":
                        None,

                    "fallback":
                        None,

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


# ==========================================================================================
# 6. Smoke-test results
# ==========================================================================================

section2f_smoke_results_df = pd.DataFrame(
    smoke_results_2f
)


print("\nHISTORICAL HARNESS SMOKE RESULTS")
print("-" * 100)

display(
    section2f_smoke_results_df
)


# ==========================================================================================
# 7. Validation
# ==========================================================================================

section2f_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "six smoke matches attempted",

            "observed":
                len(
                    section2f_smoke_results_df
                ),

            "expected":
                6,

            "passed":
                len(
                    section2f_smoke_results_df
                )
                == 6,
        },

        {
            "validation":
                "all historical smoke matches succeeded",

            "observed":
                int(
                    section2f_smoke_results_df[
                        "success"
                    ].sum()
                ),

            "expected":
                6,

            "passed":
                bool(
                    section2f_smoke_results_df[
                        "success"
                    ].all()
                ),
        },

        {
            "validation":
                "all three baselines exercised",

            "observed":
                sorted(
                    section2f_smoke_results_df[
                        "baseline"
                    ].unique()
                    .tolist()
                ),

            "expected":
                sorted(
                    SMOKE_BASELINES_2F
                ),

            "passed":
                set(
                    section2f_smoke_results_df[
                        "baseline"
                    ].unique()
                )
                ==
                set(
                    SMOKE_BASELINES_2F
                ),
        },

        {
            "validation":
                "both sides exercised",

            "observed":
                sorted(
                    section2f_smoke_results_df[
                        "evaluated_side"
                    ].unique()
                    .tolist()
                ),

            "expected":
                [
                    "Opponent",
                    "Player",
                ],

            "passed":
                set(
                    section2f_smoke_results_df[
                        "evaluated_side"
                    ].unique()
                )
                ==
                {
                    "Player",
                    "Opponent",
                },
        },
    ]
)


print("\nSECTION 2F VALIDATION")
print("-" * 100)

display(
    section2f_validation_df
)


if section2f_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print("✅ HISTORICAL TOURNAMENT STATE BUILDER EXECUTED")
    print("✅ RANDOM BASELINE SMOKE TEST PASSED")
    print("✅ GREEDY DAMAGE BASELINE SMOKE TEST PASSED")
    print("✅ DEPTH-6 SEARCH BASELINE SMOKE TEST PASSED")
    print("✅ PLAYER SIDE TESTED")
    print("✅ OPPONENT SIDE TESTED")
    print("✅ HISTORICAL HARNESS EXECUTION CONFIRMED")
    print("✅ SECTION 2F COMPLETE")

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print("⚠️ HISTORICAL HARNESS SMOKE TEST NEEDS REPAIR")
    print("⚠️ DO NOT CONNECT R3 YET")
    print("=" * 100)

====================================================================================================
SECTION 2F — HISTORICAL HARNESS SMOKE TEST
====================================================================================================

SMOKE TEST DESIGN
----------------------------------------------------------------------------------------------------
Baselines : ['Random Baseline', 'Greedy Damage Baseline', 'Depth-6 Search Baseline']
Sides     : ['Player', 'Opponent']
Matches   : 6

CREATE_TOURNAMENT_STATE SIGNATURE
----------------------------------------------------------------------------------------------------
(player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str = 'Player', player_energy: int = 3, opponent_energy: int = 3) -> src.battle_state.BattleState

RUN_TOURNAMENT_MATCH SIGNATURE
----------------------------------------------------------------------------------------------------
(match_id: int, evaluated_agent: Any, baseline_agent: Any, player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str, evaluated_agent_side: str, max_turns: int = 50, search_depth: int = 6, verbose: bool = False) -> notebook48_historical_benchmark_recovery.TournamentMatchResult

TypeError: create_tournament_state() got an unexpected keyword argument 'starting_player'. Did you mean 'starting_side'?

In [15]:
# ==========================================================================================
# SECTION 2F.1 — RECOVER EXACT NOTEBOOK 48 SMOKE-TEST INPUTS
# ==========================================================================================

print("=" * 100)
print("SECTION 2F.1 — RECOVER EXACT NOTEBOOK 48 SMOKE-TEST INPUTS")
print("=" * 100)

import ast
import pandas as pd


# ==========================================================================================
# 1. Confirm exact recovered signatures
# ==========================================================================================

import inspect

print("\nCREATE_TOURNAMENT_STATE SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        create_tournament_state_2e
    )
)


print("\nRUN_TOURNAMENT_MATCH SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        run_tournament_match_2e
    )
)


# ==========================================================================================
# 2. Search authoritative Notebook 48 script for calls to run_tournament_match()
# ==========================================================================================

tree_2f1 = ast.parse(
    source_2e
)

run_call_rows_2f1 = []


for node in ast.walk(
    tree_2f1
):

    if not isinstance(
        node,
        ast.Call,
    ):
        continue

    called_name = None

    if isinstance(
        node.func,
        ast.Name,
    ):
        called_name = node.func.id

    elif isinstance(
        node.func,
        ast.Attribute,
    ):
        called_name = node.func.attr


    if called_name != "run_tournament_match":
        continue


    call_source = ast.get_source_segment(
        source_2e,
        node,
    )


    positional_args = []

    for arg in node.args:

        positional_args.append(
            ast.get_source_segment(
                source_2e,
                arg,
            )
        )


    keyword_args = {}

    for keyword in node.keywords:

        if keyword.arg is None:
            continue

        keyword_args[
            keyword.arg
        ] = ast.get_source_segment(
            source_2e,
            keyword.value,
        )


    run_call_rows_2f1.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "positional_args":
                positional_args,

            "keyword_args":
                keyword_args,

            "source":
                call_source,
        }
    )


section2f1_run_calls_df = pd.DataFrame(
    run_call_rows_2f1
)


print("\nHISTORICAL run_tournament_match() CALLS")
print("-" * 100)

display(
    section2f1_run_calls_df
)


# ==========================================================================================
# 3. Print calls in readable form
# ==========================================================================================

print("\nDETAILED HISTORICAL MATCH INVOCATIONS")
print("-" * 100)


for index, row in (
    section2f1_run_calls_df
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        "CALL:",
        index + 1,
    )

    print(
        "LINE:",
        row["line_number"],
    )

    print("-" * 100)

    print(
        row["source"]
    )


# ==========================================================================================
# 4. Search for create_tournament_state() calls too
# ==========================================================================================

state_call_rows_2f1 = []


for node in ast.walk(
    tree_2f1
):

    if not isinstance(
        node,
        ast.Call,
    ):
        continue

    called_name = None

    if isinstance(
        node.func,
        ast.Name,
    ):
        called_name = node.func.id

    elif isinstance(
        node.func,
        ast.Attribute,
    ):
        called_name = node.func.attr


    if called_name != "create_tournament_state":
        continue


    call_source = ast.get_source_segment(
        source_2e,
        node,
    )


    state_call_rows_2f1.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "source":
                call_source,
        }
    )


section2f1_state_calls_df = pd.DataFrame(
    state_call_rows_2f1
)


print("\nHISTORICAL create_tournament_state() CALLS")
print("-" * 100)

display(
    section2f1_state_calls_df
)


# ==========================================================================================
# 5. Search exact historical script for card-variable assignments
# ==========================================================================================

CARD_NAME_TOKENS_2F1 = [
    "player_card",
    "opponent_card",
    "evaluation_player_card",
    "evaluation_opponent_card",
    "tournament_player_card",
    "tournament_opponent_card",
]


card_assignment_rows_2f1 = []


for node in tree_2f1.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue


    assigned_names = assigned_names_2e(
        node
    )


    for name in assigned_names:

        name_lower = name.lower()

        if not any(
            token in name_lower
            for token in CARD_NAME_TOKENS_2F1
        ):
            continue


        source_segment = ast.get_source_segment(
            source_2e,
            node,
        )


        card_assignment_rows_2f1.append(
            {
                "name":
                    name,

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "source":
                    source_segment,
            }
        )


section2f1_card_assignments_df = pd.DataFrame(
    card_assignment_rows_2f1
)


print("\nHISTORICAL CARD VARIABLE ASSIGNMENTS")
print("-" * 100)

if section2f1_card_assignments_df.empty:

    print(
        "No obvious top-level card assignments found."
    )

else:

    display(
        section2f1_card_assignments_df
    )


# ==========================================================================================
# 6. Search surrounding context around historical match execution
# ==========================================================================================

source_lines_2f1 = (
    source_2e.splitlines()
)

context_rows_2f1 = []


for row in run_call_rows_2f1:

    line_number = int(
        row["line_number"]
    )

    start = max(
        0,
        line_number - 50,
    )

    end = min(
        len(
            source_lines_2f1
        ),
        line_number + 35,
    )


    context_rows_2f1.append(
        {
            "line_number":
                line_number,

            "context":
                "\n".join(
                    source_lines_2f1[
                        start:end
                    ]
                ),
        }
    )


print("\nMATCH EXECUTION CONTEXT")
print("-" * 100)


for index, row in enumerate(
    context_rows_2f1,
    start=1,
):

    print("\n" + "=" * 100)

    print(
        f"CONTEXT {index}"
    )

    print(
        "AROUND LINE:",
        row["line_number"],
    )

    print("-" * 100)

    print(
        row["context"]
    )


# ==========================================================================================
# 7. Validation
# ==========================================================================================

section2f1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical match calls found",

            "observed":
                len(
                    section2f1_run_calls_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2f1_run_calls_df
                ) > 0,
        },

        {
            "validation":
                "historical state-builder calls found",

            "observed":
                len(
                    section2f1_state_calls_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section2f1_state_calls_df
                ) > 0,
        },

        {
            "validation":
                "exact runner requires cards",

            "observed":
                (
                    "player_card"
                    in inspect.signature(
                        run_tournament_match_2e
                    ).parameters
                    and
                    "opponent_card"
                    in inspect.signature(
                        run_tournament_match_2e
                    ).parameters
                ),

            "expected":
                True,

            "passed":
                (
                    "player_card"
                    in inspect.signature(
                        run_tournament_match_2e
                    ).parameters
                    and
                    "opponent_card"
                    in inspect.signature(
                        run_tournament_match_2e
                    ).parameters
                ),
        },
    ]
)


print("\nSECTION 2F.1 VALIDATION")
print("-" * 100)

display(
    section2f1_validation_df
)


assert (
    section2f1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT HISTORICAL MATCH INVOCATIONS RECOVERED")
print("✅ EXACT CARD ARGUMENT REQUIREMENT CONFIRMED")
print("✅ HISTORICAL MATCH EXECUTION CONTEXT RECOVERED")
print("✅ NO CARD DICTIONARIES FABRICATED")
print("✅ NO BENCHMARK EXECUTED")
print("✅ SECTION 2F.1 COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2F.1 — RECOVER EXACT NOTEBOOK 48 SMOKE-TEST INPUTS
====================================================================================================

CREATE_TOURNAMENT_STATE SIGNATURE
----------------------------------------------------------------------------------------------------
(player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str = 'Player', player_energy: int = 3, opponent_energy: int = 3) -> src.battle_state.BattleState

RUN_TOURNAMENT_MATCH SIGNATURE
----------------------------------------------------------------------------------------------------
(match_id: int, evaluated_agent: Any, baseline_agent: Any, player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str, evaluated_agent_side: str, max_turns: int = 50, search_depth: int = 6, verbose: bool = False) -> notebook48_historical_benchmark_recovery.TournamentMatchResult

HISTORICAL run_tournament_match() CALLS
----------------------------------------------------------------------------------------------------

,line_number,positional_args,keyword_args,source
0,3008,[],"{'match_id': 'smoke_index', 'evaluated_agent':...",run_tournament_match(\n match_id=\n ...
1,3458,[],"{'match_id': 'global_match_index', 'evaluated_...",run_tournament_match(\n match_id=\n...

DETAILED HISTORICAL MATCH INVOCATIONS
----------------------------------------------------------------------------------------------------

====================================================================================================
CALL: 1
LINE: 3008
----------------------------------------------------------------------------------------------------
run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=
            baseline_agent,

        player_card=
            smoke_player_card,

        opponent_card=
            smoke_opponent_card,

        starting_side=
            "Player",

        evaluated_agent_side=
            "Player",

        max_turns=
            20,

        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        verbose=False,
    )

====================================================================================================
CALL: 2
LINE: 3458
----------------------------------------------------------------------------------------------------
run_tournament_match(
            match_id=
                global_match_index,

            evaluated_agent=
                evaluated_agent,

            baseline_agent=
                baseline_agent,

            player_card=
                scheduled_match[
                    "player_card"
                ],

            opponent_card=
                scheduled_match[
                    "opponent_card"
                ],

            starting_side=
                scheduled_match[
                    "starting_side"
                ],

            evaluated_agent_side=
                scheduled_match[
                    "evaluated_agent_side"
                ],

            max_turns=
                MAX_TURNS_PER_MATCH,

            search_depth=
                SIMULATOR_SEARCH_DEPTH,

            verbose=False,
        )

HISTORICAL create_tournament_state() CALLS
----------------------------------------------------------------------------------------------------

   line_number                                             source
0         2721  create_tournament_state(\n            player_c...

HISTORICAL CARD VARIABLE ASSIGNMENTS
----------------------------------------------------------------------------------------------------

,name,line_number,source
0,smoke_player_card,2992,smoke_player_card = (\n TOURNAMENT_CARD_TEM...
1,smoke_opponent_card,2996,smoke_opponent_card = (\n TOURNAMENT_CARD_T...

MATCH EXECUTION CONTEXT
----------------------------------------------------------------------------------------------------

====================================================================================================
CONTEXT 1
AROUND LINE: 3008
----------------------------------------------------------------------------------------------------
    RandomLegalMoveAgent(
        seed=
            RANDOM_SEED,

        name=
            "Random Baseline",
    )
)

greedy_baseline_agent = (
    GreedyDamageAgent(
        name=
            "Greedy Damage Baseline",
    )
)

search_baseline_agent = (
    SearchAgentAdapter(
        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        name=
            "Depth-6 Search Baseline",
    )
)


# ------------------------------------------------------------
# 3.13 â€” Smoke-test one match per baseline
# ------------------------------------------------------------

smoke_test_results = []

smoke_player_card = (
    TOURNAMENT_CARD_TEMPLATES[0]
)

smoke_opponent_card = (
    TOURNAMENT_CARD_TEMPLATES[1]
)

for smoke_index, baseline_agent in enumerate(
    [
        random_baseline_agent,
        greedy_baseline_agent,
        search_baseline_agent,
    ],
    start=1,
):
    smoke_result = run_tournament_match(
        match_id=
            smoke_index,

        evaluated_agent=
            competitive_tournament_agent,

        baseline_agent=
            baseline_agent,

        player_card=
            smoke_player_card,

        opponent_card=
            smoke_opponent_card,

        starting_side=
            "Player",

        evaluated_agent_side=
            "Player",

        max_turns=
            20,

        search_depth=
            SIMULATOR_SEARCH_DEPTH,

        verbose=False,
    )

    smoke_test_results.append(
        dataclasses.asdict(
            smoke_result
        )
    )

====================================================================================================
CONTEXT 2
AROUND LINE: 3458
----------------------------------------------------------------------------------------------------

for baseline_name in (
    baseline_factories
):
    full_schedule.extend(
        build_balanced_schedule(
            baseline_name=
                baseline_name,

            match_count=
                TOURNAMENT_MATCHES_PER_BASELINE,
        )
    )


# ------------------------------------------------------------
# 4.6 â€” Run tournament
# ------------------------------------------------------------

tournament_rows = []

tournament_failures = []

tournament_start = time.perf_counter()

for global_match_index, scheduled_match in enumerate(
    full_schedule,
    start=1,
):
    baseline_name = (
        scheduled_match[
            "baseline_name"
        ]
    )

    try:
        evaluated_agent = (
            create_competitive_agent()
        )

        baseline_agent = (
            baseline_factories[
                baseline_name
            ](
                TOURNAMENT_RANDOM_SEED
                + global_match_index
            )
        )

        result = run_tournament_match(
            match_id=
                global_match_index,

            evaluated_agent=
                evaluated_agent,

            baseline_agent=
                baseline_agent,

            player_card=
                scheduled_match[
                    "player_card"
                ],

            opponent_card=
                scheduled_match[
                    "opponent_card"
                ],

            starting_side=
                scheduled_match[
                    "starting_side"
                ],

            evaluated_agent_side=
                scheduled_match[
                    "evaluated_agent_side"
                ],

            max_turns=
                MAX_TURNS_PER_MATCH,

            search_depth=
                SIMULATOR_SEARCH_DEPTH,


SECTION 2F.1 VALIDATION
----------------------------------------------------------------------------------------------------

                             validation observed expected  passed
0          historical match calls found        2      > 0    True
1  historical state-builder calls found        1      > 0    True
2           exact runner requires cards     True     True    True

====================================================================================================
✅ EXACT HISTORICAL MATCH INVOCATIONS RECOVERED
✅ EXACT CARD ARGUMENT REQUIREMENT CONFIRMED
✅ HISTORICAL MATCH EXECUTION CONTEXT RECOVERED
✅ NO CARD DICTIONARIES FABRICATED
✅ NO BENCHMARK EXECUTED
✅ SECTION 2F.1 COMPLETE
====================================================================================================

In [19]:
# ==========================================================================================
# SECTION 2F.2 — RECOVER EXACT HISTORICAL SMOKE-TEST OBJECTS
# ==========================================================================================

print("=" * 100)
print("SECTION 2F.2 — RECOVER EXACT HISTORICAL SMOKE-TEST OBJECTS")
print("=" * 100)

import ast
import pandas as pd


# ==========================================================================================
# 1. Exact historical names required by the recovered smoke-test invocation
# ==========================================================================================

REQUIRED_SMOKE_NAMES_2F2 = [
    "TOURNAMENT_CARD_TEMPLATES",
    "competitive_tournament_agent",
    "create_competitive_agent",
]


# ==========================================================================================
# 2. Find top-level assignments / definitions in authoritative Notebook 48 source
# ==========================================================================================

smoke_source_inventory_2f2 = []


for node in tree_2e.body:

    # --------------------------------------------------------------------------------------
    # Functions / classes
    # --------------------------------------------------------------------------------------

    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        if node.name in REQUIRED_SMOKE_NAMES_2F2:

            smoke_source_inventory_2f2.append(
                {
                    "name":
                        node.name,

                    "kind":
                        (
                            "CLASS"
                            if isinstance(
                                node,
                                ast.ClassDef
                            )
                            else
                            "FUNCTION"
                        ),

                    "line_number":
                        node.lineno,

                    "source":
                        ast.get_source_segment(
                            source_2e,
                            node,
                        ),
                }
            )


    # --------------------------------------------------------------------------------------
    # Assignments
    # --------------------------------------------------------------------------------------

    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        names = assigned_names_2e(
            node
        )

        for name in names:

            if name in REQUIRED_SMOKE_NAMES_2F2:

                smoke_source_inventory_2f2.append(
                    {
                        "name":
                            name,

                        "kind":
                            "ASSIGNMENT",

                        "line_number":
                            getattr(
                                node,
                                "lineno",
                                None,
                            ),

                        "source":
                            ast.get_source_segment(
                                source_2e,
                                node,
                            ),
                    }
                )


section2f2_source_inventory_df = pd.DataFrame(
    smoke_source_inventory_2f2
)


print("\nHISTORICAL SMOKE OBJECT SOURCE INVENTORY")
print("-" * 100)

display(
    section2f2_source_inventory_df
)


# ==========================================================================================
# 3. Print exact recovered sources
# ==========================================================================================

print("\nEXACT HISTORICAL SMOKE OBJECT SOURCES")
print("-" * 100)

for _, row in (
    section2f2_source_inventory_df
    .sort_values(
        "line_number"
    )
    .iterrows()
):

    print("\n" + "=" * 100)
    print(row["name"])
    print("=" * 100)
    print(row["source"])


# ==========================================================================================
# 4. Require the historical card-template assignment
# ==========================================================================================

template_rows_2f2 = (
    section2f2_source_inventory_df[
        section2f2_source_inventory_df[
            "name"
        ]
        ==
        "TOURNAMENT_CARD_TEMPLATES"
    ]
)


assert not template_rows_2f2.empty, (
    "TOURNAMENT_CARD_TEMPLATES assignment was not recovered."
)


# ==========================================================================================
# 5. Execute exact TOURNAMENT_CARD_TEMPLATES assignment in isolated namespace
# ==========================================================================================

template_assignment_node_2f2 = None


for node in tree_2e.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    if (
        "TOURNAMENT_CARD_TEMPLATES"
        in assigned_names_2e(
            node
        )
    ):
        template_assignment_node_2f2 = node
        break


assert template_assignment_node_2f2 is not None


module_2f2 = ast.Module(
    body=[
        template_assignment_node_2f2
    ],
    type_ignores=[],
)

ast.fix_missing_locations(
    module_2f2
)


exec(
    compile(
        module_2f2,
        filename=str(
            NOTEBOOK48_SCRIPT_2D
        ),
        mode="exec",
    ),
    historical_ns_2e,
)


assert (
    "TOURNAMENT_CARD_TEMPLATES"
    in historical_ns_2e
)


TOURNAMENT_CARD_TEMPLATES_2F2 = (
    historical_ns_2e[
        "TOURNAMENT_CARD_TEMPLATES"
    ]
)


print("\nTOURNAMENT CARD TEMPLATE COUNT")
print("-" * 100)

print(
    len(
        TOURNAMENT_CARD_TEMPLATES_2F2
    )
)


assert (
    len(
        TOURNAMENT_CARD_TEMPLATES_2F2
    )
    >= 2
)


# ==========================================================================================
# 6. Inspect first two exact historical smoke-test cards
# ==========================================================================================

smoke_player_card_2f2 = (
    TOURNAMENT_CARD_TEMPLATES_2F2[
        0
    ]
)

smoke_opponent_card_2f2 = (
    TOURNAMENT_CARD_TEMPLATES_2F2[
        1
    ]
)


def card_name_2f2(
    card,
):

    if not isinstance(
        card,
        dict,
    ):
        return str(
            card
        )

    for key in [
        "Card Name",
        "name",
        "card_name",
        "Name",
    ]:

        if key in card:
            return str(
                card[
                    key
                ]
            )

    return "UNKNOWN"


print("\nEXACT HISTORICAL SMOKE CARDS")
print("-" * 100)

print(
    "Player card   :",
    card_name_2f2(
        smoke_player_card_2f2
    ),
)

print(
    "Opponent card :",
    card_name_2f2(
        smoke_opponent_card_2f2
    ),
)


print("\nPLAYER CARD DICTIONARY")
print("-" * 100)

print(
    smoke_player_card_2f2
)


print("\nOPPONENT CARD DICTIONARY")
print("-" * 100)

print(
    smoke_opponent_card_2f2
)


assert isinstance(
    smoke_player_card_2f2,
    dict,
)

assert isinstance(
    smoke_opponent_card_2f2,
    dict,
)


# ==========================================================================================
# 7. Recover create_competitive_agent() exactly
# ==========================================================================================

create_competitive_agent_node_2f2 = (
    top_level_nodes_2e.get(
        "create_competitive_agent"
    )
)


assert (
    create_competitive_agent_node_2f2
    is not None
), (
    "create_competitive_agent() was not found in Notebook 48 source."
)


print("\nCREATE_COMPETITIVE_AGENT SOURCE")
print("-" * 100)

print(
    ast.get_source_segment(
        source_2e,
        create_competitive_agent_node_2f2,
    )
)


# ==========================================================================================
# 8. Discover dependencies of create_competitive_agent()
# ==========================================================================================

competitive_refs_2f2 = referenced_names_2e(
    create_competitive_agent_node_2f2
)


competitive_dependency_rows_2f2 = []


for name in sorted(
    competitive_refs_2f2
):

    dependency_type = None

    if name in historical_ns_2e:

        dependency_type = "ALREADY_LOADED"

    elif name in top_level_nodes_2e:

        dependency_type = "DEFINITION"

    elif name in assignment_map_2e:

        dependency_type = "ASSIGNMENT"

    else:

        dependency_type = "EXTERNAL_OR_BUILTIN"


    competitive_dependency_rows_2f2.append(
        {
            "name":
                name,

            "dependency_type":
                dependency_type,

            "currently_available":
                name
                in historical_ns_2e,
        }
    )


section2f2_competitive_dependencies_df = pd.DataFrame(
    competitive_dependency_rows_2f2
)


print("\nCREATE_COMPETITIVE_AGENT DEPENDENCIES")
print("-" * 100)

display(
    section2f2_competitive_dependencies_df
)


# ==========================================================================================
# 9. Load missing direct dependencies conservatively
# ==========================================================================================

dependency_load_results_2f2 = []


for dependency_name in sorted(
    competitive_refs_2f2
):

    if dependency_name in historical_ns_2e:
        continue


    # --------------------------------------------------------------------------------------
    # Required historical constant / assignment
    # --------------------------------------------------------------------------------------

    if dependency_name in assignment_map_2e:

        node = assignment_map_2e[
            dependency_name
        ]

        module = ast.Module(
            body=[
                node
            ],
            type_ignores=[],
        )

        ast.fix_missing_locations(
            module
        )

        try:

            exec(
                compile(
                    module,
                    filename=str(
                        NOTEBOOK48_SCRIPT_2D
                    ),
                    mode="exec",
                ),
                historical_ns_2e,
            )

            dependency_load_results_2f2.append(
                {
                    "name":
                        dependency_name,

                    "kind":
                        "ASSIGNMENT",

                    "loaded":
                        dependency_name
                        in historical_ns_2e,

                    "error":
                        None,
                }
            )

        except Exception as exc:

            dependency_load_results_2f2.append(
                {
                    "name":
                        dependency_name,

                    "kind":
                        "ASSIGNMENT",

                    "loaded":
                        False,

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


    # --------------------------------------------------------------------------------------
    # Required historical function/class
    # --------------------------------------------------------------------------------------

    elif dependency_name in top_level_nodes_2e:

        node = top_level_nodes_2e[
            dependency_name
        ]

        module = ast.Module(
            body=[
                node
            ],
            type_ignores=[],
        )

        ast.fix_missing_locations(
            module
        )

        try:

            exec(
                compile(
                    module,
                    filename=str(
                        NOTEBOOK48_SCRIPT_2D
                    ),
                    mode="exec",
                ),
                historical_ns_2e,
            )

            dependency_load_results_2f2.append(
                {
                    "name":
                        dependency_name,

                    "kind":
                        "DEFINITION",

                    "loaded":
                        dependency_name
                        in historical_ns_2e,

                    "error":
                        None,
                }
            )

        except Exception as exc:

            dependency_load_results_2f2.append(
                {
                    "name":
                        dependency_name,

                    "kind":
                        "DEFINITION",

                    "loaded":
                        False,

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


section2f2_dependency_load_df = pd.DataFrame(
    dependency_load_results_2f2
)


print("\nCOMPETITIVE AGENT DEPENDENCY LOAD RESULTS")
print("-" * 100)

if section2f2_dependency_load_df.empty:

    print(
        "No additional dependencies required."
    )

else:

    display(
        section2f2_dependency_load_df
    )


# ==========================================================================================
# 10. Load exact create_competitive_agent() function
# ==========================================================================================

create_agent_module_2f2 = ast.Module(
    body=[
        create_competitive_agent_node_2f2
    ],
    type_ignores=[],
)

ast.fix_missing_locations(
    create_agent_module_2f2
)


exec(
    compile(
        create_agent_module_2f2,
        filename=str(
            NOTEBOOK48_SCRIPT_2D
        ),
        mode="exec",
    ),
    historical_ns_2e,
)


assert (
    "create_competitive_agent"
    in historical_ns_2e
)


create_competitive_agent_2f2 = (
    historical_ns_2e[
        "create_competitive_agent"
    ]
)


# ==========================================================================================
# 11. Instantiate the exact historical evaluated agent
# ==========================================================================================

competitive_agent_2f2 = None
competitive_agent_error_2f2 = None


try:

    competitive_agent_2f2 = (
        create_competitive_agent_2f2()
    )

except Exception as exc:

    competitive_agent_error_2f2 = (
        f"{type(exc).__name__}: {exc}"
    )


print("\nHISTORICAL COMPETITIVE AGENT CREATION")
print("-" * 100)

print(
    "Created:",
    competitive_agent_2f2
    is not None,
)

print(
    "Type:",
    (
        type(
            competitive_agent_2f2
        ).__name__
        if competitive_agent_2f2
        is not None
        else None
    ),
)

print(
    "Error:",
    competitive_agent_error_2f2,
)


assert (
    competitive_agent_2f2
    is not None
), (
    competitive_agent_error_2f2
)


# ==========================================================================================
# 12. Bind historical smoke-test objects
# ==========================================================================================

competitive_tournament_agent_2f2 = (
    competitive_agent_2f2
)

historical_smoke_inputs_2f2 = {
    "evaluated_agent":
        competitive_tournament_agent_2f2,

    "player_card":
        smoke_player_card_2f2,

    "opponent_card":
        smoke_opponent_card_2f2,

    "starting_side":
        "Player",

    "evaluated_agent_side":
        "Player",

    "max_turns":
        20,

    "search_depth":
        int(
            historical_ns_2e[
                "SIMULATOR_SEARCH_DEPTH"
            ]
        ),
}


print("\nRECOVERED HISTORICAL SMOKE INPUTS")
print("-" * 100)

print(
    "Evaluated agent :",
    type(
        historical_smoke_inputs_2f2[
            "evaluated_agent"
        ]
    ).__name__,
)

print(
    "Player card     :",
    card_name_2f2(
        historical_smoke_inputs_2f2[
            "player_card"
        ]
    ),
)

print(
    "Opponent card   :",
    card_name_2f2(
        historical_smoke_inputs_2f2[
            "opponent_card"
        ]
    ),
)

print(
    "Starting side   :",
    historical_smoke_inputs_2f2[
        "starting_side"
    ],
)

print(
    "Evaluated side  :",
    historical_smoke_inputs_2f2[
        "evaluated_agent_side"
    ],
)

print(
    "Max turns       :",
    historical_smoke_inputs_2f2[
        "max_turns"
    ],
)

print(
    "Search depth    :",
    historical_smoke_inputs_2f2[
        "search_depth"
    ],
)


# ==========================================================================================
# 13. Validation
# ==========================================================================================

section2f2_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "card templates recovered",

            "passed":
                len(
                    TOURNAMENT_CARD_TEMPLATES_2F2
                )
                >= 2,
        },

        {
            "validation":
                "exact smoke player card recovered",

            "passed":
                isinstance(
                    smoke_player_card_2f2,
                    dict,
                ),
        },

        {
            "validation":
                "exact smoke opponent card recovered",

            "passed":
                isinstance(
                    smoke_opponent_card_2f2,
                    dict,
                ),
        },

        {
            "validation":
                "competitive agent factory recovered",

            "passed":
                callable(
                    create_competitive_agent_2f2
                ),
        },

        {
            "validation":
                "historical evaluated agent instantiated",

            "passed":
                competitive_tournament_agent_2f2
                is not None,
        },

        {
            "validation":
                "historical smoke contract reconstructed",

            "passed":
                (
                    historical_smoke_inputs_2f2[
                        "starting_side"
                    ]
                    ==
                    "Player"
                    and
                    historical_smoke_inputs_2f2[
                        "evaluated_agent_side"
                    ]
                    ==
                    "Player"
                    and
                    historical_smoke_inputs_2f2[
                        "max_turns"
                    ]
                    ==
                    20
                    and
                    historical_smoke_inputs_2f2[
                        "search_depth"
                    ]
                    ==
                    6
                ),
        },
    ]
)


print("\nSECTION 2F.2 VALIDATION")
print("-" * 100)

display(
    section2f2_validation_df
)


assert (
    section2f2_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 48 CARD TEMPLATES RECOVERED")
print("✅ EXACT HISTORICAL SMOKE CARDS RECOVERED")
print("✅ EXACT COMPETITIVE AGENT FACTORY RECOVERED")
print("✅ HISTORICAL EVALUATED AGENT INSTANTIATED")
print("✅ ORIGINAL NOTEBOOK 48 SMOKE CONTRACT RECONSTRUCTED")
print("✅ NO CARD OR AGENT FABRICATION USED")
print("✅ SECTION 2F.2 COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2F.2 — RECOVER EXACT HISTORICAL SMOKE-TEST OBJECTS
====================================================================================================

HISTORICAL SMOKE OBJECT SOURCE INVENTORY
----------------------------------------------------------------------------------------------------

,name,kind,line_number,source
0,TOURNAMENT_CARD_TEMPLATES,ASSIGNMENT,2422,TOURNAMENT_CARD_TEMPLATES = [\n {\n ...
1,competitive_tournament_agent,ASSIGNMENT,2944,competitive_tournament_agent = (\n Competit...
2,create_competitive_agent,FUNCTION,3267,def create_competitive_agent() -> CompetitiveP...

EXACT HISTORICAL SMOKE OBJECT SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
TOURNAMENT_CARD_TEMPLATES
====================================================================================================
TOURNAMENT_CARD_TEMPLATES = [
    {
        "name": "Pikachu",
        "hp": 120,
        "attacks": [
            {
                "Move Name":
                    "Quick Attack",
                "damage_numeric":
                    30,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Thunderbolt",
                "damage_numeric":
                    90,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },

    {
        "name": "Charmander",
        "hp": 100,
        "attacks": [
            {
                "Move Name":
                    "Scratch",
                "damage_numeric":
                    20,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Flame Tail",
                "damage_numeric":
                    50,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },

    {
        "name": "Squirtle",
        "hp": 110,
        "attacks": [
            {
                "Move Name":
                    "Tackle",
                "damage_numeric":
                    20,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Water Pulse",
                "damage_numeric":
                    60,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },

    {
        "name": "Bulbasaur",
        "hp": 110,
        "attacks": [
            {
                "Move Name":
                    "Vine Whip",
                "damage_numeric":
                    30,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Razor Leaf",
                "damage_numeric":
                    70,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },

    {
        "name": "Eevee",
        "hp": 100,
        "attacks": [
            {
                "Move Name":
                    "Tail Whap",
                "damage_numeric":
                    20,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Bite",
                "damage_numeric":
                    50,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },

    {
        "name": "Meowth",
        "hp": 90,
        "attacks": [
            {
                "Move Name":
                    "Scratch",
                "damage_numeric":
                    20,
                "energy_cost":
                    1,
                "Effect Explanation":
                    None,
            },
            {
                "Move Name":
                    "Fury Swipes",
                "damage_numeric":
                    60,
                "energy_cost":
                    2,
                "Effect Explanation":
                    None,
            },
        ],
    },
]

====================================================================================================
competitive_tournament_agent
====================================================================================================
competitive_tournament_agent = (
    CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )
)

====================================================================================================
create_competitive_agent
====================================================================================================
def create_competitive_agent() -> CompetitivePolicyAgent:
    return CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )

TOURNAMENT CARD TEMPLATE COUNT
----------------------------------------------------------------------------------------------------
6

EXACT HISTORICAL SMOKE CARDS
----------------------------------------------------------------------------------------------------
Player card   : Pikachu
Opponent card : Charmander

PLAYER CARD DICTIONARY
----------------------------------------------------------------------------------------------------
{'name': 'Pikachu', 'hp': 120, 'attacks': [{'Move Name': 'Quick Attack', 'damage_numeric': 30, 'energy_cost': 1, 'Effect Explanation': None}, {'Move Name': 'Thunderbolt', 'damage_numeric': 90, 'energy_cost': 2, 'Effect Explanation': None}]}

OPPONENT CARD DICTIONARY
----------------------------------------------------------------------------------------------------
{'name': 'Charmander', 'hp': 100, 'attacks': [{'Move Name': 'Scratch', 'damage_numeric': 20, 'energy_cost': 1, 'Effect Explanation': None}, {'Move Name': 'Flame Tail', 'damage_numeric': 50, 'energy_cost': 2, 'Effect Explanation': None}]}

CREATE_COMPETITIVE_AGENT SOURCE
----------------------------------------------------------------------------------------------------
def create_competitive_agent() -> CompetitivePolicyAgent:
    return CompetitivePolicyAgent(
        checkpoint_path=
            BEST_POLICY_CHECKPOINT,

        device=str(
            DEVICE
        ),

        name=
            "Competitive Policy",
    )

CREATE_COMPETITIVE_AGENT DEPENDENCIES
----------------------------------------------------------------------------------------------------

                     name      dependency_type  currently_available
0  BEST_POLICY_CHECKPOINT           ASSIGNMENT                False
1  CompetitivePolicyAgent  EXTERNAL_OR_BUILTIN                False
2                  DEVICE           ASSIGNMENT                False
3                     str  EXTERNAL_OR_BUILTIN                False

COMPETITIVE AGENT DEPENDENCY LOAD RESULTS
----------------------------------------------------------------------------------------------------

,name,kind,loaded,error
0,BEST_POLICY_CHECKPOINT,ASSIGNMENT,False,NameError: name 'PROJECT_ROOT' is not defined
1,DEVICE,ASSIGNMENT,False,NameError: name 'torch' is not defined

NameError: name 'CompetitivePolicyAgent' is not defined

In [17]:
# ==========================================================================================
# SECTION 2F.3 — RECOVER HISTORICAL CompetitivePolicyAgent DEPENDENCIES
# ==========================================================================================

print("=" * 100)
print("SECTION 2F.3 — RECOVER HISTORICAL CompetitivePolicyAgent DEPENDENCIES")
print("=" * 100)

import ast
import pandas as pd


# ==========================================================================================
# 1. Search Notebook 48 imports for CompetitivePolicyAgent
# ==========================================================================================

competitive_import_rows_2f3 = []


for node in tree_2e.body:

    if not isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        continue

    source_segment = ast.get_source_segment(
        source_2e,
        node,
    )

    if (
        source_segment
        and
        "CompetitivePolicyAgent"
        in source_segment
    ):

        competitive_import_rows_2f3.append(
            {
                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "source":
                    source_segment,
            }
        )


section2f3_competitive_import_df = pd.DataFrame(
    competitive_import_rows_2f3
)


print("\nCompetitivePolicyAgent IMPORT SOURCES")
print("-" * 100)

display(
    section2f3_competitive_import_df
)


assert not section2f3_competitive_import_df.empty, (
    "No CompetitivePolicyAgent import was found in Notebook 48 source."
)


# ==========================================================================================
# 2. Recover exact BEST_POLICY_CHECKPOINT and DEVICE assignments
# ==========================================================================================

TARGET_ASSIGNMENTS_2F3 = [
    "BEST_POLICY_CHECKPOINT",
    "DEVICE",
]


assignment_source_rows_2f3 = []


for target_name in TARGET_ASSIGNMENTS_2F3:

    node = assignment_map_2e.get(
        target_name
    )

    assert node is not None, (
        f"{target_name} assignment not found."
    )

    assignment_source_rows_2f3.append(
        {
            "name":
                target_name,

            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "source":
                ast.get_source_segment(
                    source_2e,
                    node,
                ),
        }
    )


section2f3_assignment_source_df = pd.DataFrame(
    assignment_source_rows_2f3
)


print("\nHISTORICAL CONFIGURATION ASSIGNMENTS")
print("-" * 100)

display(
    section2f3_assignment_source_df
)


for _, row in section2f3_assignment_source_df.iterrows():

    print("\n" + "=" * 100)
    print(row["name"])
    print("=" * 100)
    print(row["source"])


# ==========================================================================================
# 3. Execute exact CompetitivePolicyAgent import only
# ==========================================================================================

competitive_import_loaded_2f3 = False
competitive_import_error_2f3 = None


for node in tree_2e.body:

    if not isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        continue

    source_segment = ast.get_source_segment(
        source_2e,
        node,
    )

    if not (
        source_segment
        and
        "CompetitivePolicyAgent"
        in source_segment
    ):
        continue

    module = ast.Module(
        body=[node],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )

    try:

        exec(
            compile(
                module,
                filename=str(
                    NOTEBOOK48_SCRIPT_2D
                ),
                mode="exec",
            ),
            historical_ns_2e,
        )

        competitive_import_loaded_2f3 = (
            "CompetitivePolicyAgent"
            in historical_ns_2e
        )

    except Exception as exc:

        competitive_import_error_2f3 = (
            f"{type(exc).__name__}: {exc}"
        )

    break


print("\nCompetitivePolicyAgent IMPORT RESULT")
print("-" * 100)

print(
    "Loaded:",
    competitive_import_loaded_2f3,
)

print(
    "Type:",
    (
        historical_ns_2e[
            "CompetitivePolicyAgent"
        ]
        if competitive_import_loaded_2f3
        else None
    ),
)

print(
    "Error:",
    competitive_import_error_2f3,
)


# ==========================================================================================
# 4. Execute exact historical configuration assignments
# ==========================================================================================

config_load_rows_2f3 = []


for target_name in TARGET_ASSIGNMENTS_2F3:

    node = assignment_map_2e[
        target_name
    ]

    module = ast.Module(
        body=[node],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )

    try:

        exec(
            compile(
                module,
                filename=str(
                    NOTEBOOK48_SCRIPT_2D
                ),
                mode="exec",
            ),
            historical_ns_2e,
        )

        config_load_rows_2f3.append(
            {
                "name":
                    target_name,

                "loaded":
                    target_name
                    in historical_ns_2e,

                "value":
                    repr(
                        historical_ns_2e.get(
                            target_name
                        )
                    ),

                "error":
                    None,
            }
        )

    except Exception as exc:

        config_load_rows_2f3.append(
            {
                "name":
                    target_name,

                "loaded":
                    False,

                "value":
                    None,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section2f3_config_load_df = pd.DataFrame(
    config_load_rows_2f3
)


print("\nCONFIGURATION LOAD RESULTS")
print("-" * 100)

display(
    section2f3_config_load_df
)


# ==========================================================================================
# 5. Re-load create_competitive_agent() now that dependencies exist
# ==========================================================================================

create_agent_module_2f3 = ast.Module(
    body=[
        create_competitive_agent_node_2f2
    ],
    type_ignores=[],
)

ast.fix_missing_locations(
    create_agent_module_2f3
)


create_agent_load_error_2f3 = None


try:

    exec(
        compile(
            create_agent_module_2f3,
            filename=str(
                NOTEBOOK48_SCRIPT_2D
            ),
            mode="exec",
        ),
        historical_ns_2e,
    )

except Exception as exc:

    create_agent_load_error_2f3 = (
        f"{type(exc).__name__}: {exc}"
    )


print("\nCREATE_COMPETITIVE_AGENT RELOAD")
print("-" * 100)

print(
    "Available:",
    "create_competitive_agent"
    in historical_ns_2e,
)

print(
    "Error:",
    create_agent_load_error_2f3,
)


# ==========================================================================================
# 6. Instantiate exact historical competitive agent
# ==========================================================================================

competitive_agent_2f3 = None
competitive_agent_error_2f3 = None


if (
    "create_competitive_agent"
    in historical_ns_2e
):

    try:

        competitive_agent_2f3 = (
            historical_ns_2e[
                "create_competitive_agent"
            ]()
        )

    except Exception as exc:

        competitive_agent_error_2f3 = (
            f"{type(exc).__name__}: {exc}"
        )


print("\nHISTORICAL COMPETITIVE AGENT")
print("-" * 100)

print(
    "Created:",
    competitive_agent_2f3
    is not None,
)

print(
    "Type:",
    (
        type(
            competitive_agent_2f3
        ).__name__
        if competitive_agent_2f3
        is not None
        else None
    ),
)

print(
    "Error:",
    competitive_agent_error_2f3,
)


# ==========================================================================================
# 7. Validation
# ==========================================================================================

section2f3_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "CompetitivePolicyAgent import recovered",

            "passed":
                competitive_import_loaded_2f3,
        },

        {
            "validation":
                "BEST_POLICY_CHECKPOINT loaded",

            "passed":
                (
                    "BEST_POLICY_CHECKPOINT"
                    in historical_ns_2e
                ),
        },

        {
            "validation":
                "DEVICE loaded",

            "passed":
                (
                    "DEVICE"
                    in historical_ns_2e
                ),
        },

        {
            "validation":
                "create_competitive_agent available",

            "passed":
                (
                    "create_competitive_agent"
                    in historical_ns_2e
                ),
        },

        {
            "validation":
                "historical competitive agent instantiated",

            "passed":
                competitive_agent_2f3
                is not None,
        },
    ]
)


print("\nSECTION 2F.3 VALIDATION")
print("-" * 100)

display(
    section2f3_validation_df
)


if section2f3_validation_df[
    "passed"
].all():

    competitive_tournament_agent_2f3 = (
        competitive_agent_2f3
    )

    print("\n" + "=" * 100)
    print("✅ CompetitivePolicyAgent IMPORT RECOVERED")
    print("✅ HISTORICAL CHECKPOINT PATH RECOVERED")
    print("✅ HISTORICAL DEVICE CONFIGURATION RECOVERED")
    print("✅ HISTORICAL COMPETITIVE AGENT INSTANTIATED")
    print("✅ READY FOR EXACT NOTEBOOK 48 SMOKE TEST")
    print("✅ SECTION 2F.3 COMPLETE")
    print("=" * 100)

else:

    print("\n" + "=" * 100)
    print("⚠️ HISTORICAL COMPETITIVE AGENT STILL NEEDS DEPENDENCY REPAIR")
    print("⚠️ DO NOT RUN THE SMOKE TEST YET")
    print("=" * 100)

====================================================================================================
SECTION 2F.3 — RECOVER HISTORICAL CompetitivePolicyAgent DEPENDENCIES
====================================================================================================

CompetitivePolicyAgent IMPORT SOURCES
----------------------------------------------------------------------------------------------------

   line_number                                             source
0         1775  from src.competitive.competitive_policy_agent ...

HISTORICAL CONFIGURATION ASSIGNMENTS
----------------------------------------------------------------------------------------------------

,name,line_number,source
0,BEST_POLICY_CHECKPOINT,151,BEST_POLICY_CHECKPOINT = (\n PROJECT_ROOT\n...
1,DEVICE,140,"DEVICE = torch.device(\n ""cuda""\n if tor..."

====================================================================================================
BEST_POLICY_CHECKPOINT
====================================================================================================
BEST_POLICY_CHECKPOINT = (
    PROJECT_ROOT
    / "models"
    / "competitive"
    / "competitive_policy_best.pt"
)

====================================================================================================
DEVICE
====================================================================================================
DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

CompetitivePolicyAgent IMPORT RESULT
----------------------------------------------------------------------------------------------------
Loaded: False
Type: None
Error: ModuleNotFoundError: No module named 'torch'

CONFIGURATION LOAD RESULTS
----------------------------------------------------------------------------------------------------

,name,loaded,value,error
0,BEST_POLICY_CHECKPOINT,False,None,NameError: name 'PROJECT_ROOT' is not defined
1,DEVICE,False,None,NameError: name 'torch' is not defined

CREATE_COMPETITIVE_AGENT RELOAD
----------------------------------------------------------------------------------------------------
Available: False
Error: NameError: name 'CompetitivePolicyAgent' is not defined

HISTORICAL COMPETITIVE AGENT
----------------------------------------------------------------------------------------------------
Created: False
Type: None
Error: None

SECTION 2F.3 VALIDATION
----------------------------------------------------------------------------------------------------

                                  validation  passed
0    CompetitivePolicyAgent import recovered   False
1              BEST_POLICY_CHECKPOINT loaded   False
2                              DEVICE loaded   False
3         create_competitive_agent available   False
4  historical competitive agent instantiated   False

====================================================================================================
⚠️ HISTORICAL COMPETITIVE AGENT STILL NEEDS DEPENDENCY REPAIR
⚠️ DO NOT RUN THE SMOKE TEST YET
====================================================================================================

In [18]:
# ==========================================================================================
# SECTION 2F.4 — DOCUMENT HISTORICAL POLICY INCOMPATIBILITY AND LOCK FAIR R3 SUBSTITUTION
# ==========================================================================================

print("=" * 100)
print("SECTION 2F.4 — DOCUMENT HISTORICAL POLICY INCOMPATIBILITY AND LOCK FAIR R3 SUBSTITUTION")
print("=" * 100)

import json
import pandas as pd


# ==========================================================================================
# 1. Record the exact incompatibility
# ==========================================================================================

historical_policy_status_2f4 = {
    "historical_policy":
        "CompetitivePolicyAgent",

    "historical_checkpoint":
        "models/competitive/competitive_policy_best.pt",

    "historical_framework":
        "PyTorch",

    "historical_import_available":
        False,

    "historical_import_error":
        "ModuleNotFoundError: No module named 'torch'",

    "install_torch_for_notebook60":
        False,

    "historical_policy_recreation_required":
        False,

    "historical_baselines_available":
        True,

    "historical_match_runner_available":
        True,

    "historical_state_builder_available":
        True,

    "historical_card_templates_available":
        True,

    "historical_benchmark_structure_available":
        True,

    "historical_benchmark_results_available":
        True,

    "current_evaluated_policy":
        "R3_STATE_CENTRIC_POLICY",

    "current_model_type":
        "RandomForestClassifier",

    "evaluation_strategy":
        "Use frozen R3 policy as evaluated agent "
        "against exact Notebook 48 baseline agents "
        "under reconstructed Notebook 48 tournament structure.",

    "r3_retraining":
        False,

    "r3_model_modification":
        False,
}


print("\nHISTORICAL POLICY COMPATIBILITY STATUS")
print("-" * 100)

for key, value in historical_policy_status_2f4.items():

    print(
        f"{key:<40}: {value}"
    )


# ==========================================================================================
# 2. Define what is preserved from Notebook 48
# ==========================================================================================

preserved_components_2f4 = pd.DataFrame(
    [
        {
            "component":
                "Random Baseline",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Greedy Damage Baseline",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Depth-6 Search Baseline",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Tournament card templates",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Tournament state builder",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Tournament match runner",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "300-match benchmark structure",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "50/50 Player/Opponent split per baseline",

            "status":
                "PRESERVED",

            "exact_historical":
                True,
        },

        {
            "component":
                "Historical CompetitivePolicyAgent",

            "status":
                "NOT RECREATED",

            "exact_historical":
                False,
        },

        {
            "component":
                "Current R3 evaluated policy",

            "status":
                "SUBSTITUTED AS EVALUATED AGENT",

            "exact_historical":
                False,
        },
    ]
)


print("\nBENCHMARK COMPONENT PRESERVATION")
print("-" * 100)

display(
    preserved_components_2f4
)


# ==========================================================================================
# 3. Fair-comparison interpretation
# ==========================================================================================

print("\nFAIR-COMPARISON INTERPRETATION")
print("-" * 100)

print(
    "Notebook 48 is retained as the historical reference experiment."
)

print(
    "Its three opponent baselines, tournament state construction, "
    "match runner, card templates, side balancing, and match counts "
    "remain unchanged."
)

print(
    "The historical PyTorch CompetitivePolicyAgent is not recreated "
    "because PyTorch is unavailable in the current Notebook 60 runtime."
)

print(
    "The frozen R3 RandomForest policy becomes the evaluated policy "
    "for the new experiment."
)

print(
    "Therefore Notebook 60 is a controlled successor benchmark, "
    "not a byte-for-byte rerun of Notebook 48."
)


# ==========================================================================================
# 4. Save benchmark transition record
# ==========================================================================================

SECTION2F4_STATUS_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2f4_historical_policy_compatibility.json"
)

SECTION2F4_COMPONENT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section2f4_benchmark_component_preservation.csv"
)


with open(
    SECTION2F4_STATUS_FILE,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        historical_policy_status_2f4,
        file,
        indent=2,
    )


preserved_components_2f4.to_csv(
    SECTION2F4_COMPONENT_FILE,
    index=False,
)


# ==========================================================================================
# 5. Validation
# ==========================================================================================

section2f4_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical torch incompatibility documented",

            "passed":
                historical_policy_status_2f4[
                    "historical_import_available"
                ]
                is False,
        },

        {
            "validation":
                "no torch installation requested",

            "passed":
                historical_policy_status_2f4[
                    "install_torch_for_notebook60"
                ]
                is False,
        },

        {
            "validation":
                "three exact baselines available",

            "passed":
                all(
                    name in baseline_instances_2e
                    for name in [
                        "Random Baseline",
                        "Greedy Damage Baseline",
                        "Depth-6 Search Baseline",
                    ]
                ),
        },

        {
            "validation":
                "historical harness available",

            "passed":
                (
                    callable(
                        create_tournament_state_2e
                    )
                    and
                    callable(
                        run_tournament_match_2e
                    )
                ),
        },

        {
            "validation":
                "R3 designated as new evaluated policy",

            "passed":
                historical_policy_status_2f4[
                    "current_evaluated_policy"
                ]
                ==
                "R3_STATE_CENTRIC_POLICY",
        },

        {
            "validation":
                "R3 remains frozen",

            "passed":
                (
                    historical_policy_status_2f4[
                        "r3_retraining"
                    ]
                    is False
                    and
                    historical_policy_status_2f4[
                        "r3_model_modification"
                    ]
                    is False
                ),
        },

        {
            "validation":
                "transition evidence saved",

            "passed":
                (
                    SECTION2F4_STATUS_FILE.exists()
                    and
                    SECTION2F4_COMPONENT_FILE.exists()
                ),
        },
    ]
)


print("\nSECTION 2F.4 VALIDATION")
print("-" * 100)

display(
    section2f4_validation_df
)


assert (
    section2f4_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ HISTORICAL PYTORCH POLICY INCOMPATIBILITY DOCUMENTED")
print("✅ NO PYTORCH INSTALLATION REQUIRED")
print("✅ THREE EXACT NOTEBOOK 48 BASELINES PRESERVED")
print("✅ HISTORICAL TOURNAMENT HARNESS PRESERVED")
print("✅ 300-MATCH / 50+50 SIDE STRUCTURE PRESERVED")
print("✅ FROZEN R3 DESIGNATED AS NEW EVALUATED POLICY")
print("✅ NO R3 RETRAINING OR MODEL MODIFICATION")
print("✅ SECTION 2F.4 COMPLETE")

print("=" * 100)

====================================================================================================
SECTION 2F.4 — DOCUMENT HISTORICAL POLICY INCOMPATIBILITY AND LOCK FAIR R3 SUBSTITUTION
====================================================================================================

HISTORICAL POLICY COMPATIBILITY STATUS
----------------------------------------------------------------------------------------------------
historical_policy                       : CompetitivePolicyAgent
historical_checkpoint                   : models/competitive/competitive_policy_best.pt
historical_framework                    : PyTorch
historical_import_available             : False
historical_import_error                 : ModuleNotFoundError: No module named 'torch'
install_torch_for_notebook60            : False
historical_policy_recreation_required   : False
historical_baselines_available          : True
historical_match_runner_available       : True
historical_state_builder_available      : True
historical_card_templates_available     : True
historical_benchmark_structure_available: True
historical_benchmark_results_available  : True
current_evaluated_policy                : R3_STATE_CENTRIC_POLICY
current_model_type                      : RandomForestClassifier
evaluation_strategy                     : Use frozen R3 policy as evaluated agent against exact Notebook 48 baseline agents under reconstructed Notebook 48 tournament structure.
r3_retraining                           : False
r3_model_modification                   : False

BENCHMARK COMPONENT PRESERVATION
----------------------------------------------------------------------------------------------------

,component,status,exact_historical
0,Random Baseline,PRESERVED,True
1,Greedy Damage Baseline,PRESERVED,True
2,Depth-6 Search Baseline,PRESERVED,True
3,Tournament card templates,PRESERVED,True
4,Tournament state builder,PRESERVED,True
5,Tournament match runner,PRESERVED,True
6,300-match benchmark structure,PRESERVED,True
7,50/50 Player/Opponent split per baseline,PRESERVED,True
8,Historical CompetitivePolicyAgent,NOT RECREATED,False
9,Current R3 evaluated policy,SUBSTITUTED AS EVALUATED AGENT,False

FAIR-COMPARISON INTERPRETATION
----------------------------------------------------------------------------------------------------
Notebook 48 is retained as the historical reference experiment.
Its three opponent baselines, tournament state construction, match runner, card templates, side balancing, and match counts remain unchanged.
The historical PyTorch CompetitivePolicyAgent is not recreated because PyTorch is unavailable in the current Notebook 60 runtime.
The frozen R3 RandomForest policy becomes the evaluated policy for the new experiment.
Therefore Notebook 60 is a controlled successor benchmark, not a byte-for-byte rerun of Notebook 48.

SECTION 2F.4 VALIDATION
----------------------------------------------------------------------------------------------------

                                    validation  passed
0  historical torch incompatibility documented    True
1              no torch installation requested    True
2              three exact baselines available    True
3                 historical harness available    True
4        R3 designated as new evaluated policy    True
5                            R3 remains frozen    True
6                    transition evidence saved    True

====================================================================================================
✅ HISTORICAL PYTORCH POLICY INCOMPATIBILITY DOCUMENTED
✅ NO PYTORCH INSTALLATION REQUIRED
✅ THREE EXACT NOTEBOOK 48 BASELINES PRESERVED
✅ HISTORICAL TOURNAMENT HARNESS PRESERVED
✅ 300-MATCH / 50+50 SIDE STRUCTURE PRESERVED
✅ FROZEN R3 DESIGNATED AS NEW EVALUATED POLICY
✅ NO R3 RETRAINING OR MODEL MODIFICATION
✅ SECTION 2F.4 COMPLETE
====================================================================================================

In [20]:
# ==========================================================================================
# SECTION 3A — RECOVER EXACT NOTEBOOK 59 R3 PRODUCTION CONTRACT
# ==========================================================================================

print("=" * 100)
print("SECTION 3A — RECOVER EXACT NOTEBOOK 59 R3 PRODUCTION CONTRACT")
print("=" * 100)

from pathlib import Path
import ast
import re
import pandas as pd


# ==========================================================================================
# 1. Authoritative Notebook 59 exported script
# ==========================================================================================

NOTEBOOK59_SCRIPT_3A = (
    PROJECT_ROOT
    / "scripts"
    / "59_live_competitive_evaluation.py"
)

print("\nNOTEBOOK 59 PRODUCTION SCRIPT")
print("-" * 100)
print(NOTEBOOK59_SCRIPT_3A)

assert NOTEBOOK59_SCRIPT_3A.exists(), (
    f"Notebook 59 script missing: {NOTEBOOK59_SCRIPT_3A}"
)

assert NOTEBOOK59_SCRIPT_3A.stat().st_size > 0


source_3a = NOTEBOOK59_SCRIPT_3A.read_text(
    encoding="utf-8-sig",
    errors="ignore",
)

tree_3a = ast.parse(
    source_3a
)


# ==========================================================================================
# 2. Target R3 production objects
# ==========================================================================================

TARGET_R3_OBJECTS_3A = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "R3LivePolicyEngine",
    "R3LiveBattleAgent",
]


# ==========================================================================================
# 3. Recover exact top-level functions/classes
# ==========================================================================================

r3_objects_3a = {}


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        continue

    if node.name not in TARGET_R3_OBJECTS_3A:
        continue

    r3_objects_3a[
        node.name
    ] = {
        "name":
            node.name,

        "object_type":
            (
                "CLASS"
                if isinstance(
                    node,
                    ast.ClassDef,
                )
                else
                "FUNCTION"
            ),

        "line_number":
            node.lineno,

        "source":
            ast.get_source_segment(
                source_3a,
                node,
            ),
    }


section3a_object_inventory_df = pd.DataFrame(
    [
        {
            "name":
                name,

            "object_type":
                data[
                    "object_type"
                ],

            "line_number":
                data[
                    "line_number"
                ],

            "recovered":
                bool(
                    data[
                        "source"
                    ]
                ),
        }

        for name, data
        in r3_objects_3a.items()
    ]
)


print("\nR3 PRODUCTION OBJECT INVENTORY")
print("-" * 100)

display(
    section3a_object_inventory_df
)


# ==========================================================================================
# 4. Require the key production objects
# ==========================================================================================

missing_r3_objects_3a = [
    name
    for name in TARGET_R3_OBJECTS_3A
    if name not in r3_objects_3a
]


print("\nR3 OBJECT CHECK")
print("-" * 100)

if missing_r3_objects_3a:

    print(
        "Missing:",
        missing_r3_objects_3a,
    )

else:

    print(
        "All requested Notebook 59 R3 production objects recovered."
    )


# ==========================================================================================
# 5. Search Notebook 59 for R3 model / artifact assignments
# ==========================================================================================

R3_ASSIGNMENT_TOKENS_3A = [
    "r3_live_model",
    "r3_live_feature_names",
    "R3",
    "NOTEBOOK53",
    "MODEL_PATH",
    "FEATURE",
    "joblib",
]


assignment_rows_3a = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    source_segment = ast.get_source_segment(
        source_3a,
        node,
    )

    if not source_segment:
        continue

    source_lower = source_segment.lower()

    if not any(
        token.lower()
        in source_lower
        for token in R3_ASSIGNMENT_TOKENS_3A
    ):
        continue


    assigned_names = []


    if isinstance(
        node,
        ast.Assign,
    ):

        targets = node.targets

    else:

        targets = [
            node.target
        ]


    for target in targets:

        if isinstance(
            target,
            ast.Name,
        ):

            assigned_names.append(
                target.id
            )

        elif isinstance(
            target,
            (
                ast.Tuple,
                ast.List,
            ),
        ):

            for element in target.elts:

                if isinstance(
                    element,
                    ast.Name,
                ):

                    assigned_names.append(
                        element.id
                    )


    assignment_rows_3a.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "assigned_names":
                assigned_names,

            "source":
                source_segment,
        }
    )


section3a_assignment_df = pd.DataFrame(
    assignment_rows_3a
)


print("\nR3-RELATED NOTEBOOK 59 ASSIGNMENTS")
print("-" * 100)

display(
    section3a_assignment_df
)


# ==========================================================================================
# 6. Search source lines for exact model loading operations
# ==========================================================================================

MODEL_LOAD_TERMS_3A = [
    "joblib.load",
    "pickle.load",
    "r3_live_model",
    "RandomForestClassifier",
    "model_path",
    "notebook53",
    "encoded_feature_names",
    "raw_feature_schema",
]


model_load_rows_3a = []


for line_number, line in enumerate(
    source_3a.splitlines(),
    start=1,
):

    line_lower = line.lower()

    if any(
        term.lower()
        in line_lower
        for term in MODEL_LOAD_TERMS_3A
    ):

        model_load_rows_3a.append(
            {
                "line_number":
                    line_number,

                "source_line":
                    line.strip(),
            }
        )


section3a_model_load_lines_df = pd.DataFrame(
    model_load_rows_3a
)


print("\nR3 MODEL / ARTIFACT LOAD LINES")
print("-" * 100)

display(
    section3a_model_load_lines_df
)


# ==========================================================================================
# 7. Print context around r3_live_model construction
# ==========================================================================================

source_lines_3a = source_3a.splitlines()

r3_model_contexts_3a = []


for row in model_load_rows_3a:

    if (
        "r3_live_model"
        not in row[
            "source_line"
        ].lower()
    ):
        continue

    line_number = int(
        row[
            "line_number"
        ]
    )

    start = max(
        0,
        line_number - 30,
    )

    end = min(
        len(
            source_lines_3a
        ),
        line_number + 40,
    )

    r3_model_contexts_3a.append(
        {
            "line_number":
                line_number,

            "context":
                "\n".join(
                    source_lines_3a[
                        start:end
                    ]
                ),
        }
    )


print("\nR3 LIVE MODEL CONSTRUCTION CONTEXT")
print("-" * 100)


for index, record in enumerate(
    r3_model_contexts_3a[:10],
    start=1,
):

    print("\n" + "=" * 100)
    print(
        f"CONTEXT {index} — AROUND LINE "
        f"{record['line_number']}"
    )
    print("-" * 100)

    print(
        record[
            "context"
        ]
    )


# ==========================================================================================
# 8. Print exact R3 encoder implementation
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT R3 LIVE ENCODER")
print("=" * 100)

if (
    "encode_r3_feature_row"
    in r3_objects_3a
):

    print(
        r3_objects_3a[
            "encode_r3_feature_row"
        ][
            "source"
        ]
    )


# ==========================================================================================
# 9. Print exact R3 policy engine
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT R3 LIVE POLICY ENGINE")
print("=" * 100)

if (
    "R3LivePolicyEngine"
    in r3_objects_3a
):

    print(
        r3_objects_3a[
            "R3LivePolicyEngine"
        ][
            "source"
        ]
    )


# ==========================================================================================
# 10. Print exact R3 battle-agent bridge
# ==========================================================================================

print("\n" + "=" * 100)
print("EXACT R3 LIVE BATTLE-AGENT BRIDGE")
print("=" * 100)

if (
    "R3LiveBattleAgent"
    in r3_objects_3a
):

    print(
        r3_objects_3a[
            "R3LiveBattleAgent"
        ][
            "source"
        ]
    )


# ==========================================================================================
# 11. Search for final Notebook 59 production variables
# ==========================================================================================

FINAL_VARIABLE_NAMES_3A = [
    "r3_live_model",
    "r3_live_feature_names",
    "r3_live_policy_engine",
    "r3_live_battle_agent",
]


final_variable_rows_3a = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue


    if isinstance(
        node,
        ast.Assign,
    ):

        targets = node.targets

    else:

        targets = [
            node.target
        ]


    assigned_names = []

    for target in targets:

        if isinstance(
            target,
            ast.Name,
        ):

            assigned_names.append(
                target.id
            )


    matched_names = [
        name
        for name in assigned_names
        if name in FINAL_VARIABLE_NAMES_3A
    ]


    if not matched_names:
        continue


    final_variable_rows_3a.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "variable":
                matched_names,

            "source":
                ast.get_source_segment(
                    source_3a,
                    node,
                ),
        }
    )


section3a_final_variables_df = pd.DataFrame(
    final_variable_rows_3a
)


print("\nFINAL NOTEBOOK 59 R3 VARIABLE CONSTRUCTION")
print("-" * 100)

display(
    section3a_final_variables_df
)


# ==========================================================================================
# 12. Save production-contract evidence
# ==========================================================================================

SECTION3A_OBJECT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section3a_r3_production_objects.csv"
)

SECTION3A_ASSIGNMENT_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section3a_r3_artifact_assignments.csv"
)

SECTION3A_MODEL_LINES_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section3a_r3_model_load_lines.csv"
)

SECTION3A_SOURCE_FILE = (
    NOTEBOOK60_REPORT_DIR
    / "section3a_exact_r3_production_source.txt"
)


section3a_object_inventory_df.to_csv(
    SECTION3A_OBJECT_FILE,
    index=False,
)

section3a_assignment_df.to_csv(
    SECTION3A_ASSIGNMENT_FILE,
    index=False,
)

section3a_model_load_lines_df.to_csv(
    SECTION3A_MODEL_LINES_FILE,
    index=False,
)


with open(
    SECTION3A_SOURCE_FILE,
    "w",
    encoding="utf-8",
) as file:

    for name in TARGET_R3_OBJECTS_3A:

        if name not in r3_objects_3a:
            continue

        file.write(
            "\n"
            + "=" * 100
            + "\n"
        )

        file.write(
            name
            + "\n"
        )

        file.write(
            "=" * 100
            + "\n\n"
        )

        file.write(
            r3_objects_3a[
                name
            ][
                "source"
            ]
        )

        file.write(
            "\n\n"
        )


# ==========================================================================================
# 13. Validation
# ==========================================================================================

section3a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 59 script exists",

            "passed":
                NOTEBOOK59_SCRIPT_3A.exists(),
        },

        {
            "validation":
                "R3 feature builder recovered",

            "passed":
                (
                    "build_legality_aware_feature_row"
                    in r3_objects_3a
                ),
        },

        {
            "validation":
                "R3 encoder recovered",

            "passed":
                (
                    "encode_r3_feature_row"
                    in r3_objects_3a
                ),
        },

        {
            "validation":
                "R3 policy engine recovered",

            "passed":
                (
                    "R3LivePolicyEngine"
                    in r3_objects_3a
                ),
        },

        {
            "validation":
                "R3 battle-agent bridge recovered",

            "passed":
                (
                    "R3LiveBattleAgent"
                    in r3_objects_3a
                ),
        },

        {
            "validation":
                "R3 model/artifact evidence found",

            "passed":
                len(
                    section3a_model_load_lines_df
                ) > 0,
        },

        {
            "validation":
                "production source evidence saved",

            "passed":
                SECTION3A_SOURCE_FILE.exists(),
        },
    ]
)


print("\nSECTION 3A VALIDATION")
print("-" * 100)

display(
    section3a_validation_df
)


if section3a_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print("✅ NOTEBOOK 59 PRODUCTION SCRIPT RECOVERED")
    print("✅ EXACT R3 FEATURE BUILDER RECOVERED")
    print("✅ EXACT 46-FEATURE R3 ENCODER RECOVERED")
    print("✅ EXACT R3 LIVE POLICY ENGINE RECOVERED")
    print("✅ EXACT R3 BATTLE-AGENT BRIDGE RECOVERED")
    print("✅ R3 MODEL / ARTIFACT LOAD EVIDENCE RECOVERED")
    print("✅ NO R3 MODEL EXECUTED OR MODIFIED")
    print("✅ SECTION 3A COMPLETE")

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print("⚠️ SECTION 3A NEEDS TARGETED R3 RECOVERY")
    print("⚠️ DO NOT LOAD OR BENCHMARK R3 YET")
    print("=" * 100)

====================================================================================================
SECTION 3A — RECOVER EXACT NOTEBOOK 59 R3 PRODUCTION CONTRACT
====================================================================================================

NOTEBOOK 59 PRODUCTION SCRIPT
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\59_live_competitive_evaluation.py

R3 PRODUCTION OBJECT INVENTORY
----------------------------------------------------------------------------------------------------

                    name object_type  line_number  recovered
0  encode_r3_feature_row    FUNCTION         3287       True
1     R3LivePolicyEngine       CLASS         6432       True
2      R3LiveBattleAgent       CLASS         7654       True

R3 OBJECT CHECK
----------------------------------------------------------------------------------------------------
Missing: ['build_legality_aware_feature_row']

R3-RELATED NOTEBOOK 59 ASSIGNMENTS
----------------------------------------------------------------------------------------------------

,line_number,assigned_names,source
0,107,[R3_MODEL_PATH],"R3_MODEL_PATH = (\n MODEL_55_DIR\n / ""se..."
1,133,[path_records],"path_records = [\n {\n ""resource"": ""..."
2,251,[r3_package],r3_package = joblib.load(\n R3_MODEL_PATH\n)
3,262,[r3_model],"r3_model = r3_package.get(\n ""model""\n)"
4,266,[r3_feature_names],"r3_feature_names = r3_package.get(\n ""retai..."
...,...,...,...
103,12716,[SIDE_EFFECT_PATH_59],SIDE_EFFECT_PATH_59 = (\n NOTEBOOK59_OUTPUT...
104,12721,[ACTION_USAGE_PATH_59],ACTION_USAGE_PATH_59 = (\n NOTEBOOK59_OUTPU...
105,12726,[SUMMARY_PATH_59],SUMMARY_PATH_59 = (\n NOTEBOOK59_OUTPUT_DIR...
106,12766,[final_metrics_59],"final_metrics_59 = {\n ""notebook"":\n ..."
107,12893,[final_validation_59],final_validation_59 = pd.DataFrame(\n [\n ...

R3 MODEL / ARTIFACT LOAD LINES
----------------------------------------------------------------------------------------------------

    line_number                             source_line
0           107                       R3_MODEL_PATH = (
1           151             "path": str(R3_MODEL_PATH),
2           152       "exists": R3_MODEL_PATH.exists(),
3           175           assert R3_MODEL_PATH.exists()
4           206  notebook58_results = pickle.load(file)
..          ...                                     ...
57        12901                           r3_live_model
58        12905               "RandomForestClassifier",
59        12909                           r3_live_model
60        12912               "RandomForestClassifier",
61        13106                           r3_live_model

[62 rows x 2 columns]

R3 LIVE MODEL CONSTRUCTION CONTEXT
----------------------------------------------------------------------------------------------------

====================================================================================================
CONTEXT 1 — AROUND LINE 1339
----------------------------------------------------------------------------------------------------
    f"{R3_MODEL_PATH}"
)

# ------------------------------------------------------------------------------------------
# Load R3 model package
# ------------------------------------------------------------------------------------------

r3_live_package = joblib.load(
    R3_MODEL_PATH
)

assert isinstance(
    r3_live_package,
    dict,
), (
    "Expected the approved R3 artifact "
    "to be a dictionary model package."
)

print("\nR3 PACKAGE KEYS")
print("-" * 100)

for key in r3_live_package.keys():
    print(key)

# ------------------------------------------------------------------------------------------
# Extract model and metadata
# ------------------------------------------------------------------------------------------

r3_live_model = r3_live_package.get(
    "model"
)

r3_live_feature_names = r3_live_package.get(
    "retained_feature_names"
)

r3_live_feature_indices = r3_live_package.get(
    "retained_feature_indices"
)

r3_live_strategy_id = r3_live_package.get(
    "strategy_id"
)

r3_live_training_results = r3_live_package.get(
    "training_results"
)

# ------------------------------------------------------------------------------------------
# Validate estimator
# ------------------------------------------------------------------------------------------

assert r3_live_model is not None, (
    "R3 package does not contain a model."
)

assert r3_live_feature_names is not None, (
    "R3 package does not contain retained_feature_names."
)

assert len(
    r3_live_feature_names
) == 46, (
    f"Expected 46 R3 features, "
    f"found {len(r3_live_feature_names)}."
)

model_feature_count = getattr(
    r3_live_model,

====================================================================================================
CONTEXT 2 — AROUND LINE 1363
----------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------
# Extract model and metadata
# ------------------------------------------------------------------------------------------

r3_live_model = r3_live_package.get(
    "model"
)

r3_live_feature_names = r3_live_package.get(
    "retained_feature_names"
)

r3_live_feature_indices = r3_live_package.get(
    "retained_feature_indices"
)

r3_live_strategy_id = r3_live_package.get(
    "strategy_id"
)

r3_live_training_results = r3_live_package.get(
    "training_results"
)

# ------------------------------------------------------------------------------------------
# Validate estimator
# ------------------------------------------------------------------------------------------

assert r3_live_model is not None, (
    "R3 package does not contain a model."
)

assert r3_live_feature_names is not None, (
    "R3 package does not contain retained_feature_names."
)

assert len(
    r3_live_feature_names
) == 46, (
    f"Expected 46 R3 features, "
    f"found {len(r3_live_feature_names)}."
)

model_feature_count = getattr(
    r3_live_model,
    "n_features_in_",
    None,
)

assert model_feature_count == 46, (
    f"R3 model expects {model_feature_count} features, "
    "not 46."
)

# ------------------------------------------------------------------------------------------
# Validate class structure
# ------------------------------------------------------------------------------------------

r3_live_classes = np.asarray(
    getattr(
        r3_live_model,
        "classes_",
        [],
    )
)

assert len(r3_live_classes) > 0, (
    "R3 estimator does not expose model classes."
)

====================================================================================================
CONTEXT 3 — AROUND LINE 1379
----------------------------------------------------------------------------------------------------

r3_live_strategy_id = r3_live_package.get(
    "strategy_id"
)

r3_live_training_results = r3_live_package.get(
    "training_results"
)

# ------------------------------------------------------------------------------------------
# Validate estimator
# ------------------------------------------------------------------------------------------

assert r3_live_model is not None, (
    "R3 package does not contain a model."
)

assert r3_live_feature_names is not None, (
    "R3 package does not contain retained_feature_names."
)

assert len(
    r3_live_feature_names
) == 46, (
    f"Expected 46 R3 features, "
    f"found {len(r3_live_feature_names)}."
)

model_feature_count = getattr(
    r3_live_model,
    "n_features_in_",
    None,
)

assert model_feature_count == 46, (
    f"R3 model expects {model_feature_count} features, "
    "not 46."
)

# ------------------------------------------------------------------------------------------
# Validate class structure
# ------------------------------------------------------------------------------------------

r3_live_classes = np.asarray(
    getattr(
        r3_live_model,
        "classes_",
        [],
    )
)

assert len(r3_live_classes) > 0, (
    "R3 estimator does not expose model classes."
)

# ------------------------------------------------------------------------------------------
# Build validation summary
# ------------------------------------------------------------------------------------------

section4a_r3_live_validation_df = pd.DataFrame(
    [
        {
            "strategy": (
                r3_live_strategy_id
                if r3_live_strategy_id is not None
                else "R3_STATE_CENTRIC_POLICY"
            ),
            "model_type": type(
                r3_live_model
            ).__name__,

====================================================================================================
CONTEXT 4 — AROUND LINE 1395
----------------------------------------------------------------------------------------------------

assert r3_live_feature_names is not None, (
    "R3 package does not contain retained_feature_names."
)

assert len(
    r3_live_feature_names
) == 46, (
    f"Expected 46 R3 features, "
    f"found {len(r3_live_feature_names)}."
)

model_feature_count = getattr(
    r3_live_model,
    "n_features_in_",
    None,
)

assert model_feature_count == 46, (
    f"R3 model expects {model_feature_count} features, "
    "not 46."
)

# ------------------------------------------------------------------------------------------
# Validate class structure
# ------------------------------------------------------------------------------------------

r3_live_classes = np.asarray(
    getattr(
        r3_live_model,
        "classes_",
        [],
    )
)

assert len(r3_live_classes) > 0, (
    "R3 estimator does not expose model classes."
)

# ------------------------------------------------------------------------------------------
# Build validation summary
# ------------------------------------------------------------------------------------------

section4a_r3_live_validation_df = pd.DataFrame(
    [
        {
            "strategy": (
                r3_live_strategy_id
                if r3_live_strategy_id is not None
                else "R3_STATE_CENTRIC_POLICY"
            ),
            "model_type": type(
                r3_live_model
            ).__name__,
            "model_path": str(
                R3_MODEL_PATH
            ),
            "model_exists": (
                R3_MODEL_PATH.exists()
            ),
            "retained_feature_count": len(
                r3_live_feature_names
            ),
            "model_n_features_in": (
                model_feature_count
            ),
            "class_count": len(
                r3_live_classes
            ),
            "classes": list(

====================================================================================================
CONTEXT 5 — AROUND LINE 1418
----------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------
# Validate class structure
# ------------------------------------------------------------------------------------------

r3_live_classes = np.asarray(
    getattr(
        r3_live_model,
        "classes_",
        [],
    )
)

assert len(r3_live_classes) > 0, (
    "R3 estimator does not expose model classes."
)

# ------------------------------------------------------------------------------------------
# Build validation summary
# ------------------------------------------------------------------------------------------

section4a_r3_live_validation_df = pd.DataFrame(
    [
        {
            "strategy": (
                r3_live_strategy_id
                if r3_live_strategy_id is not None
                else "R3_STATE_CENTRIC_POLICY"
            ),
            "model_type": type(
                r3_live_model
            ).__name__,
            "model_path": str(
                R3_MODEL_PATH
            ),
            "model_exists": (
                R3_MODEL_PATH.exists()
            ),
            "retained_feature_count": len(
                r3_live_feature_names
            ),
            "model_n_features_in": (
                model_feature_count
            ),
            "class_count": len(
                r3_live_classes
            ),
            "classes": list(
                r3_live_classes
            ),
            "training_results_available": (
                isinstance(
                    r3_live_training_results,
                    dict,
                )
            ),
        }
    ]
)

print("\nR3 LIVE POLICY VALIDATION")
print("-" * 100)

display(
    section4a_r3_live_validation_df
)

# ------------------------------------------------------------------------------------------
# Display retained feature order
# ------------------------------------------------------------------------------------------


====================================================================================================
CONTEXT 6 — AROUND LINE 3516
----------------------------------------------------------------------------------------------------
            },

            {
                "contract":
                    "R3 categorical indicators",

                "value":
                    len(
                        R3_CATEGORICAL_FEATURES
                    ),

                "expected":
                    27,

                "passed":
                    (
                        len(
                            R3_CATEGORICAL_FEATURES
                        )
                        == 27
                    ),
            },

            {
                "contract":
                    "R3 model input features",

                "value":
                    int(
                        r3_live_model
                        .n_features_in_
                    ),

                "expected":
                    46,

                "passed":
                    (
                        int(
                            r3_live_model
                            .n_features_in_
                        )
                        == 46
                    ),
            },
        ]
    )
)

print("\nR3 LIVE ENCODER CONTRACT")
print("-" * 100)

display(
    section6b_encoder_contract_df
)

assert section6b_encoder_contract_df[
    "passed"
].all()

print("\nNUMERIC RAW INPUTS")
print("-" * 100)

for column_name in (
    numeric_raw_columns
):
    print(column_name)

print("\nCATEGORICAL RAW INPUTS")
print("-" * 100)

====================================================================================================
CONTEXT 7 — AROUND LINE 3526
----------------------------------------------------------------------------------------------------

                "expected":
                    27,

                "passed":
                    (
                        len(
                            R3_CATEGORICAL_FEATURES
                        )
                        == 27
                    ),
            },

            {
                "contract":
                    "R3 model input features",

                "value":
                    int(
                        r3_live_model
                        .n_features_in_
                    ),

                "expected":
                    46,

                "passed":
                    (
                        int(
                            r3_live_model
                            .n_features_in_
                        )
                        == 46
                    ),
            },
        ]
    )
)

print("\nR3 LIVE ENCODER CONTRACT")
print("-" * 100)

display(
    section6b_encoder_contract_df
)

assert section6b_encoder_contract_df[
    "passed"
].all()

print("\nNUMERIC RAW INPUTS")
print("-" * 100)

for column_name in (
    numeric_raw_columns
):
    print(column_name)

print("\nCATEGORICAL RAW INPUTS")
print("-" * 100)

for column_name in (
    categorical_source_columns
):
    print(column_name)

print(
    "\n✅ EXACT 46-FEATURE R3 ENCODER CREATED"
)


====================================================================================================
CONTEXT 8 — AROUND LINE 3609
----------------------------------------------------------------------------------------------------
    "✅ NO MODEL OR ARTIFACT MODIFICATION PERFORMED"
)

print(
    "✅ SECTION 6B COMPLETE"
)


# In[80]:


# ==========================================================================================
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)


====================================================================================================
CONTEXT 9 — AROUND LINE 3763
----------------------------------------------------------------------------------------------------
)

assert np.isfinite(
    section6c_r3_matrix
).all(), (
    "R3 feature matrix contains NaN or infinite values."
)

print("\nR3 ENCODED MATRIX")
print("-" * 100)

print(
    "Shape :",
    section6c_r3_matrix.shape,
)

section6c_encoded_df = pd.DataFrame(
    section6c_r3_matrix,
    columns=r3_live_feature_names,
)

display(section6c_encoded_df)


# ------------------------------------------------------------------------------------------
# 5. Execute live R3 model prediction
# ------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------
# 6. Execute and validate probability vector
# ------------------------------------------------------------------------------------------

assert hasattr(
    r3_live_model,
    "predict_proba",
), (
    "R3 model does not expose predict_proba()."
)

section6c_probabilities = (
    r3_live_model.predict_proba(
        section6c_r3_matrix
    )
)

assert section6c_probabilities.ndim == 2
assert section6c_probabilities.shape[0] == 1

====================================================================================================
CONTEXT 10 — AROUND LINE 3790
----------------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------
# 6. Execute and validate probability vector
# ------------------------------------------------------------------------------------------

assert hasattr(
    r3_live_model,
    "predict_proba",
), (
    "R3 model does not expose predict_proba()."
)

section6c_probabilities = (
    r3_live_model.predict_proba(
        section6c_r3_matrix
    )
)

assert section6c_probabilities.ndim == 2
assert section6c_probabilities.shape[0] == 1

section6c_probability_vector = (
    section6c_probabilities[0]
)

section6c_classes = list(
    r3_live_model.classes_
)

assert (
    len(section6c_probability_vector)
    ==
    len(section6c_classes)
), (
    "Probability vector length does not match "
    "R3 class count."
)

assert np.isfinite(
    section6c_probability_vector
).all()

assert np.isclose(
    float(
        np.sum(
            section6c_probability_vector
        )

====================================================================================================
EXACT R3 LIVE ENCODER
====================================================================================================
def encode_r3_feature_row(
    raw_feature_dataframe,
):
    """
    Convert the 1x41 raw production feature dataframe
    into the exact 1x46 feature matrix expected by R3.

    This intentionally reconstructs ONLY the retained
    R3 features and does not recreate discarded features.
    """

    assert isinstance(
        raw_feature_dataframe,
        pd.DataFrame,
    )

    assert len(
        raw_feature_dataframe
    ) == 1, (
        "R3 live encoder expects exactly one raw row."
    )

    raw_row = (
        raw_feature_dataframe
        .iloc[0]
    )

    encoded_values = {}

    # ------------------------------------------------------------------
    # Numeric columns
    # ------------------------------------------------------------------

    for encoded_name in (
        R3_NUMERIC_FEATURES
    ):

        raw_column = encoded_name[
            len("numeric__"):
        ]

        assert raw_column in raw_row.index, (
            f"Required numeric raw feature missing: "
            f"{raw_column}"
        )


,line_number,variable,source
0,1339,[r3_live_model],"r3_live_model = r3_live_package.get(\n ""mod..."
1,1343,[r3_live_feature_names],r3_live_feature_names = r3_live_package.get(\n...
2,6861,[r3_live_policy_engine],r3_live_policy_engine = (\n R3LivePolicyEng...
3,7788,[r3_live_battle_agent],r3_live_battle_agent = (\n R3LiveBattleAgen...

SECTION 3A VALIDATION
----------------------------------------------------------------------------------------------------

                         validation  passed
0         Notebook 59 script exists    True
1      R3 feature builder recovered   False
2              R3 encoder recovered    True
3        R3 policy engine recovered    True
4  R3 battle-agent bridge recovered    True
5  R3 model/artifact evidence found    True
6  production source evidence saved    True

====================================================================================================
⚠️ SECTION 3A NEEDS TARGETED R3 RECOVERY
⚠️ DO NOT LOAD OR BENCHMARK R3 YET
====================================================================================================

In [24]:
# ==========================================================================================
# SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row")
print("=" * 100)

import ast
import re
import pandas as pd


# ==========================================================================================
# 1. Confirm Notebook 59 source is available
# ==========================================================================================

assert "source_3a" in globals(), (
    "source_3a is missing. Run Section 3A first."
)

assert "tree_3a" in globals(), (
    "tree_3a is missing. Run Section 3A first."
)

TARGET_NAME_3A1 = (
    "build_legality_aware_feature_row"
)


# ==========================================================================================
# 2. Find EVERY textual occurrence
# ==========================================================================================

source_lines_3a1 = (
    source_3a.splitlines()
)

occurrence_rows_3a1 = []


for line_number, line in enumerate(
    source_lines_3a1,
    start=1,
):

    if TARGET_NAME_3A1 in line:

        occurrence_rows_3a1.append(
            {
                "line_number":
                    line_number,

                "source_line":
                    line.strip(),
            }
        )


section3a1_occurrences_df = pd.DataFrame(
    occurrence_rows_3a1
)


print("\nALL TEXTUAL OCCURRENCES")
print("-" * 100)

display(
    section3a1_occurrences_df
)


# ==========================================================================================
# 3. Print generous context around every occurrence
# ==========================================================================================

print("\nSOURCE CONTEXT AROUND OCCURRENCES")
print("-" * 100)


for index, row in enumerate(
    occurrence_rows_3a1,
    start=1,
):

    line_number = int(
        row[
            "line_number"
        ]
    )

    start_index = max(
        0,
        line_number - 80,
    )

    end_index = min(
        len(source_lines_3a1),
        line_number + 120,
    )

    print("\n" + "=" * 100)

    print(
        f"OCCURRENCE {index} "
        f"— AROUND LINE {line_number}"
    )

    print("-" * 100)

    print(
        "\n".join(
            source_lines_3a1[
                start_index:
                end_index
            ]
        )
    )


# ==========================================================================================
# 4. Inspect all AST definitions with related names
# ==========================================================================================

related_definition_rows_3a1 = []


for node in ast.walk(
    tree_3a
):

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        continue

    node_name = getattr(
        node,
        "name",
        "",
    )

    name_lower = (
        node_name.lower()
    )

    if any(
        token in name_lower
        for token in [
            "feature",
            "legal",
            "row",
            "battle",
            "state",
        ]
    ):

        related_definition_rows_3a1.append(
            {
                "name":
                    node_name,

                "object_type":
                    (
                        "CLASS"
                        if isinstance(
                            node,
                            ast.ClassDef,
                        )
                        else
                        "FUNCTION"
                    ),

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),
            }
        )


section3a1_related_definitions_df = (
    pd.DataFrame(
        related_definition_rows_3a1
    )
    .sort_values(
        "line_number"
    )
    .reset_index(
        drop=True
    )
)


print("\nRELATED FUNCTION / CLASS DEFINITIONS")
print("-" * 100)

display(
    section3a1_related_definitions_df
)


# ==========================================================================================
# 5. Search assignments involving target function
# ==========================================================================================

assignment_hits_3a1 = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    node_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not node_source:
        continue

    if TARGET_NAME_3A1 not in node_source:
        continue

    assignment_hits_3a1.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "source":
                node_source,
        }
    )


section3a1_assignments_df = pd.DataFrame(
    assignment_hits_3a1
)


print("\nTARGET-RELATED ASSIGNMENTS")
print("-" * 100)

if len(
    section3a1_assignments_df
) > 0:

    display(
        section3a1_assignments_df
    )

else:

    print(
        "No top-level assignment found."
    )


# ==========================================================================================
# 6. Search imports that may supply feature-builder dependencies
# ==========================================================================================

import_hits_3a1 = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        continue

    import_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not import_source:
        continue

    import_lower = (
        import_source.lower()
    )

    if any(
        token in import_lower
        for token in [
            "feature",
            "observation",
            "competitive",
            "dataset",
            "policy",
        ]
    ):

        import_hits_3a1.append(
            {
                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "source":
                    import_source,
            }
        )


section3a1_imports_df = pd.DataFrame(
    import_hits_3a1
)


print("\nPOTENTIALLY RELEVANT IMPORTS")
print("-" * 100)

display(
    section3a1_imports_df
)


# ==========================================================================================
# 7. Search for functions producing the expected 41-column contract
# ==========================================================================================

contract_hits_3a1 = []


SEARCH_TERMS_3A1 = [
    "41",
    "recomputed_legal_move_count",
    "legal_move_signature",
    "battle_phase",
    "energy_band",
    "damage_band",
]


for node in ast.walk(
    tree_3a
):

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
        ),
    ):
        continue

    node_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not node_source:
        continue

    matched_terms = [
        term
        for term in SEARCH_TERMS_3A1
        if term in node_source
    ]

    if not matched_terms:
        continue

    contract_hits_3a1.append(
        {
            "function":
                node.name,

            "line_number":
                node.lineno,

            "matched_terms":
                matched_terms,

            "match_count":
                len(
                    matched_terms
                ),
        }
    )


section3a1_contract_candidates_df = (
    pd.DataFrame(
        contract_hits_3a1
    )
)


if not section3a1_contract_candidates_df.empty:

    section3a1_contract_candidates_df = (
        section3a1_contract_candidates_df
        .sort_values(
            [
                "match_count",
                "line_number",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )


print("\n41-COLUMN FEATURE-BUILDER CANDIDATES")
print("-" * 100)

display(
    section3a1_contract_candidates_df
)


# ==========================================================================================
# 8. Print strongest candidate source(s)
# ==========================================================================================

print("\nSTRONGEST FEATURE-BUILDER CANDIDATE SOURCES")
print("-" * 100)


if not section3a1_contract_candidates_df.empty:

    max_match_count_3a1 = int(
        section3a1_contract_candidates_df[
            "match_count"
        ].max()
    )

    strongest_names_3a1 = (
        section3a1_contract_candidates_df.loc[
            section3a1_contract_candidates_df[
                "match_count"
            ]
            ==
            max_match_count_3a1,
            "function",
        ]
        .tolist()
    )


    for candidate_name in (
        strongest_names_3a1
    ):

        for node in ast.walk(
            tree_3a
        ):

            if not isinstance(
                node,
                (
                    ast.FunctionDef,
                    ast.AsyncFunctionDef,
                ),
            ):
                continue

            if (
                node.name
                !=
                candidate_name
            ):
                continue

            candidate_source = (
                ast.get_source_segment(
                    source_3a,
                    node,
                )
            )

            print(
                "\n"
                + "=" * 100
            )

            print(
                f"CANDIDATE: "
                f"{candidate_name} "
                f"(line {node.lineno})"
            )

            print(
                "=" * 100
            )

            print(
                candidate_source
            )

else:

    strongest_names_3a1 = []

    print(
        "No function candidate identified."
    )


# ==========================================================================================
# 9. Determine recovery status — diagnostic only
# ==========================================================================================

exact_definition_found_3a1 = any(
    (
        isinstance(
            node,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        )
        and
        getattr(
            node,
            "name",
            None,
        )
        ==
        TARGET_NAME_3A1
    )
    for node in ast.walk(
        tree_3a
    )
)


target_assignment_found_3a1 = (
    len(
        assignment_hits_3a1
    )
    > 0
)


strong_candidate_found_3a1 = (
    len(
        strongest_names_3a1
    )
    > 0
)


section3a1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "target referenced in Notebook 59",

            "observed":
                len(
                    occurrence_rows_3a1
                ),

            "passed":
                len(
                    occurrence_rows_3a1
                )
                > 0,
        },

        {
            "validation":
                "exact AST function definition found",

            "observed":
                exact_definition_found_3a1,

            "passed":
                exact_definition_found_3a1,
        },

        {
            "validation":
                "target assignment found",

            "observed":
                target_assignment_found_3a1,

            "passed":
                target_assignment_found_3a1,
        },

        {
            "validation":
                "41-column builder candidate found",

            "observed":
                strongest_names_3a1,

            "passed":
                strong_candidate_found_3a1,
        },
    ]
)


print("\nSECTION 3A.1 DIAGNOSTIC SUMMARY")
print("-" * 100)

display(
    section3a1_validation_df
)


print("\n" + "=" * 100)

print(
    "✅ TARGETED SEARCH COMPLETE"
)

print(
    "⚠️ THIS CELL DOES NOT MODIFY OR LOAD THE R3 MODEL"
)

print(
    "⚠️ DO NOT BENCHMARK YET"
)

print("=" * 100)

====================================================================================================
SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row
====================================================================================================

ALL TEXTUAL OCCURRENCES
----------------------------------------------------------------------------------------------------

    line_number                                        source_line
0          3607                "build_legality_aware_feature_row",
1          3665  # build_legality_aware_feature_row requires BOTH:
2          3671                  build_legality_aware_feature_row(
3          4014  target_function_name = "build_legality_aware_f...
4          4054  "Could not locate build_legality_aware_feature...
5          4072                 "build_legality_aware_feature_row"
6          4077                   build_legality_aware_feature_row
7          4080  print("\n✅ build_legality_aware_feature_row() ...
8          4120  TARGET_FUNCTION = "build_legality_aware_featur...
9          4169  "Could not recover build_legality_aware_featur...
10         4207  print("\n✅ build_legality_aware_feature_row() ...
11         4217    "build_legality_aware_feature_row" in globals()
12         4273  print("\nCalling build_legality_aware_feature_...
13         4276                  build_legality_aware_feature_row(
14         4327     "Expected build_legality_aware_feature_row() "
15         4783  TARGET_FUNCTION = "build_legality_aware_featur...
16         4936                   build_legality_aware_feature_row
17         4941    "✅ build_legality_aware_feature_row() RELOADED"
18         5048  TARGET_FUNCTION = "build_legality_aware_featur...
19         5266                "build_legality_aware_feature_row",
20         5288                   build_legality_aware_feature_row
21         5985                "build_legality_aware_feature_row",
22         6009                   build_legality_aware_feature_row
23         6211  build_legality_aware_feature_row.__globals__.u...
24         6383                "build_legality_aware_feature_row",
25         6403                   build_legality_aware_feature_row
26         6518                  build_legality_aware_feature_row(

SOURCE CONTEXT AROUND OCCURRENCES
----------------------------------------------------------------------------------------------------

====================================================================================================
OCCURRENCE 1 — AROUND LINE 3607
----------------------------------------------------------------------------------------------------
                        )
                        == 46
                    ),
            },
        ]
    )
)

print("\nR3 LIVE ENCODER CONTRACT")
print("-" * 100)

display(
    section6b_encoder_contract_df
)

assert section6b_encoder_contract_df[
    "passed"
].all()

print("\nNUMERIC RAW INPUTS")
print("-" * 100)

for column_name in (
    numeric_raw_columns
):
    print(column_name)

print("\nCATEGORICAL RAW INPUTS")
print("-" * 100)

for column_name in (
    categorical_source_columns
):
    print(column_name)

print(
    "\n✅ EXACT 46-FEATURE R3 ENCODER CREATED"
)

print(
    "✅ NUMERIC FEATURE MAPPING VERIFIED"
)

print(
    "✅ CATEGORICAL ONE-HOT MAPPING VERIFIED"
)

print(
    "✅ FROZEN PREPROCESSOR VERSION CONFLICT BYPASSED SAFELY"
)

print(
    "✅ NO MODEL OR ARTIFACT MODIFICATION PERFORMED"
)

print(
    "✅ SECTION 6B COMPLETE"
)


# In[80]:


# ==========================================================================================
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "

====================================================================================================
OCCURRENCE 2 — AROUND LINE 3665
----------------------------------------------------------------------------------------------------


# In[80]:


# ==========================================================================================
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "
    f"{section6c_r3_matrix.shape}; "
    "expected (1, 46)."
)

assert len(r3_live_feature_names) == 46, (
    "R3 live feature-name contract is not 46 features."
)

assert np.isfinite(
    section6c_r3_matrix
).all(), (
    "R3 feature matrix contains NaN or infinite values."
)

print("\nR3 ENCODED MATRIX")
print("-" * 100)

print(
    "Shape :",
    section6c_r3_matrix.shape,
)

section6c_encoded_df = pd.DataFrame(
    section6c_r3_matrix,
    columns=r3_live_feature_names,
)

display(section6c_encoded_df)


# ------------------------------------------------------------------------------------------
# 5. Execute live R3 model prediction
# ------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------

====================================================================================================
OCCURRENCE 3 — AROUND LINE 3671
----------------------------------------------------------------------------------------------------
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "
    f"{section6c_r3_matrix.shape}; "
    "expected (1, 46)."
)

assert len(r3_live_feature_names) == 46, (
    "R3 live feature-name contract is not 46 features."
)

assert np.isfinite(
    section6c_r3_matrix
).all(), (
    "R3 feature matrix contains NaN or infinite values."
)

print("\nR3 ENCODED MATRIX")
print("-" * 100)

print(
    "Shape :",
    section6c_r3_matrix.shape,
)

section6c_encoded_df = pd.DataFrame(
    section6c_r3_matrix,
    columns=r3_live_feature_names,
)

display(section6c_encoded_df)


# ------------------------------------------------------------------------------------------
# 5. Execute live R3 model prediction
# ------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------
# 6. Execute and validate probability vector
# ------------------------------------------------------------------------------------------

assert hasattr(
    r3_live_model,
    "predict_proba",

====================================================================================================
OCCURRENCE 4 — AROUND LINE 4014
----------------------------------------------------------------------------------------------------
            "validation":
                "probability_sum",

            "observed":
                float(
                    np.sum(
                        section6c_probability_vector
                    )
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    float(
                        np.sum(
                            section6c_probability_vector
                        )
                    ),
                    1.0,
                    atol=1e-9,
                ),
        },
    ]
)

print("\nEND-TO-END R3 LIVE INFERENCE VALIDATION")
print("-" * 100)

display(
    section6c_validation_df
)

assert section6c_validation_df[
    "passed"
].all()


# ------------------------------------------------------------------------------------------
# 8. Completion
# ------------------------------------------------------------------------------------------

print("\n" + "=" * 100)

print("✅ RAW LIVE FEATURE ROW BUILT")
print("✅ EXACT 41-COLUMN RAW FEATURE CONTRACT VERIFIED")
print("✅ EXACT 46-FEATURE R3 MATRIX CREATED")
print("✅ R3 PREDICTION EXECUTED")
print("✅ R3 PROBABILITY VECTOR VALIDATED")
print("✅ END-TO-END INFERENCE PATH CONFIRMED")
print("✅ SECTION 6C COMPLETE")

print("=" * 100)


# In[73]:


# ==========================================================================================
# SECTION 6C.1 — LOAD EXISTING LEGALITY-AWARE FEATURE BUILDER
# ==========================================================================================

print("=" * 100)
print("SECTION 6C.1 — LOAD EXISTING LEGALITY-AWARE FEATURE BUILDER")
print("=" * 100)

import ast
from pathlib import Path

# ------------------------------------------------------------------------------------------
# Search known Notebook 54/55 scripts for the exact function definition
# ------------------------------------------------------------------------------------------

candidate_scripts = [
    PROJECT_ROOT / "scripts" / "54_tournament_strength_optimization_clean.py",
    PROJECT_ROOT / "scripts" / "55_controlled_feature_ablation_retraining_clean.py",
]

target_function_name = "build_legality_aware_feature_row"

resolved_function_source = None
resolved_function_script = None

for script_path in candidate_scripts:

    if not script_path.exists():
        continue

    source = script_path.read_text(
        encoding="utf-8",
        errors="ignore",
    )

    try:
        tree = ast.parse(source)
    except SyntaxError:
        continue

    for node in tree.body:

        if (
            isinstance(node, ast.FunctionDef)
            and node.name == target_function_name
        ):

            resolved_function_source = ast.get_source_segment(
                source,
                node,
            )

            resolved_function_script = script_path

            break

    if resolved_function_source is not None:
        break

assert resolved_function_source is not None, (
    "Could not locate build_legality_aware_feature_row()."
)

print("\nFUNCTION SOURCE LOCATED IN")
print("-" * 100)

print(resolved_function_script)

# ------------------------------------------------------------------------------------------
# Execute ONLY the recovered function definition in Notebook 59
# ------------------------------------------------------------------------------------------

exec(
    resolved_function_source,
    globals(),
)

assert (
    "build_legality_aware_feature_row"
    in globals()
)

assert callable(
    build_legality_aware_feature_row
)

print("\n✅ build_legality_aware_feature_row() LOADED")
print("✅ FUNCTION IS CALLABLE")
print("✅ SECTION 6C.1 COMPLETE")


# In[38]:


# ==========================================================================================
# SECTION 6C.1A — LOAD FUNCTION DEPENDENCIES
# ==========================================================================================

from typing import Any, Sequence
import numpy as np
import pandas as pd

print("✅ Any loaded")
print("✅ Sequence loaded")
print("✅ numpy loaded")
print("✅ pandas loaded")
print("✅ SECTION 6C.1A COMPLETE")


# In[40]:


# ==========================================================================================
# SECTION 6C.1B — FORCE-LOAD LEGALITY-AWARE FEATURE BUILDER SAFELY
# ==========================================================================================

print("=" * 100)
print("SECTION 6C.1B — FORCE-LOAD LEGALITY-AWARE FEATURE BUILDER SAFELY")
print("=" * 100)

import ast
from pathlib import Path
from typing import Any, Sequence
import numpy as np
import pandas as pd

TARGET_FUNCTION = "build_legality_aware_feature_row"

candidate_scripts = [
    PROJECT_ROOT
    / "scripts"
    / "54_tournament_strength_optimization_clean.py",

    PROJECT_ROOT
    / "scripts"
    / "55_controlled_feature_ablation_retraining_clean.py",
]

function_source = None
function_file = None


====================================================================================================
OCCURRENCE 5 — AROUND LINE 4054
----------------------------------------------------------------------------------------------------
# 8. Completion

                           name object_type  line_number
0  parse_r3_categorical_feature    FUNCTION         3193
1         encode_r3_feature_row    FUNCTION         3287
2             R3LiveBattleAgent       CLASS         7654
3          R3LoggingBattleAgent       CLASS        10179
4      build_r3_battle_state_8a    FUNCTION        10757
5              run_r3_battle_8a    FUNCTION        10831

TARGET-RELATED ASSIGNMENTS
----------------------------------------------------------------------------------------------------

   line_number                                             source
0         3606  required_objects_6c = [\n    "build_legality_a...
1         3670  section6c_raw_feature_row = (\n    build_legal...
2         4014  target_function_name = "build_legality_aware_f...
3         4120  TARGET_FUNCTION = "build_legality_aware_featur...
4         4275  section6c2_raw_row = (\n    build_legality_awa...
5         4783  TARGET_FUNCTION = "build_legality_aware_featur...
6         5048  TARGET_FUNCTION = "build_legality_aware_featur...
7         5258  key_dependencies = [\n    "get_state_value",\n...
8         5984  critical_dependencies_6c2l = [\n    "build_leg...
9         6382  required_dependencies_6d = [\n    "build_legal...

POTENTIALLY RELEVANT IMPORTS
----------------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: []

41-COLUMN FEATURE-BUILDER CANDIDATES
----------------------------------------------------------------------------------------------------

                function  line_number matched_terms  match_count
0  encode_r3_feature_row         3287          [41]            1
1     build_model_matrix         6497          [41]            1

STRONGEST FEATURE-BUILDER CANDIDATE SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
CANDIDATE: encode_r3_feature_row (line 3287)
====================================================================================================
def encode_r3_feature_row(
    raw_feature_dataframe,
):
    """
    Convert the 1x41 raw production feature dataframe
    into the exact 1x46 feature matrix expected by R3.

    This intentionally reconstructs ONLY the retained
    R3 features and does not recreate discarded features.
    """

    assert isinstance(
        raw_feature_dataframe,
        pd.DataFrame,
    )

    assert len(
        raw_feature_dataframe
    ) == 1, (
        "R3 live encoder expects exactly one raw row."
    )

    raw_row = (
        raw_feature_dataframe
        .iloc[0]
    )

    encoded_values = {}

    # ------------------------------------------------------------------
    # Numeric columns
    # ------------------------------------------------------------------

    for encoded_name in (
        R3_NUMERIC_FEATURES
    ):

        raw_column = encoded_name[
            len("numeric__"):
        ]

        assert raw_column in raw_row.index, (
            f"Required numeric raw feature missing: "
            f"{raw_column}"
        )

        numeric_value = pd.to_numeric(
            raw_row[
                raw_column
            ],
            errors="coerce",
        )

        if pd.isna(
            numeric_value
        ):
            numeric_value = 0.0

        encoded_values[
            encoded_name
        ] = float(
            numeric_value
        )

    # ------------------------------------------------------------------
    # Categorical one-hot columns
    # ------------------------------------------------------------------

    for encoded_name in (
        R3_CATEGORICAL_FEATURES
    ):

        (
            source_column,
            category_value,
        ) = parse_r3_categorical_feature(
            encoded_name
        )

        assert source_column in raw_row.index, (
            f"Required categorical raw feature missing: "
            f"{source_column}"
        )

        actual_value = str(
            raw_row[
                source_column
            ]
        )

        encoded_values[
            encoded_name
        ] = float(
            actual_value
            ==
            category_value
        )

    # ------------------------------------------------------------------
    # Freeze exact R3 order
    # ------------------------------------------------------------------

    encoded_dataframe = pd.DataFrame(
        [
            encoded_values
        ],
        columns=
            R3_ENCODED_FEATURE_NAMES,
        dtype=float,
    )

    assert encoded_dataframe.shape == (
        1,
        46,
    ), (
        "Unexpected R3 encoded matrix shape: "
        f"{encoded_dataframe.shape}"
    )

    assert list(
        encoded_dataframe.columns
    ) == R3_ENCODED_FEATURE_NAMES

    assert np.isfinite(
        encoded_dataframe.to_numpy(
            dtype=float
        )
    ).all()

    return encoded_dataframe

====================================================================================================
CANDIDATE: build_model_matrix (line 6497)
====================================================================================================
def build_model_matrix(
        self,
        battle_state: Any,
        legal_moves: Sequence[Any],
    ) -> pd.DataFrame:

        legal_moves = list(
            legal_moves
        )

        if not legal_moves:

            raise ValueError(
                "At least one legal move is required."
            )

        # --------------------------------------------------------------
        # 41-column production raw feature row
        # --------------------------------------------------------------

        raw_feature_row = (
            build_legality_aware_feature_row(
                battle_state,
                legal_moves,
            )
        )

        assert isinstance(
            raw_feature_row,
            pd.DataFrame,
        )

        assert raw_feature_row.shape == (
            1,
            41,
        ), (
            "Unexpected raw feature shape: "
            f"{raw_feature_row.shape}; "
            "expected (1, 41)."
        )

        # --------------------------------------------------------------
        # Exact 46-column R3 matrix
        # --------------------------------------------------------------

        encoded_feature_row = (
            encode_r3_feature_row(
                raw_feature_row
            )
        )

        assert isinstance(
            encoded_feature_row,
            pd.DataFrame,
        )

        assert encoded_feature_row.shape == (
            1,
            46,
        ), (
            "Unexpected R3 feature shape: "
            f"{encoded_feature_row.shape}; "
            "expected (1, 46)."
        )

        assert list(
            encoded_feature_row.columns
        ) == self.retained_feature_names, (
            "R3 encoded feature order does not match "
            "the frozen retained-feature contract."
        )

        assert np.isfinite(
            encoded_feature_row.to_numpy(
                dtype=float
            )
        ).all(), (
            "R3 feature matrix contains non-finite values."
        )

        return encoded_feature_row

SECTION 3A.1 DIAGNOSTIC SUMMARY
----------------------------------------------------------------------------------------------------

,validation,observed,passed
0,target referenced in Notebook 59,27,True
1,exact AST function definition found,False,False
2,target assignment found,True,True
3,41-column builder candidate found,"[encode_r3_feature_row, build_model_matrix]",True

====================================================================================================
✅ TARGETED SEARCH COMPLETE
⚠️ THIS CELL DOES NOT MODIFY OR LOAD THE R3 MODEL
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [23]:
# ==========================================================================================
# SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row")
print("=" * 100)

import ast
import re
import pandas as pd


# ==========================================================================================
# 1. Confirm Notebook 59 source is available
# ==========================================================================================

assert "source_3a" in globals(), (
    "source_3a is missing. Run Section 3A first."
)

assert "tree_3a" in globals(), (
    "tree_3a is missing. Run Section 3A first."
)

TARGET_NAME_3A1 = (
    "build_legality_aware_feature_row"
)


# ==========================================================================================
# 2. Find EVERY textual occurrence
# ==========================================================================================

source_lines_3a1 = (
    source_3a.splitlines()
)

occurrence_rows_3a1 = []


for line_number, line in enumerate(
    source_lines_3a1,
    start=1,
):

    if TARGET_NAME_3A1 in line:

        occurrence_rows_3a1.append(
            {
                "line_number":
                    line_number,

                "source_line":
                    line.strip(),
            }
        )


section3a1_occurrences_df = pd.DataFrame(
    occurrence_rows_3a1
)


print("\nALL TEXTUAL OCCURRENCES")
print("-" * 100)

display(
    section3a1_occurrences_df
)


# ==========================================================================================
# 3. Print generous context around every occurrence
# ==========================================================================================

print("\nSOURCE CONTEXT AROUND OCCURRENCES")
print("-" * 100)


for index, row in enumerate(
    occurrence_rows_3a1,
    start=1,
):

    line_number = int(
        row[
            "line_number"
        ]
    )

    start_index = max(
        0,
        line_number - 80,
    )

    end_index = min(
        len(source_lines_3a1),
        line_number + 120,
    )

    print("\n" + "=" * 100)

    print(
        f"OCCURRENCE {index} "
        f"— AROUND LINE {line_number}"
    )

    print("-" * 100)

    print(
        "\n".join(
            source_lines_3a1[
                start_index:
                end_index
            ]
        )
    )


# ==========================================================================================
# 4. Inspect all AST definitions with related names
# ==========================================================================================

related_definition_rows_3a1 = []


for node in ast.walk(
    tree_3a
):

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        continue

    node_name = getattr(
        node,
        "name",
        "",
    )

    name_lower = (
        node_name.lower()
    )

    if any(
        token in name_lower
        for token in [
            "feature",
            "legal",
            "row",
            "battle",
            "state",
        ]
    ):

        related_definition_rows_3a1.append(
            {
                "name":
                    node_name,

                "object_type":
                    (
                        "CLASS"
                        if isinstance(
                            node,
                            ast.ClassDef,
                        )
                        else
                        "FUNCTION"
                    ),

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),
            }
        )


section3a1_related_definitions_df = (
    pd.DataFrame(
        related_definition_rows_3a1
    )
    .sort_values(
        "line_number"
    )
    .reset_index(
        drop=True
    )
)


print("\nRELATED FUNCTION / CLASS DEFINITIONS")
print("-" * 100)

display(
    section3a1_related_definitions_df
)


# ==========================================================================================
# 5. Search assignments involving target function
# ==========================================================================================

assignment_hits_3a1 = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    node_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not node_source:
        continue

    if TARGET_NAME_3A1 not in node_source:
        continue

    assignment_hits_3a1.append(
        {
            "line_number":
                getattr(
                    node,
                    "lineno",
                    None,
                ),

            "source":
                node_source,
        }
    )


section3a1_assignments_df = pd.DataFrame(
    assignment_hits_3a1
)


print("\nTARGET-RELATED ASSIGNMENTS")
print("-" * 100)

if len(
    section3a1_assignments_df
) > 0:

    display(
        section3a1_assignments_df
    )

else:

    print(
        "No top-level assignment found."
    )


# ==========================================================================================
# 6. Search imports that may supply feature-builder dependencies
# ==========================================================================================

import_hits_3a1 = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        continue

    import_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not import_source:
        continue

    import_lower = (
        import_source.lower()
    )

    if any(
        token in import_lower
        for token in [
            "feature",
            "observation",
            "competitive",
            "dataset",
            "policy",
        ]
    ):

        import_hits_3a1.append(
            {
                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "source":
                    import_source,
            }
        )


section3a1_imports_df = pd.DataFrame(
    import_hits_3a1
)


print("\nPOTENTIALLY RELEVANT IMPORTS")
print("-" * 100)

display(
    section3a1_imports_df
)


# ==========================================================================================
# 7. Search for functions producing the expected 41-column contract
# ==========================================================================================

contract_hits_3a1 = []


SEARCH_TERMS_3A1 = [
    "41",
    "recomputed_legal_move_count",
    "legal_move_signature",
    "battle_phase",
    "energy_band",
    "damage_band",
]


for node in ast.walk(
    tree_3a
):

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
        ),
    ):
        continue

    node_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not node_source:
        continue

    matched_terms = [
        term
        for term in SEARCH_TERMS_3A1
        if term in node_source
    ]

    if not matched_terms:
        continue

    contract_hits_3a1.append(
        {
            "function":
                node.name,

            "line_number":
                node.lineno,

            "matched_terms":
                matched_terms,

            "match_count":
                len(
                    matched_terms
                ),
        }
    )


section3a1_contract_candidates_df = (
    pd.DataFrame(
        contract_hits_3a1
    )
)


if not section3a1_contract_candidates_df.empty:

    section3a1_contract_candidates_df = (
        section3a1_contract_candidates_df
        .sort_values(
            [
                "match_count",
                "line_number",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )


print("\n41-COLUMN FEATURE-BUILDER CANDIDATES")
print("-" * 100)

display(
    section3a1_contract_candidates_df
)


# ==========================================================================================
# 8. Print strongest candidate source(s)
# ==========================================================================================

print("\nSTRONGEST FEATURE-BUILDER CANDIDATE SOURCES")
print("-" * 100)


if not section3a1_contract_candidates_df.empty:

    max_match_count_3a1 = int(
        section3a1_contract_candidates_df[
            "match_count"
        ].max()
    )

    strongest_names_3a1 = (
        section3a1_contract_candidates_df.loc[
            section3a1_contract_candidates_df[
                "match_count"
            ]
            ==
            max_match_count_3a1,
            "function",
        ]
        .tolist()
    )


    for candidate_name in (
        strongest_names_3a1
    ):

        for node in ast.walk(
            tree_3a
        ):

            if not isinstance(
                node,
                (
                    ast.FunctionDef,
                    ast.AsyncFunctionDef,
                ),
            ):
                continue

            if (
                node.name
                !=
                candidate_name
            ):
                continue

            candidate_source = (
                ast.get_source_segment(
                    source_3a,
                    node,
                )
            )

            print(
                "\n"
                + "=" * 100
            )

            print(
                f"CANDIDATE: "
                f"{candidate_name} "
                f"(line {node.lineno})"
            )

            print(
                "=" * 100
            )

            print(
                candidate_source
            )

else:

    strongest_names_3a1 = []

    print(
        "No function candidate identified."
    )


# ==========================================================================================
# 9. Determine recovery status — diagnostic only
# ==========================================================================================

exact_definition_found_3a1 = any(
    (
        isinstance(
            node,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        )
        and
        getattr(
            node,
            "name",
            None,
        )
        ==
        TARGET_NAME_3A1
    )
    for node in ast.walk(
        tree_3a
    )
)


target_assignment_found_3a1 = (
    len(
        assignment_hits_3a1
    )
    > 0
)


strong_candidate_found_3a1 = (
    len(
        strongest_names_3a1
    )
    > 0
)


section3a1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "target referenced in Notebook 59",

            "observed":
                len(
                    occurrence_rows_3a1
                ),

            "passed":
                len(
                    occurrence_rows_3a1
                )
                > 0,
        },

        {
            "validation":
                "exact AST function definition found",

            "observed":
                exact_definition_found_3a1,

            "passed":
                exact_definition_found_3a1,
        },

        {
            "validation":
                "target assignment found",

            "observed":
                target_assignment_found_3a1,

            "passed":
                target_assignment_found_3a1,
        },

        {
            "validation":
                "41-column builder candidate found",

            "observed":
                strongest_names_3a1,

            "passed":
                strong_candidate_found_3a1,
        },
    ]
)


print("\nSECTION 3A.1 DIAGNOSTIC SUMMARY")
print("-" * 100)

display(
    section3a1_validation_df
)


print("\n" + "=" * 100)

print(
    "✅ TARGETED SEARCH COMPLETE"
)

print(
    "⚠️ THIS CELL DOES NOT MODIFY OR LOAD THE R3 MODEL"
)

print(
    "⚠️ DO NOT BENCHMARK YET"
)

print("=" * 100)

====================================================================================================
SECTION 3A.1 — TARGETED RECOVERY OF build_legality_aware_feature_row
====================================================================================================

ALL TEXTUAL OCCURRENCES
----------------------------------------------------------------------------------------------------

    line_number                                        source_line
0          3607                "build_legality_aware_feature_row",
1          3665  # build_legality_aware_feature_row requires BOTH:
2          3671                  build_legality_aware_feature_row(
3          4014  target_function_name = "build_legality_aware_f...
4          4054  "Could not locate build_legality_aware_feature...
5          4072                 "build_legality_aware_feature_row"
6          4077                   build_legality_aware_feature_row
7          4080  print("\n✅ build_legality_aware_feature_row() ...
8          4120  TARGET_FUNCTION = "build_legality_aware_featur...
9          4169  "Could not recover build_legality_aware_featur...
10         4207  print("\n✅ build_legality_aware_feature_row() ...
11         4217    "build_legality_aware_feature_row" in globals()
12         4273  print("\nCalling build_legality_aware_feature_...
13         4276                  build_legality_aware_feature_row(
14         4327     "Expected build_legality_aware_feature_row() "
15         4783  TARGET_FUNCTION = "build_legality_aware_featur...
16         4936                   build_legality_aware_feature_row
17         4941    "✅ build_legality_aware_feature_row() RELOADED"
18         5048  TARGET_FUNCTION = "build_legality_aware_featur...
19         5266                "build_legality_aware_feature_row",
20         5288                   build_legality_aware_feature_row
21         5985                "build_legality_aware_feature_row",
22         6009                   build_legality_aware_feature_row
23         6211  build_legality_aware_feature_row.__globals__.u...
24         6383                "build_legality_aware_feature_row",
25         6403                   build_legality_aware_feature_row
26         6518                  build_legality_aware_feature_row(

SOURCE CONTEXT AROUND OCCURRENCES
----------------------------------------------------------------------------------------------------

====================================================================================================
OCCURRENCE 1 — AROUND LINE 3607
----------------------------------------------------------------------------------------------------
                        )
                        == 46
                    ),
            },
        ]
    )
)

print("\nR3 LIVE ENCODER CONTRACT")
print("-" * 100)

display(
    section6b_encoder_contract_df
)

assert section6b_encoder_contract_df[
    "passed"
].all()

print("\nNUMERIC RAW INPUTS")
print("-" * 100)

for column_name in (
    numeric_raw_columns
):
    print(column_name)

print("\nCATEGORICAL RAW INPUTS")
print("-" * 100)

for column_name in (
    categorical_source_columns
):
    print(column_name)

print(
    "\n✅ EXACT 46-FEATURE R3 ENCODER CREATED"
)

print(
    "✅ NUMERIC FEATURE MAPPING VERIFIED"
)

print(
    "✅ CATEGORICAL ONE-HOT MAPPING VERIFIED"
)

print(
    "✅ FROZEN PREPROCESSOR VERSION CONFLICT BYPASSED SAFELY"
)

print(
    "✅ NO MODEL OR ARTIFACT MODIFICATION PERFORMED"
)

print(
    "✅ SECTION 6B COMPLETE"
)


# In[80]:


# ==========================================================================================
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "

====================================================================================================
OCCURRENCE 2 — AROUND LINE 3665
----------------------------------------------------------------------------------------------------


# In[80]:


# ==========================================================================================
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "
    f"{section6c_r3_matrix.shape}; "
    "expected (1, 46)."
)

assert len(r3_live_feature_names) == 46, (
    "R3 live feature-name contract is not 46 features."
)

assert np.isfinite(
    section6c_r3_matrix
).all(), (
    "R3 feature matrix contains NaN or infinite values."
)

print("\nR3 ENCODED MATRIX")
print("-" * 100)

print(
    "Shape :",
    section6c_r3_matrix.shape,
)

section6c_encoded_df = pd.DataFrame(
    section6c_r3_matrix,
    columns=r3_live_feature_names,
)

display(section6c_encoded_df)


# ------------------------------------------------------------------------------------------
# 5. Execute live R3 model prediction
# ------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------

====================================================================================================
OCCURRENCE 3 — AROUND LINE 3671
----------------------------------------------------------------------------------------------------
# SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE
# ==========================================================================================

import numpy as np
import pandas as pd

print("=" * 100)
print("SECTION 6C — VALIDATE END-TO-END R3 LIVE INFERENCE PIPELINE")
print("=" * 100)

# ------------------------------------------------------------------------------------------
# 1. Confirm all required live components are loaded
# ------------------------------------------------------------------------------------------

required_objects_6c = [
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "r3_live_model",
    "r3_live_feature_names",
]

missing_objects_6c = [
    name
    for name in required_objects_6c
    if name not in globals()
]

assert not missing_objects_6c, (
    "Missing required Section 6C objects: "
    f"{missing_objects_6c}"
)

print("\nLIVE COMPONENT CHECK")
print("-" * 100)

for name in required_objects_6c:
    print(f"{name}: LOADED")


# ------------------------------------------------------------------------------------------
# 2. Confirm the test state and legal moves from Section 6C.2 still exist
# ------------------------------------------------------------------------------------------

assert "section6c2_test_state" in globals(), (
    "section6c2_test_state is not available."
)

assert "section6c2_legal_moves" in globals(), (
    "section6c2_legal_moves is not available."
)

assert len(section6c2_legal_moves) > 0, (
    "section6c2_legal_moves is empty."
)

print("\nTEST INPUT")
print("-" * 100)

print(
    "Battle state type :",
    type(section6c2_test_state).__name__,
)

print(
    "Legal move count  :",
    len(section6c2_legal_moves),
)


# ------------------------------------------------------------------------------------------
# 3. Build exact 41-column live raw feature row
#
# IMPORTANT:
# build_legality_aware_feature_row requires BOTH:
#     battle_state
#     legal_moves
# ------------------------------------------------------------------------------------------

section6c_raw_feature_row = (
    build_legality_aware_feature_row(
        section6c2_test_state,
        section6c2_legal_moves,
    )
)

assert isinstance(
    section6c_raw_feature_row,
    pd.DataFrame,
), (
    "Raw feature builder did not return a pandas DataFrame."
)

assert section6c_raw_feature_row.shape == (1, 41), (
    "Unexpected raw feature shape: "
    f"{section6c_raw_feature_row.shape}; "
    "expected (1, 41)."
)

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(section6c_raw_feature_row).__name__,
)

print(
    "Shape :",
    section6c_raw_feature_row.shape,
)

display(section6c_raw_feature_row)


# ------------------------------------------------------------------------------------------
# 4. Encode raw row into exact R3 46-feature model matrix
# ------------------------------------------------------------------------------------------

section6c_r3_matrix = (
    encode_r3_feature_row(
        section6c_raw_feature_row
    )
)

section6c_r3_matrix = np.asarray(
    section6c_r3_matrix,
    dtype=np.float64,
)

if section6c_r3_matrix.ndim == 1:
    section6c_r3_matrix = (
        section6c_r3_matrix.reshape(1, -1)
    )

assert section6c_r3_matrix.shape == (1, 46), (
    "Unexpected R3 encoded feature shape: "
    f"{section6c_r3_matrix.shape}; "
    "expected (1, 46)."
)

assert len(r3_live_feature_names) == 46, (
    "R3 live feature-name contract is not 46 features."
)

assert np.isfinite(
    section6c_r3_matrix
).all(), (
    "R3 feature matrix contains NaN or infinite values."
)

print("\nR3 ENCODED MATRIX")
print("-" * 100)

print(
    "Shape :",
    section6c_r3_matrix.shape,
)

section6c_encoded_df = pd.DataFrame(
    section6c_r3_matrix,
    columns=r3_live_feature_names,
)

display(section6c_encoded_df)


# ------------------------------------------------------------------------------------------
# 5. Execute live R3 model prediction
# ------------------------------------------------------------------------------------------

section6c_prediction = (
    r3_live_model.predict(
        section6c_r3_matrix
    )
)

assert len(section6c_prediction) == 1, (
    "R3 model did not return exactly one prediction."
)

section6c_predicted_action = (
    section6c_prediction[0]
)

print("\nR3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action :",
    section6c_predicted_action,
)


# ------------------------------------------------------------------------------------------
# 6. Execute and validate probability vector
# ------------------------------------------------------------------------------------------

assert hasattr(
    r3_live_model,
    "predict_proba",

====================================================================================================
OCCURRENCE 4 — AROUND LINE 4014
----------------------------------------------------------------------------------------------------
            "validation":
                "probability_sum",

            "observed":
                float(
                    np.sum(
                        section6c_probability_vector
                    )
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    float(
                        np.sum(
                            section6c_probability_vector
                        )
                    ),
                    1.0,
                    atol=1e-9,
                ),
        },
    ]
)

print("\nEND-TO-END R3 LIVE INFERENCE VALIDATION")
print("-" * 100)

display(
    section6c_validation_df
)

assert section6c_validation_df[
    "passed"
].all()


# ------------------------------------------------------------------------------------------
# 8. Completion
# ------------------------------------------------------------------------------------------

print("\n" + "=" * 100)

print("✅ RAW LIVE FEATURE ROW BUILT")
print("✅ EXACT 41-COLUMN RAW FEATURE CONTRACT VERIFIED")
print("✅ EXACT 46-FEATURE R3 MATRIX CREATED")
print("✅ R3 PREDICTION EXECUTED")
print("✅ R3 PROBABILITY VECTOR VALIDATED")
print("✅ END-TO-END INFERENCE PATH CONFIRMED")
print("✅ SECTION 6C COMPLETE")

print("=" * 100)


# In[73]:


# ==========================================================================================
# SECTION 6C.1 — LOAD EXISTING LEGALITY-AWARE FEATURE BUILDER
# ==========================================================================================

print("=" * 100)
print("SECTION 6C.1 — LOAD EXISTING LEGALITY-AWARE FEATURE BUILDER")
print("=" * 100)

import ast
from pathlib import Path

# ------------------------------------------------------------------------------------------
# Search known Notebook 54/55 scripts for the exact function definition
# ------------------------------------------------------------------------------------------

candidate_scripts = [
    PROJECT_ROOT / "scripts" / "54_tournament_strength_optimization_clean.py",
    PROJECT_ROOT / "scripts" / "55_controlled_feature_ablation_retraining_clean.py",
]

target_function_name = "build_legality_aware_feature_row"

resolved_function_source = None
resolved_function_script = None

for script_path in candidate_scripts:

    if not script_path.exists():
        continue

    source = script_path.read_text(
        encoding="utf-8",
        errors="ignore",
    )

    try:
        tree = ast.parse(source)
    except SyntaxError:
        continue

    for node in tree.body:

        if (
            isinstance(node, ast.FunctionDef)
            and node.name == target_function_name
        ):

            resolved_function_source = ast.get_source_segment(
                source,
                node,
            )

            resolved_function_script = script_path

            break

    if resolved_function_source is not None:
        break

assert resolved_function_source is not None, (
    "Could not locate build_legality_aware_feature_row()."
)

print("\nFUNCTION SOURCE LOCATED IN")
print("-" * 100)

print(resolved_function_script)

# ------------------------------------------------------------------------------------------
# Execute ONLY the recovered function definition in Notebook 59
# ------------------------------------------------------------------------------------------

exec(
    resolved_function_source,
    globals(),
)

assert (
    "build_legality_aware_feature_row"
    in globals()
)

assert callable(
    build_legality_aware_feature_row
)

print("\n✅ build_legality_aware_feature_row() LOADED")
print("✅ FUNCTION IS CALLABLE")
print("✅ SECTION 6C.1 COMPLETE")


# In[38]:


# ==========================================================================================
# SECTION 6C.1A — LOAD FUNCTION DEPENDENCIES
# ==========================================================================================

from typing import Any, Sequence
import numpy as np
import pandas as pd

print("✅ Any loaded")
print("✅ Sequence loaded")
print("✅ numpy loaded")
print("✅ pandas loaded")
print("✅ SECTION 6C.1A COMPLETE")


# In[40]:


# ==========================================================================================
# SECTION 6C.1B — FORCE-LOAD LEGALITY-AWARE FEATURE BUILDER SAFELY
# ==========================================================================================

print("=" * 100)
print("SECTION 6C.1B — FORCE-LOAD LEGALITY-AWARE FEATURE BUILDER SAFELY")
print("=" * 100)

import ast
from pathlib import Path
from typing import Any, Sequence
import numpy as np
import pandas as pd

TARGET_FUNCTION = "build_legality_aware_feature_row"

candidate_scripts = [
    PROJECT_ROOT
    / "scripts"
    / "54_tournament_strength_optimization_clean.py",

    PROJECT_ROOT
    / "scripts"
    / "55_controlled_feature_ablation_retraining_clean.py",
]

function_source = None
function_file = None


====================================================================================================
OCCURRENCE 5 — AROUND LINE 4054
----------------------------------------------------------------------------------------------------
# 8. Completion

                           name object_type  line_number
0  parse_r3_categorical_feature    FUNCTION         3193
1         encode_r3_feature_row    FUNCTION         3287
2             R3LiveBattleAgent       CLASS         7654
3          R3LoggingBattleAgent       CLASS        10179
4      build_r3_battle_state_8a    FUNCTION        10757
5              run_r3_battle_8a    FUNCTION        10831

TARGET-RELATED ASSIGNMENTS
----------------------------------------------------------------------------------------------------

   line_number                                             source
0         3606  required_objects_6c = [\n    "build_legality_a...
1         3670  section6c_raw_feature_row = (\n    build_legal...
2         4014  target_function_name = "build_legality_aware_f...
3         4120  TARGET_FUNCTION = "build_legality_aware_featur...
4         4275  section6c2_raw_row = (\n    build_legality_awa...
5         4783  TARGET_FUNCTION = "build_legality_aware_featur...
6         5048  TARGET_FUNCTION = "build_legality_aware_featur...
7         5258  key_dependencies = [\n    "get_state_value",\n...
8         5984  critical_dependencies_6c2l = [\n    "build_leg...
9         6382  required_dependencies_6d = [\n    "build_legal...

POTENTIALLY RELEVANT IMPORTS
----------------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: []

41-COLUMN FEATURE-BUILDER CANDIDATES
----------------------------------------------------------------------------------------------------

                function  line_number matched_terms  match_count
0  encode_r3_feature_row         3287          [41]            1
1     build_model_matrix         6497          [41]            1

STRONGEST FEATURE-BUILDER CANDIDATE SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
CANDIDATE: encode_r3_feature_row (line 3287)
====================================================================================================
def encode_r3_feature_row(
    raw_feature_dataframe,
):
    """
    Convert the 1x41 raw production feature dataframe
    into the exact 1x46 feature matrix expected by R3.

    This intentionally reconstructs ONLY the retained
    R3 features and does not recreate discarded features.
    """

    assert isinstance(
        raw_feature_dataframe,
        pd.DataFrame,
    )

    assert len(
        raw_feature_dataframe
    ) == 1, (
        "R3 live encoder expects exactly one raw row."
    )

    raw_row = (
        raw_feature_dataframe
        .iloc[0]
    )

    encoded_values = {}

    # ------------------------------------------------------------------
    # Numeric columns
    # ------------------------------------------------------------------

    for encoded_name in (
        R3_NUMERIC_FEATURES
    ):

        raw_column = encoded_name[
            len("numeric__"):
        ]

        assert raw_column in raw_row.index, (
            f"Required numeric raw feature missing: "
            f"{raw_column}"
        )

        numeric_value = pd.to_numeric(
            raw_row[
                raw_column
            ],
            errors="coerce",
        )

        if pd.isna(
            numeric_value
        ):
            numeric_value = 0.0

        encoded_values[
            encoded_name
        ] = float(
            numeric_value
        )

    # ------------------------------------------------------------------
    # Categorical one-hot columns
    # ------------------------------------------------------------------

    for encoded_name in (
        R3_CATEGORICAL_FEATURES
    ):

        (
            source_column,
            category_value,
        ) = parse_r3_categorical_feature(
            encoded_name
        )

        assert source_column in raw_row.index, (
            f"Required categorical raw feature missing: "
            f"{source_column}"
        )

        actual_value = str(
            raw_row[
                source_column
            ]
        )

        encoded_values[
            encoded_name
        ] = float(
            actual_value
            ==
            category_value
        )

    # ------------------------------------------------------------------
    # Freeze exact R3 order
    # ------------------------------------------------------------------

    encoded_dataframe = pd.DataFrame(
        [
            encoded_values
        ],
        columns=
            R3_ENCODED_FEATURE_NAMES,
        dtype=float,
    )

    assert encoded_dataframe.shape == (
        1,
        46,
    ), (
        "Unexpected R3 encoded matrix shape: "
        f"{encoded_dataframe.shape}"
    )

    assert list(
        encoded_dataframe.columns
    ) == R3_ENCODED_FEATURE_NAMES

    assert np.isfinite(
        encoded_dataframe.to_numpy(
            dtype=float
        )
    ).all()

    return encoded_dataframe

====================================================================================================
CANDIDATE: build_model_matrix (line 6497)
====================================================================================================
def build_model_matrix(
        self,
        battle_state: Any,
        legal_moves: Sequence[Any],
    ) -> pd.DataFrame:

        legal_moves = list(
            legal_moves
        )

        if not legal_moves:

            raise ValueError(
                "At least one legal move is required."
            )

        # --------------------------------------------------------------
        # 41-column production raw feature row
        # --------------------------------------------------------------

        raw_feature_row = (
            build_legality_aware_feature_row(
                battle_state,
                legal_moves,
            )
        )

        assert isinstance(
            raw_feature_row,
            pd.DataFrame,
        )

        assert raw_feature_row.shape == (
            1,
            41,
        ), (
            "Unexpected raw feature shape: "
            f"{raw_feature_row.shape}; "
            "expected (1, 41)."
        )

        # --------------------------------------------------------------
        # Exact 46-column R3 matrix
        # --------------------------------------------------------------

        encoded_feature_row = (
            encode_r3_feature_row(
                raw_feature_row
            )
        )

        assert isinstance(
            encoded_feature_row,
            pd.DataFrame,
        )

        assert encoded_feature_row.shape == (
            1,
            46,
        ), (
            "Unexpected R3 feature shape: "
            f"{encoded_feature_row.shape}; "
            "expected (1, 46)."
        )

        assert list(
            encoded_feature_row.columns
        ) == self.retained_feature_names, (
            "R3 encoded feature order does not match "
            "the frozen retained-feature contract."
        )

        assert np.isfinite(
            encoded_feature_row.to_numpy(
                dtype=float
            )
        ).all(), (
            "R3 feature matrix contains non-finite values."
        )

        return encoded_feature_row

SECTION 3A.1 DIAGNOSTIC SUMMARY
----------------------------------------------------------------------------------------------------

,validation,observed,passed
0,target referenced in Notebook 59,27,True
1,exact AST function definition found,False,False
2,target assignment found,True,True
3,41-column builder candidate found,"[encode_r3_feature_row, build_model_matrix]",True

====================================================================================================
✅ TARGETED SEARCH COMPLETE
⚠️ THIS CELL DOES NOT MODIFY OR LOAD THE R3 MODEL
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [28]:
# ==========================================================================================
# SECTION 3A.2 — RECOVER EXACT R3 LEGALITY-AWARE FEATURE BUILDER FROM NOTEBOOK 54
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.2 — RECOVER EXACT R3 LEGALITY-AWARE FEATURE BUILDER FROM NOTEBOOK 54")
print("=" * 100)

import ast
from pathlib import Path
from typing import Any, Sequence
import numpy as np
import pandas as pd


# ------------------------------------------------------------------------------------------
# 1. Locate the exact Notebook 54 production script
# ------------------------------------------------------------------------------------------

NOTEBOOK54_SCRIPT_3A2 = (
    PROJECT_ROOT
    / "scripts"
    / "54_tournament_strength_optimization_clean.py"
)

assert NOTEBOOK54_SCRIPT_3A2.exists(), (
    "Notebook 54 production script was not found:\n"
    f"{NOTEBOOK54_SCRIPT_3A2}"
)

print("\nSOURCE SCRIPT")
print("-" * 100)
print(NOTEBOOK54_SCRIPT_3A2)


# ------------------------------------------------------------------------------------------
# 2. Parse Notebook 54 source
# ------------------------------------------------------------------------------------------

source_54_3a2 = NOTEBOOK54_SCRIPT_3A2.read_text(
    encoding="utf-8",
    errors="ignore",
)

tree_54_3a2 = ast.parse(
    source_54_3a2
)

TARGET_FUNCTION_3A2 = (
    "build_legality_aware_feature_row"
)

target_node_3a2 = None


for node in tree_54_3a2.body:

    if (
        isinstance(node, ast.FunctionDef)
        and
        node.name == TARGET_FUNCTION_3A2
    ):
        target_node_3a2 = node
        break


assert target_node_3a2 is not None, (
    "Exact build_legality_aware_feature_row() "
    "definition was not found in Notebook 54."
)


# ------------------------------------------------------------------------------------------
# 3. Recover exact source
# ------------------------------------------------------------------------------------------

target_source_3a2 = ast.get_source_segment(
    source_54_3a2,
    target_node_3a2,
)

assert target_source_3a2 is not None


print("\nEXACT FUNCTION LOCATED")
print("-" * 100)

print(
    "Function :",
    TARGET_FUNCTION_3A2,
)

print(
    "Line     :",
    target_node_3a2.lineno,
)

print(
    "End line :",
    getattr(
        target_node_3a2,
        "end_lineno",
        None,
    ),
)

print(
    "Arguments:",
    [
        argument.arg
        for argument
        in target_node_3a2.args.args
    ],
)


# ------------------------------------------------------------------------------------------
# 4. Execute ONLY the exact recovered definition
#
# Postponing annotation evaluation prevents typing annotations such as Any
# and Sequence from interfering with function creation.
# ------------------------------------------------------------------------------------------

safe_target_source_3a2 = (
    "from __future__ import annotations\n\n"
    + target_source_3a2
)

exec(
    safe_target_source_3a2,
    globals(),
)


# ------------------------------------------------------------------------------------------
# 5. Verify function recovery
# ------------------------------------------------------------------------------------------

assert (
    TARGET_FUNCTION_3A2
    in globals()
), (
    "Function source was executed but the target "
    "was not created in globals()."
)

assert callable(
    globals()[
        TARGET_FUNCTION_3A2
    ]
), (
    "Recovered target exists but is not callable."
)


recovered_builder_3a2 = globals()[
    TARGET_FUNCTION_3A2
]


# ------------------------------------------------------------------------------------------
# 6. Validate provenance and signature
# ------------------------------------------------------------------------------------------

import inspect

signature_3a2 = inspect.signature(
    recovered_builder_3a2
)

parameter_names_3a2 = list(
    signature_3a2.parameters.keys()
)

expected_parameters_3a2 = [
    "battle_state",
    "legal_moves",
    "side_mode",
]


section3a2_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 54 production script exists",

            "observed":
                NOTEBOOK54_SCRIPT_3A2.exists(),

            "passed":
                NOTEBOOK54_SCRIPT_3A2.exists(),
        },

        {
            "validation":
                "exact AST function definition found",

            "observed":
                target_node_3a2 is not None,

            "passed":
                target_node_3a2 is not None,
        },

        {
            "validation":
                "expected production source line",

            "observed":
                target_node_3a2.lineno,

            "passed":
                target_node_3a2.lineno == 70120,
        },

        {
            "validation":
                "expected function arguments",

            "observed":
                parameter_names_3a2,

            "passed":
                parameter_names_3a2
                == expected_parameters_3a2,
        },

        {
            "validation":
                "feature builder callable",

            "observed":
                callable(
                    recovered_builder_3a2
                ),

            "passed":
                callable(
                    recovered_builder_3a2
                ),
        },
    ]
)


print("\nSECTION 3A.2 VALIDATION")
print("-" * 100)

display(
    section3a2_validation_df
)


assert section3a2_validation_df[
    "passed"
].astype(bool).all()


print("\n" + "=" * 100)

print(
    "✅ EXACT R3 LEGALITY-AWARE FEATURE BUILDER RECOVERED"
)

print(
    "✅ SOURCE: NOTEBOOK 54 PRODUCTION SCRIPT"
)

print(
    "✅ EXPECTED SOURCE LINE: 70120"
)

print(
    "✅ FUNCTION SIGNATURE VERIFIED"
)

print(
    "⚠️ R3 MODEL HAS NOT BEEN MODIFIED OR RETRAINED"
)

print(
    "⚠️ DO NOT BENCHMARK YET"
)

print("=" * 100)

====================================================================================================
SECTION 3A.2 — RECOVER EXACT R3 LEGALITY-AWARE FEATURE BUILDER FROM NOTEBOOK 54
====================================================================================================

SOURCE SCRIPT
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\54_tournament_strength_optimization_clean.py

EXACT FUNCTION LOCATED
----------------------------------------------------------------------------------------------------
Function : build_legality_aware_feature_row
Line     : 70120
End line : 70472
Arguments: ['battle_state', 'legal_moves', 'side_mode']

SECTION 3A.2 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,passed
0,Notebook 54 production script exists,True,True
1,exact AST function definition found,True,True
2,expected production source line,70120,True
3,expected function arguments,"[battle_state, legal_moves, side_mode]",True
4,feature builder callable,True,True

====================================================================================================
✅ EXACT R3 LEGALITY-AWARE FEATURE BUILDER RECOVERED
✅ SOURCE: NOTEBOOK 54 PRODUCTION SCRIPT
✅ EXPECTED SOURCE LINE: 70120
✅ FUNCTION SIGNATURE VERIFIED
⚠️ R3 MODEL HAS NOT BEEN MODIFIED OR RETRAINED
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [29]:
# ==========================================================================================
# SECTION 3A.3 — AUDIT RECOVERED R3 FEATURE-BUILDER DEPENDENCIES
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.3 — AUDIT RECOVERED R3 FEATURE-BUILDER DEPENDENCIES")
print("=" * 100)

import ast
import builtins
import pandas as pd


# ------------------------------------------------------------------------------------------
# 1. Re-parse the exact recovered function
# ------------------------------------------------------------------------------------------

audit_tree_3a3 = ast.parse(
    target_source_3a2
)

function_node_3a3 = audit_tree_3a3.body[0]

assert isinstance(
    function_node_3a3,
    (ast.FunctionDef, ast.AsyncFunctionDef),
)


# ------------------------------------------------------------------------------------------
# 2. Identify names created locally inside the function
# ------------------------------------------------------------------------------------------

local_names_3a3 = set()

# Function arguments
for arg in function_node_3a3.args.args:
    local_names_3a3.add(arg.arg)

for arg in function_node_3a3.args.kwonlyargs:
    local_names_3a3.add(arg.arg)

if function_node_3a3.args.vararg is not None:
    local_names_3a3.add(
        function_node_3a3.args.vararg.arg
    )

if function_node_3a3.args.kwarg is not None:
    local_names_3a3.add(
        function_node_3a3.args.kwarg.arg
    )


# Names assigned anywhere inside the function
for node in ast.walk(function_node_3a3):

    if isinstance(node, ast.Name):

        if isinstance(
            node.ctx,
            (ast.Store, ast.Param),
        ):
            local_names_3a3.add(
                node.id
            )

    elif isinstance(
        node,
        (ast.FunctionDef, ast.AsyncFunctionDef),
    ):

        if node is not function_node_3a3:
            local_names_3a3.add(
                node.name
            )


# ------------------------------------------------------------------------------------------
# 3. Identify all loaded names
# ------------------------------------------------------------------------------------------

loaded_names_3a3 = set()

for node in ast.walk(function_node_3a3):

    if (
        isinstance(node, ast.Name)
        and
        isinstance(node.ctx, ast.Load)
    ):
        loaded_names_3a3.add(
            node.id
        )


# ------------------------------------------------------------------------------------------
# 4. Determine external/global dependencies
# ------------------------------------------------------------------------------------------

builtin_names_3a3 = set(
    dir(builtins)
)

external_names_3a3 = sorted(
    loaded_names_3a3
    - local_names_3a3
    - builtin_names_3a3
)


dependency_rows_3a3 = []

for name in external_names_3a3:

    available = (
        name in globals()
    )

    obj = (
        globals().get(name)
        if available
        else None
    )

    dependency_rows_3a3.append(
        {
            "dependency": name,
            "available": available,
            "object_type": (
                type(obj).__name__
                if available
                else "MISSING"
            ),
        }
    )


dependency_audit_3a3 = pd.DataFrame(
    dependency_rows_3a3
)


# ------------------------------------------------------------------------------------------
# 5. Display audit
# ------------------------------------------------------------------------------------------

print("\nRECOVERED FUNCTION")
print("-" * 100)

print(
    TARGET_FUNCTION_3A2
)

print(
    "Source lines:",
    target_node_3a2.lineno,
    "-",
    getattr(
        target_node_3a2,
        "end_lineno",
        None,
    ),
)


print("\nEXTERNAL/GLOBAL DEPENDENCIES")
print("-" * 100)

if len(dependency_audit_3a3) > 0:

    display(
        dependency_audit_3a3
    )

else:

    print(
        "No external dependencies detected."
    )


# ------------------------------------------------------------------------------------------
# 6. Separate available and missing dependencies
# ------------------------------------------------------------------------------------------

if len(dependency_audit_3a3) > 0:

    missing_dependencies_3a3 = (
        dependency_audit_3a3.loc[
            ~dependency_audit_3a3[
                "available"
            ].astype(bool),
            "dependency",
        ]
        .astype(str)
        .tolist()
    )

    available_dependencies_3a3 = (
        dependency_audit_3a3.loc[
            dependency_audit_3a3[
                "available"
            ].astype(bool),
            "dependency",
        ]
        .astype(str)
        .tolist()
    )

else:

    missing_dependencies_3a3 = []
    available_dependencies_3a3 = []


print("\nDEPENDENCY SUMMARY")
print("-" * 100)

print(
    "External dependencies detected :",
    len(external_names_3a3),
)

print(
    "Available in Notebook 60       :",
    len(available_dependencies_3a3),
)

print(
    "Missing from Notebook 60       :",
    len(missing_dependencies_3a3),
)


if missing_dependencies_3a3:

    print("\nMISSING DEPENDENCIES:")

    for dependency in missing_dependencies_3a3:
        print(
            "  -",
            dependency,
        )

else:

    print(
        "\n✅ No missing runtime dependencies detected."
    )


# ------------------------------------------------------------------------------------------
# 7. Validation result
#
# IMPORTANT:
# Do NOT assert that all dependencies exist yet.
# If something is missing, we want the notebook to REPORT it cleanly
# rather than stop execution.
# ------------------------------------------------------------------------------------------

section3a3_status_df = pd.DataFrame(
    [
        {
            "validation":
                "exact recovered source available",

            "observed":
                target_source_3a2 is not None,

            "passed":
                target_source_3a2 is not None,
        },

        {
            "validation":
                "function AST parsed",

            "observed":
                isinstance(
                    function_node_3a3,
                    (
                        ast.FunctionDef,
                        ast.AsyncFunctionDef,
                    ),
                ),

            "passed":
                isinstance(
                    function_node_3a3,
                    (
                        ast.FunctionDef,
                        ast.AsyncFunctionDef,
                    ),
                ),
        },

        {
            "validation":
                "runtime dependencies present",

            "observed":
                (
                    "ALL PRESENT"
                    if not missing_dependencies_3a3
                    else missing_dependencies_3a3
                ),

            "passed":
                len(
                    missing_dependencies_3a3
                ) == 0,
        },
    ]
)


print("\nSECTION 3A.3 VALIDATION")
print("-" * 100)

display(
    section3a3_status_df
)


print("\n" + "=" * 100)

if not missing_dependencies_3a3:

    print(
        "✅ R3 FEATURE-BUILDER DEPENDENCY AUDIT PASSED"
    )

    print(
        "➡️ NEXT: VALIDATE FEATURE SCHEMA / OUTPUT CONTRACT"
    )

else:

    print(
        "⚠️ R3 FEATURE-BUILDER DEPENDENCY AUDIT FOUND MISSING GLOBALS"
    )

    print(
        "➡️ NEXT: RECOVER ONLY THE REQUIRED DEPENDENCIES FROM THE PRODUCTION SOURCE"
    )


print(
    "⚠️ R3 MODEL REMAINS UNMODIFIED"
)

print(
    "⚠️ NO RETRAINING"
)

print(
    "⚠️ DO NOT BENCHMARK YET"
)

print("=" * 100)

====================================================================================================
SECTION 3A.3 — AUDIT RECOVERED R3 FEATURE-BUILDER DEPENDENCIES
====================================================================================================

RECOVERED FUNCTION
----------------------------------------------------------------------------------------------------
build_legality_aware_feature_row
Source lines: 70120 - 70472

EXTERNAL/GLOBAL DEPENDENCIES
----------------------------------------------------------------------------------------------------

                                dependency  available           object_type
0                                      Any       True              _AnyMeta
1                    POLICY_ACTION_CLASSES      False               MISSING
2                  PREPROCESS_RAW_FEATURES      False               MISSING
3                                 Sequence       True  _SpecialGenericAlias
4                      action_feature_name      False               MISSING
5                 canonical_move_signature      False               MISSING
6                     classify_damage_band      False               MISSING
7                     classify_energy_band      False               MISSING
8                      classify_turn_phase      False               MISSING
9                        extract_move_name      False               MISSING
10                     get_attached_energy      False               MISSING
11                           get_card_name      False               MISSING
12                      get_pokemon_damage      False               MISSING
13                         get_state_value      False               MISSING
14  legality_training_categorical_features      False               MISSING
15      legality_training_numeric_features      False               MISSING
16                   normalize_action_name      False               MISSING
17                                      pd       True                module
18         training_active_card_action_map      False               MISSING

DEPENDENCY SUMMARY
----------------------------------------------------------------------------------------------------
External dependencies detected : 19
Available in Notebook 60       : 3
Missing from Notebook 60       : 16

MISSING DEPENDENCIES:
  - POLICY_ACTION_CLASSES
  - PREPROCESS_RAW_FEATURES
  - action_feature_name
  - canonical_move_signature
  - classify_damage_band
  - classify_energy_band
  - classify_turn_phase
  - extract_move_name
  - get_attached_energy
  - get_card_name
  - get_pokemon_damage
  - get_state_value
  - legality_training_categorical_features
  - legality_training_numeric_features
  - normalize_action_name
  - training_active_card_action_map

SECTION 3A.3 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,passed
0,exact recovered source available,True,True
1,function AST parsed,True,True
2,runtime dependencies present,"[POLICY_ACTION_CLASSES, PREPROCESS_RAW_FEATURE...",False

====================================================================================================
⚠️ R3 FEATURE-BUILDER DEPENDENCY AUDIT FOUND MISSING GLOBALS
➡️ NEXT: RECOVER ONLY THE REQUIRED DEPENDENCIES FROM THE PRODUCTION SOURCE
⚠️ R3 MODEL REMAINS UNMODIFIED
⚠️ NO RETRAINING
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [30]:
# ==========================================================================================
# SECTION 3A.4 — RECOVER MISSING R3 FEATURE-BUILDER DEPENDENCIES FROM NOTEBOOK 54
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.4 — RECOVER MISSING R3 FEATURE-BUILDER DEPENDENCIES FROM NOTEBOOK 54")
print("=" * 100)

import ast
import builtins
import pandas as pd


# ------------------------------------------------------------------------------------------
# 1. Exact dependency list from Section 3A.3
# ------------------------------------------------------------------------------------------

REQUIRED_DEPENDENCIES_3A4 = list(
    missing_dependencies_3a3
)

print("\nREQUIRED DEPENDENCIES")
print("-" * 100)

for name in REQUIRED_DEPENDENCIES_3A4:
    print(name)


# ------------------------------------------------------------------------------------------
# 2. Build Notebook 54 top-level definition / assignment maps
# ------------------------------------------------------------------------------------------

definition_map_3a4 = {}
assignment_map_3a4 = {}


for node in tree_54_3a2.body:

    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):
        definition_map_3a4[
            node.name
        ] = node

    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        targets = (
            node.targets
            if isinstance(
                node,
                ast.Assign,
            )
            else [node.target]
        )

        for target in targets:

            if isinstance(
                target,
                ast.Name,
            ):

                assignment_map_3a4[
                    target.id
                ] = node

            elif isinstance(
                target,
                (
                    ast.Tuple,
                    ast.List,
                ),
            ):

                for element in target.elts:

                    if isinstance(
                        element,
                        ast.Name,
                    ):

                        assignment_map_3a4[
                            element.id
                        ] = node


# ------------------------------------------------------------------------------------------
# 3. Inventory exact source locations
# ------------------------------------------------------------------------------------------

recovery_inventory_3a4 = []


for name in REQUIRED_DEPENDENCIES_3A4:

    if name in definition_map_3a4:

        node = definition_map_3a4[
            name
        ]

        recovery_inventory_3a4.append(
            {
                "dependency":
                    name,

                "source_type":
                    "DEFINITION",

                "line_number":
                    node.lineno,

                "end_line":
                    getattr(
                        node,
                        "end_lineno",
                        None,
                    ),

                "found":
                    True,
            }
        )

    elif name in assignment_map_3a4:

        node = assignment_map_3a4[
            name
        ]

        recovery_inventory_3a4.append(
            {
                "dependency":
                    name,

                "source_type":
                    "ASSIGNMENT",

                "line_number":
                    node.lineno,

                "end_line":
                    getattr(
                        node,
                        "end_lineno",
                        None,
                    ),

                "found":
                    True,
            }
        )

    else:

        recovery_inventory_3a4.append(
            {
                "dependency":
                    name,

                "source_type":
                    "NOT FOUND",

                "line_number":
                    None,

                "end_line":
                    None,

                "found":
                    False,
            }
        )


section3a4_inventory_df = pd.DataFrame(
    recovery_inventory_3a4
)


print("\nDEPENDENCY SOURCE INVENTORY")
print("-" * 100)

display(
    section3a4_inventory_df
)


# ------------------------------------------------------------------------------------------
# 4. Require every dependency to exist in Notebook 54 source
# ------------------------------------------------------------------------------------------

missing_source_dependencies_3a4 = (
    section3a4_inventory_df.loc[
        ~section3a4_inventory_df[
            "found"
        ].astype(bool),
        "dependency",
    ]
    .astype(str)
    .tolist()
)


assert not missing_source_dependencies_3a4, (
    "The following production dependencies "
    "were not found in Notebook 54:\n"
    + "\n".join(
        missing_source_dependencies_3a4
    )
)


# ------------------------------------------------------------------------------------------
# 5. Helper to discover referenced names
# ------------------------------------------------------------------------------------------

def referenced_names_3a4(
    node,
):

    return {
        child.id
        for child in ast.walk(
            node
        )
        if (
            isinstance(
                child,
                ast.Name,
            )
            and
            isinstance(
                child.ctx,
                ast.Load,
            )
        )
    }


# ------------------------------------------------------------------------------------------
# 6. Resolve dependency closure
#
# Some of the 16 objects may themselves require additional Notebook 54 globals.
# We recover those too, but ONLY if directly required by the dependency chain.
# ------------------------------------------------------------------------------------------

required_definitions_3a4 = set()
required_assignments_3a4 = set()


for name in REQUIRED_DEPENDENCIES_3A4:

    if name in definition_map_3a4:
        required_definitions_3a4.add(
            name
        )

    elif name in assignment_map_3a4:
        required_assignments_3a4.add(
            name
        )


changed_3a4 = True


while changed_3a4:

    changed_3a4 = False


    for name in list(
        required_definitions_3a4
    ):

        node = definition_map_3a4[
            name
        ]

        refs = referenced_names_3a4(
            node
        )

        for ref in refs:

            if (
                ref in definition_map_3a4
                and
                ref not in required_definitions_3a4
            ):

                required_definitions_3a4.add(
                    ref
                )

                changed_3a4 = True


            if (
                ref in assignment_map_3a4
                and
                ref not in required_assignments_3a4
            ):

                required_assignments_3a4.add(
                    ref
                )

                changed_3a4 = True


    for name in list(
        required_assignments_3a4
    ):

        node = assignment_map_3a4[
            name
        ]

        refs = referenced_names_3a4(
            node
        )

        for ref in refs:

            if (
                ref in definition_map_3a4
                and
                ref not in required_definitions_3a4
            ):

                required_definitions_3a4.add(
                    ref
                )

                changed_3a4 = True


            if (
                ref in assignment_map_3a4
                and
                ref not in required_assignments_3a4
            ):

                required_assignments_3a4.add(
                    ref
                )

                changed_3a4 = True


print("\nDEPENDENCY CLOSURE")
print("-" * 100)

print(
    "Required definitions :",
    len(
        required_definitions_3a4
    ),
)

print(
    "Required assignments :",
    len(
        required_assignments_3a4
    ),
)


# ------------------------------------------------------------------------------------------
# 7. Execute required imports from Notebook 54 first
# ------------------------------------------------------------------------------------------

import_results_3a4 = []


for node in tree_54_3a2.body:

    if not isinstance(
        node,
        (
            ast.Import,
            ast.ImportFrom,
        ),
    ):
        continue

    module = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )

    source_line = ast.get_source_segment(
        source_54_3a2,
        node,
    )

    try:

        exec(
            compile(
                module,
                filename=str(
                    NOTEBOOK54_SCRIPT_3A2
                ),
                mode="exec",
            ),
            globals(),
        )

        import_results_3a4.append(
            {
                "source":
                    source_line,

                "loaded":
                    True,

                "error":
                    None,
            }
        )

    except Exception as exc:

        import_results_3a4.append(
            {
                "source":
                    source_line,

                "loaded":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section3a4_import_df = pd.DataFrame(
    import_results_3a4
)


print("\nIMPORT RECOVERY SUMMARY")
print("-" * 100)

print(
    "Successful imports:",
    int(
        section3a4_import_df[
            "loaded"
        ].sum()
    ),
)

print(
    "Failed/skipped imports:",
    int(
        (
            ~section3a4_import_df[
                "loaded"
            ]
        ).sum()
    ),
)


# ------------------------------------------------------------------------------------------
# 8. Execute required assignments / definitions in ORIGINAL source order
# ------------------------------------------------------------------------------------------

load_results_3a4 = []


for node in tree_54_3a2.body:

    object_name = None
    object_type = None


    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        if (
            node.name
            not in required_definitions_3a4
        ):
            continue

        object_name = node.name
        object_type = "DEFINITION"


    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        assigned_names = []

        targets = (
            node.targets
            if isinstance(
                node,
                ast.Assign,
            )
            else [node.target]
        )

        for target in targets:

            if isinstance(
                target,
                ast.Name,
            ):
                assigned_names.append(
                    target.id
                )

            elif isinstance(
                target,
                (
                    ast.Tuple,
                    ast.List,
                ),
            ):

                for element in target.elts:

                    if isinstance(
                        element,
                        ast.Name,
                    ):
                        assigned_names.append(
                            element.id
                        )


        relevant_names = [
            name
            for name in assigned_names
            if name
            in required_assignments_3a4
        ]

        if not relevant_names:
            continue

        object_name = ", ".join(
            relevant_names
        )

        object_type = "ASSIGNMENT"


    else:

        continue


    module = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )


    try:

        exec(
            compile(
                module,
                filename=str(
                    NOTEBOOK54_SCRIPT_3A2
                ),
                mode="exec",
            ),
            globals(),
        )

        load_results_3a4.append(
            {
                "object":
                    object_name,

                "source_type":
                    object_type,

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "loaded":
                    True,

                "error":
                    None,
            }
        )

    except Exception as exc:

        load_results_3a4.append(
            {
                "object":
                    object_name,

                "source_type":
                    object_type,

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "loaded":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section3a4_load_df = pd.DataFrame(
    load_results_3a4
)


print("\nDEPENDENCY LOAD RESULTS")
print("-" * 100)

display(
    section3a4_load_df
)


# ------------------------------------------------------------------------------------------
# 9. Validate the original 16 required dependencies
# ------------------------------------------------------------------------------------------

final_dependency_rows_3a4 = []


for name in REQUIRED_DEPENDENCIES_3A4:

    available = (
        name in globals()
    )

    obj = (
        globals().get(
            name
        )
        if available
        else None
    )

    final_dependency_rows_3a4.append(
        {
            "dependency":
                name,

            "available":
                available,

            "object_type":
                (
                    type(
                        obj
                    ).__name__
                    if available
                    else "MISSING"
                ),
        }
    )


section3a4_final_df = pd.DataFrame(
    final_dependency_rows_3a4
)


print("\nFINAL REQUIRED DEPENDENCY STATUS")
print("-" * 100)

display(
    section3a4_final_df
)


remaining_missing_3a4 = (
    section3a4_final_df.loc[
        ~section3a4_final_df[
            "available"
        ].astype(bool),
        "dependency",
    ]
    .astype(str)
    .tolist()
)


# ------------------------------------------------------------------------------------------
# 10. Re-audit recovered feature builder
# ------------------------------------------------------------------------------------------

builder_ready_3a4 = (
    len(
        remaining_missing_3a4
    )
    == 0
)


section3a4_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "all 16 dependency sources located",

            "observed":
                len(
                    REQUIRED_DEPENDENCIES_3A4
                )
                -
                len(
                    missing_source_dependencies_3a4
                ),

            "expected":
                len(
                    REQUIRED_DEPENDENCIES_3A4
                ),

            "passed":
                len(
                    missing_source_dependencies_3a4
                )
                == 0,
        },

        {
            "validation":
                "required runtime dependencies loaded",

            "observed":
                (
                    "ALL PRESENT"
                    if builder_ready_3a4
                    else remaining_missing_3a4
                ),

            "expected":
                "ALL PRESENT",

            "passed":
                builder_ready_3a4,
        },

        {
            "validation":
                "feature builder remains callable",

            "observed":
                callable(
                    globals().get(
                        "build_legality_aware_feature_row"
                    )
                ),

            "expected":
                True,

            "passed":
                callable(
                    globals().get(
                        "build_legality_aware_feature_row"
                    )
                ),
        },
    ]
)


print("\nSECTION 3A.4 VALIDATION")
print("-" * 100)

display(
    section3a4_validation_df
)


if builder_ready_3a4:

    assert section3a4_validation_df[
        "passed"
    ].all()

    print("\n" + "=" * 100)

    print(
        "✅ ALL R3 FEATURE-BUILDER DEPENDENCIES RECOVERED"
    )

    print(
        "✅ EXACT NOTEBOOK 54 PRODUCTION DEFINITIONS USED"
    )

    print(
        "✅ EXACT NOTEBOOK 54 PRODUCTION CONSTANTS USED"
    )

    print(
        "✅ R3 LEGALITY-AWARE FEATURE BUILDER IS RUNTIME-READY"
    )

    print(
        "✅ SECTION 3A.4 COMPLETE"
    )

    print(
        "⚠️ R3 MODEL REMAINS FROZEN"
    )

    print(
        "⚠️ DO NOT BENCHMARK YET"
    )

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print(
        "⚠️ SOME R3 FEATURE-BUILDER DEPENDENCIES ARE STILL MISSING"
    )

    print(
        "Remaining:",
        remaining_missing_3a4,
    )

    print(
        "⚠️ DO NOT BENCHMARK YET"
    )

    print("=" * 100)

====================================================================================================
SECTION 3A.4 — RECOVER MISSING R3 FEATURE-BUILDER DEPENDENCIES FROM NOTEBOOK 54
====================================================================================================

REQUIRED DEPENDENCIES
----------------------------------------------------------------------------------------------------
POLICY_ACTION_CLASSES
PREPROCESS_RAW_FEATURES
action_feature_name
canonical_move_signature
classify_damage_band
classify_energy_band
classify_turn_phase
extract_move_name
get_attached_energy
get_card_name
get_pokemon_damage
get_state_value
legality_training_categorical_features
legality_training_numeric_features
normalize_action_name
training_active_card_action_map

DEPENDENCY SOURCE INVENTORY
----------------------------------------------------------------------------------------------------

,dependency,source_type,line_number,end_line,found
0,POLICY_ACTION_CLASSES,ASSIGNMENT,49717,49719,True
1,PREPROCESS_RAW_FEATURES,ASSIGNMENT,49967,49971,True
2,action_feature_name,ASSIGNMENT,49658,49658,True
3,canonical_move_signature,DEFINITION,69809,69833,True
4,classify_damage_band,DEFINITION,69913,69943,True
5,classify_energy_band,DEFINITION,69876,69906,True
6,classify_turn_phase,DEFINITION,69840,69869,True
7,extract_move_name,DEFINITION,69740,69802,True
8,get_attached_energy,DEFINITION,69597,69649,True
9,get_card_name,DEFINITION,69542,69590,True
10,get_pokemon_damage,DEFINITION,69656,69733,True
11,get_state_value,DEFINITION,69513,69535,True
12,legality_training_categorical_features,ASSIGNMENT,49892,49896,True
13,legality_training_numeric_features,ASSIGNMENT,49886,49890,True
14,normalize_action_name,DEFINITION,22549,22562,True
15,training_active_card_action_map,ASSIGNMENT,51939,51941,True

DEPENDENCY CLOSURE
----------------------------------------------------------------------------------------------------
Required definitions : 10
Required assignments : 12

IMPORT RECOVERY SUMMARY
----------------------------------------------------------------------------------------------------
Successful imports: 110
Failed/skipped imports: 1

DEPENDENCY LOAD RESULTS
----------------------------------------------------------------------------------------------------

,object,source_type,line_number,loaded,error
0,normalize_action_name,DEFINITION,22549,True,NaN
1,POLICY_ACTION_CLASSES,ASSIGNMENT,48661,False,NameError: name 'recovered_policy_action_class...
2,training_active_card_action_map,ASSIGNMENT,49182,True,NaN
3,recovered_action_feature_name,ASSIGNMENT,49524,True,NaN
4,action_feature_name,ASSIGNMENT,49658,True,NaN
5,POLICY_ACTION_CLASSES,ASSIGNMENT,49717,False,NameError: name 'POLICY_ACTION_CLASSES' is not...
6,recovered_feature_lists,ASSIGNMENT,49742,True,NaN
7,legality_training_numeric_features,ASSIGNMENT,49886,False,KeyError: 'legality_training_numeric_features'
8,legality_training_categorical_features,ASSIGNMENT,49892,False,KeyError: 'legality_training_categorical_featu...
9,section4vb_action_indicator_features,ASSIGNMENT,49912,True,NaN
10,PREPROCESS_NUMERIC_FEATURES,ASSIGNMENT,49953,False,NameError: name 'legality_training_numeric_fea...
11,PREPROCESS_CATEGORICAL_FEATURES,ASSIGNMENT,49963,False,NameError: name 'legality_training_categorical...
12,PREPROCESS_RAW_FEATURES,ASSIGNMENT,49967,False,NameError: name 'PREPROCESS_NUMERIC_FEATURES' ...
13,section4vb_recovered_action_map,ASSIGNMENT,51649,True,NaN
14,training_active_card_action_map,ASSIGNMENT,51939,True,NaN
15,get_state_value,DEFINITION,69513,True,NaN
16,get_card_name,DEFINITION,69542,True,NaN
17,get_attached_energy,DEFINITION,69597,True,NaN
18,get_pokemon_damage,DEFINITION,69656,True,NaN
19,extract_move_name,DEFINITION,69740,True,NaN
20,canonical_move_signature,DEFINITION,69809,True,NaN
21,classify_turn_phase,DEFINITION,69840,True,NaN
22,classify_energy_band,DEFINITION,69876,True,NaN
23,classify_damage_band,DEFINITION,69913,True,NaN

FINAL REQUIRED DEPENDENCY STATUS
----------------------------------------------------------------------------------------------------

                                dependency  available object_type
0                    POLICY_ACTION_CLASSES      False     MISSING
1                  PREPROCESS_RAW_FEATURES      False     MISSING
2                      action_feature_name       True    NoneType
3                 canonical_move_signature       True    function
4                     classify_damage_band       True    function
5                     classify_energy_band       True    function
6                      classify_turn_phase       True    function
7                        extract_move_name       True    function
8                      get_attached_energy       True    function
9                            get_card_name       True    function
10                      get_pokemon_damage       True    function
11                         get_state_value       True    function
12  legality_training_categorical_features      False     MISSING
13      legality_training_numeric_features      False     MISSING
14                   normalize_action_name       True    function
15         training_active_card_action_map       True    NoneType

SECTION 3A.4 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,all 16 dependency sources located,16,16,True
1,required runtime dependencies loaded,"[POLICY_ACTION_CLASSES, PREPROCESS_RAW_FEATURE...",ALL PRESENT,False
2,feature builder remains callable,True,True,True

====================================================================================================
⚠️ SOME R3 FEATURE-BUILDER DEPENDENCIES ARE STILL MISSING
Remaining: ['POLICY_ACTION_CLASSES', 'PREPROCESS_RAW_FEATURES', 'legality_training_categorical_features', 'legality_training_numeric_features']
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [31]:
# ==========================================================================================
# SECTION 3A.4A — LOCATE AUTHORITATIVE R3 SCHEMA OBJECTS IN NOTEBOOK 53
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.4A — LOCATE AUTHORITATIVE R3 SCHEMA OBJECTS IN NOTEBOOK 53")
print("=" * 100)

from pathlib import Path
import ast
import pandas as pd


# ==========================================================================================
# 1. Authoritative upstream source
# ==========================================================================================

NOTEBOOK53_SCRIPT_3A4A = (
    PROJECT_ROOT
    / "scripts"
    / "53_legality_aware_policy_optimization.py"
)

print("\nNOTEBOOK 53 SOURCE")
print("-" * 100)
print(NOTEBOOK53_SCRIPT_3A4A)

assert NOTEBOOK53_SCRIPT_3A4A.exists(), (
    f"Notebook 53 script not found:\n{NOTEBOOK53_SCRIPT_3A4A}"
)


source_53_3a4a = NOTEBOOK53_SCRIPT_3A4A.read_text(
    encoding="utf-8-sig",
    errors="ignore",
)

tree_53_3a4a = ast.parse(
    source_53_3a4a
)


# ==========================================================================================
# 2. Objects that remain unresolved after Section 3A.4
# ==========================================================================================

TARGETS_3A4A = [
    "POLICY_ACTION_CLASSES",
    "PREPROCESS_RAW_FEATURES",
    "action_feature_name",
    "legality_training_categorical_features",
    "legality_training_numeric_features",
    "training_active_card_action_map",
]


print("\nTARGET OBJECTS")
print("-" * 100)

for name in TARGETS_3A4A:
    print(name)


# ==========================================================================================
# 3. Helpers
# ==========================================================================================

def assigned_names_3a4a(node):

    names = []

    if isinstance(node, ast.Assign):
        targets = node.targets

    elif isinstance(node, ast.AnnAssign):
        targets = [node.target]

    else:
        return names

    for target in targets:

        if isinstance(target, ast.Name):
            names.append(target.id)

        elif isinstance(
            target,
            (ast.Tuple, ast.List),
        ):

            for element in target.elts:

                if isinstance(element, ast.Name):
                    names.append(element.id)

    return names


# ==========================================================================================
# 4. Locate every direct assignment / definition
# ==========================================================================================

source_inventory_3a4a = []


for node in tree_53_3a4a.body:

    # --------------------------------------------------------------------------------------
    # Assignments
    # --------------------------------------------------------------------------------------

    if isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        names = assigned_names_3a4a(
            node
        )

        for name in names:

            if name not in TARGETS_3A4A:
                continue

            source_inventory_3a4a.append(
                {
                    "name":
                        name,

                    "source_type":
                        "ASSIGNMENT",

                    "line_number":
                        node.lineno,

                    "end_line":
                        getattr(
                            node,
                            "end_lineno",
                            None,
                        ),

                    "source":
                        ast.get_source_segment(
                            source_53_3a4a,
                            node,
                        ),
                }
            )


    # --------------------------------------------------------------------------------------
    # Definitions
    # --------------------------------------------------------------------------------------

    elif isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        if node.name not in TARGETS_3A4A:
            continue

        source_inventory_3a4a.append(
            {
                "name":
                    node.name,

                "source_type":
                    (
                        "CLASS"
                        if isinstance(
                            node,
                            ast.ClassDef,
                        )
                        else
                        "FUNCTION"
                    ),

                "line_number":
                    node.lineno,

                "end_line":
                    getattr(
                        node,
                        "end_lineno",
                        None,
                    ),

                "source":
                    ast.get_source_segment(
                        source_53_3a4a,
                        node,
                    ),
            }
        )


section3a4a_inventory_df = pd.DataFrame(
    source_inventory_3a4a
)


print("\nDIRECT NOTEBOOK 53 SOURCE INVENTORY")
print("-" * 100)

display(
    section3a4a_inventory_df[
        [
            "name",
            "source_type",
            "line_number",
            "end_line",
        ]
    ]
)


# ==========================================================================================
# 5. Print exact source for each recovered object
# ==========================================================================================

print("\nEXACT NOTEBOOK 53 SOURCES")
print("-" * 100)


for _, row in (
    section3a4a_inventory_df
    .sort_values(
        "line_number"
    )
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        f"{row['name']} "
        f"— {row['source_type']} "
        f"— line {row['line_number']}"
    )

    print("-" * 100)

    print(
        row["source"]
    )


# ==========================================================================================
# 6. Detect whether any recovered assignment is only a recovery placeholder
# ==========================================================================================

placeholder_tokens_3a4a = [
    "recovered_",
    "globals()",
    "exec(",
    "ast.",
    "resolved_",
]


placeholder_rows_3a4a = []


for _, row in section3a4a_inventory_df.iterrows():

    source_text = str(
        row["source"]
    )

    placeholder_detected = any(
        token in source_text
        for token in placeholder_tokens_3a4a
    )

    placeholder_rows_3a4a.append(
        {
            "name":
                row["name"],

            "line_number":
                row["line_number"],

            "looks_like_recovery_placeholder":
                placeholder_detected,
        }
    )


section3a4a_placeholder_df = pd.DataFrame(
    placeholder_rows_3a4a
)


print("\nPLACEHOLDER CHECK")
print("-" * 100)

display(
    section3a4a_placeholder_df
)


# ==========================================================================================
# 7. Search ALL textual occurrences for targets that do not have direct definitions
# ==========================================================================================

found_direct_3a4a = set(
    section3a4a_inventory_df[
        "name"
    ].tolist()
)


missing_direct_3a4a = [
    name
    for name in TARGETS_3A4A
    if name not in found_direct_3a4a
]


text_occurrence_rows_3a4a = []


for missing_name in missing_direct_3a4a:

    for line_number, line in enumerate(
        source_53_3a4a.splitlines(),
        start=1,
    ):

        if missing_name not in line:
            continue

        text_occurrence_rows_3a4a.append(
            {
                "name":
                    missing_name,

                "line_number":
                    line_number,

                "source_line":
                    line.strip(),
            }
        )


section3a4a_missing_occurrences_df = pd.DataFrame(
    text_occurrence_rows_3a4a
)


print("\nTARGETS WITHOUT DIRECT TOP-LEVEL SOURCE")
print("-" * 100)

print(
    missing_direct_3a4a
)


if not section3a4a_missing_occurrences_df.empty:

    print(
        "\nTEXTUAL OCCURRENCES FOR MISSING DIRECT TARGETS"
    )

    display(
        section3a4a_missing_occurrences_df
    )


# ==========================================================================================
# 8. Validate discovery only
#
# IMPORTANT:
# Nothing from Notebook 53 is executed here.
# ==========================================================================================

section3a4a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 53 source exists",

            "observed":
                NOTEBOOK53_SCRIPT_3A4A.exists(),

            "passed":
                NOTEBOOK53_SCRIPT_3A4A.exists(),
        },

        {
            "validation":
                "at least one authoritative target recovered",

            "observed":
                len(
                    found_direct_3a4a
                ),

            "passed":
                len(
                    found_direct_3a4a
                ) > 0,
        },

        {
            "validation":
                "action_feature_name direct source found",

            "observed":
                (
                    "action_feature_name"
                    in found_direct_3a4a
                ),

            "passed":
                (
                    "action_feature_name"
                    in found_direct_3a4a
                ),
        },
    ]
)


print("\nSECTION 3A.4A VALIDATION")
print("-" * 100)

display(
    section3a4a_validation_df
)


print("\n" + "=" * 100)

print("✅ NOTEBOOK 53 UPSTREAM SOURCE INSPECTED")

print(
    "✅ NO NOTEBOOK 53 CODE EXECUTED"
)

print(
    "✅ NO MANUAL FEATURE SCHEMA CREATED"
)

print(
    "⚠️ DO NOT RERUN SECTION 3A.4"
)

print(
    "⚠️ DO NOT BENCHMARK YET"
)

print("=" * 100)

====================================================================================================
SECTION 3A.4A — LOCATE AUTHORITATIVE R3 SCHEMA OBJECTS IN NOTEBOOK 53
====================================================================================================

NOTEBOOK 53 SOURCE
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\53_legality_aware_policy_optimization.py

TARGET OBJECTS
----------------------------------------------------------------------------------------------------
POLICY_ACTION_CLASSES
PREPROCESS_RAW_FEATURES
action_feature_name
legality_training_categorical_features
legality_training_numeric_features
training_active_card_action_map

DIRECT NOTEBOOK 53 SOURCE INVENTORY
----------------------------------------------------------------------------------------------------

                                     name source_type  line_number  end_line
0                   POLICY_ACTION_CLASSES  ASSIGNMENT         4275      4282
1                     action_feature_name    FUNCTION         4285      4300
2         training_active_card_action_map  ASSIGNMENT         8054      8054
3      legality_training_numeric_features  ASSIGNMENT         8131      8151
4  legality_training_categorical_features  ASSIGNMENT         8162      8173
5                 PREPROCESS_RAW_FEATURES  ASSIGNMENT        10569     10572

EXACT NOTEBOOK 53 SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
POLICY_ACTION_CLASSES — ASSIGNMENT — line 4275
----------------------------------------------------------------------------------------------------
POLICY_ACTION_CLASSES = [
    "Ascension",
    "Bind Down",
    "Live Coal",
    "Pass",
    "Quick Attack",
    "Tuck Tail",
]

====================================================================================================
action_feature_name — FUNCTION — line 4285
----------------------------------------------------------------------------------------------------
def action_feature_name(
    action_name: str,
) -> str:
    """
    Convert a policy action name into a safe feature-column suffix.
    """

    return (
        normalize_action_name(
            action_name
        )
        .replace(
            " ",
            "_",
        )
    )

====================================================================================================
training_active_card_action_map — ASSIGNMENT — line 8054
----------------------------------------------------------------------------------------------------
training_active_card_action_map: Dict[str, List[str]] = {}

====================================================================================================
legality_training_numeric_features — ASSIGNMENT — line 8131
----------------------------------------------------------------------------------------------------
legality_training_numeric_features = [
    "turn_number",
    "player_energy",
    "opponent_energy",
    "player_damage",
    "opponent_damage",
    "prize_cards_remaining",
    "hand_size",
    "recomputed_legal_move_count",
    "acting_energy",
    "defending_energy",
    "energy_difference",
    "absolute_energy_difference",
    "acting_damage",
    "defending_damage",
    "damage_difference",
    "absolute_damage_difference",
    "single_legal_move_flag",
    "multi_legal_move_flag",
    "model_choice_required_flag",
]

====================================================================================================
legality_training_categorical_features — ASSIGNMENT — line 8162
----------------------------------------------------------------------------------------------------
legality_training_categorical_features = [
    "current_side",
    "side_mode",
    "player_card",
    "opponent_card",
    "active_card",
    "inactive_card",
    "legal_move_signature",
    "battle_phase",
    "energy_band",
    "damage_band",
]

====================================================================================================
PREPROCESS_RAW_FEATURES — ASSIGNMENT — line 10569
----------------------------------------------------------------------------------------------------
PREPROCESS_RAW_FEATURES = (
    PREPROCESS_NUMERIC_FEATURES
    + PREPROCESS_CATEGORICAL_FEATURES
)

PLACEHOLDER CHECK
----------------------------------------------------------------------------------------------------

,name,line_number,looks_like_recovery_placeholder
0,POLICY_ACTION_CLASSES,4275,False
1,action_feature_name,4285,False
2,training_active_card_action_map,8054,False
3,legality_training_numeric_features,8131,False
4,legality_training_categorical_features,8162,False
5,PREPROCESS_RAW_FEATURES,10569,False

TARGETS WITHOUT DIRECT TOP-LEVEL SOURCE
----------------------------------------------------------------------------------------------------
[]

SECTION 3A.4A VALIDATION
----------------------------------------------------------------------------------------------------

                                    validation observed  passed
0                    Notebook 53 source exists     True    True
1  at least one authoritative target recovered        6    True
2      action_feature_name direct source found     True    True

====================================================================================================
✅ NOTEBOOK 53 UPSTREAM SOURCE INSPECTED
✅ NO NOTEBOOK 53 CODE EXECUTED
✅ NO MANUAL FEATURE SCHEMA CREATED
⚠️ DO NOT RERUN SECTION 3A.4
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [32]:
# ==========================================================================================
# SECTION 3A.4B — LOAD AUTHORITATIVE NOTEBOOK 53 R3 FEATURE SCHEMA
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.4B — LOAD AUTHORITATIVE NOTEBOOK 53 R3 FEATURE SCHEMA")
print("=" * 100)

import ast
import pandas as pd


# ==========================================================================================
# 1. Exact Notebook 53 schema objects required by the production builder
# ==========================================================================================

AUTHORITATIVE_SCHEMA_OBJECTS_3A4B = [
    "POLICY_ACTION_CLASSES",
    "action_feature_name",
    "training_active_card_action_map",
    "legality_training_numeric_features",
    "legality_training_categorical_features",
    "PREPROCESS_NUMERIC_FEATURES",
    "PREPROCESS_CATEGORICAL_FEATURES",
    "PREPROCESS_RAW_FEATURES",
]


print("\nAUTHORITATIVE SCHEMA OBJECTS")
print("-" * 100)

for name in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B:
    print(name)


# ==========================================================================================
# 2. Build exact Notebook 53 source map
# ==========================================================================================

schema_nodes_3a4b = {}


def assigned_names_3a4b(node):

    names = []

    if isinstance(node, ast.Assign):
        targets = node.targets

    elif isinstance(node, ast.AnnAssign):
        targets = [node.target]

    else:
        return names


    for target in targets:

        if isinstance(target, ast.Name):

            names.append(
                target.id
            )

        elif isinstance(
            target,
            (
                ast.Tuple,
                ast.List,
            ),
        ):

            for element in target.elts:

                if isinstance(
                    element,
                    ast.Name,
                ):

                    names.append(
                        element.id
                    )

    return names


for node in tree_53_3a4a.body:

    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        if node.name in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B:

            schema_nodes_3a4b[
                node.name
            ] = node


    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        for assigned_name in assigned_names_3a4b(
            node
        ):

            if (
                assigned_name
                in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B
            ):

                schema_nodes_3a4b[
                    assigned_name
                ] = node


# ==========================================================================================
# 3. Inventory exact sources
# ==========================================================================================

schema_inventory_rows_3a4b = []


for name in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B:

    node = schema_nodes_3a4b.get(
        name
    )

    schema_inventory_rows_3a4b.append(
        {
            "name":
                name,

            "found":
                node is not None,

            "source_type":
                (
                    "FUNCTION"
                    if isinstance(
                        node,
                        (
                            ast.FunctionDef,
                            ast.AsyncFunctionDef,
                        ),
                    )
                    else
                    "ASSIGNMENT"
                    if node is not None
                    else
                    "MISSING"
                ),

            "line_number":
                (
                    node.lineno
                    if node is not None
                    else None
                ),

            "end_line":
                (
                    getattr(
                        node,
                        "end_lineno",
                        None,
                    )
                    if node is not None
                    else None
                ),
        }
    )


section3a4b_inventory_df = pd.DataFrame(
    schema_inventory_rows_3a4b
)


print("\nAUTHORITATIVE NOTEBOOK 53 SCHEMA INVENTORY")
print("-" * 100)

display(
    section3a4b_inventory_df
)


missing_schema_sources_3a4b = (
    section3a4b_inventory_df.loc[
        ~section3a4b_inventory_df[
            "found"
        ].astype(bool),
        "name",
    ]
    .astype(str)
    .tolist()
)


assert not missing_schema_sources_3a4b, (
    "Missing Notebook 53 authoritative schema sources:\n"
    + "\n".join(
        missing_schema_sources_3a4b
    )
)


# ==========================================================================================
# 4. Show exact PREPROCESS definitions before executing
# ==========================================================================================

print("\nEXACT PREPROCESS SCHEMA SOURCES")
print("-" * 100)


for name in [
    "PREPROCESS_NUMERIC_FEATURES",
    "PREPROCESS_CATEGORICAL_FEATURES",
    "PREPROCESS_RAW_FEATURES",
]:

    node = schema_nodes_3a4b[
        name
    ]

    print("\n" + "=" * 100)
    print(
        f"{name} — line {node.lineno}"
    )
    print("-" * 100)

    print(
        ast.get_source_segment(
            source_53_3a4a,
            node,
        )
    )


# ==========================================================================================
# 5. Remove bad intermediate Notebook 54 values before loading authoritative ones
#
# We remove ONLY the schema objects being replaced by exact Notebook 53 production values.
# ==========================================================================================

for name in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B:

    if name in globals():

        del globals()[
            name
        ]


print("\nINTERMEDIATE SCHEMA VALUES CLEARED")
print("-" * 100)

print(
    "Only authoritative Notebook 53 schema objects were cleared for exact reload."
)


# ==========================================================================================
# 6. Execute authoritative schema nodes in ORIGINAL Notebook 53 source order
# ==========================================================================================

unique_nodes_3a4b = {}


for name, node in schema_nodes_3a4b.items():

    unique_nodes_3a4b[
        id(node)
    ] = node


ordered_nodes_3a4b = sorted(
    unique_nodes_3a4b.values(),
    key=lambda node:
        node.lineno,
)


load_results_3a4b = []


for node in ordered_nodes_3a4b:

    node_source = ast.get_source_segment(
        source_53_3a4a,
        node,
    )

    names_for_node = [
        name
        for name, mapped_node
        in schema_nodes_3a4b.items()
        if mapped_node is node
    ]


    module_3a4b = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module_3a4b
    )


    try:

        exec(
            compile(
                module_3a4b,
                filename=str(
                    NOTEBOOK53_SCRIPT_3A4A
                ),
                mode="exec",
            ),
            globals(),
        )

        for name in names_for_node:

            load_results_3a4b.append(
                {
                    "name":
                        name,

                    "line_number":
                        node.lineno,

                    "loaded":
                        name in globals(),

                    "object_type":
                        (
                            type(
                                globals().get(
                                    name
                                )
                            ).__name__
                            if name in globals()
                            else "MISSING"
                        ),

                    "error":
                        None,
                }
            )


    except Exception as exc:

        for name in names_for_node:

            load_results_3a4b.append(
                {
                    "name":
                        name,

                    "line_number":
                        node.lineno,

                    "loaded":
                        False,

                    "object_type":
                        "MISSING",

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


section3a4b_load_df = pd.DataFrame(
    load_results_3a4b
)


print("\nAUTHORITATIVE SCHEMA LOAD RESULTS")
print("-" * 100)

display(
    section3a4b_load_df
)


# ==========================================================================================
# 7. Validate actual object types
# ==========================================================================================

print("\nAUTHORITATIVE OBJECT TYPES")
print("-" * 100)


schema_type_rows_3a4b = []


for name in AUTHORITATIVE_SCHEMA_OBJECTS_3A4B:

    available = (
        name in globals()
    )

    value = (
        globals().get(
            name
        )
        if available
        else None
    )

    schema_type_rows_3a4b.append(
        {
            "name":
                name,

            "available":
                available,

            "object_type":
                (
                    type(
                        value
                    ).__name__
                    if available
                    else "MISSING"
                ),

            "is_none":
                (
                    value is None
                    if available
                    else True
                ),
        }
    )


section3a4b_types_df = pd.DataFrame(
    schema_type_rows_3a4b
)


display(
    section3a4b_types_df
)


# ==========================================================================================
# 8. Exact schema-count validation
# ==========================================================================================

policy_class_count_3a4b = len(
    POLICY_ACTION_CLASSES
)

legality_numeric_count_3a4b = len(
    legality_training_numeric_features
)

legality_categorical_count_3a4b = len(
    legality_training_categorical_features
)

preprocess_numeric_count_3a4b = len(
    PREPROCESS_NUMERIC_FEATURES
)

preprocess_categorical_count_3a4b = len(
    PREPROCESS_CATEGORICAL_FEATURES
)

preprocess_raw_count_3a4b = len(
    PREPROCESS_RAW_FEATURES
)


print("\nAUTHORITATIVE R3 FEATURE COUNTS")
print("-" * 100)

print(
    "Policy action classes        :",
    policy_class_count_3a4b,
)

print(
    "Legality numeric features    :",
    legality_numeric_count_3a4b,
)

print(
    "Legality categorical features:",
    legality_categorical_count_3a4b,
)

print(
    "Preprocess numeric features  :",
    preprocess_numeric_count_3a4b,
)

print(
    "Preprocess categorical       :",
    preprocess_categorical_count_3a4b,
)

print(
    "Total raw features           :",
    preprocess_raw_count_3a4b,
)


# ==========================================================================================
# 9. Display exact schema
# ==========================================================================================

print("\nPOLICY ACTION CLASSES")
print("-" * 100)

for index, value in enumerate(
    POLICY_ACTION_CLASSES,
    start=1,
):

    print(
        f"{index:02d}. {value}"
    )


print("\nPREPROCESS NUMERIC FEATURES")
print("-" * 100)

for index, value in enumerate(
    PREPROCESS_NUMERIC_FEATURES,
    start=1,
):

    print(
        f"{index:02d}. {value}"
    )


print("\nPREPROCESS CATEGORICAL FEATURES")
print("-" * 100)

for index, value in enumerate(
    PREPROCESS_CATEGORICAL_FEATURES,
    start=1,
):

    print(
        f"{index:02d}. {value}"
    )


# ==========================================================================================
# 10. Re-audit original 16 builder dependencies
# ==========================================================================================

dependency_recheck_rows_3a4b = []


for name in REQUIRED_DEPENDENCIES_3A4:

    available = (
        name in globals()
    )

    obj = (
        globals().get(
            name
        )
        if available
        else None
    )


    # None is NOT accepted as a valid recovered production dependency.
    usable = (
        available
        and
        obj is not None
    )


    dependency_recheck_rows_3a4b.append(
        {
            "dependency":
                name,

            "available":
                available,

            "object_type":
                (
                    type(
                        obj
                    ).__name__
                    if available
                    else "MISSING"
                ),

            "usable":
                usable,
        }
    )


section3a4b_dependency_recheck_df = pd.DataFrame(
    dependency_recheck_rows_3a4b
)


print("\nR3 BUILDER DEPENDENCY RECHECK")
print("-" * 100)

display(
    section3a4b_dependency_recheck_df
)


remaining_unusable_3a4b = (
    section3a4b_dependency_recheck_df.loc[
        ~section3a4b_dependency_recheck_df[
            "usable"
        ].astype(bool),
        "dependency",
    ]
    .astype(str)
    .tolist()
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3a4b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "six policy classes",

            "observed":
                policy_class_count_3a4b,

            "expected":
                6,

            "passed":
                policy_class_count_3a4b
                == 6,
        },

        {
            "validation":
                "19 legality numeric features",

            "observed":
                legality_numeric_count_3a4b,

            "expected":
                19,

            "passed":
                legality_numeric_count_3a4b
                == 19,
        },

        {
            "validation":
                "10 legality categorical features",

            "observed":
                legality_categorical_count_3a4b,

            "expected":
                10,

            "passed":
                legality_categorical_count_3a4b
                == 10,
        },

        {
            "validation":
                "31 preprocess numeric features",

            "observed":
                preprocess_numeric_count_3a4b,

            "expected":
                31,

            "passed":
                preprocess_numeric_count_3a4b
                == 31,
        },

        {
            "validation":
                "10 preprocess categorical features",

            "observed":
                preprocess_categorical_count_3a4b,

            "expected":
                10,

            "passed":
                preprocess_categorical_count_3a4b
                == 10,
        },

        {
            "validation":
                "41 raw feature contract",

            "observed":
                preprocess_raw_count_3a4b,

            "expected":
                41,

            "passed":
                preprocess_raw_count_3a4b
                == 41,
        },

        {
            "validation":
                "action_feature_name callable",

            "observed":
                callable(
                    action_feature_name
                ),

            "expected":
                True,

            "passed":
                callable(
                    action_feature_name
                ),
        },

        {
            "validation":
                "training action map is dictionary",

            "observed":
                type(
                    training_active_card_action_map
                ).__name__,

            "expected":
                "dict",

            "passed":
                isinstance(
                    training_active_card_action_map,
                    dict,
                ),
        },

        {
            "validation":
                "all original builder dependencies usable",

            "observed":
                (
                    "ALL USABLE"
                    if not remaining_unusable_3a4b
                    else remaining_unusable_3a4b
                ),

            "expected":
                "ALL USABLE",

            "passed":
                len(
                    remaining_unusable_3a4b
                )
                == 0,
        },
    ]
)


print("\nSECTION 3A.4B VALIDATION")
print("-" * 100)

display(
    section3a4b_validation_df
)


if section3a4b_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print(
        "✅ AUTHORITATIVE NOTEBOOK 53 R3 SCHEMA LOADED"
    )

    print(
        "✅ 6 ACTION CLASSES VERIFIED"
    )

    print(
        "✅ 19 BASE NUMERIC FEATURES VERIFIED"
    )

    print(
        "✅ 12 ACTION-INDICATOR FEATURES INCLUDED"
    )

    print(
        "✅ 31 PREPROCESS NUMERIC FEATURES VERIFIED"
    )

    print(
        "✅ 10 CATEGORICAL FEATURES VERIFIED"
    )

    print(
        "✅ EXACT 41-COLUMN RAW FEATURE CONTRACT RESTORED"
    )

    print(
        "✅ ALL FEATURE-BUILDER DEPENDENCIES NOW USABLE"
    )

    print(
        "✅ SECTION 3A.4B COMPLETE"
    )

    print(
        "⚠️ R3 MODEL REMAINS FROZEN"
    )

    print(
        "⚠️ DO NOT BENCHMARK YET"
    )

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print(
        "⚠️ AUTHORITATIVE SCHEMA LOAD REQUIRES ONE MORE TARGETED REPAIR"
    )

    print(
        "Remaining unusable dependencies:",
        remaining_unusable_3a4b,
    )

    print(
        "⚠️ DO NOT BENCHMARK YET"
    )

    print("=" * 100)

====================================================================================================
SECTION 3A.4B — LOAD AUTHORITATIVE NOTEBOOK 53 R3 FEATURE SCHEMA
====================================================================================================

AUTHORITATIVE SCHEMA OBJECTS
----------------------------------------------------------------------------------------------------
POLICY_ACTION_CLASSES
action_feature_name
training_active_card_action_map
legality_training_numeric_features
legality_training_categorical_features
PREPROCESS_NUMERIC_FEATURES
PREPROCESS_CATEGORICAL_FEATURES
PREPROCESS_RAW_FEATURES

AUTHORITATIVE NOTEBOOK 53 SCHEMA INVENTORY
----------------------------------------------------------------------------------------------------

,name,found,source_type,line_number,end_line
0,POLICY_ACTION_CLASSES,True,ASSIGNMENT,4275,4282
1,action_feature_name,True,FUNCTION,4285,4300
2,training_active_card_action_map,True,ASSIGNMENT,8054,8054
3,legality_training_numeric_features,True,ASSIGNMENT,8131,8151
4,legality_training_categorical_features,True,ASSIGNMENT,8162,8173
5,PREPROCESS_NUMERIC_FEATURES,True,ASSIGNMENT,10561,10563
6,PREPROCESS_CATEGORICAL_FEATURES,True,ASSIGNMENT,10565,10567
7,PREPROCESS_RAW_FEATURES,True,ASSIGNMENT,10569,10572

EXACT PREPROCESS SCHEMA SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
PREPROCESS_NUMERIC_FEATURES — line 10561
----------------------------------------------------------------------------------------------------
PREPROCESS_NUMERIC_FEATURES = list(
    legality_training_numeric_features
)

====================================================================================================
PREPROCESS_CATEGORICAL_FEATURES — line 10565
----------------------------------------------------------------------------------------------------
PREPROCESS_CATEGORICAL_FEATURES = list(
    legality_training_categorical_features
)

====================================================================================================
PREPROCESS_RAW_FEATURES — line 10569
----------------------------------------------------------------------------------------------------
PREPROCESS_RAW_FEATURES = (
    PREPROCESS_NUMERIC_FEATURES
    + PREPROCESS_CATEGORICAL_FEATURES
)

INTERMEDIATE SCHEMA VALUES CLEARED
----------------------------------------------------------------------------------------------------
Only authoritative Notebook 53 schema objects were cleared for exact reload.

AUTHORITATIVE SCHEMA LOAD RESULTS
----------------------------------------------------------------------------------------------------

,name,line_number,loaded,object_type,error
0,POLICY_ACTION_CLASSES,4275,True,list,None
1,action_feature_name,4285,True,function,None
2,training_active_card_action_map,8054,True,dict,None
3,legality_training_numeric_features,8131,True,list,None
4,legality_training_categorical_features,8162,True,list,None
5,PREPROCESS_NUMERIC_FEATURES,10561,True,list,None
6,PREPROCESS_CATEGORICAL_FEATURES,10565,True,list,None
7,PREPROCESS_RAW_FEATURES,10569,True,list,None

AUTHORITATIVE OBJECT TYPES
----------------------------------------------------------------------------------------------------

                                     name  available object_type  is_none
0                   POLICY_ACTION_CLASSES       True        list    False
1                     action_feature_name       True    function    False
2         training_active_card_action_map       True        dict    False
3      legality_training_numeric_features       True        list    False
4  legality_training_categorical_features       True        list    False
5             PREPROCESS_NUMERIC_FEATURES       True        list    False
6         PREPROCESS_CATEGORICAL_FEATURES       True        list    False
7                 PREPROCESS_RAW_FEATURES       True        list    False

AUTHORITATIVE R3 FEATURE COUNTS
----------------------------------------------------------------------------------------------------
Policy action classes        : 6
Legality numeric features    : 19
Legality categorical features: 10
Preprocess numeric features  : 19
Preprocess categorical       : 10
Total raw features           : 29

POLICY ACTION CLASSES
----------------------------------------------------------------------------------------------------
01. Ascension
02. Bind Down
03. Live Coal
04. Pass
05. Quick Attack
06. Tuck Tail

PREPROCESS NUMERIC FEATURES
----------------------------------------------------------------------------------------------------
01. turn_number
02. player_energy
03. opponent_energy
04. player_damage
05. opponent_damage
06. prize_cards_remaining
07. hand_size
08. recomputed_legal_move_count
09. acting_energy
10. defending_energy
11. energy_difference
12. absolute_energy_difference
13. acting_damage
14. defending_damage
15. damage_difference
16. absolute_damage_difference
17. single_legal_move_flag
18. multi_legal_move_flag
19. model_choice_required_flag

PREPROCESS CATEGORICAL FEATURES
----------------------------------------------------------------------------------------------------
01. current_side
02. side_mode
03. player_card
04. opponent_card
05. active_card
06. inactive_card
07. legal_move_signature
08. battle_phase
09. energy_band
10. damage_band

R3 BUILDER DEPENDENCY RECHECK
----------------------------------------------------------------------------------------------------

                                dependency  available object_type  usable
0                    POLICY_ACTION_CLASSES       True        list    True
1                  PREPROCESS_RAW_FEATURES       True        list    True
2                      action_feature_name       True    function    True
3                 canonical_move_signature       True    function    True
4                     classify_damage_band       True    function    True
5                     classify_energy_band       True    function    True
6                      classify_turn_phase       True    function    True
7                        extract_move_name       True    function    True
8                      get_attached_energy       True    function    True
9                            get_card_name       True    function    True
10                      get_pokemon_damage       True    function    True
11                         get_state_value       True    function    True
12  legality_training_categorical_features       True        list    True
13      legality_training_numeric_features       True        list    True
14                   normalize_action_name       True    function    True
15         training_active_card_action_map       True        dict    True

SECTION 3A.4B VALIDATION
----------------------------------------------------------------------------------------------------

                                 validation    observed    expected  passed
0                        six policy classes           6           6    True
1              19 legality numeric features          19          19    True
2          10 legality categorical features          10          10    True
3            31 preprocess numeric features          19          31   False
4        10 preprocess categorical features          10          10    True
5                   41 raw feature contract          29          41   False
6              action_feature_name callable        True        True    True
7         training action map is dictionary        dict        dict    True
8  all original builder dependencies usable  ALL USABLE  ALL USABLE    True

====================================================================================================
⚠️ AUTHORITATIVE SCHEMA LOAD REQUIRES ONE MORE TARGETED REPAIR
Remaining unusable dependencies: []
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [33]:
# ==========================================================================================
# SECTION 3A.4C — RECOVER EXACT 12 ACTION-INDICATOR FEATURES AND RESTORE 41-COLUMN SCHEMA
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.4C — RECOVER EXACT 12 ACTION-INDICATOR FEATURES AND RESTORE 41-COLUMN SCHEMA")
print("=" * 100)

import ast
import pandas as pd


# ==========================================================================================
# 1. Search Notebook 54 and Notebook 59 source for exact action-indicator feature lists
# ==========================================================================================

SOURCE_CANDIDATES_3A4C = [
    (
        "Notebook 54",
        source_54_3a2,
    ),
    (
        "Notebook 59",
        source_3a,
    ),
]


indicator_candidates_3a4c = []


for source_name, source_text in SOURCE_CANDIDATES_3A4C:

    source_tree = ast.parse(
        source_text
    )

    for node in ast.walk(
        source_tree
    ):

        if not isinstance(
            node,
            (
                ast.Assign,
                ast.AnnAssign,
            ),
        ):
            continue

        source_segment = ast.get_source_segment(
            source_text,
            node,
        )

        if not source_segment:
            continue

        if (
            "is_legal__"
            not in source_segment
            and
            "active_card_can_use__"
            not in source_segment
        ):
            continue


        # ------------------------------------------------------------------
        # Recover assigned names
        # ------------------------------------------------------------------

        assigned_names = []

        targets = (
            node.targets
            if isinstance(
                node,
                ast.Assign,
            )
            else [
                node.target
            ]
        )

        for target in targets:

            if isinstance(
                target,
                ast.Name,
            ):

                assigned_names.append(
                    target.id
                )


        indicator_candidates_3a4c.append(
            {
                "source":
                    source_name,

                "line_number":
                    getattr(
                        node,
                        "lineno",
                        None,
                    ),

                "assigned_names":
                    assigned_names,

                "source_code":
                    source_segment,
            }
        )


section3a4c_candidate_df = pd.DataFrame(
    indicator_candidates_3a4c
)


print("\nACTION-INDICATOR SOURCE CANDIDATES")
print("-" * 100)

display(
    section3a4c_candidate_df[
        [
            "source",
            "line_number",
            "assigned_names",
        ]
    ]
)


# ==========================================================================================
# 2. Print exact candidate source
# ==========================================================================================

print("\nEXACT ACTION-INDICATOR SOURCE")
print("-" * 100)


for index, row in (
    section3a4c_candidate_df
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        f"CANDIDATE {index + 1}"
    )

    print(
        "Source:",
        row[
            "source"
        ],
    )

    print(
        "Line:",
        row[
            "line_number"
        ],
    )

    print("-" * 100)

    print(
        row[
            "source_code"
        ]
    )


# ==========================================================================================
# 3. Recover exact indicator names directly from source text
#
# We extract literal feature names only.
# No names are invented here.
# ==========================================================================================

indicator_names_3a4c = []


for _, row in (
    section3a4c_candidate_df
    .iterrows()
):

    source_code = str(
        row[
            "source_code"
        ]
    )

    candidate_tree = ast.parse(
        source_code
    )

    for node in ast.walk(
        candidate_tree
    ):

        if not isinstance(
            node,
            ast.Constant,
        ):
            continue

        if not isinstance(
            node.value,
            str,
        ):
            continue

        value = node.value

        if (
            value.startswith(
                "is_legal__"
            )
            or
            value.startswith(
                "active_card_can_use__"
            )
        ):

            if (
                value
                not in indicator_names_3a4c
            ):

                indicator_names_3a4c.append(
                    value
                )


print("\nRECOVERED ACTION-INDICATOR FEATURES")
print("-" * 100)

for index, feature_name in enumerate(
    indicator_names_3a4c,
    start=1,
):

    print(
        f"{index:02d}. {feature_name}"
    )


# ==========================================================================================
# 4. If the source constructed names dynamically, recover them using the exact
#    authoritative action classes + action_feature_name() contract.
#
# This is not a fallback schema invention; it follows the production naming contract.
# ==========================================================================================

if len(
    indicator_names_3a4c
) != 12:

    print(
        "\nLiteral extraction did not yield all 12 names."
    )

    print(
        "Reconstructing names from exact production naming functions..."
    )

    indicator_names_3a4c = []


    for action_name in POLICY_ACTION_CLASSES:

        feature_suffix = (
            action_feature_name(
                action_name
            )
        )

        indicator_names_3a4c.extend(
            [
                (
                    "is_legal__"
                    + feature_suffix
                ),
                (
                    "active_card_can_use__"
                    + feature_suffix
                ),
            ]
        )


# ==========================================================================================
# 5. Validate exact 12-feature structure
# ==========================================================================================

assert (
    len(
        indicator_names_3a4c
    )
    == 12
), (
    "Expected exactly 12 action-indicator features."
)


assert (
    len(
        set(
            indicator_names_3a4c
        )
    )
    == 12
), (
    "Duplicate action-indicator features detected."
)


ACTION_INDICATOR_FEATURES_3A4C = list(
    indicator_names_3a4c
)


# ==========================================================================================
# 6. Display action ↔ feature mapping
# ==========================================================================================

action_indicator_mapping_rows_3a4c = []


for action_name in POLICY_ACTION_CLASSES:

    suffix = action_feature_name(
        action_name
    )

    action_indicator_mapping_rows_3a4c.append(
        {
            "action":
                action_name,

            "legal_feature":
                "is_legal__"
                + suffix,

            "active_card_feature":
                "active_card_can_use__"
                + suffix,
        }
    )


section3a4c_mapping_df = pd.DataFrame(
    action_indicator_mapping_rows_3a4c
)


print("\nACTION INDICATOR MAPPING")
print("-" * 100)

display(
    section3a4c_mapping_df
)


# ==========================================================================================
# 7. Restore exact Notebook 59 / Notebook 54 live raw schema
#
# 19 base numeric
# + 12 action indicator numeric
# = 31 numeric
#
# + 10 categorical
# = 41 raw
# ==========================================================================================

PREPROCESS_NUMERIC_FEATURES = (
    list(
        legality_training_numeric_features
    )
    +
    list(
        ACTION_INDICATOR_FEATURES_3A4C
    )
)


PREPROCESS_CATEGORICAL_FEATURES = list(
    legality_training_categorical_features
)


PREPROCESS_RAW_FEATURES = (
    PREPROCESS_NUMERIC_FEATURES
    +
    PREPROCESS_CATEGORICAL_FEATURES
)


# ==========================================================================================
# 8. Schema counts
# ==========================================================================================

base_numeric_count_3a4c = len(
    legality_training_numeric_features
)

indicator_count_3a4c = len(
    ACTION_INDICATOR_FEATURES_3A4C
)

numeric_count_3a4c = len(
    PREPROCESS_NUMERIC_FEATURES
)

categorical_count_3a4c = len(
    PREPROCESS_CATEGORICAL_FEATURES
)

raw_count_3a4c = len(
    PREPROCESS_RAW_FEATURES
)


print("\nRESTORED LIVE FEATURE COUNTS")
print("-" * 100)

print(
    "Base numeric features       :",
    base_numeric_count_3a4c,
)

print(
    "Action indicator features   :",
    indicator_count_3a4c,
)

print(
    "Preprocess numeric features :",
    numeric_count_3a4c,
)

print(
    "Categorical features        :",
    categorical_count_3a4c,
)

print(
    "Total raw features          :",
    raw_count_3a4c,
)


# ==========================================================================================
# 9. Print exact restored raw schema
# ==========================================================================================

print("\nRESTORED 41-COLUMN RAW FEATURE SCHEMA")
print("-" * 100)


for index, feature_name in enumerate(
    PREPROCESS_RAW_FEATURES,
    start=1,
):

    print(
        f"{index:02d}. {feature_name}"
    )


# ==========================================================================================
# 10. Rebind schema inside the recovered builder globals
#
# Since the recovered function was created with globals(), these variables are
# automatically visible. We explicitly verify that fact.
# ==========================================================================================

builder_globals_3a4c = (
    build_legality_aware_feature_row
    .__globals__
)


builder_schema_binding_rows_3a4c = []


for name in [
    "POLICY_ACTION_CLASSES",
    "PREPROCESS_NUMERIC_FEATURES",
    "PREPROCESS_CATEGORICAL_FEATURES",
    "PREPROCESS_RAW_FEATURES",
]:

    builder_schema_binding_rows_3a4c.append(
        {
            "name":
                name,

            "available_to_builder":
                name
                in builder_globals_3a4c,

            "same_object":
                (
                    builder_globals_3a4c.get(
                        name
                    )
                    is globals().get(
                        name
                    )
                ),
        }
    )


section3a4c_binding_df = pd.DataFrame(
    builder_schema_binding_rows_3a4c
)


print("\nBUILDER GLOBAL SCHEMA BINDING")
print("-" * 100)

display(
    section3a4c_binding_df
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3a4c_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "six action classes",

            "observed":
                len(
                    POLICY_ACTION_CLASSES
                ),

            "expected":
                6,

            "passed":
                len(
                    POLICY_ACTION_CLASSES
                )
                == 6,
        },

        {
            "validation":
                "19 base numeric features",

            "observed":
                base_numeric_count_3a4c,

            "expected":
                19,

            "passed":
                base_numeric_count_3a4c
                == 19,
        },

        {
            "validation":
                "12 action indicator features",

            "observed":
                indicator_count_3a4c,

            "expected":
                12,

            "passed":
                indicator_count_3a4c
                == 12,
        },

        {
            "validation":
                "31 preprocess numeric features",

            "observed":
                numeric_count_3a4c,

            "expected":
                31,

            "passed":
                numeric_count_3a4c
                == 31,
        },

        {
            "validation":
                "10 categorical features",

            "observed":
                categorical_count_3a4c,

            "expected":
                10,

            "passed":
                categorical_count_3a4c
                == 10,
        },

        {
            "validation":
                "41 raw feature contract",

            "observed":
                raw_count_3a4c,

            "expected":
                41,

            "passed":
                raw_count_3a4c
                == 41,
        },

        {
            "validation":
                "builder sees restored schema",

            "observed":
                bool(
                    section3a4c_binding_df[
                        "available_to_builder"
                    ].all()
                ),

            "expected":
                True,

            "passed":
                bool(
                    section3a4c_binding_df[
                        "available_to_builder"
                    ].all()
                ),
        },
    ]
)


print("\nSECTION 3A.4C VALIDATION")
print("-" * 100)

display(
    section3a4c_validation_df
)


assert (
    section3a4c_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ NOTEBOOK 53 BASE 29-COLUMN SCHEMA PRESERVED")
print("✅ EXACT SIX R3 ACTION CLASSES PRESERVED")
print("✅ 12 LEGALITY/ACTION INDICATOR FEATURES RESTORED")
print("✅ 19 + 12 = 31 NUMERIC FEATURES")
print("✅ 31 + 10 = 41 RAW FEATURES")
print("✅ R3 FEATURE BUILDER GLOBAL SCHEMA UPDATED")
print("✅ EXACT NOTEBOOK 59 LIVE CONTRACT RESTORED")
print("✅ SECTION 3A.4C COMPLETE")
print("⚠️ R3 MODEL REMAINS FROZEN — NO RETRAINING")
print("⚠️ DO NOT BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3A.4C — RECOVER EXACT 12 ACTION-INDICATOR FEATURES AND RESTORE 41-COLUMN SCHEMA
====================================================================================================

ACTION-INDICATOR SOURCE CANDIDATES
----------------------------------------------------------------------------------------------------

        source  line_number          assigned_names
0  Notebook 54        70388     [legal_flag_column]
1  Notebook 54        70396  [compatibility_column]

EXACT ACTION-INDICATOR SOURCE
----------------------------------------------------------------------------------------------------

====================================================================================================
CANDIDATE 1
Source: Notebook 54
Line: 70388
----------------------------------------------------------------------------------------------------
legal_flag_column = (
            "is_legal__"
            +
            action_feature_name(
                action_name
            )
        )

====================================================================================================
CANDIDATE 2
Source: Notebook 54
Line: 70396
----------------------------------------------------------------------------------------------------
compatibility_column = (
            "active_card_can_use__"
            +
            action_feature_name(
                action_name
            )
        )

RECOVERED ACTION-INDICATOR FEATURES
----------------------------------------------------------------------------------------------------
01. is_legal__
02. active_card_can_use__

Literal extraction did not yield all 12 names.
Reconstructing names from exact production naming functions...

ACTION INDICATOR MAPPING
----------------------------------------------------------------------------------------------------

         action           legal_feature                active_card_feature
0     Ascension     is_legal__ascension     active_card_can_use__ascension
1     Bind Down     is_legal__bind_down     active_card_can_use__bind_down
2     Live Coal     is_legal__live_coal     active_card_can_use__live_coal
3          Pass          is_legal__pass          active_card_can_use__pass
4  Quick Attack  is_legal__quick_attack  active_card_can_use__quick_attack
5     Tuck Tail     is_legal__tuck_tail     active_card_can_use__tuck_tail

RESTORED LIVE FEATURE COUNTS
----------------------------------------------------------------------------------------------------
Base numeric features       : 19
Action indicator features   : 12
Preprocess numeric features : 31
Categorical features        : 10
Total raw features          : 41

RESTORED 41-COLUMN RAW FEATURE SCHEMA
----------------------------------------------------------------------------------------------------
01. turn_number
02. player_energy
03. opponent_energy
04. player_damage
05. opponent_damage
06. prize_cards_remaining
07. hand_size
08. recomputed_legal_move_count
09. acting_energy
10. defending_energy
11. energy_difference
12. absolute_energy_difference
13. acting_damage
14. defending_damage
15. damage_difference
16. absolute_damage_difference
17. single_legal_move_flag
18. multi_legal_move_flag
19. model_choice_required_flag
20. is_legal__ascension
21. active_card_can_use__ascension
22. is_legal__bind_down
23. active_card_can_use__bind_down
24. is_legal__live_coal
25. active_card_can_use__live_coal
26. is_legal__pass
27. active_card_can_use__pass
28. is_legal__quick_attack
29. active_card_can_use__quick_attack
30. is_legal__tuck_tail
31. active_card_can_use__tuck_tail
32. current_side
33. side_mode
34. player_card
35. opponent_card
36. active_card
37. inactive_card
38. legal_move_signature
39. battle_phase
40. energy_band
41. damage_band

BUILDER GLOBAL SCHEMA BINDING
----------------------------------------------------------------------------------------------------

                              name  available_to_builder  same_object
0            POLICY_ACTION_CLASSES                  True         True
1      PREPROCESS_NUMERIC_FEATURES                  True         True
2  PREPROCESS_CATEGORICAL_FEATURES                  True         True
3          PREPROCESS_RAW_FEATURES                  True         True

SECTION 3A.4C VALIDATION
----------------------------------------------------------------------------------------------------

                       validation observed expected  passed
0              six action classes        6        6    True
1        19 base numeric features       19       19    True
2    12 action indicator features       12       12    True
3  31 preprocess numeric features       31       31    True
4         10 categorical features       10       10    True
5         41 raw feature contract       41       41    True
6    builder sees restored schema     True     True    True

====================================================================================================
✅ NOTEBOOK 53 BASE 29-COLUMN SCHEMA PRESERVED
✅ EXACT SIX R3 ACTION CLASSES PRESERVED
✅ 12 LEGALITY/ACTION INDICATOR FEATURES RESTORED
✅ 19 + 12 = 31 NUMERIC FEATURES
✅ 31 + 10 = 41 RAW FEATURES
✅ R3 FEATURE BUILDER GLOBAL SCHEMA UPDATED
✅ EXACT NOTEBOOK 59 LIVE CONTRACT RESTORED
✅ SECTION 3A.4C COMPLETE
⚠️ R3 MODEL REMAINS FROZEN — NO RETRAINING
⚠️ DO NOT BENCHMARK YET
====================================================================================================

In [34]:
# ==========================================================================================
# SECTION 3A.5 — EXECUTE RESTORED R3 FEATURE BUILDER AND VALIDATE 41-COLUMN RAW OUTPUT
# ==========================================================================================

print("=" * 100)
print("SECTION 3A.5 — EXECUTE RESTORED R3 FEATURE BUILDER AND VALIDATE 41-COLUMN RAW OUTPUT")
print("=" * 100)

from pathlib import Path
import sys
import pandas as pd


# ==========================================================================================
# 1. Ensure project package is importable
# ==========================================================================================

PROJECT_ROOT_STR_3A5 = str(
    PROJECT_ROOT
)

if PROJECT_ROOT_STR_3A5 not in sys.path:

    sys.path.insert(
        0,
        PROJECT_ROOT_STR_3A5,
    )


# ==========================================================================================
# 2. Import genuine project BattleState contract and production legal-move resolver
# ==========================================================================================

from src.battle_state import (
    BattleState,
    PlayerState,
    PokemonState,
)

from src.legal_moves import (
    get_current_legal_moves,
)


print("\nPROJECT COMPONENTS")
print("-" * 100)

print(
    "BattleState resolver      :",
    BattleState,
)

print(
    "Legal move resolver       :",
    get_current_legal_moves,
)

print(
    "Feature builder callable  :",
    callable(
        build_legality_aware_feature_row
    ),
)


# ==========================================================================================
# 3. Use real card dictionaries already recovered from the historical project
#
# Prefer the exact Notebook 48 tournament templates recovered earlier.
# No new cards are fabricated.
# ==========================================================================================

assert (
    "TOURNAMENT_CARD_TEMPLATES_2F2"
    in globals()
), (
    "Historical tournament card templates are missing. "
    "Run Section 2F.2 first."
)


assert (
    len(
        TOURNAMENT_CARD_TEMPLATES_2F2
    )
    >= 2
)


player_card_3a5 = dict(
    TOURNAMENT_CARD_TEMPLATES_2F2[
        0
    ]
)

opponent_card_3a5 = dict(
    TOURNAMENT_CARD_TEMPLATES_2F2[
        1
    ]
)


print("\nTEST CARDS")
print("-" * 100)

print(
    "Player card   :",
    player_card_3a5.get(
        "name",
        "UNKNOWN",
    ),
)

print(
    "Opponent card :",
    opponent_card_3a5.get(
        "name",
        "UNKNOWN",
    ),
)


# ==========================================================================================
# 4. Build genuine project BattleState
#
# We intentionally use enough energy to expose more than one potential move where possible.
# ==========================================================================================

player_pokemon_3a5 = PokemonState(
    card=player_card_3a5,
    current_hp=float(
        player_card_3a5[
            "hp"
        ]
    ),
    attached_energy=3,
    damage=0.0,
    is_active=True,
)


opponent_pokemon_3a5 = PokemonState(
    card=opponent_card_3a5,
    current_hp=float(
        opponent_card_3a5[
            "hp"
        ]
    ),
    attached_energy=3,
    damage=0.0,
    is_active=True,
)


player_state_3a5 = PlayerState(
    active=player_pokemon_3a5,
    bench=[],
    prize_cards_remaining=6,
    hand_size=7,
)


opponent_state_3a5 = PlayerState(
    active=opponent_pokemon_3a5,
    bench=[],
    prize_cards_remaining=6,
    hand_size=7,
)


battle_state_3a5 = BattleState(
    player=player_state_3a5,
    opponent=opponent_state_3a5,
    turn_number=3,
    current_player="Player",
)


print("\nLIVE TEST BATTLE STATE")
print("-" * 100)

print(
    "Type            :",
    type(
        battle_state_3a5
    ).__name__,
)

print(
    "Turn            :",
    battle_state_3a5.turn_number,
)

print(
    "Current side    :",
    battle_state_3a5.current_player,
)

print(
    "Player energy   :",
    battle_state_3a5.player.active.attached_energy,
)

print(
    "Opponent energy :",
    battle_state_3a5.opponent.active.attached_energy,
)


# ==========================================================================================
# 5. Resolve genuine legal moves
# ==========================================================================================

legal_moves_3a5 = get_current_legal_moves(
    battle_state_3a5
)


print("\nPRODUCTION LEGAL MOVES")
print("-" * 100)

print(
    "Legal move count:",
    len(
        legal_moves_3a5
    ),
)


for index, move in enumerate(
    legal_moves_3a5,
    start=1,
):

    print(
        f"{index:02d}.",
        move,
    )


assert (
    len(
        legal_moves_3a5
    )
    >= 1
), (
    "Production resolver returned no legal moves."
)


# ==========================================================================================
# 6. Execute exact recovered R3 production feature builder
# ==========================================================================================

print("\nCALLING build_legality_aware_feature_row()")
print("-" * 100)


raw_feature_row_3a5 = (
    build_legality_aware_feature_row(
        battle_state_3a5,
        legal_moves_3a5,
        "PRESERVE",
    )
)


print(
    "Builder returned successfully."
)


# ==========================================================================================
# 7. Inspect returned object
# ==========================================================================================

print("\nRAW FEATURE ROW")
print("-" * 100)

print(
    "Type  :",
    type(
        raw_feature_row_3a5
    ).__name__,
)

print(
    "Shape :",
    raw_feature_row_3a5.shape,
)


display(
    raw_feature_row_3a5
)


# ==========================================================================================
# 8. Exact raw-schema comparison
# ==========================================================================================

observed_columns_3a5 = (
    raw_feature_row_3a5
    .columns
    .tolist()
)

expected_columns_3a5 = list(
    PREPROCESS_RAW_FEATURES
)


missing_columns_3a5 = [
    column
    for column in expected_columns_3a5
    if column not in observed_columns_3a5
]


unexpected_columns_3a5 = [
    column
    for column in observed_columns_3a5
    if column not in expected_columns_3a5
]


column_order_matches_3a5 = (
    observed_columns_3a5
    ==
    expected_columns_3a5
)


print("\nRAW SCHEMA COMPARISON")
print("-" * 100)

print(
    "Observed column count :",
    len(
        observed_columns_3a5
    ),
)

print(
    "Expected column count :",
    len(
        expected_columns_3a5
    ),
)

print(
    "Missing columns       :",
    missing_columns_3a5,
)

print(
    "Unexpected columns    :",
    unexpected_columns_3a5,
)

print(
    "Exact column order    :",
    column_order_matches_3a5,
)


# ==========================================================================================
# 9. Inspect action-indicator portion
# ==========================================================================================

action_indicator_output_3a5 = (
    raw_feature_row_3a5[
        ACTION_INDICATOR_FEATURES_3A4C
    ]
    .copy()
)


print("\nACTION-INDICATOR OUTPUT")
print("-" * 100)

display(
    action_indicator_output_3a5
)


# ==========================================================================================
# 10. Inspect categorical portion
# ==========================================================================================

categorical_output_3a5 = (
    raw_feature_row_3a5[
        PREPROCESS_CATEGORICAL_FEATURES
    ]
    .copy()
)


print("\nCATEGORICAL OUTPUT")
print("-" * 100)

display(
    categorical_output_3a5
)


# ==========================================================================================
# 11. Structural integrity checks
# ==========================================================================================

duplicate_columns_3a5 = (
    raw_feature_row_3a5
    .columns[
        raw_feature_row_3a5
        .columns
        .duplicated()
    ]
    .tolist()
)


null_count_3a5 = int(
    raw_feature_row_3a5
    .isna()
    .sum()
    .sum()
)


print("\nSTRUCTURAL INTEGRITY")
print("-" * 100)

print(
    "Duplicate columns :",
    duplicate_columns_3a5,
)

print(
    "Null cells        :",
    null_count_3a5,
)


# ==========================================================================================
# 12. Validation
# ==========================================================================================

section3a5_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "genuine BattleState created",

            "observed":
                type(
                    battle_state_3a5
                ).__name__,

            "expected":
                "BattleState",

            "passed":
                isinstance(
                    battle_state_3a5,
                    BattleState,
                ),
        },

        {
            "validation":
                "production legal moves generated",

            "observed":
                len(
                    legal_moves_3a5
                ),

            "expected":
                ">= 1",

            "passed":
                len(
                    legal_moves_3a5
                )
                >= 1,
        },

        {
            "validation":
                "builder returned DataFrame",

            "observed":
                type(
                    raw_feature_row_3a5
                ).__name__,

            "expected":
                "DataFrame",

            "passed":
                isinstance(
                    raw_feature_row_3a5,
                    pd.DataFrame,
                ),
        },

        {
            "validation":
                "exact raw feature shape",

            "observed":
                raw_feature_row_3a5.shape,

            "expected":
                (1, 41),

            "passed":
                raw_feature_row_3a5.shape
                ==
                (1, 41),
        },

        {
            "validation":
                "41 expected columns present",

            "observed":
                len(
                    observed_columns_3a5
                ),

            "expected":
                41,

            "passed":
                (
                    len(
                        observed_columns_3a5
                    )
                    == 41
                    and
                    not missing_columns_3a5
                    and
                    not unexpected_columns_3a5
                ),
        },

        {
            "validation":
                "exact raw column order",

            "observed":
                column_order_matches_3a5,

            "expected":
                True,

            "passed":
                column_order_matches_3a5,
        },

        {
            "validation":
                "12 action indicators returned",

            "observed":
                action_indicator_output_3a5.shape[
                    1
                ],

            "expected":
                12,

            "passed":
                action_indicator_output_3a5.shape[
                    1
                ]
                == 12,
        },

        {
            "validation":
                "10 categorical features returned",

            "observed":
                categorical_output_3a5.shape[
                    1
                ],

            "expected":
                10,

            "passed":
                categorical_output_3a5.shape[
                    1
                ]
                == 10,
        },

        {
            "validation":
                "no duplicate columns",

            "observed":
                duplicate_columns_3a5,

            "expected":
                [],

            "passed":
                len(
                    duplicate_columns_3a5
                )
                == 0,
        },
    ]
)


print("\nSECTION 3A.5 VALIDATION")
print("-" * 100)

display(
    section3a5_validation_df
)


# ==========================================================================================
# 13. Final gate
# ==========================================================================================

if section3a5_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print("✅ GENUINE PROJECT BattleState CREATED")
    print("✅ PRODUCTION LEGAL-MOVE RESOLVER EXECUTED")
    print("✅ EXACT R3 FEATURE BUILDER EXECUTED")
    print("✅ ONE 41-COLUMN RAW FEATURE ROW RETURNED")
    print("✅ 12 ACTION-INDICATOR FEATURES VERIFIED")
    print("✅ 10 CATEGORICAL FEATURES VERIFIED")
    print("✅ EXACT RAW COLUMN ORDER VERIFIED")
    print("✅ SECTION 3A.5 COMPLETE")

    print("⚠️ R3 MODEL REMAINS FROZEN")
    print("⚠️ NO RETRAINING")
    print("⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET")

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print("⚠️ SECTION 3A.5 RAW FEATURE CONTRACT NEEDS TARGETED REPAIR")
    print("⚠️ DO NOT LOAD THE MODEL OR BENCHMARK YET")

    print("=" * 100)

====================================================================================================
SECTION 3A.5 — EXECUTE RESTORED R3 FEATURE BUILDER AND VALIDATE 41-COLUMN RAW OUTPUT
====================================================================================================

PROJECT COMPONENTS
----------------------------------------------------------------------------------------------------
BattleState resolver      : <class 'src.battle_state.BattleState'>
Legal move resolver       : <function get_current_legal_moves at 0x000001422125FF60>
Feature builder callable  : True

TEST CARDS
----------------------------------------------------------------------------------------------------
Player card   : Pikachu
Opponent card : Charmander

LIVE TEST BATTLE STATE
----------------------------------------------------------------------------------------------------
Type            : BattleState
Turn            : 3
Current side    : Player
Player energy   : 3
Opponent energy : 3

PRODUCTION LEGAL MOVES
----------------------------------------------------------------------------------------------------
Legal move count: 2
01. {'name': 'Quick Attack', 'damage': 30.0, 'energy_cost': 1, 'effect': None}
02. {'name': 'Thunderbolt', 'damage': 90.0, 'energy_cost': 2, 'effect': None}

CALLING build_legality_aware_feature_row()
----------------------------------------------------------------------------------------------------
Builder returned successfully.

RAW FEATURE ROW
----------------------------------------------------------------------------------------------------
Type  : DataFrame
Shape : (1, 41)

,turn_number,player_energy,opponent_energy,player_damage,opponent_damage,prize_cards_remaining,hand_size,recomputed_legal_move_count,acting_energy,defending_energy,...,current_side,side_mode,player_card,opponent_card,active_card,inactive_card,legal_move_signature,battle_phase,energy_band,damage_band
0,3.0,3.0,3.0,0.0,0.0,6.0,7.0,2.0,3.0,3.0,...,Player,PRESERVE,Pikachu,Charmander,Pikachu,Charmander,Quick Attack | Thunderbolt,EARLY_MID,THREE,NONE

RAW SCHEMA COMPARISON
----------------------------------------------------------------------------------------------------
Observed column count : 41
Expected column count : 41
Missing columns       : []
Unexpected columns    : []
Exact column order    : True

ACTION-INDICATOR OUTPUT
----------------------------------------------------------------------------------------------------

,is_legal__ascension,active_card_can_use__ascension,is_legal__bind_down,active_card_can_use__bind_down,is_legal__live_coal,active_card_can_use__live_coal,is_legal__pass,active_card_can_use__pass,is_legal__quick_attack,active_card_can_use__quick_attack,is_legal__tuck_tail,active_card_can_use__tuck_tail
0,0,0,0,0,0,0,0,0,1,0,0,0

CATEGORICAL OUTPUT
----------------------------------------------------------------------------------------------------

,current_side,side_mode,player_card,opponent_card,active_card,inactive_card,legal_move_signature,battle_phase,energy_band,damage_band
0,Player,PRESERVE,Pikachu,Charmander,Pikachu,Charmander,Quick Attack | Thunderbolt,EARLY_MID,THREE,NONE

STRUCTURAL INTEGRITY
----------------------------------------------------------------------------------------------------
Duplicate columns : []
Null cells        : 0

SECTION 3A.5 VALIDATION
----------------------------------------------------------------------------------------------------

                         validation     observed     expected  passed
0       genuine BattleState created  BattleState  BattleState    True
1  production legal moves generated            2         >= 1    True
2        builder returned DataFrame    DataFrame    DataFrame    True
3           exact raw feature shape      (1, 41)      (1, 41)    True
4       41 expected columns present           41           41    True
5            exact raw column order         True         True    True
6     12 action indicators returned           12           12    True
7  10 categorical features returned           10           10    True
8              no duplicate columns           []           []    True

====================================================================================================
✅ GENUINE PROJECT BattleState CREATED
✅ PRODUCTION LEGAL-MOVE RESOLVER EXECUTED
✅ EXACT R3 FEATURE BUILDER EXECUTED
✅ ONE 41-COLUMN RAW FEATURE ROW RETURNED
✅ 12 ACTION-INDICATOR FEATURES VERIFIED
✅ 10 CATEGORICAL FEATURES VERIFIED
✅ EXACT RAW COLUMN ORDER VERIFIED
✅ SECTION 3A.5 COMPLETE
⚠️ R3 MODEL REMAINS FROZEN
⚠️ NO RETRAINING
⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET
====================================================================================================

In [11]:
# ==========================================================================================
# SECTION 3B — RECOVER FROZEN R3 MODEL AND EXACT 46-FEATURE ENCODER
# ==========================================================================================

print("=" * 100)
print("SECTION 3B — RECOVER FROZEN R3 MODEL AND EXACT 46-FEATURE ENCODER")
print("=" * 100)

from pathlib import Path
import ast
import joblib
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require successful raw-feature validation
# ==========================================================================================

assert (
    "raw_feature_row_3a5"
    in globals()
), (
    "Section 3A.5 output is missing."
)

assert (
    raw_feature_row_3a5.shape
    ==
    (1, 41)
), (
    "Raw feature contract is not (1, 41)."
)


# ==========================================================================================
# 2. Recover exact Notebook 59 encoder definition
# ==========================================================================================

ENCODER_NAME_3B = (
    "encode_r3_feature_row"
)

encoder_node_3b = None


for node in tree_3a.body:

    if (
        isinstance(
            node,
            ast.FunctionDef,
        )
        and
        node.name
        ==
        ENCODER_NAME_3B
    ):
        encoder_node_3b = node
        break


assert (
    encoder_node_3b
    is not None
), (
    "encode_r3_feature_row() was not found in Notebook 59 source."
)


encoder_source_3b = ast.get_source_segment(
    source_3a,
    encoder_node_3b,
)


print("\nENCODER SOURCE")
print("-" * 100)

print(
    "Function :",
    ENCODER_NAME_3B,
)

print(
    "Line     :",
    encoder_node_3b.lineno,
)


# ==========================================================================================
# 3. Execute exact encoder definition
# ==========================================================================================

exec(
    "from __future__ import annotations\n\n"
    +
    encoder_source_3b,
    globals(),
)


assert callable(
    globals().get(
        ENCODER_NAME_3B
    )
)


# ==========================================================================================
# 4. Search Notebook 59 for final model + feature-name assignments
# ==========================================================================================

TARGET_VARIABLES_3B = [
    "r3_live_model",
    "r3_live_feature_names",
]


assignment_hits_3b = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    node_source = ast.get_source_segment(
        source_3a,
        node,
    )

    if not node_source:
        continue

    matched = [
        name
        for name in TARGET_VARIABLES_3B
        if name in node_source
    ]

    if not matched:
        continue

    assignment_hits_3b.append(
        {
            "line_number":
                node.lineno,

            "matched":
                matched,

            "source":
                node_source,
        }
    )


section3b_assignment_hits_df = pd.DataFrame(
    assignment_hits_3b
)


print("\nR3 LIVE VARIABLE ASSIGNMENTS")
print("-" * 100)

display(
    section3b_assignment_hits_df
)


# ==========================================================================================
# 5. Search for candidate model artifact files
# ==========================================================================================

model_candidates_3b = []


for root in [
    PROJECT_ROOT / "models",
    PROJECT_ROOT / "artifacts",
    PROJECT_ROOT / "outputs",
]:

    if not root.exists():
        continue

    for path in root.rglob("*"):

        if not path.is_file():
            continue

        name_lower = path.name.lower()

        if (
            "r3" in name_lower
            or
            "state_centric" in name_lower
            or
            "randomforest" in name_lower
            or
            "random_forest" in name_lower
        ):

            model_candidates_3b.append(
                {
                    "path":
                        str(path),

                    "suffix":
                        path.suffix.lower(),

                    "size_bytes":
                        path.stat().st_size,
                }
            )


section3b_model_candidates_df = pd.DataFrame(
    model_candidates_3b
)


print("\nR3 MODEL / ARTIFACT CANDIDATES")
print("-" * 100)

display(
    section3b_model_candidates_df
)


# ==========================================================================================
# 6. Search Notebook 59 source for actual artifact paths
# ==========================================================================================

artifact_path_rows_3b = []


for line_number, line in enumerate(
    source_3a.splitlines(),
    start=1,
):

    line_lower = line.lower()

    if not any(
        token in line_lower
        for token in [
            ".joblib",
            ".pkl",
            ".pickle",
            "feature_names",
            "randomforest",
            "r3_live_model",
        ]
    ):
        continue

    artifact_path_rows_3b.append(
        {
            "line_number":
                line_number,

            "source_line":
                line.strip(),
        }
    )


section3b_artifact_lines_df = pd.DataFrame(
    artifact_path_rows_3b
)


print("\nNOTEBOOK 59 ARTIFACT / MODEL LOAD LINES")
print("-" * 100)

display(
    section3b_artifact_lines_df
)


# ==========================================================================================
# 7. Recover model + feature names from existing Notebook 59 artifacts if already available
# ==========================================================================================

model_loaded_3b = False
feature_names_loaded_3b = False

r3_model_3b = None
r3_feature_names_3b = None


# Prefer already-existing live variables if present
if (
    "r3_live_model"
    in globals()
    and
    globals().get(
        "r3_live_model"
    )
    is not None
):

    r3_model_3b = globals()[
        "r3_live_model"
    ]

    model_loaded_3b = True


if (
    "r3_live_feature_names"
    in globals()
    and
    globals().get(
        "r3_live_feature_names"
    )
    is not None
):

    r3_feature_names_3b = list(
        globals()[
            "r3_live_feature_names"
        ]
    )

    feature_names_loaded_3b = True


print("\nEXISTING LIVE VARIABLE STATUS")
print("-" * 100)

print(
    "Model already available        :",
    model_loaded_3b,
)

print(
    "Feature names already available:",
    feature_names_loaded_3b,
)


# ==========================================================================================
# 8. If not already loaded, inspect candidate joblib/pickle artifacts
# ==========================================================================================

artifact_probe_rows_3b = []


if not model_loaded_3b or not feature_names_loaded_3b:

    for _, row in (
        section3b_model_candidates_df
        .iterrows()
    ):

        path = Path(
            row[
                "path"
            ]
        )

        if path.suffix.lower() not in [
            ".joblib",
            ".pkl",
            ".pickle",
        ]:
            continue

        try:

            obj = joblib.load(
                path
            )

            artifact_probe_rows_3b.append(
                {
                    "path":
                        str(path),

                    "loaded":
                        True,

                    "object_type":
                        type(
                            obj
                        ).__name__,

                    "keys":
                        (
                            list(
                                obj.keys()
                            )
                            if isinstance(
                                obj,
                                dict,
                            )
                            else None
                        ),

                    "error":
                        None,
                }
            )


            # --------------------------------------------------------------
            # Direct RandomForest object
            # --------------------------------------------------------------

            if (
                not model_loaded_3b
                and
                hasattr(
                    obj,
                    "predict_proba",
                )
                and
                type(
                    obj
                ).__name__
                ==
                "RandomForestClassifier"
            ):

                r3_model_3b = obj
                model_loaded_3b = True


            # --------------------------------------------------------------
            # Dict bundle
            # --------------------------------------------------------------

            if isinstance(
                obj,
                dict,
            ):

                if not model_loaded_3b:

                    for key in [
                        "model",
                        "r3_model",
                        "classifier",
                        "random_forest",
                    ]:

                        candidate_model = obj.get(
                            key
                        )

                        if (
                            candidate_model
                            is not None
                            and
                            hasattr(
                                candidate_model,
                                "predict_proba",
                            )
                        ):

                            r3_model_3b = candidate_model
                            model_loaded_3b = True
                            break


                if not feature_names_loaded_3b:

                    for key in [
                        "feature_names",
                        "r3_feature_names",
                        "encoded_feature_names",
                        "retained_feature_names",
                    ]:

                        candidate_names = obj.get(
                            key
                        )

                        if candidate_names is not None:

                            candidate_names = list(
                                candidate_names
                            )

                            if len(
                                candidate_names
                            ) == 46:

                                r3_feature_names_3b = candidate_names
                                feature_names_loaded_3b = True
                                break


        except Exception as exc:

            artifact_probe_rows_3b.append(
                {
                    "path":
                        str(path),

                    "loaded":
                        False,

                    "object_type":
                        None,

                    "keys":
                        None,

                    "error":
                        f"{type(exc).__name__}: {exc}",
                }
            )


section3b_artifact_probe_df = pd.DataFrame(
    artifact_probe_rows_3b
)


print("\nARTIFACT PROBE RESULTS")
print("-" * 100)

if not section3b_artifact_probe_df.empty:

    display(
        section3b_artifact_probe_df
    )

else:

    print(
        "No artifact probe was required or no probeable artifacts were found."
    )


# ==========================================================================================
# 9. Bind recovered frozen objects
# ==========================================================================================

assert (
    model_loaded_3b
), (
    "Frozen R3 RandomForest model has not yet been recovered."
)

assert (
    r3_model_3b
    is not None
)

assert (
    type(
        r3_model_3b
    ).__name__
    ==
    "RandomForestClassifier"
), (
    "Recovered R3 model is not the expected RandomForestClassifier."
)


assert (
    feature_names_loaded_3b
), (
    "Exact 46 R3 feature names have not yet been recovered."
)

assert (
    len(
        r3_feature_names_3b
    )
    ==
    46
)


r3_live_model = r3_model_3b

r3_live_feature_names = list(
    r3_feature_names_3b
)


# ==========================================================================================
# 10. Encode the genuine 41-column row
# ==========================================================================================

print("\nENCODING GENUINE LIVE FEATURE ROW")
print("-" * 100)


encoded_r3_row_3b = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type  :",
    type(
        encoded_r3_row_3b
    ).__name__,
)

print(
    "Shape :",
    encoded_r3_row_3b.shape,
)


display(
    encoded_r3_row_3b
)


# ==========================================================================================
# 11. Validate exact 46-feature contract
# ==========================================================================================

observed_encoded_columns_3b = (
    encoded_r3_row_3b
    .columns
    .tolist()
)


encoded_shape_ok_3b = (
    encoded_r3_row_3b.shape
    ==
    (1, 46)
)


encoded_names_ok_3b = (
    observed_encoded_columns_3b
    ==
    r3_live_feature_names
)


print("\nENCODED CONTRACT CHECK")
print("-" * 100)

print(
    "Observed feature count :",
    len(
        observed_encoded_columns_3b
    ),
)

print(
    "Expected feature count :",
    len(
        r3_live_feature_names
    ),
)

print(
    "Exact feature names    :",
    encoded_names_ok_3b,
)


# ==========================================================================================
# 12. Run frozen model prediction
# ==========================================================================================

prediction_3b = (
    r3_live_model.predict(
        encoded_r3_row_3b
    )
)


probabilities_3b = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b
    )
)


predicted_action_3b = (
    prediction_3b[
        0
    ]
)


probability_vector_3b = (
    probabilities_3b[
        0
    ]
)


print("\nFROZEN R3 PREDICTION")
print("-" * 100)

print(
    "Predicted action:",
    predicted_action_3b,
)


probability_df_3b = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probability_vector_3b,
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nR3 CLASS PROBABILITIES")
print("-" * 100)

display(
    probability_df_3b
)


# ==========================================================================================
# 13. Final validation
# ==========================================================================================

section3b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "frozen model recovered",

            "observed":
                type(
                    r3_live_model
                ).__name__,

            "expected":
                "RandomForestClassifier",

            "passed":
                type(
                    r3_live_model
                ).__name__
                ==
                "RandomForestClassifier",
        },

        {
            "validation":
                "46 feature names recovered",

            "observed":
                len(
                    r3_live_feature_names
                ),

            "expected":
                46,

            "passed":
                len(
                    r3_live_feature_names
                )
                ==
                46,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_shape_ok_3b,
        },

        {
            "validation":
                "exact encoded feature names",

            "observed":
                encoded_names_ok_3b,

            "expected":
                True,

            "passed":
                encoded_names_ok_3b,
        },

        {
            "validation":
                "prediction count",

            "observed":
                len(
                    prediction_3b
                ),

            "expected":
                1,

            "passed":
                len(
                    prediction_3b
                )
                ==
                1,
        },

        {
            "validation":
                "six class probabilities",

            "observed":
                len(
                    probability_vector_3b
                ),

            "expected":
                6,

            "passed":
                len(
                    probability_vector_3b
                )
                ==
                6,
        },

        {
            "validation":
                "probability sum",

            "observed":
                float(
                    np.sum(
                        probability_vector_3b
                    )
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    np.sum(
                        probability_vector_3b
                    ),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B VALIDATION")
print("-" * 100)

display(
    section3b_validation_df
)


if section3b_validation_df[
    "passed"
].all():

    print("\n" + "=" * 100)

    print("✅ FROZEN R3 RandomForestClassifier RECOVERED")
    print("✅ EXACT 46-FEATURE CONTRACT RECOVERED")
    print("✅ 41 → 46 ENCODING EXECUTED")
    print("✅ FROZEN R3 PREDICTION EXECUTED")
    print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
    print("✅ SECTION 3B COMPLETE")

    print("⚠️ NO RETRAINING")
    print("⚠️ NO MODEL MODIFICATION")
    print("⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET")

    print("=" * 100)

else:

    print("\n" + "=" * 100)

    print("⚠️ SECTION 3B NEEDS TARGETED ARTIFACT RECOVERY")
    print("⚠️ DO NOT BENCHMARK YET")

    print("=" * 100)

====================================================================================================
SECTION 3B — RECOVER FROZEN R3 MODEL AND EXACT 46-FEATURE ENCODER
====================================================================================================

AssertionError: Section 3A.5 output is missing.

In [12]:
# ==========================================================================================
# SECTION 3B.1 — RECOVER EXACT NOTEBOOK 59 ENCODER DEPENDENCIES
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.1 — RECOVER EXACT NOTEBOOK 59 ENCODER DEPENDENCIES")
print("=" * 100)

import ast
import builtins
import pandas as pd


# ==========================================================================================
# 1. Inspect exact globals referenced by encode_r3_feature_row()
# ==========================================================================================

encoder_code_names_3b1 = sorted(
    set(
        encode_r3_feature_row
        .__code__
        .co_names
    )
)


print("\nENCODER REFERENCED GLOBAL NAMES")
print("-" * 100)

for name in encoder_code_names_3b1:
    print(name)


# ==========================================================================================
# 2. Determine which encoder globals are currently missing
# ==========================================================================================

encoder_globals_3b1 = (
    encode_r3_feature_row
    .__globals__
)


missing_encoder_globals_3b1 = []


for name in encoder_code_names_3b1:

    if hasattr(
        builtins,
        name,
    ):
        continue

    if name in encoder_globals_3b1:
        continue

    missing_encoder_globals_3b1.append(
        name
    )


print("\nMISSING ENCODER GLOBALS")
print("-" * 100)

if missing_encoder_globals_3b1:

    for name in missing_encoder_globals_3b1:
        print("-", name)

else:

    print("None")


# ==========================================================================================
# 3. Locate exact Notebook 59 top-level sources for the missing names
# ==========================================================================================

def assigned_names_3b1(
    node,
):

    names = []

    if isinstance(
        node,
        ast.Assign,
    ):

        targets = node.targets

    elif isinstance(
        node,
        ast.AnnAssign,
    ):

        targets = [
            node.target
        ]

    else:

        targets = []


    for target in targets:

        if isinstance(
            target,
            ast.Name,
        ):

            names.append(
                target.id
            )

    return names


encoder_dependency_sources_3b1 = []


for node in tree_3a.body:

    recovered_names = []


    if isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        recovered_names = (
            assigned_names_3b1(
                node
            )
        )


    elif isinstance(
        node,
        (
            ast.FunctionDef,
            ast.ClassDef,
        ),
    ):

        recovered_names = [
            node.name
        ]


    matching_names = [
        name
        for name in missing_encoder_globals_3b1
        if name in recovered_names
    ]


    if not matching_names:
        continue


    source_segment = ast.get_source_segment(
        source_3a,
        node,
    )


    encoder_dependency_sources_3b1.append(
        {
            "name":
                matching_names[
                    0
                ],

            "object_type":
                type(
                    node
                ).__name__,

            "line_number":
                node.lineno,

            "source":
                source_segment,
        }
    )


section3b1_dependency_sources_df = pd.DataFrame(
    encoder_dependency_sources_3b1
)


print("\nEXACT NOTEBOOK 59 ENCODER DEPENDENCY SOURCES")
print("-" * 100)

display(
    section3b1_dependency_sources_df[
        [
            "name",
            "object_type",
            "line_number",
        ]
    ]
    if not section3b1_dependency_sources_df.empty
    else section3b1_dependency_sources_df
)


# ==========================================================================================
# 4. Print exact source for audit
# ==========================================================================================

for _, row in (
    section3b1_dependency_sources_df
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        "OBJECT:",
        row[
            "name"
        ]
    )

    print(
        "LINE:",
        row[
            "line_number"
        ]
    )

    print("-" * 100)

    print(
        row[
            "source"
        ]
    )


# ==========================================================================================
# 5. Recover the exact R3 schema aliases
#
# We only bind from the already validated 41-column live contract when the exact
# Notebook 59 object is a schema alias. No feature is invented or removed.
# ==========================================================================================

schema_alias_status_3b1 = []


# ------------------------------------------------------------------
# R3_NUMERIC_FEATURES
# ------------------------------------------------------------------

if (
    "R3_NUMERIC_FEATURES"
    in missing_encoder_globals_3b1
):

    R3_NUMERIC_FEATURES = list(
        PREPROCESS_NUMERIC_FEATURES
    )

    schema_alias_status_3b1.append(
        {
            "name":
                "R3_NUMERIC_FEATURES",

            "count":
                len(
                    R3_NUMERIC_FEATURES
                ),

            "expected":
                31,

            "loaded":
                True,
        }
    )


# ------------------------------------------------------------------
# R3_CATEGORICAL_FEATURES
# ------------------------------------------------------------------

if (
    "R3_CATEGORICAL_FEATURES"
    in missing_encoder_globals_3b1
):

    R3_CATEGORICAL_FEATURES = list(
        PREPROCESS_CATEGORICAL_FEATURES
    )

    schema_alias_status_3b1.append(
        {
            "name":
                "R3_CATEGORICAL_FEATURES",

            "count":
                len(
                    R3_CATEGORICAL_FEATURES
                ),

            "expected":
                10,

            "loaded":
                True,
        }
    )


# ------------------------------------------------------------------
# R3_RAW_FEATURES, if Notebook 59 encoder references it
# ------------------------------------------------------------------

if (
    "R3_RAW_FEATURES"
    in missing_encoder_globals_3b1
):

    R3_RAW_FEATURES = list(
        PREPROCESS_RAW_FEATURES
    )

    schema_alias_status_3b1.append(
        {
            "name":
                "R3_RAW_FEATURES",

            "count":
                len(
                    R3_RAW_FEATURES
                ),

            "expected":
                41,

            "loaded":
                True,
        }
    )


section3b1_schema_alias_df = pd.DataFrame(
    schema_alias_status_3b1
)


print("\nRESTORED ENCODER SCHEMA ALIASES")
print("-" * 100)

if not section3b1_schema_alias_df.empty:

    display(
        section3b1_schema_alias_df
    )

else:

    print(
        "No schema aliases required."
    )


# ==========================================================================================
# 6. Recheck all encoder globals
# ==========================================================================================

remaining_missing_3b1 = []


for name in encoder_code_names_3b1:

    if hasattr(
        builtins,
        name,
    ):
        continue

    if name in (
        encode_r3_feature_row
        .__globals__
    ):
        continue

    remaining_missing_3b1.append(
        name
    )


print("\nENCODER DEPENDENCY RECHECK")
print("-" * 100)

print(
    "Remaining missing globals:",
    remaining_missing_3b1,
)


# ==========================================================================================
# 7. Confirm exact schema relationship
# ==========================================================================================

numeric_contract_ok_3b1 = (
    (
        "R3_NUMERIC_FEATURES"
        not in globals()
    )
    or
    (
        list(
            R3_NUMERIC_FEATURES
        )
        ==
        list(
            PREPROCESS_NUMERIC_FEATURES
        )
    )
)


categorical_contract_ok_3b1 = (
    (
        "R3_CATEGORICAL_FEATURES"
        not in globals()
    )
    or
    (
        list(
            R3_CATEGORICAL_FEATURES
        )
        ==
        list(
            PREPROCESS_CATEGORICAL_FEATURES
        )
    )
)


print("\nSCHEMA CONTRACT")
print("-" * 100)

if (
    "R3_NUMERIC_FEATURES"
    in globals()
):

    print(
        "R3 numeric count      :",
        len(
            R3_NUMERIC_FEATURES
        )
    )


if (
    "R3_CATEGORICAL_FEATURES"
    in globals()
):

    print(
        "R3 categorical count  :",
        len(
            R3_CATEGORICAL_FEATURES
        )
    )


print(
    "Numeric contract exact :",
    numeric_contract_ok_3b1,
)

print(
    "Categorical exact      :",
    categorical_contract_ok_3b1,
)


# ==========================================================================================
# 8. Execute encoder again
# ==========================================================================================

print("\nRETRYING encode_r3_feature_row()")
print("-" * 100)


encoded_r3_row_3b1 = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type  :",
    type(
        encoded_r3_row_3b1
    ).__name__,
)

print(
    "Shape :",
    encoded_r3_row_3b1.shape,
)


display(
    encoded_r3_row_3b1
)


# ==========================================================================================
# 9. Compare against exact frozen 46-feature contract
# ==========================================================================================

observed_encoded_names_3b1 = (
    encoded_r3_row_3b1
    .columns
    .tolist()
)


expected_encoded_names_3b1 = list(
    r3_live_feature_names
)


missing_encoded_names_3b1 = [
    name
    for name in expected_encoded_names_3b1
    if name not in observed_encoded_names_3b1
]


unexpected_encoded_names_3b1 = [
    name
    for name in observed_encoded_names_3b1
    if name not in expected_encoded_names_3b1
]


encoded_order_exact_3b1 = (
    observed_encoded_names_3b1
    ==
    expected_encoded_names_3b1
)


print("\n46-FEATURE CONTRACT CHECK")
print("-" * 100)

print(
    "Observed shape     :",
    encoded_r3_row_3b1.shape,
)

print(
    "Expected shape     :",
    (1, 46),
)

print(
    "Missing features   :",
    missing_encoded_names_3b1,
)

print(
    "Unexpected features:",
    unexpected_encoded_names_3b1,
)

print(
    "Exact feature order:",
    encoded_order_exact_3b1,
)


# ==========================================================================================
# 10. Run frozen model prediction
# ==========================================================================================

prediction_3b1 = (
    r3_live_model.predict(
        encoded_r3_row_3b1
    )
)


probabilities_3b1 = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b1
    )
)


probability_df_3b1 = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probabilities_3b1[
                0
            ],
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nFROZEN R3 LIVE PREDICTION")
print("-" * 100)

print(
    "Predicted action:",
    prediction_3b1[
        0
    ]
)


print("\nR3 ACTION PROBABILITIES")
print("-" * 100)

display(
    probability_df_3b1
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3b1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "R3 model loaded",

            "observed":
                type(
                    r3_live_model
                ).__name__,

            "expected":
                "RandomForestClassifier",

            "passed":
                type(
                    r3_live_model
                ).__name__
                ==
                "RandomForestClassifier",
        },

        {
            "validation":
                "31 numeric features",

            "observed":
                len(
                    R3_NUMERIC_FEATURES
                ),

            "expected":
                31,

            "passed":
                len(
                    R3_NUMERIC_FEATURES
                )
                ==
                31,
        },

        {
            "validation":
                "10 categorical features",

            "observed":
                len(
                    R3_CATEGORICAL_FEATURES
                ),

            "expected":
                10,

            "passed":
                len(
                    R3_CATEGORICAL_FEATURES
                )
                ==
                10,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b1.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_r3_row_3b1.shape
                ==
                (1, 46),
        },

        {
            "validation":
                "exact encoded feature order",

            "observed":
                encoded_order_exact_3b1,

            "expected":
                True,

            "passed":
                encoded_order_exact_3b1,
        },

        {
            "validation":
                "prediction returned",

            "observed":
                len(
                    prediction_3b1
                ),

            "expected":
                1,

            "passed":
                len(
                    prediction_3b1
                )
                ==
                1,
        },

        {
            "validation":
                "six probability classes",

            "observed":
                probabilities_3b1.shape[
                    1
                ],

            "expected":
                6,

            "passed":
                probabilities_3b1.shape[
                    1
                ]
                ==
                6,
        },

        {
            "validation":
                "probability sum",

            "observed":
                float(
                    probabilities_3b1[
                        0
                    ].sum()
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    probabilities_3b1[
                        0
                    ].sum(),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B.1 VALIDATION")
print("-" * 100)

display(
    section3b1_validation_df
)


assert (
    section3b1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ FROZEN R3 MODEL PRESERVED")
print("✅ EXACT R3 ENCODER SCHEMA RESTORED")
print("✅ 31 NUMERIC + 10 CATEGORICAL RAW CONTRACT VERIFIED")
print("✅ 41 RAW FEATURES ENCODED")
print("✅ EXACT 46-FEATURE MATRIX VERIFIED")
print("✅ FROZEN RANDOM FOREST PREDICTION EXECUTED")
print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
print("✅ SECTION 3B.1 COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.1 — RECOVER EXACT NOTEBOOK 59 ENCODER DEPENDENCIES
====================================================================================================

NameError: name 'encode_r3_feature_row' is not defined

In [13]:
# ==========================================================================================
# SECTION 3B.2 — RECOVER EXACT NOTEBOOK 59 ENCODER FEATURE LISTS
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.2 — RECOVER EXACT NOTEBOOK 59 ENCODER FEATURE LISTS")
print("=" * 100)

import ast
import pandas as pd


TARGETS_3B2 = [
    "R3_NUMERIC_FEATURES",
    "R3_CATEGORICAL_FEATURES",
    "R3_ENCODED_FEATURE_NAMES",
]


# ==========================================================================================
# 1. Search exact Notebook 59 assignments
# ==========================================================================================

rows_3b2 = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue

    source_text = ast.get_source_segment(
        source_3a,
        node,
    )

    if not source_text:
        continue

    matched = [
        name
        for name in TARGETS_3B2
        if name in source_text
    ]

    if not matched:
        continue

    rows_3b2.append(
        {
            "line_number":
                node.lineno,

            "end_line":
                getattr(
                    node,
                    "end_lineno",
                    None,
                ),

            "matched":
                matched,

            "source":
                source_text,
        }
    )


section3b2_assignments_df = pd.DataFrame(
    rows_3b2
)


print("\nEXACT NOTEBOOK 59 ENCODER SCHEMA ASSIGNMENTS")
print("-" * 100)

display(
    section3b2_assignments_df
)


# ==========================================================================================
# 2. Print complete source
# ==========================================================================================

print("\nCOMPLETE ENCODER SCHEMA SOURCES")
print("-" * 100)


for index, row in (
    section3b2_assignments_df
    .iterrows()
):

    print("\n" + "=" * 100)

    print(
        f"ASSIGNMENT {index + 1}"
    )

    print(
        "Lines:",
        row[
            "line_number"
        ],
        "-",
        row[
            "end_line"
        ],
    )

    print("-" * 100)

    print(
        row[
            "source"
        ]
    )


# ==========================================================================================
# 3. Inspect exact encoder source for expected raw names
# ==========================================================================================

print("\nENCODER SOURCE")
print("-" * 100)

print(
    encoder_source_3b
)


# ==========================================================================================
# 4. Extract all string literals referenced by encoder
# ==========================================================================================

encoder_tree_3b2 = ast.parse(
    encoder_source_3b
)


encoder_strings_3b2 = []


for node in ast.walk(
    encoder_tree_3b2
):

    if (
        isinstance(
            node,
            ast.Constant,
        )
        and
        isinstance(
            node.value,
            str,
        )
    ):

        encoder_strings_3b2.append(
            node.value
        )


print("\nENCODER STRING LITERALS")
print("-" * 100)

for value in encoder_strings_3b2:
    print(value)


# ==========================================================================================
# 5. Compare current aliases against actual 41-column raw row
# ==========================================================================================

print("\nCURRENT R3_NUMERIC_FEATURES")
print("-" * 100)

for index, feature in enumerate(
    R3_NUMERIC_FEATURES,
    start=1,
):

    present = (
        feature
        in raw_feature_row_3a5.columns
    )

    print(
        f"{index:02d}. "
        f"{feature:<45} "
        f"present={present}"
    )


missing_numeric_3b2 = [
    feature
    for feature in R3_NUMERIC_FEATURES
    if feature
    not in raw_feature_row_3a5.columns
]


print("\nCURRENT NUMERIC FEATURES MISSING FROM RAW ROW")
print("-" * 100)

print(
    missing_numeric_3b2
)


# ==========================================================================================
# 6. Also compare categorical list
# ==========================================================================================

missing_categorical_3b2 = [
    feature
    for feature in R3_CATEGORICAL_FEATURES
    if feature
    not in raw_feature_row_3a5.columns
]


print("\nCURRENT CATEGORICAL FEATURES MISSING FROM RAW ROW")
print("-" * 100)

print(
    missing_categorical_3b2
)


# ==========================================================================================
# 7. Diagnostic summary
# ==========================================================================================

section3b2_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 59 encoder assignment evidence found",

            "observed":
                len(
                    section3b2_assignments_df
                ),

            "passed":
                len(
                    section3b2_assignments_df
                )
                > 0,
        },

        {
            "validation":
                "current numeric alias matches raw row",

            "observed":
                missing_numeric_3b2,

            "passed":
                len(
                    missing_numeric_3b2
                )
                == 0,
        },

        {
            "validation":
                "current categorical alias matches raw row",

            "observed":
                missing_categorical_3b2,

            "passed":
                len(
                    missing_categorical_3b2
                )
                == 0,
        },
    ]
)


print("\nSECTION 3B.2 DIAGNOSTIC")
print("-" * 100)

display(
    section3b2_validation_df
)


print("\n" + "=" * 100)

print("✅ EXACT ENCODER SCHEMA SEARCH COMPLETE")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.2 — RECOVER EXACT NOTEBOOK 59 ENCODER FEATURE LISTS
====================================================================================================

NameError: name 'tree_3a' is not defined

In [38]:
# ==========================================================================================
# SECTION 3B.3 — VERIFY EXACT FROZEN 46-FEATURE R3 ENCODED CONTRACT
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.3 — VERIFY EXACT FROZEN 46-FEATURE R3 ENCODED CONTRACT")
print("=" * 100)

import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require recovered frozen model + exact feature names
# ==========================================================================================

assert (
    "r3_live_model"
    in globals()
    and
    r3_live_model is not None
), (
    "r3_live_model is missing. "
    "Run the Section 3B artifact recovery first."
)

assert (
    "r3_live_feature_names"
    in globals()
    and
    r3_live_feature_names is not None
), (
    "r3_live_feature_names is missing. "
    "Run the Section 3B artifact recovery first."
)


R3_ENCODED_FEATURE_NAMES = list(
    r3_live_feature_names
)


print("\nFROZEN R3 FEATURE CONTRACT")
print("-" * 100)

print(
    "Total encoded features:",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)


# ==========================================================================================
# 2. Recover exact numeric / categorical split using Notebook 59 rules
# ==========================================================================================

R3_NUMERIC_FEATURES_ENCODED_3B3 = [
    feature_name
    for feature_name
    in R3_ENCODED_FEATURE_NAMES
    if str(
        feature_name
    ).startswith(
        "numeric__"
    )
]


R3_CATEGORICAL_FEATURES_ENCODED_3B3 = [
    feature_name
    for feature_name
    in R3_ENCODED_FEATURE_NAMES
    if str(
        feature_name
    ).startswith(
        "categorical__"
    )
]


other_encoded_features_3b3 = [
    feature_name
    for feature_name
    in R3_ENCODED_FEATURE_NAMES
    if (
        feature_name
        not in R3_NUMERIC_FEATURES_ENCODED_3B3
        and
        feature_name
        not in R3_CATEGORICAL_FEATURES_ENCODED_3B3
    )
]


print("\nENCODED FEATURE SPLIT")
print("-" * 100)

print(
    "numeric__ features      :",
    len(
        R3_NUMERIC_FEATURES_ENCODED_3B3
    ),
)

print(
    "categorical__ features  :",
    len(
        R3_CATEGORICAL_FEATURES_ENCODED_3B3
    ),
)

print(
    "other-prefix features   :",
    len(
        other_encoded_features_3b3
    ),
)


# ==========================================================================================
# 3. Print exact 46-feature order
# ==========================================================================================

print("\nEXACT FROZEN 46-FEATURE ORDER")
print("-" * 100)


for index, feature_name in enumerate(
    R3_ENCODED_FEATURE_NAMES,
    start=1,
):

    print(
        f"{index:02d}. {feature_name}"
    )


# ==========================================================================================
# 4. Print numeric encoded features
# ==========================================================================================

print("\nFROZEN NUMERIC ENCODED FEATURES")
print("-" * 100)


for index, feature_name in enumerate(
    R3_NUMERIC_FEATURES_ENCODED_3B3,
    start=1,
):

    print(
        f"{index:02d}. {feature_name}"
    )


# ==========================================================================================
# 5. Print categorical encoded features
# ==========================================================================================

print("\nFROZEN CATEGORICAL ENCODED FEATURES")
print("-" * 100)


for index, feature_name in enumerate(
    R3_CATEGORICAL_FEATURES_ENCODED_3B3,
    start=1,
):

    print(
        f"{index:02d}. {feature_name}"
    )


# ==========================================================================================
# 6. Recover raw source columns required by encoded numeric features
# ==========================================================================================

numeric_raw_columns_3b3 = [
    feature_name.replace(
        "numeric__",
        "",
        1,
    )
    for feature_name
    in R3_NUMERIC_FEATURES_ENCODED_3B3
]


print("\nRAW COLUMNS REQUIRED BY FROZEN NUMERIC FEATURES")
print("-" * 100)


for index, raw_name in enumerate(
    numeric_raw_columns_3b3,
    start=1,
):

    present = (
        raw_name
        in raw_feature_row_3a5.columns
    )

    print(
        f"{index:02d}. "
        f"{raw_name:<45} "
        f"present={present}"
    )


missing_numeric_raw_3b3 = [
    raw_name
    for raw_name
    in numeric_raw_columns_3b3
    if raw_name
    not in raw_feature_row_3a5.columns
]


# ==========================================================================================
# 7. Parse categorical encoded names to source raw columns
#
# Example:
# categorical__energy_band_ZERO
#     -> source column = energy_band
#
# We use longest matching raw categorical column prefix.
# ==========================================================================================

raw_categorical_columns_3b3 = list(
    PREPROCESS_CATEGORICAL_FEATURES
)


categorical_mapping_rows_3b3 = []


for encoded_name in (
    R3_CATEGORICAL_FEATURES_ENCODED_3B3
):

    suffix = encoded_name.replace(
        "categorical__",
        "",
        1,
    )

    matched_source = None
    matched_value = None


    # Longest names first avoids prefix ambiguity.
    for raw_column in sorted(
        raw_categorical_columns_3b3,
        key=len,
        reverse=True,
    ):

        prefix = (
            raw_column
            + "_"
        )

        if suffix.startswith(
            prefix
        ):

            matched_source = (
                raw_column
            )

            matched_value = (
                suffix[
                    len(
                        prefix
                    ):
                ]
            )

            break


    categorical_mapping_rows_3b3.append(
        {
            "encoded_feature":
                encoded_name,

            "raw_source_column":
                matched_source,

            "category_value":
                matched_value,

            "source_present":
                (
                    matched_source
                    in raw_feature_row_3a5.columns
                    if matched_source
                    is not None
                    else False
                ),
        }
    )


section3b3_categorical_mapping_df = pd.DataFrame(
    categorical_mapping_rows_3b3
)


print("\nCATEGORICAL ENCODED → RAW SOURCE MAPPING")
print("-" * 100)

display(
    section3b3_categorical_mapping_df
)


unresolved_categorical_features_3b3 = (
    section3b3_categorical_mapping_df.loc[
        section3b3_categorical_mapping_df[
            "raw_source_column"
        ].isna(),
        "encoded_feature",
    ]
    .astype(str)
    .tolist()
)


missing_categorical_sources_3b3 = (
    section3b3_categorical_mapping_df.loc[
        ~section3b3_categorical_mapping_df[
            "source_present"
        ].astype(bool),
        "encoded_feature",
    ]
    .astype(str)
    .tolist()
)


# ==========================================================================================
# 8. Compare model's own input dimensionality
# ==========================================================================================

model_feature_count_3b3 = getattr(
    r3_live_model,
    "n_features_in_",
    None,
)


model_classes_3b3 = list(
    getattr(
        r3_live_model,
        "classes_",
        [],
    )
)


print("\nFROZEN MODEL CONTRACT")
print("-" * 100)

print(
    "Model type       :",
    type(
        r3_live_model
    ).__name__,
)

print(
    "n_features_in_   :",
    model_feature_count_3b3,
)

print(
    "Class count      :",
    len(
        model_classes_3b3
    ),
)

print(
    "Classes          :",
    model_classes_3b3,
)


# ==========================================================================================
# 9. Validate exact expected class set
# ==========================================================================================

expected_classes_3b3 = list(
    POLICY_ACTION_CLASSES
)


class_contract_exact_3b3 = (
    model_classes_3b3
    ==
    expected_classes_3b3
)


print("\nACTION CLASS CONTRACT")
print("-" * 100)

print(
    "Expected:",
    expected_classes_3b3,
)

print(
    "Observed:",
    model_classes_3b3,
)

print(
    "Exact order match:",
    class_contract_exact_3b3,
)


# ==========================================================================================
# 10. Build contract summary
# ==========================================================================================

section3b3_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "total frozen encoded features",

            "observed":
                len(
                    R3_ENCODED_FEATURE_NAMES
                ),

            "expected":
                46,

            "passed":
                len(
                    R3_ENCODED_FEATURE_NAMES
                )
                == 46,
        },

        {
            "validation":
                "numeric encoded features",

            "observed":
                len(
                    R3_NUMERIC_FEATURES_ENCODED_3B3
                ),

            "expected":
                19,

            "passed":
                len(
                    R3_NUMERIC_FEATURES_ENCODED_3B3
                )
                == 19,
        },

        {
            "validation":
                "categorical encoded features",

            "observed":
                len(
                    R3_CATEGORICAL_FEATURES_ENCODED_3B3
                ),

            "expected":
                27,

            "passed":
                len(
                    R3_CATEGORICAL_FEATURES_ENCODED_3B3
                )
                == 27,
        },

        {
            "validation":
                "no unknown encoded prefixes",

            "observed":
                other_encoded_features_3b3,

            "expected":
                [],

            "passed":
                len(
                    other_encoded_features_3b3
                )
                == 0,
        },

        {
            "validation":
                "all frozen numeric raw sources present",

            "observed":
                missing_numeric_raw_3b3,

            "expected":
                [],

            "passed":
                len(
                    missing_numeric_raw_3b3
                )
                == 0,
        },

        {
            "validation":
                "all categorical encodings resolved",

            "observed":
                unresolved_categorical_features_3b3,

            "expected":
                [],

            "passed":
                len(
                    unresolved_categorical_features_3b3
                )
                == 0,
        },

        {
            "validation":
                "all categorical raw sources present",

            "observed":
                missing_categorical_sources_3b3,

            "expected":
                [],

            "passed":
                len(
                    missing_categorical_sources_3b3
                )
                == 0,
        },

        {
            "validation":
                "model expects 46 inputs",

            "observed":
                model_feature_count_3b3,

            "expected":
                46,

            "passed":
                model_feature_count_3b3
                == 46,
        },

        {
            "validation":
                "six frozen action classes",

            "observed":
                len(
                    model_classes_3b3
                ),

            "expected":
                6,

            "passed":
                len(
                    model_classes_3b3
                )
                == 6,
        },

        {
            "validation":
                "exact action class order",

            "observed":
                class_contract_exact_3b3,

            "expected":
                True,

            "passed":
                class_contract_exact_3b3,
        },
    ]
)


print("\nSECTION 3B.3 VALIDATION")
print("-" * 100)

display(
    section3b3_validation_df
)


# ==========================================================================================
# 11. Important clarification of the earlier 31-column confusion
# ==========================================================================================

print("\nCONTRACT INTERPRETATION")
print("-" * 100)

print(
    "The 41-column production row contains 31 numeric-like/raw columns "
    "plus 10 categorical raw columns."
)

print(
    "The frozen R3 model does NOT retain all 31 numeric-like raw columns."
)

print(
    "Its final encoded model contract contains exactly 19 retained numeric "
    "features plus 27 one-hot categorical indicators = 46 total."
)

print(
    "Therefore the 31 raw numeric-like columns and 19 frozen numeric encoded "
    "features are different layers of the same production pipeline."
)


# ==========================================================================================
# 12. Gate
# ==========================================================================================

all_contract_checks_pass_3b3 = bool(
    section3b3_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)


if all_contract_checks_pass_3b3:

    print("✅ EXACT FROZEN R3 ENCODED CONTRACT VERIFIED")
    print("✅ 46 TOTAL ENCODED FEATURES")
    print("✅ 19 RETAINED NUMERIC FEATURES")
    print("✅ 27 CATEGORICAL ONE-HOT INDICATORS")
    print("✅ MODEL n_features_in_ = 46")
    print("✅ SIX ACTION CLASSES VERIFIED")
    print("✅ RAW 41-COLUMN INPUT SOURCES ARE AVAILABLE")
    print("✅ SECTION 3B.3 COMPLETE")

else:

    print("⚠️ FROZEN R3 CONTRACT HAS A SPECIFIC MISMATCH")
    print("⚠️ REVIEW FAILED VALIDATION ROWS BEFORE ENCODING")


print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.3 — VERIFY EXACT FROZEN 46-FEATURE R3 ENCODED CONTRACT
====================================================================================================

FROZEN R3 FEATURE CONTRACT
----------------------------------------------------------------------------------------------------
Total encoded features: 46

ENCODED FEATURE SPLIT
----------------------------------------------------------------------------------------------------
numeric__ features      : 19
categorical__ features  : 27
other-prefix features   : 0

EXACT FROZEN 46-FEATURE ORDER
----------------------------------------------------------------------------------------------------
01. numeric__turn_number
02. numeric__player_energy
03. numeric__opponent_energy
04. numeric__player_damage
05. numeric__opponent_damage
06. numeric__prize_cards_remaining
07. numeric__hand_size
08. numeric__recomputed_legal_move_count
09. numeric__acting_energy
10. numeric__defending_energy
11. numeric__energy_difference
12. numeric__absolute_energy_difference
13. numeric__acting_damage
14. numeric__defending_damage
15. numeric__damage_difference
16. numeric__absolute_damage_difference
17. numeric__single_legal_move_flag
18. numeric__multi_legal_move_flag
19. numeric__model_choice_required_flag
20. categorical__current_side_Opponent
21. categorical__current_side_Player
22. categorical__side_mode_FLIP
23. categorical__side_mode_PRESERVE
24. categorical__player_card_Bulbasaur
25. categorical__player_card_Charmander
26. categorical__player_card_Eevee
27. categorical__player_card_Meowth
28. categorical__opponent_card_Charmander
29. categorical__opponent_card_Eevee
30. categorical__active_card_Bulbasaur
31. categorical__active_card_Charmander
32. categorical__active_card_Eevee
33. categorical__active_card_Meowth
34. categorical__inactive_card_Bulbasaur
35. categorical__inactive_card_Charmander
36. categorical__inactive_card_Eevee
37. categorical__inactive_card_Meowth
38. categorical__battle_phase_EARLY
39. categorical__battle_phase_LATE
40. categorical__battle_phase_MID
41. categorical__energy_band_LOW
42. categorical__energy_band_READY
43. categorical__energy_band_ZERO
44. categorical__damage_band_HIGH_DAMAGE
45. categorical__damage_band_LOW_DAMAGE
46. categorical__damage_band_MEDIUM_DAMAGE

FROZEN NUMERIC ENCODED FEATURES
----------------------------------------------------------------------------------------------------
01. numeric__turn_number
02. numeric__player_energy
03. numeric__opponent_energy
04. numeric__player_damage
05. numeric__opponent_damage
06. numeric__prize_cards_remaining
07. numeric__hand_size
08. numeric__recomputed_legal_move_count
09. numeric__acting_energy
10. numeric__defending_energy
11. numeric__energy_difference
12. numeric__absolute_energy_difference
13. numeric__acting_damage
14. numeric__defending_damage
15. numeric__damage_difference
16. numeric__absolute_damage_difference
17. numeric__single_legal_move_flag
18. numeric__multi_legal_move_flag
19. numeric__model_choice_required_flag

FROZEN CATEGORICAL ENCODED FEATURES
----------------------------------------------------------------------------------------------------
01. categorical__current_side_Opponent
02. categorical__current_side_Player
03. categorical__side_mode_FLIP
04. categorical__side_mode_PRESERVE
05. categorical__player_card_Bulbasaur
06. categorical__player_card_Charmander
07. categorical__player_card_Eevee
08. categorical__player_card_Meowth
09. categorical__opponent_card_Charmander
10. categorical__opponent_card_Eevee
11. categorical__active_card_Bulbasaur
12. categorical__active_card_Charmander
13. categorical__active_card_Eevee
14. categorical__active_card_Meowth
15. categorical__inactive_card_Bulbasaur
16. categorical__inactive_card_Charmander
17. categorical__inactive_card_Eevee
18. categorical__inactive_card_Meowth
19. categorical__battle_phase_EARLY
20. categorical__battle_phase_LATE
21. categorical__battle_phase_MID
22. categorical__energy_band_LOW
23. categorical__energy_band_READY
24. categorical__energy_band_ZERO
25. categorical__damage_band_HIGH_DAMAGE
26. categorical__damage_band_LOW_DAMAGE
27. categorical__damage_band_MEDIUM_DAMAGE

RAW COLUMNS REQUIRED BY FROZEN NUMERIC FEATURES
----------------------------------------------------------------------------------------------------
01. turn_number                                   present=True
02. player_energy                                 present=True
03. opponent_energy                               present=True
04. player_damage                                 present=True
05. opponent_damage                               present=True
06. prize_cards_remaining                         present=True
07. hand_size                                     present=True
08. recomputed_legal_move_count                   present=True
09. acting_energy                                 present=True
10. defending_energy                              present=True
11. energy_difference                             present=True
12. absolute_energy_difference                    present=True
13. acting_damage                                 present=True
14. defending_damage                              present=True
15. damage_difference                             present=True
16. absolute_damage_difference                    present=True
17. single_legal_move_flag                        present=True
18. multi_legal_move_flag                         present=True
19. model_choice_required_flag                    present=True

CATEGORICAL ENCODED → RAW SOURCE MAPPING
----------------------------------------------------------------------------------------------------

,encoded_feature,raw_source_column,category_value,source_present
0,categorical__current_side_Opponent,current_side,Opponent,True
1,categorical__current_side_Player,current_side,Player,True
2,categorical__side_mode_FLIP,side_mode,FLIP,True
3,categorical__side_mode_PRESERVE,side_mode,PRESERVE,True
4,categorical__player_card_Bulbasaur,player_card,Bulbasaur,True
5,categorical__player_card_Charmander,player_card,Charmander,True
6,categorical__player_card_Eevee,player_card,Eevee,True
7,categorical__player_card_Meowth,player_card,Meowth,True
8,categorical__opponent_card_Charmander,opponent_card,Charmander,True
9,categorical__opponent_card_Eevee,opponent_card,Eevee,True
10,categorical__active_card_Bulbasaur,active_card,Bulbasaur,True
11,categorical__active_card_Charmander,active_card,Charmander,True
12,categorical__active_card_Eevee,active_card,Eevee,True
13,categorical__active_card_Meowth,active_card,Meowth,True
14,categorical__inactive_card_Bulbasaur,inactive_card,Bulbasaur,True
15,categorical__inactive_card_Charmander,inactive_card,Charmander,True
16,categorical__inactive_card_Eevee,inactive_card,Eevee,True
17,categorical__inactive_card_Meowth,inactive_card,Meowth,True
18,categorical__battle_phase_EARLY,battle_phase,EARLY,True
19,categorical__battle_phase_LATE,battle_phase,LATE,True
20,categorical__battle_phase_MID,battle_phase,MID,True
21,categorical__energy_band_LOW,energy_band,LOW,True
22,categorical__energy_band_READY,energy_band,READY,True
23,categorical__energy_band_ZERO,energy_band,ZERO,True
24,categorical__damage_band_HIGH_DAMAGE,damage_band,HIGH_DAMAGE,True
25,categorical__damage_band_LOW_DAMAGE,damage_band,LOW_DAMAGE,True
26,categorical__damage_band_MEDIUM_DAMAGE,damage_band,MEDIUM_DAMAGE,True

FROZEN MODEL CONTRACT
----------------------------------------------------------------------------------------------------
Model type       : RandomForestClassifier
n_features_in_   : 64
Class count      : 6
Classes          : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

ACTION CLASS CONTRACT
----------------------------------------------------------------------------------------------------
Expected: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
Observed: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
Exact order match: True

SECTION 3B.3 VALIDATION
----------------------------------------------------------------------------------------------------

                               validation observed expected  passed
0           total frozen encoded features       46       46    True
1                numeric encoded features       19       19    True
2            categorical encoded features       27       27    True
3             no unknown encoded prefixes       []       []    True
4  all frozen numeric raw sources present       []       []    True
5      all categorical encodings resolved       []       []    True
6     all categorical raw sources present       []       []    True
7                 model expects 46 inputs       64       46   False
8               six frozen action classes        6        6    True
9                exact action class order     True     True    True

CONTRACT INTERPRETATION
----------------------------------------------------------------------------------------------------
The 41-column production row contains 31 numeric-like/raw columns plus 10 categorical raw columns.
The frozen R3 model does NOT retain all 31 numeric-like raw columns.
Its final encoded model contract contains exactly 19 retained numeric features plus 27 one-hot categorical indicators = 46 total.
Therefore the 31 raw numeric-like columns and 19 frozen numeric encoded features are different layers of the same production pipeline.

====================================================================================================
⚠️ FROZEN R3 CONTRACT HAS A SPECIFIC MISMATCH
⚠️ REVIEW FAILED VALIDATION ROWS BEFORE ENCODING
⚠️ NO MODEL MODIFICATION
⚠️ NO RETRAINING
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [39]:
# ==========================================================================================
# SECTION 3B.4 — RECOVER EXACT 46-FEATURE R3 PRODUCTION PACKAGE AND MODEL
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.4 — RECOVER EXACT 46-FEATURE R3 PRODUCTION PACKAGE AND MODEL")
print("=" * 100)

from pathlib import Path
import joblib
import numpy as np
import pandas as pd


# ==========================================================================================
# 1. Collect probeable R3 joblib candidates
# ==========================================================================================

assert (
    "section3b_model_candidates_df"
    in globals()
), (
    "Section 3B artifact candidate inventory is missing."
)


joblib_candidates_3b4 = (
    section3b_model_candidates_df.loc[
        section3b_model_candidates_df[
            "suffix"
        ].astype(str).str.lower()
        ==
        ".joblib"
    ]
    .copy()
    .reset_index(
        drop=True
    )
)


print("\nJOBLIB CANDIDATES")
print("-" * 100)

display(
    joblib_candidates_3b4
)


assert len(
    joblib_candidates_3b4
) > 0, (
    "No R3 joblib candidates were found."
)


# ==========================================================================================
# 2. Inspect every artifact WITHOUT selecting one yet
# ==========================================================================================

artifact_inspection_rows_3b4 = []

loaded_objects_3b4 = {}


for index, row in joblib_candidates_3b4.iterrows():

    artifact_path = Path(
        row[
            "path"
        ]
    )

    inspection = {
        "candidate_index":
            index,

        "path":
            str(
                artifact_path
            ),

        "size_bytes":
            int(
                artifact_path.stat().st_size
            ),

        "loaded":
            False,

        "top_level_type":
            None,

        "dictionary_keys":
            None,

        "strategy_id":
            None,

        "nested_model_type":
            None,

        "nested_model_n_features":
            None,

        "nested_model_class_count":
            None,

        "retained_feature_count":
            None,

        "direct_model_n_features":
            None,

        "error":
            None,
    }


    try:

        obj = joblib.load(
            artifact_path
        )

        loaded_objects_3b4[
            index
        ] = obj

        inspection[
            "loaded"
        ] = True

        inspection[
            "top_level_type"
        ] = type(
            obj
        ).__name__


        # ------------------------------------------------------------------
        # Case A: package dictionary
        # ------------------------------------------------------------------

        if isinstance(
            obj,
            dict,
        ):

            inspection[
                "dictionary_keys"
            ] = list(
                obj.keys()
            )

            inspection[
                "strategy_id"
            ] = obj.get(
                "strategy_id"
            )


            retained_names = (
                obj.get(
                    "retained_feature_names"
                )
            )

            if retained_names is not None:

                inspection[
                    "retained_feature_count"
                ] = len(
                    retained_names
                )


            nested_model = obj.get(
                "model"
            )

            if nested_model is not None:

                inspection[
                    "nested_model_type"
                ] = type(
                    nested_model
                ).__name__

                inspection[
                    "nested_model_n_features"
                ] = getattr(
                    nested_model,
                    "n_features_in_",
                    None,
                )

                nested_classes = getattr(
                    nested_model,
                    "classes_",
                    [],
                )

                inspection[
                    "nested_model_class_count"
                ] = len(
                    nested_classes
                )


        # ------------------------------------------------------------------
        # Case B: standalone estimator
        # ------------------------------------------------------------------

        elif hasattr(
            obj,
            "predict"
        ):

            inspection[
                "direct_model_n_features"
            ] = getattr(
                obj,
                "n_features_in_",
                None,
            )


    except Exception as exc:

        inspection[
            "error"
        ] = (
            f"{type(exc).__name__}: {exc}"
        )


    artifact_inspection_rows_3b4.append(
        inspection
    )


section3b4_artifact_inspection_df = pd.DataFrame(
    artifact_inspection_rows_3b4
)


print("\nFULL R3 ARTIFACT INSPECTION")
print("-" * 100)

display(
    section3b4_artifact_inspection_df
)


# ==========================================================================================
# 3. Identify exact Notebook 59-compatible package
#
# Requirements:
#   - dictionary package
#   - nested model exists
#   - retained_feature_names count = 46
#   - nested model n_features_in_ = 46
#   - six classes
# ==========================================================================================

compatible_rows_3b4 = (
    section3b4_artifact_inspection_df.loc[
        (
            section3b4_artifact_inspection_df[
                "top_level_type"
            ]
            ==
            "dict"
        )
        &
        (
            section3b4_artifact_inspection_df[
                "retained_feature_count"
            ]
            ==
            46
        )
        &
        (
            section3b4_artifact_inspection_df[
                "nested_model_n_features"
            ]
            ==
            46
        )
        &
        (
            section3b4_artifact_inspection_df[
                "nested_model_class_count"
            ]
            ==
            6
        )
    ]
    .copy()
)


print("\nEXACT 46-FEATURE PACKAGE CANDIDATES")
print("-" * 100)

display(
    compatible_rows_3b4
)


assert (
    len(
        compatible_rows_3b4
    )
    >= 1
), (
    "No exact 46-feature R3 package was found. "
    "Do not alter the feature contract."
)


# ==========================================================================================
# 4. Prefer exact R3 strategy identifier if available
# ==========================================================================================

strategy_matches_3b4 = (
    compatible_rows_3b4.loc[
        compatible_rows_3b4[
            "strategy_id"
        ].astype(str)
        ==
        "R3_STATE_CENTRIC_POLICY"
    ]
)


if len(
    strategy_matches_3b4
) == 1:

    selected_row_3b4 = (
        strategy_matches_3b4
        .iloc[
            0
        ]
    )

elif len(
    compatible_rows_3b4
) == 1:

    selected_row_3b4 = (
        compatible_rows_3b4
        .iloc[
            0
        ]
    )

else:

    raise AssertionError(
        "Multiple 46-feature packages remain. "
        "Do not choose arbitrarily."
    )


selected_candidate_index_3b4 = int(
    selected_row_3b4[
        "candidate_index"
    ]
)


r3_live_package = (
    loaded_objects_3b4[
        selected_candidate_index_3b4
    ]
)


print("\nSELECTED R3 PRODUCTION PACKAGE")
print("-" * 100)

print(
    "Path:",
    selected_row_3b4[
        "path"
    ],
)

print(
    "Strategy:",
    r3_live_package.get(
        "strategy_id"
    ),
)

print(
    "Keys:",
    list(
        r3_live_package.keys()
    ),
)


# ==========================================================================================
# 5. Bind EXACT Notebook 59 package objects
# ==========================================================================================

r3_live_model = (
    r3_live_package.get(
        "model"
    )
)


r3_live_feature_names = list(
    r3_live_package.get(
        "retained_feature_names"
    )
)


assert (
    r3_live_model
    is not None
)


assert (
    len(
        r3_live_feature_names
    )
    ==
    46
)


print("\nBOUND FROZEN R3 MODEL")
print("-" * 100)

print(
    "Type              :",
    type(
        r3_live_model
    ).__name__,
)

print(
    "n_features_in_    :",
    getattr(
        r3_live_model,
        "n_features_in_",
        None,
    ),
)

print(
    "Feature-name count:",
    len(
        r3_live_feature_names
    ),
)

print(
    "Classes           :",
    list(
        r3_live_model.classes_
    ),
)


# ==========================================================================================
# 6. Reconstruct EXACT Notebook 59 encoder lists
#
# IMPORTANT:
# These are ENCODED names, not raw feature names.
# ==========================================================================================

R3_ENCODED_FEATURE_NAMES = list(
    r3_live_feature_names
)


R3_NUMERIC_FEATURES = [
    feature_name
    for feature_name
    in R3_ENCODED_FEATURE_NAMES
    if feature_name.startswith(
        "numeric__"
    )
]


R3_CATEGORICAL_FEATURES = [
    feature_name
    for feature_name
    in R3_ENCODED_FEATURE_NAMES
    if feature_name.startswith(
        "categorical__"
    )
]


print("\nEXACT NOTEBOOK 59 ENCODER SPLIT")
print("-" * 100)

print(
    "Encoded features    :",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)

print(
    "Numeric encoded     :",
    len(
        R3_NUMERIC_FEATURES
    ),
)

print(
    "Categorical encoded :",
    len(
        R3_CATEGORICAL_FEATURES
    ),
)


assert (
    len(
        R3_NUMERIC_FEATURES
    )
    ==
    19
)


assert (
    len(
        R3_CATEGORICAL_FEATURES
    )
    ==
    27
)


# ==========================================================================================
# 7. Verify exact feature list identity against Section 3B.3
# ==========================================================================================

feature_order_matches_3b4 = (
    list(
        R3_ENCODED_FEATURE_NAMES
    )
    ==
    list(
        R3_ENCODED_FEATURE_NAMES
    )
)


print("\nMODEL / ENCODER CONTRACT")
print("-" * 100)

print(
    "Model input count  :",
    r3_live_model.n_features_in_,
)

print(
    "Encoder feature count:",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)

print(
    "Counts agree:",
    (
        r3_live_model.n_features_in_
        ==
        len(
            R3_ENCODED_FEATURE_NAMES
        )
    ),
)


# ==========================================================================================
# 8. Execute exact 41 → 46 encoder
# ==========================================================================================

print("\nEXECUTING EXACT 41 → 46 R3 ENCODER")
print("-" * 100)


encoded_r3_row_3b4 = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type :",
    type(
        encoded_r3_row_3b4
    ).__name__,
)

print(
    "Shape:",
    encoded_r3_row_3b4.shape,
)


display(
    encoded_r3_row_3b4
)


# ==========================================================================================
# 9. Exact encoded order validation
# ==========================================================================================

encoded_order_exact_3b4 = (
    encoded_r3_row_3b4
    .columns
    .tolist()
    ==
    R3_ENCODED_FEATURE_NAMES
)


print("\nENCODED ORDER CHECK")
print("-" * 100)

print(
    "Exact order:",
    encoded_order_exact_3b4,
)


# ==========================================================================================
# 10. Run frozen R3 prediction
# ==========================================================================================

prediction_3b4 = (
    r3_live_model.predict(
        encoded_r3_row_3b4
    )
)


probabilities_3b4 = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b4
    )
)


probability_df_3b4 = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probabilities_3b4[
                0
            ],
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nFROZEN R3 PREDICTION")
print("-" * 100)

print(
    "Predicted action:",
    prediction_3b4[
        0
    ]
)


print("\nSIX-CLASS PROBABILITY VECTOR")
print("-" * 100)

display(
    probability_df_3b4
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3b4_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exact R3 package recovered",

            "observed":
                type(
                    r3_live_package
                ).__name__,

            "expected":
                "dict",

            "passed":
                isinstance(
                    r3_live_package,
                    dict,
                ),
        },

        {
            "validation":
                "strategy identifier",

            "observed":
                r3_live_package.get(
                    "strategy_id"
                ),

            "expected":
                "R3_STATE_CENTRIC_POLICY",

            "passed":
                r3_live_package.get(
                    "strategy_id"
                )
                ==
                "R3_STATE_CENTRIC_POLICY",
        },

        {
            "validation":
                "frozen model type",

            "observed":
                type(
                    r3_live_model
                ).__name__,

            "expected":
                "RandomForestClassifier",

            "passed":
                type(
                    r3_live_model
                ).__name__
                ==
                "RandomForestClassifier",
        },

        {
            "validation":
                "model expects 46 inputs",

            "observed":
                r3_live_model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_live_model.n_features_in_
                ==
                46,
        },

        {
            "validation":
                "46 retained features",

            "observed":
                len(
                    R3_ENCODED_FEATURE_NAMES
                ),

            "expected":
                46,

            "passed":
                len(
                    R3_ENCODED_FEATURE_NAMES
                )
                ==
                46,
        },

        {
            "validation":
                "19 encoded numeric features",

            "observed":
                len(
                    R3_NUMERIC_FEATURES
                ),

            "expected":
                19,

            "passed":
                len(
                    R3_NUMERIC_FEATURES
                )
                ==
                19,
        },

        {
            "validation":
                "27 encoded categorical features",

            "observed":
                len(
                    R3_CATEGORICAL_FEATURES
                ),

            "expected":
                27,

            "passed":
                len(
                    R3_CATEGORICAL_FEATURES
                )
                ==
                27,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b4.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_r3_row_3b4.shape
                ==
                (1, 46),
        },

        {
            "validation":
                "exact encoded feature order",

            "observed":
                encoded_order_exact_3b4,

            "expected":
                True,

            "passed":
                encoded_order_exact_3b4,
        },

        {
            "validation":
                "six class probabilities",

            "observed":
                probabilities_3b4.shape[
                    1
                ],

            "expected":
                6,

            "passed":
                probabilities_3b4.shape[
                    1
                ]
                ==
                6,
        },

        {
            "validation":
                "probabilities sum to one",

            "observed":
                float(
                    probabilities_3b4[
                        0
                    ].sum()
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    probabilities_3b4[
                        0
                    ].sum(),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B.4 VALIDATION")
print("-" * 100)

display(
    section3b4_validation_df
)


assert (
    section3b4_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 59 R3 PACKAGE RECOVERED")
print("✅ WRONG 64-FEATURE RANDOM FOREST REJECTED")
print("✅ FROZEN 46-FEATURE RANDOM FOREST BOUND")
print("✅ 19 NUMERIC + 27 CATEGORICAL ENCODED CONTRACT VERIFIED")
print("✅ 41 → 46 LIVE ENCODING EXECUTED")
print("✅ FROZEN R3 PREDICTION EXECUTED")
print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
print("✅ SECTION 3B.4 COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.4 — RECOVER EXACT 46-FEATURE R3 PRODUCTION PACKAGE AND MODEL
====================================================================================================

JOBLIB CANDIDATES
----------------------------------------------------------------------------------------------------

                                                path   suffix  size_bytes
0  D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...  .joblib     1218918
1  D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...  .joblib      283846

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

FULL R3 ARTIFACT INSPECTION
----------------------------------------------------------------------------------------------------

,candidate_index,path,size_bytes,loaded,top_level_type,dictionary_keys,strategy_id,nested_model_type,nested_model_n_features,nested_model_class_count,retained_feature_count,direct_model_n_features,error
0,0,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,1218918,True,RandomForestClassifier,None,NaN,NaN,NaN,NaN,NaN,64.0,None
1,1,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,283846,True,dict,"[strategy_id, model, retained_feature_names, r...",R3_STATE_CENTRIC_POLICY,RandomForestClassifier,46.0,6.0,46.0,NaN,None

EXACT 46-FEATURE PACKAGE CANDIDATES
----------------------------------------------------------------------------------------------------

,candidate_index,path,size_bytes,loaded,top_level_type,dictionary_keys,strategy_id,nested_model_type,nested_model_n_features,nested_model_class_count,retained_feature_count,direct_model_n_features,error
1,1,D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Bat...,283846,True,dict,"[strategy_id, model, retained_feature_names, r...",R3_STATE_CENTRIC_POLICY,RandomForestClassifier,46.0,6.0,46.0,NaN,None

SELECTED R3 PRODUCTION PACKAGE
----------------------------------------------------------------------------------------------------
Path: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\models\notebook55\section3a_r3_state_centric_policy_model.joblib
Strategy: R3_STATE_CENTRIC_POLICY
Keys: ['strategy_id', 'model', 'retained_feature_names', 'retained_feature_indices', 'training_results']

BOUND FROZEN R3 MODEL
----------------------------------------------------------------------------------------------------
Type              : RandomForestClassifier
n_features_in_    : 46
Feature-name count: 46
Classes           : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

EXACT NOTEBOOK 59 ENCODER SPLIT
----------------------------------------------------------------------------------------------------
Encoded features    : 46
Numeric encoded     : 19
Categorical encoded : 27

MODEL / ENCODER CONTRACT
----------------------------------------------------------------------------------------------------
Model input count  : 46
Encoder feature count: 46
Counts agree: True

EXECUTING EXACT 41 → 46 R3 ENCODER
----------------------------------------------------------------------------------------------------

NameError: name 'parse_r3_categorical_feature' is not defined

In [40]:
# ==========================================================================================
# SECTION 3B.4A — RECOVER EXACT NOTEBOOK 59 ENCODER HELPERS AND RETRY 41 → 46
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.4A — RECOVER EXACT NOTEBOOK 59 ENCODER HELPERS AND RETRY 41 → 46")
print("=" * 100)

import ast
import builtins
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Identify globals required by the exact Notebook 59 encoder
# ==========================================================================================

encoder_required_names_3b4a = sorted(
    set(
        encode_r3_feature_row
        .__code__
        .co_names
    )
)


encoder_globals_3b4a = (
    encode_r3_feature_row
    .__globals__
)


missing_encoder_names_3b4a = []


for name in encoder_required_names_3b4a:

    if hasattr(
        builtins,
        name,
    ):
        continue

    if name in encoder_globals_3b4a:
        continue

    missing_encoder_names_3b4a.append(
        name
    )


print("\nENCODER GLOBAL DEPENDENCY STATUS")
print("-" * 100)

print(
    "Referenced names:",
    encoder_required_names_3b4a,
)

print(
    "Currently missing:",
    missing_encoder_names_3b4a,
)


# ==========================================================================================
# 2. Build exact Notebook 59 top-level definition map
# ==========================================================================================

definition_map_3b4a = {}


for node in tree_3a.body:

    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        definition_map_3b4a[
            node.name
        ] = node


# ==========================================================================================
# 3. Locate exact Notebook 59 definitions for missing encoder helpers
# ==========================================================================================

helper_inventory_rows_3b4a = []


for name in missing_encoder_names_3b4a:

    node = definition_map_3b4a.get(
        name
    )

    helper_inventory_rows_3b4a.append(
        {
            "name":
                name,

            "found_in_notebook59":
                node is not None,

            "object_type":
                (
                    type(
                        node
                    ).__name__
                    if node is not None
                    else "NOT_FOUND"
                ),

            "line_number":
                (
                    node.lineno
                    if node is not None
                    else None
                ),

            "end_line":
                (
                    getattr(
                        node,
                        "end_lineno",
                        None,
                    )
                    if node is not None
                    else None
                ),
        }
    )


section3b4a_helper_inventory_df = pd.DataFrame(
    helper_inventory_rows_3b4a
)


print("\nNOTEBOOK 59 ENCODER HELPER INVENTORY")
print("-" * 100)

display(
    section3b4a_helper_inventory_df
)


# ==========================================================================================
# 4. Print exact helper sources before executing
# ==========================================================================================

print("\nEXACT NOTEBOOK 59 HELPER SOURCES")
print("-" * 100)


for name in missing_encoder_names_3b4a:

    node = definition_map_3b4a.get(
        name
    )

    if node is None:
        continue

    print("\n" + "=" * 100)
    print(
        f"{name} — line {node.lineno}"
    )
    print("-" * 100)

    print(
        ast.get_source_segment(
            source_3a,
            node,
        )
    )


# ==========================================================================================
# 5. Recover recursive helper-definition closure
#
# If parse_r3_categorical_feature() calls another Notebook 59 helper,
# recover that exact helper too.
# ==========================================================================================

required_helpers_3b4a = set()


for name in missing_encoder_names_3b4a:

    if name in definition_map_3b4a:

        required_helpers_3b4a.add(
            name
        )


changed_3b4a = True


while changed_3b4a:

    changed_3b4a = False

    for helper_name in list(
        required_helpers_3b4a
    ):

        helper_node = definition_map_3b4a[
            helper_name
        ]

        loaded_names = {
            child.id
            for child in ast.walk(
                helper_node
            )
            if (
                isinstance(
                    child,
                    ast.Name,
                )
                and
                isinstance(
                    child.ctx,
                    ast.Load,
                )
            )
        }

        for referenced_name in loaded_names:

            if (
                referenced_name
                in definition_map_3b4a
                and
                referenced_name
                not in required_helpers_3b4a
            ):

                required_helpers_3b4a.add(
                    referenced_name
                )

                changed_3b4a = True


print("\nHELPER DEPENDENCY CLOSURE")
print("-" * 100)

print(
    sorted(
        required_helpers_3b4a
    )
)


# ==========================================================================================
# 6. Execute exact helper definitions in original Notebook 59 source order
# ==========================================================================================

ordered_helper_nodes_3b4a = sorted(
    [
        definition_map_3b4a[
            name
        ]
        for name in required_helpers_3b4a
    ],
    key=lambda node:
        node.lineno,
)


helper_load_rows_3b4a = []


for node in ordered_helper_nodes_3b4a:

    helper_name = node.name

    helper_module = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        helper_module
    )


    try:

        exec(
            compile(
                helper_module,
                filename=str(
                    "notebook59_encoder_helper_recovery"
                ),
                mode="exec",
            ),
            globals(),
        )

        helper_load_rows_3b4a.append(
            {
                "helper":
                    helper_name,

                "line_number":
                    node.lineno,

                "loaded":
                    helper_name in globals(),

                "callable":
                    callable(
                        globals().get(
                            helper_name
                        )
                    ),

                "error":
                    None,
            }
        )

    except Exception as exc:

        helper_load_rows_3b4a.append(
            {
                "helper":
                    helper_name,

                "line_number":
                    node.lineno,

                "loaded":
                    False,

                "callable":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section3b4a_helper_load_df = pd.DataFrame(
    helper_load_rows_3b4a
)


print("\nENCODER HELPER LOAD RESULTS")
print("-" * 100)

display(
    section3b4a_helper_load_df
)


# ==========================================================================================
# 7. Recheck encoder dependencies
# ==========================================================================================

remaining_missing_3b4a = []


for name in encoder_required_names_3b4a:

    if hasattr(
        builtins,
        name,
    ):
        continue

    if name in (
        encode_r3_feature_row
        .__globals__
    ):
        continue

    remaining_missing_3b4a.append(
        name
    )


print("\nENCODER DEPENDENCY RECHECK")
print("-" * 100)

print(
    "Remaining missing globals:",
    remaining_missing_3b4a,
)


assert (
    len(
        remaining_missing_3b4a
    )
    == 0
), (
    "Encoder still has unresolved globals:\n"
    + "\n".join(
        remaining_missing_3b4a
    )
)


# ==========================================================================================
# 8. Confirm correct frozen production model remains bound
# ==========================================================================================

print("\nFROZEN R3 MODEL BEFORE RETRY")
print("-" * 100)

print(
    "Strategy:",
    r3_live_package.get(
        "strategy_id"
    ),
)

print(
    "Model type:",
    type(
        r3_live_model
    ).__name__,
)

print(
    "n_features_in_:",
    getattr(
        r3_live_model,
        "n_features_in_",
        None,
    ),
)

print(
    "Feature count:",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)


assert (
    r3_live_package.get(
        "strategy_id"
    )
    ==
    "R3_STATE_CENTRIC_POLICY"
)

assert (
    r3_live_model.n_features_in_
    ==
    46
)

assert (
    len(
        R3_ENCODED_FEATURE_NAMES
    )
    ==
    46
)


# ==========================================================================================
# 9. Retry exact 41 → 46 encoder
# ==========================================================================================

print("\nRETRYING EXACT 41 → 46 ENCODER")
print("-" * 100)


encoded_r3_row_3b4a = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type  :",
    type(
        encoded_r3_row_3b4a
    ).__name__,
)

print(
    "Shape :",
    encoded_r3_row_3b4a.shape,
)


display(
    encoded_r3_row_3b4a
)


# ==========================================================================================
# 10. Exact encoded feature-order validation
# ==========================================================================================

encoded_order_exact_3b4a = (
    encoded_r3_row_3b4a
    .columns
    .tolist()
    ==
    list(
        R3_ENCODED_FEATURE_NAMES
    )
)


missing_encoded_3b4a = [
    name
    for name in R3_ENCODED_FEATURE_NAMES
    if name
    not in encoded_r3_row_3b4a.columns
]


unexpected_encoded_3b4a = [
    name
    for name in encoded_r3_row_3b4a.columns
    if name
    not in R3_ENCODED_FEATURE_NAMES
]


print("\nENCODED CONTRACT")
print("-" * 100)

print(
    "Shape              :",
    encoded_r3_row_3b4a.shape,
)

print(
    "Missing features   :",
    missing_encoded_3b4a,
)

print(
    "Unexpected features:",
    unexpected_encoded_3b4a,
)

print(
    "Exact feature order:",
    encoded_order_exact_3b4a,
)


# ==========================================================================================
# 11. Run correct frozen R3 prediction
# ==========================================================================================

print("\nRUNNING FROZEN R3 PREDICTION")
print("-" * 100)


prediction_3b4a = (
    r3_live_model.predict(
        encoded_r3_row_3b4a
    )
)


probabilities_3b4a = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b4a
    )
)


predicted_action_3b4a = (
    prediction_3b4a[
        0
    ]
)


probability_vector_3b4a = (
    probabilities_3b4a[
        0
    ]
)


print(
    "Predicted action:",
    predicted_action_3b4a,
)


probability_df_3b4a = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probability_vector_3b4a,
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nSIX-CLASS R3 PROBABILITIES")
print("-" * 100)

display(
    probability_df_3b4a
)


# ==========================================================================================
# 12. Final validation
# ==========================================================================================

section3b4a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "parse_r3_categorical_feature available",

            "observed":
                callable(
                    globals().get(
                        "parse_r3_categorical_feature"
                    )
                ),

            "expected":
                True,

            "passed":
                callable(
                    globals().get(
                        "parse_r3_categorical_feature"
                    )
                ),
        },

        {
            "validation":
                "all encoder helper dependencies resolved",

            "observed":
                remaining_missing_3b4a,

            "expected":
                [],

            "passed":
                len(
                    remaining_missing_3b4a
                )
                == 0,
        },

        {
            "validation":
                "correct frozen model expects 46",

            "observed":
                r3_live_model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_live_model.n_features_in_
                ==
                46,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b4a.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_r3_row_3b4a.shape
                ==
                (1, 46),
        },

        {
            "validation":
                "exact encoded feature order",

            "observed":
                encoded_order_exact_3b4a,

            "expected":
                True,

            "passed":
                encoded_order_exact_3b4a,
        },

        {
            "validation":
                "single prediction returned",

            "observed":
                len(
                    prediction_3b4a
                ),

            "expected":
                1,

            "passed":
                len(
                    prediction_3b4a
                )
                ==
                1,
        },

        {
            "validation":
                "six class probabilities",

            "observed":
                len(
                    probability_vector_3b4a
                ),

            "expected":
                6,

            "passed":
                len(
                    probability_vector_3b4a
                )
                ==
                6,
        },

        {
            "validation":
                "probabilities sum to one",

            "observed":
                float(
                    np.sum(
                        probability_vector_3b4a
                    )
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    np.sum(
                        probability_vector_3b4a
                    ),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B.4A VALIDATION")
print("-" * 100)

display(
    section3b4a_validation_df
)


assert (
    section3b4a_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 59 ENCODER HELPERS RECOVERED")
print("✅ parse_r3_categorical_feature() RESTORED")
print("✅ CORRECT 46-FEATURE R3 MODEL REMAINS BOUND")
print("✅ 41 → 46 ENCODING EXECUTED")
print("✅ EXACT ENCODED ORDER VERIFIED")
print("✅ FROZEN R3 PREDICTION EXECUTED")
print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
print("✅ SECTION 3B.4A COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.4A — RECOVER EXACT NOTEBOOK 59 ENCODER HELPERS AND RETRY 41 → 46
====================================================================================================

ENCODER GLOBAL DEPENDENCY STATUS
----------------------------------------------------------------------------------------------------
Referenced names: ['DataFrame', 'R3_CATEGORICAL_FEATURES', 'R3_ENCODED_FEATURE_NAMES', 'R3_NUMERIC_FEATURES', 'all', 'columns', 'float', 'iloc', 'index', 'isfinite', 'isinstance', 'isna', 'len', 'list', 'np', 'parse_r3_categorical_feature', 'pd', 'shape', 'str', 'to_numeric', 'to_numpy']
Currently missing: ['DataFrame', 'columns', 'iloc', 'isfinite', 'isna', 'parse_r3_categorical_feature', 'shape', 'to_numeric', 'to_numpy']

NOTEBOOK 59 ENCODER HELPER INVENTORY
----------------------------------------------------------------------------------------------------

,name,found_in_notebook59,object_type,line_number,end_line
0,DataFrame,False,NOT_FOUND,NaN,NaN
1,columns,False,NOT_FOUND,NaN,NaN
2,iloc,False,NOT_FOUND,NaN,NaN
3,isfinite,False,NOT_FOUND,NaN,NaN
4,isna,False,NOT_FOUND,NaN,NaN
5,parse_r3_categorical_feature,True,FunctionDef,3193.0,3239.0
6,shape,False,NOT_FOUND,NaN,NaN
7,to_numeric,False,NOT_FOUND,NaN,NaN
8,to_numpy,False,NOT_FOUND,NaN,NaN

EXACT NOTEBOOK 59 HELPER SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
parse_r3_categorical_feature — line 3193
----------------------------------------------------------------------------------------------------
def parse_r3_categorical_feature(
    encoded_feature_name,
):
    """
    Convert for example

        categorical__active_card_Eevee

    into

        ("active_card", "Eevee")
    """

    assert encoded_feature_name.startswith(
        "categorical__"
    )

    encoded_body = encoded_feature_name[
        len("categorical__"):
    ]

    for source_column in (
        R3_CATEGORICAL_SOURCE_COLUMNS
    ):

        prefix = (
            source_column
            + "_"
        )

        if encoded_body.startswith(
            prefix
        ):

            category_value = encoded_body[
                len(prefix):
            ]

            return (
                source_column,
                category_value,
            )

    raise ValueError(
        "Unable to resolve categorical source "
        f"for encoded feature: {encoded_feature_name}"
    )

HELPER DEPENDENCY CLOSURE
----------------------------------------------------------------------------------------------------
['parse_r3_categorical_feature']

ENCODER HELPER LOAD RESULTS
----------------------------------------------------------------------------------------------------

                         helper  line_number  loaded  callable error
0  parse_r3_categorical_feature         3193    True      True  None

ENCODER DEPENDENCY RECHECK
----------------------------------------------------------------------------------------------------
Remaining missing globals: ['DataFrame', 'columns', 'iloc', 'isfinite', 'isna', 'shape', 'to_numeric', 'to_numpy']

AssertionError: Encoder still has unresolved globals:
DataFrame
columns
iloc
isfinite
isna
shape
to_numeric
to_numpy

In [41]:
# ==========================================================================================
# SECTION 3B.4B — CORRECT ENCODER GLOBAL AUDIT AND COMPLETE FROZEN R3 41 → 46 PATH
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.4B — CORRECT ENCODER GLOBAL AUDIT AND COMPLETE FROZEN R3 41 → 46 PATH")
print("=" * 100)

import ast
import builtins
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Explanation of the previous false-positive dependency report
# ==========================================================================================

print("\nDEPENDENCY AUDIT CORRECTION")
print("-" * 100)

print(
    "Section 3B.4A used function.__code__.co_names, which also contains "
    "attribute/method names such as DataFrame, columns, iloc, shape, "
    "to_numeric, to_numpy, isna, and isfinite."
)

print(
    "Those are NOT standalone globals. "
    "This section uses AST Name-load analysis instead."
)


# ==========================================================================================
# 2. Helper: identify TRUE external/global names from a function AST
# ==========================================================================================

def true_external_names_3b4b(
    function_node,
):

    local_names = set()

    # ------------------------------------------------------------------
    # Function parameters
    # ------------------------------------------------------------------

    for arg in function_node.args.args:
        local_names.add(
            arg.arg
        )

    for arg in function_node.args.kwonlyargs:
        local_names.add(
            arg.arg
        )

    if function_node.args.vararg is not None:

        local_names.add(
            function_node.args.vararg.arg
        )

    if function_node.args.kwarg is not None:

        local_names.add(
            function_node.args.kwarg.arg
        )


    # ------------------------------------------------------------------
    # Locally assigned names
    # ------------------------------------------------------------------

    for node in ast.walk(
        function_node
    ):

        if (
            isinstance(
                node,
                ast.Name,
            )
            and
            isinstance(
                node.ctx,
                (
                    ast.Store,
                    ast.Param,
                ),
            )
        ):

            local_names.add(
                node.id
            )


    # ------------------------------------------------------------------
    # Loaded names
    # ------------------------------------------------------------------

    loaded_names = {
        node.id
        for node in ast.walk(
            function_node
        )
        if (
            isinstance(
                node,
                ast.Name,
            )
            and
            isinstance(
                node.ctx,
                ast.Load,
            )
        )
    }


    return sorted(
        loaded_names
        -
        local_names
        -
        set(
            dir(
                builtins
            )
        )
    )


# ==========================================================================================
# 3. Parse exact Notebook 59 encoder source
# ==========================================================================================

encoder_ast_3b4b = ast.parse(
    encoder_source_3b
)


encoder_function_node_3b4b = next(
    node
    for node in encoder_ast_3b4b.body
    if isinstance(
        node,
        ast.FunctionDef,
    )
)


true_encoder_globals_3b4b = (
    true_external_names_3b4b(
        encoder_function_node_3b4b
    )
)


print("\nTRUE ENCODER GLOBAL REFERENCES")
print("-" * 100)

for name in true_encoder_globals_3b4b:
    print(
        "-",
        name,
    )


# ==========================================================================================
# 4. Inspect parse_r3_categorical_feature() using the same correct method
# ==========================================================================================

assert callable(
    globals().get(
        "parse_r3_categorical_feature"
    )
), (
    "parse_r3_categorical_feature() should have been recovered by 3B.4A."
)


parse_helper_node_3b4b = None


for node in tree_3a.body:

    if (
        isinstance(
            node,
            ast.FunctionDef,
        )
        and
        node.name
        ==
        "parse_r3_categorical_feature"
    ):

        parse_helper_node_3b4b = node
        break


assert (
    parse_helper_node_3b4b
    is not None
)


true_helper_globals_3b4b = (
    true_external_names_3b4b(
        parse_helper_node_3b4b
    )
)


print("\nTRUE parse_r3_categorical_feature() GLOBAL REFERENCES")
print("-" * 100)

for name in true_helper_globals_3b4b:
    print(
        "-",
        name,
    )


# ==========================================================================================
# 5. Combined real dependency set
# ==========================================================================================

REAL_REQUIRED_GLOBALS_3B4B = sorted(
    set(
        true_encoder_globals_3b4b
    )
    |
    set(
        true_helper_globals_3b4b
    )
)


real_dependency_rows_3b4b = []


for name in REAL_REQUIRED_GLOBALS_3B4B:

    available = (
        name in globals()
    )

    value = (
        globals().get(
            name
        )
        if available
        else None
    )

    real_dependency_rows_3b4b.append(
        {
            "name":
                name,

            "available":
                available,

            "object_type":
                (
                    type(
                        value
                    ).__name__
                    if available
                    else
                    "MISSING"
                ),
        }
    )


section3b4b_dependency_df = pd.DataFrame(
    real_dependency_rows_3b4b
)


print("\nREAL ENCODER DEPENDENCY STATUS")
print("-" * 100)

display(
    section3b4b_dependency_df
)


missing_real_globals_3b4b = (
    section3b4b_dependency_df.loc[
        ~section3b4b_dependency_df[
            "available"
        ].astype(bool),
        "name",
    ]
    .astype(str)
    .tolist()
)


print(
    "\nActually missing globals:",
    missing_real_globals_3b4b,
)


# ==========================================================================================
# 6. Build exact Notebook 59 top-level maps
# ==========================================================================================

definition_map_3b4b = {}

assignment_map_3b4b = {}


for node in tree_3a.body:

    # ------------------------------------------------------------------
    # Functions / classes
    # ------------------------------------------------------------------

    if isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
            ast.ClassDef,
        ),
    ):

        definition_map_3b4b[
            node.name
        ] = node


    # ------------------------------------------------------------------
    # Assignments
    # ------------------------------------------------------------------

    elif isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        targets = (
            node.targets
            if isinstance(
                node,
                ast.Assign,
            )
            else [
                node.target
            ]
        )

        for target in targets:

            if isinstance(
                target,
                ast.Name,
            ):

                assignment_map_3b4b[
                    target.id
                ] = node


# ==========================================================================================
# 7. Inventory sources for any truly missing globals
# ==========================================================================================

recovery_rows_3b4b = []


for name in missing_real_globals_3b4b:

    if name in assignment_map_3b4b:

        node = assignment_map_3b4b[
            name
        ]

        recovery_rows_3b4b.append(
            {
                "name":
                    name,

                "source_type":
                    "ASSIGNMENT",

                "line_number":
                    node.lineno,

                "found":
                    True,

                "source":
                    ast.get_source_segment(
                        source_3a,
                        node,
                    ),
            }
        )


    elif name in definition_map_3b4b:

        node = definition_map_3b4b[
            name
        ]

        recovery_rows_3b4b.append(
            {
                "name":
                    name,

                "source_type":
                    "DEFINITION",

                "line_number":
                    node.lineno,

                "found":
                    True,

                "source":
                    ast.get_source_segment(
                        source_3a,
                        node,
                    ),
            }
        )


    else:

        recovery_rows_3b4b.append(
            {
                "name":
                    name,

                "source_type":
                    "NOT_FOUND",

                "line_number":
                    None,

                "found":
                    False,

                "source":
                    None,
            }
        )


section3b4b_recovery_df = pd.DataFrame(
    recovery_rows_3b4b
)


print("\nMISSING GLOBAL SOURCE INVENTORY")
print("-" * 100)

if not section3b4b_recovery_df.empty:

    display(
        section3b4b_recovery_df[
            [
                "name",
                "source_type",
                "line_number",
                "found",
            ]
        ]
    )

else:

    print(
        "No actual encoder globals require recovery."
    )


# ==========================================================================================
# 8. Print exact sources before executing
# ==========================================================================================

if not section3b4b_recovery_df.empty:

    print("\nEXACT NOTEBOOK 59 SOURCES TO RECOVER")
    print("-" * 100)


    for _, row in (
        section3b4b_recovery_df
        .loc[
            section3b4b_recovery_df[
                "found"
            ].astype(bool)
        ]
        .iterrows()
    ):

        print("\n" + "=" * 100)

        print(
            f"{row['name']} "
            f"— {row['source_type']} "
            f"— line {row['line_number']}"
        )

        print("-" * 100)

        print(
            row[
                "source"
            ]
        )


# ==========================================================================================
# 9. Recover exact missing Notebook 59 globals in source order
# ==========================================================================================

nodes_to_execute_3b4b = []


for name in missing_real_globals_3b4b:

    node = (
        assignment_map_3b4b.get(
            name
        )
        or
        definition_map_3b4b.get(
            name
        )
    )

    if node is not None:

        if node not in nodes_to_execute_3b4b:

            nodes_to_execute_3b4b.append(
                node
            )


nodes_to_execute_3b4b = sorted(
    nodes_to_execute_3b4b,
    key=lambda node:
        node.lineno,
)


load_rows_3b4b = []


for node in nodes_to_execute_3b4b:

    module = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )


    try:

        exec(
            compile(
                module,
                filename="notebook59_exact_encoder_global_recovery",
                mode="exec",
            ),
            globals(),
        )

        load_rows_3b4b.append(
            {
                "line_number":
                    node.lineno,

                "loaded":
                    True,

                "error":
                    None,
            }
        )


    except Exception as exc:

        load_rows_3b4b.append(
            {
                "line_number":
                    node.lineno,

                "loaded":
                    False,

                "error":
                    f"{type(exc).__name__}: {exc}",
            }
        )


section3b4b_load_df = pd.DataFrame(
    load_rows_3b4b
)


if not section3b4b_load_df.empty:

    print("\nEXACT GLOBAL LOAD RESULTS")
    print("-" * 100)

    display(
        section3b4b_load_df
    )


# ==========================================================================================
# 10. Final dependency recheck using ONLY true AST globals
# ==========================================================================================

remaining_real_missing_3b4b = []


for name in REAL_REQUIRED_GLOBALS_3B4B:

    if name not in globals():

        remaining_real_missing_3b4b.append(
            name
        )


print("\nCORRECTED DEPENDENCY RECHECK")
print("-" * 100)

print(
    "Remaining REAL missing globals:",
    remaining_real_missing_3b4b,
)


assert (
    len(
        remaining_real_missing_3b4b
    )
    == 0
), (
    "Actual encoder globals remain unresolved:\n"
    + "\n".join(
        remaining_real_missing_3b4b
    )
)


# ==========================================================================================
# 11. Preserve exact frozen Notebook 59 contracts
# ==========================================================================================

assert (
    r3_live_package.get(
        "strategy_id"
    )
    ==
    "R3_STATE_CENTRIC_POLICY"
)


assert (
    type(
        r3_live_model
    ).__name__
    ==
    "RandomForestClassifier"
)


assert (
    r3_live_model.n_features_in_
    ==
    46
)


assert (
    len(
        R3_ENCODED_FEATURE_NAMES
    )
    ==
    46
)


assert (
    len(
        R3_NUMERIC_FEATURES
    )
    ==
    19
)


assert (
    len(
        R3_CATEGORICAL_FEATURES
    )
    ==
    27
)


print("\nFROZEN R3 CONTRACT BEFORE ENCODING")
print("-" * 100)

print(
    "Strategy               :",
    r3_live_package.get(
        "strategy_id"
    )
)

print(
    "Model type             :",
    type(
        r3_live_model
    ).__name__,
)

print(
    "Model input features   :",
    r3_live_model.n_features_in_,
)

print(
    "Encoded feature names  :",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)

print(
    "Numeric encoded        :",
    len(
        R3_NUMERIC_FEATURES
    ),
)

print(
    "Categorical encoded    :",
    len(
        R3_CATEGORICAL_FEATURES
    ),
)


# ==========================================================================================
# 12. Execute exact production encoder
# ==========================================================================================

print("\nEXECUTING EXACT 41 → 46 ENCODER")
print("-" * 100)


encoded_r3_row_3b4b = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type  :",
    type(
        encoded_r3_row_3b4b
    ).__name__,
)

print(
    "Shape :",
    encoded_r3_row_3b4b.shape,
)


display(
    encoded_r3_row_3b4b
)


# ==========================================================================================
# 13. Exact encoded matrix integrity
# ==========================================================================================

encoded_order_exact_3b4b = (
    list(
        encoded_r3_row_3b4b.columns
    )
    ==
    list(
        R3_ENCODED_FEATURE_NAMES
    )
)


encoded_all_finite_3b4b = bool(
    np.isfinite(
        encoded_r3_row_3b4b.to_numpy(
            dtype=float
        )
    ).all()
)


print("\nENCODED MATRIX INTEGRITY")
print("-" * 100)

print(
    "Shape             :",
    encoded_r3_row_3b4b.shape,
)

print(
    "Exact column order:",
    encoded_order_exact_3b4b,
)

print(
    "All values finite :",
    encoded_all_finite_3b4b,
)


# ==========================================================================================
# 14. Run frozen R3 prediction
# ==========================================================================================

print("\nRUNNING FROZEN R3 MODEL")
print("-" * 100)


prediction_3b4b = (
    r3_live_model.predict(
        encoded_r3_row_3b4b
    )
)


probabilities_3b4b = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b4b
    )
)


predicted_action_3b4b = (
    prediction_3b4b[
        0
    ]
)


probability_vector_3b4b = (
    probabilities_3b4b[
        0
    ]
)


print(
    "Predicted action:",
    predicted_action_3b4b,
)


section3b4b_probability_df = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probability_vector_3b4b,
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nFROZEN R3 SIX-CLASS PROBABILITIES")
print("-" * 100)

display(
    section3b4b_probability_df
)


# ==========================================================================================
# 15. Final validation
# ==========================================================================================

section3b4b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exact R3 production package",

            "observed":
                r3_live_package.get(
                    "strategy_id"
                ),

            "expected":
                "R3_STATE_CENTRIC_POLICY",

            "passed":
                r3_live_package.get(
                    "strategy_id"
                )
                ==
                "R3_STATE_CENTRIC_POLICY",
        },

        {
            "validation":
                "correct frozen model input count",

            "observed":
                r3_live_model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_live_model.n_features_in_
                ==
                46,
        },

        {
            "validation":
                "exact encoder helper callable",

            "observed":
                callable(
                    parse_r3_categorical_feature
                ),

            "expected":
                True,

            "passed":
                callable(
                    parse_r3_categorical_feature
                ),
        },

        {
            "validation":
                "all TRUE encoder globals available",

            "observed":
                remaining_real_missing_3b4b,

            "expected":
                [],

            "passed":
                len(
                    remaining_real_missing_3b4b
                )
                == 0,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b4b.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_r3_row_3b4b.shape
                ==
                (1, 46),
        },

        {
            "validation":
                "exact encoded feature order",

            "observed":
                encoded_order_exact_3b4b,

            "expected":
                True,

            "passed":
                encoded_order_exact_3b4b,
        },

        {
            "validation":
                "encoded values finite",

            "observed":
                encoded_all_finite_3b4b,

            "expected":
                True,

            "passed":
                encoded_all_finite_3b4b,
        },

        {
            "validation":
                "single prediction returned",

            "observed":
                len(
                    prediction_3b4b
                ),

            "expected":
                1,

            "passed":
                len(
                    prediction_3b4b
                )
                ==
                1,
        },

        {
            "validation":
                "six class probabilities",

            "observed":
                len(
                    probability_vector_3b4b
                ),

            "expected":
                6,

            "passed":
                len(
                    probability_vector_3b4b
                )
                ==
                6,
        },

        {
            "validation":
                "probability sum equals one",

            "observed":
                float(
                    probability_vector_3b4b.sum()
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    probability_vector_3b4b.sum(),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B.4B VALIDATION")
print("-" * 100)

display(
    section3b4b_validation_df
)


assert (
    section3b4b_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ PREVIOUS ATTRIBUTE FALSE POSITIVES REMOVED")
print("✅ TRUE ENCODER GLOBAL DEPENDENCIES VERIFIED")
print("✅ EXACT NOTEBOOK 59 CATEGORICAL PARSER PRESERVED")
print("✅ EXACT 46-FEATURE R3 MODEL PRESERVED")
print("✅ EXACT 41 → 46 ENCODING EXECUTED")
print("✅ ENCODED ORDER AND FINITE VALUES VERIFIED")
print("✅ FROZEN RANDOM FOREST PREDICTION EXECUTED")
print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
print("✅ SECTION 3B.4B COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.4B — CORRECT ENCODER GLOBAL AUDIT AND COMPLETE FROZEN R3 41 → 46 PATH
====================================================================================================

DEPENDENCY AUDIT CORRECTION
----------------------------------------------------------------------------------------------------
Section 3B.4A used function.__code__.co_names, which also contains attribute/method names such as DataFrame, columns, iloc, shape, to_numeric, to_numpy, isna, and isfinite.
Those are NOT standalone globals. This section uses AST Name-load analysis instead.

TRUE ENCODER GLOBAL REFERENCES
----------------------------------------------------------------------------------------------------
- R3_CATEGORICAL_FEATURES
- R3_ENCODED_FEATURE_NAMES
- R3_NUMERIC_FEATURES
- np
- parse_r3_categorical_feature
- pd

TRUE parse_r3_categorical_feature() GLOBAL REFERENCES
----------------------------------------------------------------------------------------------------
- R3_CATEGORICAL_SOURCE_COLUMNS

REAL ENCODER DEPENDENCY STATUS
----------------------------------------------------------------------------------------------------

                            name  available object_type
0        R3_CATEGORICAL_FEATURES       True        list
1  R3_CATEGORICAL_SOURCE_COLUMNS      False     MISSING
2       R3_ENCODED_FEATURE_NAMES       True        list
3            R3_NUMERIC_FEATURES       True        list
4                             np       True      module
5   parse_r3_categorical_feature       True    function
6                             pd       True      module

Actually missing globals: ['R3_CATEGORICAL_SOURCE_COLUMNS']

MISSING GLOBAL SOURCE INVENTORY
----------------------------------------------------------------------------------------------------

                            name source_type  line_number  found
0  R3_CATEGORICAL_SOURCE_COLUMNS  ASSIGNMENT         3183   True

EXACT NOTEBOOK 59 SOURCES TO RECOVER
----------------------------------------------------------------------------------------------------

====================================================================================================
R3_CATEGORICAL_SOURCE_COLUMNS — ASSIGNMENT — line 3183
----------------------------------------------------------------------------------------------------
R3_CATEGORICAL_SOURCE_COLUMNS = sorted(
    R3_CATEGORICAL_SOURCE_COLUMNS,
    key=len,
    reverse=True,
)

EXACT GLOBAL LOAD RESULTS
----------------------------------------------------------------------------------------------------

   line_number  loaded                                              error
0         3183   False  NameError: name 'R3_CATEGORICAL_SOURCE_COLUMNS...

CORRECTED DEPENDENCY RECHECK
----------------------------------------------------------------------------------------------------
Remaining REAL missing globals: ['R3_CATEGORICAL_SOURCE_COLUMNS']

AssertionError: Actual encoder globals remain unresolved:
R3_CATEGORICAL_SOURCE_COLUMNS

In [42]:
# ==========================================================================================
# SECTION 3B.4C — RECOVER COMPLETE R3_CATEGORICAL_SOURCE_COLUMNS ASSIGNMENT CHAIN
# ==========================================================================================

print("=" * 100)
print("SECTION 3B.4C — RECOVER COMPLETE R3_CATEGORICAL_SOURCE_COLUMNS ASSIGNMENT CHAIN")
print("=" * 100)

import ast
import pandas as pd
import numpy as np


TARGET_3B4C = (
    "R3_CATEGORICAL_SOURCE_COLUMNS"
)


# ==========================================================================================
# 1. Locate EVERY top-level assignment to the target in Notebook 59
# ==========================================================================================

assignment_chain_3b4c = []


for node in tree_3a.body:

    if not isinstance(
        node,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):
        continue


    targets = (
        node.targets
        if isinstance(
            node,
            ast.Assign,
        )
        else [
            node.target
        ]
    )


    assigned_names = []

    for target in targets:

        if isinstance(
            target,
            ast.Name,
        ):

            assigned_names.append(
                target.id
            )


    if TARGET_3B4C not in assigned_names:
        continue


    source_segment = (
        ast.get_source_segment(
            source_3a,
            node,
        )
    )


    # ------------------------------------------------------------------
    # Detect whether the assignment reads itself on the RHS
    # ------------------------------------------------------------------

    loaded_names = {
        child.id
        for child in ast.walk(
            node
        )
        if (
            isinstance(
                child,
                ast.Name,
            )
            and
            isinstance(
                child.ctx,
                ast.Load,
            )
        )
    }


    assignment_chain_3b4c.append(
        {
            "line_number":
                node.lineno,

            "end_line":
                getattr(
                    node,
                    "end_lineno",
                    None,
                ),

            "self_referential":
                TARGET_3B4C
                in loaded_names,

            "node":
                node,

            "source":
                source_segment,
        }
    )


assignment_chain_3b4c = sorted(
    assignment_chain_3b4c,
    key=lambda row:
        row[
            "line_number"
        ],
)


section3b4c_assignment_df = pd.DataFrame(
    [
        {
            "sequence":
                index,

            "line_number":
                row[
                    "line_number"
                ],

            "end_line":
                row[
                    "end_line"
                ],

            "self_referential":
                row[
                    "self_referential"
                ],
        }

        for index, row in enumerate(
            assignment_chain_3b4c,
            start=1,
        )
    ]
)


print("\nCOMPLETE NOTEBOOK 59 ASSIGNMENT CHAIN")
print("-" * 100)

display(
    section3b4c_assignment_df
)


assert (
    len(
        assignment_chain_3b4c
    )
    >= 2
), (
    "Expected an earlier initializer plus the later sorting assignment. "
    "Do not fabricate R3_CATEGORICAL_SOURCE_COLUMNS."
)


# ==========================================================================================
# 2. Print every exact assignment before execution
# ==========================================================================================

print("\nEXACT NOTEBOOK 59 SOURCES")
print("-" * 100)


for index, row in enumerate(
    assignment_chain_3b4c,
    start=1,
):

    print("\n" + "=" * 100)

    print(
        f"ASSIGNMENT {index}"
    )

    print(
        "Lines:",
        row[
            "line_number"
        ],
        "-",
        row[
            "end_line"
        ],
    )

    print(
        "Self-referential:",
        row[
            "self_referential"
        ],
    )

    print("-" * 100)

    print(
        row[
            "source"
        ]
    )


# ==========================================================================================
# 3. Confirm there is an initializer BEFORE the self-referential sort
# ==========================================================================================

initializer_rows_3b4c = [
    row
    for row in assignment_chain_3b4c
    if not row[
        "self_referential"
    ]
]


sorting_rows_3b4c = [
    row
    for row in assignment_chain_3b4c
    if row[
        "self_referential"
    ]
]


print("\nASSIGNMENT STRUCTURE")
print("-" * 100)

print(
    "Initializer assignments:",
    len(
        initializer_rows_3b4c
    ),
)

print(
    "Self-referential transforms:",
    len(
        sorting_rows_3b4c
    ),
)


assert (
    len(
        initializer_rows_3b4c
    )
    >= 1
), (
    "No original Notebook 59 initializer was found."
)


assert (
    initializer_rows_3b4c[
        0
    ][
        "line_number"
    ]
    <
    sorting_rows_3b4c[
        0
    ][
        "line_number"
    ]
), (
    "Notebook 59 source order is not initializer → transformation."
)


# ==========================================================================================
# 4. Clear ONLY the incomplete target variable
# ==========================================================================================

if TARGET_3B4C in globals():

    del globals()[
        TARGET_3B4C
    ]


print("\nTARGET CLEARED FOR CLEAN SOURCE-ORDER RECOVERY")
print("-" * 100)

print(
    TARGET_3B4C,
    "present:",
    TARGET_3B4C
    in globals(),
)


# ==========================================================================================
# 5. Execute ALL exact assignments in original Notebook 59 order
# ==========================================================================================

execution_rows_3b4c = []


for sequence, row in enumerate(
    assignment_chain_3b4c,
    start=1,
):

    node = row[
        "node"
    ]


    module = ast.Module(
        body=[
            node
        ],
        type_ignores=[],
    )

    ast.fix_missing_locations(
        module
    )


    try:

        exec(
            compile(
                module,
                filename=(
                    "notebook59_r3_categorical_source_columns_recovery"
                ),
                mode="exec",
            ),
            globals(),
        )


        current_value = globals().get(
            TARGET_3B4C
        )


        execution_rows_3b4c.append(
            {
                "sequence":
                    sequence,

                "line_number":
                    row[
                        "line_number"
                    ],

                "loaded":
                    TARGET_3B4C
                    in globals(),

                "object_type":
                    (
                        type(
                            current_value
                        ).__name__
                        if TARGET_3B4C
                        in globals()
                        else
                        "MISSING"
                    ),

                "count":
                    (
                        len(
                            current_value
                        )
                        if isinstance(
                            current_value,
                            (
                                list,
                                tuple,
                            ),
                        )
                        else
                        None
                    ),

                "error":
                    None,
            }
        )


    except Exception as exc:

        execution_rows_3b4c.append(
            {
                "sequence":
                    sequence,

                "line_number":
                    row[
                        "line_number"
                    ],

                "loaded":
                    False,

                "object_type":
                    "MISSING",

                "count":
                    None,

                "error":
                    (
                        f"{type(exc).__name__}: "
                        f"{exc}"
                    ),
            }
        )

        raise


section3b4c_execution_df = pd.DataFrame(
    execution_rows_3b4c
)


print("\nSOURCE-ORDER EXECUTION RESULTS")
print("-" * 100)

display(
    section3b4c_execution_df
)


# ==========================================================================================
# 6. Inspect recovered categorical source columns
# ==========================================================================================

assert (
    TARGET_3B4C
    in globals()
)


assert isinstance(
    R3_CATEGORICAL_SOURCE_COLUMNS,
    list,
)


print("\nRECOVERED R3 CATEGORICAL SOURCE COLUMNS")
print("-" * 100)


for index, column_name in enumerate(
    R3_CATEGORICAL_SOURCE_COLUMNS,
    start=1,
):

    print(
        f"{index:02d}. {column_name}"
    )


print(
    "\nCount:",
    len(
        R3_CATEGORICAL_SOURCE_COLUMNS
    )
)


# ==========================================================================================
# 7. Verify each categorical encoded feature can now be parsed
# ==========================================================================================

categorical_parse_rows_3b4c = []


for encoded_name in (
    R3_CATEGORICAL_FEATURES
):

    try:

        source_column, category_value = (
            parse_r3_categorical_feature(
                encoded_name
            )
        )


        categorical_parse_rows_3b4c.append(
            {
                "encoded_feature":
                    encoded_name,

                "source_column":
                    source_column,

                "category_value":
                    category_value,

                "source_exists_in_raw":
                    source_column
                    in raw_feature_row_3a5.columns,

                "parsed":
                    True,

                "error":
                    None,
            }
        )


    except Exception as exc:

        categorical_parse_rows_3b4c.append(
            {
                "encoded_feature":
                    encoded_name,

                "source_column":
                    None,

                "category_value":
                    None,

                "source_exists_in_raw":
                    False,

                "parsed":
                    False,

                "error":
                    (
                        f"{type(exc).__name__}: "
                        f"{exc}"
                    ),
            }
        )


section3b4c_parse_df = pd.DataFrame(
    categorical_parse_rows_3b4c
)


print("\n27 CATEGORICAL ENCODED FEATURES → RAW SOURCE CHECK")
print("-" * 100)

display(
    section3b4c_parse_df
)


all_categorical_parse_ok_3b4c = bool(
    section3b4c_parse_df[
        "parsed"
    ].all()
)


all_categorical_sources_present_3b4c = bool(
    section3b4c_parse_df[
        "source_exists_in_raw"
    ].all()
)


# ==========================================================================================
# 8. Reconfirm correct frozen model before encoder execution
# ==========================================================================================

print("\nFROZEN R3 CONTRACT")
print("-" * 100)

print(
    "Strategy:",
    r3_live_package.get(
        "strategy_id"
    ),
)

print(
    "Model:",
    type(
        r3_live_model
    ).__name__,
)

print(
    "Model features:",
    r3_live_model.n_features_in_,
)

print(
    "Encoded contract:",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)

print(
    "Numeric:",
    len(
        R3_NUMERIC_FEATURES
    ),
)

print(
    "Categorical:",
    len(
        R3_CATEGORICAL_FEATURES
    ),
)


assert (
    r3_live_model.n_features_in_
    ==
    46
)

assert (
    len(
        R3_ENCODED_FEATURE_NAMES
    )
    ==
    46
)

assert (
    len(
        R3_NUMERIC_FEATURES
    )
    ==
    19
)

assert (
    len(
        R3_CATEGORICAL_FEATURES
    )
    ==
    27
)


# ==========================================================================================
# 9. Execute exact 41 → 46 Notebook 59 encoder
# ==========================================================================================

print("\nEXECUTING EXACT 41 → 46 ENCODER")
print("-" * 100)


encoded_r3_row_3b4c = (
    encode_r3_feature_row(
        raw_feature_row_3a5
    )
)


print(
    "Type  :",
    type(
        encoded_r3_row_3b4c
    ).__name__,
)

print(
    "Shape :",
    encoded_r3_row_3b4c.shape,
)


display(
    encoded_r3_row_3b4c
)


# ==========================================================================================
# 10. Exact encoded matrix verification
# ==========================================================================================

encoded_order_exact_3b4c = (
    encoded_r3_row_3b4c
    .columns
    .tolist()
    ==
    list(
        R3_ENCODED_FEATURE_NAMES
    )
)


encoded_values_finite_3b4c = bool(
    np.isfinite(
        encoded_r3_row_3b4c
        .to_numpy(
            dtype=float
        )
    ).all()
)


print("\nENCODED MATRIX VALIDATION")
print("-" * 100)

print(
    "Expected shape    :",
    (1, 46),
)

print(
    "Observed shape    :",
    encoded_r3_row_3b4c.shape,
)

print(
    "Exact order       :",
    encoded_order_exact_3b4c,
)

print(
    "All values finite :",
    encoded_values_finite_3b4c,
)


# ==========================================================================================
# 11. Execute frozen production Random Forest
# ==========================================================================================

print("\nRUNNING FROZEN R3 RANDOM FOREST")
print("-" * 100)


prediction_3b4c = (
    r3_live_model.predict(
        encoded_r3_row_3b4c
    )
)


probabilities_3b4c = (
    r3_live_model.predict_proba(
        encoded_r3_row_3b4c
    )
)


predicted_action_3b4c = (
    prediction_3b4c[
        0
    ]
)


probability_vector_3b4c = (
    probabilities_3b4c[
        0
    ]
)


print(
    "Predicted action:",
    predicted_action_3b4c,
)


section3b4c_probability_df = pd.DataFrame(
    {
        "action":
            list(
                r3_live_model.classes_
            ),

        "probability":
            probability_vector_3b4c,
    }
).sort_values(
    "probability",
    ascending=False,
).reset_index(
    drop=True
)


print("\nSIX-CLASS R3 PROBABILITY VECTOR")
print("-" * 100)

display(
    section3b4c_probability_df
)


# ==========================================================================================
# 12. Final validation
# ==========================================================================================

section3b4c_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "initializer recovered",

            "observed":
                len(
                    initializer_rows_3b4c
                ),

            "expected":
                ">= 1",

            "passed":
                len(
                    initializer_rows_3b4c
                )
                >= 1,
        },

        {
            "validation":
                "categorical source list available",

            "observed":
                isinstance(
                    R3_CATEGORICAL_SOURCE_COLUMNS,
                    list,
                ),

            "expected":
                True,

            "passed":
                isinstance(
                    R3_CATEGORICAL_SOURCE_COLUMNS,
                    list,
                ),
        },

        {
            "validation":
                "all 27 categorical encodings parse",

            "observed":
                all_categorical_parse_ok_3b4c,

            "expected":
                True,

            "passed":
                all_categorical_parse_ok_3b4c,
        },

        {
            "validation":
                "all categorical sources in raw row",

            "observed":
                all_categorical_sources_present_3b4c,

            "expected":
                True,

            "passed":
                all_categorical_sources_present_3b4c,
        },

        {
            "validation":
                "correct model input count",

            "observed":
                r3_live_model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_live_model.n_features_in_
                ==
                46,
        },

        {
            "validation":
                "encoded matrix shape",

            "observed":
                encoded_r3_row_3b4c.shape,

            "expected":
                (1, 46),

            "passed":
                encoded_r3_row_3b4c.shape
                ==
                (1, 46),
        },

        {
            "validation":
                "exact encoded column order",

            "observed":
                encoded_order_exact_3b4c,

            "expected":
                True,

            "passed":
                encoded_order_exact_3b4c,
        },

        {
            "validation":
                "encoded values finite",

            "observed":
                encoded_values_finite_3b4c,

            "expected":
                True,

            "passed":
                encoded_values_finite_3b4c,
        },

        {
            "validation":
                "single prediction",

            "observed":
                len(
                    prediction_3b4c
                ),

            "expected":
                1,

            "passed":
                len(
                    prediction_3b4c
                )
                ==
                1,
        },

        {
            "validation":
                "six probability values",

            "observed":
                len(
                    probability_vector_3b4c
                ),

            "expected":
                6,

            "passed":
                len(
                    probability_vector_3b4c
                )
                ==
                6,
        },

        {
            "validation":
                "probability vector sums to one",

            "observed":
                float(
                    probability_vector_3b4c.sum()
                ),

            "expected":
                1.0,

            "passed":
                np.isclose(
                    probability_vector_3b4c.sum(),
                    1.0,
                ),
        },
    ]
)


print("\nSECTION 3B.4C VALIDATION")
print("-" * 100)

display(
    section3b4c_validation_df
)


assert (
    section3b4c_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ ORIGINAL NOTEBOOK 59 CATEGORICAL SOURCE LIST RECOVERED")
print("✅ SELF-REFERENTIAL SORT EXECUTED IN CORRECT SOURCE ORDER")
print("✅ ALL 27 CATEGORICAL ENCODINGS RESOLVED")
print("✅ EXACT 41 → 46 ENCODER EXECUTED")
print("✅ EXACT 46-COLUMN ORDER VERIFIED")
print("✅ CORRECT FROZEN R3 RANDOM FOREST EXECUTED")
print("✅ SIX-CLASS PROBABILITY VECTOR VERIFIED")
print("✅ SECTION 3B COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3B.4C — RECOVER COMPLETE R3_CATEGORICAL_SOURCE_COLUMNS ASSIGNMENT CHAIN
====================================================================================================

COMPLETE NOTEBOOK 59 ASSIGNMENT CHAIN
----------------------------------------------------------------------------------------------------

   sequence  line_number  end_line  self_referential
0         1         3169      3179             False
1         2         3183      3187              True

EXACT NOTEBOOK 59 SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
ASSIGNMENT 1
Lines: 3169 - 3179
Self-referential: False
----------------------------------------------------------------------------------------------------
R3_CATEGORICAL_SOURCE_COLUMNS = [
    "current_side",
    "side_mode",
    "player_card",
    "opponent_card",
    "active_card",
    "inactive_card",
    "battle_phase",
    "energy_band",
    "damage_band",
]

====================================================================================================
ASSIGNMENT 2
Lines: 3183 - 3187
Self-referential: True
----------------------------------------------------------------------------------------------------
R3_CATEGORICAL_SOURCE_COLUMNS = sorted(
    R3_CATEGORICAL_SOURCE_COLUMNS,
    key=len,
    reverse=True,
)

ASSIGNMENT STRUCTURE
----------------------------------------------------------------------------------------------------
Initializer assignments: 1
Self-referential transforms: 1

TARGET CLEARED FOR CLEAN SOURCE-ORDER RECOVERY
----------------------------------------------------------------------------------------------------
R3_CATEGORICAL_SOURCE_COLUMNS present: False

SOURCE-ORDER EXECUTION RESULTS
----------------------------------------------------------------------------------------------------

   sequence  line_number  loaded object_type  count error
0         1         3169    True        list      9  None
1         2         3183    True        list      9  None

RECOVERED R3 CATEGORICAL SOURCE COLUMNS
----------------------------------------------------------------------------------------------------
01. opponent_card
02. inactive_card
03. current_side
04. battle_phase
05. player_card
06. active_card
07. energy_band
08. damage_band
09. side_mode

Count: 9

27 CATEGORICAL ENCODED FEATURES → RAW SOURCE CHECK
----------------------------------------------------------------------------------------------------

,encoded_feature,source_column,category_value,source_exists_in_raw,parsed,error
0,categorical__current_side_Opponent,current_side,Opponent,True,True,None
1,categorical__current_side_Player,current_side,Player,True,True,None
2,categorical__side_mode_FLIP,side_mode,FLIP,True,True,None
3,categorical__side_mode_PRESERVE,side_mode,PRESERVE,True,True,None
4,categorical__player_card_Bulbasaur,player_card,Bulbasaur,True,True,None
5,categorical__player_card_Charmander,player_card,Charmander,True,True,None
6,categorical__player_card_Eevee,player_card,Eevee,True,True,None
7,categorical__player_card_Meowth,player_card,Meowth,True,True,None
8,categorical__opponent_card_Charmander,opponent_card,Charmander,True,True,None
9,categorical__opponent_card_Eevee,opponent_card,Eevee,True,True,None
10,categorical__active_card_Bulbasaur,active_card,Bulbasaur,True,True,None
11,categorical__active_card_Charmander,active_card,Charmander,True,True,None
12,categorical__active_card_Eevee,active_card,Eevee,True,True,None
13,categorical__active_card_Meowth,active_card,Meowth,True,True,None
14,categorical__inactive_card_Bulbasaur,inactive_card,Bulbasaur,True,True,None
15,categorical__inactive_card_Charmander,inactive_card,Charmander,True,True,None
16,categorical__inactive_card_Eevee,inactive_card,Eevee,True,True,None
17,categorical__inactive_card_Meowth,inactive_card,Meowth,True,True,None
18,categorical__battle_phase_EARLY,battle_phase,EARLY,True,True,None
19,categorical__battle_phase_LATE,battle_phase,LATE,True,True,None
20,categorical__battle_phase_MID,battle_phase,MID,True,True,None
21,categorical__energy_band_LOW,energy_band,LOW,True,True,None
22,categorical__energy_band_READY,energy_band,READY,True,True,None
23,categorical__energy_band_ZERO,energy_band,ZERO,True,True,None
24,categorical__damage_band_HIGH_DAMAGE,damage_band,HIGH_DAMAGE,True,True,None
25,categorical__damage_band_LOW_DAMAGE,damage_band,LOW_DAMAGE,True,True,None
26,categorical__damage_band_MEDIUM_DAMAGE,damage_band,MEDIUM_DAMAGE,True,True,None

FROZEN R3 CONTRACT
----------------------------------------------------------------------------------------------------
Strategy: R3_STATE_CENTRIC_POLICY
Model: RandomForestClassifier
Model features: 46
Encoded contract: 46
Numeric: 19
Categorical: 27

EXECUTING EXACT 41 → 46 ENCODER
----------------------------------------------------------------------------------------------------
Type  : DataFrame
Shape : (1, 46)

,numeric__turn_number,numeric__player_energy,numeric__opponent_energy,numeric__player_damage,numeric__opponent_damage,numeric__prize_cards_remaining,numeric__hand_size,numeric__recomputed_legal_move_count,numeric__acting_energy,numeric__defending_energy,...,categorical__inactive_card_Meowth,categorical__battle_phase_EARLY,categorical__battle_phase_LATE,categorical__battle_phase_MID,categorical__energy_band_LOW,categorical__energy_band_READY,categorical__energy_band_ZERO,categorical__damage_band_HIGH_DAMAGE,categorical__damage_band_LOW_DAMAGE,categorical__damage_band_MEDIUM_DAMAGE
0,3.0,3.0,3.0,0.0,0.0,6.0,7.0,2.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

ENCODED MATRIX VALIDATION
----------------------------------------------------------------------------------------------------
Expected shape    : (1, 46)
Observed shape    : (1, 46)
Exact order       : True
All values finite : True

RUNNING FROZEN R3 RANDOM FOREST
----------------------------------------------------------------------------------------------------
Predicted action: Quick Attack

SIX-CLASS R3 PROBABILITY VECTOR
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

         action  probability
0  Quick Attack        0.726
1     Ascension        0.120
2          Pass        0.090
3     Live Coal        0.036
4     Bind Down        0.028
5     Tuck Tail        0.000

SECTION 3B.4C VALIDATION
----------------------------------------------------------------------------------------------------

                            validation observed expected  passed
0                initializer recovered        1     >= 1    True
1    categorical source list available     True     True    True
2   all 27 categorical encodings parse     True     True    True
3   all categorical sources in raw row     True     True    True
4            correct model input count       46       46    True
5                 encoded matrix shape  (1, 46)  (1, 46)    True
6           exact encoded column order     True     True    True
7                encoded values finite     True     True    True
8                    single prediction        1        1    True
9               six probability values        6        6    True
10      probability vector sums to one      1.0      1.0    True

====================================================================================================
✅ ORIGINAL NOTEBOOK 59 CATEGORICAL SOURCE LIST RECOVERED
✅ SELF-REFERENTIAL SORT EXECUTED IN CORRECT SOURCE ORDER
✅ ALL 27 CATEGORICAL ENCODINGS RESOLVED
✅ EXACT 41 → 46 ENCODER EXECUTED
✅ EXACT 46-COLUMN ORDER VERIFIED
✅ CORRECT FROZEN R3 RANDOM FOREST EXECUTED
✅ SIX-CLASS PROBABILITY VECTOR VERIFIED
✅ SECTION 3B COMPLETE
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [43]:
# ==========================================================================================
# SECTION 3C.1 — RECOVER EXACT NOTEBOOK 59 R3 LEGALITY-MASK POLICY ENGINE CONTRACT
# ==========================================================================================

print("=" * 100)
print("SECTION 3C.1 — RECOVER EXACT NOTEBOOK 59 R3 LEGALITY-MASK POLICY ENGINE CONTRACT")
print("=" * 100)

import ast
import inspect
import pandas as pd


# ==========================================================================================
# 1. Locate exact R3LivePolicyEngine class in Notebook 59
# ==========================================================================================

TARGET_CLASS_3C1 = (
    "R3LivePolicyEngine"
)


r3_engine_class_node_3c1 = None


for node in tree_3a.body:

    if (
        isinstance(
            node,
            ast.ClassDef,
        )
        and
        node.name
        ==
        TARGET_CLASS_3C1
    ):

        r3_engine_class_node_3c1 = node
        break


assert (
    r3_engine_class_node_3c1
    is not None
), (
    "R3LivePolicyEngine class was not found in Notebook 59 source."
)


print("\nR3 LIVE POLICY ENGINE SOURCE LOCATION")
print("-" * 100)

print(
    "Class:",
    r3_engine_class_node_3c1.name,
)

print(
    "Start line:",
    r3_engine_class_node_3c1.lineno,
)

print(
    "End line:",
    r3_engine_class_node_3c1.end_lineno,
)


# ==========================================================================================
# 2. Inventory exact methods
# ==========================================================================================

method_rows_3c1 = []


for node in r3_engine_class_node_3c1.body:

    if not isinstance(
        node,
        (
            ast.FunctionDef,
            ast.AsyncFunctionDef,
        ),
    ):
        continue


    method_rows_3c1.append(
        {
            "method":
                node.name,

            "line_number":
                node.lineno,

            "end_line":
                node.end_lineno,

            "arguments":
                [
                    arg.arg
                    for arg in node.args.args
                ],
        }
    )


section3c1_method_df = pd.DataFrame(
    method_rows_3c1
)


print("\nR3 LIVE POLICY ENGINE METHODS")
print("-" * 100)

display(
    section3c1_method_df
)


# ==========================================================================================
# 3. Print exact constructor and decision-method source
# ==========================================================================================

IMPORTANT_METHODS_3C1 = [
    "__init__",
    "score_moves",
    "choose_move",
]


important_method_nodes_3c1 = {}


for node in r3_engine_class_node_3c1.body:

    if (
        isinstance(
            node,
            ast.FunctionDef,
        )
        and
        node.name
        in IMPORTANT_METHODS_3C1
    ):

        important_method_nodes_3c1[
            node.name
        ] = node


print("\nEXACT NOTEBOOK 59 POLICY METHOD SOURCES")
print("-" * 100)


for method_name in IMPORTANT_METHODS_3C1:

    node = important_method_nodes_3c1.get(
        method_name
    )

    if node is None:
        continue


    print("\n" + "=" * 100)

    print(
        method_name
    )

    print(
        f"Lines {node.lineno} - {node.end_lineno}"
    )

    print("-" * 100)

    print(
        ast.get_source_segment(
            source_3a,
            node,
        )
    )


# ==========================================================================================
# 4. Determine true external/global dependencies of the entire class
# ==========================================================================================

def class_external_names_3c1(
    class_node,
):

    loaded_names = {
        node.id
        for node in ast.walk(
            class_node
        )
        if (
            isinstance(
                node,
                ast.Name,
            )
            and
            isinstance(
                node.ctx,
                ast.Load,
            )
        )
    }


    local_names = {
        class_node.name
    }


    for method in class_node.body:

        if not isinstance(
            method,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        ):
            continue


        local_names.add(
            method.name
        )


        for arg in method.args.args:

            local_names.add(
                arg.arg
            )


        for child in ast.walk(
            method
        ):

            if (
                isinstance(
                    child,
                    ast.Name,
                )
                and
                isinstance(
                    child.ctx,
                    ast.Store,
                )
            ):

                local_names.add(
                    child.id
                )


    import builtins


    return sorted(
        loaded_names
        -
        local_names
        -
        set(
            dir(
                builtins
            )
        )
    )


external_names_3c1 = (
    class_external_names_3c1(
        r3_engine_class_node_3c1
    )
)


print("\nTRUE CLASS-LEVEL EXTERNAL DEPENDENCIES")
print("-" * 100)

for name in external_names_3c1:

    print(
        "-",
        name,
    )


# ==========================================================================================
# 5. Check which dependencies are already present in Notebook 60
# ==========================================================================================

dependency_rows_3c1 = []


for name in external_names_3c1:

    available = (
        name in globals()
    )


    dependency_rows_3c1.append(
        {
            "dependency":
                name,

            "available":
                available,

            "object_type":
                (
                    type(
                        globals().get(
                            name
                        )
                    ).__name__
                    if available
                    else
                    "MISSING"
                ),
        }
    )


section3c1_dependency_df = pd.DataFrame(
    dependency_rows_3c1
)


print("\nR3 POLICY ENGINE DEPENDENCY STATUS")
print("-" * 100)

display(
    section3c1_dependency_df
)


missing_dependencies_3c1 = (
    section3c1_dependency_df.loc[
        ~section3c1_dependency_df[
            "available"
        ].astype(bool),
        "dependency",
    ]
    .astype(str)
    .tolist()
)


print(
    "\nMissing dependencies:",
    missing_dependencies_3c1,
)


# ==========================================================================================
# 6. Locate Notebook 59 sources for missing dependencies
# ==========================================================================================

dependency_source_rows_3c1 = []


for dependency_name in (
    missing_dependencies_3c1
):

    matches = []


    for node in tree_3a.body:

        # ------------------------------------------------------------------
        # Definition
        # ------------------------------------------------------------------

        if (
            isinstance(
                node,
                (
                    ast.FunctionDef,
                    ast.ClassDef,
                ),
            )
            and
            node.name
            ==
            dependency_name
        ):

            matches.append(
                {
                    "dependency":
                        dependency_name,

                    "source_type":
                        type(
                            node
                        ).__name__,

                    "line_number":
                        node.lineno,

                    "end_line":
                        node.end_lineno,

                    "source":
                        ast.get_source_segment(
                            source_3a,
                            node,
                        ),
                }
            )


        # ------------------------------------------------------------------
        # Assignment
        # ------------------------------------------------------------------

        elif isinstance(
            node,
            (
                ast.Assign,
                ast.AnnAssign,
            ),
        ):

            targets = (
                node.targets
                if isinstance(
                    node,
                    ast.Assign,
                )
                else [
                    node.target
                ]
            )


            assigned_names = [
                target.id
                for target in targets
                if isinstance(
                    target,
                    ast.Name,
                )
            ]


            if (
                dependency_name
                in assigned_names
            ):

                matches.append(
                    {
                        "dependency":
                            dependency_name,

                        "source_type":
                            type(
                                node
                            ).__name__,

                        "line_number":
                            node.lineno,

                        "end_line":
                            node.end_lineno,

                        "source":
                            ast.get_source_segment(
                                source_3a,
                                node,
                            ),
                    }
                )


    if matches:

        dependency_source_rows_3c1.extend(
            matches
        )

    else:

        dependency_source_rows_3c1.append(
            {
                "dependency":
                    dependency_name,

                "source_type":
                    "NOT_FOUND",

                "line_number":
                    None,

                "end_line":
                    None,

                "source":
                    None,
            }
        )


section3c1_dependency_sources_df = pd.DataFrame(
    dependency_source_rows_3c1
)


print("\nNOTEBOOK 59 SOURCES FOR MISSING DEPENDENCIES")
print("-" * 100)

if not section3c1_dependency_sources_df.empty:

    display(
        section3c1_dependency_sources_df[
            [
                "dependency",
                "source_type",
                "line_number",
                "end_line",
            ]
        ]
    )


# ==========================================================================================
# 7. Inspect masking-related source statements inside score_moves()
# ==========================================================================================

score_moves_node_3c1 = (
    important_method_nodes_3c1.get(
        "score_moves"
    )
)


masking_lines_3c1 = []


if score_moves_node_3c1 is not None:

    score_source_lines_3c1 = (
        ast.get_source_segment(
            source_3a,
            score_moves_node_3c1,
        )
        .splitlines()
    )


    MASK_TERMS_3C1 = [
        "legal",
        "probab",
        "fallback",
        "mask",
        "renorm",
        "class",
        "selected",
        "sum",
    ]


    for offset, line in enumerate(
        score_source_lines_3c1,
        start=score_moves_node_3c1.lineno,
    ):

        if any(
            term
            in line.lower()
            for term in MASK_TERMS_3C1
        ):

            masking_lines_3c1.append(
                {
                    "line_number":
                        offset,

                    "source":
                        line.strip(),
                }
            )


section3c1_masking_lines_df = pd.DataFrame(
    masking_lines_3c1
)


print("\nLEGALITY / MASKING SOURCE EVIDENCE")
print("-" * 100)

display(
    section3c1_masking_lines_df
)


# ==========================================================================================
# 8. Preserve current live test evidence
# ==========================================================================================

print("\nCURRENT LIVE TEST STATE")
print("-" * 100)

print(
    "Player:",
    player_card_3a5[
        "name"
    ],
)

print(
    "Opponent:",
    opponent_card_3a5[
        "name"
    ],
)

print(
    "Legal moves:",
    [
        move.get(
            "name"
        )
        for move in legal_moves_3a5
    ],
)

print(
    "R3 classes:",
    list(
        r3_live_model.classes_
    ),
)


legal_names_3c1 = [
    move.get(
        "name"
    )
    for move in legal_moves_3a5
]


in_vocab_legal_names_3c1 = [
    name
    for name in legal_names_3c1
    if name
    in set(
        r3_live_model.classes_
    )
]


out_of_vocab_legal_names_3c1 = [
    name
    for name in legal_names_3c1
    if name
    not in set(
        r3_live_model.classes_
    )
]


print(
    "Legal + R3 vocabulary:",
    in_vocab_legal_names_3c1,
)

print(
    "Legal but outside R3 vocabulary:",
    out_of_vocab_legal_names_3c1,
)


# ==========================================================================================
# 9. Section validation
# ==========================================================================================

section3c1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "R3LivePolicyEngine located",

            "observed":
                r3_engine_class_node_3c1
                is not None,

            "expected":
                True,

            "passed":
                r3_engine_class_node_3c1
                is not None,
        },

        {
            "validation":
                "score_moves located",

            "observed":
                score_moves_node_3c1
                is not None,

            "expected":
                True,

            "passed":
                score_moves_node_3c1
                is not None,
        },

        {
            "validation":
                "live state has legal moves",

            "observed":
                len(
                    legal_names_3c1
                ),

            "expected":
                ">= 1",

            "passed":
                len(
                    legal_names_3c1
                )
                >= 1,
        },

        {
            "validation":
                "at least one legal move in R3 vocabulary",

            "observed":
                in_vocab_legal_names_3c1,

            "expected":
                ">= 1",

            "passed":
                len(
                    in_vocab_legal_names_3c1
                )
                >= 1,
        },

        {
            "validation":
                "out-of-vocabulary legal move test available",

            "observed":
                out_of_vocab_legal_names_3c1,

            "expected":
                ">= 1",

            "passed":
                len(
                    out_of_vocab_legal_names_3c1
                )
                >= 1,
        },

        {
            "validation":
                "correct frozen model still bound",

            "observed":
                r3_live_model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_live_model.n_features_in_
                ==
                46,
        },
    ]
)


print("\nSECTION 3C.1 VALIDATION")
print("-" * 100)

display(
    section3c1_validation_df
)


assert (
    section3c1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 59 R3 POLICY ENGINE LOCATED")
print("✅ score_moves() CONTRACT LOCATED")
print("✅ LEGALITY / MASKING SOURCE INSPECTED")
print("✅ CURRENT PIKACHU TEST HAS IN-VOCAB LEGAL ACTION")
print("✅ CURRENT PIKACHU TEST ALSO HAS OUT-OF-VOCAB LEGAL ACTION")
print("✅ IDEAL MASKING TEST CASE CONFIRMED")
print("✅ SECTION 3C.1 COMPLETE")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3C.1 — RECOVER EXACT NOTEBOOK 59 R3 LEGALITY-MASK POLICY ENGINE CONTRACT
====================================================================================================

R3 LIVE POLICY ENGINE SOURCE LOCATION
----------------------------------------------------------------------------------------------------
Class: R3LivePolicyEngine
Start line: 6432
End line: 6854

R3 LIVE POLICY ENGINE METHODS
----------------------------------------------------------------------------------------------------

,method,line_number,end_line,arguments
0,__init__,6441,6490,"[self, model, retained_feature_names]"
1,build_model_matrix,6497,6577,"[self, battle_state, legal_moves]"
2,score_moves,6584,6834,"[self, battle_state, legal_moves]"
3,choose_move,6841,6854,"[self, battle_state, legal_moves]"

EXACT NOTEBOOK 59 POLICY METHOD SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
__init__
Lines 6441 - 6490
----------------------------------------------------------------------------------------------------
def __init__(
        self,
        model,
        retained_feature_names,
        *,
        name: str = "R3_STATE_CENTRIC_POLICY",
    ) -> None:

        self.model = model

        self.retained_feature_names = list(
            retained_feature_names
        )

        self.name = str(
            name
        )

        self.checkpoint_epoch = 0

        self.classes_ = [
            str(value)
            for value in self.model.classes_
        ]

        assert len(
            self.retained_feature_names
        ) == 46

        assert int(
            self.model.n_features_in_
        ) == 46

        assert len(
            self.classes_
        ) > 0

        # --------------------------------------------------------------
        # Normalized class-name lookup
        # --------------------------------------------------------------

        self._normalized_class_lookup = {
            normalize_action_name(
                class_name
            ):
            class_name

            for class_name
            in self.classes_
        }

====================================================================================================
score_moves
Lines 6584 - 6834
----------------------------------------------------------------------------------------------------
def score_moves(
        self,
        battle_state: Any,
        legal_moves: Sequence[Any],
    ) -> dict[str, Any]:

        legal_moves = list(
            legal_moves
        )

        if not legal_moves:

            raise ValueError(
                "At least one legal move is required."
            )

        # --------------------------------------------------------------
        # Build R3 feature matrix
        # --------------------------------------------------------------

        model_matrix = self.build_model_matrix(
            battle_state=battle_state,
            legal_moves=legal_moves,
        )

        # --------------------------------------------------------------
        # Full six-class RF probability distribution
        # --------------------------------------------------------------

        full_probability_matrix = (
            self.model.predict_proba(
                model_matrix
            )
        )

        assert full_probability_matrix.shape == (
            1,
            len(self.classes_),
        )

        full_probabilities = np.asarray(
            full_probability_matrix[0],
            dtype=float,
        )

        assert np.isfinite(
            full_probabilities
        ).all()

        assert np.isclose(
            full_probabilities.sum(),
            1.0,
            atol=1e-9,
        )

        # --------------------------------------------------------------
        # Class probability lookup
        # --------------------------------------------------------------

        class_probability_lookup = {}

        for class_name, probability in zip(
            self.classes_,
            full_probabilities,
        ):

            normalized_name = (
                normalize_action_name(
                    class_name
                )
            )

            class_probability_lookup[
                normalized_name
            ] = float(
                probability
            )

        # --------------------------------------------------------------
        # Resolve actual legal move names
        # --------------------------------------------------------------

        legal_move_names = [
            str(
                extract_move_name(
                    move
                )
            )
            for move in legal_moves
        ]

        normalized_legal_names = [
            normalize_action_name(
                move_name
            )
            for move_name in legal_move_names
        ]

        # --------------------------------------------------------------
        # Mask model probabilities to legal actions only
        # --------------------------------------------------------------

        legal_probability_values = np.asarray(
            [
                class_probability_lookup.get(
                    normalized_name,
                    0.0,
                )
                for normalized_name
                in normalized_legal_names
            ],
            dtype=float,
        )

        legal_probability_mass = float(
            legal_probability_values.sum()
        )

        fallback = False

        if legal_probability_mass > 0.0:

            legal_probabilities = (
                legal_probability_values
                /
                legal_probability_mass
            )

        else:

            # ----------------------------------------------------------
            # Defensive fallback:
            # model classes could not be mapped to available moves.
            #
            # Preserve legality by selecting first legal move.
            # ----------------------------------------------------------

            fallback = True

            legal_probabilities = np.zeros(
                len(
                    legal_moves
                ),
                dtype=float,
            )

            legal_probabilities[0] = 1.0

        # --------------------------------------------------------------
        # Select best LEGAL move
        # --------------------------------------------------------------

        selected_index = int(
            np.argmax(
                legal_probabilities
            )
        )

        selected_move = legal_moves[
            selected_index
        ]

        selected_move_name = (
            legal_move_names[
                selected_index
            ]
        )

        confidence = float(
            legal_probabilities[
                selected_index
            ]
        )

        # --------------------------------------------------------------
        # Compatibility logits
        #
        # RandomForestClassifier does not expose neural-network logits.
        # Log-probabilities provide a deterministic score vector with
        # the same ordering as the legal probabilities.
        # --------------------------------------------------------------

        epsilon = 1e-12

        legal_logits = np.log(
            np.clip(
                legal_probabilities,
                epsilon,
                1.0,
            )
        )

        # --------------------------------------------------------------
        # Return existing CompetitivePolicyEngine-compatible contract
        # --------------------------------------------------------------

        return {
            "selected_index":
                selected_index,

            "selected_move":
                selected_move,

            "selected_move_name":
                selected_move_name,

            "confidence":
                confidence,

            "probabilities":
                [
                    float(value)
                    for value
                    in legal_probabilities
                ],

            "logits":
                [
                    float(value)
                    for value
                    in legal_logits
                ],

            "move_names":
                legal_move_names,

            "checkpoint_epoch":
                self.checkpoint_epoch,

            "fallback":
                fallback,

            # Additional diagnostics — harmless to existing callers
            "policy_name":
                self.name,

            "full_class_names":
                list(
                    self.classes_
                ),

            "full_class_probabilities":
                [
                    float(value)
                    for value
                    in full_probabilities
                ],

            "legal_probability_mass":
                legal_probability_mass,
        }

====================================================================================================
choose_move
Lines 6841 - 6854
----------------------------------------------------------------------------------------------------
def choose_move(
        self,
        battle_state: Any,
        legal_moves: Sequence[Any],
    ) -> Any:

        result = self.score_moves(
            battle_state=battle_state,
            legal_moves=legal_moves,
        )

        return result[
            "selected_move"
        ]

TRUE CLASS-LEVEL EXTERNAL DEPENDENCIES
----------------------------------------------------------------------------------------------------
- Any
- Sequence
- build_legality_aware_feature_row
- encode_r3_feature_row
- extract_move_name
- name
- normalize_action_name
- np
- pd

R3 POLICY ENGINE DEPENDENCY STATUS
----------------------------------------------------------------------------------------------------

                         dependency  available           object_type
0                               Any       True              _AnyMeta
1                          Sequence       True  _SpecialGenericAlias
2  build_legality_aware_feature_row       True              function
3             encode_r3_feature_row       True              function
4                 extract_move_name       True              function
5                              name       True                   str
6             normalize_action_name       True              function
7                                np       True                module
8                                pd       True                module

Missing dependencies: []

NOTEBOOK 59 SOURCES FOR MISSING DEPENDENCIES
----------------------------------------------------------------------------------------------------

LEGALITY / MASKING SOURCE EVIDENCE
----------------------------------------------------------------------------------------------------

    line_number                                  source
0          6587             legal_moves: Sequence[Any],
1          6590                     legal_moves = list(
2          6591                             legal_moves
3          6594                     if not legal_moves:
4          6597  "At least one legal move is required."
..          ...                                     ...
73         6822                           self.classes_
74         6825             "full_class_probabilities":
75         6829                   in full_probabilities
76         6832               "legal_probability_mass":
77         6833                 legal_probability_mass,

[78 rows x 2 columns]

CURRENT LIVE TEST STATE
----------------------------------------------------------------------------------------------------
Player: Pikachu
Opponent: Charmander
Legal moves: ['Quick Attack', 'Thunderbolt']
R3 classes: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
Legal + R3 vocabulary: ['Quick Attack']
Legal but outside R3 vocabulary: ['Thunderbolt']

SECTION 3C.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,R3LivePolicyEngine located,True,True,True
1,score_moves located,True,True,True
2,live state has legal moves,2,>= 1,True
3,at least one legal move in R3 vocabulary,[Quick Attack],>= 1,True
4,out-of-vocabulary legal move test available,[Thunderbolt],>= 1,True
5,correct frozen model still bound,46,46,True

====================================================================================================
✅ EXACT NOTEBOOK 59 R3 POLICY ENGINE LOCATED
✅ score_moves() CONTRACT LOCATED
✅ LEGALITY / MASKING SOURCE INSPECTED
✅ CURRENT PIKACHU TEST HAS IN-VOCAB LEGAL ACTION
✅ CURRENT PIKACHU TEST ALSO HAS OUT-OF-VOCAB LEGAL ACTION
✅ IDEAL MASKING TEST CASE CONFIRMED
✅ SECTION 3C.1 COMPLETE
⚠️ NO MODEL MODIFICATION
⚠️ NO RETRAINING
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [44]:
# ==========================================================================================
# SECTION 3C.2 — EXECUTE EXACT R3 LEGALITY MASK AND RENORMALIZATION
# ==========================================================================================

print("=" * 100)
print("SECTION 3C.2 — EXECUTE EXACT R3 LEGALITY MASK AND RENORMALIZATION")
print("=" * 100)

import ast
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require all previously validated production components
# ==========================================================================================

assert (
    "r3_live_model"
    in globals()
    and
    r3_live_model is not None
)

assert (
    "r3_live_feature_names"
    in globals()
    and
    len(
        r3_live_feature_names
    )
    ==
    46
)

assert callable(
    build_legality_aware_feature_row
)

assert callable(
    encode_r3_feature_row
)

assert callable(
    extract_move_name
)

assert callable(
    normalize_action_name
)

assert (
    "battle_state_3a5"
    in globals()
), (
    "battle_state_3a5 is missing."
)

assert (
    "legal_moves_3a5"
    in globals()
), (
    "legal_moves_3a5 is missing."
)


# ==========================================================================================
# 2. Execute exact Notebook 59 R3LivePolicyEngine class definition
# ==========================================================================================

r3_engine_module_3c2 = ast.Module(
    body=[
        r3_engine_class_node_3c1
    ],
    type_ignores=[],
)

ast.fix_missing_locations(
    r3_engine_module_3c2
)


exec(
    compile(
        r3_engine_module_3c2,
        filename="notebook59_exact_r3_live_policy_engine",
        mode="exec",
    ),
    globals(),
)


assert (
    "R3LivePolicyEngine"
    in globals()
)


assert callable(
    R3LivePolicyEngine
)


print("\nEXACT POLICY ENGINE LOADED")
print("-" * 100)

print(
    "Class:",
    R3LivePolicyEngine
)


# ==========================================================================================
# 3. Instantiate exact frozen R3 engine
# ==========================================================================================

r3_policy_engine_3c2 = (
    R3LivePolicyEngine(
        model=r3_live_model,
        retained_feature_names=r3_live_feature_names,
        name="R3_STATE_CENTRIC_POLICY",
    )
)


print("\nR3 ENGINE INSTANCE")
print("-" * 100)

print(
    "Name:",
    r3_policy_engine_3c2.name
)

print(
    "Model:",
    type(
        r3_policy_engine_3c2.model
    ).__name__
)

print(
    "Model features:",
    r3_policy_engine_3c2.model.n_features_in_
)

print(
    "Classes:",
    r3_policy_engine_3c2.classes_
)


# ==========================================================================================
# 4. Preserve simulator legal move names
# ==========================================================================================

legal_move_names_3c2 = [
    extract_move_name(
        move
    )
    for move in legal_moves_3a5
]


r3_class_names_3c2 = [
    str(
        value
    )
    for value
    in r3_policy_engine_3c2.classes_
]


print("\nSIMULATOR LEGAL MOVES")
print("-" * 100)

for index, move_name in enumerate(
    legal_move_names_3c2,
    start=1,
):

    print(
        f"{index:02d}. {move_name}"
    )


print("\nR3 MODEL CLASSES")
print("-" * 100)

for index, class_name in enumerate(
    r3_class_names_3c2,
    start=1,
):

    print(
        f"{index:02d}. {class_name}"
    )


# ==========================================================================================
# 5. Identify overlap and out-of-vocabulary legal actions
# ==========================================================================================

normalized_r3_classes_3c2 = {
    normalize_action_name(
        class_name
    )
    for class_name
    in r3_class_names_3c2
}


in_vocab_legal_moves_3c2 = [
    move_name
    for move_name
    in legal_move_names_3c2
    if normalize_action_name(
        move_name
    )
    in normalized_r3_classes_3c2
]


out_of_vocab_legal_moves_3c2 = [
    move_name
    for move_name
    in legal_move_names_3c2
    if normalize_action_name(
        move_name
    )
    not in normalized_r3_classes_3c2
]


print("\nLEGALITY / VOCABULARY OVERLAP")
print("-" * 100)

print(
    "Legal + represented by R3:",
    in_vocab_legal_moves_3c2,
)

print(
    "Legal but outside R3 vocabulary:",
    out_of_vocab_legal_moves_3c2,
)


# ==========================================================================================
# 6. Execute exact score_moves()
# ==========================================================================================

print("\nEXECUTING score_moves()")
print("-" * 100)


score_result_3c2 = (
    r3_policy_engine_3c2.score_moves(
        battle_state=battle_state_3a5,
        legal_moves=legal_moves_3a5,
    )
)


print(
    "Result type:",
    type(
        score_result_3c2
    ).__name__
)


print("\nFULL R3 POLICY RESULT")
print("-" * 100)

for key, value in (
    score_result_3c2.items()
):

    print(
        f"{key}: {value}"
    )


# ==========================================================================================
# 7. Extract policy diagnostics
# ==========================================================================================

selected_move_3c2 = (
    score_result_3c2.get(
        "selected_move"
    )
)


selected_move_name_3c2 = (
    score_result_3c2.get(
        "selected_move_name"
    )
)


confidence_3c2 = float(
    score_result_3c2.get(
        "confidence",
        0.0,
    )
)


fallback_3c2 = bool(
    score_result_3c2.get(
        "fallback",
        False,
    )
)


legal_probability_mass_3c2 = float(
    score_result_3c2.get(
        "legal_probability_mass",
        0.0,
    )
)


full_class_names_3c2 = list(
    score_result_3c2.get(
        "full_class_names",
        [],
    )
)


full_class_probabilities_3c2 = list(
    score_result_3c2.get(
        "full_class_probabilities",
        [],
    )
)


returned_move_names_3c2 = list(
    score_result_3c2.get(
        "move_names",
        [],
    )
)


returned_probabilities_3c2 = list(
    score_result_3c2.get(
        "probabilities",
        [],
    )
)


# ==========================================================================================
# 8. Display raw six-class model probabilities
# ==========================================================================================

full_probability_df_3c2 = pd.DataFrame(
    {
        "class_name":
            full_class_names_3c2,

        "raw_probability":
            full_class_probabilities_3c2,
    }
)


print("\nRAW SIX-CLASS MODEL OUTPUT")
print("-" * 100)

display(
    full_probability_df_3c2
)


# ==========================================================================================
# 9. Display legal masked / renormalized policy output
# ==========================================================================================

legal_policy_df_3c2 = pd.DataFrame(
    {
        "legal_move":
            returned_move_names_3c2,

        "policy_probability":
            returned_probabilities_3c2,
    }
)


print("\nLEGAL-ACTION POLICY DISTRIBUTION")
print("-" * 100)

display(
    legal_policy_df_3c2
)


# ==========================================================================================
# 10. Validate selected action against simulator legality
# ==========================================================================================

selected_is_simulator_legal_3c2 = (
    selected_move_name_3c2
    in legal_move_names_3c2
)


selected_is_r3_class_3c2 = (
    normalize_action_name(
        selected_move_name_3c2
    )
    in normalized_r3_classes_3c2
)


print("\nSELECTED ACTION")
print("-" * 100)

print(
    "Selected move:",
    selected_move_name_3c2
)

print(
    "Confidence:",
    confidence_3c2
)

print(
    "Fallback:",
    fallback_3c2
)

print(
    "Legal probability mass:",
    legal_probability_mass_3c2
)

print(
    "Simulator legal:",
    selected_is_simulator_legal_3c2
)

print(
    "Represented by R3:",
    selected_is_r3_class_3c2
)


# ==========================================================================================
# 11. Validate masked probability normalization
# ==========================================================================================

legal_probability_sum_3c2 = float(
    np.sum(
        returned_probabilities_3c2
    )
)


print("\nMASK / RENORMALIZATION CHECK")
print("-" * 100)

print(
    "Returned policy probability sum:",
    legal_probability_sum_3c2
)


# ==========================================================================================
# 12. Ensure out-of-vocabulary legal moves were NOT invented as model classes
# ==========================================================================================

oov_in_full_model_classes_3c2 = [
    move_name
    for move_name
    in out_of_vocab_legal_moves_3c2
    if normalize_action_name(
        move_name
    )
    in {
        normalize_action_name(
            name
        )
        for name
        in full_class_names_3c2
    }
]


print("\nOUT-OF-VOCABULARY LEGAL ACTION CHECK")
print("-" * 100)

print(
    "Out-of-vocabulary legal moves:",
    out_of_vocab_legal_moves_3c2
)

print(
    "Incorrectly present as R3 model classes:",
    oov_in_full_model_classes_3c2
)


# ==========================================================================================
# 13. Compare selected action to raw model maximum
# ==========================================================================================

raw_model_top_class_3c2 = None


if (
    len(
        full_class_names_3c2
    )
    ==
    len(
        full_class_probabilities_3c2
    )
    and
    len(
        full_class_names_3c2
    )
    > 0
):

    raw_top_index_3c2 = int(
        np.argmax(
            full_class_probabilities_3c2
        )
    )

    raw_model_top_class_3c2 = (
        full_class_names_3c2[
            raw_top_index_3c2
        ]
    )


print("\nRAW MODEL VS LEGAL POLICY")
print("-" * 100)

print(
    "Raw model top class:",
    raw_model_top_class_3c2
)

print(
    "Final selected legal move:",
    selected_move_name_3c2
)


# ==========================================================================================
# 14. execute choose_move() too
# ==========================================================================================

print("\nEXECUTING choose_move()")
print("-" * 100)


chosen_move_3c2 = (
    r3_policy_engine_3c2.choose_move(
        battle_state=battle_state_3a5,
        legal_moves=legal_moves_3a5,
    )
)


chosen_move_name_3c2 = (
    extract_move_name(
        chosen_move_3c2
    )
)


print(
    "choose_move() returned:",
    chosen_move_name_3c2
)


# ==========================================================================================
# 15. Final Section 3C.2 validation
# ==========================================================================================

section3c2_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exact R3 engine instantiated",

            "observed":
                type(
                    r3_policy_engine_3c2
                ).__name__,

            "expected":
                "R3LivePolicyEngine",

            "passed":
                type(
                    r3_policy_engine_3c2
                ).__name__
                ==
                "R3LivePolicyEngine",
        },

        {
            "validation":
                "score_moves returned dictionary",

            "observed":
                type(
                    score_result_3c2
                ).__name__,

            "expected":
                "dict",

            "passed":
                isinstance(
                    score_result_3c2,
                    dict,
                ),
        },

        {
            "validation":
                "selected move present",

            "observed":
                selected_move_name_3c2,

            "expected":
                "non-empty",

            "passed":
                bool(
                    selected_move_name_3c2
                ),
        },

        {
            "validation":
                "selected move simulator-legal",

            "observed":
                selected_is_simulator_legal_3c2,

            "expected":
                True,

            "passed":
                selected_is_simulator_legal_3c2,
        },

        {
            "validation":
                "selected move represented by R3",

            "observed":
                selected_is_r3_class_3c2,

            "expected":
                True,

            "passed":
                selected_is_r3_class_3c2,
        },

        {
            "validation":
                "masked probabilities sum to one",

            "observed":
                legal_probability_sum_3c2,

            "expected":
                1.0,

            "passed":
                np.isclose(
                    legal_probability_sum_3c2,
                    1.0,
                ),
        },

        {
            "validation":
                "positive legal probability mass",

            "observed":
                legal_probability_mass_3c2,

            "expected":
                "> 0",

            "passed":
                legal_probability_mass_3c2
                >
                0.0,
        },

        {
            "validation":
                "OOV legal action not invented as model class",

            "observed":
                oov_in_full_model_classes_3c2,

            "expected":
                [],

            "passed":
                len(
                    oov_in_full_model_classes_3c2
                )
                ==
                0,
        },

        {
            "validation":
                "fallback not required",

            "observed":
                fallback_3c2,

            "expected":
                False,

            "passed":
                fallback_3c2
                is False,
        },

        {
            "validation":
                "choose_move agrees with score_moves",

            "observed":
                chosen_move_name_3c2,

            "expected":
                selected_move_name_3c2,

            "passed":
                chosen_move_name_3c2
                ==
                selected_move_name_3c2,
        },
    ]
)


print("\nSECTION 3C.2 VALIDATION")
print("-" * 100)

display(
    section3c2_validation_df
)


assert (
    section3c2_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 59 R3 POLICY ENGINE EXECUTED")
print("✅ SIX-CLASS RAW MODEL OUTPUT RECOVERED")
print("✅ SIMULATOR LEGALITY MASK APPLIED")
print("✅ LEGAL PROBABILITY MASS COMPUTED")
print("✅ LEGAL DISTRIBUTION RENORMALIZED")
print("✅ OUT-OF-VOCAB THUNDERBOLT NOT INVENTED AS R3 CLASS")
print("✅ SELECTED ACTION IS SIMULATOR-LEGAL")
print("✅ NO LEGALITY FALLBACK REQUIRED")
print("✅ choose_move() AGREES WITH score_moves()")
print("✅ SECTION 3C.2 COMPLETE")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3C.2 — EXECUTE EXACT R3 LEGALITY MASK AND RENORMALIZATION
====================================================================================================

EXACT POLICY ENGINE LOADED
----------------------------------------------------------------------------------------------------
Class: <class '__main__.R3LivePolicyEngine'>

R3 ENGINE INSTANCE
----------------------------------------------------------------------------------------------------
Name: R3_STATE_CENTRIC_POLICY
Model: RandomForestClassifier
Model features: 46
Classes: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

SIMULATOR LEGAL MOVES
----------------------------------------------------------------------------------------------------
01. Quick Attack
02. Thunderbolt

R3 MODEL CLASSES
----------------------------------------------------------------------------------------------------
01. Ascension
02. Bind Down
03. Live Coal
04. Pass
05. Quick Attack
06. Tuck Tail

LEGALITY / VOCABULARY OVERLAP
----------------------------------------------------------------------------------------------------
Legal + represented by R3: ['Quick Attack']
Legal but outside R3 vocabulary: ['Thunderbolt']

EXECUTING score_moves()
----------------------------------------------------------------------------------------------------
Result type: dict

FULL R3 POLICY RESULT
----------------------------------------------------------------------------------------------------
selected_index: 0
selected_move: {'name': 'Quick Attack', 'damage': 30.0, 'energy_cost': 1, 'effect': None}
selected_move_name: Quick Attack
confidence: 1.0
probabilities: [1.0, 0.0]
logits: [0.0, -27.631021115928547]
move_names: ['Quick Attack', 'Thunderbolt']
checkpoint_epoch: 0
fallback: False
policy_name: R3_STATE_CENTRIC_POLICY
full_class_names: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
full_class_probabilities: [0.12, 0.028, 0.036, 0.09, 0.726, 0.0]
legal_probability_mass: 0.726

RAW SIX-CLASS MODEL OUTPUT
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

     class_name  raw_probability
0     Ascension            0.120
1     Bind Down            0.028
2     Live Coal            0.036
3          Pass            0.090
4  Quick Attack            0.726
5     Tuck Tail            0.000

LEGAL-ACTION POLICY DISTRIBUTION
----------------------------------------------------------------------------------------------------

     legal_move  policy_probability
0  Quick Attack                 1.0
1   Thunderbolt                 0.0

SELECTED ACTION
----------------------------------------------------------------------------------------------------
Selected move: Quick Attack
Confidence: 1.0
Fallback: False
Legal probability mass: 0.726
Simulator legal: True
Represented by R3: True

MASK / RENORMALIZATION CHECK
----------------------------------------------------------------------------------------------------
Returned policy probability sum: 1.0

OUT-OF-VOCABULARY LEGAL ACTION CHECK
----------------------------------------------------------------------------------------------------
Out-of-vocabulary legal moves: ['Thunderbolt']
Incorrectly present as R3 model classes: []

RAW MODEL VS LEGAL POLICY
----------------------------------------------------------------------------------------------------
Raw model top class: Quick Attack
Final selected legal move: Quick Attack

EXECUTING choose_move()
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

choose_move() returned: Quick Attack

SECTION 3C.2 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,exact R3 engine instantiated,R3LivePolicyEngine,R3LivePolicyEngine,True
1,score_moves returned dictionary,dict,dict,True
2,selected move present,Quick Attack,non-empty,True
3,selected move simulator-legal,True,True,True
4,selected move represented by R3,True,True,True
5,masked probabilities sum to one,1.0,1.0,True
6,positive legal probability mass,0.726,> 0,True
7,OOV legal action not invented as model class,[],[],True
8,fallback not required,False,False,True
9,choose_move agrees with score_moves,Quick Attack,Quick Attack,True

====================================================================================================
✅ EXACT NOTEBOOK 59 R3 POLICY ENGINE EXECUTED
✅ SIX-CLASS RAW MODEL OUTPUT RECOVERED
✅ SIMULATOR LEGALITY MASK APPLIED
✅ LEGAL PROBABILITY MASS COMPUTED
✅ LEGAL DISTRIBUTION RENORMALIZED
✅ OUT-OF-VOCAB THUNDERBOLT NOT INVENTED AS R3 CLASS
✅ SELECTED ACTION IS SIMULATOR-LEGAL
✅ NO LEGALITY FALLBACK REQUIRED
✅ choose_move() AGREES WITH score_moves()
✅ SECTION 3C.2 COMPLETE
⚠️ NO MODEL MODIFICATION
⚠️ NO RETRAINING
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [45]:
# ==========================================================================================
# SECTION 3C.3 — VALIDATE ZERO-MASS LEGALITY FALLBACK WITH GENUINE OOV MOVE
# ==========================================================================================

print("=" * 100)
print("SECTION 3C.3 — VALIDATE ZERO-MASS LEGALITY FALLBACK WITH GENUINE OOV MOVE")
print("=" * 100)

import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require exact production policy engine from Section 3C.2
# ==========================================================================================

assert (
    "r3_policy_engine_3c2"
    in globals()
), (
    "Run Section 3C.2 first."
)

assert (
    type(
        r3_policy_engine_3c2
    ).__name__
    ==
    "R3LivePolicyEngine"
)

assert (
    r3_policy_engine_3c2.model.n_features_in_
    ==
    46
)


print("\nFROZEN R3 ENGINE")
print("-" * 100)

print(
    "Name:",
    r3_policy_engine_3c2.name
)

print(
    "Model:",
    type(
        r3_policy_engine_3c2.model
    ).__name__
)

print(
    "Feature count:",
    r3_policy_engine_3c2.model.n_features_in_
)

print(
    "Classes:",
    r3_policy_engine_3c2.classes_
)


# ==========================================================================================
# 2. Recover the genuine Thunderbolt move from the production legal resolver output
# ==========================================================================================

thunderbolt_moves_3c3 = [
    move
    for move in legal_moves_3a5
    if normalize_action_name(
        extract_move_name(
            move
        )
    )
    ==
    normalize_action_name(
        "Thunderbolt"
    )
]


assert (
    len(
        thunderbolt_moves_3c3
    )
    ==
    1
), (
    "Expected exactly one genuine Thunderbolt move "
    "from the production legal-move resolver."
)


thunderbolt_move_3c3 = (
    thunderbolt_moves_3c3[
        0
    ]
)


fallback_legal_moves_3c3 = [
    thunderbolt_move_3c3
]


print("\nGENUINE FALLBACK TEST MOVE")
print("-" * 100)

print(
    thunderbolt_move_3c3
)


print(
    "\nMove name:",
    extract_move_name(
        thunderbolt_move_3c3
    )
)


# ==========================================================================================
# 3. Confirm Thunderbolt really is outside the frozen R3 action vocabulary
# ==========================================================================================

r3_normalized_classes_3c3 = {
    normalize_action_name(
        class_name
    )
    for class_name
    in r3_policy_engine_3c2.classes_
}


thunderbolt_in_r3_vocabulary_3c3 = (
    normalize_action_name(
        "Thunderbolt"
    )
    in r3_normalized_classes_3c3
)


print("\nVOCABULARY CHECK")
print("-" * 100)

print(
    "Thunderbolt is simulator-legal:",
    thunderbolt_move_3c3
    in legal_moves_3a5
)

print(
    "Thunderbolt represented by R3:",
    thunderbolt_in_r3_vocabulary_3c3
)


assert (
    thunderbolt_in_r3_vocabulary_3c3
    is False
)


# ==========================================================================================
# 4. Execute exact Notebook 59 score_moves() with ONLY the genuine OOV legal move
# ==========================================================================================

print("\nEXECUTING ZERO-MASS FALLBACK TEST")
print("-" * 100)


fallback_result_3c3 = (
    r3_policy_engine_3c2.score_moves(
        battle_state=battle_state_3a5,
        legal_moves=fallback_legal_moves_3c3,
    )
)


print(
    "Result type:",
    type(
        fallback_result_3c3
    ).__name__
)


print("\nFULL FALLBACK POLICY RESULT")
print("-" * 100)

for key, value in (
    fallback_result_3c3.items()
):

    print(
        f"{key}: {value}"
    )


# ==========================================================================================
# 5. Extract fallback diagnostics
# ==========================================================================================

fallback_selected_move_3c3 = (
    fallback_result_3c3.get(
        "selected_move"
    )
)


fallback_selected_name_3c3 = (
    fallback_result_3c3.get(
        "selected_move_name"
    )
)


fallback_flag_3c3 = bool(
    fallback_result_3c3.get(
        "fallback",
        False,
    )
)


fallback_legal_mass_3c3 = float(
    fallback_result_3c3.get(
        "legal_probability_mass",
        0.0,
    )
)


fallback_probabilities_3c3 = list(
    fallback_result_3c3.get(
        "probabilities",
        [],
    )
)


fallback_move_names_3c3 = list(
    fallback_result_3c3.get(
        "move_names",
        [],
    )
)


fallback_confidence_3c3 = float(
    fallback_result_3c3.get(
        "confidence",
        0.0,
    )
)


print("\nFALLBACK DIAGNOSTICS")
print("-" * 100)

print(
    "Selected move:",
    fallback_selected_name_3c3
)

print(
    "Fallback:",
    fallback_flag_3c3
)

print(
    "Legal model probability mass:",
    fallback_legal_mass_3c3
)

print(
    "Confidence:",
    fallback_confidence_3c3
)

print(
    "Returned move names:",
    fallback_move_names_3c3
)

print(
    "Returned probabilities:",
    fallback_probabilities_3c3
)


# ==========================================================================================
# 6. Display fallback legal distribution
# ==========================================================================================

fallback_distribution_df_3c3 = pd.DataFrame(
    {
        "legal_move":
            fallback_move_names_3c3,

        "policy_probability":
            fallback_probabilities_3c3,
    }
)


print("\nFALLBACK LEGAL-ACTION DISTRIBUTION")
print("-" * 100)

display(
    fallback_distribution_df_3c3
)


# ==========================================================================================
# 7. Verify raw model still has six unchanged classes
# ==========================================================================================

full_class_names_3c3 = list(
    fallback_result_3c3.get(
        "full_class_names",
        [],
    )
)


full_class_probabilities_3c3 = list(
    fallback_result_3c3.get(
        "full_class_probabilities",
        [],
    )
)


raw_model_df_3c3 = pd.DataFrame(
    {
        "class_name":
            full_class_names_3c3,

        "raw_probability":
            full_class_probabilities_3c3,
    }
)


print("\nUNCHANGED SIX-CLASS RAW MODEL OUTPUT")
print("-" * 100)

display(
    raw_model_df_3c3
)


# ==========================================================================================
# 8. Execute choose_move() under the same all-OOV legal set
# ==========================================================================================

print("\nEXECUTING choose_move() UNDER FALLBACK CONDITION")
print("-" * 100)


fallback_chosen_move_3c3 = (
    r3_policy_engine_3c2.choose_move(
        battle_state=battle_state_3a5,
        legal_moves=fallback_legal_moves_3c3,
    )
)


fallback_chosen_name_3c3 = (
    extract_move_name(
        fallback_chosen_move_3c3
    )
)


print(
    "choose_move() returned:",
    fallback_chosen_name_3c3
)


# ==========================================================================================
# 9. Core safety checks
# ==========================================================================================

selected_is_supplied_legal_move_3c3 = (
    fallback_selected_move_3c3
    in fallback_legal_moves_3c3
)


selected_name_is_thunderbolt_3c3 = (
    normalize_action_name(
        fallback_selected_name_3c3
    )
    ==
    normalize_action_name(
        "Thunderbolt"
    )
)


fallback_distribution_sum_3c3 = float(
    np.sum(
        fallback_probabilities_3c3
    )
)


selected_not_in_r3_vocabulary_3c3 = (
    normalize_action_name(
        fallback_selected_name_3c3
    )
    not in r3_normalized_classes_3c3
)


print("\nFALLBACK SAFETY CHECK")
print("-" * 100)

print(
    "Selected supplied legal object:",
    selected_is_supplied_legal_move_3c3
)

print(
    "Selected Thunderbolt:",
    selected_name_is_thunderbolt_3c3
)

print(
    "Selected action outside R3 vocabulary:",
    selected_not_in_r3_vocabulary_3c3
)

print(
    "Fallback distribution sum:",
    fallback_distribution_sum_3c3
)

print(
    "choose_move() agreement:",
    fallback_chosen_name_3c3
    ==
    fallback_selected_name_3c3
)


# ==========================================================================================
# 10. Important interpretation
# ==========================================================================================

print("\nFALLBACK INTERPRETATION")
print("-" * 100)

print(
    "The simulator supplied a genuinely legal action that the six-class "
    "R3 model cannot represent."
)

print(
    "Therefore the model contributes zero legal probability mass."
)

print(
    "The policy layer must preserve simulator legality rather than invent "
    "an R3 class that is not legal."
)

print(
    "This is a safety fallback, not a model-driven decision."
)


# ==========================================================================================
# 11. Section 3C.3 validation
# ==========================================================================================

section3c3_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "genuine simulator move used",

            "observed":
                thunderbolt_move_3c3
                in legal_moves_3a5,

            "expected":
                True,

            "passed":
                thunderbolt_move_3c3
                in legal_moves_3a5,
        },

        {
            "validation":
                "Thunderbolt outside R3 vocabulary",

            "observed":
                thunderbolt_in_r3_vocabulary_3c3,

            "expected":
                False,

            "passed":
                thunderbolt_in_r3_vocabulary_3c3
                is False,
        },

        {
            "validation":
                "fallback activated",

            "observed":
                fallback_flag_3c3,

            "expected":
                True,

            "passed":
                fallback_flag_3c3
                is True,
        },

        {
            "validation":
                "zero legal model probability mass",

            "observed":
                fallback_legal_mass_3c3,

            "expected":
                0.0,

            "passed":
                np.isclose(
                    fallback_legal_mass_3c3,
                    0.0,
                ),
        },

        {
            "validation":
                "selected move is supplied legal move",

            "observed":
                selected_is_supplied_legal_move_3c3,

            "expected":
                True,

            "passed":
                selected_is_supplied_legal_move_3c3,
        },

        {
            "validation":
                "fallback selected Thunderbolt",

            "observed":
                fallback_selected_name_3c3,

            "expected":
                "Thunderbolt",

            "passed":
                selected_name_is_thunderbolt_3c3,
        },

        {
            "validation":
                "fallback legal distribution sums to one",

            "observed":
                fallback_distribution_sum_3c3,

            "expected":
                1.0,

            "passed":
                np.isclose(
                    fallback_distribution_sum_3c3,
                    1.0,
                ),
        },

        {
            "validation":
                "raw six-class model remains intact",

            "observed":
                len(
                    full_class_names_3c3
                ),

            "expected":
                6,

            "passed":
                len(
                    full_class_names_3c3
                )
                ==
                6,
        },

        {
            "validation":
                "fallback did not invent R3 action",

            "observed":
                selected_not_in_r3_vocabulary_3c3,

            "expected":
                True,

            "passed":
                selected_not_in_r3_vocabulary_3c3,
        },

        {
            "validation":
                "choose_move agrees with score_moves",

            "observed":
                fallback_chosen_name_3c3,

            "expected":
                fallback_selected_name_3c3,

            "passed":
                fallback_chosen_name_3c3
                ==
                fallback_selected_name_3c3,
        },
    ]
)


print("\nSECTION 3C.3 VALIDATION")
print("-" * 100)

display(
    section3c3_validation_df
)


assert (
    section3c3_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ GENUINE OUT-OF-VOCAB SIMULATOR ACTION TESTED")
print("✅ ZERO LEGAL R3 PROBABILITY MASS CONFIRMED")
print("✅ LEGALITY FALLBACK ACTIVATED")
print("✅ FALLBACK PRESERVED SIMULATOR-LEGAL ACTION")
print("✅ NO ILLEGAL R3 CLASS INVENTED")
print("✅ choose_move() FALLBACK CONTRACT VERIFIED")
print("✅ SECTION 3C.3 COMPLETE")
print("✅ SECTION 3C LEGALITY SAFETY GATE COMPLETE")
print("⚠️ FALLBACK DECISIONS ARE NOT MODEL-DRIVEN")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3C.3 — VALIDATE ZERO-MASS LEGALITY FALLBACK WITH GENUINE OOV MOVE
====================================================================================================

FROZEN R3 ENGINE
----------------------------------------------------------------------------------------------------
Name: R3_STATE_CENTRIC_POLICY
Model: RandomForestClassifier
Feature count: 46
Classes: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

GENUINE FALLBACK TEST MOVE
----------------------------------------------------------------------------------------------------
{'name': 'Thunderbolt', 'damage': 90.0, 'energy_cost': 2, 'effect': None}

Move name: Thunderbolt

VOCABULARY CHECK
----------------------------------------------------------------------------------------------------
Thunderbolt is simulator-legal: True
Thunderbolt represented by R3: False

EXECUTING ZERO-MASS FALLBACK TEST
----------------------------------------------------------------------------------------------------
Result type: dict

FULL FALLBACK POLICY RESULT
----------------------------------------------------------------------------------------------------
selected_index: 0
selected_move: {'name': 'Thunderbolt', 'damage': 90.0, 'energy_cost': 2, 'effect': None}
selected_move_name: Thunderbolt
confidence: 1.0
probabilities: [1.0]
logits: [0.0]
move_names: ['Thunderbolt']
checkpoint_epoch: 0
fallback: True
policy_name: R3_STATE_CENTRIC_POLICY
full_class_names: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
full_class_probabilities: [0.574, 0.074, 0.098, 0.216, 0.036, 0.002]
legal_probability_mass: 0.0

FALLBACK DIAGNOSTICS
----------------------------------------------------------------------------------------------------
Selected move: Thunderbolt
Fallback: True
Legal model probability mass: 0.0
Confidence: 1.0
Returned move names: ['Thunderbolt']
Returned probabilities: [1.0]

FALLBACK LEGAL-ACTION DISTRIBUTION
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

    legal_move  policy_probability
0  Thunderbolt                 1.0

UNCHANGED SIX-CLASS RAW MODEL OUTPUT
----------------------------------------------------------------------------------------------------

     class_name  raw_probability
0     Ascension            0.574
1     Bind Down            0.074
2     Live Coal            0.098
3          Pass            0.216
4  Quick Attack            0.036
5     Tuck Tail            0.002

EXECUTING choose_move() UNDER FALLBACK CONDITION
----------------------------------------------------------------------------------------------------
choose_move() returned: Thunderbolt

FALLBACK SAFETY CHECK
----------------------------------------------------------------------------------------------------
Selected supplied legal object: True
Selected Thunderbolt: True
Selected action outside R3 vocabulary: True
Fallback distribution sum: 1.0
choose_move() agreement: True

FALLBACK INTERPRETATION
----------------------------------------------------------------------------------------------------
The simulator supplied a genuinely legal action that the six-class R3 model cannot represent.
Therefore the model contributes zero legal probability mass.
The policy layer must preserve simulator legality rather than invent an R3 class that is not legal.
This is a safety fallback, not a model-driven decision.

SECTION 3C.3 VALIDATION
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

                                validation     observed     expected  passed
0              genuine simulator move used         True         True    True
1        Thunderbolt outside R3 vocabulary        False        False    True
2                       fallback activated         True         True    True
3        zero legal model probability mass          0.0          0.0    True
4     selected move is supplied legal move         True         True    True
5            fallback selected Thunderbolt  Thunderbolt  Thunderbolt    True
6  fallback legal distribution sums to one          1.0          1.0    True
7       raw six-class model remains intact            6            6    True
8        fallback did not invent R3 action         True         True    True
9      choose_move agrees with score_moves  Thunderbolt  Thunderbolt    True

====================================================================================================
✅ GENUINE OUT-OF-VOCAB SIMULATOR ACTION TESTED
✅ ZERO LEGAL R3 PROBABILITY MASS CONFIRMED
✅ LEGALITY FALLBACK ACTIVATED
✅ FALLBACK PRESERVED SIMULATOR-LEGAL ACTION
✅ NO ILLEGAL R3 CLASS INVENTED
✅ choose_move() FALLBACK CONTRACT VERIFIED
✅ SECTION 3C.3 COMPLETE
✅ SECTION 3C LEGALITY SAFETY GATE COMPLETE
⚠️ FALLBACK DECISIONS ARE NOT MODEL-DRIVEN
⚠️ NO MODEL MODIFICATION
⚠️ NO RETRAINING
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [46]:
# ==========================================================================================
# SECTION 3D.1 — INSPECT NOTEBOOK 48 TOURNAMENT AGENT CONTRACT FOR R3 ADAPTER
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.1 — INSPECT NOTEBOOK 48 TOURNAMENT AGENT CONTRACT FOR R3 ADAPTER")
print("=" * 100)

import inspect
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require recovered Notebook 48 historical harness
# ==========================================================================================

required_historical_objects_3d1 = [
    "TournamentDecision",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
    "create_tournament_state",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


historical_status_rows_3d1 = []


for name_3d1 in required_historical_objects_3d1:

    available_3d1 = (
        name_3d1
        in globals()
    )

    historical_status_rows_3d1.append(
        {
            "object":
                name_3d1,

            "available":
                available_3d1,

            "object_type":
                (
                    type(
                        globals().get(
                            name_3d1
                        )
                    ).__name__
                    if available_3d1
                    else
                    "MISSING"
                ),
        }
    )


section3d1_historical_status_df = pd.DataFrame(
    historical_status_rows_3d1
)


print("\nHISTORICAL HARNESS STATUS")
print("-" * 100)

display(
    section3d1_historical_status_df
)


assert (
    section3d1_historical_status_df[
        "available"
    ].all()
), (
    "One or more historical Notebook 48 harness objects are missing."
)


# ==========================================================================================
# 2. Require frozen R3 production policy
# ==========================================================================================

assert (
    "r3_policy_engine_3c2"
    in globals()
)

assert (
    r3_policy_engine_3c2.model.n_features_in_
    ==
    46
)

assert (
    "R3_STATE_CENTRIC_POLICY"
    ==
    r3_policy_engine_3c2.name
)


print("\nFROZEN R3 STATUS")
print("-" * 100)

print(
    "Engine:",
    type(
        r3_policy_engine_3c2
    ).__name__
)

print(
    "Model:",
    type(
        r3_policy_engine_3c2.model
    ).__name__
)

print(
    "Features:",
    r3_policy_engine_3c2.model.n_features_in_
)

print(
    "Classes:",
    r3_policy_engine_3c2.classes_
)


# ==========================================================================================
# 3. Inspect TournamentDecision contract
# ==========================================================================================

print("\nTOURNAMENT DECISION SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        TournamentDecision
    )
)


print("\nTOURNAMENT DECISION SOURCE")
print("-" * 100)

try:

    print(
        inspect.getsource(
            TournamentDecision
        )
    )

except Exception as exc:

    print(
        "Source unavailable:",
        type(
            exc
        ).__name__,
        exc,
    )


# ==========================================================================================
# 4. Inspect historical baseline decision methods
# ==========================================================================================

baseline_agent_objects_3d1 = {
    "RandomLegalMoveAgent":
        RandomLegalMoveAgent,

    "GreedyDamageAgent":
        GreedyDamageAgent,

    "SearchAgentAdapter":
        SearchAgentAdapter,
}


baseline_method_rows_3d1 = []


for class_name_3d1, class_obj_3d1 in (
    baseline_agent_objects_3d1.items()
):

    for candidate_method_3d1 in [
        "choose_move",
        "decide",
        "select_move",
        "score_moves",
    ]:

        method_obj_3d1 = getattr(
            class_obj_3d1,
            candidate_method_3d1,
            None,
        )

        if method_obj_3d1 is None:
            continue


        try:

            signature_3d1 = str(
                inspect.signature(
                    method_obj_3d1
                )
            )

        except Exception:

            signature_3d1 = (
                "SIGNATURE_UNAVAILABLE"
            )


        baseline_method_rows_3d1.append(
            {
                "class":
                    class_name_3d1,

                "method":
                    candidate_method_3d1,

                "signature":
                    signature_3d1,
            }
        )


section3d1_baseline_methods_df = pd.DataFrame(
    baseline_method_rows_3d1
)


print("\nHISTORICAL BASELINE DECISION METHODS")
print("-" * 100)

display(
    section3d1_baseline_methods_df
)


# ==========================================================================================
# 5. Inspect exact run_tournament_match signature
# ==========================================================================================

print("\nRUN_TOURNAMENT_MATCH SIGNATURE")
print("-" * 100)

run_match_signature_3d1 = (
    inspect.signature(
        run_tournament_match
    )
)

print(
    run_match_signature_3d1
)


# ==========================================================================================
# 6. Inspect historical runner source around evaluated-agent invocation
# ==========================================================================================

print("\nRUN_TOURNAMENT_MATCH SOURCE")
print("-" * 100)

try:

    run_match_source_3d1 = (
        inspect.getsource(
            run_tournament_match
        )
    )

    print(
        run_match_source_3d1
    )

except Exception as exc:

    run_match_source_3d1 = ""

    print(
        "Source unavailable:",
        type(
            exc
        ).__name__,
        exc,
    )


# ==========================================================================================
# 7. Locate evaluated-agent call patterns
# ==========================================================================================

call_pattern_rows_3d1 = []


for line_number_3d1, source_line_3d1 in enumerate(
    run_match_source_3d1.splitlines(),
    start=1,
):

    lowered_3d1 = (
        source_line_3d1
        .lower()
    )

    if any(
        term_3d1
        in lowered_3d1
        for term_3d1
        in [
            "evaluated_agent",
            "choose_move",
            "decide",
            "score_moves",
            "legal_moves",
            "tournamentdecision",
        ]
    ):

        call_pattern_rows_3d1.append(
            {
                "relative_line":
                    line_number_3d1,

                "source":
                    source_line_3d1.strip(),
            }
        )


section3d1_call_patterns_df = pd.DataFrame(
    call_pattern_rows_3d1
)


print("\nEVALUATED-AGENT INVOCATION EVIDENCE")
print("-" * 100)

display(
    section3d1_call_patterns_df
)


# ==========================================================================================
# 8. Inspect exact TournamentDecision fields
# ==========================================================================================

decision_annotations_3d1 = getattr(
    TournamentDecision,
    "__annotations__",
    {},
)


print("\nTOURNAMENT DECISION FIELDS")
print("-" * 100)

for field_name_3d1, field_type_3d1 in (
    decision_annotations_3d1.items()
):

    print(
        f"{field_name_3d1}: {field_type_3d1}"
    )


# ==========================================================================================
# 9. Confirm historical smoke-test cards remain available
# ==========================================================================================

assert (
    "TOURNAMENT_CARD_TEMPLATES"
    in globals()
)

assert (
    len(
        TOURNAMENT_CARD_TEMPLATES
    )
    >= 2
)


smoke_player_card_3d1 = (
    TOURNAMENT_CARD_TEMPLATES[
        0
    ]
)

smoke_opponent_card_3d1 = (
    TOURNAMENT_CARD_TEMPLATES[
        1
    ]
)


print("\nHISTORICAL SMOKE CARDS")
print("-" * 100)

print(
    "Player:",
    smoke_player_card_3d1[
        "name"
    ]
)

print(
    "Opponent:",
    smoke_opponent_card_3d1[
        "name"
    ]
)


# ==========================================================================================
# 10. Reconfirm exact historical baselines remain instantiated
# ==========================================================================================

baseline_instances_3d1 = {
    "Random Baseline":
        random_baseline_agent_2e1,

    "Greedy Damage Baseline":
        greedy_baseline_agent_2e,

    "Depth-6 Search Baseline":
        search_baseline_agent_2e,
}


baseline_instance_rows_3d1 = []


for baseline_name_3d1, baseline_obj_3d1 in (
    baseline_instances_3d1.items()
):

    baseline_instance_rows_3d1.append(
        {
            "baseline":
                baseline_name_3d1,

            "available":
                baseline_obj_3d1
                is not None,

            "object_type":
                type(
                    baseline_obj_3d1
                ).__name__,
        }
    )


section3d1_baseline_instances_df = pd.DataFrame(
    baseline_instance_rows_3d1
)


print("\nHISTORICAL BASELINE INSTANCES")
print("-" * 100)

display(
    section3d1_baseline_instances_df
)


# ==========================================================================================
# 11. Validation
# ==========================================================================================

section3d1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical harness objects available",

            "observed":
                bool(
                    section3d1_historical_status_df[
                        "available"
                    ].all()
                ),

            "expected":
                True,

            "passed":
                bool(
                    section3d1_historical_status_df[
                        "available"
                    ].all()
                ),
        },

        {
            "validation":
                "TournamentDecision available",

            "observed":
                callable(
                    TournamentDecision
                ),

            "expected":
                True,

            "passed":
                callable(
                    TournamentDecision
                ),
        },

        {
            "validation":
                "run_tournament_match callable",

            "observed":
                callable(
                    run_tournament_match
                ),

            "expected":
                True,

            "passed":
                callable(
                    run_tournament_match
                ),
        },

        {
            "validation":
                "baseline agent method evidence found",

            "observed":
                len(
                    section3d1_baseline_methods_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section3d1_baseline_methods_df
                )
                >
                0,
        },

        {
            "validation":
                "evaluated-agent call evidence found",

            "observed":
                len(
                    section3d1_call_patterns_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section3d1_call_patterns_df
                )
                >
                0,
        },

        {
            "validation":
                "historical smoke cards available",

            "observed":
                [
                    smoke_player_card_3d1[
                        "name"
                    ],
                    smoke_opponent_card_3d1[
                        "name"
                    ],
                ],

            "expected":
                [
                    "Pikachu",
                    "Charmander",
                ],

            "passed":
                (
                    smoke_player_card_3d1[
                        "name"
                    ]
                    ==
                    "Pikachu"
                    and
                    smoke_opponent_card_3d1[
                        "name"
                    ]
                    ==
                    "Charmander"
                ),
        },

        {
            "validation":
                "three historical baselines instantiated",

            "observed":
                len(
                    baseline_instances_3d1
                ),

            "expected":
                3,

            "passed":
                len(
                    baseline_instances_3d1
                )
                ==
                3,
        },

        {
            "validation":
                "frozen R3 model still 46 features",

            "observed":
                r3_policy_engine_3c2.model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_policy_engine_3c2.model.n_features_in_
                ==
                46,
        },
    ]
)


print("\nSECTION 3D.1 VALIDATION")
print("-" * 100)

display(
    section3d1_validation_df
)


assert (
    section3d1_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ NOTEBOOK 48 TOURNAMENT AGENT CONTRACT INSPECTED")
print("✅ TournamentDecision CONTRACT AVAILABLE")
print("✅ run_tournament_match() CONTRACT AVAILABLE")
print("✅ THREE EXACT HISTORICAL BASELINES AVAILABLE")
print("✅ HISTORICAL PIKACHU / CHARMANDER SMOKE CARDS AVAILABLE")
print("✅ FROZEN R3 POLICY REMAINS UNCHANGED")
print("✅ SECTION 3D.1 COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.1 — INSPECT NOTEBOOK 48 TOURNAMENT AGENT CONTRACT FOR R3 ADAPTER
====================================================================================================

HISTORICAL HARNESS STATUS
----------------------------------------------------------------------------------------------------

                    object  available object_type
0       TournamentDecision      False     MISSING
1     RandomLegalMoveAgent      False     MISSING
2        GreedyDamageAgent      False     MISSING
3       SearchAgentAdapter      False     MISSING
4  create_tournament_state      False     MISSING
5     run_tournament_match      False     MISSING
6   create_random_baseline      False     MISSING
7   create_greedy_baseline      False     MISSING
8   create_search_baseline      False     MISSING

AssertionError: One or more historical Notebook 48 harness objects are missing.

In [47]:
# ==========================================================================================
# SECTION 3D.1A — LOCATE AND REBIND EXISTING NOTEBOOK 48 HISTORICAL HARNESS NAMESPACE
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.1A — LOCATE AND REBIND EXISTING NOTEBOOK 48 HISTORICAL HARNESS NAMESPACE")
print("=" * 100)

import types
import pandas as pd


# ==========================================================================================
# 1. Exact historical objects required by Section 3D
# ==========================================================================================

REQUIRED_HISTORICAL_OBJECTS_3D1A = [
    "TournamentDecision",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
    "create_tournament_state",
    "TournamentMatchResult",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


# ==========================================================================================
# 2. Search current globals for containers that may hold the recovered objects
#
# We inspect:
#   - module objects
#   - dictionaries
#   - SimpleNamespace-like objects
#
# We do NOT execute any historical source.
# ==========================================================================================

candidate_rows_3d1a = []
candidate_containers_3d1a = {}


for global_name_3d1a, global_obj_3d1a in list(
    globals().items()
):

    # ------------------------------------------------------------------
    # Skip obvious noise
    # ------------------------------------------------------------------

    if global_name_3d1a.startswith(
        "__"
    ):
        continue


    container_kind_3d1a = None
    available_names_3d1a = set()


    # ------------------------------------------------------------------
    # Dictionary namespace
    # ------------------------------------------------------------------

    if isinstance(
        global_obj_3d1a,
        dict,
    ):

        container_kind_3d1a = (
            "dict"
        )

        available_names_3d1a = set(
            global_obj_3d1a.keys()
        )


    # ------------------------------------------------------------------
    # Module namespace
    # ------------------------------------------------------------------

    elif isinstance(
        global_obj_3d1a,
        types.ModuleType,
    ):

        container_kind_3d1a = (
            "module"
        )

        available_names_3d1a = set(
            dir(
                global_obj_3d1a
            )
        )


    # ------------------------------------------------------------------
    # Generic namespace-like object
    # ------------------------------------------------------------------

    elif hasattr(
        global_obj_3d1a,
        "__dict__",
    ):

        try:

            available_names_3d1a = set(
                vars(
                    global_obj_3d1a
                ).keys()
            )

            container_kind_3d1a = (
                type(
                    global_obj_3d1a
                ).__name__
            )

        except Exception:

            continue


    else:

        continue


    matched_names_3d1a = [
        name_3d1a
        for name_3d1a
        in REQUIRED_HISTORICAL_OBJECTS_3D1A
        if name_3d1a
        in available_names_3d1a
    ]


    if not matched_names_3d1a:

        continue


    candidate_containers_3d1a[
        global_name_3d1a
    ] = global_obj_3d1a


    candidate_rows_3d1a.append(
        {
            "global_name":
                global_name_3d1a,

            "container_type":
                container_kind_3d1a,

            "matched_count":
                len(
                    matched_names_3d1a
                ),

            "matched_objects":
                matched_names_3d1a,

            "contains_run_tournament_match":
                (
                    "run_tournament_match"
                    in available_names_3d1a
                ),

            "contains_three_factories":
                all(
                    name_3d1a
                    in available_names_3d1a
                    for name_3d1a
                    in [
                        "create_random_baseline",
                        "create_greedy_baseline",
                        "create_search_baseline",
                    ]
                ),
        }
    )


section3d1a_candidate_df = pd.DataFrame(
    candidate_rows_3d1a
)


print("\nHISTORICAL NAMESPACE CANDIDATES")
print("-" * 100)

if len(
    section3d1a_candidate_df
) > 0:

    display(
        section3d1a_candidate_df.sort_values(
            "matched_count",
            ascending=False,
        ).reset_index(
            drop=True
        )
    )

else:

    print(
        "No namespace container currently exposes the required historical objects."
    )


assert (
    len(
        section3d1a_candidate_df
    )
    >
    0
), (
    "Could not locate the previously recovered Notebook 48 namespace. "
    "Do not recreate historical objects yet."
)


# ==========================================================================================
# 3. Select namespace containing the COMPLETE historical contract
# ==========================================================================================

complete_candidates_3d1a = (
    section3d1a_candidate_df.loc[
        section3d1a_candidate_df[
            "matched_count"
        ]
        ==
        len(
            REQUIRED_HISTORICAL_OBJECTS_3D1A
        )
    ]
    .copy()
)


print("\nCOMPLETE HISTORICAL NAMESPACE CANDIDATES")
print("-" * 100)

display(
    complete_candidates_3d1a
)


# ==========================================================================================
# 4. If no single container has all ten objects, allow strongest exact historical container
#    but require all critical benchmark objects.
# ==========================================================================================

CRITICAL_HISTORICAL_OBJECTS_3D1A = [
    "TournamentDecision",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
    "create_tournament_state",
    "TournamentMatchResult",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
]


qualified_names_3d1a = []


for candidate_name_3d1a, candidate_obj_3d1a in (
    candidate_containers_3d1a.items()
):

    if isinstance(
        candidate_obj_3d1a,
        dict,
    ):

        candidate_keys_3d1a = set(
            candidate_obj_3d1a.keys()
        )

    else:

        candidate_keys_3d1a = set(
            dir(
                candidate_obj_3d1a
            )
        )


    if all(
        object_name_3d1a
        in candidate_keys_3d1a
        for object_name_3d1a
        in CRITICAL_HISTORICAL_OBJECTS_3D1A
    ):

        qualified_names_3d1a.append(
            candidate_name_3d1a
        )


print(
    "\nQualified complete namespaces:",
    qualified_names_3d1a,
)


assert (
    len(
        qualified_names_3d1a
    )
    >=
    1
), (
    "No existing namespace contains the complete Notebook 48 historical harness."
)


# ==========================================================================================
# 5. Prefer the explicitly named historical recovery namespace
# ==========================================================================================

preferred_names_3d1a = [
    name_3d1a
    for name_3d1a
    in qualified_names_3d1a
    if (
        "notebook48"
        in name_3d1a.lower()
        or
        "historical"
        in name_3d1a.lower()
        or
        "benchmark"
        in name_3d1a.lower()
    )
]


if len(
    preferred_names_3d1a
) == 1:

    selected_namespace_name_3d1a = (
        preferred_names_3d1a[
            0
        ]
    )


elif len(
    qualified_names_3d1a
) == 1:

    selected_namespace_name_3d1a = (
        qualified_names_3d1a[
            0
        ]
    )


else:

    # ------------------------------------------------------------------
    # Rank by exact-looking namespace name and number of historical objects.
    # Do not silently choose an arbitrary object.
    # ------------------------------------------------------------------

    ranking_rows_3d1a = []


    for namespace_name_3d1a in (
        qualified_names_3d1a
    ):

        namespace_lower_3d1a = (
            namespace_name_3d1a.lower()
        )

        score_3d1a = 0


        if "notebook48" in namespace_lower_3d1a:
            score_3d1a += 100

        if "historical" in namespace_lower_3d1a:
            score_3d1a += 50

        if "benchmark" in namespace_lower_3d1a:
            score_3d1a += 25

        if "recovery" in namespace_lower_3d1a:
            score_3d1a += 10


        ranking_rows_3d1a.append(
            {
                "namespace":
                    namespace_name_3d1a,

                "score":
                    score_3d1a,
            }
        )


    ranking_df_3d1a = pd.DataFrame(
        ranking_rows_3d1a
    ).sort_values(
        "score",
        ascending=False,
    ).reset_index(
        drop=True
    )


    print("\nNAMESPACE RANKING")
    print("-" * 100)

    display(
        ranking_df_3d1a
    )


    assert (
        len(
            ranking_df_3d1a
        )
        >=
        1
    )


    if (
        len(
            ranking_df_3d1a
        )
        >
        1
        and
        ranking_df_3d1a.loc[
            0,
            "score",
        ]
        ==
        ranking_df_3d1a.loc[
            1,
            "score",
        ]
    ):

        raise AssertionError(
            "Multiple equally qualified historical namespaces remain. "
            "Do not bind one arbitrarily."
        )


    selected_namespace_name_3d1a = (
        ranking_df_3d1a.loc[
            0,
            "namespace",
        ]
    )


historical_namespace_3d1a = (
    candidate_containers_3d1a[
        selected_namespace_name_3d1a
    ]
)


print("\nSELECTED HISTORICAL NAMESPACE")
print("-" * 100)

print(
    "Global variable:",
    selected_namespace_name_3d1a
)

print(
    "Object type:",
    type(
        historical_namespace_3d1a
    ).__name__
)


# ==========================================================================================
# 6. Safe accessor for dict / module namespace
# ==========================================================================================

def get_historical_object_3d1a(
    namespace,
    name,
):

    if isinstance(
        namespace,
        dict,
    ):

        return namespace[
            name
        ]


    return getattr(
        namespace,
        name,
    )


# ==========================================================================================
# 7. Bind exact recovered historical objects into current Notebook 60 globals
#
# IMPORTANT:
# No definitions are recreated.
# No Notebook 48 script is executed.
# These are references to the already recovered historical objects.
# ==========================================================================================

binding_rows_3d1a = []


for object_name_3d1a in (
    REQUIRED_HISTORICAL_OBJECTS_3D1A
):

    historical_object_3d1a = (
        get_historical_object_3d1a(
            historical_namespace_3d1a,
            object_name_3d1a,
        )
    )


    globals()[
        object_name_3d1a
    ] = historical_object_3d1a


    binding_rows_3d1a.append(
        {
            "object":
                object_name_3d1a,

            "bound":
                object_name_3d1a
                in globals(),

            "object_type":
                type(
                    globals()[
                        object_name_3d1a
                    ]
                ).__name__,

            "module":
                getattr(
                    globals()[
                        object_name_3d1a
                    ],
                    "__module__",
                    None,
                ),

            "same_object":
                (
                    globals()[
                        object_name_3d1a
                    ]
                    is
                    historical_object_3d1a
                ),
        }
    )


section3d1a_binding_df = pd.DataFrame(
    binding_rows_3d1a
)


print("\nHISTORICAL OBJECT BINDINGS")
print("-" * 100)

display(
    section3d1a_binding_df
)


# ==========================================================================================
# 8. Verify exact identity preservation
# ==========================================================================================

assert (
    section3d1a_binding_df[
        "bound"
    ].all()
)

assert (
    section3d1a_binding_df[
        "same_object"
    ].all()
)


# ==========================================================================================
# 9. Recreate baseline instances ONLY through exact historical factories if needed
#
# This does not modify baseline definitions.
# ==========================================================================================

historical_random_seed_3d1a = (
    globals().get(
        "RANDOM_SEED",
        4801,
    )
)


# Random
random_baseline_agent_3d = (
    create_random_baseline(
        historical_random_seed_3d1a
    )
)


# Greedy
greedy_baseline_agent_3d = (
    create_greedy_baseline()
)


# Depth-6
search_baseline_agent_3d = (
    create_search_baseline()
)


baseline_rows_3d1a = [
    {
        "baseline":
            "Random Baseline",

        "object_type":
            type(
                random_baseline_agent_3d
            ).__name__,

        "created":
            random_baseline_agent_3d
            is not None,
    },

    {
        "baseline":
            "Greedy Damage Baseline",

        "object_type":
            type(
                greedy_baseline_agent_3d
            ).__name__,

        "created":
            greedy_baseline_agent_3d
            is not None,
    },

    {
        "baseline":
            "Depth-6 Search Baseline",

        "object_type":
            type(
                search_baseline_agent_3d
            ).__name__,

        "created":
            search_baseline_agent_3d
            is not None,
    },
]


section3d1a_baselines_df = pd.DataFrame(
    baseline_rows_3d1a
)


print("\nREBOUND HISTORICAL BASELINES")
print("-" * 100)

display(
    section3d1a_baselines_df
)


# ==========================================================================================
# 10. Inspect signatures now that exact historical objects are bound
# ==========================================================================================

import inspect


print("\nTOURNAMENT DECISION SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        TournamentDecision
    )
)


print("\nRUN_TOURNAMENT_MATCH SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        run_tournament_match
    )
)


print("\nCREATE_TOURNAMENT_STATE SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        create_tournament_state
    )
)


# ==========================================================================================
# 11. Find decision methods on exact historical baseline objects
# ==========================================================================================

historical_agents_3d1a = {
    "Random Baseline":
        random_baseline_agent_3d,

    "Greedy Damage Baseline":
        greedy_baseline_agent_3d,

    "Depth-6 Search Baseline":
        search_baseline_agent_3d,
}


agent_method_rows_3d1a = []


for baseline_name_3d1a, agent_3d1a in (
    historical_agents_3d1a.items()
):

    for method_name_3d1a in [
        "choose_move",
        "decide",
        "select_move",
        "score_moves",
    ]:

        method_3d1a = getattr(
            agent_3d1a,
            method_name_3d1a,
            None,
        )


        if method_3d1a is None:
            continue


        try:

            signature_3d1a = str(
                inspect.signature(
                    method_3d1a
                )
            )

        except Exception:

            signature_3d1a = (
                "UNAVAILABLE"
            )


        agent_method_rows_3d1a.append(
            {
                "baseline":
                    baseline_name_3d1a,

                "method":
                    method_name_3d1a,

                "signature":
                    signature_3d1a,
            }
        )


section3d1a_agent_methods_df = pd.DataFrame(
    agent_method_rows_3d1a
)


print("\nHISTORICAL BASELINE DECISION METHODS")
print("-" * 100)

display(
    section3d1a_agent_methods_df
)


# ==========================================================================================
# 12. Inspect run_tournament_match exact evaluated-agent invocation
# ==========================================================================================

try:

    runner_source_3d1a = (
        inspect.getsource(
            run_tournament_match
        )
    )

except Exception:

    runner_source_3d1a = ""


invocation_rows_3d1a = []


for relative_line_3d1a, line_3d1a in enumerate(
    runner_source_3d1a.splitlines(),
    start=1,
):

    lowered_3d1a = (
        line_3d1a.lower()
    )


    if any(
        token_3d1a
        in lowered_3d1a
        for token_3d1a
        in [
            "evaluated_agent",
            "baseline_agent",
            ".decide",
            ".choose_move",
            ".select_move",
            "legal_moves",
            "tournamentdecision",
        ]
    ):

        invocation_rows_3d1a.append(
            {
                "relative_line":
                    relative_line_3d1a,

                "source":
                    line_3d1a.strip(),
            }
        )


section3d1a_invocation_df = pd.DataFrame(
    invocation_rows_3d1a
)


print("\nEVALUATED-AGENT INVOCATION EVIDENCE")
print("-" * 100)

display(
    section3d1a_invocation_df
)


# ==========================================================================================
# 13. Final validation
# ==========================================================================================

section3d1a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical namespace located",

            "observed":
                selected_namespace_name_3d1a,

            "expected":
                "existing recovery namespace",

            "passed":
                historical_namespace_3d1a
                is not None,
        },

        {
            "validation":
                "all historical objects rebound",

            "observed":
                int(
                    section3d1a_binding_df[
                        "bound"
                    ].sum()
                ),

            "expected":
                len(
                    REQUIRED_HISTORICAL_OBJECTS_3D1A
                ),

            "passed":
                bool(
                    section3d1a_binding_df[
                        "bound"
                    ].all()
                ),
        },

        {
            "validation":
                "exact object identity preserved",

            "observed":
                bool(
                    section3d1a_binding_df[
                        "same_object"
                    ].all()
                ),

            "expected":
                True,

            "passed":
                bool(
                    section3d1a_binding_df[
                        "same_object"
                    ].all()
                ),
        },

        {
            "validation":
                "three historical baselines available",

            "observed":
                int(
                    section3d1a_baselines_df[
                        "created"
                    ].sum()
                ),

            "expected":
                3,

            "passed":
                bool(
                    section3d1a_baselines_df[
                        "created"
                    ].all()
                ),
        },

        {
            "validation":
                "historical runner callable",

            "observed":
                callable(
                    run_tournament_match
                ),

            "expected":
                True,

            "passed":
                callable(
                    run_tournament_match
                ),
        },

        {
            "validation":
                "historical state builder callable",

            "observed":
                callable(
                    create_tournament_state
                ),

            "expected":
                True,

            "passed":
                callable(
                    create_tournament_state
                ),
        },

        {
            "validation":
                "evaluated-agent invocation evidence recovered",

            "observed":
                len(
                    section3d1a_invocation_df
                ),

            "expected":
                "> 0",

            "passed":
                len(
                    section3d1a_invocation_df
                )
                >
                0,
        },

        {
            "validation":
                "R3 remains frozen",

            "observed":
                r3_policy_engine_3c2.model.n_features_in_,

            "expected":
                46,

            "passed":
                r3_policy_engine_3c2.model.n_features_in_
                ==
                46,
        },
    ]
)


print("\nSECTION 3D.1A VALIDATION")
print("-" * 100)

display(
    section3d1a_validation_df
)


assert (
    section3d1a_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ EXISTING NOTEBOOK 48 RECOVERY NAMESPACE LOCATED")
print("✅ EXACT HISTORICAL OBJECTS REBOUND — NOT RECREATED")
print("✅ TournamentDecision RESTORED")
print("✅ EXACT RANDOM BASELINE AVAILABLE")
print("✅ EXACT GREEDY DAMAGE BASELINE AVAILABLE")
print("✅ EXACT DEPTH-6 SEARCH BASELINE AVAILABLE")
print("✅ HISTORICAL STATE BUILDER RESTORED")
print("✅ HISTORICAL MATCH RUNNER RESTORED")
print("✅ EVALUATED-AGENT CALL CONTRACT RECOVERED")
print("✅ FROZEN R3 MODEL REMAINS UNCHANGED")
print("✅ SECTION 3D.1A COMPLETE")
print("⚠️ NO HISTORICAL SCRIPT EXECUTED")
print("⚠️ NO R3 RETRAINING")
print("⚠️ NO R3 MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.1A — LOCATE AND REBIND EXISTING NOTEBOOK 48 HISTORICAL HARNESS NAMESPACE
====================================================================================================

HISTORICAL NAMESPACE CANDIDATES
----------------------------------------------------------------------------------------------------

,global_name,container_type,matched_count,matched_objects,contains_run_tournament_match,contains_three_factories
0,objects_2d,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True
1,top_level_nodes_2e,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True
2,historical_ns_2e,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True

COMPLETE HISTORICAL NAMESPACE CANDIDATES
----------------------------------------------------------------------------------------------------

,global_name,container_type,matched_count,matched_objects,contains_run_tournament_match,contains_three_factories
0,objects_2d,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True
1,top_level_nodes_2e,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True
2,historical_ns_2e,dict,10,"[TournamentDecision, RandomLegalMoveAgent, Gre...",True,True

Qualified complete namespaces: ['objects_2d', 'top_level_nodes_2e', 'historical_ns_2e']

SELECTED HISTORICAL NAMESPACE
----------------------------------------------------------------------------------------------------
Global variable: historical_ns_2e
Object type: dict

HISTORICAL OBJECT BINDINGS
----------------------------------------------------------------------------------------------------

,object,bound,object_type,module,same_object
0,TournamentDecision,True,type,notebook48_historical_benchmark_recovery,True
1,RandomLegalMoveAgent,True,type,notebook48_historical_benchmark_recovery,True
2,GreedyDamageAgent,True,type,notebook48_historical_benchmark_recovery,True
3,SearchAgentAdapter,True,type,notebook48_historical_benchmark_recovery,True
4,create_tournament_state,True,function,notebook48_historical_benchmark_recovery,True
5,TournamentMatchResult,True,type,notebook48_historical_benchmark_recovery,True
6,run_tournament_match,True,function,notebook48_historical_benchmark_recovery,True
7,create_random_baseline,True,function,notebook48_historical_benchmark_recovery,True
8,create_greedy_baseline,True,function,notebook48_historical_benchmark_recovery,True
9,create_search_baseline,True,function,notebook48_historical_benchmark_recovery,True

REBOUND HISTORICAL BASELINES
----------------------------------------------------------------------------------------------------

                  baseline           object_type  created
0          Random Baseline  RandomLegalMoveAgent     True
1   Greedy Damage Baseline     GreedyDamageAgent     True
2  Depth-6 Search Baseline    SearchAgentAdapter     True

TOURNAMENT DECISION SIGNATURE
----------------------------------------------------------------------------------------------------
(move: Any, score: float, search_depth: int, nodes: int, confidence: float = 0.0, selected_move_name: str | None = None, fallback: bool = False, reason: str | None = None) -> None

RUN_TOURNAMENT_MATCH SIGNATURE
----------------------------------------------------------------------------------------------------
(match_id: int, evaluated_agent: Any, baseline_agent: Any, player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str, evaluated_agent_side: str, max_turns: int = 50, search_depth: int = 6, verbose: bool = False) -> notebook48_historical_benchmark_recovery.TournamentMatchResult

CREATE_TOURNAMENT_STATE SIGNATURE
----------------------------------------------------------------------------------------------------
(player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str = 'Player', player_energy: int = 3, opponent_energy: int = 3) -> src.battle_state.BattleState

HISTORICAL BASELINE DECISION METHODS
----------------------------------------------------------------------------------------------------

,baseline,method,signature
0,Random Baseline,choose_move,"(state: Any = None, depth: int | None = None, ..."
1,Greedy Damage Baseline,choose_move,"(state: Any = None, depth: int | None = None, ..."
2,Depth-6 Search Baseline,choose_move,"(state: Any = None, depth: int | None = None, ..."

EVALUATED-AGENT INVOCATION EVIDENCE
----------------------------------------------------------------------------------------------------

    relative_line                                source
0               3                 evaluated_agent: Any,
1               4                  baseline_agent: Any,
2               8            evaluated_agent_side: str,
3              16      if evaluated_agent_side not in {
4              21       "evaluated_agent_side must be "
5              85                         .choose_move(
6             105  if evaluated_agent_side == "Player":
7             108                      evaluated_agent,
8             111                       baseline_agent,
9             117                       baseline_agent,
10            120                      evaluated_agent,
11            168  elif winner == evaluated_agent_side:
12            181                      evaluated_agent,
13            184                       evaluated_agent
14            192                       baseline_agent,
15            195                        baseline_agent

SECTION 3D.1A VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,historical namespace located,historical_ns_2e,existing recovery namespace,True
1,all historical objects rebound,10,10,True
2,exact object identity preserved,True,True,True
3,three historical baselines available,3,3,True
4,historical runner callable,True,True,True
5,historical state builder callable,True,True,True
6,evaluated-agent invocation evidence recovered,16,> 0,True
7,R3 remains frozen,46,46,True

====================================================================================================
✅ EXISTING NOTEBOOK 48 RECOVERY NAMESPACE LOCATED
✅ EXACT HISTORICAL OBJECTS REBOUND — NOT RECREATED
✅ TournamentDecision RESTORED
✅ EXACT RANDOM BASELINE AVAILABLE
✅ EXACT GREEDY DAMAGE BASELINE AVAILABLE
✅ EXACT DEPTH-6 SEARCH BASELINE AVAILABLE
✅ HISTORICAL STATE BUILDER RESTORED
✅ HISTORICAL MATCH RUNNER RESTORED
✅ EVALUATED-AGENT CALL CONTRACT RECOVERED
✅ FROZEN R3 MODEL REMAINS UNCHANGED
✅ SECTION 3D.1A COMPLETE
⚠️ NO HISTORICAL SCRIPT EXECUTED
⚠️ NO R3 RETRAINING
⚠️ NO R3 MODEL MODIFICATION
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [48]:
# ==========================================================================================
# SECTION 3D.2 — RECOVER EXACT TOURNAMENT AGENT DECISION CONTRACT FOR R3 ADAPTER
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.2 — RECOVER EXACT TOURNAMENT AGENT DECISION CONTRACT FOR R3 ADAPTER")
print("=" * 100)

import inspect
import ast
import pandas as pd


# ==========================================================================================
# 1. Confirm exact historical objects remain available
# ==========================================================================================

required_objects_3d2 = [
    "TournamentDecision",
    "RandomLegalMoveAgent",
    "GreedyDamageAgent",
    "SearchAgentAdapter",
    "create_tournament_state",
    "run_tournament_match",
]

status_rows_3d2 = []

for name_3d2 in required_objects_3d2:

    obj_3d2 = globals().get(
        name_3d2,
        None,
    )

    status_rows_3d2.append(
        {
            "object": name_3d2,
            "available": obj_3d2 is not None,
            "object_type": (
                type(obj_3d2).__name__
                if obj_3d2 is not None
                else "MISSING"
            ),
            "module": (
                getattr(
                    obj_3d2,
                    "__module__",
                    None,
                )
                if obj_3d2 is not None
                else None
            ),
        }
    )

section3d2_status_df = pd.DataFrame(
    status_rows_3d2
)

print("\nHISTORICAL HARNESS STATUS")
print("-" * 100)

display(
    section3d2_status_df
)

assert section3d2_status_df[
    "available"
].all(), (
    "Historical Notebook 48 harness is no longer fully bound."
)


# ==========================================================================================
# 2. Recover exact choose_move() sources from all three baseline classes
# ==========================================================================================

baseline_classes_3d2 = {
    "RandomLegalMoveAgent":
        RandomLegalMoveAgent,

    "GreedyDamageAgent":
        GreedyDamageAgent,

    "SearchAgentAdapter":
        SearchAgentAdapter,
}


choose_move_rows_3d2 = []

choose_move_sources_3d2 = {}


for class_name_3d2, class_obj_3d2 in (
    baseline_classes_3d2.items()
):

    method_3d2 = getattr(
        class_obj_3d2,
        "choose_move",
        None,
    )

    assert method_3d2 is not None, (
        f"{class_name_3d2} has no choose_move() method."
    )

    signature_3d2 = inspect.signature(
        method_3d2
    )

    try:

        source_3d2 = inspect.getsource(
            method_3d2
        )

    except Exception as exc_3d2:

        source_3d2 = ""

        print(
            f"Could not recover source for "
            f"{class_name_3d2}.choose_move(): "
            f"{type(exc_3d2).__name__}: {exc_3d2}"
        )


    choose_move_sources_3d2[
        class_name_3d2
    ] = source_3d2


    choose_move_rows_3d2.append(
        {
            "class":
                class_name_3d2,

            "signature":
                str(
                    signature_3d2
                ),

            "source_recovered":
                bool(
                    source_3d2
                ),

            "returns_tournament_decision_text":
                (
                    "TournamentDecision"
                    in source_3d2
                ),

            "references_legal_moves":
                (
                    "legal_moves"
                    in source_3d2
                ),

            "references_state":
                (
                    "state"
                    in source_3d2
                ),
        }
    )


section3d2_choose_move_df = pd.DataFrame(
    choose_move_rows_3d2
)


print("\nBASELINE choose_move() CONTRACT SUMMARY")
print("-" * 100)

display(
    section3d2_choose_move_df
)


# ==========================================================================================
# 3. Print exact historical choose_move() sources
# ==========================================================================================

print("\nEXACT HISTORICAL choose_move() SOURCES")
print("-" * 100)


for class_name_3d2, source_3d2 in (
    choose_move_sources_3d2.items()
):

    print("\n" + "=" * 100)
    print(
        f"{class_name_3d2}.choose_move"
    )
    print("=" * 100)

    print(
        source_3d2
        if source_3d2
        else
        "<SOURCE NOT AVAILABLE>"
    )


# ==========================================================================================
# 4. Recover TournamentDecision dataclass/constructor contract
# ==========================================================================================

decision_signature_3d2 = inspect.signature(
    TournamentDecision
)

decision_fields_3d2 = getattr(
    TournamentDecision,
    "__dataclass_fields__",
    {},
)


decision_field_rows_3d2 = []


for field_name_3d2, field_obj_3d2 in (
    decision_fields_3d2.items()
):

    decision_field_rows_3d2.append(
        {
            "field":
                field_name_3d2,

            "type":
                str(
                    getattr(
                        field_obj_3d2,
                        "type",
                        None,
                    )
                ),

            "default":
                str(
                    getattr(
                        field_obj_3d2,
                        "default",
                        None,
                    )
                ),
        }
    )


section3d2_decision_fields_df = pd.DataFrame(
    decision_field_rows_3d2
)


print("\nTOURNAMENT DECISION CONSTRUCTOR")
print("-" * 100)

print(
    decision_signature_3d2
)


print("\nTOURNAMENT DECISION FIELDS")
print("-" * 100)

display(
    section3d2_decision_fields_df
)


# ==========================================================================================
# 5. Recover exact run_tournament_match() source
# ==========================================================================================

runner_source_3d2 = inspect.getsource(
    run_tournament_match
)


print("\nRUN_TOURNAMENT_MATCH SIGNATURE")
print("-" * 100)

print(
    inspect.signature(
        run_tournament_match
    )
)


# ==========================================================================================
# 6. AST inspection:
#    Find every .choose_move(...) invocation in the tournament runner
# ==========================================================================================

runner_tree_3d2 = ast.parse(
    runner_source_3d2
)


choose_calls_3d2 = []


for node_3d2 in ast.walk(
    runner_tree_3d2
):

    if not isinstance(
        node_3d2,
        ast.Call,
    ):
        continue


    func_3d2 = node_3d2.func


    if not isinstance(
        func_3d2,
        ast.Attribute,
    ):
        continue


    if func_3d2.attr != "choose_move":
        continue


    try:

        receiver_3d2 = ast.unparse(
            func_3d2.value
        )

    except Exception:

        receiver_3d2 = "<UNKNOWN>"


    positional_args_3d2 = []

    for arg_3d2 in node_3d2.args:

        try:

            positional_args_3d2.append(
                ast.unparse(
                    arg_3d2
                )
            )

        except Exception:

            positional_args_3d2.append(
                "<UNKNOWN>"
            )


    keyword_args_3d2 = {}

    for kw_3d2 in node_3d2.keywords:

        if kw_3d2.arg is None:
            continue

        try:

            keyword_args_3d2[
                kw_3d2.arg
            ] = ast.unparse(
                kw_3d2.value
            )

        except Exception:

            keyword_args_3d2[
                kw_3d2.arg
            ] = "<UNKNOWN>"


    choose_calls_3d2.append(
        {
            "line":
                getattr(
                    node_3d2,
                    "lineno",
                    None,
                ),

            "receiver":
                receiver_3d2,

            "positional_args":
                positional_args_3d2,

            "keyword_args":
                keyword_args_3d2,

            "call":
                (
                    ast.unparse(
                        node_3d2
                    )
                    if hasattr(
                        ast,
                        "unparse",
                    )
                    else
                    "choose_move(...)"
                ),
        }
    )


section3d2_choose_calls_df = pd.DataFrame(
    choose_calls_3d2
)


print("\nEXACT choose_move() INVOCATIONS INSIDE TOURNAMENT RUNNER")
print("-" * 100)

display(
    section3d2_choose_calls_df
)


assert len(
    section3d2_choose_calls_df
) >= 1, (
    "No choose_move() invocation found in historical tournament runner."
)


# ==========================================================================================
# 7. Recover runner context around each choose_move() call
# ==========================================================================================

runner_lines_3d2 = (
    runner_source_3d2.splitlines()
)


context_rows_3d2 = []


for call_index_3d2, call_row_3d2 in (
    section3d2_choose_calls_df.iterrows()
):

    line_number_3d2 = int(
        call_row_3d2[
            "line"
        ]
    )


    start_3d2 = max(
        1,
        line_number_3d2 - 8,
    )

    end_3d2 = min(
        len(
            runner_lines_3d2
        ),
        line_number_3d2 + 12,
    )


    context_3d2 = "\n".join(
        f"{line_idx_3d2:03d}: "
        f"{runner_lines_3d2[line_idx_3d2 - 1]}"
        for line_idx_3d2
        in range(
            start_3d2,
            end_3d2 + 1,
        )
    )


    context_rows_3d2.append(
        {
            "call_index":
                call_index_3d2,

            "choose_move_line":
                line_number_3d2,

            "receiver":
                call_row_3d2[
                    "receiver"
                ],

            "context":
                context_3d2,
        }
    )


section3d2_runner_context_df = pd.DataFrame(
    context_rows_3d2
)


print("\nRUNNER CONTEXT AROUND choose_move()")
print("-" * 100)


for _, row_3d2 in (
    section3d2_runner_context_df.iterrows()
):

    print("\n" + "=" * 100)

    print(
        f"Receiver: {row_3d2['receiver']} | "
        f"Runner relative line: {row_3d2['choose_move_line']}"
    )

    print("-" * 100)

    print(
        row_3d2[
            "context"
        ]
    )


# ==========================================================================================
# 8. Determine exact common choose_move signature
# ==========================================================================================

signature_strings_3d2 = {
    class_name_3d2:
        str(
            inspect.signature(
                getattr(
                    class_obj_3d2,
                    "choose_move",
                )
            )
        )

    for class_name_3d2, class_obj_3d2
    in baseline_classes_3d2.items()
}


print("\nEXACT BASELINE choose_move() SIGNATURES")
print("-" * 100)


for class_name_3d2, signature_3d2 in (
    signature_strings_3d2.items()
):

    print(
        f"{class_name_3d2}: "
        f"{signature_3d2}"
    )


# ==========================================================================================
# 9. Build one genuine tournament state ONLY for interface inspection
#
# No match is run here.
# ==========================================================================================

candidate_player_cards_3d2 = [
    globals().get(
        name_3d2
    )
    for name_3d2
    in [
        "pikachu_card",
        "PIKACHU_CARD",
        "player_card_2e",
        "player_card",
    ]
    if globals().get(
        name_3d2
    ) is not None
]


candidate_opponent_cards_3d2 = [
    globals().get(
        name_3d2
    )
    for name_3d2
    in [
        "charmander_card",
        "CHARMANDER_CARD",
        "opponent_card_2e",
        "opponent_card",
    ]
    if globals().get(
        name_3d2
    ) is not None
]


print("\nAVAILABLE EXISTING CARD OBJECTS FOR INTERFACE TEST")
print("-" * 100)

print(
    "Player-card candidates:",
    len(
        candidate_player_cards_3d2
    )
)

print(
    "Opponent-card candidates:",
    len(
        candidate_opponent_cards_3d2
    )
)


# ==========================================================================================
# 10. Recover card dictionaries from prior live test state if direct variables are absent
# ==========================================================================================

if not candidate_player_cards_3d2:

    live_state_candidates_3d2 = [
        globals().get(
            name_3d2
        )
        for name_3d2
        in [
            "battle_state_3c1",
            "battle_state_3c2",
            "live_test_state_3c1",
            "live_test_state_3c2",
        ]
        if globals().get(
            name_3d2
        ) is not None
    ]


    for state_candidate_3d2 in (
        live_state_candidates_3d2
    ):

        player_card_candidate_3d2 = getattr(
            state_candidate_3d2,
            "player_card",
            None,
        )

        opponent_card_candidate_3d2 = getattr(
            state_candidate_3d2,
            "opponent_card",
            None,
        )


        if player_card_candidate_3d2 is not None:

            candidate_player_cards_3d2.append(
                player_card_candidate_3d2
            )


        if opponent_card_candidate_3d2 is not None:

            candidate_opponent_cards_3d2.append(
                opponent_card_candidate_3d2
            )


# ==========================================================================================
# 11. Interface inspection only if genuine cards are already available
# ==========================================================================================

state_interface_rows_3d2 = []


if (
    candidate_player_cards_3d2
    and
    candidate_opponent_cards_3d2
):

    inspection_state_3d2 = (
        create_tournament_state(
            player_card=
                candidate_player_cards_3d2[
                    0
                ],

            opponent_card=
                candidate_opponent_cards_3d2[
                    0
                ],

            starting_side=
                "Player",
        )
    )


    print("\nGENUINE TOURNAMENT STATE CREATED FOR INTERFACE INSPECTION")
    print("-" * 100)

    print(
        "Type:",
        type(
            inspection_state_3d2
        )
    )


    for attr_3d2 in [
        "current_side",
        "player_card",
        "opponent_card",
        "player_energy",
        "opponent_energy",
        "player_damage",
        "opponent_damage",
        "turn_number",
        "prize_cards_remaining",
        "hand_size",
    ]:

        state_interface_rows_3d2.append(
            {
                "attribute":
                    attr_3d2,

                "available":
                    hasattr(
                        inspection_state_3d2,
                        attr_3d2,
                    ),

                "value":
                    repr(
                        getattr(
                            inspection_state_3d2,
                            attr_3d2,
                            None,
                        )
                    ),
            }
        )


    section3d2_state_interface_df = pd.DataFrame(
        state_interface_rows_3d2
    )


    display(
        section3d2_state_interface_df
    )


else:

    inspection_state_3d2 = None

    section3d2_state_interface_df = pd.DataFrame()


    print("\nSTATE INTERFACE TEST DEFERRED")
    print("-" * 100)

    print(
        "No existing genuine player/opponent card pair was found "
        "under the inspected variable names."
    )

    print(
        "This does NOT block recovery of the adapter contract."
    )


# ==========================================================================================
# 12. Validate what we now know before implementing adapter
# ==========================================================================================

choose_move_source_count_3d2 = int(
    section3d2_choose_move_df[
        "source_recovered"
    ].sum()
)


runner_has_evaluated_agent_3d2 = bool(
    (
        section3d2_choose_calls_df[
            "receiver"
        ]
        .astype(
            str
        )
        .str.contains(
            "evaluated_agent",
            regex=False,
        )
    ).any()
)


runner_has_baseline_agent_3d2 = bool(
    (
        section3d2_choose_calls_df[
            "receiver"
        ]
        .astype(
            str
        )
        .str.contains(
            "baseline_agent",
            regex=False,
        )
    ).any()
)


section3d2_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "all historical harness objects available",

            "observed":
                int(
                    section3d2_status_df[
                        "available"
                    ].sum()
                ),

            "expected":
                len(
                    required_objects_3d2
                ),

            "passed":
                bool(
                    section3d2_status_df[
                        "available"
                    ].all()
                ),
        },

        {
            "validation":
                "all three choose_move methods recovered",

            "observed":
                choose_move_source_count_3d2,

            "expected":
                3,

            "passed":
                (
                    choose_move_source_count_3d2
                    ==
                    3
                ),
        },

        {
            "validation":
                "runner choose_move calls recovered",

            "observed":
                len(
                    section3d2_choose_calls_df
                ),

            "expected":
                ">= 2",

            "passed":
                (
                    len(
                        section3d2_choose_calls_df
                    )
                    >=
                    2
                ),
        },

        {
            "validation":
                "runner invokes evaluated agent",

            "observed":
                runner_has_evaluated_agent_3d2,

            "expected":
                True,

            "passed":
                runner_has_evaluated_agent_3d2,
        },

        {
            "validation":
                "runner invokes baseline agent",

            "observed":
                runner_has_baseline_agent_3d2,

            "expected":
                True,

            "passed":
                runner_has_baseline_agent_3d2,
        },

        {
            "validation":
                "TournamentDecision contract available",

            "observed":
                str(
                    decision_signature_3d2
                ),

            "expected":
                "constructor signature",

            "passed":
                decision_signature_3d2
                is not None,
        },

        {
            "validation":
                "R3 model remains frozen",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                (
                    int(
                        r3_policy_engine_3c2
                        .model
                        .n_features_in_
                    )
                    ==
                    46
                ),
        },
    ]
)


print("\nSECTION 3D.2 VALIDATION")
print("-" * 100)

display(
    section3d2_validation_df
)


assert (
    section3d2_validation_df[
        "passed"
    ].all()
), (
    "Section 3D.2 contract recovery failed. "
    "Do not implement the R3 tournament adapter yet."
)


print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 48 choose_move() CONTRACT RECOVERED")
print("✅ EXACT TournamentDecision CONTRACT RECOVERED")
print("✅ EXACT TOURNAMENT RUNNER CALL SITES RECOVERED")
print("✅ EVALUATED-AGENT INVOCATION VERIFIED")
print("✅ BASELINE-AGENT INVOCATION VERIFIED")
print("✅ HISTORICAL HARNESS REMAINS UNMODIFIED")
print("✅ FROZEN R3 MODEL REMAINS 46 FEATURES")
print("✅ SECTION 3D.2 COMPLETE")
print("⚠️ R3 TOURNAMENT ADAPTER NOT IMPLEMENTED YET")
print("⚠️ NO MATCH EXECUTED")
print("⚠️ NO RETRAINING")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.2 — RECOVER EXACT TOURNAMENT AGENT DECISION CONTRACT FOR R3 ADAPTER
====================================================================================================

HISTORICAL HARNESS STATUS
----------------------------------------------------------------------------------------------------

,object,available,object_type,module
0,TournamentDecision,True,type,notebook48_historical_benchmark_recovery
1,RandomLegalMoveAgent,True,type,notebook48_historical_benchmark_recovery
2,GreedyDamageAgent,True,type,notebook48_historical_benchmark_recovery
3,SearchAgentAdapter,True,type,notebook48_historical_benchmark_recovery
4,create_tournament_state,True,function,notebook48_historical_benchmark_recovery
5,run_tournament_match,True,function,notebook48_historical_benchmark_recovery

BASELINE choose_move() CONTRACT SUMMARY
----------------------------------------------------------------------------------------------------

,class,signature,source_recovered,returns_tournament_decision_text,references_legal_moves,references_state
0,RandomLegalMoveAgent,"(self, state: Any = None, depth: int | None = ...",True,True,True,True
1,GreedyDamageAgent,"(self, state: Any = None, depth: int | None = ...",True,True,True,True
2,SearchAgentAdapter,"(self, state: Any = None, depth: int | None = ...",True,False,False,True

EXACT HISTORICAL choose_move() SOURCES
----------------------------------------------------------------------------------------------------

====================================================================================================
RandomLegalMoveAgent.choose_move
====================================================================================================
    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_move = (
            self.random.choice(
                legal_moves
            )
        )

        confidence = (
            1.0
            / len(legal_moves)
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    confidence,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=
                    confidence,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision


====================================================================================================
GreedyDamageAgent.choose_move
====================================================================================================
    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        legal_moves = (
            get_current_legal_moves(
                resolved_state
            )
        )

        if not legal_moves:
            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason=
                        "No legal moves available.",
                )
            )

            return self.last_decision

        selected_index = max(
            range(
                len(legal_moves)
            ),
            key=lambda index: (
                tournament_move_damage(
                    legal_moves[index]
                ),
                -index,
            ),
        )

        selected_move = (
            legal_moves[
                selected_index
            ]
        )

        maximum_damage = (
            tournament_move_damage(
                selected_move
            )
        )

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    maximum_damage,

                search_depth=int(
                    depth or 0
                ),

                nodes=0,

                confidence=1.0,

                selected_move_name=
                    tournament_move_name(
                        selected_move
                    ),

                fallback=False,
            )
        )

        return self.last_decision


====================================================================================================
SearchAgentAdapter.choose_move
====================================================================================================
    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> Any:
        resolved_state = (
            state
            if state is not None
            else battle_state
        )

        if resolved_state is None:
            raise ValueError(
                "A battle state is required."
            )

        resolved_depth = int(
            depth
            if depth is not None
            else self.search_depth
        )

        self.last_decision = (
            self.inner_agent
            .choose_move(
                state=
                    resolved_state,

                depth=
                    resolved_depth,
            )
        )

        return self.last_decision


TOURNAMENT DECISION CONSTRUCTOR
----------------------------------------------------------------------------------------------------
(move: Any, score: float, search_depth: int, nodes: int, confidence: float = 0.0, selected_move_name: str | None = None, fallback: bool = False, reason: str | None = None) -> None

TOURNAMENT DECISION FIELDS
----------------------------------------------------------------------------------------------------

,field,type,default
0,move,typing.Any,<dataclasses._MISSING_TYPE object at 0x0000014...
1,score,<class 'float'>,<dataclasses._MISSING_TYPE object at 0x0000014...
2,search_depth,<class 'int'>,<dataclasses._MISSING_TYPE object at 0x0000014...
3,nodes,<class 'int'>,<dataclasses._MISSING_TYPE object at 0x0000014...
4,confidence,<class 'float'>,0.0
5,selected_move_name,str | None,None
6,fallback,<class 'bool'>,False
7,reason,str | None,None

RUN_TOURNAMENT_MATCH SIGNATURE
----------------------------------------------------------------------------------------------------
(match_id: int, evaluated_agent: Any, baseline_agent: Any, player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str, evaluated_agent_side: str, max_turns: int = 50, search_depth: int = 6, verbose: bool = False) -> notebook48_historical_benchmark_recovery.TournamentMatchResult

EXACT choose_move() INVOCATIONS INSIDE TOURNAMENT RUNNER
----------------------------------------------------------------------------------------------------

,line,receiver,positional_args,keyword_args,call
0,84,selected_agent,[],"{'state': 'resolved_state', 'depth': 'depth'}",selected_agent.choose_move(state=resolved_stat...

RUNNER CONTEXT AROUND choose_move()
----------------------------------------------------------------------------------------------------

====================================================================================================
Receiver: selected_agent | Runner relative line: 84
----------------------------------------------------------------------------------------------------
076:
077:             selected_agent = (
078:                 self.player_agent
079:                 if side == "Player"
080:                 else self.opponent_agent
081:             )
082:
083:             decision = (
084:                 selected_agent
085:                 .choose_move(
086:                     state=
087:                         resolved_state,
088:
089:                     depth=
090:                         depth,
091:                 )
092:             )
093:
094:             if bool(
095:                 getattr(
096:                     decision,

EXACT BASELINE choose_move() SIGNATURES
----------------------------------------------------------------------------------------------------
RandomLegalMoveAgent: (self, state: Any = None, depth: int | None = None, battle_state: Any = None, **kwargs: Any) -> notebook48_historical_benchmark_recovery.TournamentDecision
GreedyDamageAgent: (self, state: Any = None, depth: int | None = None, battle_state: Any = None, **kwargs: Any) -> notebook48_historical_benchmark_recovery.TournamentDecision
SearchAgentAdapter: (self, state: Any = None, depth: int | None = None, battle_state: Any = None, **kwargs: Any) -> Any

AVAILABLE EXISTING CARD OBJECTS FOR INTERFACE TEST
----------------------------------------------------------------------------------------------------
Player-card candidates: 0
Opponent-card candidates: 0

STATE INTERFACE TEST DEFERRED
----------------------------------------------------------------------------------------------------
No existing genuine player/opponent card pair was found under the inspected variable names.
This does NOT block recovery of the adapter contract.

SECTION 3D.2 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,all historical harness objects available,6,6,True
1,all three choose_move methods recovered,3,3,True
2,runner choose_move calls recovered,1,>= 2,False
3,runner invokes evaluated agent,False,True,False
4,runner invokes baseline agent,False,True,False
5,TournamentDecision contract available,"(move: Any, score: float, search_depth: int, n...",constructor signature,True
6,R3 model remains frozen,46,46,True

AssertionError: Section 3D.2 contract recovery failed. Do not implement the R3 tournament adapter yet.

In [49]:
# ==========================================================================================
# SECTION 3D.2A — CORRECT RUNNER ROUTING VALIDATION FOR GENERIC selected_agent.choose_move()
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.2A — CORRECT RUNNER ROUTING VALIDATION")
print("=" * 100)

import ast
import inspect
import pandas as pd


# ==========================================================================================
# 1. Reuse exact historical runner source
# ==========================================================================================

assert callable(
    run_tournament_match
)

runner_source_3d2a = inspect.getsource(
    run_tournament_match
)

runner_tree_3d2a = ast.parse(
    runner_source_3d2a
)


# ==========================================================================================
# 2. Recover every choose_move() call
# ==========================================================================================

choose_call_rows_3d2a = []


for node_3d2a in ast.walk(
    runner_tree_3d2a
):

    if not isinstance(
        node_3d2a,
        ast.Call,
    ):
        continue

    if not isinstance(
        node_3d2a.func,
        ast.Attribute,
    ):
        continue

    if node_3d2a.func.attr != "choose_move":
        continue

    receiver_3d2a = ast.unparse(
        node_3d2a.func.value
    )

    keyword_args_3d2a = {
        keyword_3d2a.arg:
            ast.unparse(
                keyword_3d2a.value
            )
        for keyword_3d2a
        in node_3d2a.keywords
        if keyword_3d2a.arg
        is not None
    }

    choose_call_rows_3d2a.append(
        {
            "line":
                node_3d2a.lineno,

            "receiver":
                receiver_3d2a,

            "keyword_args":
                keyword_args_3d2a,

            "full_call":
                ast.unparse(
                    node_3d2a
                ),
        }
    )


section3d2a_choose_calls_df = pd.DataFrame(
    choose_call_rows_3d2a
)


print("\nEXACT RUNNER choose_move() CALL")
print("-" * 100)

display(
    section3d2a_choose_calls_df
)


# ==========================================================================================
# 3. Recover assignments involving:
#
#       evaluated_agent
#       baseline_agent
#       player_agent
#       opponent_agent
#       selected_agent
#
# This proves routing rather than expecting separate choose_move calls.
# ==========================================================================================

ROUTING_NAMES_3D2A = {
    "evaluated_agent",
    "baseline_agent",
    "player_agent",
    "opponent_agent",
    "selected_agent",
    "evaluated_agent_side",
}


routing_rows_3d2a = []


for node_3d2a in ast.walk(
    runner_tree_3d2a
):

    # ------------------------------------------------------------------
    # Assignments
    # ------------------------------------------------------------------

    if isinstance(
        node_3d2a,
        (
            ast.Assign,
            ast.AnnAssign,
        ),
    ):

        if isinstance(
            node_3d2a,
            ast.Assign,
        ):
            targets_3d2a = (
                node_3d2a.targets
            )
        else:
            targets_3d2a = [
                node_3d2a.target
            ]

        assigned_names_3d2a = []

        for target_3d2a in (
            targets_3d2a
        ):

            if isinstance(
                target_3d2a,
                ast.Name,
            ):
                assigned_names_3d2a.append(
                    target_3d2a.id
                )

            elif isinstance(
                target_3d2a,
                ast.Tuple,
            ):
                assigned_names_3d2a.extend(
                    element_3d2a.id
                    for element_3d2a
                    in target_3d2a.elts
                    if isinstance(
                        element_3d2a,
                        ast.Name,
                    )
                )

        source_text_3d2a = ast.unparse(
            node_3d2a
        )

        names_in_source_3d2a = {
            name_3d2a.id
            for name_3d2a
            in ast.walk(
                node_3d2a
            )
            if isinstance(
                name_3d2a,
                ast.Name,
            )
        }

        if (
            set(
                assigned_names_3d2a
            )
            &
            ROUTING_NAMES_3D2A
            or
            names_in_source_3d2a
            &
            ROUTING_NAMES_3D2A
        ):

            routing_rows_3d2a.append(
                {
                    "line":
                        node_3d2a.lineno,

                    "node_type":
                        type(
                            node_3d2a
                        ).__name__,

                    "source":
                        source_text_3d2a,
                }
            )


    # ------------------------------------------------------------------
    # If / conditional blocks referencing routing names
    # ------------------------------------------------------------------

    elif isinstance(
        node_3d2a,
        ast.If,
    ):

        names_in_if_3d2a = {
            name_3d2a.id
            for name_3d2a
            in ast.walk(
                node_3d2a.test
            )
            if isinstance(
                name_3d2a,
                ast.Name,
            )
        }

        if (
            names_in_if_3d2a
            &
            ROUTING_NAMES_3D2A
        ):

            routing_rows_3d2a.append(
                {
                    "line":
                        node_3d2a.lineno,

                    "node_type":
                        "If",

                    "source":
                        ast.unparse(
                            node_3d2a.test
                        ),
                }
            )


section3d2a_routing_df = (
    pd.DataFrame(
        routing_rows_3d2a
    )
    .drop_duplicates(
        subset=[
            "line",
            "source",
        ]
    )
    .sort_values(
        "line"
    )
    .reset_index(
        drop=True
    )
)


print("\nAGENT ROUTING EVIDENCE")
print("-" * 100)

display(
    section3d2a_routing_df
)


# ==========================================================================================
# 4. Print exact runner context around selected_agent.choose_move()
# ==========================================================================================

assert len(
    section3d2a_choose_calls_df
) == 1


choose_line_3d2a = int(
    section3d2a_choose_calls_df.loc[
        0,
        "line",
    ]
)


runner_lines_3d2a = (
    runner_source_3d2a
    .splitlines()
)


context_start_3d2a = max(
    1,
    choose_line_3d2a - 20,
)

context_end_3d2a = min(
    len(
        runner_lines_3d2a
    ),
    choose_line_3d2a + 15,
)


print("\nRUNNER ROUTING CONTEXT")
print("-" * 100)


for line_number_3d2a in range(
    context_start_3d2a,
    context_end_3d2a + 1,
):

    print(
        f"{line_number_3d2a:03d}: "
        f"{runner_lines_3d2a[line_number_3d2a - 1]}"
    )


# ==========================================================================================
# 5. Recover exact common baseline choose_move signatures
# ==========================================================================================

baseline_classes_3d2a = {
    "RandomLegalMoveAgent":
        RandomLegalMoveAgent,

    "GreedyDamageAgent":
        GreedyDamageAgent,

    "SearchAgentAdapter":
        SearchAgentAdapter,
}


signature_rows_3d2a = []


for class_name_3d2a, class_obj_3d2a in (
    baseline_classes_3d2a.items()
):

    signature_rows_3d2a.append(
        {
            "class":
                class_name_3d2a,

            "choose_move_signature":
                str(
                    inspect.signature(
                        class_obj_3d2a.choose_move
                    )
                ),
        }
    )


section3d2a_signature_df = pd.DataFrame(
    signature_rows_3d2a
)


print("\nEXACT HISTORICAL AGENT CONTRACT")
print("-" * 100)

display(
    section3d2a_signature_df
)


# ==========================================================================================
# 6. TournamentDecision contract
# ==========================================================================================

decision_signature_3d2a = (
    inspect.signature(
        TournamentDecision
    )
)


print("\nTournamentDecision CONTRACT")
print("-" * 100)

print(
    decision_signature_3d2a
)


# ==========================================================================================
# 7. Explicit adapter contract derived ONLY from recovered historical source
# ==========================================================================================

adapter_contract_3d2a = {
    "method_name":
        "choose_move",

    "runner_receiver":
        section3d2a_choose_calls_df.loc[
            0,
            "receiver",
        ],

    "runner_keyword_arguments":
        section3d2a_choose_calls_df.loc[
            0,
            "keyword_args",
        ],

    "return_type":
        "TournamentDecision",

    "routing_model":
        (
            "Runner selects player_agent or opponent_agent "
            "into selected_agent, then invokes one generic "
            "selected_agent.choose_move(...) call."
        ),

    "r3_retraining":
        False,

    "r3_model_modification":
        False,
}


print("\nLOCKED R3 TOURNAMENT ADAPTER CONTRACT")
print("-" * 100)

for key_3d2a, value_3d2a in (
    adapter_contract_3d2a.items()
):

    print(
        f"{key_3d2a}: {value_3d2a}"
    )


# ==========================================================================================
# 8. Correct validation
# ==========================================================================================

choose_call_3d2a = (
    section3d2a_choose_calls_df
    .iloc[
        0
    ]
)


choose_receiver_is_selected_agent_3d2a = (
    choose_call_3d2a[
        "receiver"
    ]
    ==
    "selected_agent"
)


choose_keywords_3d2a = (
    choose_call_3d2a[
        "keyword_args"
    ]
)


state_passed_3d2a = (
    choose_keywords_3d2a.get(
        "state"
    )
    ==
    "resolved_state"
)


depth_passed_3d2a = (
    choose_keywords_3d2a.get(
        "depth"
    )
    ==
    "depth"
)


routing_source_text_3d2a = " ".join(
    section3d2a_routing_df[
        "source"
    ].astype(
        str
    )
)


evaluated_agent_appears_in_routing_3d2a = (
    "evaluated_agent"
    in routing_source_text_3d2a
)


baseline_agent_appears_in_routing_3d2a = (
    "baseline_agent"
    in routing_source_text_3d2a
)


selected_agent_appears_in_routing_3d2a = (
    "selected_agent"
    in routing_source_text_3d2a
)


section3d2a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exactly one generic choose_move call",

            "observed":
                len(
                    section3d2a_choose_calls_df
                ),

            "expected":
                1,

            "passed":
                len(
                    section3d2a_choose_calls_df
                )
                ==
                1,
        },

        {
            "validation":
                "generic receiver is selected_agent",

            "observed":
                choose_call_3d2a[
                    "receiver"
                ],

            "expected":
                "selected_agent",

            "passed":
                choose_receiver_is_selected_agent_3d2a,
        },

        {
            "validation":
                "runner passes resolved_state",

            "observed":
                choose_keywords_3d2a.get(
                    "state"
                ),

            "expected":
                "resolved_state",

            "passed":
                state_passed_3d2a,
        },

        {
            "validation":
                "runner passes search depth",

            "observed":
                choose_keywords_3d2a.get(
                    "depth"
                ),

            "expected":
                "depth",

            "passed":
                depth_passed_3d2a,
        },

        {
            "validation":
                "evaluated agent participates in routing",

            "observed":
                evaluated_agent_appears_in_routing_3d2a,

            "expected":
                True,

            "passed":
                evaluated_agent_appears_in_routing_3d2a,
        },

        {
            "validation":
                "baseline agent participates in routing",

            "observed":
                baseline_agent_appears_in_routing_3d2a,

            "expected":
                True,

            "passed":
                baseline_agent_appears_in_routing_3d2a,
        },

        {
            "validation":
                "selected_agent routing recovered",

            "observed":
                selected_agent_appears_in_routing_3d2a,

            "expected":
                True,

            "passed":
                selected_agent_appears_in_routing_3d2a,
        },

        {
            "validation":
                "three historical choose_move contracts available",

            "observed":
                len(
                    section3d2a_signature_df
                ),

            "expected":
                3,

            "passed":
                len(
                    section3d2a_signature_df
                )
                ==
                3,
        },

        {
            "validation":
                "TournamentDecision contract available",

            "observed":
                str(
                    decision_signature_3d2a
                ),

            "expected":
                "constructor signature",

            "passed":
                decision_signature_3d2a
                is not None,
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                )
                ==
                46,
        },
    ]
)


print("\nSECTION 3D.2A VALIDATION")
print("-" * 100)

display(
    section3d2a_validation_df
)


assert (
    section3d2a_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ PREVIOUS 3D.2 VALIDATION ASSUMPTION CORRECTED")
print("✅ EXACTLY ONE GENERIC selected_agent.choose_move() CALL VERIFIED")
print("✅ EVALUATED AGENT ROUTES THROUGH selected_agent")
print("✅ BASELINE AGENT ROUTES THROUGH selected_agent")
print("✅ RUNNER PASSES state=resolved_state")
print("✅ RUNNER PASSES depth=depth")
print("✅ TournamentDecision RETURN CONTRACT LOCKED")
print("✅ R3 TOURNAMENT ADAPTER INTERFACE IS NOW KNOWN")
print("✅ SECTION 3D.2A COMPLETE")
print("⚠️ PREVIOUS 3D.2 ASSERTION WAS A DIAGNOSTIC ERROR — NOT A PROJECT FAILURE")
print("⚠️ NO MATCH EXECUTED")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.2A — CORRECT RUNNER ROUTING VALIDATION
====================================================================================================

EXACT RUNNER choose_move() CALL
----------------------------------------------------------------------------------------------------

,line,receiver,keyword_args,full_call
0,84,selected_agent,"{'state': 'resolved_state', 'depth': 'depth'}",selected_agent.choose_move(state=resolved_stat...

AGENT ROUTING EVIDENCE
----------------------------------------------------------------------------------------------------

   line node_type                                             source
0    16        If  evaluated_agent_side not in {'Player', 'Oppone...
1    44    Assign                   self.player_agent = player_agent
2    48    Assign               self.opponent_agent = opponent_agent
3    77    Assign  selected_agent = self.player_agent if side == ...
4    83    Assign  decision = selected_agent.choose_move(state=re...
5   105        If                   evaluated_agent_side == 'Player'
6   106    Assign  side_agent = SideAwareAgent(player_agent=evalu...
7   115    Assign  side_agent = SideAwareAgent(player_agent=basel...
8   168        If                     winner == evaluated_agent_side

RUNNER ROUTING CONTEXT
----------------------------------------------------------------------------------------------------
064:                 else battle_state
065:             )
066:
067:             if resolved_state is None:
068:                 raise ValueError(
069:                     "A battle state is required."
070:                 )
071:
072:             side = str(
073:                 resolved_state
074:                 .current_player
075:             )
076:
077:             selected_agent = (
078:                 self.player_agent
079:                 if side == "Player"
080:                 else self.opponent_agent
081:             )
082:
083:             decision = (
084:                 selected_agent
085:                 .choose_move(
086:                     state=
087:                         resolved_state,
088:
089:                     depth=
090:                         depth,
091:                 )
092:             )
093:
094:             if bool(
095:                 getattr(
096:                     decision,
097:                     "fallback",
098:                     False,
099:                 )

EXACT HISTORICAL AGENT CONTRACT
----------------------------------------------------------------------------------------------------

                  class                              choose_move_signature
0  RandomLegalMoveAgent  (self, state: Any = None, depth: int | None = ...
1     GreedyDamageAgent  (self, state: Any = None, depth: int | None = ...
2    SearchAgentAdapter  (self, state: Any = None, depth: int | None = ...

TournamentDecision CONTRACT
----------------------------------------------------------------------------------------------------
(move: Any, score: float, search_depth: int, nodes: int, confidence: float = 0.0, selected_move_name: str | None = None, fallback: bool = False, reason: str | None = None) -> None

LOCKED R3 TOURNAMENT ADAPTER CONTRACT
----------------------------------------------------------------------------------------------------
method_name: choose_move
runner_receiver: selected_agent
runner_keyword_arguments: {'state': 'resolved_state', 'depth': 'depth'}
return_type: TournamentDecision
routing_model: Runner selects player_agent or opponent_agent into selected_agent, then invokes one generic selected_agent.choose_move(...) call.
r3_retraining: False
r3_model_modification: False

SECTION 3D.2A VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,exactly one generic choose_move call,1,1,True
1,generic receiver is selected_agent,selected_agent,selected_agent,True
2,runner passes resolved_state,resolved_state,resolved_state,True
3,runner passes search depth,depth,depth,True
4,evaluated agent participates in routing,True,True,True
5,baseline agent participates in routing,True,True,True
6,selected_agent routing recovered,True,True,True
7,three historical choose_move contracts available,3,3,True
8,TournamentDecision contract available,"(move: Any, score: float, search_depth: int, n...",constructor signature,True
9,frozen R3 remains 46 features,46,46,True

====================================================================================================
✅ PREVIOUS 3D.2 VALIDATION ASSUMPTION CORRECTED
✅ EXACTLY ONE GENERIC selected_agent.choose_move() CALL VERIFIED
✅ EVALUATED AGENT ROUTES THROUGH selected_agent
✅ BASELINE AGENT ROUTES THROUGH selected_agent
✅ RUNNER PASSES state=resolved_state
✅ RUNNER PASSES depth=depth
✅ TournamentDecision RETURN CONTRACT LOCKED
✅ R3 TOURNAMENT ADAPTER INTERFACE IS NOW KNOWN
✅ SECTION 3D.2A COMPLETE
⚠️ PREVIOUS 3D.2 ASSERTION WAS A DIAGNOSTIC ERROR — NOT A PROJECT FAILURE
⚠️ NO MATCH EXECUTED
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [50]:
# ==========================================================================================
# SECTION 3D.3 — BUILD EXACT R3 TOURNAMENT AGENT ADAPTER
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.3 — BUILD EXACT R3 TOURNAMENT AGENT ADAPTER")
print("=" * 100)

from typing import Any
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Require validated frozen R3 and historical tournament contract
# ==========================================================================================

assert (
    "r3_policy_engine_3c2"
    in globals()
)

assert (
    r3_policy_engine_3c2.model.n_features_in_
    ==
    46
)

assert callable(
    get_current_legal_moves
)

assert callable(
    extract_move_name
)

assert callable(
    TournamentDecision
)


# ==========================================================================================
# 2. Historical-compatible adapter
# ==========================================================================================

class R3TournamentAgentAdapter:
    """
    Adapt the frozen R3 live policy engine to the exact Notebook 48
    tournament choose_move() contract.

    This class does NOT:
    - retrain R3
    - modify the RandomForest
    - change retained features
    - modify simulator legality
    - modify Notebook 48 tournament logic
    """

    def __init__(
        self,
        r3_policy_engine,
        name: str = "R3_STATE_CENTRIC_POLICY",
    ) -> None:

        self.r3_policy_engine = (
            r3_policy_engine
        )

        self.name = str(
            name
        )

        self.last_decision = None
        self.last_policy_result = None

        # --------------------------------------------------------------
        # Frozen contract checks
        # --------------------------------------------------------------

        assert (
            int(
                self.r3_policy_engine
                .model
                .n_features_in_
            )
            ==
            46
        )

        assert (
            len(
                self.r3_policy_engine
                .classes_
            )
            ==
            6
        )


    def choose_move(
        self,
        state: Any = None,
        depth: int | None = None,
        battle_state: Any = None,
        **kwargs: Any,
    ) -> TournamentDecision:
        """
        Exact historical tournament-agent method contract.
        """

        # --------------------------------------------------------------
        # Resolve state using same compatibility pattern as baselines
        # --------------------------------------------------------------

        resolved_state = (
            state
            if state is not None
            else battle_state
        )


        if resolved_state is None:

            raise ValueError(
                "A battle state is required."
            )


        # --------------------------------------------------------------
        # Resolve exact simulator legal moves
        # --------------------------------------------------------------

        legal_moves = list(
            get_current_legal_moves(
                resolved_state
            )
        )


        # --------------------------------------------------------------
        # Historical-style no-legal-move fallback
        # --------------------------------------------------------------

        if not legal_moves:

            self.last_policy_result = None

            self.last_decision = (
                TournamentDecision(
                    move=None,
                    score=0.0,
                    search_depth=int(
                        depth or 0
                    ),
                    nodes=0,
                    confidence=0.0,
                    selected_move_name=None,
                    fallback=True,
                    reason="No legal moves available.",
                )
            )

            return self.last_decision


        # --------------------------------------------------------------
        # Execute already-validated frozen R3 legality-aware policy
        # --------------------------------------------------------------

        policy_result = (
            self.r3_policy_engine
            .score_moves(
                battle_state=
                    resolved_state,

                legal_moves=
                    legal_moves,
            )
        )


        self.last_policy_result = (
            policy_result
        )


        selected_move = (
            policy_result.get(
                "selected_move"
            )
        )


        selected_move_name = (
            policy_result.get(
                "selected_move_name"
            )
        )


        confidence = float(
            policy_result.get(
                "confidence",
                0.0,
            )
        )


        fallback = bool(
            policy_result.get(
                "fallback",
                False,
            )
        )


        legal_probability_mass = float(
            policy_result.get(
                "legal_probability_mass",
                0.0,
            )
        )


        # --------------------------------------------------------------
        # Safety: selected move must come from simulator legal list
        # --------------------------------------------------------------

        if selected_move not in legal_moves:

            raise AssertionError(
                "R3 tournament adapter received a selected move "
                "that is not present in simulator legal moves."
            )


        # --------------------------------------------------------------
        # Tournament score
        #
        # Use confidence as adapter score because Notebook 48 requires
        # a numeric score and R3's decision confidence is the closest
        # direct policy-quality quantity.
        #
        # This does NOT affect which move R3 chooses.
        # --------------------------------------------------------------

        tournament_score = float(
            confidence
        )


        # --------------------------------------------------------------
        # Diagnostic reason only
        # --------------------------------------------------------------

        if fallback:

            reason = (
                "R3 legality fallback used because no "
                "model probability mass covered legal actions."
            )

        else:

            reason = (
                "Frozen R3 model-driven legal decision."
            )


        # --------------------------------------------------------------
        # Build exact historical TournamentDecision
        # --------------------------------------------------------------

        self.last_decision = (
            TournamentDecision(
                move=
                    selected_move,

                score=
                    tournament_score,

                search_depth=
                    int(
                        depth or 0
                    ),

                nodes=
                    0,

                confidence=
                    confidence,

                selected_move_name=
                    selected_move_name,

                fallback=
                    fallback,

                reason=
                    reason,
            )
        )


        return (
            self.last_decision
        )


# ==========================================================================================
# 3. Instantiate adapter
# ==========================================================================================

r3_tournament_agent_3d3 = (
    R3TournamentAgentAdapter(
        r3_policy_engine=
            r3_policy_engine_3c2,

        name=
            "R3_STATE_CENTRIC_POLICY",
    )
)


print("\nR3 TOURNAMENT ADAPTER")
print("-" * 100)

print(
    "Type:",
    type(
        r3_tournament_agent_3d3
    ).__name__
)

print(
    "Name:",
    r3_tournament_agent_3d3.name
)

print(
    "Frozen model:",
    type(
        r3_tournament_agent_3d3
        .r3_policy_engine
        .model
    ).__name__
)

print(
    "Feature count:",
    r3_tournament_agent_3d3
    .r3_policy_engine
    .model
    .n_features_in_
)


# ==========================================================================================
# 4. Reuse exact historical Pikachu / Charmander templates
# ==========================================================================================

assert (
    "TOURNAMENT_CARD_TEMPLATES"
    in globals()
)

assert (
    len(
        TOURNAMENT_CARD_TEMPLATES
    )
    >=
    2
)


adapter_player_card_3d3 = (
    TOURNAMENT_CARD_TEMPLATES[
        0
    ]
)

adapter_opponent_card_3d3 = (
    TOURNAMENT_CARD_TEMPLATES[
        1
    ]
)


print("\nADAPTER TEST CARDS")
print("-" * 100)

print(
    "Player:",
    adapter_player_card_3d3[
        "name"
    ]
)

print(
    "Opponent:",
    adapter_opponent_card_3d3[
        "name"
    ]
)


# ==========================================================================================
# 5. Build genuine historical tournament state
# ==========================================================================================

adapter_test_state_3d3 = (
    create_tournament_state(
        player_card=
            adapter_player_card_3d3,

        opponent_card=
            adapter_opponent_card_3d3,

        starting_side=
            "Player",
    )
)


print("\nGENUINE TOURNAMENT STATE")
print("-" * 100)

print(
    "Type:",
    type(
        adapter_test_state_3d3
    ).__name__
)

print(
    "Current side:",
    getattr(
        adapter_test_state_3d3,
        "current_player",
        getattr(
            adapter_test_state_3d3,
            "current_side",
            None,
        ),
    )
)


# ==========================================================================================
# 6. Inspect legal moves before adapter execution
# ==========================================================================================

adapter_legal_moves_3d3 = list(
    get_current_legal_moves(
        adapter_test_state_3d3
    )
)


adapter_legal_names_3d3 = [
    extract_move_name(
        move
    )
    for move
    in adapter_legal_moves_3d3
]


print("\nSIMULATOR LEGAL MOVES")
print("-" * 100)

for index_3d3, move_name_3d3 in enumerate(
    adapter_legal_names_3d3,
    start=1,
):

    print(
        f"{index_3d3:02d}. "
        f"{move_name_3d3}"
    )


assert (
    len(
        adapter_legal_moves_3d3
    )
    >=
    1
)


# ==========================================================================================
# 7. Execute exact historical choose_move() interface
# ==========================================================================================

print("\nEXECUTING R3 TOURNAMENT ADAPTER choose_move()")
print("-" * 100)


adapter_decision_3d3 = (
    r3_tournament_agent_3d3
    .choose_move(
        state=
            adapter_test_state_3d3,

        depth=
            6,
    )
)


print(
    "Decision type:",
    type(
        adapter_decision_3d3
    ).__name__
)


print("\nTOURNAMENT DECISION")
print("-" * 100)

print(
    "Move:",
    adapter_decision_3d3.move
)

print(
    "Selected move name:",
    adapter_decision_3d3.selected_move_name
)

print(
    "Score:",
    adapter_decision_3d3.score
)

print(
    "Confidence:",
    adapter_decision_3d3.confidence
)

print(
    "Search depth:",
    adapter_decision_3d3.search_depth
)

print(
    "Nodes:",
    adapter_decision_3d3.nodes
)

print(
    "Fallback:",
    adapter_decision_3d3.fallback
)

print(
    "Reason:",
    adapter_decision_3d3.reason
)


# ==========================================================================================
# 8. Inspect underlying R3 policy result
# ==========================================================================================

adapter_policy_result_3d3 = (
    r3_tournament_agent_3d3
    .last_policy_result
)


print("\nUNDERLYING R3 POLICY RESULT")
print("-" * 100)

for key_3d3, value_3d3 in (
    adapter_policy_result_3d3.items()
):

    print(
        f"{key_3d3}: {value_3d3}"
    )


# ==========================================================================================
# 9. Validate adapter did not alter R3 selection
# ==========================================================================================

policy_selected_name_3d3 = (
    adapter_policy_result_3d3.get(
        "selected_move_name"
    )
)


policy_selected_move_3d3 = (
    adapter_policy_result_3d3.get(
        "selected_move"
    )
)


decision_is_legal_3d3 = (
    adapter_decision_3d3.move
    in adapter_legal_moves_3d3
)


same_move_object_3d3 = (
    adapter_decision_3d3.move
    is
    policy_selected_move_3d3
)


same_move_name_3d3 = (
    adapter_decision_3d3
    .selected_move_name
    ==
    policy_selected_name_3d3
)


same_fallback_3d3 = (
    bool(
        adapter_decision_3d3
        .fallback
    )
    ==
    bool(
        adapter_policy_result_3d3.get(
            "fallback",
            False,
        )
    )
)


same_confidence_3d3 = (
    np.isclose(
        float(
            adapter_decision_3d3
            .confidence
        ),
        float(
            adapter_policy_result_3d3.get(
                "confidence",
                0.0,
            )
        ),
    )
)


print("\nADAPTER TRANSLATION CHECK")
print("-" * 100)

print(
    "Decision is simulator legal:",
    decision_is_legal_3d3
)

print(
    "Same move object:",
    same_move_object_3d3
)

print(
    "Same move name:",
    same_move_name_3d3
)

print(
    "Same fallback flag:",
    same_fallback_3d3
)

print(
    "Same confidence:",
    same_confidence_3d3
)


# ==========================================================================================
# 10. Exact choose_move signature check
# ==========================================================================================

import inspect


adapter_signature_3d3 = (
    inspect.signature(
        R3TournamentAgentAdapter
        .choose_move
    )
)


print("\nADAPTER choose_move() SIGNATURE")
print("-" * 100)

print(
    adapter_signature_3d3
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3d3_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "adapter instantiated",

            "observed":
                type(
                    r3_tournament_agent_3d3
                ).__name__,

            "expected":
                "R3TournamentAgentAdapter",

            "passed":
                type(
                    r3_tournament_agent_3d3
                ).__name__
                ==
                "R3TournamentAgentAdapter",
        },

        {
            "validation":
                "genuine tournament state used",

            "observed":
                type(
                    adapter_test_state_3d3
                ).__name__,

            "expected":
                "BattleState",

            "passed":
                type(
                    adapter_test_state_3d3
                ).__name__
                ==
                "BattleState",
        },

        {
            "validation":
                "legal moves available",

            "observed":
                len(
                    adapter_legal_moves_3d3
                ),

            "expected":
                ">= 1",

            "passed":
                len(
                    adapter_legal_moves_3d3
                )
                >=
                1,
        },

        {
            "validation":
                "TournamentDecision returned",

            "observed":
                type(
                    adapter_decision_3d3
                ).__name__,

            "expected":
                "TournamentDecision",

            "passed":
                type(
                    adapter_decision_3d3
                ).__name__
                ==
                "TournamentDecision",
        },

        {
            "validation":
                "selected move simulator legal",

            "observed":
                decision_is_legal_3d3,

            "expected":
                True,

            "passed":
                decision_is_legal_3d3,
        },

        {
            "validation":
                "adapter preserves R3 move object",

            "observed":
                same_move_object_3d3,

            "expected":
                True,

            "passed":
                same_move_object_3d3,
        },

        {
            "validation":
                "adapter preserves R3 move name",

            "observed":
                same_move_name_3d3,

            "expected":
                True,

            "passed":
                same_move_name_3d3,
        },

        {
            "validation":
                "adapter preserves R3 fallback flag",

            "observed":
                same_fallback_3d3,

            "expected":
                True,

            "passed":
                same_fallback_3d3,
        },

        {
            "validation":
                "adapter preserves R3 confidence",

            "observed":
                same_confidence_3d3,

            "expected":
                True,

            "passed":
                same_confidence_3d3,
        },

        {
            "validation":
                "search depth propagated",

            "observed":
                adapter_decision_3d3
                .search_depth,

            "expected":
                6,

            "passed":
                adapter_decision_3d3
                .search_depth
                ==
                6,
        },

        {
            "validation":
                "frozen model still 46 features",

            "observed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                )
                ==
                46,
        },
    ]
)


print("\nSECTION 3D.3 VALIDATION")
print("-" * 100)

display(
    section3d3_validation_df
)


assert (
    section3d3_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ R3 TOURNAMENT AGENT ADAPTER CREATED")
print("✅ EXACT NOTEBOOK 48 choose_move() INTERFACE SUPPORTED")
print("✅ EXACT TournamentDecision RETURN TYPE PRODUCED")
print("✅ GENUINE HISTORICAL TOURNAMENT BattleState USED")
print("✅ SIMULATOR LEGAL MOVES USED")
print("✅ FROZEN R3 POLICY EXECUTED")
print("✅ R3 MOVE PRESERVED THROUGH ADAPTER")
print("✅ R3 CONFIDENCE / FALLBACK PRESERVED")
print("✅ FROZEN 46-FEATURE MODEL REMAINS UNCHANGED")
print("✅ SECTION 3D.3 COMPLETE")
print("⚠️ ADAPTER ONLY — NO MODEL MODIFICATION")
print("⚠️ NO RETRAINING")
print("⚠️ NO TOURNAMENT MATCH RUN YET")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.3 — BUILD EXACT R3 TOURNAMENT AGENT ADAPTER
====================================================================================================

R3 TOURNAMENT ADAPTER
----------------------------------------------------------------------------------------------------
Type: R3TournamentAgentAdapter
Name: R3_STATE_CENTRIC_POLICY
Frozen model: RandomForestClassifier
Feature count: 46

AssertionError:

In [51]:
# ==========================================================================================
# SECTION 3D.3A — RECOVER EXACT NOTEBOOK 48 TOURNAMENT CARD TEMPLATES
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.3A — RECOVER EXACT NOTEBOOK 48 TOURNAMENT CARD TEMPLATES")
print("=" * 100)

from pathlib import Path
import ast
import pandas as pd


# ==========================================================================================
# 1. Confirm the important part of Section 3D.3 already succeeded
# ==========================================================================================

assert (
    "R3TournamentAgentAdapter"
    in globals()
), (
    "R3TournamentAgentAdapter was not created. "
    "Do not continue until Section 3D.3 has at least defined the adapter."
)


assert (
    "r3_tournament_agent_3d3"
    in globals()
), (
    "The R3 tournament adapter instance was not created."
)


assert (
    int(
        r3_tournament_agent_3d3
        .r3_policy_engine
        .model
        .n_features_in_
    )
    ==
    46
)


print("\nEXISTING R3 ADAPTER STATUS")
print("-" * 100)

print(
    "Type:",
    type(
        r3_tournament_agent_3d3
    ).__name__
)

print(
    "Name:",
    r3_tournament_agent_3d3.name
)

print(
    "Model:",
    type(
        r3_tournament_agent_3d3
        .r3_policy_engine
        .model
    ).__name__
)

print(
    "Feature count:",
    r3_tournament_agent_3d3
    .r3_policy_engine
    .model
    .n_features_in_
)


# ==========================================================================================
# 2. First search existing Notebook 60 namespaces
#
# We prefer an already-recovered exact object if one exists.
# ==========================================================================================

target_name_3d3a = (
    "TOURNAMENT_CARD_TEMPLATES"
)


namespace_candidates_3d3a = []


for namespace_name_3d3a in [
    "historical_ns_2e",
    "objects_2d",
    "top_level_nodes_2e",
]:

    namespace_3d3a = globals().get(
        namespace_name_3d3a,
        None,
    )


    if not isinstance(
        namespace_3d3a,
        dict,
    ):
        continue


    namespace_candidates_3d3a.append(
        {
            "namespace":
                namespace_name_3d3a,

            "target_present":
                target_name_3d3a
                in namespace_3d3a,

            "object_type":
                (
                    type(
                        namespace_3d3a.get(
                            target_name_3d3a
                        )
                    ).__name__
                    if target_name_3d3a
                    in namespace_3d3a
                    else
                    None
                ),
        }
    )


section3d3a_namespace_df = pd.DataFrame(
    namespace_candidates_3d3a
)


print("\nEXISTING NAMESPACE SEARCH")
print("-" * 100)

display(
    section3d3a_namespace_df
)


# ==========================================================================================
# 3. Bind from an existing exact namespace if present
# ==========================================================================================

recovery_source_3d3a = None


for namespace_name_3d3a in [
    "historical_ns_2e",
    "objects_2d",
    "top_level_nodes_2e",
]:

    namespace_3d3a = globals().get(
        namespace_name_3d3a,
        None,
    )


    if (
        isinstance(
            namespace_3d3a,
            dict,
        )
        and
        target_name_3d3a
        in namespace_3d3a
        and
        isinstance(
            namespace_3d3a[
                target_name_3d3a
            ],
            list,
        )
    ):

        TOURNAMENT_CARD_TEMPLATES = (
            namespace_3d3a[
                target_name_3d3a
            ]
        )

        recovery_source_3d3a = (
            f"existing namespace: "
            f"{namespace_name_3d3a}"
        )

        break


# ==========================================================================================
# 4. If not in a current namespace, recover the exact literal assignment from Notebook 48
#
# No historical script is executed.
# ast.literal_eval() accepts only Python literal structures.
# ==========================================================================================

if recovery_source_3d3a is None:

    PROJECT_ROOT_3D3A = Path(
        r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
    )


    NOTEBOOK48_SCRIPT_3D3A = (
        PROJECT_ROOT_3D3A
        / "scripts"
        / "48_tournament_evaluation_and_elo_benchmarking.py"
    )


    print("\nAUTHORITATIVE NOTEBOOK 48 SCRIPT")
    print("-" * 100)

    print(
        NOTEBOOK48_SCRIPT_3D3A
    )


    assert (
        NOTEBOOK48_SCRIPT_3D3A.exists()
    ), (
        "Authoritative Notebook 48 script not found."
    )


    source_text_3d3a = (
        NOTEBOOK48_SCRIPT_3D3A
        .read_text(
            encoding="utf-8"
        )
    )


    source_tree_3d3a = ast.parse(
        source_text_3d3a
    )


    assignment_candidates_3d3a = []


    for node_3d3a in (
        source_tree_3d3a.body
    ):

        target_matches_3d3a = False


        # --------------------------------------------------------------
        # Standard assignment
        # --------------------------------------------------------------

        if isinstance(
            node_3d3a,
            ast.Assign,
        ):

            for target_3d3a in (
                node_3d3a.targets
            ):

                if (
                    isinstance(
                        target_3d3a,
                        ast.Name,
                    )
                    and
                    target_3d3a.id
                    ==
                    target_name_3d3a
                ):

                    target_matches_3d3a = True


        # --------------------------------------------------------------
        # Annotated assignment
        # --------------------------------------------------------------

        elif isinstance(
            node_3d3a,
            ast.AnnAssign,
        ):

            if (
                isinstance(
                    node_3d3a.target,
                    ast.Name,
                )
                and
                node_3d3a.target.id
                ==
                target_name_3d3a
            ):

                target_matches_3d3a = True


        if not target_matches_3d3a:
            continue


        assignment_candidates_3d3a.append(
            node_3d3a
        )


    print("\nEXACT ASSIGNMENT CANDIDATES")
    print("-" * 100)

    print(
        "Count:",
        len(
            assignment_candidates_3d3a
        )
    )


    assert (
        len(
            assignment_candidates_3d3a
        )
        >=
        1
    ), (
        "TOURNAMENT_CARD_TEMPLATES assignment "
        "was not found in Notebook 48."
    )


    # --------------------------------------------------------------
    # Use the first top-level authoritative assignment.
    # --------------------------------------------------------------

    assignment_node_3d3a = (
        assignment_candidates_3d3a[
            0
        ]
    )


    assignment_value_node_3d3a = (
        assignment_node_3d3a.value
    )


    exact_templates_3d3a = (
        ast.literal_eval(
            assignment_value_node_3d3a
        )
    )


    assert isinstance(
        exact_templates_3d3a,
        list,
    )


    TOURNAMENT_CARD_TEMPLATES = (
        exact_templates_3d3a
    )


    recovery_source_3d3a = (
        "authoritative Notebook 48 literal assignment"
    )


# ==========================================================================================
# 5. Inspect recovered templates
# ==========================================================================================

print("\nRECOVERED TOURNAMENT CARD TEMPLATES")
print("-" * 100)

print(
    "Recovery source:",
    recovery_source_3d3a
)

print(
    "Template count:",
    len(
        TOURNAMENT_CARD_TEMPLATES
    )
)


template_rows_3d3a = []


for index_3d3a, card_3d3a in enumerate(
    TOURNAMENT_CARD_TEMPLATES,
    start=1,
):

    attacks_3d3a = list(
        card_3d3a.get(
            "attacks",
            [],
        )
    )


    attack_names_3d3a = [
        attack_3d3a.get(
            "Move Name"
        )
        for attack_3d3a
        in attacks_3d3a
    ]


    template_rows_3d3a.append(
        {
            "index":
                index_3d3a,

            "name":
                card_3d3a.get(
                    "name"
                ),

            "hp":
                card_3d3a.get(
                    "hp"
                ),

            "attack_count":
                len(
                    attacks_3d3a
                ),

            "attacks":
                attack_names_3d3a,
        }
    )


section3d3a_templates_df = pd.DataFrame(
    template_rows_3d3a
)


display(
    section3d3a_templates_df
)


# ==========================================================================================
# 6. Exact historical smoke-card check
# ==========================================================================================

assert (
    len(
        TOURNAMENT_CARD_TEMPLATES
    )
    ==
    6
), (
    "Expected six historical Notebook 48 tournament card templates."
)


smoke_player_card_3d3a = (
    TOURNAMENT_CARD_TEMPLATES[
        0
    ]
)

smoke_opponent_card_3d3a = (
    TOURNAMENT_CARD_TEMPLATES[
        1
    ]
)


print("\nEXACT HISTORICAL SMOKE CARDS")
print("-" * 100)

print(
    "Player:",
    smoke_player_card_3d3a[
        "name"
    ]
)

print(
    "Opponent:",
    smoke_opponent_card_3d3a[
        "name"
    ]
)


# ==========================================================================================
# 7. Validate templates without running a tournament match
# ==========================================================================================

expected_names_3d3a = [
    "Pikachu",
    "Charmander",
    "Squirtle",
    "Bulbasaur",
    "Eevee",
    "Meowth",
]


observed_names_3d3a = [
    card_3d3a[
        "name"
    ]
    for card_3d3a
    in TOURNAMENT_CARD_TEMPLATES
]


section3d3a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "existing R3 adapter preserved",

            "observed":
                type(
                    r3_tournament_agent_3d3
                ).__name__,

            "expected":
                "R3TournamentAgentAdapter",

            "passed":
                type(
                    r3_tournament_agent_3d3
                ).__name__
                ==
                "R3TournamentAgentAdapter",
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                )
                ==
                46,
        },

        {
            "validation":
                "six historical templates recovered",

            "observed":
                len(
                    TOURNAMENT_CARD_TEMPLATES
                ),

            "expected":
                6,

            "passed":
                len(
                    TOURNAMENT_CARD_TEMPLATES
                )
                ==
                6,
        },

        {
            "validation":
                "exact historical card order",

            "observed":
                observed_names_3d3a,

            "expected":
                expected_names_3d3a,

            "passed":
                observed_names_3d3a
                ==
                expected_names_3d3a,
        },

        {
            "validation":
                "smoke player is Pikachu",

            "observed":
                smoke_player_card_3d3a[
                    "name"
                ],

            "expected":
                "Pikachu",

            "passed":
                smoke_player_card_3d3a[
                    "name"
                ]
                ==
                "Pikachu",
        },

        {
            "validation":
                "smoke opponent is Charmander",

            "observed":
                smoke_opponent_card_3d3a[
                    "name"
                ],

            "expected":
                "Charmander",

            "passed":
                smoke_opponent_card_3d3a[
                    "name"
                ]
                ==
                "Charmander",
        },
    ]
)


print("\nSECTION 3D.3A VALIDATION")
print("-" * 100)

display(
    section3d3a_validation_df
)


assert (
    section3d3a_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ R3 TOURNAMENT ADAPTER FROM 3D.3 PRESERVED")
print("✅ EXACT NOTEBOOK 48 CARD TEMPLATE ASSIGNMENT RECOVERED")
print("✅ SIX HISTORICAL TOURNAMENT CARDS AVAILABLE")
print("✅ HISTORICAL PIKACHU / CHARMANDER SMOKE PAIR RESTORED")
print("✅ NO HISTORICAL SCRIPT EXECUTED")
print("✅ FROZEN R3 MODEL REMAINS 46 FEATURES")
print("✅ SECTION 3D.3A COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO TOURNAMENT MATCH RUN YET")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.3A — RECOVER EXACT NOTEBOOK 48 TOURNAMENT CARD TEMPLATES
====================================================================================================

EXISTING R3 ADAPTER STATUS
----------------------------------------------------------------------------------------------------
Type: R3TournamentAgentAdapter
Name: R3_STATE_CENTRIC_POLICY
Model: RandomForestClassifier
Feature count: 46

EXISTING NAMESPACE SEARCH
----------------------------------------------------------------------------------------------------

            namespace  target_present object_type
0    historical_ns_2e            True        list
1          objects_2d           False         NaN
2  top_level_nodes_2e           False         NaN

RECOVERED TOURNAMENT CARD TEMPLATES
----------------------------------------------------------------------------------------------------
Recovery source: existing namespace: historical_ns_2e
Template count: 6

   index        name   hp  attack_count                      attacks
0      1     Pikachu  120             2  [Quick Attack, Thunderbolt]
1      2  Charmander  100             2        [Scratch, Flame Tail]
2      3    Squirtle  110             2        [Tackle, Water Pulse]
3      4   Bulbasaur  110             2      [Vine Whip, Razor Leaf]
4      5       Eevee  100             2            [Tail Whap, Bite]
5      6      Meowth   90             2       [Scratch, Fury Swipes]

EXACT HISTORICAL SMOKE CARDS
----------------------------------------------------------------------------------------------------
Player: Pikachu
Opponent: Charmander

SECTION 3D.3A VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,existing R3 adapter preserved,R3TournamentAgentAdapter,R3TournamentAgentAdapter,True
1,frozen R3 remains 46 features,46,46,True
2,six historical templates recovered,6,6,True
3,exact historical card order,"[Pikachu, Charmander, Squirtle, Bulbasaur, Eev...","[Pikachu, Charmander, Squirtle, Bulbasaur, Eev...",True
4,smoke player is Pikachu,Pikachu,Pikachu,True
5,smoke opponent is Charmander,Charmander,Charmander,True

====================================================================================================
✅ R3 TOURNAMENT ADAPTER FROM 3D.3 PRESERVED
✅ EXACT NOTEBOOK 48 CARD TEMPLATE ASSIGNMENT RECOVERED
✅ SIX HISTORICAL TOURNAMENT CARDS AVAILABLE
✅ HISTORICAL PIKACHU / CHARMANDER SMOKE PAIR RESTORED
✅ NO HISTORICAL SCRIPT EXECUTED
✅ FROZEN R3 MODEL REMAINS 46 FEATURES
✅ SECTION 3D.3A COMPLETE
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ NO TOURNAMENT MATCH RUN YET
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [52]:
# ==========================================================================================
# SECTION 3D.3B — RESUME R3 TOURNAMENT ADAPTER VALIDATION ON GENUINE HISTORICAL STATE
# ==========================================================================================

print("=" * 100)
print("SECTION 3D.3B — RESUME R3 TOURNAMENT ADAPTER VALIDATION")
print("=" * 100)

import inspect
import numpy as np
import pandas as pd


# ==========================================================================================
# 1. Confirm preserved objects
# ==========================================================================================

assert (
    "r3_tournament_agent_3d3"
    in globals()
)

assert (
    "TOURNAMENT_CARD_TEMPLATES"
    in globals()
)

assert callable(
    create_tournament_state
)

assert callable(
    get_current_legal_moves
)

assert callable(
    extract_move_name
)

assert callable(
    TournamentDecision
)

assert (
    int(
        r3_tournament_agent_3d3
        .r3_policy_engine
        .model
        .n_features_in_
    )
    ==
    46
)


# ==========================================================================================
# 2. Exact historical smoke cards
# ==========================================================================================

adapter_player_card_3d3b = (
    TOURNAMENT_CARD_TEMPLATES[
        0
    ]
)

adapter_opponent_card_3d3b = (
    TOURNAMENT_CARD_TEMPLATES[
        1
    ]
)


print("\nHISTORICAL ADAPTER TEST CARDS")
print("-" * 100)

print(
    "Player:",
    adapter_player_card_3d3b[
        "name"
    ]
)

print(
    "Opponent:",
    adapter_opponent_card_3d3b[
        "name"
    ]
)


assert (
    adapter_player_card_3d3b[
        "name"
    ]
    ==
    "Pikachu"
)

assert (
    adapter_opponent_card_3d3b[
        "name"
    ]
    ==
    "Charmander"
)


# ==========================================================================================
# 3. Build genuine Notebook 48 tournament BattleState
# ==========================================================================================

adapter_test_state_3d3b = (
    create_tournament_state(
        player_card=
            adapter_player_card_3d3b,

        opponent_card=
            adapter_opponent_card_3d3b,

        starting_side=
            "Player",

        player_energy=
            3,

        opponent_energy=
            3,
    )
)


print("\nGENUINE HISTORICAL TOURNAMENT STATE")
print("-" * 100)

print(
    "Type:",
    type(
        adapter_test_state_3d3b
    ).__name__
)

print(
    "Current player:",
    getattr(
        adapter_test_state_3d3b,
        "current_player",
        None,
    )
)

print(
    "Turn number:",
    getattr(
        adapter_test_state_3d3b,
        "turn_number",
        None,
    )
)


assert (
    type(
        adapter_test_state_3d3b
    ).__name__
    ==
    "BattleState"
)


# ==========================================================================================
# 4. Resolve production simulator legal moves
# ==========================================================================================

adapter_legal_moves_3d3b = list(
    get_current_legal_moves(
        adapter_test_state_3d3b
    )
)


adapter_legal_names_3d3b = [
    extract_move_name(
        move_3d3b
    )
    for move_3d3b
    in adapter_legal_moves_3d3b
]


print("\nSIMULATOR LEGAL MOVES")
print("-" * 100)

for index_3d3b, move_name_3d3b in enumerate(
    adapter_legal_names_3d3b,
    start=1,
):

    print(
        f"{index_3d3b:02d}. "
        f"{move_name_3d3b}"
    )


assert (
    len(
        adapter_legal_moves_3d3b
    )
    >=
    1
)


# ==========================================================================================
# 5. Execute adapter using exact historical runner interface
# ==========================================================================================

print("\nEXECUTING R3 TOURNAMENT ADAPTER")
print("-" * 100)


adapter_decision_3d3b = (
    r3_tournament_agent_3d3
    .choose_move(
        state=
            adapter_test_state_3d3b,

        depth=
            6,
    )
)


print(
    "Decision type:",
    type(
        adapter_decision_3d3b
    ).__name__
)


# ==========================================================================================
# 6. Print translated TournamentDecision
# ==========================================================================================

print("\nTOURNAMENT DECISION")
print("-" * 100)

print(
    "Move:",
    adapter_decision_3d3b.move
)

print(
    "Selected move name:",
    adapter_decision_3d3b.selected_move_name
)

print(
    "Score:",
    adapter_decision_3d3b.score
)

print(
    "Confidence:",
    adapter_decision_3d3b.confidence
)

print(
    "Search depth:",
    adapter_decision_3d3b.search_depth
)

print(
    "Nodes:",
    adapter_decision_3d3b.nodes
)

print(
    "Fallback:",
    adapter_decision_3d3b.fallback
)

print(
    "Reason:",
    adapter_decision_3d3b.reason
)


# ==========================================================================================
# 7. Underlying frozen R3 policy result
# ==========================================================================================

adapter_policy_result_3d3b = (
    r3_tournament_agent_3d3
    .last_policy_result
)


assert isinstance(
    adapter_policy_result_3d3b,
    dict,
)


print("\nUNDERLYING R3 POLICY RESULT")
print("-" * 100)


for key_3d3b, value_3d3b in (
    adapter_policy_result_3d3b.items()
):

    print(
        f"{key_3d3b}: "
        f"{value_3d3b}"
    )


# ==========================================================================================
# 8. Compare adapter output to underlying R3 output
# ==========================================================================================

policy_selected_move_3d3b = (
    adapter_policy_result_3d3b.get(
        "selected_move"
    )
)

policy_selected_name_3d3b = (
    adapter_policy_result_3d3b.get(
        "selected_move_name"
    )
)

policy_confidence_3d3b = float(
    adapter_policy_result_3d3b.get(
        "confidence",
        0.0,
    )
)

policy_fallback_3d3b = bool(
    adapter_policy_result_3d3b.get(
        "fallback",
        False,
    )
)


decision_is_legal_3d3b = (
    adapter_decision_3d3b.move
    in adapter_legal_moves_3d3b
)

same_move_object_3d3b = (
    adapter_decision_3d3b.move
    is
    policy_selected_move_3d3b
)

same_move_name_3d3b = (
    adapter_decision_3d3b
    .selected_move_name
    ==
    policy_selected_name_3d3b
)

same_confidence_3d3b = bool(
    np.isclose(
        float(
            adapter_decision_3d3b
            .confidence
        ),
        policy_confidence_3d3b,
    )
)

same_fallback_3d3b = (
    bool(
        adapter_decision_3d3b
        .fallback
    )
    ==
    policy_fallback_3d3b
)


print("\nADAPTER TRANSLATION INTEGRITY")
print("-" * 100)

print(
    "Simulator legal:",
    decision_is_legal_3d3b
)

print(
    "Same move object:",
    same_move_object_3d3b
)

print(
    "Same move name:",
    same_move_name_3d3b
)

print(
    "Same confidence:",
    same_confidence_3d3b
)

print(
    "Same fallback:",
    same_fallback_3d3b
)


# ==========================================================================================
# 9. Confirm exact historical choose_move interface remains supported
# ==========================================================================================

adapter_signature_3d3b = (
    inspect.signature(
        R3TournamentAgentAdapter
        .choose_move
    )
)


print("\nR3 ADAPTER choose_move() SIGNATURE")
print("-" * 100)

print(
    adapter_signature_3d3b
)


# ==========================================================================================
# 10. Validate model-driven vs fallback behavior
# ==========================================================================================

legal_probability_mass_3d3b = float(
    adapter_policy_result_3d3b.get(
        "legal_probability_mass",
        0.0,
    )
)


if adapter_decision_3d3b.fallback:

    model_driven_status_3d3b = (
        "FALLBACK"
    )

else:

    model_driven_status_3d3b = (
        "MODEL_DRIVEN"
    )


print("\nDECISION MODE")
print("-" * 100)

print(
    "Mode:",
    model_driven_status_3d3b
)

print(
    "Legal probability mass:",
    legal_probability_mass_3d3b
)


# ==========================================================================================
# 11. Final validation
# ==========================================================================================

section3d3b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "historical smoke cards available",

            "observed":
                [
                    adapter_player_card_3d3b[
                        "name"
                    ],
                    adapter_opponent_card_3d3b[
                        "name"
                    ],
                ],

            "expected":
                [
                    "Pikachu",
                    "Charmander",
                ],

            "passed":
                (
                    adapter_player_card_3d3b[
                        "name"
                    ]
                    ==
                    "Pikachu"
                    and
                    adapter_opponent_card_3d3b[
                        "name"
                    ]
                    ==
                    "Charmander"
                ),
        },

        {
            "validation":
                "genuine BattleState created",

            "observed":
                type(
                    adapter_test_state_3d3b
                ).__name__,

            "expected":
                "BattleState",

            "passed":
                type(
                    adapter_test_state_3d3b
                ).__name__
                ==
                "BattleState",
        },

        {
            "validation":
                "production legal moves generated",

            "observed":
                len(
                    adapter_legal_moves_3d3b
                ),

            "expected":
                ">= 1",

            "passed":
                len(
                    adapter_legal_moves_3d3b
                )
                >=
                1,
        },

        {
            "validation":
                "TournamentDecision returned",

            "observed":
                type(
                    adapter_decision_3d3b
                ).__name__,

            "expected":
                "TournamentDecision",

            "passed":
                type(
                    adapter_decision_3d3b
                ).__name__
                ==
                "TournamentDecision",
        },

        {
            "validation":
                "selected move simulator legal",

            "observed":
                decision_is_legal_3d3b,

            "expected":
                True,

            "passed":
                decision_is_legal_3d3b,
        },

        {
            "validation":
                "adapter preserves selected move",

            "observed":
                same_move_object_3d3b,

            "expected":
                True,

            "passed":
                same_move_object_3d3b,
        },

        {
            "validation":
                "adapter preserves selected move name",

            "observed":
                same_move_name_3d3b,

            "expected":
                True,

            "passed":
                same_move_name_3d3b,
        },

        {
            "validation":
                "adapter preserves confidence",

            "observed":
                same_confidence_3d3b,

            "expected":
                True,

            "passed":
                same_confidence_3d3b,
        },

        {
            "validation":
                "adapter preserves fallback flag",

            "observed":
                same_fallback_3d3b,

            "expected":
                True,

            "passed":
                same_fallback_3d3b,
        },

        {
            "validation":
                "search depth propagated",

            "observed":
                adapter_decision_3d3b
                .search_depth,

            "expected":
                6,

            "passed":
                adapter_decision_3d3b
                .search_depth
                ==
                6,
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_tournament_agent_3d3
                    .r3_policy_engine
                    .model
                    .n_features_in_
                )
                ==
                46,
        },
    ]
)


print("\nSECTION 3D.3B VALIDATION")
print("-" * 100)

display(
    section3d3b_validation_df
)


assert (
    section3d3b_validation_df[
        "passed"
    ].all()
), (
    "Section 3D.3B adapter validation failed. "
    "Do not run tournament smoke matches."
)


print("\n" + "=" * 100)

print("✅ EXACT HISTORICAL PIKACHU / CHARMANDER STATE CREATED")
print("✅ PRODUCTION LEGAL MOVE RESOLVER USED")
print("✅ R3 TOURNAMENT ADAPTER choose_move() EXECUTED")
print("✅ TournamentDecision RETURNED")
print("✅ SELECTED MOVE IS SIMULATOR LEGAL")
print("✅ ADAPTER PRESERVES FROZEN R3 DECISION")
print("✅ CONFIDENCE AND FALLBACK PRESERVED")
print("✅ SEARCH DEPTH PROPAGATED")
print("✅ FROZEN 46-FEATURE MODEL REMAINS UNCHANGED")
print("✅ SECTION 3D.3B COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NO FULL TOURNAMENT MATCH EXECUTED YET")
print("⚠️ DO NOT RUN 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 3D.3B — RESUME R3 TOURNAMENT ADAPTER VALIDATION
====================================================================================================

HISTORICAL ADAPTER TEST CARDS
----------------------------------------------------------------------------------------------------
Player: Pikachu
Opponent: Charmander

GENUINE HISTORICAL TOURNAMENT STATE
----------------------------------------------------------------------------------------------------
Type: BattleState
Current player: Player
Turn number: 1

SIMULATOR LEGAL MOVES
----------------------------------------------------------------------------------------------------
01. Quick Attack
02. Thunderbolt

EXECUTING R3 TOURNAMENT ADAPTER
----------------------------------------------------------------------------------------------------
Decision type: TournamentDecision

TOURNAMENT DECISION
----------------------------------------------------------------------------------------------------
Move: {'name': 'Quick Attack', 'damage': 30.0, 'energy_cost': 1, 'effect': None}
Selected move name: Quick Attack
Score: 1.0
Confidence: 1.0
Search depth: 6
Nodes: 0
Fallback: False
Reason: Frozen R3 model-driven legal decision.

UNDERLYING R3 POLICY RESULT
----------------------------------------------------------------------------------------------------
selected_index: 0
selected_move: {'name': 'Quick Attack', 'damage': 30.0, 'energy_cost': 1, 'effect': None}
selected_move_name: Quick Attack
confidence: 1.0
probabilities: [1.0, 0.0]
logits: [0.0, -27.631021115928547]
move_names: ['Quick Attack', 'Thunderbolt']
checkpoint_epoch: 0
fallback: False
policy_name: R3_STATE_CENTRIC_POLICY
full_class_names: ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
full_class_probabilities: [0.092, 0.026, 0.038, 0.12, 0.724, 0.0]
legal_probability_mass: 0.724

ADAPTER TRANSLATION INTEGRITY
----------------------------------------------------------------------------------------------------
Simulator legal: True
Same move object: True
Same move name: True
Same confidence: True
Same fallback: True

R3 ADAPTER choose_move() SIGNATURE
----------------------------------------------------------------------------------------------------
(self, state: Any = None, depth: int | None = None, battle_state: Any = None, **kwargs: Any) -> notebook48_historical_benchmark_recovery.TournamentDecision

DECISION MODE
----------------------------------------------------------------------------------------------------
Mode: MODEL_DRIVEN
Legal probability mass: 0.724

SECTION 3D.3B VALIDATION
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

,validation,observed,expected,passed
0,historical smoke cards available,"[Pikachu, Charmander]","[Pikachu, Charmander]",True
1,genuine BattleState created,BattleState,BattleState,True
2,production legal moves generated,2,>= 1,True
3,TournamentDecision returned,TournamentDecision,TournamentDecision,True
4,selected move simulator legal,True,True,True
5,adapter preserves selected move,True,True,True
6,adapter preserves selected move name,True,True,True
7,adapter preserves confidence,True,True,True
8,adapter preserves fallback flag,True,True,True
9,search depth propagated,6,6,True
10,frozen R3 remains 46 features,46,46,True

====================================================================================================
✅ EXACT HISTORICAL PIKACHU / CHARMANDER STATE CREATED
✅ PRODUCTION LEGAL MOVE RESOLVER USED
✅ R3 TOURNAMENT ADAPTER choose_move() EXECUTED
✅ TournamentDecision RETURNED
✅ SELECTED MOVE IS SIMULATOR LEGAL
✅ ADAPTER PRESERVES FROZEN R3 DECISION
✅ CONFIDENCE AND FALLBACK PRESERVED
✅ SEARCH DEPTH PROPAGATED
✅ FROZEN 46-FEATURE MODEL REMAINS UNCHANGED
✅ SECTION 3D.3B COMPLETE
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ NO FULL TOURNAMENT MATCH EXECUTED YET
⚠️ DO NOT RUN 300-MATCH BENCHMARK YET
====================================================================================================

In [54]:
# ==========================================================================================
# SECTION 4A — RECOVER EXACT NOTEBOOK 48 BALANCED TOURNAMENT SCHEDULE BUILDER
# ==========================================================================================

print("=" * 100)
print("SECTION 4A — RECOVER EXACT NOTEBOOK 48 BALANCED TOURNAMENT SCHEDULE BUILDER")
print("=" * 100)

from pathlib import Path
import ast
import inspect
import pandas as pd


# ==========================================================================================
# 1. Historical benchmark lock
# ==========================================================================================

HISTORICAL_BASELINES_4A = [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]

HISTORICAL_MATCHES_PER_BASELINE_4A = 100
HISTORICAL_TOTAL_MATCHES_4A = 300
HISTORICAL_MATCHES_PER_SIDE_PER_BASELINE_4A = 50


print("\nHISTORICAL BENCHMARK TARGET")
print("-" * 100)

print(
    "Baselines                :",
    HISTORICAL_BASELINES_4A
)

print(
    "Matches per baseline     :",
    HISTORICAL_MATCHES_PER_BASELINE_4A
)

print(
    "Matches per side/baseline:",
    HISTORICAL_MATCHES_PER_SIDE_PER_BASELINE_4A
)

print(
    "Total matches            :",
    HISTORICAL_TOTAL_MATCHES_4A
)


# ==========================================================================================
# 2. Search current globals and recovered Notebook 48 namespaces first
# ==========================================================================================

target_function_4a = (
    "build_balanced_schedule"
)


schedule_builder_candidates_4a = []


# Current globals
if callable(
    globals().get(
        target_function_4a
    )
):

    schedule_builder_candidates_4a.append(
        {
            "location":
                "globals",

            "available":
                True,

            "object_type":
                type(
                    globals()[
                        target_function_4a
                    ]
                ).__name__,
        }
    )


# Historical namespaces already recovered earlier
for namespace_name_4a in [
    "historical_ns_2e",
    "objects_2d",
    "top_level_nodes_2e",
]:

    namespace_4a = globals().get(
        namespace_name_4a,
        None,
    )

    if not isinstance(
        namespace_4a,
        dict,
    ):
        continue

    candidate_4a = namespace_4a.get(
        target_function_4a
    )

    schedule_builder_candidates_4a.append(
        {
            "location":
                namespace_name_4a,

            "available":
                callable(
                    candidate_4a
                ),

            "object_type":
                (
                    type(
                        candidate_4a
                    ).__name__
                    if candidate_4a
                    is not None
                    else
                    None
                ),
        }
    )


section4a_namespace_search_df = pd.DataFrame(
    schedule_builder_candidates_4a
)


print("\nEXISTING SCHEDULE BUILDER SEARCH")
print("-" * 100)

display(
    section4a_namespace_search_df
)


# ==========================================================================================
# 3. Bind existing exact historical function if available
# ==========================================================================================

build_balanced_schedule_4a = None
schedule_builder_source_4a = None


if callable(
    globals().get(
        target_function_4a
    )
):

    build_balanced_schedule_4a = (
        globals()[
            target_function_4a
        ]
    )

    schedule_builder_source_4a = (
        "existing global binding"
    )


if build_balanced_schedule_4a is None:

    for namespace_name_4a in [
        "historical_ns_2e",
        "objects_2d",
        "top_level_nodes_2e",
    ]:

        namespace_4a = globals().get(
            namespace_name_4a,
            None,
        )

        if not isinstance(
            namespace_4a,
            dict,
        ):
            continue

        candidate_4a = namespace_4a.get(
            target_function_4a
        )

        if callable(
            candidate_4a
        ):

            build_balanced_schedule_4a = (
                candidate_4a
            )

            schedule_builder_source_4a = (
                f"existing namespace: "
                f"{namespace_name_4a}"
            )

            break


# ==========================================================================================
# 4. If function is not currently loaded, inspect authoritative Notebook 48 source
# ==========================================================================================

PROJECT_ROOT_4A = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

NOTEBOOK48_SCRIPT_4A = (
    PROJECT_ROOT_4A
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py"
)


assert (
    NOTEBOOK48_SCRIPT_4A.exists()
)


source_text_4a = (
    NOTEBOOK48_SCRIPT_4A
    .read_text(
        encoding="utf-8"
    )
)


source_tree_4a = ast.parse(
    source_text_4a
)


schedule_function_node_4a = None


for node_4a in (
    source_tree_4a.body
):

    if (
        isinstance(
            node_4a,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        )
        and
        node_4a.name
        ==
        target_function_4a
    ):

        schedule_function_node_4a = (
            node_4a
        )

        break


print("\nAUTHORITATIVE SCHEDULE BUILDER SOURCE")
print("-" * 100)


assert (
    schedule_function_node_4a
    is not None
), (
    "build_balanced_schedule() was not found "
    "in Notebook 48 authoritative script."
)


schedule_function_source_4a = (
    ast.get_source_segment(
        source_text_4a,
        schedule_function_node_4a,
    )
)


print(
    schedule_function_source_4a
)


# ==========================================================================================
# 5. Inspect exact signature and external dependencies
# ==========================================================================================

schedule_function_tree_4a = ast.Module(
    body=[
        schedule_function_node_4a
    ],
    type_ignores=[],
)


defined_local_names_4a = {
    argument_4a.arg
    for argument_4a
    in (
        schedule_function_node_4a.args.args
        +
        schedule_function_node_4a.args.kwonlyargs
    )
}


defined_local_names_4a.update(
    {
        node_4a.id
        for node_4a
        in ast.walk(
            schedule_function_node_4a
        )
        if isinstance(
            node_4a,
            ast.Store,
        )
    }
)


referenced_names_4a = {
    node_4a.id
    for node_4a
    in ast.walk(
        schedule_function_node_4a
    )
    if isinstance(
        node_4a,
        ast.Name,
    )
    and isinstance(
        node_4a.ctx,
        ast.Load,
    )
}


builtin_names_4a = set(
    dir(
        __builtins__
    )
)


external_dependencies_4a = sorted(
    referenced_names_4a
    -
    defined_local_names_4a
    -
    builtin_names_4a
)


print("\nSCHEDULE BUILDER EXTERNAL DEPENDENCIES")
print("-" * 100)

for dependency_4a in (
    external_dependencies_4a
):

    print(
        "-",
        dependency_4a
    )


# ==========================================================================================
# 6. Recover needed dependencies from current namespace / historical namespace
# ==========================================================================================

schedule_exec_namespace_4a = {
    "__builtins__":
        __builtins__,
}


dependency_rows_4a = []


for dependency_4a in (
    external_dependencies_4a
):

    recovered_object_4a = None
    recovered_from_4a = None


    # Current globals
    if dependency_4a in globals():

        recovered_object_4a = (
            globals()[
                dependency_4a
            ]
        )

        recovered_from_4a = (
            "globals"
        )


    # Existing historical recovery namespace
    if recovered_object_4a is None:

        historical_namespace_4a = globals().get(
            "historical_ns_2e",
            {}
        )

        if (
            isinstance(
                historical_namespace_4a,
                dict,
            )
            and
            dependency_4a
            in historical_namespace_4a
        ):

            recovered_object_4a = (
                historical_namespace_4a[
                    dependency_4a
                ]
            )

            recovered_from_4a = (
                "historical_ns_2e"
            )


    if recovered_object_4a is not None:

        schedule_exec_namespace_4a[
            dependency_4a
        ] = recovered_object_4a


    dependency_rows_4a.append(
        {
            "dependency":
                dependency_4a,

            "available":
                recovered_object_4a
                is not None,

            "source":
                recovered_from_4a,

            "object_type":
                (
                    type(
                        recovered_object_4a
                    ).__name__
                    if recovered_object_4a
                    is not None
                    else
                    "MISSING"
                ),
        }
    )


section4a_dependency_df = pd.DataFrame(
    dependency_rows_4a
)


print("\nSCHEDULE BUILDER DEPENDENCY STATUS")
print("-" * 100)

display(
    section4a_dependency_df
)


# ==========================================================================================
# 7. If exact function was not already loaded, execute ONLY its function definition
#
# This does not execute Notebook 48.
# ==========================================================================================

if build_balanced_schedule_4a is None:

    unresolved_dependencies_4a = (
        section4a_dependency_df.loc[
            ~section4a_dependency_df[
                "available"
            ],
            "dependency",
        ]
        .tolist()
    )


    assert (
        len(
            unresolved_dependencies_4a
        )
        ==
        0
    ), (
        "Schedule builder has unresolved dependencies: "
        f"{unresolved_dependencies_4a}"
    )


    compiled_schedule_function_4a = compile(
        schedule_function_tree_4a,
        filename=str(
            NOTEBOOK48_SCRIPT_4A
        ),
        mode="exec",
    )


    exec(
        compiled_schedule_function_4a,
        schedule_exec_namespace_4a,
    )


    build_balanced_schedule_4a = (
        schedule_exec_namespace_4a[
            target_function_4a
        ]
    )


    schedule_builder_source_4a = (
        "authoritative Notebook 48 "
        "function definition"
    )


assert callable(
    build_balanced_schedule_4a
)


print("\nRECOVERED SCHEDULE BUILDER")
print("-" * 100)

print(
    "Source:",
    schedule_builder_source_4a
)

print(
    "Signature:",
    inspect.signature(
        build_balanced_schedule_4a
    )
)


# ==========================================================================================
# 8. Build schedule exactly as Notebook 48 did
#
# IMPORTANT:
# This constructs schedule rows only.
# It does NOT run any matches.
# ==========================================================================================

full_schedule_4a = []


for baseline_name_4a in (
    HISTORICAL_BASELINES_4A
):

    baseline_schedule_4a = (
        build_balanced_schedule_4a(
            baseline_name=
                baseline_name_4a,

            match_count=
                HISTORICAL_MATCHES_PER_BASELINE_4A,
        )
    )


    full_schedule_4a.extend(
        baseline_schedule_4a
    )


print("\nSCHEDULE CONSTRUCTION COMPLETE")
print("-" * 100)

print(
    "Total rows:",
    len(
        full_schedule_4a
    )
)


# ==========================================================================================
# 9. Convert schedule to inspection dataframe
# ==========================================================================================

schedule_rows_4a = []


for schedule_index_4a, match_4a in enumerate(
    full_schedule_4a,
    start=1,
):

    schedule_rows_4a.append(
        {
            "match_id":
                schedule_index_4a,

            "baseline_name":
                match_4a.get(
                    "baseline_name"
                ),

            "player_card":
                (
                    match_4a.get(
                        "player_card",
                        {}
                    ).get(
                        "name"
                    )
                    if isinstance(
                        match_4a.get(
                            "player_card"
                        ),
                        dict,
                    )
                    else
                    str(
                        match_4a.get(
                            "player_card"
                        )
                    )
                ),

            "opponent_card":
                (
                    match_4a.get(
                        "opponent_card",
                        {}
                    ).get(
                        "name"
                    )
                    if isinstance(
                        match_4a.get(
                            "opponent_card"
                        ),
                        dict,
                    )
                    else
                    str(
                        match_4a.get(
                            "opponent_card"
                        )
                    )
                ),

            "starting_side":
                match_4a.get(
                    "starting_side"
                ),

            "evaluated_agent_side":
                match_4a.get(
                    "evaluated_agent_side"
                ),
        }
    )


section4a_schedule_df = pd.DataFrame(
    schedule_rows_4a
)


print("\nFIRST 20 SCHEDULE ROWS")
print("-" * 100)

display(
    section4a_schedule_df.head(
        20
    )
)


# ==========================================================================================
# 10. Baseline distribution
# ==========================================================================================

section4a_baseline_counts_df = (
    section4a_schedule_df
    .groupby(
        "baseline_name",
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nMATCHES PER BASELINE")
print("-" * 100)

display(
    section4a_baseline_counts_df
)


# ==========================================================================================
# 11. Evaluated-agent side distribution
# ==========================================================================================

section4a_side_counts_df = (
    section4a_schedule_df
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nSIDE BALANCE PER BASELINE")
print("-" * 100)

display(
    section4a_side_counts_df
)


# ==========================================================================================
# 12. Starting-side distribution
# ==========================================================================================

section4a_start_counts_df = (
    section4a_schedule_df
    .groupby(
        [
            "baseline_name",
            "starting_side",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nSTARTING-SIDE DISTRIBUTION")
print("-" * 100)

display(
    section4a_start_counts_df
)


# ==========================================================================================
# 13. Card matchup coverage
# ==========================================================================================

section4a_matchup_counts_df = (
    section4a_schedule_df
    .groupby(
        [
            "player_card",
            "opponent_card",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
    .sort_values(
        [
            "player_card",
            "opponent_card",
        ]
    )
    .reset_index(
        drop=True
    )
)


print("\nCARD MATCHUP COVERAGE")
print("-" * 100)

display(
    section4a_matchup_counts_df
)


# ==========================================================================================
# 14. Structural integrity checks
# ==========================================================================================

required_schedule_columns_4a = [
    "baseline_name",
    "player_card",
    "opponent_card",
    "starting_side",
    "evaluated_agent_side",
]


missing_schedule_columns_4a = [
    column_4a
    for column_4a
    in required_schedule_columns_4a
    if column_4a
    not in section4a_schedule_df.columns
]


null_required_cells_4a = int(
    section4a_schedule_df[
        required_schedule_columns_4a
    ]
    .isna()
    .sum()
    .sum()
)


baseline_counts_4a = dict(
    zip(
        section4a_baseline_counts_df[
            "baseline_name"
        ],
        section4a_baseline_counts_df[
            "matches"
        ],
    )
)


side_counts_lookup_4a = {
    (
        row_4a[
            "baseline_name"
        ],
        row_4a[
            "evaluated_agent_side"
        ],
    ):
        int(
            row_4a[
                "matches"
            ]
        )

    for _, row_4a
    in section4a_side_counts_df.iterrows()
}


all_baselines_100_4a = all(
    baseline_counts_4a.get(
        baseline_name_4a,
        0,
    )
    ==
    100

    for baseline_name_4a
    in HISTORICAL_BASELINES_4A
)


all_baselines_50_50_4a = all(

    side_counts_lookup_4a.get(
        (
            baseline_name_4a,
            "Player",
        ),
        0,
    )
    ==
    50

    and

    side_counts_lookup_4a.get(
        (
            baseline_name_4a,
            "Opponent",
        ),
        0,
    )
    ==
    50

    for baseline_name_4a
    in HISTORICAL_BASELINES_4A
)


# ==========================================================================================
# 15. Section 4A validation
# ==========================================================================================

section4a_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exact historical schedule builder recovered",

            "observed":
                callable(
                    build_balanced_schedule_4a
                ),

            "expected":
                True,

            "passed":
                callable(
                    build_balanced_schedule_4a
                ),
        },

        {
            "validation":
                "three baseline labels preserved",

            "observed":
                sorted(
                    section4a_schedule_df[
                        "baseline_name"
                    ]
                    .dropna()
                    .unique()
                    .tolist()
                ),

            "expected":
                sorted(
                    HISTORICAL_BASELINES_4A
                ),

            "passed":
                sorted(
                    section4a_schedule_df[
                        "baseline_name"
                    ]
                    .dropna()
                    .unique()
                    .tolist()
                )
                ==
                sorted(
                    HISTORICAL_BASELINES_4A
                ),
        },

        {
            "validation":
                "exactly 300 matches scheduled",

            "observed":
                len(
                    section4a_schedule_df
                ),

            "expected":
                300,

            "passed":
                len(
                    section4a_schedule_df
                )
                ==
                300,
        },

        {
            "validation":
                "100 matches per baseline",

            "observed":
                baseline_counts_4a,

            "expected":
                100,

            "passed":
                all_baselines_100_4a,
        },

        {
            "validation":
                "50/50 evaluated-side split per baseline",

            "observed":
                side_counts_lookup_4a,

            "expected":
                "50 Player + 50 Opponent per baseline",

            "passed":
                all_baselines_50_50_4a,
        },

        {
            "validation":
                "all required schedule fields present",

            "observed":
                missing_schedule_columns_4a,

            "expected":
                [],

            "passed":
                len(
                    missing_schedule_columns_4a
                )
                ==
                0,
        },

        {
            "validation":
                "no null required schedule values",

            "observed":
                null_required_cells_4a,

            "expected":
                0,

            "passed":
                null_required_cells_4a
                ==
                0,
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                )
                ==
                46,
        },
    ]
)


print("\nSECTION 4A VALIDATION")
print("-" * 100)

display(
    section4a_validation_df
)


assert (
    section4a_validation_df[
        "passed"
    ].all()
), (
    "Section 4A schedule reconstruction failed. "
    "Do not start the 300-match benchmark."
)


# ==========================================================================================
# 16. Conclusion
# ==========================================================================================

print("\n" + "=" * 100)

print("✅ EXACT NOTEBOOK 48 BALANCED SCHEDULE BUILDER RECOVERED")
print("✅ THREE HISTORICAL BASELINES PRESERVED")
print("✅ 100 MATCHES PER BASELINE")
print("✅ 50 PLAYER + 50 OPPONENT EVALUATIONS PER BASELINE")
print("✅ EXACTLY 300 MATCHES SCHEDULED")
print("✅ REQUIRED MATCH FIELDS PRESENT")
print("✅ CARD MATCHUP COVERAGE INSPECTED")
print("✅ FROZEN R3 MODEL REMAINS UNCHANGED")
print("✅ SECTION 4A COMPLETE")
print("⚠️ SCHEDULE CONSTRUCTION ONLY")
print("⚠️ ZERO OF THE 300 BENCHMARK MATCHES HAVE BEEN RUN")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT EXECUTE THE 300-MATCH BENCHMARK UNTIL WE REVIEW THIS SCHEDULE")

print("=" * 100)

====================================================================================================
SECTION 4A — RECOVER EXACT NOTEBOOK 48 BALANCED TOURNAMENT SCHEDULE BUILDER
====================================================================================================

HISTORICAL BENCHMARK TARGET
----------------------------------------------------------------------------------------------------
Baselines                : ['Random Baseline', 'Greedy Damage Baseline', 'Depth-6 Search Baseline']
Matches per baseline     : 100
Matches per side/baseline: 50
Total matches            : 300

EXISTING SCHEDULE BUILDER SEARCH
----------------------------------------------------------------------------------------------------

             location  available  object_type
0    historical_ns_2e      False          NaN
1          objects_2d      False          NaN
2  top_level_nodes_2e      False  FunctionDef

SyntaxError: invalid non-printable character U+FEFF (<unknown>, line 1)

In [55]:
# ==========================================================================================
# SECTION 4A.1 — REPAIR UTF-8 BOM AND COMPLETE HISTORICAL SCHEDULE RECOVERY
# ==========================================================================================

print("=" * 100)
print("SECTION 4A.1 — REPAIR UTF-8 BOM AND COMPLETE HISTORICAL SCHEDULE RECOVERY")
print("=" * 100)

from pathlib import Path
import ast
import inspect
import pandas as pd


# ==========================================================================================
# 1. Historical benchmark lock
# ==========================================================================================

HISTORICAL_BASELINES_4A1 = [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]

HISTORICAL_MATCHES_PER_BASELINE_4A1 = 100
HISTORICAL_TOTAL_MATCHES_4A1 = 300
HISTORICAL_MATCHES_PER_SIDE_PER_BASELINE_4A1 = 50


print("\nHISTORICAL BENCHMARK TARGET")
print("-" * 100)

print(
    "Baselines                :",
    HISTORICAL_BASELINES_4A1
)

print(
    "Matches per baseline     :",
    HISTORICAL_MATCHES_PER_BASELINE_4A1
)

print(
    "Matches per side/baseline:",
    HISTORICAL_MATCHES_PER_SIDE_PER_BASELINE_4A1
)

print(
    "Total matches            :",
    HISTORICAL_TOTAL_MATCHES_4A1
)


# ==========================================================================================
# 2. Authoritative Notebook 48 script
#
# IMPORTANT FIX:
# utf-8-sig automatically removes an initial U+FEFF BOM.
# ==========================================================================================

PROJECT_ROOT_4A1 = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

NOTEBOOK48_SCRIPT_4A1 = (
    PROJECT_ROOT_4A1
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py"
)


assert (
    NOTEBOOK48_SCRIPT_4A1.exists()
), (
    "Notebook 48 authoritative script was not found."
)


print("\nAUTHORITATIVE NOTEBOOK 48 SCRIPT")
print("-" * 100)

print(
    NOTEBOOK48_SCRIPT_4A1
)


source_text_4a1 = (
    NOTEBOOK48_SCRIPT_4A1
    .read_text(
        encoding="utf-8-sig"
    )
)


print("\nSOURCE ENCODING CHECK")
print("-" * 100)

print(
    "First character repr:",
    repr(
        source_text_4a1[
            :1
        ]
    )
)

print(
    "Starts with BOM:",
    source_text_4a1.startswith(
        "\ufeff"
    )
)


assert not (
    source_text_4a1.startswith(
        "\ufeff"
    )
), (
    "UTF-8 BOM was not removed."
)


# ==========================================================================================
# 3. Parse corrected source
# ==========================================================================================

source_tree_4a1 = ast.parse(
    source_text_4a1,
    filename=str(
        NOTEBOOK48_SCRIPT_4A1
    ),
)


print("\nAST PARSE STATUS")
print("-" * 100)

print(
    "Parsed successfully:",
    True
)

print(
    "Top-level nodes:",
    len(
        source_tree_4a1.body
    )
)


# ==========================================================================================
# 4. Locate exact build_balanced_schedule()
# ==========================================================================================

target_function_4a1 = (
    "build_balanced_schedule"
)

schedule_function_node_4a1 = None


for node_4a1 in (
    source_tree_4a1.body
):

    if (
        isinstance(
            node_4a1,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
            ),
        )
        and
        node_4a1.name
        ==
        target_function_4a1
    ):

        schedule_function_node_4a1 = (
            node_4a1
        )

        break


assert (
    schedule_function_node_4a1
    is not None
), (
    "Exact build_balanced_schedule() "
    "definition not found in Notebook 48."
)


schedule_function_source_4a1 = (
    ast.get_source_segment(
        source_text_4a1,
        schedule_function_node_4a1,
    )
)


print("\nEXACT NOTEBOOK 48 SCHEDULE BUILDER")
print("-" * 100)

print(
    "Function:",
    schedule_function_node_4a1.name
)

print(
    "Start line:",
    schedule_function_node_4a1.lineno
)

print(
    "End line:",
    schedule_function_node_4a1.end_lineno
)

print("\nSOURCE")
print("-" * 100)

print(
    schedule_function_source_4a1
)


# ==========================================================================================
# 5. Inspect true external/global dependencies
# ==========================================================================================

argument_names_4a1 = {
    argument_4a1.arg

    for argument_4a1
    in (
        list(
            schedule_function_node_4a1.args.args
        )
        +
        list(
            schedule_function_node_4a1.args.kwonlyargs
        )
    )
}


local_store_names_4a1 = {
    node_4a1.id

    for node_4a1
    in ast.walk(
        schedule_function_node_4a1
    )

    if (
        isinstance(
            node_4a1,
            ast.Name,
        )
        and
        isinstance(
            node_4a1.ctx,
            ast.Store,
        )
    )
}


loaded_names_4a1 = {
    node_4a1.id

    for node_4a1
    in ast.walk(
        schedule_function_node_4a1
    )

    if (
        isinstance(
            node_4a1,
            ast.Name,
        )
        and
        isinstance(
            node_4a1.ctx,
            ast.Load,
        )
    )
}


builtin_names_4a1 = set(
    dir(
        __builtins__
    )
)


external_dependencies_4a1 = sorted(
    loaded_names_4a1
    -
    argument_names_4a1
    -
    local_store_names_4a1
    -
    builtin_names_4a1
)


print("\nTRUE SCHEDULE BUILDER EXTERNAL DEPENDENCIES")
print("-" * 100)

for dependency_4a1 in (
    external_dependencies_4a1
):

    print(
        "-",
        dependency_4a1
    )


# ==========================================================================================
# 6. Resolve dependencies from current Notebook 60 state
# ==========================================================================================

schedule_namespace_4a1 = {
    "__builtins__":
        __builtins__,
}


dependency_rows_4a1 = []


for dependency_4a1 in (
    external_dependencies_4a1
):

    recovered_object_4a1 = None
    recovered_source_4a1 = None


    # ------------------------------------------------------------------
    # Current notebook globals
    # ------------------------------------------------------------------

    if dependency_4a1 in globals():

        recovered_object_4a1 = (
            globals()[
                dependency_4a1
            ]
        )

        recovered_source_4a1 = (
            "globals"
        )


    # ------------------------------------------------------------------
    # Existing historical namespace
    # ------------------------------------------------------------------

    if recovered_object_4a1 is None:

        historical_namespace_4a1 = (
            globals().get(
                "historical_ns_2e",
                {},
            )
        )


        if (
            isinstance(
                historical_namespace_4a1,
                dict,
            )
            and
            dependency_4a1
            in historical_namespace_4a1
        ):

            recovered_object_4a1 = (
                historical_namespace_4a1[
                    dependency_4a1
                ]
            )

            recovered_source_4a1 = (
                "historical_ns_2e"
            )


    # ------------------------------------------------------------------
    # Known tournament templates already recovered in 3D.3A
    # ------------------------------------------------------------------

    if (
        recovered_object_4a1 is None
        and
        dependency_4a1
        ==
        "TOURNAMENT_CARD_TEMPLATES"
        and
        "TOURNAMENT_CARD_TEMPLATES"
        in globals()
    ):

        recovered_object_4a1 = (
            TOURNAMENT_CARD_TEMPLATES
        )

        recovered_source_4a1 = (
            "Section 3D.3A"
        )


    if recovered_object_4a1 is not None:

        schedule_namespace_4a1[
            dependency_4a1
        ] = recovered_object_4a1


    dependency_rows_4a1.append(
        {
            "dependency":
                dependency_4a1,

            "available":
                recovered_object_4a1
                is not None,

            "source":
                recovered_source_4a1,

            "object_type":
                (
                    type(
                        recovered_object_4a1
                    ).__name__
                    if recovered_object_4a1
                    is not None
                    else
                    "MISSING"
                ),
        }
    )


section4a1_dependency_df = (
    pd.DataFrame(
        dependency_rows_4a1
    )
)


print("\nSCHEDULE BUILDER DEPENDENCY STATUS")
print("-" * 100)

display(
    section4a1_dependency_df
)


missing_dependencies_4a1 = (
    section4a1_dependency_df.loc[
        ~section4a1_dependency_df[
            "available"
        ],
        "dependency",
    ]
    .tolist()
)


assert (
    len(
        missing_dependencies_4a1
    )
    ==
    0
), (
    "Exact schedule builder still has unresolved "
    f"dependencies: {missing_dependencies_4a1}"
)


# ==========================================================================================
# 7. Compile ONLY exact build_balanced_schedule() definition
#
# Notebook 48 itself is NOT executed.
# ==========================================================================================

schedule_function_module_4a1 = ast.Module(
    body=[
        schedule_function_node_4a1
    ],
    type_ignores=[],
)


compiled_schedule_function_4a1 = compile(
    schedule_function_module_4a1,
    filename=str(
        NOTEBOOK48_SCRIPT_4A1
    ),
    mode="exec",
)


exec(
    compiled_schedule_function_4a1,
    schedule_namespace_4a1,
)


build_balanced_schedule_4a1 = (
    schedule_namespace_4a1[
        target_function_4a1
    ]
)


assert callable(
    build_balanced_schedule_4a1
)


print("\nRECOVERED SCHEDULE BUILDER")
print("-" * 100)

print(
    "Callable:",
    callable(
        build_balanced_schedule_4a1
    )
)

print(
    "Signature:",
    inspect.signature(
        build_balanced_schedule_4a1
    )
)


# ==========================================================================================
# 8. Construct exact 300-row schedule
#
# ZERO matches are executed here.
# ==========================================================================================

full_schedule_4a1 = []


for baseline_name_4a1 in (
    HISTORICAL_BASELINES_4A1
):

    baseline_schedule_4a1 = (
        build_balanced_schedule_4a1(
            baseline_name=
                baseline_name_4a1,

            match_count=
                HISTORICAL_MATCHES_PER_BASELINE_4A1,
        )
    )


    full_schedule_4a1.extend(
        baseline_schedule_4a1
    )


print("\nSCHEDULE CONSTRUCTION")
print("-" * 100)

print(
    "Total schedule rows:",
    len(
        full_schedule_4a1
    )
)


# ==========================================================================================
# 9. Build inspection dataframe
# ==========================================================================================

schedule_rows_4a1 = []


for match_id_4a1, scheduled_match_4a1 in enumerate(
    full_schedule_4a1,
    start=1,
):

    player_card_object_4a1 = (
        scheduled_match_4a1.get(
            "player_card"
        )
    )

    opponent_card_object_4a1 = (
        scheduled_match_4a1.get(
            "opponent_card"
        )
    )


    schedule_rows_4a1.append(
        {
            "match_id":
                match_id_4a1,

            "baseline_name":
                scheduled_match_4a1.get(
                    "baseline_name"
                ),

            "player_card":
                (
                    player_card_object_4a1.get(
                        "name"
                    )
                    if isinstance(
                        player_card_object_4a1,
                        dict,
                    )
                    else
                    str(
                        player_card_object_4a1
                    )
                ),

            "opponent_card":
                (
                    opponent_card_object_4a1.get(
                        "name"
                    )
                    if isinstance(
                        opponent_card_object_4a1,
                        dict,
                    )
                    else
                    str(
                        opponent_card_object_4a1
                    )
                ),

            "starting_side":
                scheduled_match_4a1.get(
                    "starting_side"
                ),

            "evaluated_agent_side":
                scheduled_match_4a1.get(
                    "evaluated_agent_side"
                ),
        }
    )


section4a1_schedule_df = (
    pd.DataFrame(
        schedule_rows_4a1
    )
)


print("\nFIRST 20 SCHEDULE ROWS")
print("-" * 100)

display(
    section4a1_schedule_df.head(
        20
    )
)


# ==========================================================================================
# 10. Matches per baseline
# ==========================================================================================

section4a1_baseline_counts_df = (
    section4a1_schedule_df
    .groupby(
        "baseline_name",
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nMATCHES PER BASELINE")
print("-" * 100)

display(
    section4a1_baseline_counts_df
)


# ==========================================================================================
# 11. Evaluated-agent side distribution
# ==========================================================================================

section4a1_side_counts_df = (
    section4a1_schedule_df
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nEVALUATED-AGENT SIDE DISTRIBUTION")
print("-" * 100)

display(
    section4a1_side_counts_df
)


# ==========================================================================================
# 12. Starting-side distribution
# ==========================================================================================

section4a1_starting_side_df = (
    section4a1_schedule_df
    .groupby(
        [
            "baseline_name",
            "starting_side",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nSTARTING-SIDE DISTRIBUTION")
print("-" * 100)

display(
    section4a1_starting_side_df
)


# ==========================================================================================
# 13. Matchup coverage
# ==========================================================================================

section4a1_matchup_df = (
    section4a1_schedule_df
    .groupby(
        [
            "player_card",
            "opponent_card",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
    .sort_values(
        [
            "player_card",
            "opponent_card",
        ]
    )
    .reset_index(
        drop=True
    )
)


print("\nCARD MATCHUP COVERAGE")
print("-" * 100)

display(
    section4a1_matchup_df
)


# ==========================================================================================
# 14. Structural counts
# ==========================================================================================

baseline_count_lookup_4a1 = dict(
    zip(
        section4a1_baseline_counts_df[
            "baseline_name"
        ],
        section4a1_baseline_counts_df[
            "matches"
        ],
    )
)


side_count_lookup_4a1 = {
    (
        row_4a1[
            "baseline_name"
        ],
        row_4a1[
            "evaluated_agent_side"
        ],
    ):
        int(
            row_4a1[
                "matches"
            ]
        )

    for _, row_4a1
    in section4a1_side_counts_df.iterrows()
}


exact_100_each_4a1 = all(
    baseline_count_lookup_4a1.get(
        baseline_name_4a1,
        0,
    )
    ==
    100

    for baseline_name_4a1
    in HISTORICAL_BASELINES_4A1
)


exact_50_50_each_4a1 = all(
    (
        side_count_lookup_4a1.get(
            (
                baseline_name_4a1,
                "Player",
            ),
            0,
        )
        ==
        50
    )
    and
    (
        side_count_lookup_4a1.get(
            (
                baseline_name_4a1,
                "Opponent",
            ),
            0,
        )
        ==
        50
    )

    for baseline_name_4a1
    in HISTORICAL_BASELINES_4A1
)


required_columns_4a1 = [
    "baseline_name",
    "player_card",
    "opponent_card",
    "starting_side",
    "evaluated_agent_side",
]


missing_columns_4a1 = [
    column_4a1
    for column_4a1
    in required_columns_4a1
    if column_4a1
    not in section4a1_schedule_df.columns
]


null_required_values_4a1 = int(
    section4a1_schedule_df[
        required_columns_4a1
    ]
    .isna()
    .sum()
    .sum()
)


# ==========================================================================================
# 15. Final validation
# ==========================================================================================

section4a1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "UTF-8 BOM removed",

            "observed":
                source_text_4a1.startswith(
                    "\ufeff"
                ),

            "expected":
                False,

            "passed":
                not source_text_4a1.startswith(
                    "\ufeff"
                ),
        },

        {
            "validation":
                "Notebook 48 AST parses",

            "observed":
                True,

            "expected":
                True,

            "passed":
                True,
        },

        {
            "validation":
                "exact schedule builder recovered",

            "observed":
                callable(
                    build_balanced_schedule_4a1
                ),

            "expected":
                True,

            "passed":
                callable(
                    build_balanced_schedule_4a1
                ),
        },

        {
            "validation":
                "exactly 300 schedule rows",

            "observed":
                len(
                    section4a1_schedule_df
                ),

            "expected":
                300,

            "passed":
                len(
                    section4a1_schedule_df
                )
                ==
                300,
        },

        {
            "validation":
                "100 matches per baseline",

            "observed":
                baseline_count_lookup_4a1,

            "expected":
                100,

            "passed":
                exact_100_each_4a1,
        },

        {
            "validation":
                "50/50 evaluated-side split per baseline",

            "observed":
                side_count_lookup_4a1,

            "expected":
                "50 Player + 50 Opponent each",

            "passed":
                exact_50_50_each_4a1,
        },

        {
            "validation":
                "required schedule columns present",

            "observed":
                missing_columns_4a1,

            "expected":
                [],

            "passed":
                missing_columns_4a1
                ==
                [],
        },

        {
            "validation":
                "no null required schedule values",

            "observed":
                null_required_values_4a1,

            "expected":
                0,

            "passed":
                null_required_values_4a1
                ==
                0,
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                )
                ==
                46,
        },
    ]
)


print("\nSECTION 4A.1 VALIDATION")
print("-" * 100)

display(
    section4a1_validation_df
)


assert (
    section4a1_validation_df[
        "passed"
    ].all()
), (
    "Section 4A.1 failed. "
    "Do not execute the 300-match benchmark."
)


# ==========================================================================================
# 16. Preserve aliases for later Notebook 60 sections
# ==========================================================================================

build_balanced_schedule = (
    build_balanced_schedule_4a1
)

full_schedule = list(
    full_schedule_4a1
)


print("\n" + "=" * 100)

print("✅ UTF-8 BOM ISSUE REPAIRED")
print("✅ NOTEBOOK 48 SOURCE PARSED SUCCESSFULLY")
print("✅ EXACT build_balanced_schedule() RECOVERED")
print("✅ EXACTLY 300 MATCHES SCHEDULED")
print("✅ 100 MATCHES PER HISTORICAL BASELINE")
print("✅ 50 PLAYER + 50 OPPONENT EVALUATIONS PER BASELINE")
print("✅ REQUIRED SCHEDULE FIELDS VALIDATED")
print("✅ CARD MATCHUP COVERAGE RECOVERED")
print("✅ FROZEN R3 MODEL REMAINS 46 FEATURES")
print("✅ SECTION 4A.1 COMPLETE")
print("⚠️ ZERO OF THE 300 BENCHMARK MATCHES EXECUTED")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 4A.1 — REPAIR UTF-8 BOM AND COMPLETE HISTORICAL SCHEDULE RECOVERY
====================================================================================================

HISTORICAL BENCHMARK TARGET
----------------------------------------------------------------------------------------------------
Baselines                : ['Random Baseline', 'Greedy Damage Baseline', 'Depth-6 Search Baseline']
Matches per baseline     : 100
Matches per side/baseline: 50
Total matches            : 300

AUTHORITATIVE NOTEBOOK 48 SCRIPT
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\48_tournament_evaluation_and_elo_benchmarking.py

SOURCE ENCODING CHECK
----------------------------------------------------------------------------------------------------
First character repr: 'f'
Starts with BOM: False

AST PARSE STATUS
----------------------------------------------------------------------------------------------------
Parsed successfully: True
Top-level nodes: 481

EXACT NOTEBOOK 48 SCHEDULE BUILDER
----------------------------------------------------------------------------------------------------
Function: build_balanced_schedule
Start line: 3327
End line: 3405

SOURCE
----------------------------------------------------------------------------------------------------
def build_balanced_schedule(
    baseline_name: str,
    match_count: int,
) -> list[dict[str, Any]]:
    schedule = []

    card_count = len(
        TOURNAMENT_CARD_TEMPLATES
    )

    for match_index in range(
        match_count
    ):
        evaluated_side = (
            "Player"
            if match_index % 2 == 0
            else "Opponent"
        )

        starting_side = (
            "Player"
            if (
                match_index // 2
            ) % 2 == 0
            else "Opponent"
        )

        first_card_index = (
            match_index
            % card_count
        )

        second_card_index = (
            (
                match_index * 3
            )
            + 1
        ) % card_count

        if (
            second_card_index
            == first_card_index
        ):
            second_card_index = (
                second_card_index + 1
            ) % card_count

        player_card = (
            TOURNAMENT_CARD_TEMPLATES[
                first_card_index
            ]
        )

        opponent_card = (
            TOURNAMENT_CARD_TEMPLATES[
                second_card_index
            ]
        )

        schedule.append(
            {
                "baseline_name":
                    baseline_name,

                "evaluated_agent_side":
                    evaluated_side,

                "starting_side":
                    starting_side,

                "player_card":
                    player_card,

                "opponent_card":
                    opponent_card,
            }
        )

    return schedule

TRUE SCHEDULE BUILDER EXTERNAL DEPENDENCIES
----------------------------------------------------------------------------------------------------
- Any
- TOURNAMENT_CARD_TEMPLATES

SCHEDULE BUILDER DEPENDENCY STATUS
----------------------------------------------------------------------------------------------------

                  dependency  available   source object_type
0                        Any       True  globals    _AnyMeta
1  TOURNAMENT_CARD_TEMPLATES       True  globals        list

RECOVERED SCHEDULE BUILDER
----------------------------------------------------------------------------------------------------
Callable: True
Signature: (baseline_name: str, match_count: int) -> list[dict[str, typing.Any]]

SCHEDULE CONSTRUCTION
----------------------------------------------------------------------------------------------------
Total schedule rows: 300

FIRST 20 SCHEDULE ROWS
----------------------------------------------------------------------------------------------------

,match_id,baseline_name,player_card,opponent_card,starting_side,evaluated_agent_side
0,1,Random Baseline,Pikachu,Charmander,Player,Player
1,2,Random Baseline,Charmander,Eevee,Player,Opponent
2,3,Random Baseline,Squirtle,Charmander,Opponent,Player
3,4,Random Baseline,Bulbasaur,Eevee,Opponent,Opponent
4,5,Random Baseline,Eevee,Charmander,Player,Player
5,6,Random Baseline,Meowth,Eevee,Player,Opponent
6,7,Random Baseline,Pikachu,Charmander,Opponent,Player
7,8,Random Baseline,Charmander,Eevee,Opponent,Opponent
8,9,Random Baseline,Squirtle,Charmander,Player,Player
9,10,Random Baseline,Bulbasaur,Eevee,Player,Opponent
10,11,Random Baseline,Eevee,Charmander,Opponent,Player
11,12,Random Baseline,Meowth,Eevee,Opponent,Opponent
12,13,Random Baseline,Pikachu,Charmander,Player,Player
13,14,Random Baseline,Charmander,Eevee,Player,Opponent
14,15,Random Baseline,Squirtle,Charmander,Opponent,Player
15,16,Random Baseline,Bulbasaur,Eevee,Opponent,Opponent
16,17,Random Baseline,Eevee,Charmander,Player,Player
17,18,Random Baseline,Meowth,Eevee,Player,Opponent
18,19,Random Baseline,Pikachu,Charmander,Opponent,Player
19,20,Random Baseline,Charmander,Eevee,Opponent,Opponent

MATCHES PER BASELINE
----------------------------------------------------------------------------------------------------

             baseline_name  matches
0  Depth-6 Search Baseline      100
1   Greedy Damage Baseline      100
2          Random Baseline      100

EVALUATED-AGENT SIDE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name evaluated_agent_side  matches
0  Depth-6 Search Baseline             Opponent       50
1  Depth-6 Search Baseline               Player       50
2   Greedy Damage Baseline             Opponent       50
3   Greedy Damage Baseline               Player       50
4          Random Baseline             Opponent       50
5          Random Baseline               Player       50

STARTING-SIDE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name starting_side  matches
0  Depth-6 Search Baseline      Opponent       50
1  Depth-6 Search Baseline        Player       50
2   Greedy Damage Baseline      Opponent       50
3   Greedy Damage Baseline        Player       50
4          Random Baseline      Opponent       50
5          Random Baseline        Player       50

CARD MATCHUP COVERAGE
----------------------------------------------------------------------------------------------------

  player_card opponent_card  matches
0   Bulbasaur         Eevee       51
1  Charmander         Eevee       51
2       Eevee    Charmander       48
3      Meowth         Eevee       48
4     Pikachu    Charmander       51
5    Squirtle    Charmander       51

SECTION 4A.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,UTF-8 BOM removed,False,False,True
1,Notebook 48 AST parses,True,True,True
2,exact schedule builder recovered,True,True,True
3,exactly 300 schedule rows,300,300,True
4,100 matches per baseline,"{'Depth-6 Search Baseline': 100, 'Greedy Damag...",100,True
5,50/50 evaluated-side split per baseline,"{('Depth-6 Search Baseline', 'Opponent'): 50, ...",50 Player + 50 Opponent each,True
6,required schedule columns present,[],[],True
7,no null required schedule values,0,0,True
8,frozen R3 remains 46 features,46,46,True

====================================================================================================
✅ UTF-8 BOM ISSUE REPAIRED
✅ NOTEBOOK 48 SOURCE PARSED SUCCESSFULLY
✅ EXACT build_balanced_schedule() RECOVERED
✅ EXACTLY 300 MATCHES SCHEDULED
✅ 100 MATCHES PER HISTORICAL BASELINE
✅ 50 PLAYER + 50 OPPONENT EVALUATIONS PER BASELINE
✅ REQUIRED SCHEDULE FIELDS VALIDATED
✅ CARD MATCHUP COVERAGE RECOVERED
✅ FROZEN R3 MODEL REMAINS 46 FEATURES
✅ SECTION 4A.1 COMPLETE
⚠️ ZERO OF THE 300 BENCHMARK MATCHES EXECUTED
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET
====================================================================================================

In [58]:
# ==========================================================================================
# SECTION 4B — FINAL 300-MATCH BENCHMARK PREFLIGHT AND EXECUTION LOCK
# ==========================================================================================

print("=" * 100)
print("SECTION 4B — FINAL 300-MATCH BENCHMARK PREFLIGHT AND EXECUTION LOCK")
print("=" * 100)

from pathlib import Path
import inspect
import json
import pandas as pd
import numpy as np


# ==========================================================================================
# 1. Project directories
# ==========================================================================================

PROJECT_ROOT_4B = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

OUTPUTS_60_DIR = (
    PROJECT_ROOT_4B
    / "outputs"
    / "notebook60"
)

REPORTS_60_DIR = (
    PROJECT_ROOT_4B
    / "reports"
    / "notebook60"
)

ARTIFACTS_60_DIR = (
    PROJECT_ROOT_4B
    / "artifacts"
    / "notebook60"
)


for directory_4b in [
    OUTPUTS_60_DIR,
    REPORTS_60_DIR,
    ARTIFACTS_60_DIR,
]:
    directory_4b.mkdir(
        parents=True,
        exist_ok=True,
    )


print("\nNOTEBOOK 60 DIRECTORIES")
print("-" * 100)

print(
    "Output directory  :",
    OUTPUTS_60_DIR
)

print(
    "Report directory  :",
    REPORTS_60_DIR
)

print(
    "Artifact directory:",
    ARTIFACTS_60_DIR
)


# ==========================================================================================
# 2. Exact benchmark structure lock
# ==========================================================================================

BENCHMARK_BASELINES_4B = [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]

MATCHES_PER_BASELINE_4B = 100
TOTAL_MATCHES_4B = 300

MATCHES_PER_SIDE_PER_BASELINE_4B = 50

MAX_TURNS_4B = 50
SEARCH_DEPTH_4B = 6

RANDOM_SEED_4B = 4801


print("\nBENCHMARK STRUCTURE LOCK")
print("-" * 100)

print(
    "Baselines             :",
    BENCHMARK_BASELINES_4B
)

print(
    "Matches per baseline  :",
    MATCHES_PER_BASELINE_4B
)

print(
    "Matches per side      :",
    MATCHES_PER_SIDE_PER_BASELINE_4B
)

print(
    "Total matches         :",
    TOTAL_MATCHES_4B
)

print(
    "Maximum turns         :",
    MAX_TURNS_4B
)

print(
    "Search depth          :",
    SEARCH_DEPTH_4B
)

print(
    "Historical random seed:",
    RANDOM_SEED_4B
)


# ==========================================================================================
# 3. Required component inventory
# ==========================================================================================

required_components_4b = {
    "R3TournamentAgentAdapter":
        globals().get(
            "R3TournamentAgentAdapter"
        ),

    "r3_policy_engine_3c2":
        globals().get(
            "r3_policy_engine_3c2"
        ),

    "run_tournament_match":
        globals().get(
            "run_tournament_match"
        ),

    "create_random_baseline":
        globals().get(
            "create_random_baseline"
        ),

    "create_greedy_baseline":
        globals().get(
            "create_greedy_baseline"
        ),

    "create_search_baseline":
        globals().get(
            "create_search_baseline"
        ),

    "TournamentMatchResult":
        globals().get(
            "TournamentMatchResult"
        ),

    "TOURNAMENT_CARD_TEMPLATES":
        globals().get(
            "TOURNAMENT_CARD_TEMPLATES"
        ),

    "build_balanced_schedule":
        globals().get(
            "build_balanced_schedule"
        ),

    "full_schedule":
        globals().get(
            "full_schedule"
        ),
}


component_rows_4b = []


for component_name_4b, component_4b in (
    required_components_4b.items()
):

    component_rows_4b.append(
        {
            "component":
                component_name_4b,

            "available":
                component_4b is not None,

            "callable":
                callable(
                    component_4b
                ),

            "object_type":
                (
                    type(
                        component_4b
                    ).__name__
                    if component_4b
                    is not None
                    else
                    "MISSING"
                ),
        }
    )


section4b_component_df = pd.DataFrame(
    component_rows_4b
)


print("\nREQUIRED BENCHMARK COMPONENTS")
print("-" * 100)

display(
    section4b_component_df
)


# ==========================================================================================
# 4. Bind exact frozen R3 tournament adapter
# ==========================================================================================

r3_tournament_agent_4b = (
    R3TournamentAgentAdapter(
        r3_policy_engine=
            r3_policy_engine_3c2,
    )
)


print("\nFROZEN R3 TOURNAMENT AGENT")
print("-" * 100)

print(
    "Adapter type :",
    type(
        r3_tournament_agent_4b
    ).__name__
)

print(
    "Agent name   :",
    r3_tournament_agent_4b.name
)

print(
    "Model type   :",
    type(
        r3_policy_engine_3c2.model
    ).__name__
)

print(
    "Feature count:",
    int(
        r3_policy_engine_3c2
        .model
        .n_features_in_
    )
)

print(
    "Classes      :",
    list(
        r3_policy_engine_3c2
        .model
        .classes_
    )
)


# ==========================================================================================
# 5. Frozen R3 model contract
# ==========================================================================================

EXPECTED_R3_CLASSES_4B = [
    "Ascension",
    "Bind Down",
    "Live Coal",
    "Pass",
    "Quick Attack",
    "Tuck Tail",
]


r3_feature_count_4b = int(
    r3_policy_engine_3c2
    .model
    .n_features_in_
)


r3_classes_4b = [
    str(
        value_4b
    )
    for value_4b
    in r3_policy_engine_3c2
    .model
    .classes_
]


print("\nFROZEN R3 CONTRACT")
print("-" * 100)

print(
    "Expected features:",
    46
)

print(
    "Observed features:",
    r3_feature_count_4b
)

print(
    "Expected classes :",
    EXPECTED_R3_CLASSES_4B
)

print(
    "Observed classes :",
    r3_classes_4b
)


# ==========================================================================================
# 6. Baseline factory lock
# ==========================================================================================

baseline_factories_4b = {
    "Random Baseline":
        lambda seed_4b: (
            create_random_baseline(
                seed_4b
            )
        ),

    "Greedy Damage Baseline":
        lambda seed_4b: (
            create_greedy_baseline()
        ),

    "Depth-6 Search Baseline":
        lambda seed_4b: (
            create_search_baseline()
        ),
}


baseline_factory_rows_4b = []


for baseline_name_4b in (
    BENCHMARK_BASELINES_4B
):

    factory_4b = (
        baseline_factories_4b[
            baseline_name_4b
        ]
    )

    baseline_object_4b = None
    baseline_error_4b = None


    try:

        baseline_object_4b = (
            factory_4b(
                RANDOM_SEED_4B
            )
        )

    except Exception as exc_4b:

        baseline_error_4b = (
            f"{type(exc_4b).__name__}: "
            f"{exc_4b}"
        )


    baseline_factory_rows_4b.append(
        {
            "baseline_name":
                baseline_name_4b,

            "factory_callable":
                callable(
                    factory_4b
                ),

            "created":
                baseline_object_4b
                is not None,

            "object_type":
                (
                    type(
                        baseline_object_4b
                    ).__name__
                    if baseline_object_4b
                    is not None
                    else
                    None
                ),

            "error":
                baseline_error_4b,
        }
    )


section4b_factory_df = pd.DataFrame(
    baseline_factory_rows_4b
)


print("\nBASELINE FACTORY PREFLIGHT")
print("-" * 100)

display(
    section4b_factory_df
)


# ==========================================================================================
# 7. Verify exact historical schedule object
# ==========================================================================================

assert isinstance(
    full_schedule,
    list,
)

assert (
    len(
        full_schedule
    )
    ==
    TOTAL_MATCHES_4B
)


schedule_check_rows_4b = []


for index_4b, scheduled_match_4b in enumerate(
    full_schedule,
    start=1,
):

    schedule_check_rows_4b.append(
        {
            "match_id":
                index_4b,

            "baseline_name":
                scheduled_match_4b[
                    "baseline_name"
                ],

            "evaluated_agent_side":
                scheduled_match_4b[
                    "evaluated_agent_side"
                ],

            "starting_side":
                scheduled_match_4b[
                    "starting_side"
                ],

            "player_card":
                scheduled_match_4b[
                    "player_card"
                ]["name"],

            "opponent_card":
                scheduled_match_4b[
                    "opponent_card"
                ]["name"],
        }
    )


section4b_schedule_df = pd.DataFrame(
    schedule_check_rows_4b
)


print("\nLOCKED 300-MATCH SCHEDULE")
print("-" * 100)

print(
    "Rows:",
    len(
        section4b_schedule_df
    )
)


display(
    section4b_schedule_df.head(
        12
    )
)


# ==========================================================================================
# 8. Baseline distribution
# ==========================================================================================

section4b_baseline_distribution_df = (
    section4b_schedule_df
    .groupby(
        "baseline_name"
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nBASELINE DISTRIBUTION")
print("-" * 100)

display(
    section4b_baseline_distribution_df
)


# ==========================================================================================
# 9. Evaluated side distribution
# ==========================================================================================

section4b_side_distribution_df = (
    section4b_schedule_df
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ]
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nSIDE-NEUTRAL DISTRIBUTION")
print("-" * 100)

display(
    section4b_side_distribution_df
)


# ==========================================================================================
# 10. Starting side distribution
# ==========================================================================================

section4b_start_distribution_df = (
    section4b_schedule_df
    .groupby(
        [
            "baseline_name",
            "starting_side",
        ]
    )
    .size()
    .reset_index(
        name="matches"
    )
)


print("\nSTARTING-SIDE DISTRIBUTION")
print("-" * 100)

display(
    section4b_start_distribution_df
)


# ==========================================================================================
# 11. Verify tournament runner signature
# ==========================================================================================

runner_signature_4b = (
    inspect.signature(
        run_tournament_match
    )
)


print("\nTOURNAMENT RUNNER CONTRACT")
print("-" * 100)

print(
    runner_signature_4b
)


runner_parameter_names_4b = list(
    runner_signature_4b
    .parameters
    .keys()
)


required_runner_parameters_4b = [
    "match_id",
    "evaluated_agent",
    "baseline_agent",
    "player_card",
    "opponent_card",
    "starting_side",
    "evaluated_agent_side",
    "max_turns",
    "search_depth",
    "verbose",
]


missing_runner_parameters_4b = [
    parameter_4b

    for parameter_4b
    in required_runner_parameters_4b

    if parameter_4b
    not in runner_parameter_names_4b
]


# ==========================================================================================
# 12. Historical reference targets
# ==========================================================================================

historical_targets_4b = {
    "overall": {
        "matches":
            300,

        "wins":
            194,

        "losses":
            106,

        "draws":
            0,

        "win_rate":
            0.6466666666666666,
    },

    "baseline_win_rates": {
        "Depth-6 Search Baseline":
            0.58,

        "Greedy Damage Baseline":
            0.58,

        "Random Baseline":
            0.78,
    },

    "player_side": {
        "matches":
            150,

        "win_rate":
            0.8666666666666667,
    },

    "opponent_side": {
        "matches":
            150,

        "win_rate":
            0.4266666666666667,
    },
}


print("\nHISTORICAL NOTEBOOK 48 REFERENCE")
print("-" * 100)

print(
    json.dumps(
        historical_targets_4b,
        indent=4,
    )
)


# ==========================================================================================
# 13. Execution configuration
#
# This describes the next section.
# Nothing is executed here.
# ==========================================================================================

benchmark_execution_config_4b = {
    "notebook":
        60,

    "evaluation_policy":
        "R3_STATE_CENTRIC_POLICY",

    "model_type":
        type(
            r3_policy_engine_3c2.model
        ).__name__,

    "feature_count":
        r3_feature_count_4b,

    "total_matches":
        TOTAL_MATCHES_4B,

    "matches_per_baseline":
        MATCHES_PER_BASELINE_4B,

    "matches_per_side_per_baseline":
        MATCHES_PER_SIDE_PER_BASELINE_4B,

    "baseline_names":
        BENCHMARK_BASELINES_4B,

    "max_turns":
        MAX_TURNS_4B,

    "search_depth":
        SEARCH_DEPTH_4B,

    "random_seed":
        RANDOM_SEED_4B,

    "historical_reference_notebook":
        48,

    "historical_overall_win_rate":
        0.6466666666666666,

    "r3_retraining":
        False,

    "r3_model_modification":
        False,

    "benchmark_executed":
        False,
}


print("\nBENCHMARK EXECUTION CONFIGURATION")
print("-" * 100)

print(
    json.dumps(
        benchmark_execution_config_4b,
        indent=4,
    )
)


# ==========================================================================================
# 14. Save preflight evidence
# ==========================================================================================

SECTION4B_CONFIG_FILE = (
    REPORTS_60_DIR
    / "section4b_benchmark_execution_lock.json"
)


with open(
    SECTION4B_CONFIG_FILE,
    "w",
    encoding="utf-8",
) as file_4b:

    json.dump(
        benchmark_execution_config_4b,
        file_4b,
        indent=4,
    )


SECTION4B_SCHEDULE_FILE = (
    REPORTS_60_DIR
    / "section4b_locked_300_match_schedule.csv"
)


section4b_schedule_df.to_csv(
    SECTION4B_SCHEDULE_FILE,
    index=False,
)


print("\nSAVED PREFLIGHT EVIDENCE")
print("-" * 100)

print(
    SECTION4B_CONFIG_FILE
)

print(
    SECTION4B_SCHEDULE_FILE
)


# ==========================================================================================
# 15. Validation helpers
# ==========================================================================================

baseline_counts_4b = (
    section4b_schedule_df[
        "baseline_name"
    ]
    .value_counts()
    .to_dict()
)


side_counts_4b = (
    section4b_schedule_df
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ]
    )
    .size()
    .to_dict()
)


start_counts_4b = (
    section4b_schedule_df
    .groupby(
        [
            "baseline_name",
            "starting_side",
        ]
    )
    .size()
    .to_dict()
)


exact_baseline_distribution_4b = all(
    baseline_counts_4b.get(
        baseline_name_4b,
        0,
    )
    ==
    100

    for baseline_name_4b
    in BENCHMARK_BASELINES_4B
)


exact_side_balance_4b = all(

    side_counts_4b.get(
        (
            baseline_name_4b,
            "Player",
        ),
        0,
    )
    ==
    50

    and

    side_counts_4b.get(
        (
            baseline_name_4b,
            "Opponent",
        ),
        0,
    )
    ==
    50

    for baseline_name_4b
    in BENCHMARK_BASELINES_4B
)


exact_start_balance_4b = all(

    start_counts_4b.get(
        (
            baseline_name_4b,
            "Player",
        ),
        0,
    )
    ==
    50

    and

    start_counts_4b.get(
        (
            baseline_name_4b,
            "Opponent",
        ),
        0,
    )
    ==
    50

    for baseline_name_4b
    in BENCHMARK_BASELINES_4B
)


# ==========================================================================================
# 16. Section 4B final validation
# ==========================================================================================

section4b_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "all required benchmark components available",

            "observed":
                int(
                    section4b_component_df[
                        "available"
                    ].sum()
                ),

            "expected":
                len(
                    required_components_4b
                ),

            "passed":
                bool(
                    section4b_component_df[
                        "available"
                    ].all()
                ),
        },

        {
            "validation":
                "all three baseline factories instantiate",

            "observed":
                int(
                    section4b_factory_df[
                        "created"
                    ].sum()
                ),

            "expected":
                3,

            "passed":
                bool(
                    section4b_factory_df[
                        "created"
                    ].all()
                ),
        },

        {
            "validation":
                "exactly 300 locked schedule rows",

            "observed":
                len(
                    section4b_schedule_df
                ),

            "expected":
                300,

            "passed":
                len(
                    section4b_schedule_df
                )
                ==
                300,
        },

        {
            "validation":
                "100 matches per baseline",

            "observed":
                baseline_counts_4b,

            "expected":
                100,

            "passed":
                exact_baseline_distribution_4b,
        },

        {
            "validation":
                "50/50 evaluated side per baseline",

            "observed":
                side_counts_4b,

            "expected":
                "50 Player + 50 Opponent",

            "passed":
                exact_side_balance_4b,
        },

        {
            "validation":
                "50/50 starting side per baseline",

            "observed":
                start_counts_4b,

            "expected":
                "50 Player + 50 Opponent",

            "passed":
                exact_start_balance_4b,
        },

        {
            "validation":
                "historical runner contract complete",

            "observed":
                missing_runner_parameters_4b,

            "expected":
                [],

            "passed":
                missing_runner_parameters_4b
                ==
                [],
        },

        {
            "validation":
                "frozen R3 feature contract",

            "observed":
                r3_feature_count_4b,

            "expected":
                46,

            "passed":
                r3_feature_count_4b
                ==
                46,
        },

        {
            "validation":
                "frozen six-class action contract",

            "observed":
                r3_classes_4b,

            "expected":
                EXPECTED_R3_CLASSES_4B,

            "passed":
                r3_classes_4b
                ==
                EXPECTED_R3_CLASSES_4B,
        },

        {
            "validation":
                "no R3 retraining configured",

            "observed":
                benchmark_execution_config_4b[
                    "r3_retraining"
                ],

            "expected":
                False,

            "passed":
                benchmark_execution_config_4b[
                    "r3_retraining"
                ]
                is False,
        },

        {
            "validation":
                "no R3 model modification configured",

            "observed":
                benchmark_execution_config_4b[
                    "r3_model_modification"
                ],

            "expected":
                False,

            "passed":
                benchmark_execution_config_4b[
                    "r3_model_modification"
                ]
                is False,
        },

        {
            "validation":
                "300-match benchmark still not executed",

            "observed":
                benchmark_execution_config_4b[
                    "benchmark_executed"
                ],

            "expected":
                False,

            "passed":
                benchmark_execution_config_4b[
                    "benchmark_executed"
                ]
                is False,
        },
    ]
)


print("\nSECTION 4B VALIDATION")
print("-" * 100)

display(
    section4b_validation_df
)


assert (
    section4b_validation_df[
        "passed"
    ].all()
), (
    "Section 4B preflight failed. "
    "DO NOT launch the 300-match benchmark."
)


# ==========================================================================================
# 17. Final execution gate
# ==========================================================================================

BENCHMARK_READY_4B = bool(
    section4b_validation_df[
        "passed"
    ].all()
)


print("\n" + "=" * 100)

print("✅ NOTEBOOK 60 OUTPUT DIRECTORY READY")
print("✅ NOTEBOOK 60 REPORT DIRECTORY READY")
print("✅ NOTEBOOK 60 ARTIFACT DIRECTORY READY")
print("✅ EXACT NOTEBOOK 48 300-MATCH SCHEDULE LOCKED")
print("✅ 100 MATCHES PER BASELINE")
print("✅ 50/50 EVALUATED-AGENT SIDE BALANCE")
print("✅ 50/50 STARTING-SIDE BALANCE")
print("✅ THREE EXACT HISTORICAL BASELINE FACTORIES READY")
print("✅ EXACT HISTORICAL MATCH RUNNER READY")
print("✅ FROZEN R3 TOURNAMENT ADAPTER READY")
print("✅ FROZEN 46-FEATURE CONTRACT VERIFIED")
print("✅ FROZEN SIX-CLASS ACTION CONTRACT VERIFIED")
print("✅ HISTORICAL 64.67% REFERENCE PRESERVED")
print("✅ PREFLIGHT CONFIGURATION SAVED")
print("✅ LOCKED 300-MATCH SCHEDULE SAVED")
print("✅ SECTION 4B COMPLETE")
print()
print("BENCHMARK_READY_4B =", BENCHMARK_READY_4B)
print()
print("⚠️ ZERO OF THE 300 BENCHMARK MATCHES EXECUTED")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ NEXT SECTION WILL BE THE ACTUAL 300-MATCH EXECUTION")

print("=" * 100)

====================================================================================================
SECTION 4B — FINAL 300-MATCH BENCHMARK PREFLIGHT AND EXECUTION LOCK
====================================================================================================

NOTEBOOK 60 DIRECTORIES
----------------------------------------------------------------------------------------------------
Output directory  : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60
Report directory  : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60
Artifact directory: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\artifacts\notebook60

BENCHMARK STRUCTURE LOCK
----------------------------------------------------------------------------------------------------
Baselines             : ['Random Baseline', 'Greedy Damage Baseline', 'Depth-6 Search Baseline']
Matches per baseline  : 100
Matches per side      : 50
Total matches         : 300
Maximum turns         : 50
Search depth          : 6
Historical random seed: 4801

REQUIRED BENCHMARK COMPONENTS
----------------------------------------------------------------------------------------------------

                   component  available  callable         object_type
0   R3TournamentAgentAdapter       True      True                type
1       r3_policy_engine_3c2       True     False  R3LivePolicyEngine
2       run_tournament_match       True      True            function
3     create_random_baseline       True      True            function
4     create_greedy_baseline       True      True            function
5     create_search_baseline       True      True            function
6      TournamentMatchResult       True      True                type
7  TOURNAMENT_CARD_TEMPLATES       True     False                list
8    build_balanced_schedule       True      True            function
9              full_schedule       True     False                list

FROZEN R3 TOURNAMENT AGENT
----------------------------------------------------------------------------------------------------
Adapter type : R3TournamentAgentAdapter
Agent name   : R3_STATE_CENTRIC_POLICY
Model type   : RandomForestClassifier
Feature count: 46
Classes      : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

FROZEN R3 CONTRACT
----------------------------------------------------------------------------------------------------
Expected features: 46
Observed features: 46
Expected classes : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
Observed classes : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

BASELINE FACTORY PREFLIGHT
----------------------------------------------------------------------------------------------------

,baseline_name,factory_callable,created,object_type,error
0,Random Baseline,True,True,RandomLegalMoveAgent,None
1,Greedy Damage Baseline,True,True,GreedyDamageAgent,None
2,Depth-6 Search Baseline,True,True,SearchAgentAdapter,None

LOCKED 300-MATCH SCHEDULE
----------------------------------------------------------------------------------------------------
Rows: 300

,match_id,baseline_name,evaluated_agent_side,starting_side,player_card,opponent_card
0,1,Random Baseline,Player,Player,Pikachu,Charmander
1,2,Random Baseline,Opponent,Player,Charmander,Eevee
2,3,Random Baseline,Player,Opponent,Squirtle,Charmander
3,4,Random Baseline,Opponent,Opponent,Bulbasaur,Eevee
4,5,Random Baseline,Player,Player,Eevee,Charmander
5,6,Random Baseline,Opponent,Player,Meowth,Eevee
6,7,Random Baseline,Player,Opponent,Pikachu,Charmander
7,8,Random Baseline,Opponent,Opponent,Charmander,Eevee
8,9,Random Baseline,Player,Player,Squirtle,Charmander
9,10,Random Baseline,Opponent,Player,Bulbasaur,Eevee
10,11,Random Baseline,Player,Opponent,Eevee,Charmander
11,12,Random Baseline,Opponent,Opponent,Meowth,Eevee

BASELINE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name  matches
0  Depth-6 Search Baseline      100
1   Greedy Damage Baseline      100
2          Random Baseline      100

SIDE-NEUTRAL DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name evaluated_agent_side  matches
0  Depth-6 Search Baseline             Opponent       50
1  Depth-6 Search Baseline               Player       50
2   Greedy Damage Baseline             Opponent       50
3   Greedy Damage Baseline               Player       50
4          Random Baseline             Opponent       50
5          Random Baseline               Player       50

STARTING-SIDE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name starting_side  matches
0  Depth-6 Search Baseline      Opponent       50
1  Depth-6 Search Baseline        Player       50
2   Greedy Damage Baseline      Opponent       50
3   Greedy Damage Baseline        Player       50
4          Random Baseline      Opponent       50
5          Random Baseline        Player       50

TOURNAMENT RUNNER CONTRACT
----------------------------------------------------------------------------------------------------
(match_id: int, evaluated_agent: Any, baseline_agent: Any, player_card: dict[str, typing.Any], opponent_card: dict[str, typing.Any], starting_side: str, evaluated_agent_side: str, max_turns: int = 50, search_depth: int = 6, verbose: bool = False) -> notebook48_historical_benchmark_recovery.TournamentMatchResult

HISTORICAL NOTEBOOK 48 REFERENCE
----------------------------------------------------------------------------------------------------
{
    "overall": {
        "matches": 300,
        "wins": 194,
        "losses": 106,
        "draws": 0,
        "win_rate": 0.6466666666666666
    },
    "baseline_win_rates": {
        "Depth-6 Search Baseline": 0.58,
        "Greedy Damage Baseline": 0.58,
        "Random Baseline": 0.78
    },
    "player_side": {
        "matches": 150,
        "win_rate": 0.8666666666666667
    },
    "opponent_side": {
        "matches": 150,
        "win_rate": 0.4266666666666667
    }
}

BENCHMARK EXECUTION CONFIGURATION
----------------------------------------------------------------------------------------------------
{
    "notebook": 60,
    "evaluation_policy": "R3_STATE_CENTRIC_POLICY",
    "model_type": "RandomForestClassifier",
    "feature_count": 46,
    "total_matches": 300,
    "matches_per_baseline": 100,
    "matches_per_side_per_baseline": 50,
    "baseline_names": [
        "Random Baseline",
        "Greedy Damage Baseline",
        "Depth-6 Search Baseline"
    ],
    "max_turns": 50,
    "search_depth": 6,
    "random_seed": 4801,
    "historical_reference_notebook": 48,
    "historical_overall_win_rate": 0.6466666666666666,
    "r3_retraining": false,
    "r3_model_modification": false,
    "benchmark_executed": false
}

SAVED PREFLIGHT EVIDENCE
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4b_benchmark_execution_lock.json
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4b_locked_300_match_schedule.csv

SECTION 4B VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,all required benchmark components available,10,10,True
1,all three baseline factories instantiate,3,3,True
2,exactly 300 locked schedule rows,300,300,True
3,100 matches per baseline,"{'Random Baseline': 100, 'Greedy Damage Baseli...",100,True
4,50/50 evaluated side per baseline,"{('Depth-6 Search Baseline', 'Opponent'): 50, ...",50 Player + 50 Opponent,True
5,50/50 starting side per baseline,"{('Depth-6 Search Baseline', 'Opponent'): 50, ...",50 Player + 50 Opponent,True
6,historical runner contract complete,[],[],True
7,frozen R3 feature contract,46,46,True
8,frozen six-class action contract,"[Ascension, Bind Down, Live Coal, Pass, Quick ...","[Ascension, Bind Down, Live Coal, Pass, Quick ...",True
9,no R3 retraining configured,False,False,True
10,no R3 model modification configured,False,False,True
11,300-match benchmark still not executed,False,False,True

====================================================================================================
✅ NOTEBOOK 60 OUTPUT DIRECTORY READY
✅ NOTEBOOK 60 REPORT DIRECTORY READY
✅ NOTEBOOK 60 ARTIFACT DIRECTORY READY
✅ EXACT NOTEBOOK 48 300-MATCH SCHEDULE LOCKED
✅ 100 MATCHES PER BASELINE
✅ 50/50 EVALUATED-AGENT SIDE BALANCE
✅ 50/50 STARTING-SIDE BALANCE
✅ THREE EXACT HISTORICAL BASELINE FACTORIES READY
✅ EXACT HISTORICAL MATCH RUNNER READY
✅ FROZEN R3 TOURNAMENT ADAPTER READY
✅ FROZEN 46-FEATURE CONTRACT VERIFIED
✅ FROZEN SIX-CLASS ACTION CONTRACT VERIFIED
✅ HISTORICAL 64.67% REFERENCE PRESERVED
✅ PREFLIGHT CONFIGURATION SAVED
✅ LOCKED 300-MATCH SCHEDULE SAVED
✅ SECTION 4B COMPLETE

BENCHMARK_READY_4B = True

⚠️ ZERO OF THE 300 BENCHMARK MATCHES EXECUTED
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ NEXT SECTION WILL BE THE ACTUAL 300-MATCH EXECUTION
====================================================================================================

In [57]:
# ==========================================================================================
# SECTION 4B.1 — REPAIR R3 TOURNAMENT ADAPTER CONSTRUCTOR AND RESUME PREFLIGHT
# ==========================================================================================

print("=" * 100)
print("SECTION 4B.1 — REPAIR R3 TOURNAMENT ADAPTER CONSTRUCTOR AND RESUME PREFLIGHT")
print("=" * 100)

import inspect
import pandas as pd


# ==========================================================================================
# 1. Inspect exact constructor contract
# ==========================================================================================

print("\nR3TournamentAgentAdapter CONSTRUCTOR")
print("-" * 100)

adapter_signature_4b1 = inspect.signature(
    R3TournamentAgentAdapter
)

print(
    "Signature:",
    adapter_signature_4b1
)


adapter_init_signature_4b1 = inspect.signature(
    R3TournamentAgentAdapter.__init__
)

print(
    "__init__:",
    adapter_init_signature_4b1
)


# ==========================================================================================
# 2. Verify expected parameter
# ==========================================================================================

adapter_parameter_names_4b1 = list(
    adapter_init_signature_4b1
    .parameters
    .keys()
)


print("\nCONSTRUCTOR PARAMETERS")
print("-" * 100)

for parameter_4b1 in adapter_parameter_names_4b1:
    print(
        "-",
        parameter_4b1
    )


assert (
    "r3_policy_engine"
    in adapter_parameter_names_4b1
), (
    "Expected constructor argument "
    "'r3_policy_engine' was not found."
)


# ==========================================================================================
# 3. Create exact frozen R3 tournament adapter
# ==========================================================================================

r3_tournament_agent_4b = (
    R3TournamentAgentAdapter(
        r3_policy_engine=
            r3_policy_engine_3c2,
    )
)


print("\nR3 TOURNAMENT ADAPTER CREATED")
print("-" * 100)

print(
    "Created       :",
    r3_tournament_agent_4b
    is not None
)

print(
    "Type          :",
    type(
        r3_tournament_agent_4b
    ).__name__
)


# ==========================================================================================
# 4. Inspect adapter attributes safely
# ==========================================================================================

adapter_attribute_rows_4b1 = []


for attribute_4b1 in [
    "name",
    "r3_policy_engine",
    "policy_engine",
    "model",
]:

    attribute_exists_4b1 = hasattr(
        r3_tournament_agent_4b,
        attribute_4b1,
    )

    attribute_value_4b1 = (
        getattr(
            r3_tournament_agent_4b,
            attribute_4b1,
        )
        if attribute_exists_4b1
        else None
    )


    adapter_attribute_rows_4b1.append(
        {
            "attribute":
                attribute_4b1,

            "exists":
                attribute_exists_4b1,

            "object_type":
                (
                    type(
                        attribute_value_4b1
                    ).__name__
                    if attribute_value_4b1
                    is not None
                    else None
                ),
        }
    )


section4b1_attribute_df = pd.DataFrame(
    adapter_attribute_rows_4b1
)


print("\nADAPTER ATTRIBUTE CHECK")
print("-" * 100)

display(
    section4b1_attribute_df
)


# ==========================================================================================
# 5. Verify engine identity
# ==========================================================================================

bound_engine_4b1 = getattr(
    r3_tournament_agent_4b,
    "r3_policy_engine",
    None,
)


same_engine_object_4b1 = (
    bound_engine_4b1
    is r3_policy_engine_3c2
)


print("\nFROZEN ENGINE BINDING")
print("-" * 100)

print(
    "Adapter has r3_policy_engine:",
    bound_engine_4b1
    is not None
)

print(
    "Same exact engine object:",
    same_engine_object_4b1
)


assert (
    same_engine_object_4b1
), (
    "Adapter is not bound to the exact "
    "existing frozen R3 policy engine."
)


# ==========================================================================================
# 6. Verify frozen model through existing engine
# ==========================================================================================

frozen_model_4b1 = (
    r3_policy_engine_3c2.model
)


frozen_feature_count_4b1 = int(
    frozen_model_4b1.n_features_in_
)


frozen_classes_4b1 = [
    str(
        value_4b1
    )
    for value_4b1
    in frozen_model_4b1.classes_
]


EXPECTED_R3_CLASSES_4B1 = [
    "Ascension",
    "Bind Down",
    "Live Coal",
    "Pass",
    "Quick Attack",
    "Tuck Tail",
]


print("\nFROZEN R3 MODEL CONTRACT")
print("-" * 100)

print(
    "Model type   :",
    type(
        frozen_model_4b1
    ).__name__
)

print(
    "Feature count:",
    frozen_feature_count_4b1
)

print(
    "Classes      :",
    frozen_classes_4b1
)


# ==========================================================================================
# 7. Verify choose_move interface
# ==========================================================================================

assert hasattr(
    r3_tournament_agent_4b,
    "choose_move",
)


assert callable(
    r3_tournament_agent_4b.choose_move
)


adapter_choose_move_signature_4b1 = (
    inspect.signature(
        r3_tournament_agent_4b.choose_move
    )
)


print("\nADAPTER choose_move() CONTRACT")
print("-" * 100)

print(
    adapter_choose_move_signature_4b1
)


# ==========================================================================================
# 8. Make sure benchmark has still NOT executed
# ==========================================================================================

benchmark_rows_current_4b1 = 0


for possible_name_4b1 in [
    "tournament_rows",
    "tournament_rows_4c",
    "benchmark_rows_4c",
    "section4c_results_df",
]:

    possible_object_4b1 = globals().get(
        possible_name_4b1
    )

    if possible_object_4b1 is None:
        continue


    try:
        benchmark_rows_current_4b1 = max(
            benchmark_rows_current_4b1,
            len(
                possible_object_4b1
            ),
        )

    except Exception:
        pass


print("\nBENCHMARK EXECUTION SAFETY")
print("-" * 100)

print(
    "Observed benchmark result rows:",
    benchmark_rows_current_4b1
)


assert (
    benchmark_rows_current_4b1
    ==
    0
), (
    "Benchmark result rows already exist. "
    "Do not continue until reviewed."
)


# ==========================================================================================
# 9. Validation
# ==========================================================================================

section4b1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "r3_policy_engine constructor parameter confirmed",

            "observed":
                (
                    "r3_policy_engine"
                    in adapter_parameter_names_4b1
                ),

            "expected":
                True,

            "passed":
                (
                    "r3_policy_engine"
                    in adapter_parameter_names_4b1
                ),
        },

        {
            "validation":
                "R3 tournament adapter instantiated",

            "observed":
                type(
                    r3_tournament_agent_4b
                ).__name__,

            "expected":
                "R3TournamentAgentAdapter",

            "passed":
                type(
                    r3_tournament_agent_4b
                ).__name__
                ==
                "R3TournamentAgentAdapter",
        },

        {
            "validation":
                "exact existing policy engine bound",

            "observed":
                same_engine_object_4b1,

            "expected":
                True,

            "passed":
                same_engine_object_4b1,
        },

        {
            "validation":
                "frozen model still 46 features",

            "observed":
                frozen_feature_count_4b1,

            "expected":
                46,

            "passed":
                frozen_feature_count_4b1
                ==
                46,
        },

        {
            "validation":
                "six-class action order unchanged",

            "observed":
                frozen_classes_4b1,

            "expected":
                EXPECTED_R3_CLASSES_4B1,

            "passed":
                frozen_classes_4b1
                ==
                EXPECTED_R3_CLASSES_4B1,
        },

        {
            "validation":
                "adapter choose_move callable",

            "observed":
                callable(
                    r3_tournament_agent_4b.choose_move
                ),

            "expected":
                True,

            "passed":
                callable(
                    r3_tournament_agent_4b.choose_move
                ),
        },

        {
            "validation":
                "zero benchmark result rows",

            "observed":
                benchmark_rows_current_4b1,

            "expected":
                0,

            "passed":
                benchmark_rows_current_4b1
                ==
                0,
        },
    ]
)


print("\nSECTION 4B.1 VALIDATION")
print("-" * 100)

display(
    section4b1_validation_df
)


assert (
    section4b1_validation_df[
        "passed"
    ].all()
), (
    "Section 4B.1 failed. "
    "Do not continue to benchmark execution."
)


print("\n" + "=" * 100)

print("✅ EXACT R3 TOURNAMENT ADAPTER CONSTRUCTOR VERIFIED")
print("✅ r3_policy_engine ARGUMENT USED")
print("✅ EXISTING FROZEN R3 POLICY ENGINE BOUND")
print("✅ FROZEN 46-FEATURE MODEL PRESERVED")
print("✅ SIX-CLASS ACTION CONTRACT PRESERVED")
print("✅ TOURNAMENT choose_move() INTERFACE AVAILABLE")
print("✅ ZERO BENCHMARK MATCHES EXECUTED")
print("✅ SECTION 4B.1 COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET")

print("=" * 100)

====================================================================================================
SECTION 4B.1 — REPAIR R3 TOURNAMENT ADAPTER CONSTRUCTOR AND RESUME PREFLIGHT
====================================================================================================

R3TournamentAgentAdapter CONSTRUCTOR
----------------------------------------------------------------------------------------------------
Signature: (r3_policy_engine, name: str = 'R3_STATE_CENTRIC_POLICY') -> None
__init__: (self, r3_policy_engine, name: str = 'R3_STATE_CENTRIC_POLICY') -> None

CONSTRUCTOR PARAMETERS
----------------------------------------------------------------------------------------------------
- self
- r3_policy_engine
- name

R3 TOURNAMENT ADAPTER CREATED
----------------------------------------------------------------------------------------------------
Created       : True
Type          : R3TournamentAgentAdapter

ADAPTER ATTRIBUTE CHECK
----------------------------------------------------------------------------------------------------

          attribute  exists         object_type
0              name    True                 str
1  r3_policy_engine    True  R3LivePolicyEngine
2     policy_engine   False                 NaN
3             model   False                 NaN

FROZEN ENGINE BINDING
----------------------------------------------------------------------------------------------------
Adapter has r3_policy_engine: True
Same exact engine object: True

FROZEN R3 MODEL CONTRACT
----------------------------------------------------------------------------------------------------
Model type   : RandomForestClassifier
Feature count: 46
Classes      : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

ADAPTER choose_move() CONTRACT
----------------------------------------------------------------------------------------------------
(state: Any = None, depth: int | None = None, battle_state: Any = None, **kwargs: Any) -> notebook48_historical_benchmark_recovery.TournamentDecision

BENCHMARK EXECUTION SAFETY
----------------------------------------------------------------------------------------------------
Observed benchmark result rows: 0

SECTION 4B.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,r3_policy_engine constructor parameter confirmed,True,True,True
1,R3 tournament adapter instantiated,R3TournamentAgentAdapter,R3TournamentAgentAdapter,True
2,exact existing policy engine bound,True,True,True
3,frozen model still 46 features,46,46,True
4,six-class action order unchanged,"[Ascension, Bind Down, Live Coal, Pass, Quick ...","[Ascension, Bind Down, Live Coal, Pass, Quick ...",True
5,adapter choose_move callable,True,True,True
6,zero benchmark result rows,0,0,True

====================================================================================================
✅ EXACT R3 TOURNAMENT ADAPTER CONSTRUCTOR VERIFIED
✅ r3_policy_engine ARGUMENT USED
✅ EXISTING FROZEN R3 POLICY ENGINE BOUND
✅ FROZEN 46-FEATURE MODEL PRESERVED
✅ SIX-CLASS ACTION CONTRACT PRESERVED
✅ TOURNAMENT choose_move() INTERFACE AVAILABLE
✅ ZERO BENCHMARK MATCHES EXECUTED
✅ SECTION 4B.1 COMPLETE
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
⚠️ DO NOT RUN THE 300-MATCH BENCHMARK YET
====================================================================================================

In [59]:
# ==========================================================================================
# SECTION 4C — EXECUTE LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK
# ==========================================================================================

print("=" * 100)
print("SECTION 4C — EXECUTE LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK")
print("=" * 100)

from pathlib import Path
import dataclasses
import json
import math
import time
import warnings

import pandas as pd


# ==========================================================================================
# 1. HARD EXECUTION GATE
# ==========================================================================================

print("\nEXECUTION GATE")
print("-" * 100)

assert (
    globals().get(
        "BENCHMARK_READY_4B",
        False,
    )
    is True
), (
    "Section 4B benchmark preflight has not been approved."
)


assert len(
    full_schedule
) == 300, (
    "Locked schedule must contain exactly 300 matches."
)


assert int(
    r3_policy_engine_3c2
    .model
    .n_features_in_
) == 46, (
    "Frozen R3 model no longer has the required 46-feature contract."
)


EXPECTED_R3_CLASSES_4C = [
    "Ascension",
    "Bind Down",
    "Live Coal",
    "Pass",
    "Quick Attack",
    "Tuck Tail",
]


observed_r3_classes_4c = [
    str(
        value
    )
    for value
    in r3_policy_engine_3c2
    .model
    .classes_
]


assert (
    observed_r3_classes_4c
    ==
    EXPECTED_R3_CLASSES_4C
), (
    "Frozen R3 six-class action contract changed."
)


assert callable(
    run_tournament_match
)

assert callable(
    create_random_baseline
)

assert callable(
    create_greedy_baseline
)

assert callable(
    create_search_baseline
)

assert callable(
    R3TournamentAgentAdapter
)


print("BENCHMARK_READY_4B       :", BENCHMARK_READY_4B)
print("Locked schedule rows     :", len(full_schedule))
print("Frozen feature count     :", r3_policy_engine_3c2.model.n_features_in_)
print("Frozen classes           :", observed_r3_classes_4c)
print("R3 retraining            : False")
print("R3 model modification    : False")


# ==========================================================================================
# 2. NOTEBOOK 60 OUTPUT LOCATIONS
# ==========================================================================================

PROJECT_ROOT_4C = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

OUTPUTS_60_DIR_4C = (
    PROJECT_ROOT_4C
    / "outputs"
    / "notebook60"
)

REPORTS_60_DIR_4C = (
    PROJECT_ROOT_4C
    / "reports"
    / "notebook60"
)

ARTIFACTS_60_DIR_4C = (
    PROJECT_ROOT_4C
    / "artifacts"
    / "notebook60"
)


for directory_4c in [
    OUTPUTS_60_DIR_4C,
    REPORTS_60_DIR_4C,
    ARTIFACTS_60_DIR_4C,
]:
    directory_4c.mkdir(
        parents=True,
        exist_ok=True,
    )


RAW_RESULTS_FILE_4C = (
    OUTPUTS_60_DIR_4C
    / "section4c_r3_300_match_raw_results.csv"
)

FAILURES_FILE_4C = (
    REPORTS_60_DIR_4C
    / "section4c_r3_300_match_failures.json"
)

EXECUTION_SUMMARY_FILE_4C = (
    REPORTS_60_DIR_4C
    / "section4c_r3_300_match_execution_summary.json"
)

PROGRESS_FILE_4C = (
    OUTPUTS_60_DIR_4C
    / "section4c_r3_300_match_progress.csv"
)


print("\nOUTPUT FILES")
print("-" * 100)

print(
    "Raw results      :",
    RAW_RESULTS_FILE_4C
)

print(
    "Failure report   :",
    FAILURES_FILE_4C
)

print(
    "Execution summary:",
    EXECUTION_SUMMARY_FILE_4C
)

print(
    "Progress file    :",
    PROGRESS_FILE_4C
)


# ==========================================================================================
# 3. EXACT BASELINE FACTORY WRAPPER
# ==========================================================================================

def create_baseline_for_match_4c(
    baseline_name,
    match_id,
):
    """
    Instantiate a fresh exact historical Notebook 48 baseline
    for one benchmark match.

    No replacement baseline implementation is permitted.
    """

    if baseline_name == "Random Baseline":

        return create_random_baseline(
            RANDOM_SEED
            + int(
                match_id
            )
        )


    if baseline_name == "Greedy Damage Baseline":

        return create_greedy_baseline()


    if baseline_name == "Depth-6 Search Baseline":

        return create_search_baseline()


    raise ValueError(
        "Unknown historical baseline: "
        f"{baseline_name}"
    )


# ==========================================================================================
# 4. FRESH FROZEN-R3 TOURNAMENT ADAPTER FACTORY
# ==========================================================================================

def create_r3_tournament_agent_4c():
    """
    Create a fresh tournament adapter around the SAME frozen
    Notebook 59 R3 policy engine.

    This does not train, modify, refit, or replace the model.
    """

    return R3TournamentAgentAdapter(
        r3_policy_engine=
            r3_policy_engine_3c2,
    )


# ==========================================================================================
# 5. EXECUTION CONTAINERS
# ==========================================================================================

benchmark_rows_4c = []
benchmark_failures_4c = []

benchmark_start_4c = (
    time.perf_counter()
)


print("\n" + "=" * 100)
print("STARTING LOCKED 300-MATCH BENCHMARK")
print("=" * 100)

print(
    "\nThis is the first execution of the final "
    "Notebook 60 300-match benchmark."
)

print(
    "Historical structure: Notebook 48"
)

print(
    "Evaluated policy      : Frozen R3_STATE_CENTRIC_POLICY"
)

print(
    "Matches               : 300"
)

print(
    "Baselines             : 3 × 100"
)

print(
    "Evaluated-side split  : 50 Player + 50 Opponent per baseline"
)


# ==========================================================================================
# 6. EXECUTE ALL 300 LOCKED MATCHES
# ==========================================================================================

for schedule_index_4c, scheduled_match_4c in enumerate(
    full_schedule,
    start=1,
):

    match_id_4c = int(
        scheduled_match_4c.get(
            "match_id",
            schedule_index_4c,
        )
    )


    baseline_name_4c = str(
        scheduled_match_4c[
            "baseline_name"
        ]
    )


    evaluated_side_4c = str(
        scheduled_match_4c[
            "evaluated_agent_side"
        ]
    )


    starting_side_4c = str(
        scheduled_match_4c[
            "starting_side"
        ]
    )


    player_card_4c = (
        scheduled_match_4c[
            "player_card"
        ]
    )


    opponent_card_4c = (
        scheduled_match_4c[
            "opponent_card"
        ]
    )


    try:

        # ------------------------------------------------------------------
        # Fresh evaluated adapter.
        # SAME frozen R3 model.
        # ------------------------------------------------------------------

        evaluated_agent_4c = (
            create_r3_tournament_agent_4c()
        )


        # ------------------------------------------------------------------
        # Fresh exact historical baseline.
        # ------------------------------------------------------------------

        baseline_agent_4c = (
            create_baseline_for_match_4c(
                baseline_name=
                    baseline_name_4c,

                match_id=
                    match_id_4c,
            )
        )


        # ------------------------------------------------------------------
        # Exact Notebook 48 tournament runner.
        # ------------------------------------------------------------------

        with warnings.catch_warnings():

            warnings.filterwarnings(
                "ignore",
                message=(
                    "X has feature names, "
                    "but RandomForestClassifier "
                    "was fitted without feature names"
                ),
            )


            result_4c = (
                run_tournament_match(
                    match_id=
                        match_id_4c,

                    evaluated_agent=
                        evaluated_agent_4c,

                    baseline_agent=
                        baseline_agent_4c,

                    player_card=
                        player_card_4c,

                    opponent_card=
                        opponent_card_4c,

                    starting_side=
                        starting_side_4c,

                    evaluated_agent_side=
                        evaluated_side_4c,

                    max_turns=
                        50,

                    search_depth=
                        6,

                    verbose=False,
                )
            )


        # ------------------------------------------------------------------
        # Preserve exact historical result fields.
        # ------------------------------------------------------------------

        if dataclasses.is_dataclass(
            result_4c
        ):

            result_row_4c = (
                dataclasses.asdict(
                    result_4c
                )
            )

        else:

            result_row_4c = {
                key_4c:
                    getattr(
                        result_4c,
                        key_4c,
                    )

                for key_4c
                in dir(
                    result_4c
                )

                if (
                    not key_4c.startswith(
                        "_"
                    )
                    and not callable(
                        getattr(
                            result_4c,
                            key_4c,
                        )
                    )
                )
            }


        # ------------------------------------------------------------------
        # Add locked schedule evidence.
        # ------------------------------------------------------------------

        result_row_4c[
            "schedule_match_id"
        ] = match_id_4c


        result_row_4c[
            "scheduled_baseline_name"
        ] = baseline_name_4c


        result_row_4c[
            "scheduled_evaluated_agent_side"
        ] = evaluated_side_4c


        result_row_4c[
            "scheduled_starting_side"
        ] = starting_side_4c


        result_row_4c[
            "scheduled_player_card"
        ] = player_card_4c.get(
            "name"
        )


        result_row_4c[
            "scheduled_opponent_card"
        ] = opponent_card_4c.get(
            "name"
        )


        # ------------------------------------------------------------------
        # Independent outcome reconstruction.
        # Do NOT rely only on agent_result.
        # ------------------------------------------------------------------

        winner_4c = str(
            result_row_4c.get(
                "winner",
                "",
            )
        )


        if winner_4c == evaluated_side_4c:

            reconstructed_outcome_4c = (
                "WIN"
            )

            reconstructed_score_4c = (
                1.0
            )


        elif winner_4c in {
            "Player",
            "Opponent",
        }:

            reconstructed_outcome_4c = (
                "LOSS"
            )

            reconstructed_score_4c = (
                0.0
            )


        else:

            reconstructed_outcome_4c = (
                "DRAW"
            )

            reconstructed_score_4c = (
                0.5
            )


        result_row_4c[
            "r3_outcome"
        ] = reconstructed_outcome_4c


        result_row_4c[
            "r3_score_reconstructed"
        ] = reconstructed_score_4c


        result_row_4c[
            "execution_success"
        ] = True


        benchmark_rows_4c.append(
            result_row_4c
        )


    except Exception as error_4c:

        failure_row_4c = {
            "match_id":
                match_id_4c,

            "baseline_name":
                baseline_name_4c,

            "evaluated_agent_side":
                evaluated_side_4c,

            "starting_side":
                starting_side_4c,

            "player_card":
                player_card_4c.get(
                    "name"
                ),

            "opponent_card":
                opponent_card_4c.get(
                    "name"
                ),

            "error_type":
                type(
                    error_4c
                ).__name__,

            "error":
                str(
                    error_4c
                ),
        }


        benchmark_failures_4c.append(
            failure_row_4c
        )


        print(
            f"\n❌ MATCH {match_id_4c} FAILED"
        )

        print(
            failure_row_4c
        )


    # ----------------------------------------------------------------------
    # Persistent progress every 25 matches.
    # ----------------------------------------------------------------------

    if (
        schedule_index_4c % 25 == 0
        or schedule_index_4c == 300
    ):

        progress_df_4c = pd.DataFrame(
            benchmark_rows_4c
        )


        if not progress_df_4c.empty:

            progress_df_4c.to_csv(
                PROGRESS_FILE_4C,
                index=False,
            )


        elapsed_now_4c = (
            time.perf_counter()
            -
            benchmark_start_4c
        )


        successful_now_4c = len(
            benchmark_rows_4c
        )


        failed_now_4c = len(
            benchmark_failures_4c
        )


        print(
            "\n"
            + "-" * 100
        )

        print(
            f"PROGRESS: {schedule_index_4c}/300 scheduled"
        )

        print(
            f"Successful: {successful_now_4c}"
        )

        print(
            f"Failed    : {failed_now_4c}"
        )

        print(
            f"Elapsed   : {elapsed_now_4c:.2f} seconds"
        )

        print(
            "-" * 100
        )


# ==========================================================================================
# 7. EXECUTION COMPLETE
# ==========================================================================================

benchmark_elapsed_4c = (
    time.perf_counter()
    -
    benchmark_start_4c
)


benchmark_results_df_4c = pd.DataFrame(
    benchmark_rows_4c
)


benchmark_failures_df_4c = pd.DataFrame(
    benchmark_failures_4c
)


print("\n" + "=" * 100)
print("300-MATCH EXECUTION FINISHED")
print("=" * 100)


print(
    "Scheduled matches :",
    len(
        full_schedule
    )
)

print(
    "Successful matches:",
    len(
        benchmark_results_df_4c
    )
)

print(
    "Failed matches    :",
    len(
        benchmark_failures_4c
    )
)

print(
    "Elapsed seconds   :",
    round(
        benchmark_elapsed_4c,
        4,
    )
)


# ==========================================================================================
# 8. SAVE RAW MATCH RESULTS IMMEDIATELY
# ==========================================================================================

benchmark_results_df_4c.to_csv(
    RAW_RESULTS_FILE_4C,
    index=False,
)


with open(
    FAILURES_FILE_4C,
    "w",
    encoding="utf-8",
) as file_4c:

    json.dump(
        benchmark_failures_4c,
        file_4c,
        indent=2,
        default=str,
    )


# ==========================================================================================
# 9. BASIC EXECUTION COUNTS ONLY
#
# IMPORTANT:
# Final historical comparison is intentionally deferred to Section 4D.
# ==========================================================================================

outcome_counts_4c = (
    benchmark_results_df_4c[
        "r3_outcome"
    ]
    .value_counts(
        dropna=False
    )
    .to_dict()
    if (
        not benchmark_results_df_4c.empty
        and "r3_outcome"
        in benchmark_results_df_4c.columns
    )
    else {}
)


fallback_total_4c = 0


if (
    not benchmark_results_df_4c.empty
    and "fallback_count"
    in benchmark_results_df_4c.columns
):

    fallback_total_4c = int(
        pd.to_numeric(
            benchmark_results_df_4c[
                "fallback_count"
            ],
            errors="coerce",
        )
        .fillna(
            0
        )
        .sum()
    )


execution_summary_4c = {
    "notebook":
        60,

    "section":
        "4C",

    "purpose":
        (
            "Execute frozen R3 policy against exact "
            "Notebook 48 historical baselines under "
            "locked 300-match side-neutral schedule."
        ),

    "evaluated_policy":
        "R3_STATE_CENTRIC_POLICY",

    "model_type":
        type(
            r3_policy_engine_3c2.model
        ).__name__,

    "feature_count":
        int(
            r3_policy_engine_3c2
            .model
            .n_features_in_
        ),

    "action_classes":
        observed_r3_classes_4c,

    "scheduled_matches":
        int(
            len(
                full_schedule
            )
        ),

    "successful_matches":
        int(
            len(
                benchmark_results_df_4c
            )
        ),

    "failed_matches":
        int(
            len(
                benchmark_failures_4c
            )
        ),

    "outcome_counts":
        outcome_counts_4c,

    "fallback_count":
        fallback_total_4c,

    "elapsed_seconds":
        float(
            benchmark_elapsed_4c
        ),

    "r3_retraining":
        False,

    "r3_model_modification":
        False,

    "historical_reference_notebook":
        48,

    "historical_reference_win_rate":
        0.6466666666666666,

    "raw_results_file":
        str(
            RAW_RESULTS_FILE_4C
        ),

    "failures_file":
        str(
            FAILURES_FILE_4C
        ),
}


with open(
    EXECUTION_SUMMARY_FILE_4C,
    "w",
    encoding="utf-8",
) as file_4c:

    json.dump(
        execution_summary_4c,
        file_4c,
        indent=2,
        default=str,
    )


# ==========================================================================================
# 10. DISPLAY EXECUTION RESULTS
# ==========================================================================================

print("\nRAW RESULT PREVIEW")
print("-" * 100)

display(
    benchmark_results_df_4c.head(
        20
    )
)


print("\nOUTCOME COUNTS")
print("-" * 100)

print(
    outcome_counts_4c
)


print("\nFALLBACK COUNT")
print("-" * 100)

print(
    fallback_total_4c
)


if benchmark_failures_4c:

    print("\nFAILURES")
    print("-" * 100)

    display(
        benchmark_failures_df_4c
    )

else:

    print("\nFAILURES")
    print("-" * 100)

    print(
        "No benchmark execution failures."
    )


# ==========================================================================================
# 11. SECTION 4C VALIDATION
# ==========================================================================================

section4c_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "exactly 300 scheduled matches",

            "observed":
                len(
                    full_schedule
                ),

            "expected":
                300,

            "passed":
                len(
                    full_schedule
                )
                ==
                300,
        },

        {
            "validation":
                "all 300 benchmark matches succeeded",

            "observed":
                len(
                    benchmark_results_df_4c
                ),

            "expected":
                300,

            "passed":
                len(
                    benchmark_results_df_4c
                )
                ==
                300,
        },

        {
            "validation":
                "zero execution failures",

            "observed":
                len(
                    benchmark_failures_4c
                ),

            "expected":
                0,

            "passed":
                len(
                    benchmark_failures_4c
                )
                ==
                0,
        },

        {
            "validation":
                "raw result file saved",

            "observed":
                RAW_RESULTS_FILE_4C.exists(),

            "expected":
                True,

            "passed":
                RAW_RESULTS_FILE_4C.exists(),
        },

        {
            "validation":
                "execution summary saved",

            "observed":
                EXECUTION_SUMMARY_FILE_4C.exists(),

            "expected":
                True,

            "passed":
                EXECUTION_SUMMARY_FILE_4C.exists(),
        },

        {
            "validation":
                "frozen R3 remains 46 features",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                )
                ==
                46,
        },

        {
            "validation":
                "six-class R3 action order unchanged",

            "observed":
                observed_r3_classes_4c,

            "expected":
                EXPECTED_R3_CLASSES_4C,

            "passed":
                observed_r3_classes_4c
                ==
                EXPECTED_R3_CLASSES_4C,
        },
    ]
)


print("\nSECTION 4C VALIDATION")
print("-" * 100)

display(
    section4c_validation_df
)


SECTION_4C_COMPLETE = bool(
    section4c_validation_df[
        "passed"
    ].all()
)


assert (
    SECTION_4C_COMPLETE
), (
    "Section 4C execution validation failed. "
    "Do not calculate final benchmark metrics yet."
)


print("\n" + "=" * 100)

print("✅ LOCKED 300-MATCH BENCHMARK EXECUTED")
print("✅ EXACT NOTEBOOK 48 TOURNAMENT RUNNER USED")
print("✅ THREE EXACT HISTORICAL BASELINES USED")
print("✅ LOCKED SIDE-NEUTRAL SCHEDULE USED")
print("✅ RAW MATCH EVIDENCE SAVED")
print("✅ EXECUTION SUMMARY SAVED")
print("✅ ZERO EXECUTION FAILURES")
print("✅ FROZEN 46-FEATURE R3 MODEL PRESERVED")
print("✅ SIX-CLASS ACTION CONTRACT PRESERVED")
print("✅ SECTION 4C COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("⚠️ FINAL 64.67% COMPARISON HAS NOT YET BEEN CALCULATED")
print("➡️ NEXT: SECTION 4D — BENCHMARK RESULTS AND HISTORICAL COMPARISON")

print("=" * 100)

====================================================================================================
SECTION 4C — EXECUTE LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK
====================================================================================================

EXECUTION GATE
----------------------------------------------------------------------------------------------------
BENCHMARK_READY_4B       : True
Locked schedule rows     : 300
Frozen feature count     : 46
Frozen classes           : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']
R3 retraining            : False
R3 model modification    : False

OUTPUT FILES
----------------------------------------------------------------------------------------------------
Raw results      : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c_r3_300_match_raw_results.csv
Failure report   : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c_r3_300_match_failures.json
Execution summary: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c_r3_300_match_execution_summary.json
Progress file    : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c_r3_300_match_progress.csv

====================================================================================================
STARTING LOCKED 300-MATCH BENCHMARK
====================================================================================================

This is the first execution of the final Notebook 60 300-match benchmark.
Historical structure: Notebook 48
Evaluated policy      : Frozen R3_STATE_CENTRIC_POLICY
Matches               : 300
Baselines             : 3 × 100
Evaluated-side split  : 50 Player + 50 Opponent per baseline

❌ MATCH 1 FAILED
{'match_id': 1, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 2 FAILED
{'match_id': 2, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 3 FAILED
{'match_id': 3, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 4 FAILED
{'match_id': 4, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 5 FAILED
{'match_id': 5, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 6 FAILED
{'match_id': 6, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 7 FAILED
{'match_id': 7, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 8 FAILED
{'match_id': 8, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 9 FAILED
{'match_id': 9, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 10 FAILED
{'match_id': 10, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 11 FAILED
{'match_id': 11, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 12 FAILED
{'match_id': 12, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 13 FAILED
{'match_id': 13, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 14 FAILED
{'match_id': 14, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 15 FAILED
{'match_id': 15, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 16 FAILED
{'match_id': 16, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 17 FAILED
{'match_id': 17, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 18 FAILED
{'match_id': 18, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 19 FAILED
{'match_id': 19, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 20 FAILED
{'match_id': 20, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 21 FAILED
{'match_id': 21, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 22 FAILED
{'match_id': 22, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 23 FAILED
{'match_id': 23, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 24 FAILED
{'match_id': 24, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 25 FAILED
{'match_id': 25, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

----------------------------------------------------------------------------------------------------
PROGRESS: 25/300 scheduled
Successful: 0
Failed    : 25
Elapsed   : 0.00 seconds
----------------------------------------------------------------------------------------------------

❌ MATCH 26 FAILED
{'match_id': 26, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 27 FAILED
{'match_id': 27, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 28 FAILED
{'match_id': 28, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 29 FAILED
{'match_id': 29, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 30 FAILED
{'match_id': 30, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 31 FAILED
{'match_id': 31, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 32 FAILED
{'match_id': 32, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 33 FAILED
{'match_id': 33, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 34 FAILED
{'match_id': 34, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 35 FAILED
{'match_id': 35, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 36 FAILED
{'match_id': 36, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 37 FAILED
{'match_id': 37, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 38 FAILED
{'match_id': 38, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 39 FAILED
{'match_id': 39, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 40 FAILED
{'match_id': 40, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 41 FAILED
{'match_id': 41, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 42 FAILED
{'match_id': 42, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 43 FAILED
{'match_id': 43, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 44 FAILED
{'match_id': 44, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 45 FAILED
{'match_id': 45, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 46 FAILED
{'match_id': 46, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 47 FAILED
{'match_id': 47, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 48 FAILED
{'match_id': 48, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 49 FAILED
{'match_id': 49, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 50 FAILED
{'match_id': 50, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

----------------------------------------------------------------------------------------------------
PROGRESS: 50/300 scheduled
Successful: 0
Failed    : 50
Elapsed   : 0.00 seconds
----------------------------------------------------------------------------------------------------

❌ MATCH 51 FAILED
{'match_id': 51, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 52 FAILED
{'match_id': 52, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 53 FAILED
{'match_id': 53, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 54 FAILED
{'match_id': 54, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 55 FAILED
{'match_id': 55, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 56 FAILED
{'match_id': 56, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 57 FAILED
{'match_id': 57, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 58 FAILED
{'match_id': 58, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 59 FAILED
{'match_id': 59, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 60 FAILED
{'match_id': 60, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 61 FAILED
{'match_id': 61, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Pikachu', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 62 FAILED
{'match_id': 62, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Charmander', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 63 FAILED
{'match_id': 63, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Opponent', 'player_card': 'Squirtle', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 64 FAILED
{'match_id': 64, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Opponent', 'player_card': 'Bulbasaur', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 65 FAILED
{'match_id': 65, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Player', 'starting_side': 'Player', 'player_card': 'Eevee', 'opponent_card': 'Charmander', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 66 FAILED
{'match_id': 66, 'baseline_name': 'Random Baseline', 'evaluated_agent_side': 'Opponent', 'starting_side': 'Player', 'player_card': 'Meowth', 'opponent_card': 'Eevee', 'error_type': 'NameError', 'error': "name 'RANDOM_SEED' is not defined"}

❌ MATCH 67 FAILED

,match_id,agent_name,baseline_name,player_card,opponent_card,starting_side,winner,turns,stop_reason,agent_result,...,elapsed_seconds,schedule_match_id,scheduled_baseline_name,scheduled_evaluated_agent_side,scheduled_starting_side,scheduled_player_card,scheduled_opponent_card,r3_outcome,r3_score_reconstructed,execution_success
0,101,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Pikachu,Charmander,Player,Opponent,6,Battle reached a terminal state.,0.0,...,0.312506,101,Greedy Damage Baseline,Player,Player,Pikachu,Charmander,LOSS,0.0,True
1,102,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Charmander,Eevee,Player,Player,3,Battle reached a terminal state.,0.0,...,0.083606,102,Greedy Damage Baseline,Opponent,Player,Charmander,Eevee,LOSS,0.0,True
2,103,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Squirtle,Charmander,Opponent,Opponent,5,Battle reached a terminal state.,0.0,...,0.156996,103,Greedy Damage Baseline,Player,Opponent,Squirtle,Charmander,LOSS,0.0,True
3,104,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Bulbasaur,Eevee,Opponent,Player,4,Battle reached a terminal state.,0.0,...,0.156196,104,Greedy Damage Baseline,Opponent,Opponent,Bulbasaur,Eevee,LOSS,0.0,True
4,105,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Eevee,Charmander,Player,Opponent,4,Battle reached a terminal state.,0.0,...,0.150351,105,Greedy Damage Baseline,Player,Player,Eevee,Charmander,LOSS,0.0,True
5,106,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Meowth,Eevee,Player,Player,3,Battle reached a terminal state.,0.0,...,0.098339,106,Greedy Damage Baseline,Opponent,Player,Meowth,Eevee,LOSS,0.0,True
6,107,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Pikachu,Charmander,Opponent,Opponent,5,Battle reached a terminal state.,0.0,...,0.146909,107,Greedy Damage Baseline,Player,Opponent,Pikachu,Charmander,LOSS,0.0,True
7,108,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Charmander,Eevee,Opponent,Player,4,Battle reached a terminal state.,0.0,...,0.156012,108,Greedy Damage Baseline,Opponent,Opponent,Charmander,Eevee,LOSS,0.0,True
8,109,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Squirtle,Charmander,Player,Opponent,6,Battle reached a terminal state.,0.0,...,0.258603,109,Greedy Damage Baseline,Player,Player,Squirtle,Charmander,LOSS,0.0,True
9,110,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Bulbasaur,Eevee,Player,Player,3,Battle reached a terminal state.,0.0,...,0.099265,110,Greedy Damage Baseline,Opponent,Player,Bulbasaur,Eevee,LOSS,0.0,True
10,111,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Eevee,Charmander,Opponent,Opponent,3,Battle reached a terminal state.,0.0,...,0.077385,111,Greedy Damage Baseline,Player,Opponent,Eevee,Charmander,LOSS,0.0,True
11,112,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Meowth,Eevee,Opponent,Player,4,Battle reached a terminal state.,0.0,...,0.175160,112,Greedy Damage Baseline,Opponent,Opponent,Meowth,Eevee,LOSS,0.0,True
12,113,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Pikachu,Charmander,Player,Opponent,6,Battle reached a terminal state.,0.0,...,0.284683,113,Greedy Damage Baseline,Player,Player,Pikachu,Charmander,LOSS,0.0,True
13,114,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Charmander,Eevee,Player,Player,3,Battle reached a terminal state.,0.0,...,0.098836,114,Greedy Damage Baseline,Opponent,Player,Charmander,Eevee,LOSS,0.0,True
14,115,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Squirtle,Charmander,Opponent,Opponent,5,Battle reached a terminal state.,0.0,...,0.155908,115,Greedy Damage Baseline,Player,Opponent,Squirtle,Charmander,LOSS,0.0,True
15,116,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Bulbasaur,Eevee,Opponent,Player,4,Battle reached a terminal state.,0.0,...,0.147005,116,Greedy Damage Baseline,Opponent,Opponent,Bulbasaur,Eevee,LOSS,0.0,True
16,117,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Eevee,Charmander,Player,Opponent,4,Battle reached a terminal state.,0.0,...,0.141016,117,Greedy Damage Baseline,Player,Player,Eevee,Charmander,LOSS,0.0,True
17,118,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Meowth,Eevee,Player,Player,3,Battle reached a terminal state.,0.0,...,0.082143,118,Greedy Damage Baseline,Opponent,Player,Meowth,Eevee,LOSS,0.0,True
18,119,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Pikachu,Charmander,Opponent,Opponent,5,Battle reached a terminal state.,0.0,...,0.186429,119,Greedy Damage Baseline,Player,Opponent,Pikachu,Charmander,LOSS,0.0,True
19,120,R3_STATE_CENTRIC_POLICY,Greedy Damage Baseline,Charmander,Eevee,Opponent,Player,4,Battle reached a terminal state.,0.0,...,0.200311,120,Greedy Damage Baseline,Opponent,Opponent,Charmander,Eevee,LOSS,0.0,True

OUTCOME COUNTS
----------------------------------------------------------------------------------------------------
{'LOSS': 183, 'WIN': 17}

FALLBACK COUNT
----------------------------------------------------------------------------------------------------
373

FAILURES
----------------------------------------------------------------------------------------------------

,match_id,baseline_name,evaluated_agent_side,starting_side,player_card,opponent_card,error_type,error
0,1,Random Baseline,Player,Player,Pikachu,Charmander,NameError,name 'RANDOM_SEED' is not defined
1,2,Random Baseline,Opponent,Player,Charmander,Eevee,NameError,name 'RANDOM_SEED' is not defined
2,3,Random Baseline,Player,Opponent,Squirtle,Charmander,NameError,name 'RANDOM_SEED' is not defined
3,4,Random Baseline,Opponent,Opponent,Bulbasaur,Eevee,NameError,name 'RANDOM_SEED' is not defined
4,5,Random Baseline,Player,Player,Eevee,Charmander,NameError,name 'RANDOM_SEED' is not defined
...,...,...,...,...,...,...,...,...
95,96,Random Baseline,Opponent,Opponent,Meowth,Eevee,NameError,name 'RANDOM_SEED' is not defined
96,97,Random Baseline,Player,Player,Pikachu,Charmander,NameError,name 'RANDOM_SEED' is not defined
97,98,Random Baseline,Opponent,Player,Charmander,Eevee,NameError,name 'RANDOM_SEED' is not defined
98,99,Random Baseline,Player,Opponent,Squirtle,Charmander,NameError,name 'RANDOM_SEED' is not defined
99,100,Random Baseline,Opponent,Opponent,Bulbasaur,Eevee,NameError,name 'RANDOM_SEED' is not defined

SECTION 4C VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,exactly 300 scheduled matches,300,300,True
1,all 300 benchmark matches succeeded,200,300,False
2,zero execution failures,100,0,False
3,raw result file saved,True,True,True
4,execution summary saved,True,True,True
5,frozen R3 remains 46 features,46,46,True
6,six-class R3 action order unchanged,"[Ascension, Bind Down, Live Coal, Pass, Quick ...","[Ascension, Bind Down, Live Coal, Pass, Quick ...",True

AssertionError: Section 4C execution validation failed. Do not calculate final benchmark metrics yet.

In [61]:
# ==========================================================================================
# SECTION 4C.1 — REPAIR HISTORICAL TOURNAMENT RANDOM-SEED CONTRACT
# ==========================================================================================

print("=" * 100)
print("SECTION 4C.1 — REPAIR HISTORICAL TOURNAMENT RANDOM-SEED CONTRACT")
print("=" * 100)

from pathlib import Path
import ast
import pandas as pd


# ==========================================================================================
# 1. AUTHORITATIVE NOTEBOOK 48 SCRIPT
# ==========================================================================================

PROJECT_ROOT_4C1 = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

NOTEBOOK48_SCRIPT_4C1 = (
    PROJECT_ROOT_4C1
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py"
)

assert NOTEBOOK48_SCRIPT_4C1.exists(), (
    f"Notebook 48 script not found: {NOTEBOOK48_SCRIPT_4C1}"
)

print("\nAUTHORITATIVE SOURCE")
print("-" * 100)
print(NOTEBOOK48_SCRIPT_4C1)


# ==========================================================================================
# 2. READ AND PARSE SOURCE SAFELY
# ==========================================================================================

source_4c1 = NOTEBOOK48_SCRIPT_4C1.read_text(
    encoding="utf-8-sig"
)

tree_4c1 = ast.parse(
    source_4c1,
    filename=str(
        NOTEBOOK48_SCRIPT_4C1
    ),
)


# ==========================================================================================
# 3. LOCATE HISTORICAL RANDOM-SEED ASSIGNMENTS
# ==========================================================================================

seed_names_4c1 = {
    "RANDOM_SEED",
    "TOURNAMENT_RANDOM_SEED",
}

seed_records_4c1 = []


for node_4c1 in tree_4c1.body:

    assigned_names_4c1 = []


    if isinstance(
        node_4c1,
        ast.Assign,
    ):

        for target_4c1 in node_4c1.targets:

            if isinstance(
                target_4c1,
                ast.Name,
            ):

                assigned_names_4c1.append(
                    target_4c1.id
                )


    elif isinstance(
        node_4c1,
        ast.AnnAssign,
    ):

        if isinstance(
            node_4c1.target,
            ast.Name,
        ):

            assigned_names_4c1.append(
                node_4c1.target.id
            )


    for assigned_name_4c1 in assigned_names_4c1:

        if assigned_name_4c1 in seed_names_4c1:

            source_segment_4c1 = ast.get_source_segment(
                source_4c1,
                node_4c1,
            )

            seed_records_4c1.append(
                {
                    "name":
                        assigned_name_4c1,

                    "line_number":
                        int(
                            node_4c1.lineno
                        ),

                    "source":
                        source_segment_4c1,
                }
            )


seed_inventory_4c1 = pd.DataFrame(
    seed_records_4c1
)


print("\nNOTEBOOK 48 RANDOM-SEED SOURCE INVENTORY")
print("-" * 100)

display(
    seed_inventory_4c1
)


assert len(
    seed_inventory_4c1
) >= 1, (
    "Could not locate historical random-seed assignment."
)


# ==========================================================================================
# 4. RECOVER CONSTANT VALUES FROM SIMPLE ASSIGNMENTS
# ==========================================================================================

recovered_seed_values_4c1 = {}


for record_4c1 in seed_records_4c1:

    assignment_tree_4c1 = ast.parse(
        record_4c1[
            "source"
        ]
    )


    assignment_node_4c1 = (
        assignment_tree_4c1.body[0]
    )


    if isinstance(
        assignment_node_4c1,
        ast.Assign,
    ):

        value_node_4c1 = (
            assignment_node_4c1.value
        )

    elif isinstance(
        assignment_node_4c1,
        ast.AnnAssign,
    ):

        value_node_4c1 = (
            assignment_node_4c1.value
        )

    else:

        continue


    try:

        value_4c1 = ast.literal_eval(
            value_node_4c1
        )

        recovered_seed_values_4c1[
            record_4c1[
                "name"
            ]
        ] = value_4c1

    except Exception:

        pass


print("\nRECOVERED HISTORICAL SEED VALUES")
print("-" * 100)

print(
    recovered_seed_values_4c1
)


# ==========================================================================================
# 5. RESOLVE EXACT TOURNAMENT SEED
#
# Historical evidence already recovered in Notebook 60 locked this value at 4801.
# Prefer the explicit tournament seed if present; otherwise accept the locked
# historical random seed only if it equals 4801.
# ==========================================================================================

if (
    "TOURNAMENT_RANDOM_SEED"
    in recovered_seed_values_4c1
):

    TOURNAMENT_RANDOM_SEED_4C1 = int(
        recovered_seed_values_4c1[
            "TOURNAMENT_RANDOM_SEED"
        ]
    )


elif (
    "RANDOM_SEED"
    in recovered_seed_values_4c1
):

    TOURNAMENT_RANDOM_SEED_4C1 = int(
        recovered_seed_values_4c1[
            "RANDOM_SEED"
        ]
    )


else:

    # Exact Notebook 48 tournament-specific random seed.
    TOURNAMENT_RANDOM_SEED_4C1 = 4804


print("\nRESOLVED HISTORICAL TOURNAMENT SEED")
print("-" * 100)

print(
    "TOURNAMENT_RANDOM_SEED_4C1 :",
    TOURNAMENT_RANDOM_SEED_4C1
)


assert (
    TOURNAMENT_RANDOM_SEED_4C1
    ==
    4804
), (
    "Historical tournament seed does not match "
    "the authoritative Notebook 48 TOURNAMENT_RANDOM_SEED value of 4804."
)

# ==========================================================================================
# 6. REPAIR BASELINE FACTORY FOR BENCHMARK EXECUTION
# ==========================================================================================

def create_baseline_for_match_4c1(
    baseline_name,
    match_id,
):
    """
    Create a fresh exact Notebook 48 baseline agent.

    Random baseline receives the historical per-match tournament seed:
        4801 + global_match_id

    Greedy and depth-6 factories retain their exact recovered contracts.
    """

    resolved_match_id_4c1 = int(
        match_id
    )


    if baseline_name == "Random Baseline":

        return create_random_baseline(
            TOURNAMENT_RANDOM_SEED_4C1
            + resolved_match_id_4c1
        )


    if baseline_name == "Greedy Damage Baseline":

        return create_greedy_baseline()


    if baseline_name == "Depth-6 Search Baseline":

        return create_search_baseline()


    raise ValueError(
        "Unknown historical baseline: "
        f"{baseline_name}"
    )


# ==========================================================================================
# 7. TEST THE PREVIOUSLY FAILING RANDOM BASELINE
# ==========================================================================================

print("\nRANDOM BASELINE FACTORY REPAIR TEST")
print("-" * 100)


random_test_agent_4c1 = (
    create_baseline_for_match_4c1(
        baseline_name=
            "Random Baseline",

        match_id=
            1,
    )
)


print(
    "Created       :",
    random_test_agent_4c1 is not None
)

print(
    "Object type   :",
    type(
        random_test_agent_4c1
    ).__name__
)

print(
    "Expected type :",
    "RandomLegalMoveAgent"
)

print(
    "Seed supplied :",
    TOURNAMENT_RANDOM_SEED_4C1 + 1
)


assert (
    type(
        random_test_agent_4c1
    ).__name__
    ==
    "RandomLegalMoveAgent"
)


# ==========================================================================================
# 8. VERIFY ALL THREE BASELINES
# ==========================================================================================

baseline_test_rows_4c1 = []


for baseline_name_4c1 in [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]:

    try:

        baseline_object_4c1 = (
            create_baseline_for_match_4c1(
                baseline_name=
                    baseline_name_4c1,

                match_id=
                    1,
            )
        )


        baseline_test_rows_4c1.append(
            {
                "baseline":
                    baseline_name_4c1,

                "created":
                    True,

                "object_type":
                    type(
                        baseline_object_4c1
                    ).__name__,

                "error":
                    None,
            }
        )


    except Exception as error_4c1:

        baseline_test_rows_4c1.append(
            {
                "baseline":
                    baseline_name_4c1,

                "created":
                    False,

                "object_type":
                    None,

                "error":
                    (
                        f"{type(error_4c1).__name__}: "
                        f"{error_4c1}"
                    ),
            }
        )


baseline_factory_validation_4c1 = pd.DataFrame(
    baseline_test_rows_4c1
)


print("\nTHREE-BASELINE FACTORY VALIDATION")
print("-" * 100)

display(
    baseline_factory_validation_4c1
)


# ==========================================================================================
# 9. CONFIRM FAILED 4C RUN IS NOT ACCEPTED AS BENCHMARK
# ==========================================================================================

previous_success_count_4c1 = (
    len(
        benchmark_results_df_4c
    )
    if "benchmark_results_df_4c"
    in globals()
    else None
)


previous_failure_count_4c1 = (
    len(
        benchmark_failures_4c
    )
    if "benchmark_failures_4c"
    in globals()
    else None
)


print("\nPREVIOUS SECTION 4C STATUS")
print("-" * 100)

print(
    "Successful matches :",
    previous_success_count_4c1
)

print(
    "Failed matches     :",
    previous_failure_count_4c1
)

print(
    "Accepted benchmark :",
    False
)


# ==========================================================================================
# 10. SECTION 4C.1 VALIDATION
# ==========================================================================================

section4c1_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "Notebook 48 source parsed",

            "observed":
                True,

            "expected":
                True,

            "passed":
                True,
        },

        {
            "validation":
                "historical tournament seed resolved",

            "observed":
                TOURNAMENT_RANDOM_SEED_4C1,

            "expected":
                4804,

            "passed":
                TOURNAMENT_RANDOM_SEED_4C1
                ==
                4804,
        },

        {
            "validation":
                "random baseline factory repaired",

            "observed":
                type(
                    random_test_agent_4c1
                ).__name__,

            "expected":
                "RandomLegalMoveAgent",

            "passed":
                type(
                    random_test_agent_4c1
                ).__name__
                ==
                "RandomLegalMoveAgent",
        },

        {
            "validation":
                "all three historical baselines instantiate",

            "observed":
                int(
                    baseline_factory_validation_4c1[
                        "created"
                    ].sum()
                ),

            "expected":
                3,

            "passed":
                bool(
                    baseline_factory_validation_4c1[
                        "created"
                    ].all()
                ),
        },

        {
            "validation":
                "frozen R3 model remains 46 features",

            "observed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                ),

            "expected":
                46,

            "passed":
                int(
                    r3_policy_engine_3c2
                    .model
                    .n_features_in_
                )
                ==
                46,
        },

        {
            "validation":
                "failed partial benchmark rejected",

            "observed":
                False,

            "expected":
                False,

            "passed":
                True,
        },
    ]
)


print("\nSECTION 4C.1 VALIDATION")
print("-" * 100)

display(
    section4c1_validation_df
)


SECTION_4C1_COMPLETE = bool(
    section4c1_validation_df[
        "passed"
    ].all()
)


assert SECTION_4C1_COMPLETE


print("\n" + "=" * 100)
print("✅ RANDOM BASELINE SEED CONTRACT REPAIRED")
print("✅ HISTORICAL TOURNAMENT SEED = 4804 VERIFIED")
print("✅ RANDOM BASELINE NOW INSTANTIATES")
print("✅ GREEDY DAMAGE BASELINE STILL INSTANTIATES")
print("✅ DEPTH-6 SEARCH BASELINE STILL INSTANTIATES")
print("✅ FROZEN R3 MODEL REMAINS 46 FEATURES")
print("✅ FAILED 200/300 PARTIAL RUN IS NOT ACCEPTED")
print("✅ SECTION 4C.1 COMPLETE")
print("⚠️ NO RETRAINING")
print("⚠️ NO MODEL MODIFICATION")
print("➡️ NEXT: CLEAN RE-RUN OF ALL 300 MATCHES")
print("=" * 100)

====================================================================================================
SECTION 4C.1 — REPAIR HISTORICAL TOURNAMENT RANDOM-SEED CONTRACT
====================================================================================================

AUTHORITATIVE SOURCE
----------------------------------------------------------------------------------------------------
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\scripts\48_tournament_evaluation_and_elo_benchmarking.py

NOTEBOOK 48 RANDOM-SEED SOURCE INVENTORY
----------------------------------------------------------------------------------------------------

                     name  line_number                         source
0             RANDOM_SEED          129             RANDOM_SEED = 4801
1  TOURNAMENT_RANDOM_SEED         3253  TOURNAMENT_RANDOM_SEED = 4804

RECOVERED HISTORICAL SEED VALUES
----------------------------------------------------------------------------------------------------
{'RANDOM_SEED': 4801, 'TOURNAMENT_RANDOM_SEED': 4804}

RESOLVED HISTORICAL TOURNAMENT SEED
----------------------------------------------------------------------------------------------------
TOURNAMENT_RANDOM_SEED_4C1 : 4804

RANDOM BASELINE FACTORY REPAIR TEST
----------------------------------------------------------------------------------------------------
Created       : True
Object type   : RandomLegalMoveAgent
Expected type : RandomLegalMoveAgent
Seed supplied : 4805

THREE-BASELINE FACTORY VALIDATION
----------------------------------------------------------------------------------------------------

                  baseline  created           object_type error
0          Random Baseline     True  RandomLegalMoveAgent  None
1   Greedy Damage Baseline     True     GreedyDamageAgent  None
2  Depth-6 Search Baseline     True    SearchAgentAdapter  None

PREVIOUS SECTION 4C STATUS
----------------------------------------------------------------------------------------------------
Successful matches : 200
Failed matches     : 100
Accepted benchmark : False

SECTION 4C.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,Notebook 48 source parsed,True,True,True
1,historical tournament seed resolved,4804,4804,True
2,random baseline factory repaired,RandomLegalMoveAgent,RandomLegalMoveAgent,True
3,all three historical baselines instantiate,3,3,True
4,frozen R3 model remains 46 features,46,46,True
5,failed partial benchmark rejected,False,False,True

====================================================================================================
✅ RANDOM BASELINE SEED CONTRACT REPAIRED
✅ HISTORICAL TOURNAMENT SEED = 4804 VERIFIED
✅ RANDOM BASELINE NOW INSTANTIATES
✅ GREEDY DAMAGE BASELINE STILL INSTANTIATES
✅ DEPTH-6 SEARCH BASELINE STILL INSTANTIATES
✅ FROZEN R3 MODEL REMAINS 46 FEATURES
✅ FAILED 200/300 PARTIAL RUN IS NOT ACCEPTED
✅ SECTION 4C.1 COMPLETE
⚠️ NO RETRAINING
⚠️ NO MODEL MODIFICATION
➡️ NEXT: CLEAN RE-RUN OF ALL 300 MATCHES
====================================================================================================

In [ ]:
# ======================================================================================
# SECTION 4C.2 — CLEAN RE-RUN OF LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK
# ======================================================================================

from pathlib import Path
import dataclasses
import json
import time

import numpy as np
import pandas as pd


print("=" * 100)
print("SECTION 4C.2 — CLEAN RE-RUN OF LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK")
print("=" * 100)


# ======================================================================================
# 1. REQUIRED CONTRACT
# ======================================================================================

REQUIRED_OBJECTS_4C2 = [
    "R3TournamentAgentAdapter",
    "r3_policy_engine_3c2",
    "run_tournament_match",
    "create_random_baseline",
    "create_greedy_baseline",
    "create_search_baseline",
    "TournamentMatchResult",
    "TOURNAMENT_CARD_TEMPLATES",
    "full_schedule",
]

component_rows_4c2 = []

for object_name in REQUIRED_OBJECTS_4C2:
    obj = globals().get(object_name)

    component_rows_4c2.append(
        {
            "object": object_name,
            "available": obj is not None,
            "callable": callable(obj) if obj is not None else False,
            "object_type": (
                type(obj).__name__
                if obj is not None
                else "MISSING"
            ),
        }
    )

component_status_4c2_df = pd.DataFrame(
    component_rows_4c2
)

print("\nREQUIRED BENCHMARK COMPONENTS")
print("-" * 100)
display(component_status_4c2_df)

assert component_status_4c2_df[
    "available"
].all(), (
    "One or more required Section 4C.2 objects are missing."
)


# ======================================================================================
# 2. AUTHORITATIVE BENCHMARK CONSTANTS
# ======================================================================================

NOTEBOOK_48_RANDOM_SEED_4C2 = 4801
TOURNAMENT_RANDOM_SEED_4C2 = 4804

MATCHES_PER_BASELINE_4C2 = 100
MATCHES_PER_SIDE_PER_BASELINE_4C2 = 50
TOTAL_MATCHES_4C2 = 300
MAX_TURNS_4C2 = 50
SEARCH_DEPTH_4C2 = 6

BASELINE_NAMES_4C2 = [
    "Random Baseline",
    "Greedy Damage Baseline",
    "Depth-6 Search Baseline",
]

EXPECTED_R3_CLASSES_4C2 = [
    "Ascension",
    "Bind Down",
    "Live Coal",
    "Pass",
    "Quick Attack",
    "Tuck Tail",
]


print("\nAUTHORITATIVE BENCHMARK CONSTANTS")
print("-" * 100)
print(
    f"Notebook 48 general random seed : "
    f"{NOTEBOOK_48_RANDOM_SEED_4C2}"
)
print(
    f"Notebook 48 tournament seed     : "
    f"{TOURNAMENT_RANDOM_SEED_4C2}"
)
print(
    f"Matches per baseline            : "
    f"{MATCHES_PER_BASELINE_4C2}"
)
print(
    f"Matches per side/baseline       : "
    f"{MATCHES_PER_SIDE_PER_BASELINE_4C2}"
)
print(
    f"Total benchmark matches         : "
    f"{TOTAL_MATCHES_4C2}"
)
print(
    f"Maximum turns                   : "
    f"{MAX_TURNS_4C2}"
)
print(
    f"Search depth                    : "
    f"{SEARCH_DEPTH_4C2}"
)


# ======================================================================================
# 3. RE-VALIDATE FROZEN R3 CONTRACT
# ======================================================================================

r3_model_4c2 = r3_policy_engine_3c2.model

observed_feature_count_4c2 = int(
    r3_model_4c2.n_features_in_
)

observed_classes_4c2 = [
    str(value)
    for value in r3_model_4c2.classes_
]

print("\nFROZEN R3 CONTRACT")
print("-" * 100)
print(
    f"Model type       : "
    f"{type(r3_model_4c2).__name__}"
)
print(
    f"Feature count    : "
    f"{observed_feature_count_4c2}"
)
print(
    f"Classes          : "
    f"{observed_classes_4c2}"
)

assert observed_feature_count_4c2 == 46
assert observed_classes_4c2 == EXPECTED_R3_CLASSES_4C2


# ======================================================================================
# 4. CREATE FRESH R3 TOURNAMENT ADAPTER
# ======================================================================================

r3_tournament_agent_4c2 = (
    R3TournamentAgentAdapter(
        r3_policy_engine=
            r3_policy_engine_3c2,
    )
)

print("\nFROZEN R3 TOURNAMENT AGENT")
print("-" * 100)
print(
    f"Adapter type : "
    f"{type(r3_tournament_agent_4c2).__name__}"
)
print(
    f"Agent name   : "
    f"{r3_tournament_agent_4c2.name}"
)
print(
    f"Model type   : "
    f"{type(r3_tournament_agent_4c2.r3_policy_engine.model).__name__}"
)
print(
    f"Features     : "
    f"{int(r3_tournament_agent_4c2.r3_policy_engine.model.n_features_in_)}"
)


# ======================================================================================
# 5. VALIDATE LOCKED SCHEDULE
# ======================================================================================

assert isinstance(
    full_schedule,
    list,
)

assert len(
    full_schedule
) == TOTAL_MATCHES_4C2


required_schedule_fields_4c2 = {
    "baseline_name",
    "evaluated_agent_side",
    "starting_side",
    "player_card",
    "opponent_card",
}

schedule_rows_4c2 = []

for match_id_4c2, row_4c2 in enumerate(
    full_schedule,
    start=1,
):
    assert isinstance(
        row_4c2,
        dict,
    )

    missing_fields_4c2 = (
        required_schedule_fields_4c2
        - set(
            row_4c2.keys()
        )
    )

    assert not missing_fields_4c2, (
        f"Schedule row {match_id_4c2} "
        f"is missing fields: "
        f"{sorted(missing_fields_4c2)}"
    )

    schedule_rows_4c2.append(
        {
            "match_id": match_id_4c2,
            "baseline_name":
                row_4c2["baseline_name"],
            "evaluated_agent_side":
                row_4c2["evaluated_agent_side"],
            "starting_side":
                row_4c2["starting_side"],
            "player_card":
                row_4c2["player_card"]["name"],
            "opponent_card":
                row_4c2["opponent_card"]["name"],
        }
    )

schedule_4c2_df = pd.DataFrame(
    schedule_rows_4c2
)


print("\nLOCKED 300-MATCH SCHEDULE")
print("-" * 100)
print(
    f"Rows: "
    f"{len(schedule_4c2_df)}"
)

display(
    schedule_4c2_df.head(
        12
    )
)


baseline_distribution_4c2 = (
    schedule_4c2_df
    .groupby(
        "baseline_name"
    )
    .size()
    .rename(
        "matches"
    )
    .reset_index()
)

side_distribution_4c2 = (
    schedule_4c2_df
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ]
    )
    .size()
    .rename(
        "matches"
    )
    .reset_index()
)

starting_side_distribution_4c2 = (
    schedule_4c2_df
    .groupby(
        [
            "baseline_name",
            "starting_side",
        ]
    )
    .size()
    .rename(
        "matches"
    )
    .reset_index()
)


print("\nBASELINE DISTRIBUTION")
print("-" * 100)
display(
    baseline_distribution_4c2
)


print("\nEVALUATED-AGENT SIDE DISTRIBUTION")
print("-" * 100)
display(
    side_distribution_4c2
)


print("\nSTARTING-SIDE DISTRIBUTION")
print("-" * 100)
display(
    starting_side_distribution_4c2
)


for baseline_name_4c2 in BASELINE_NAMES_4C2:

    baseline_match_count_4c2 = int(
        (
            schedule_4c2_df[
                "baseline_name"
            ]
            == baseline_name_4c2
        ).sum()
    )

    assert (
        baseline_match_count_4c2
        == MATCHES_PER_BASELINE_4C2
    )

    for side_4c2 in [
        "Player",
        "Opponent",
    ]:

        evaluated_side_count_4c2 = int(
            (
                (
                    schedule_4c2_df[
                        "baseline_name"
                    ]
                    == baseline_name_4c2
                )
                &
                (
                    schedule_4c2_df[
                        "evaluated_agent_side"
                    ]
                    == side_4c2
                )
            ).sum()
        )

        starting_side_count_4c2 = int(
            (
                (
                    schedule_4c2_df[
                        "baseline_name"
                    ]
                    == baseline_name_4c2
                )
                &
                (
                    schedule_4c2_df[
                        "starting_side"
                    ]
                    == side_4c2
                )
            ).sum()
        )

        assert (
            evaluated_side_count_4c2
            == MATCHES_PER_SIDE_PER_BASELINE_4C2
        )

        assert (
            starting_side_count_4c2
            == MATCHES_PER_SIDE_PER_BASELINE_4C2
        )


# ======================================================================================
# 6. OUTPUT DIRECTORIES
# ======================================================================================

PROJECT_ROOT_4C2 = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

OUTPUT_DIR_4C2 = (
    PROJECT_ROOT_4C2
    / "outputs"
    / "notebook60"
)

REPORT_DIR_4C2 = (
    PROJECT_ROOT_4C2
    / "reports"
    / "notebook60"
)

ARTIFACT_DIR_4C2 = (
    PROJECT_ROOT_4C2
    / "artifacts"
    / "notebook60"
)

for directory_4c2 in [
    OUTPUT_DIR_4C2,
    REPORT_DIR_4C2,
    ARTIFACT_DIR_4C2,
]:
    directory_4c2.mkdir(
        parents=True,
        exist_ok=True,
    )


RAW_RESULTS_PATH_4C2 = (
    OUTPUT_DIR_4C2
    / "section4c2_r3_300_match_raw_results.csv"
)

FAILURES_PATH_4C2 = (
    REPORT_DIR_4C2
    / "section4c2_r3_300_match_failures.csv"
)

PROGRESS_PATH_4C2 = (
    OUTPUT_DIR_4C2
    / "section4c2_r3_300_match_progress.csv"
)

EXECUTION_SUMMARY_PATH_4C2 = (
    REPORT_DIR_4C2
    / "section4c2_r3_300_match_execution_summary.json"
)


print("\nCLEAN OUTPUT FILES")
print("-" * 100)
print(
    f"Raw results      : "
    f"{RAW_RESULTS_PATH_4C2}"
)
print(
    f"Failure report   : "
    f"{FAILURES_PATH_4C2}"
)
print(
    f"Progress file    : "
    f"{PROGRESS_PATH_4C2}"
)
print(
    f"Execution summary: "
    f"{EXECUTION_SUMMARY_PATH_4C2}"
)


# ======================================================================================
# 7. PROTECT AGAINST ACCIDENTAL RESUME / STALE RESULTS
# ======================================================================================

for stale_path_4c2 in [
    RAW_RESULTS_PATH_4C2,
    FAILURES_PATH_4C2,
    PROGRESS_PATH_4C2,
    EXECUTION_SUMMARY_PATH_4C2,
]:
    if stale_path_4c2.exists():
        stale_path_4c2.unlink()


print("\nCLEAN-RUN SAFETY")
print("-" * 100)
print(
    "Any existing Section 4C.2 result files "
    "were removed before execution."
)
print(
    "The previous failed Section 4C output "
    "will NOT be reused."
)


# ======================================================================================
# 8. BASELINE FACTORIES
# ======================================================================================

baseline_factories_4c2 = {
    "Random Baseline":
        lambda seed:
            create_random_baseline(
                seed
            ),

    "Greedy Damage Baseline":
        lambda seed:
            create_greedy_baseline(),

    "Depth-6 Search Baseline":
        lambda seed:
            create_search_baseline(),
}


factory_test_rows_4c2 = []

for baseline_index_4c2, baseline_name_4c2 in enumerate(
    BASELINE_NAMES_4C2,
    start=1,
):

    try:
        test_seed_4c2 = (
            TOURNAMENT_RANDOM_SEED_4C2
            + baseline_index_4c2
        )

        test_baseline_4c2 = (
            baseline_factories_4c2[
                baseline_name_4c2
            ](
                test_seed_4c2
            )
        )

        factory_test_rows_4c2.append(
            {
                "baseline":
                    baseline_name_4c2,
                "created":
                    True,
                "object_type":
                    type(
                        test_baseline_4c2
                    ).__name__,
                "seed_tested":
                    (
                        test_seed_4c2
                        if baseline_name_4c2
                        == "Random Baseline"
                        else None
                    ),
                "error":
                    None,
            }
        )

    except Exception as exc_4c2:

        factory_test_rows_4c2.append(
            {
                "baseline":
                    baseline_name_4c2,
                "created":
                    False,
                "object_type":
                    None,
                "seed_tested":
                    None,
                "error":
                    (
                        f"{type(exc_4c2).__name__}: "
                        f"{exc_4c2}"
                    ),
            }
        )


factory_test_4c2_df = pd.DataFrame(
    factory_test_rows_4c2
)

print("\nBASELINE FACTORY PREFLIGHT")
print("-" * 100)
display(
    factory_test_4c2_df
)

assert factory_test_4c2_df[
    "created"
].all()


# ======================================================================================
# 9. CLEAN 300-MATCH EXECUTION
# ======================================================================================

print("\n" + "=" * 100)
print("STARTING CLEAN LOCKED 300-MATCH BENCHMARK")
print("=" * 100)

print(
    "\nThis run starts from match 1."
)
print(
    "No result from the failed Section 4C run "
    "will be counted."
)
print(
    f"Historical tournament seed: "
    f"{TOURNAMENT_RANDOM_SEED_4C2}"
)
print(
    "Random baseline match seed = "
    "4804 + global match id."
)


benchmark_results_4c2 = []
benchmark_failures_4c2 = []

benchmark_start_4c2 = (
    time.perf_counter()
)


for global_match_id_4c2, scheduled_match_4c2 in enumerate(
    full_schedule,
    start=1,
):

    baseline_name_4c2 = (
        scheduled_match_4c2[
            "baseline_name"
        ]
    )

    evaluated_side_4c2 = (
        scheduled_match_4c2[
            "evaluated_agent_side"
        ]
    )

    starting_side_4c2 = (
        scheduled_match_4c2[
            "starting_side"
        ]
    )

    player_card_4c2 = (
        scheduled_match_4c2[
            "player_card"
        ]
    )

    opponent_card_4c2 = (
        scheduled_match_4c2[
            "opponent_card"
        ]
    )

    try:

        # --------------------------------------------------------------
        # Fresh frozen R3 adapter per match.
        # The RandomForest model itself remains unchanged.
        # --------------------------------------------------------------

        evaluated_agent_4c2 = (
            R3TournamentAgentAdapter(
                r3_policy_engine=
                    r3_policy_engine_3c2,
            )
        )

        # --------------------------------------------------------------
        # Exact Notebook 48 tournament-seed convention:
        # baseline_factory(TOURNAMENT_RANDOM_SEED + global_match_index)
        # --------------------------------------------------------------

        match_seed_4c2 = (
            TOURNAMENT_RANDOM_SEED_4C2
            + global_match_id_4c2
        )

        baseline_agent_4c2 = (
            baseline_factories_4c2[
                baseline_name_4c2
            ](
                match_seed_4c2
            )
        )

        result_4c2 = (
            run_tournament_match(
                match_id=
                    global_match_id_4c2,

                evaluated_agent=
                    evaluated_agent_4c2,

                baseline_agent=
                    baseline_agent_4c2,

                player_card=
                    player_card_4c2,

                opponent_card=
                    opponent_card_4c2,

                starting_side=
                    starting_side_4c2,

                evaluated_agent_side=
                    evaluated_side_4c2,

                max_turns=
                    MAX_TURNS_4C2,

                search_depth=
                    SEARCH_DEPTH_4C2,

                verbose=False,
            )
        )

        assert isinstance(
            result_4c2,
            TournamentMatchResult,
        )

        result_dict_4c2 = (
            dataclasses.asdict(
                result_4c2
            )
        )

        winner_4c2 = str(
            result_dict_4c2.get(
                "winner",
                "",
            )
        )

        if winner_4c2 == evaluated_side_4c2:
            r3_outcome_4c2 = "WIN"
            r3_score_4c2 = 1.0

        elif winner_4c2 in {
            "Player",
            "Opponent",
        }:
            r3_outcome_4c2 = "LOSS"
            r3_score_4c2 = 0.0

        else:
            r3_outcome_4c2 = "DRAW"
            r3_score_4c2 = 0.5


        result_dict_4c2.update(
            {
                "schedule_match_id":
                    global_match_id_4c2,

                "scheduled_baseline_name":
                    baseline_name_4c2,

                "scheduled_evaluated_agent_side":
                    evaluated_side_4c2,

                "scheduled_starting_side":
                    starting_side_4c2,

                "scheduled_player_card":
                    player_card_4c2[
                        "name"
                    ],

                "scheduled_opponent_card":
                    opponent_card_4c2[
                        "name"
                    ],

                "baseline_seed":
                    match_seed_4c2,

                "r3_outcome":
                    r3_outcome_4c2,

                "r3_score_reconstructed":
                    r3_score_4c2,

                "execution_success":
                    True,
            }
        )

        benchmark_results_4c2.append(
            result_dict_4c2
        )


    except Exception as exc_4c2:

        failure_row_4c2 = {
            "match_id":
                global_match_id_4c2,

            "baseline_name":
                baseline_name_4c2,

            "evaluated_agent_side":
                evaluated_side_4c2,

            "starting_side":
                starting_side_4c2,

            "player_card":
                player_card_4c2[
                    "name"
                ],

            "opponent_card":
                opponent_card_4c2[
                    "name"
                ],

            "baseline_seed":
                (
                    TOURNAMENT_RANDOM_SEED_4C2
                    + global_match_id_4c2
                ),

            "error_type":
                type(
                    exc_4c2
                ).__name__,

            "error":
                str(
                    exc_4c2
                ),
        }

        benchmark_failures_4c2.append(
            failure_row_4c2
        )

        print(
            f"\n❌ MATCH "
            f"{global_match_id_4c2} FAILED"
        )

        print(
            failure_row_4c2
        )


    # --------------------------------------------------------------
    # Progress checkpoint every 25 scheduled matches
    # --------------------------------------------------------------

    if (
        global_match_id_4c2 % 25 == 0
        or global_match_id_4c2
        == TOTAL_MATCHES_4C2
    ):

        elapsed_4c2 = (
            time.perf_counter()
            - benchmark_start_4c2
        )

        print(
            "\n"
            + "-" * 100
        )

        print(
            f"PROGRESS: "
            f"{global_match_id_4c2}"
            f"/{TOTAL_MATCHES_4C2} scheduled"
        )

        print(
            f"Successful: "
            f"{len(benchmark_results_4c2)}"
        )

        print(
            f"Failed    : "
            f"{len(benchmark_failures_4c2)}"
        )

        print(
            f"Elapsed   : "
            f"{elapsed_4c2:.2f} seconds"
        )

        print(
            "-" * 100
        )


        progress_row_4c2 = pd.DataFrame(
            [
                {
                    "scheduled_matches":
                        global_match_id_4c2,

                    "successful_matches":
                        len(
                            benchmark_results_4c2
                        ),

                    "failed_matches":
                        len(
                            benchmark_failures_4c2
                        ),

                    "elapsed_seconds":
                        elapsed_4c2,
                }
            ]
        )

        progress_row_4c2.to_csv(
            PROGRESS_PATH_4C2,
            mode="a",
            header=(
                not PROGRESS_PATH_4C2.exists()
            ),
            index=False,
        )


# ======================================================================================
# 10. EXECUTION COMPLETE
# ======================================================================================

benchmark_elapsed_4c2 = (
    time.perf_counter()
    - benchmark_start_4c2
)

successful_match_count_4c2 = len(
    benchmark_results_4c2
)

failed_match_count_4c2 = len(
    benchmark_failures_4c2
)


print("\n" + "=" * 100)
print("CLEAN 300-MATCH EXECUTION FINISHED")
print("=" * 100)

print(
    f"Scheduled matches : "
    f"{TOTAL_MATCHES_4C2}"
)

print(
    f"Successful matches: "
    f"{successful_match_count_4c2}"
)

print(
    f"Failed matches    : "
    f"{failed_match_count_4c2}"
)

print(
    f"Elapsed seconds   : "
    f"{benchmark_elapsed_4c2:.4f}"
)


# ======================================================================================
# 11. SAVE RAW RESULTS AND FAILURES
# ======================================================================================

benchmark_results_4c2_df = pd.DataFrame(
    benchmark_results_4c2
)

benchmark_failures_4c2_df = pd.DataFrame(
    benchmark_failures_4c2
)


benchmark_results_4c2_df.to_csv(
    RAW_RESULTS_PATH_4C2,
    index=False,
)


benchmark_failures_4c2_df.to_csv(
    FAILURES_PATH_4C2,
    index=False,
)


print("\nRAW RESULT PREVIEW")
print("-" * 100)

if not benchmark_results_4c2_df.empty:
    display(
        benchmark_results_4c2_df.head(
            20
        )
    )
else:
    print(
        "No successful result rows."
    )


print("\nFAILURE REPORT")
print("-" * 100)

if benchmark_failures_4c2_df.empty:
    print(
        "No execution failures."
    )
else:
    display(
        benchmark_failures_4c2_df
    )


# ======================================================================================
# 12. VALIDATION — DO NOT CALCULATE FINAL METRICS UNLESS ALL 300 PASS
# ======================================================================================

section4c2_validation_rows = [
    {
        "validation":
            "exactly 300 scheduled matches",

        "observed":
            TOTAL_MATCHES_4C2,

        "expected":
            300,

        "passed":
            TOTAL_MATCHES_4C2
            == 300,
    },

    {
        "validation":
            "all 300 benchmark matches succeeded",

        "observed":
            successful_match_count_4c2,

        "expected":
            300,

        "passed":
            successful_match_count_4c2
            == 300,
    },

    {
        "validation":
            "zero execution failures",

        "observed":
            failed_match_count_4c2,

        "expected":
            0,

        "passed":
            failed_match_count_4c2
            == 0,
    },

    {
        "validation":
            "exactly 300 raw result rows",

        "observed":
            len(
                benchmark_results_4c2_df
            ),

        "expected":
            300,

        "passed":
            len(
                benchmark_results_4c2_df
            )
            == 300,
    },

    {
        "validation":
            "frozen R3 remains 46 features",

        "observed":
            int(
                r3_model_4c2.n_features_in_
            ),

        "expected":
            46,

        "passed":
            int(
                r3_model_4c2.n_features_in_
            )
            == 46,
    },

    {
        "validation":
            "frozen six-class action order unchanged",

        "observed":
            [
                str(value)
                for value
                in r3_model_4c2.classes_
            ],

        "expected":
            EXPECTED_R3_CLASSES_4C2,

        "passed":
            [
                str(value)
                for value
                in r3_model_4c2.classes_
            ]
            == EXPECTED_R3_CLASSES_4C2,
    },

    {
        "validation":
            "historical tournament seed is 4804",

        "observed":
            TOURNAMENT_RANDOM_SEED_4C2,

        "expected":
            4804,

        "passed":
            TOURNAMENT_RANDOM_SEED_4C2
            == 4804,
    },
]


section4c2_validation_df = pd.DataFrame(
    section4c2_validation_rows
)

SECTION_4C2_COMPLETE = bool(
    section4c2_validation_df[
        "passed"
    ].all()
)


execution_summary_4c2 = {
    "notebook":
        60,

    "section":
        "4C.2",

    "benchmark":
        "clean_locked_300_match_r3_side_neutral",

    "scheduled_matches":
        TOTAL_MATCHES_4C2,

    "successful_matches":
        successful_match_count_4c2,

    "failed_matches":
        failed_match_count_4c2,

    "elapsed_seconds":
        benchmark_elapsed_4c2,

    "historical_random_seed":
        NOTEBOOK_48_RANDOM_SEED_4C2,

    "historical_tournament_seed":
        TOURNAMENT_RANDOM_SEED_4C2,

    "matches_per_baseline":
        MATCHES_PER_BASELINE_4C2,

    "matches_per_side_per_baseline":
        MATCHES_PER_SIDE_PER_BASELINE_4C2,

    "feature_count":
        int(
            r3_model_4c2.n_features_in_
        ),

    "classes":
        [
            str(value)
            for value
            in r3_model_4c2.classes_
        ],

    "r3_retraining":
        False,

    "r3_model_modification":
        False,

    "benchmark_accepted":
        SECTION_4C2_COMPLETE,
}


with open(
    EXECUTION_SUMMARY_PATH_4C2,
    "w",
    encoding="utf-8",
) as file_4c2:
    json.dump(
        execution_summary_4c2,
        file_4c2,
        indent=2,
    )


print("\nSECTION 4C.2 VALIDATION")
print("-" * 100)

display(
    section4c2_validation_df
)


print("\n" + "=" * 100)

if SECTION_4C2_COMPLETE:

    print(
        "✅ ALL 300 LOCKED BENCHMARK MATCHES EXECUTED SUCCESSFULLY"
    )

    print(
        "✅ ZERO EXECUTION FAILURES"
    )

    print(
        "✅ HISTORICAL TOURNAMENT SEED 4804 USED"
    )

    print(
        "✅ RANDOM BASELINE MATCH SEEDS USE 4804 + MATCH_ID"
    )

    print(
        "✅ EXACT NOTEBOOK 48 SIDE-BALANCED SCHEDULE PRESERVED"
    )

    print(
        "✅ FROZEN R3 46-FEATURE MODEL PRESERVED"
    )

    print(
        "✅ SIX-CLASS ACTION CONTRACT PRESERVED"
    )

    print(
        "✅ NO R3 RETRAINING"
    )

    print(
        "✅ NO R3 MODEL MODIFICATION"
    )

    print(
        "✅ SECTION 4C.2 COMPLETE"
    )

    print(
        "➡️ NEXT: CALCULATE FINAL 300-MATCH BENCHMARK METRICS"
    )

else:

    print(
        "❌ SECTION 4C.2 IS NOT ACCEPTED"
    )

    print(
        "❌ DO NOT CALCULATE FINAL BENCHMARK METRICS"
    )

    print(
        "Inspect the failure table above before continuing."
    )


print("=" * 100)


assert SECTION_4C2_COMPLETE, (
    "Section 4C.2 clean execution did not produce "
    "300 successful matches with zero failures. "
    "Do not calculate final benchmark metrics yet."
)

====================================================================================================
SECTION 4C.2 — CLEAN RE-RUN OF LOCKED 300-MATCH R3 SIDE-NEUTRAL BENCHMARK
====================================================================================================

REQUIRED BENCHMARK COMPONENTS
----------------------------------------------------------------------------------------------------

                      object  available  callable         object_type
0   R3TournamentAgentAdapter       True      True                type
1       r3_policy_engine_3c2       True     False  R3LivePolicyEngine
2       run_tournament_match       True      True            function
3     create_random_baseline       True      True            function
4     create_greedy_baseline       True      True            function
5     create_search_baseline       True      True            function
6      TournamentMatchResult       True      True                type
7  TOURNAMENT_CARD_TEMPLATES       True     False                list
8              full_schedule       True     False                list

AUTHORITATIVE BENCHMARK CONSTANTS
----------------------------------------------------------------------------------------------------
Notebook 48 general random seed : 4801
Notebook 48 tournament seed     : 4804
Matches per baseline            : 100
Matches per side/baseline       : 50
Total benchmark matches         : 300
Maximum turns                   : 50
Search depth                    : 6

FROZEN R3 CONTRACT
----------------------------------------------------------------------------------------------------
Model type       : RandomForestClassifier
Feature count    : 46
Classes          : ['Ascension', 'Bind Down', 'Live Coal', 'Pass', 'Quick Attack', 'Tuck Tail']

FROZEN R3 TOURNAMENT AGENT
----------------------------------------------------------------------------------------------------
Adapter type : R3TournamentAgentAdapter
Agent name   : R3_STATE_CENTRIC_POLICY
Model type   : RandomForestClassifier
Features     : 46

LOCKED 300-MATCH SCHEDULE
----------------------------------------------------------------------------------------------------
Rows: 300

,match_id,baseline_name,evaluated_agent_side,starting_side,player_card,opponent_card
0,1,Random Baseline,Player,Player,Pikachu,Charmander
1,2,Random Baseline,Opponent,Player,Charmander,Eevee
2,3,Random Baseline,Player,Opponent,Squirtle,Charmander
3,4,Random Baseline,Opponent,Opponent,Bulbasaur,Eevee
4,5,Random Baseline,Player,Player,Eevee,Charmander
5,6,Random Baseline,Opponent,Player,Meowth,Eevee
6,7,Random Baseline,Player,Opponent,Pikachu,Charmander
7,8,Random Baseline,Opponent,Opponent,Charmander,Eevee
8,9,Random Baseline,Player,Player,Squirtle,Charmander
9,10,Random Baseline,Opponent,Player,Bulbasaur,Eevee
10,11,Random Baseline,Player,Opponent,Eevee,Charmander
11,12,Random Baseline,Opponent,Opponent,Meowth,Eevee

BASELINE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name  matches
0  Depth-6 Search Baseline      100
1   Greedy Damage Baseline      100
2          Random Baseline      100

EVALUATED-AGENT SIDE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name evaluated_agent_side  matches
0  Depth-6 Search Baseline             Opponent       50
1  Depth-6 Search Baseline               Player       50
2   Greedy Damage Baseline             Opponent       50
3   Greedy Damage Baseline               Player       50
4          Random Baseline             Opponent       50
5          Random Baseline               Player       50

STARTING-SIDE DISTRIBUTION
----------------------------------------------------------------------------------------------------

             baseline_name starting_side  matches
0  Depth-6 Search Baseline      Opponent       50
1  Depth-6 Search Baseline        Player       50
2   Greedy Damage Baseline      Opponent       50
3   Greedy Damage Baseline        Player       50
4          Random Baseline      Opponent       50
5          Random Baseline        Player       50

CLEAN OUTPUT FILES
----------------------------------------------------------------------------------------------------
Raw results      : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c2_r3_300_match_raw_results.csv
Failure report   : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c2_r3_300_match_failures.csv
Progress file    : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c2_r3_300_match_progress.csv
Execution summary: D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c2_r3_300_match_execution_summary.json

CLEAN-RUN SAFETY
----------------------------------------------------------------------------------------------------
Any existing Section 4C.2 result files were removed before execution.
The previous failed Section 4C output will NOT be reused.

BASELINE FACTORY PREFLIGHT
----------------------------------------------------------------------------------------------------

                  baseline  created           object_type  seed_tested error
0          Random Baseline     True  RandomLegalMoveAgent       4805.0  None
1   Greedy Damage Baseline     True     GreedyDamageAgent          NaN  None
2  Depth-6 Search Baseline     True    SearchAgentAdapter          NaN  None

====================================================================================================
STARTING CLEAN LOCKED 300-MATCH BENCHMARK
====================================================================================================

This run starts from match 1.
No result from the failed Section 4C run will be counted.
Historical tournament seed: 4804
Random baseline match seed = 4804 + global match id.

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 25/300 scheduled
Successful: 25
Failed    : 0
Elapsed   : 5.22 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 50/300 scheduled
Successful: 50
Failed    : 0
Elapsed   : 10.81 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 75/300 scheduled
Successful: 75
Failed    : 0
Elapsed   : 16.09 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 100/300 scheduled
Successful: 100
Failed    : 0
Elapsed   : 21.26 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 125/300 scheduled
Successful: 125
Failed    : 0
Elapsed   : 25.13 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 150/300 scheduled
Successful: 150
Failed    : 0
Elapsed   : 29.08 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 175/300 scheduled
Successful: 175
Failed    : 0
Elapsed   : 33.04 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

----------------------------------------------------------------------------------------------------
PROGRESS: 200/300 scheduled
Successful: 200
Failed    : 0
Elapsed   : 37.51 seconds
----------------------------------------------------------------------------------------------------

D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\.venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

# SECTION 4D — LOCKED 300-MATCH R3 BENCHMARK ACCEPTANCE RECORD

## 4D.1 Purpose

This section formally documents and accepts the completed Section 4C.2 clean, locked, side-neutral benchmark of the frozen R3 tournament agent.

The purpose of this record is to establish a reproducible audit trail confirming that the authoritative 300-match benchmark completed successfully and that no model retraining, feature modification, or policy modification occurred during the benchmark.

---

## 4D.2 Authoritative Benchmark Configuration

The Section 4C.2 benchmark used the historical Notebook 48 tournament configuration recovered and validated in Section 4C.1.

| Benchmark Property | Locked Value |
|---|---:|
| Evaluated agent | `R3_STATE_CENTRIC_POLICY` |
| Model type | `RandomForestClassifier` |
| Frozen feature count | `46` |
| Historical general random seed | `4801` |
| Historical tournament random seed | `4804` |
| Baselines evaluated | `3` |
| Matches per baseline | `100` |
| Evaluated-agent Player-side matches per baseline | `50` |
| Evaluated-agent Opponent-side matches per baseline | `50` |
| Total scheduled matches | `300` |
| Maximum turns per match | `50` |
| Depth-6 search depth | `6` |
| Model retraining | `False` |
| Model modification | `False` |

### Frozen R3 Action-Class Contract

The frozen R3 classifier retained the following six action classes throughout the benchmark:

1. `Ascension`
2. `Bind Down`
3. `Live Coal`
4. `Pass`
5. `Quick Attack`
6. `Tuck Tail`

No feature, class, estimator, or trained-model modification was performed for this benchmark.

---

## 4D.3 Baseline Composition

The locked benchmark consisted of exactly 100 matches against each of the following historical baselines:

- **Random Baseline**
- **Greedy Damage Baseline**
- **Depth-6 Search Baseline**

For every baseline, the evaluated R3 agent was assigned to each battle side exactly 50 times.

The benchmark therefore contained:

- 100 Random Baseline matches
- 100 Greedy Damage Baseline matches
- 100 Depth-6 Search Baseline matches
- **300 total matches**

This preserves the intended side-neutral evaluation contract.

---

## 4D.4 Execution Result

The clean Section 4C.2 benchmark completed successfully.

| Execution Metric | Result |
|---|---:|
| Scheduled matches | `300` |
| Successful matches | `300` |
| Failed matches | `0` |
| Raw-result rows persisted | `300` |
| Final progress checkpoint | `300 / 300` |
| Approximate benchmark execution time | `65.57 seconds` |
| Benchmark accepted | `True` |

The failure report contains **zero failure records**.

The raw-results artifact contains all scheduled matches through **match_id 300**, confirming that the persisted benchmark dataset is complete.

---

## 4D.5 Execution Observability Incident

During interactive execution in JupyterLab, the visible notebook output appeared to remain at:

`PROGRESS: 200/300 scheduled`

while repeated `scikit-learn` parallel-processing `UserWarning` messages continued to appear.

At the time, this behavior appeared consistent with a possible stall during the Depth-6 Search Baseline portion of the benchmark.

The associated Python worker processes continued to exist, and the JupyterLab browser interface eventually experienced a server-connection issue.

The worker processes were subsequently terminated after the notebook could no longer be reliably controlled through the Jupyter interface.

### Post-Execution Verification

The persisted Section 4C.2 artifacts were inspected independently through PowerShell after JupyterLab was restored.

That verification established that the benchmark had, in fact, completed before termination of the remaining processes.

The following facts were confirmed directly from the persisted artifacts:

- Raw-results CSV contained exactly **300 rows**.
- Final raw-result record was **match_id 300**.
- Progress checkpoints continued beyond the last visibly observed `200/300` state.
- Progress records were present for:
  - `225/300`
  - `250/300`
  - `275/300`
  - `300/300`
- Final progress record reported:
  - `300` scheduled
  - `300` successful
  - `0` failed
- Failure report contained **0 rows**.
- Execution-summary JSON reported:
  - `"scheduled_matches": 300`
  - `"successful_matches": 300`
  - `"failed_matches": 0`
  - `"benchmark_accepted": true`
- The execution summary recorded approximately **65.57 seconds** of benchmark execution time.

Therefore, the apparent `200/300` stall was **not a benchmark execution failure**.

It is classified as a **Jupyter/output observability issue associated with repeated parallel-processing warning output**, while the underlying benchmark continued and completed successfully.

No benchmark matches need to be repeated because the complete authoritative results were persisted to disk.

---

## 4D.6 Authoritative Evidence Artifacts

The following Section 4C.2 files constitute the authoritative evidence set for the clean 300-match benchmark.

### Raw Benchmark Results

`outputs/notebook60/section4c2_r3_300_match_raw_results.csv`

Contains the complete match-level results for all **300 matches**.

### Benchmark Progress Log

`outputs/notebook60/section4c2_r3_300_match_progress.csv`

Contains execution checkpoints through **300/300 successful matches**.

### Failure Report

`reports/notebook60/section4c2_r3_300_match_failures.csv`

Contains **zero failure records**.

### Execution Summary

`reports/notebook60/section4c2_r3_300_match_execution_summary.json`

Records the final benchmark execution contract and confirms:

`"benchmark_accepted": true`

---

## 4D.7 Superseded Partial Benchmark Artifacts

Files beginning with:

`section4c_r3_300_match_*`

belong to the earlier incomplete Section 4C execution and are retained only for historical/debugging provenance.

That earlier execution reached only:

- `200` successful matches
- `100` uncompleted matches
- benchmark acceptance = `False`

Those artifacts **MUST NOT** be used for final R3 performance calculations.

All subsequent Notebook 60 benchmark analysis must use only the clean Section 4C.2 artifacts beginning with:

`section4c2_r3_300_match_*`

---

## 4D.8 Benchmark Integrity Decision

**SECTION 4C.2 BENCHMARK STATUS: ACCEPTED**

The locked R3 benchmark satisfies the required execution contract:

- [x] Historical benchmark seeds recovered and preserved
- [x] Historical tournament seed `4804` preserved
- [x] General random seed `4801` preserved
- [x] Three historical baselines instantiated
- [x] 100 matches executed per baseline
- [x] 50 Player-side evaluations per baseline
- [x] 50 Opponent-side evaluations per baseline
- [x] 300 total matches completed
- [x] 300 successful match executions
- [x] 0 failed match executions
- [x] Frozen R3 model retained 46 features
- [x] Frozen six-class action contract preserved
- [x] No R3 retraining performed
- [x] No R3 model modification performed
- [x] Complete raw results persisted
- [x] Complete progress record persisted
- [x] Failure report verified empty
- [x] Execution summary reports `benchmark_accepted = true`

### Final Acceptance Statement

The Section 4C.2 clean locked 300-match R3 side-neutral benchmark is formally accepted as the authoritative Notebook 60 evaluation run.

The complete persisted Section 4C.2 dataset will be used for all subsequent performance calculations, baseline comparisons, side-neutral analysis, historical comparisons, and final competitive benchmark conclusions.

**No rerun of the 300-match benchmark is required.**

In [2]:
# ============================================================
# SECTION 4D.1 — VERIFY AUTHORITATIVE 300-MATCH ACCEPTANCE
# ============================================================
#
# PURPOSE
# -------
# Independently reload the persisted Section 4C.2 benchmark
# artifacts and verify that the authoritative clean benchmark
# completed exactly as required.
#
# IMPORTANT
# ---------
# - NO matches are executed here.
# - NO model is loaded or modified here.
# - NO retraining occurs here.
# - The verification is performed entirely from persisted
#   Section 4C.2 artifacts.
# ============================================================

from pathlib import Path
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Resolve project root
# ------------------------------------------------------------

cwd_4d1 = Path.cwd().resolve()

if cwd_4d1.name.lower() == "notebooks":
    project_root_4d1 = cwd_4d1.parent
else:
    project_root_4d1 = cwd_4d1

print("=" * 100)
print("SECTION 4D.1 — AUTHORITATIVE BENCHMARK ACCEPTANCE VERIFICATION")
print("=" * 100)

print()
print("Project root:")
print(project_root_4d1)


# ------------------------------------------------------------
# 2. Authoritative Section 4C.2 artifact paths
# ------------------------------------------------------------

raw_results_path_4d1 = (
    project_root_4d1
    / "outputs"
    / "notebook60"
    / "section4c2_r3_300_match_raw_results.csv"
)

progress_path_4d1 = (
    project_root_4d1
    / "outputs"
    / "notebook60"
    / "section4c2_r3_300_match_progress.csv"
)

failure_path_4d1 = (
    project_root_4d1
    / "reports"
    / "notebook60"
    / "section4c2_r3_300_match_failures.csv"
)

summary_path_4d1 = (
    project_root_4d1
    / "reports"
    / "notebook60"
    / "section4c2_r3_300_match_execution_summary.json"
)


artifact_paths_4d1 = {
    "raw_results": raw_results_path_4d1,
    "progress": progress_path_4d1,
    "failures": failure_path_4d1,
    "execution_summary": summary_path_4d1,
}


print()
print("AUTHORITATIVE ARTIFACTS")
print("-" * 100)

for artifact_name_4d1, artifact_path_4d1 in artifact_paths_4d1.items():
    print(
        f"{artifact_name_4d1:<20}: "
        f"{artifact_path_4d1} "
        f"[exists={artifact_path_4d1.exists()}]"
    )


# ------------------------------------------------------------
# 3. Require all authoritative artifacts
# ------------------------------------------------------------

missing_artifacts_4d1 = [
    str(path_4d1)
    for path_4d1 in artifact_paths_4d1.values()
    if not path_4d1.exists()
]

assert not missing_artifacts_4d1, (
    "Missing authoritative Section 4C.2 artifacts:\n"
    + "\n".join(missing_artifacts_4d1)
)


# ------------------------------------------------------------
# 4. Load persisted benchmark evidence
# ------------------------------------------------------------

raw_results_4d1 = pd.read_csv(
    raw_results_path_4d1
)

progress_4d1 = pd.read_csv(
    progress_path_4d1
)

# Failure report may be a completely empty file when
# the benchmark completes with zero failures.
try:
    failures_4d1 = pd.read_csv(
        failure_path_4d1
    )
except pd.errors.EmptyDataError:
    failures_4d1 = pd.DataFrame()
with open(
    summary_path_4d1,
    "r",
    encoding="utf-8",
) as summary_file_4d1:
    execution_summary_4d1 = json.load(
        summary_file_4d1
    )


# ------------------------------------------------------------
# 5. Extract authoritative observations
# ------------------------------------------------------------

raw_row_count_4d1 = len(
    raw_results_4d1
)

unique_match_ids_4d1 = (
    raw_results_4d1["match_id"]
    .nunique()
)

minimum_match_id_4d1 = int(
    raw_results_4d1["match_id"].min()
)

maximum_match_id_4d1 = int(
    raw_results_4d1["match_id"].max()
)

failure_count_4d1 = len(
    failures_4d1
)

final_progress_4d1 = (
    progress_4d1
    .iloc[-1]
)

final_scheduled_4d1 = int(
    final_progress_4d1[
        "scheduled_matches"
    ]
)

final_successful_4d1 = int(
    final_progress_4d1[
        "successful_matches"
    ]
)

final_failed_4d1 = int(
    final_progress_4d1[
        "failed_matches"
    ]
)

summary_scheduled_4d1 = int(
    execution_summary_4d1[
        "scheduled_matches"
    ]
)

summary_successful_4d1 = int(
    execution_summary_4d1[
        "successful_matches"
    ]
)

summary_failed_4d1 = int(
    execution_summary_4d1[
        "failed_matches"
    ]
)

benchmark_accepted_4d1 = bool(
    execution_summary_4d1[
        "benchmark_accepted"
    ]
)

feature_count_4d1 = int(
    execution_summary_4d1[
        "feature_count"
    ]
)

r3_retraining_4d1 = bool(
    execution_summary_4d1[
        "r3_retraining"
    ]
)

r3_model_modification_4d1 = bool(
    execution_summary_4d1[
        "r3_model_modification"
    ]
)


# ------------------------------------------------------------
# 6. Baseline distribution
# ------------------------------------------------------------

baseline_counts_4d1 = (
    raw_results_4d1[
        "baseline_name"
    ]
    .value_counts()
    .sort_index()
)

print()
print("BASELINE MATCH COUNTS")
print("-" * 100)

print(
    baseline_counts_4d1.to_string()
)


# ------------------------------------------------------------
# 7. Evaluated-side distribution
# ------------------------------------------------------------

if "evaluated_agent_side" in raw_results_4d1.columns:

    side_counts_4d1 = (
        raw_results_4d1
        .groupby(
            [
                "baseline_name",
                "evaluated_agent_side",
            ]
        )
        .size()
        .rename(
            "matches"
        )
        .reset_index()
    )

    print()
    print("SIDE-BALANCED MATCH COUNTS")
    print("-" * 100)

    print(
        side_counts_4d1.to_string(
            index=False
        )
    )

else:

    side_counts_4d1 = pd.DataFrame()

    print()
    print(
        "NOTE: evaluated_agent_side is not present "
        "in the persisted raw-results schema."
    )


# ------------------------------------------------------------
# 8. Formal validation table
# ------------------------------------------------------------

validation_rows_4d1 = [
    {
        "validation":
            "raw result rows",
        "observed":
            raw_row_count_4d1,
        "expected":
            300,
        "passed":
            raw_row_count_4d1 == 300,
    },
    {
        "validation":
            "unique match IDs",
        "observed":
            unique_match_ids_4d1,
        "expected":
            300,
        "passed":
            unique_match_ids_4d1 == 300,
    },
    {
        "validation":
            "minimum match ID",
        "observed":
            minimum_match_id_4d1,
        "expected":
            1,
        "passed":
            minimum_match_id_4d1 == 1,
    },
    {
        "validation":
            "maximum match ID",
        "observed":
            maximum_match_id_4d1,
        "expected":
            300,
        "passed":
            maximum_match_id_4d1 == 300,
    },
    {
        "validation":
            "progress scheduled",
        "observed":
            final_scheduled_4d1,
        "expected":
            300,
        "passed":
            final_scheduled_4d1 == 300,
    },
    {
        "validation":
            "progress successful",
        "observed":
            final_successful_4d1,
        "expected":
            300,
        "passed":
            final_successful_4d1 == 300,
    },
    {
        "validation":
            "progress failed",
        "observed":
            final_failed_4d1,
        "expected":
            0,
        "passed":
            final_failed_4d1 == 0,
    },
    {
        "validation":
            "failure report rows",
        "observed":
            failure_count_4d1,
        "expected":
            0,
        "passed":
            failure_count_4d1 == 0,
    },
    {
        "validation":
            "summary scheduled",
        "observed":
            summary_scheduled_4d1,
        "expected":
            300,
        "passed":
            summary_scheduled_4d1 == 300,
    },
    {
        "validation":
            "summary successful",
        "observed":
            summary_successful_4d1,
        "expected":
            300,
        "passed":
            summary_successful_4d1 == 300,
    },
    {
        "validation":
            "summary failed",
        "observed":
            summary_failed_4d1,
        "expected":
            0,
        "passed":
            summary_failed_4d1 == 0,
    },
    {
        "validation":
            "frozen R3 feature count",
        "observed":
            feature_count_4d1,
        "expected":
            46,
        "passed":
            feature_count_4d1 == 46,
    },
    {
        "validation":
            "R3 retraining disabled",
        "observed":
            r3_retraining_4d1,
        "expected":
            False,
        "passed":
            r3_retraining_4d1 is False,
    },
    {
        "validation":
            "R3 modification disabled",
        "observed":
            r3_model_modification_4d1,
        "expected":
            False,
        "passed":
            r3_model_modification_4d1 is False,
    },
    {
        "validation":
            "benchmark accepted",
        "observed":
            benchmark_accepted_4d1,
        "expected":
            True,
        "passed":
            benchmark_accepted_4d1 is True,
    },
]


# Validate exactly 100 matches per baseline.

expected_baselines_4d1 = {
    "Depth-6 Search Baseline",
    "Greedy Damage Baseline",
    "Random Baseline",
}

observed_baselines_4d1 = set(
    baseline_counts_4d1.index
)

baseline_contract_passed_4d1 = (
    observed_baselines_4d1
    == expected_baselines_4d1
    and all(
        int(count_4d1) == 100
        for count_4d1
        in baseline_counts_4d1.values
    )
)

validation_rows_4d1.append(
    {
        "validation":
            "100 matches per historical baseline",
        "observed":
            baseline_counts_4d1.to_dict(),
        "expected":
            "100 each",
        "passed":
            baseline_contract_passed_4d1,
    }
)


validation_4d1 = pd.DataFrame(
    validation_rows_4d1
)


print()
print("SECTION 4D.1 VALIDATION")
print("-" * 100)

display(
    validation_4d1
)


# ------------------------------------------------------------
# 9. Final acceptance gate
# ------------------------------------------------------------

all_validations_passed_4d1 = bool(
    validation_4d1[
        "passed"
    ].all()
)

assert all_validations_passed_4d1, (
    "Section 4D.1 acceptance verification failed. "
    "Do not proceed to benchmark performance analysis."
)


print()
print("=" * 100)
print(
    "✅ SECTION 4D.1 ACCEPTANCE VERIFIED"
)
print(
    "✅ 300 / 300 AUTHORITATIVE MATCHES RECOVERED"
)
print(
    "✅ 0 BENCHMARK FAILURES"
)
print(
    "✅ THREE HISTORICAL BASELINES × 100 MATCHES"
)
print(
    "✅ FROZEN 46-FEATURE R3 CONTRACT PRESERVED"
)
print(
    "✅ NO R3 RETRAINING"
)
print(
    "✅ NO R3 MODEL MODIFICATION"
)
print(
    "✅ SECTION 4C.2 IS THE AUTHORITATIVE BENCHMARK"
)
print("=" * 100)

====================================================================================================
SECTION 4D.1 — AUTHORITATIVE BENCHMARK ACCEPTANCE VERIFICATION
====================================================================================================

Project root:
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge

AUTHORITATIVE ARTIFACTS
----------------------------------------------------------------------------------------------------
raw_results         : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c2_r3_300_match_raw_results.csv [exists=True]
progress            : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c2_r3_300_match_progress.csv [exists=True]
failures            : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c2_r3_300_match_failures.csv [exists=True]
execution_summary   : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c2_r3_300_match_execution_summary.json [exists=True]

BASELINE MATCH COUNTS
----------------------------------------------------------------------------------------------------
baseline_name
Depth-6 Search Baseline    100
Greedy Damage Baseline     100
Random Baseline            100

NOTE: evaluated_agent_side is not present in the persisted raw-results schema.

SECTION 4D.1 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,raw result rows,300,300,True
1,unique match IDs,300,300,True
2,minimum match ID,1,1,True
3,maximum match ID,300,300,True
4,progress scheduled,300,300,True
5,progress successful,300,300,True
6,progress failed,0,0,True
7,failure report rows,0,0,True
8,summary scheduled,300,300,True
9,summary successful,300,300,True
10,summary failed,0,0,True
11,frozen R3 feature count,46,46,True
12,R3 retraining disabled,False,False,True
13,R3 modification disabled,False,False,True
14,benchmark accepted,True,True,True
15,100 matches per historical baseline,"{'Depth-6 Search Baseline': 100, 'Greedy Damag...",100 each,True

====================================================================================================
✅ SECTION 4D.1 ACCEPTANCE VERIFIED
✅ 300 / 300 AUTHORITATIVE MATCHES RECOVERED
✅ 0 BENCHMARK FAILURES
✅ THREE HISTORICAL BASELINES × 100 MATCHES
✅ FROZEN 46-FEATURE R3 CONTRACT PRESERVED
✅ NO R3 RETRAINING
✅ NO R3 MODEL MODIFICATION
✅ SECTION 4C.2 IS THE AUTHORITATIVE BENCHMARK
====================================================================================================

In [4]:
# ============================================================
# SECTION 4D.2 — AUTHORITATIVE R3 PERFORMANCE RECONSTRUCTION
# ============================================================
#
# PURPOSE
# -------
# Calculate the final accepted R3 benchmark performance from
# the persisted 300-match Section 4C.2 benchmark.
#
# IMPORTANT
# ---------
# - NO battles are executed.
# - NO model modification.
# - NO retraining.
# - Uses only the accepted Section 4C.2 results.
# - Reconstructs evaluated-agent side from the locked schedule.
# ============================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Resolve project root
# ------------------------------------------------------------

cwd_4d2 = Path.cwd().resolve()

if cwd_4d2.name.lower() == "notebooks":
    project_root_4d2 = cwd_4d2.parent
else:
    project_root_4d2 = cwd_4d2


print("=" * 100)
print("SECTION 4D.2 — AUTHORITATIVE R3 PERFORMANCE RECONSTRUCTION")
print("=" * 100)


# ------------------------------------------------------------
# 2. Authoritative accepted benchmark files
# ------------------------------------------------------------

raw_path_4d2 = (
    project_root_4d2
    / "outputs"
    / "notebook60"
    / "section4c2_r3_300_match_raw_results.csv"
)

summary_path_4d2 = (
    project_root_4d2
    / "reports"
    / "notebook60"
    / "section4c2_r3_300_match_execution_summary.json"
)

locked_schedule_path_4d2 = (
    project_root_4d2
    / "reports"
    / "notebook60"
    / "section4b_locked_300_match_schedule.csv"
)


print()
print("AUTHORITATIVE INPUTS")
print("-" * 100)

for path_name_4d2, path_value_4d2 in {
    "accepted raw results": raw_path_4d2,
    "accepted execution summary": summary_path_4d2,
    "locked schedule": locked_schedule_path_4d2,
}.items():

    print(
        f"{path_name_4d2:<28}: "
        f"{path_value_4d2} "
        f"[exists={path_value_4d2.exists()}]"
    )


assert raw_path_4d2.exists(), (
    f"Accepted raw result file missing: {raw_path_4d2}"
)

assert summary_path_4d2.exists(), (
    f"Accepted execution summary missing: {summary_path_4d2}"
)

assert locked_schedule_path_4d2.exists(), (
    f"Locked benchmark schedule missing: {locked_schedule_path_4d2}"
)


# ------------------------------------------------------------
# 3. Load accepted benchmark evidence
# ------------------------------------------------------------

raw_4d2 = pd.read_csv(
    raw_path_4d2
)

schedule_4d2 = pd.read_csv(
    locked_schedule_path_4d2
)

with open(
    summary_path_4d2,
    "r",
    encoding="utf-8",
) as summary_file_4d2:

    summary_4d2 = json.load(
        summary_file_4d2
    )


assert bool(
    summary_4d2.get(
        "benchmark_accepted",
        False,
    )
), (
    "Section 4C.2 benchmark is not marked accepted."
)


print()
print("ACCEPTED BENCHMARK SIZE")
print("-" * 100)
print("Raw result rows :", len(raw_4d2))
print("Schedule rows   :", len(schedule_4d2))


assert len(raw_4d2) == 300
assert len(schedule_4d2) == 300


# ------------------------------------------------------------
# 4. Normalize match IDs
# ------------------------------------------------------------

raw_4d2["match_id"] = pd.to_numeric(
    raw_4d2["match_id"],
    errors="raise",
).astype(int)

schedule_4d2["match_id"] = pd.to_numeric(
    schedule_4d2["match_id"],
    errors="raise",
).astype(int)


assert raw_4d2["match_id"].is_unique
assert schedule_4d2["match_id"].is_unique


# ------------------------------------------------------------
# 5. Identify required locked-schedule fields
# ------------------------------------------------------------

required_schedule_columns_4d2 = [
    "match_id",
    "baseline_name",
    "evaluated_agent_side",
    "starting_side",
    "player_card",
    "opponent_card",
]

missing_schedule_columns_4d2 = [
    column_4d2
    for column_4d2
    in required_schedule_columns_4d2
    if column_4d2 not in schedule_4d2.columns
]

assert not missing_schedule_columns_4d2, (
    "Locked schedule is missing required columns: "
    + str(missing_schedule_columns_4d2)
)


# ------------------------------------------------------------
# 6. Restore authoritative schedule fields safely
# ------------------------------------------------------------
#
# Section 4C.2 raw results may already contain persisted
# scheduled_* fields. Do not merge duplicate scheduled columns.
# Only recover evaluated_agent_side from the locked schedule
# when it is not already available.
# ------------------------------------------------------------

benchmark_4d2 = raw_4d2.copy()


print()
print("RAW RESULT SCHEMA")
print("-" * 100)

print(
    "\n".join(
        benchmark_4d2.columns.astype(str).tolist()
    )
)


# ------------------------------------------------------------
# Determine whether evaluated_agent_side is already persisted
# ------------------------------------------------------------

if (
    "evaluated_agent_side"
    in benchmark_4d2.columns
):

    print()
    print(
        "evaluated_agent_side already present "
        "in accepted raw results."
    )

elif (
    "scheduled_evaluated_agent_side"
    in benchmark_4d2.columns
):

    benchmark_4d2[
        "evaluated_agent_side"
    ] = benchmark_4d2[
        "scheduled_evaluated_agent_side"
    ]

    print()
    print(
        "evaluated_agent_side restored from "
        "persisted scheduled_evaluated_agent_side."
    )

else:

    evaluated_side_lookup_4d2 = (
        schedule_4d2[
            [
                "match_id",
                "evaluated_agent_side",
            ]
        ]
        .copy()
    )

    benchmark_4d2 = (
        benchmark_4d2
        .merge(
            evaluated_side_lookup_4d2,
            on="match_id",
            how="left",
            validate="one_to_one",
        )
    )

    print()
    print(
        "evaluated_agent_side restored from "
        "locked Section 4B schedule."
    )


assert (
    "evaluated_agent_side"
    in benchmark_4d2.columns
), (
    "evaluated_agent_side could not be reconstructed."
)

assert benchmark_4d2[
    "evaluated_agent_side"
].notna().all(), (
    "One or more evaluated-agent sides are missing."
)


# ------------------------------------------------------------
# 7. Validate accepted results against locked schedule
# ------------------------------------------------------------

schedule_validation_4d2 = (
    schedule_4d2[
        [
            "match_id",
            "baseline_name",
            "starting_side",
            "player_card",
            "opponent_card",
            "evaluated_agent_side",
        ]
    ]
    .copy()
    .rename(
        columns={
            "baseline_name":
                "lock_baseline_name",
            "starting_side":
                "lock_starting_side",
            "player_card":
                "lock_player_card",
            "opponent_card":
                "lock_opponent_card",
            "evaluated_agent_side":
                "lock_evaluated_agent_side",
        }
    )
)


contract_4d2 = (
    benchmark_4d2[
        [
            "match_id",
            "baseline_name",
            "starting_side",
            "player_card",
            "opponent_card",
            "evaluated_agent_side",
        ]
    ]
    .merge(
        schedule_validation_4d2,
        on="match_id",
        how="left",
        validate="one_to_one",
    )
)


contract_checks_4d2 = []


for (
    result_column_4d2,
    lock_column_4d2,
) in [
    (
        "baseline_name",
        "lock_baseline_name",
    ),
    (
        "starting_side",
        "lock_starting_side",
    ),
    (
        "player_card",
        "lock_player_card",
    ),
    (
        "opponent_card",
        "lock_opponent_card",
    ),
    (
        "evaluated_agent_side",
        "lock_evaluated_agent_side",
    ),
]:

    row_matches_4d2 = (
        contract_4d2[
            result_column_4d2
        ].astype(str)
        ==
        contract_4d2[
            lock_column_4d2
        ].astype(str)
    )

    contract_checks_4d2.append(
        {
            "contract":
                (
                    f"{result_column_4d2} "
                    "agrees with locked schedule"
                ),
            "matching_rows":
                int(
                    row_matches_4d2.sum()
                ),
            "expected_rows":
                300,
            "passed":
                bool(
                    row_matches_4d2.all()
                ),
        }
    )


contract_df_4d2 = pd.DataFrame(
    contract_checks_4d2
)


print()
print(
    "RAW RESULT ↔ LOCKED SCHEDULE CONTRACT"
)
print("-" * 100)

display(
    contract_df_4d2
)


assert contract_df_4d2[
    "passed"
].all(), (
    "Accepted benchmark results do not agree "
    "with the locked Section 4B schedule."
)


print()
print(
    "✅ ACCEPTED RESULTS MATCH LOCKED "
    "300-MATCH SCHEDULE"
)
# ------------------------------------------------------------
# 8. Reconstruct R3 outcome from winner + evaluated side
# ------------------------------------------------------------

benchmark_4d2[
    "winner_normalized"
] = (
    benchmark_4d2[
        "winner"
    ]
    .astype(str)
    .str.strip()
)

benchmark_4d2[
    "evaluated_agent_side"
] = (
    benchmark_4d2[
        "evaluated_agent_side"
    ]
    .astype(str)
    .str.strip()
)


def reconstruct_r3_outcome_4d2(row_4d2):

    winner_4d2 = row_4d2[
        "winner_normalized"
    ]

    evaluated_side_4d2 = row_4d2[
        "evaluated_agent_side"
    ]

    if winner_4d2 == evaluated_side_4d2:
        return "WIN"

    if winner_4d2 in {
        "Player",
        "Opponent",
    }:
        return "LOSS"

    return "DRAW"


benchmark_4d2[
    "r3_outcome_authoritative"
] = benchmark_4d2.apply(
    reconstruct_r3_outcome_4d2,
    axis=1,
)


benchmark_4d2[
    "r3_score_authoritative"
] = (
    benchmark_4d2[
        "r3_outcome_authoritative"
    ]
    .map(
        {
            "WIN": 1.0,
            "DRAW": 0.5,
            "LOSS": 0.0,
        }
    )
)


assert benchmark_4d2[
    "r3_score_authoritative"
].notna().all()


# ------------------------------------------------------------
# 9. Overall outcome counts
# ------------------------------------------------------------

outcome_counts_4d2 = (
    benchmark_4d2[
        "r3_outcome_authoritative"
    ]
    .value_counts()
    .reindex(
        [
            "WIN",
            "LOSS",
            "DRAW",
        ],
        fill_value=0,
    )
)


wins_4d2 = int(
    outcome_counts_4d2["WIN"]
)

losses_4d2 = int(
    outcome_counts_4d2["LOSS"]
)

draws_4d2 = int(
    outcome_counts_4d2["DRAW"]
)

matches_4d2 = int(
    len(
        benchmark_4d2
    )
)

overall_win_rate_4d2 = (
    wins_4d2
    / matches_4d2
)

overall_score_rate_4d2 = float(
    benchmark_4d2[
        "r3_score_authoritative"
    ].mean()
)


print()
print("AUTHORITATIVE OVERALL OUTCOME")
print("-" * 100)

print(
    f"Matches      : {matches_4d2}"
)
print(
    f"Wins         : {wins_4d2}"
)
print(
    f"Losses       : {losses_4d2}"
)
print(
    f"Draws        : {draws_4d2}"
)
print(
    f"Win rate     : {overall_win_rate_4d2:.4%}"
)
print(
    f"Score rate   : {overall_score_rate_4d2:.4%}"
)


# ------------------------------------------------------------
# 10. Performance by historical baseline
# ------------------------------------------------------------

baseline_performance_4d2 = (
    benchmark_4d2
    .groupby(
        "baseline_name",
        as_index=False,
    )
    .agg(
        matches=(
            "match_id",
            "count",
        ),
        wins=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "WIN"
                    ).sum()
                ),
        ),
        losses=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "LOSS"
                    ).sum()
                ),
        ),
        draws=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "DRAW"
                    ).sum()
                ),
        ),
        mean_turns=(
            "turns",
            "mean",
        ),
        score_rate=(
            "r3_score_authoritative",
            "mean",
        ),
    )
)


baseline_performance_4d2[
    "win_rate"
] = (
    baseline_performance_4d2[
        "wins"
    ]
    /
    baseline_performance_4d2[
        "matches"
    ]
)


baseline_performance_4d2[
    "win_rate_pct"
] = (
    100
    *
    baseline_performance_4d2[
        "win_rate"
    ]
)


baseline_performance_4d2[
    "score_rate_pct"
] = (
    100
    *
    baseline_performance_4d2[
        "score_rate"
    ]
)


baseline_performance_4d2 = (
    baseline_performance_4d2[
        [
            "baseline_name",
            "matches",
            "wins",
            "losses",
            "draws",
            "win_rate_pct",
            "score_rate_pct",
            "mean_turns",
        ]
    ]
    .sort_values(
        "baseline_name"
    )
    .reset_index(
        drop=True
    )
)


print()
print("PERFORMANCE BY HISTORICAL BASELINE")
print("-" * 100)

display(
    baseline_performance_4d2.round(
        {
            "win_rate_pct": 2,
            "score_rate_pct": 2,
            "mean_turns": 2,
        }
    )
)


# ------------------------------------------------------------
# 11. Performance by evaluated-agent side
# ------------------------------------------------------------

evaluated_side_performance_4d2 = (
    benchmark_4d2
    .groupby(
        "evaluated_agent_side",
        as_index=False,
    )
    .agg(
        matches=(
            "match_id",
            "count",
        ),
        wins=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "WIN"
                    ).sum()
                ),
        ),
        losses=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "LOSS"
                    ).sum()
                ),
        ),
        draws=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "DRAW"
                    ).sum()
                ),
        ),
        score_rate=(
            "r3_score_authoritative",
            "mean",
        ),
    )
)


evaluated_side_performance_4d2[
    "win_rate_pct"
] = (
    100
    *
    evaluated_side_performance_4d2[
        "wins"
    ]
    /
    evaluated_side_performance_4d2[
        "matches"
    ]
)


evaluated_side_performance_4d2[
    "score_rate_pct"
] = (
    100
    *
    evaluated_side_performance_4d2[
        "score_rate"
    ]
)


print()
print("PERFORMANCE BY EVALUATED-AGENT SIDE")
print("-" * 100)

display(
    evaluated_side_performance_4d2[
        [
            "evaluated_agent_side",
            "matches",
            "wins",
            "losses",
            "draws",
            "win_rate_pct",
            "score_rate_pct",
        ]
    ].round(
        {
            "win_rate_pct": 2,
            "score_rate_pct": 2,
        }
    )
)


# ------------------------------------------------------------
# 12. Baseline × evaluated-side performance
# ------------------------------------------------------------

baseline_side_performance_4d2 = (
    benchmark_4d2
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
        ],
        as_index=False,
    )
    .agg(
        matches=(
            "match_id",
            "count",
        ),
        wins=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "WIN"
                    ).sum()
                ),
        ),
        losses=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "LOSS"
                    ).sum()
                ),
        ),
        draws=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "DRAW"
                    ).sum()
                ),
        ),
        score_rate=(
            "r3_score_authoritative",
            "mean",
        ),
    )
)


baseline_side_performance_4d2[
    "win_rate_pct"
] = (
    100
    *
    baseline_side_performance_4d2[
        "wins"
    ]
    /
    baseline_side_performance_4d2[
        "matches"
    ]
)


baseline_side_performance_4d2[
    "score_rate_pct"
] = (
    100
    *
    baseline_side_performance_4d2[
        "score_rate"
    ]
)


print()
print("BASELINE × EVALUATED-SIDE PERFORMANCE")
print("-" * 100)

display(
    baseline_side_performance_4d2[
        [
            "baseline_name",
            "evaluated_agent_side",
            "matches",
            "wins",
            "losses",
            "draws",
            "win_rate_pct",
            "score_rate_pct",
        ]
    ].round(
        {
            "win_rate_pct": 2,
            "score_rate_pct": 2,
        }
    )
)


# ------------------------------------------------------------
# 13. Starting-side performance
# ------------------------------------------------------------

starting_side_performance_4d2 = (
    benchmark_4d2
    .groupby(
        "starting_side",
        as_index=False,
    )
    .agg(
        matches=(
            "match_id",
            "count",
        ),
        wins=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "WIN"
                    ).sum()
                ),
        ),
        losses=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "LOSS"
                    ).sum()
                ),
        ),
        draws=(
            "r3_outcome_authoritative",
            lambda series_4d2:
                int(
                    (
                        series_4d2
                        == "DRAW"
                    ).sum()
                ),
        ),
        score_rate=(
            "r3_score_authoritative",
            "mean",
        ),
    )
)


starting_side_performance_4d2[
    "win_rate_pct"
] = (
    100
    *
    starting_side_performance_4d2[
        "wins"
    ]
    /
    starting_side_performance_4d2[
        "matches"
    ]
)


print()
print("PERFORMANCE BY MATCH STARTING SIDE")
print("-" * 100)

display(
    starting_side_performance_4d2[
        [
            "starting_side",
            "matches",
            "wins",
            "losses",
            "draws",
            "win_rate_pct",
        ]
    ].round(
        {
            "win_rate_pct": 2,
        }
    )
)


# ------------------------------------------------------------
# 14. Historical Notebook 48 comparison
# ------------------------------------------------------------

historical_win_rate_4d2 = (
    194
    / 300
)

historical_wins_4d2 = 194

win_difference_4d2 = (
    wins_4d2
    - historical_wins_4d2
)

percentage_point_difference_4d2 = (
    100
    * (
        overall_win_rate_4d2
        - historical_win_rate_4d2
    )
)


print()
print("HISTORICAL NOTEBOOK 48 COMPARISON")
print("-" * 100)

print(
    f"Historical wins          : "
    f"{historical_wins_4d2} / 300"
)

print(
    f"Historical win rate      : "
    f"{historical_win_rate_4d2:.4%}"
)

print(
    f"Current R3 wins          : "
    f"{wins_4d2} / 300"
)

print(
    f"Current R3 win rate      : "
    f"{overall_win_rate_4d2:.4%}"
)

print(
    f"Win-count difference     : "
    f"{win_difference_4d2:+d}"
)

print(
    f"Percentage-point change  : "
    f"{percentage_point_difference_4d2:+.2f}"
)


# ------------------------------------------------------------
# 15. Final Section 4D.2 validation
# ------------------------------------------------------------

validation_4d2 = pd.DataFrame(
    [
        {
            "validation":
                "accepted benchmark contains 300 matches",
            "observed":
                matches_4d2,
            "expected":
                300,
            "passed":
                matches_4d2 == 300,
        },
        {
            "validation":
                "R3 outcome assigned to every match",
            "observed":
                int(
                    benchmark_4d2[
                        "r3_outcome_authoritative"
                    ].notna().sum()
                ),
            "expected":
                300,
            "passed":
                benchmark_4d2[
                    "r3_outcome_authoritative"
                ].notna().all(),
        },
        {
            "validation":
                "R3 score assigned to every match",
            "observed":
                int(
                    benchmark_4d2[
                        "r3_score_authoritative"
                    ].notna().sum()
                ),
            "expected":
                300,
            "passed":
                benchmark_4d2[
                    "r3_score_authoritative"
                ].notna().all(),
        },
        {
            "validation":
                "three baselines represented",
            "observed":
                benchmark_4d2[
                    "baseline_name"
                ].nunique(),
            "expected":
                3,
            "passed":
                benchmark_4d2[
                    "baseline_name"
                ].nunique()
                == 3,
        },
        {
            "validation":
                "150 Player-side evaluations",
            "observed":
                int(
                    (
                        benchmark_4d2[
                            "evaluated_agent_side"
                        ]
                        == "Player"
                    ).sum()
                ),
            "expected":
                150,
            "passed":
                int(
                    (
                        benchmark_4d2[
                            "evaluated_agent_side"
                        ]
                        == "Player"
                    ).sum()
                )
                == 150,
        },
        {
            "validation":
                "150 Opponent-side evaluations",
            "observed":
                int(
                    (
                        benchmark_4d2[
                            "evaluated_agent_side"
                        ]
                        == "Opponent"
                    ).sum()
                ),
            "expected":
                150,
            "passed":
                int(
                    (
                        benchmark_4d2[
                            "evaluated_agent_side"
                        ]
                        == "Opponent"
                    ).sum()
                )
                == 150,
        },
        {
            "validation":
                "win + loss + draw totals equal 300",
            "observed":
                (
                    wins_4d2
                    + losses_4d2
                    + draws_4d2
                ),
            "expected":
                300,
            "passed":
                (
                    wins_4d2
                    + losses_4d2
                    + draws_4d2
                )
                == 300,
        },
        {
            "validation":
                "benchmark remains accepted",
            "observed":
                bool(
                    summary_4d2[
                        "benchmark_accepted"
                    ]
                ),
            "expected":
                True,
            "passed":
                bool(
                    summary_4d2[
                        "benchmark_accepted"
                    ]
                ),
        },
    ]
)


print()
print("SECTION 4D.2 VALIDATION")
print("-" * 100)

display(
    validation_4d2
)


SECTION_4D2_COMPLETE = bool(
    validation_4d2[
        "passed"
    ].all()
)


assert SECTION_4D2_COMPLETE, (
    "Section 4D.2 performance reconstruction failed."
)


print()
print("=" * 100)
print("✅ ACCEPTED 300-MATCH PERFORMANCE RECONSTRUCTED")
print("✅ EVALUATED-AGENT SIDE RESTORED FROM LOCKED SCHEDULE")
print("✅ OVERALL R3 RESULT CALCULATED")
print("✅ THREE BASELINE RESULTS CALCULATED")
print("✅ SIDE-NEUTRAL PERFORMANCE CALCULATED")
print("✅ STARTING-SIDE PERFORMANCE CALCULATED")
print("✅ HISTORICAL NOTEBOOK 48 COMPARISON CALCULATED")
print("✅ NO MATCHES RE-RUN")
print("✅ NO RETRAINING")
print("✅ NO MODEL MODIFICATION")
print("✅ SECTION 4D.2 COMPLETE")
print("=" * 100)

====================================================================================================
SECTION 4D.2 — AUTHORITATIVE R3 PERFORMANCE RECONSTRUCTION
====================================================================================================

AUTHORITATIVE INPUTS
----------------------------------------------------------------------------------------------------
accepted raw results        : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\outputs\notebook60\section4c2_r3_300_match_raw_results.csv [exists=True]
accepted execution summary  : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4c2_r3_300_match_execution_summary.json [exists=True]
locked schedule             : D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge\reports\notebook60\section4b_locked_300_match_schedule.csv [exists=True]

ACCEPTED BENCHMARK SIZE
----------------------------------------------------------------------------------------------------
Raw result rows : 300
Schedule rows   : 300

RAW RESULT SCHEMA
----------------------------------------------------------------------------------------------------
match_id
agent_name
baseline_name
player_card
opponent_card
starting_side
winner
turns
stop_reason
agent_result
fallback_count
elapsed_seconds
schedule_match_id
scheduled_baseline_name
scheduled_evaluated_agent_side
scheduled_starting_side
scheduled_player_card
scheduled_opponent_card
baseline_seed
r3_outcome
r3_score_reconstructed
execution_success

evaluated_agent_side restored from persisted scheduled_evaluated_agent_side.

RAW RESULT ↔ LOCKED SCHEDULE CONTRACT
----------------------------------------------------------------------------------------------------

,contract,matching_rows,expected_rows,passed
0,baseline_name agrees with locked schedule,300,300,True
1,starting_side agrees with locked schedule,300,300,True
2,player_card agrees with locked schedule,300,300,True
3,opponent_card agrees with locked schedule,300,300,True
4,evaluated_agent_side agrees with locked schedule,300,300,True

✅ ACCEPTED RESULTS MATCH LOCKED 300-MATCH SCHEDULE

AUTHORITATIVE OVERALL OUTCOME
----------------------------------------------------------------------------------------------------
Matches      : 300
Wins         : 27
Losses       : 273
Draws        : 0
Win rate     : 9.0000%
Score rate   : 9.0000%

PERFORMANCE BY HISTORICAL BASELINE
----------------------------------------------------------------------------------------------------

,baseline_name,matches,wins,losses,draws,win_rate_pct,score_rate_pct,mean_turns
0,Depth-6 Search Baseline,100,17,83,0,17.0,17.0,6.33
1,Greedy Damage Baseline,100,0,100,0,0.0,0.0,4.18
2,Random Baseline,100,10,90,0,10.0,10.0,5.58

PERFORMANCE BY EVALUATED-AGENT SIDE
----------------------------------------------------------------------------------------------------

,evaluated_agent_side,matches,wins,losses,draws,win_rate_pct,score_rate_pct
0,Opponent,150,0,150,0,0.0,0.0
1,Player,150,27,123,0,18.0,18.0

BASELINE × EVALUATED-SIDE PERFORMANCE
----------------------------------------------------------------------------------------------------

,baseline_name,evaluated_agent_side,matches,wins,losses,draws,win_rate_pct,score_rate_pct
0,Depth-6 Search Baseline,Opponent,50,0,50,0,0.0,0.0
1,Depth-6 Search Baseline,Player,50,17,33,0,34.0,34.0
2,Greedy Damage Baseline,Opponent,50,0,50,0,0.0,0.0
3,Greedy Damage Baseline,Player,50,0,50,0,0.0,0.0
4,Random Baseline,Opponent,50,0,50,0,0.0,0.0
5,Random Baseline,Player,50,10,40,0,20.0,20.0

PERFORMANCE BY MATCH STARTING SIDE
----------------------------------------------------------------------------------------------------

  starting_side  matches  wins  losses  draws  win_rate_pct
0      Opponent      150    11     139      0          7.33
1        Player      150    16     134      0         10.67

HISTORICAL NOTEBOOK 48 COMPARISON
----------------------------------------------------------------------------------------------------
Historical wins          : 194 / 300
Historical win rate      : 64.6667%
Current R3 wins          : 27 / 300
Current R3 win rate      : 9.0000%
Win-count difference     : -167
Percentage-point change  : -55.67

SECTION 4D.2 VALIDATION
----------------------------------------------------------------------------------------------------

                                validation observed expected  passed
0  accepted benchmark contains 300 matches      300      300    True
1       R3 outcome assigned to every match      300      300    True
2         R3 score assigned to every match      300      300    True
3              three baselines represented        3        3    True
4              150 Player-side evaluations      150      150    True
5            150 Opponent-side evaluations      150      150    True
6       win + loss + draw totals equal 300      300      300    True
7               benchmark remains accepted     True     True    True

====================================================================================================
✅ ACCEPTED 300-MATCH PERFORMANCE RECONSTRUCTED
✅ EVALUATED-AGENT SIDE RESTORED FROM LOCKED SCHEDULE
✅ OVERALL R3 RESULT CALCULATED
✅ THREE BASELINE RESULTS CALCULATED
✅ SIDE-NEUTRAL PERFORMANCE CALCULATED
✅ STARTING-SIDE PERFORMANCE CALCULATED
✅ HISTORICAL NOTEBOOK 48 COMPARISON CALCULATED
✅ NO MATCHES RE-RUN
✅ NO RETRAINING
✅ NO MODEL MODIFICATION
✅ SECTION 4D.2 COMPLETE
====================================================================================================

## Section 4D.2 — Authoritative R3 Benchmark Performance Reconstruction

The accepted Section 4C.2 benchmark was reconstructed against the exact
locked 300-match Notebook 48 tournament schedule.

### Benchmark integrity

- 300 accepted benchmark matches
- 300 unique scheduled matches
- 100 matches against each historical baseline
- 150 Player-side R3 evaluations
- 150 Opponent-side R3 evaluations
- 0 execution failures
- Frozen R3 feature contract remained at 46 features
- Frozen six-class action contract remained unchanged
- No R3 retraining was performed
- No R3 model modification was performed

The accepted raw-result rows were verified against the locked tournament
schedule for baseline name, starting side, player card, opponent card,
and evaluated-agent side. All 300 rows matched the locked schedule.

### Reconstructed performance

Overall R3 performance:

- Wins: 27
- Losses: 273
- Draws: 0
- Win rate: 9.00%

Performance by baseline:

- Depth-6 Search Baseline: 17 / 100 wins = 17.00%
- Greedy Damage Baseline: 0 / 100 wins = 0.00%
- Random Baseline: 10 / 100 wins = 10.00%

Performance by evaluated-agent side:

- Player side: 27 / 150 wins = 18.00%
- Opponent side: 0 / 150 wins = 0.00%

Historical Notebook 48 reference:

- Historical wins: 194 / 300
- Historical win rate: 64.67%
- Current R3 wins: 27 / 300
- Current R3 win rate: 9.00%
- Difference: -167 wins
- Percentage-point change: -55.67

### Interpretation

The benchmark execution is mechanically valid, but the resulting
performance contains a severe side asymmetry.

R3 won 27 of 150 matches when evaluated as Player but won 0 of 150
matches when evaluated as Opponent.

This asymmetry must be investigated before the 9.00% overall win rate
is accepted as a genuine estimate of frozen R3 model quality.

The next diagnostic stage will therefore audit tournament-side
orientation, state transformation, acting/defending feature semantics,
move selection, and winner attribution.

No retraining or model modification will be performed until this
side-orientation audit is complete.

In [6]:
# ======================================================================================
# SECTION 4D.3 — SIDE-ORIENTATION FORENSIC AUDIT
# ======================================================================================

print("=" * 100)
print("SECTION 4D.3 — SIDE-ORIENTATION FORENSIC AUDIT")
print("=" * 100)

# --------------------------------------------------------------------------------------
# 1. Start from authoritative reconstructed benchmark
# --------------------------------------------------------------------------------------

audit_4d3 = benchmark_4d2.copy()

required_4d3_columns = [
    "match_id",
    "baseline_name",
    "player_card",
    "opponent_card",
    "starting_side",
    "winner",
    "evaluated_agent_side",
    "r3_outcome",
    "r3_score_reconstructed",
]

missing_4d3_columns = [
    column_name
    for column_name in required_4d3_columns
    if column_name not in audit_4d3.columns
]

assert not missing_4d3_columns, (
    "Required Section 4D.3 columns are missing: "
    f"{missing_4d3_columns}"
)

print()
print("AUTHORITATIVE AUDIT INPUT")
print("-" * 100)
print("Rows:", len(audit_4d3))
print("Columns available:", len(audit_4d3.columns))


# --------------------------------------------------------------------------------------
# 2. Reconstruct expected evaluated-agent winner identity
# --------------------------------------------------------------------------------------

def expected_r3_win_from_side_4d3(row):
    evaluated_side = str(row["evaluated_agent_side"])
    winner = str(row["winner"])

    if winner not in {"Player", "Opponent"}:
        return False

    return winner == evaluated_side


audit_4d3["winner_matches_evaluated_agent"] = (
    audit_4d3.apply(
        expected_r3_win_from_side_4d3,
        axis=1,
    )
)

audit_4d3["stored_r3_win"] = (
    audit_4d3["r3_outcome"]
    .astype(str)
    .str.upper()
    .eq("WIN")
)

audit_4d3["winner_mapping_agrees"] = (
    audit_4d3["winner_matches_evaluated_agent"]
    ==
    audit_4d3["stored_r3_win"]
)


print()
print("WINNER ATTRIBUTION CHECK")
print("-" * 100)

winner_mapping_summary_4d3 = pd.DataFrame(
    [
        {
            "validation": "all stored R3 outcomes agree with winner + evaluated side",
            "observed": int(
                audit_4d3["winner_mapping_agrees"].sum()
            ),
            "expected": len(audit_4d3),
            "passed": bool(
                audit_4d3["winner_mapping_agrees"].all()
            ),
        }
    ]
)

display(winner_mapping_summary_4d3)


# --------------------------------------------------------------------------------------
# 3. Side-level result audit
# --------------------------------------------------------------------------------------

side_result_audit_4d3 = (
    audit_4d3
    .groupby(
        "evaluated_agent_side",
        dropna=False,
    )
    .agg(
        matches=("match_id", "count"),
        player_winners=(
            "winner",
            lambda values: int(
                (values.astype(str) == "Player").sum()
            ),
        ),
        opponent_winners=(
            "winner",
            lambda values: int(
                (values.astype(str) == "Opponent").sum()
            ),
        ),
        stored_r3_wins=(
            "stored_r3_win",
            "sum",
        ),
        reconstructed_r3_wins=(
            "winner_matches_evaluated_agent",
            "sum",
        ),
    )
    .reset_index()
)

side_result_audit_4d3[
    "stored_r3_wins"
] = side_result_audit_4d3[
    "stored_r3_wins"
].astype(int)

side_result_audit_4d3[
    "reconstructed_r3_wins"
] = side_result_audit_4d3[
    "reconstructed_r3_wins"
].astype(int)

side_result_audit_4d3[
    "win_reconstruction_agrees"
] = (
    side_result_audit_4d3[
        "stored_r3_wins"
    ]
    ==
    side_result_audit_4d3[
        "reconstructed_r3_wins"
    ]
)

print()
print("SIDE-LEVEL WINNER ATTRIBUTION")
print("-" * 100)

display(side_result_audit_4d3)


# --------------------------------------------------------------------------------------
# 4. Cross-check match identity and scheduled orientation
# --------------------------------------------------------------------------------------

orientation_check_columns_4d3 = [
    "match_id",
    "player_card",
    "opponent_card",
    "starting_side",
    "evaluated_agent_side",
    "winner",
    "r3_outcome",
]

orientation_preview_4d3 = (
    audit_4d3[
        orientation_check_columns_4d3
    ]
    .copy()
)

print()
print("FIRST 20 ORIENTATION RECORDS")
print("-" * 100)

display(
    orientation_preview_4d3.head(20)
)


# --------------------------------------------------------------------------------------
# 5. Matched card-pair comparison across evaluated side
# --------------------------------------------------------------------------------------

pair_counts_4d3 = (
    audit_4d3
    .groupby(
        [
            "player_card",
            "opponent_card",
            "evaluated_agent_side",
        ]
    )
    .size()
    .reset_index(
        name="matches"
    )
)

print()
print("CARD PAIR × EVALUATED SIDE COUNTS")
print("-" * 100)

display(pair_counts_4d3)


# --------------------------------------------------------------------------------------
# 6. Find card pairs represented on both R3 sides
# --------------------------------------------------------------------------------------

pair_side_coverage_4d3 = (
    audit_4d3
    .groupby(
        [
            "player_card",
            "opponent_card",
        ]
    )["evaluated_agent_side"]
    .nunique()
    .reset_index(
        name="evaluated_side_count"
    )
)

both_sides_pairs_4d3 = (
    pair_side_coverage_4d3[
        pair_side_coverage_4d3[
            "evaluated_side_count"
        ] == 2
    ]
    .copy()
)

print()
print("CARD PAIRS AVAILABLE ON BOTH EVALUATED SIDES")
print("-" * 100)

display(both_sides_pairs_4d3)


# --------------------------------------------------------------------------------------
# 7. Forensic samples by evaluated-agent side
# --------------------------------------------------------------------------------------
#
# The locked historical schedule does not contain identical
# (player_card, opponent_card) pairs on both evaluated-agent sides.
# Therefore exact card-pair mirroring is NOT a valid requirement.
#
# Instead, inspect representative rows independently for:
#   1. R3 evaluated as Player
#   2. R3 evaluated as Opponent
# --------------------------------------------------------------------------------------

player_sample_4d3 = (
    audit_4d3[
        audit_4d3[
            "evaluated_agent_side"
        ] == "Player"
    ]
    [
        [
            "match_id",
            "baseline_name",
            "player_card",
            "opponent_card",
            "starting_side",
            "evaluated_agent_side",
            "winner",
            "r3_outcome",
            "r3_score_reconstructed",
            "fallback_count",
        ]
    ]
    .head(12)
    .copy()
)

opponent_sample_4d3 = (
    audit_4d3[
        audit_4d3[
            "evaluated_agent_side"
        ] == "Opponent"
    ]
    [
        [
            "match_id",
            "baseline_name",
            "player_card",
            "opponent_card",
            "starting_side",
            "evaluated_agent_side",
            "winner",
            "r3_outcome",
            "r3_score_reconstructed",
            "fallback_count",
        ]
    ]
    .head(12)
    .copy()
)


print()
print("FORENSIC SAMPLE — R3 EVALUATED AS PLAYER")
print("-" * 100)

display(player_sample_4d3)


print()
print("FORENSIC SAMPLE — R3 EVALUATED AS OPPONENT")
print("-" * 100)

display(opponent_sample_4d3)


# --------------------------------------------------------------------------------------
# 8. Winner distribution by evaluated-agent side
# --------------------------------------------------------------------------------------

winner_distribution_4d3 = (
    audit_4d3
    .groupby(
        [
            "evaluated_agent_side",
            "winner",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)

print()
print("WINNER DISTRIBUTION BY EVALUATED-AGENT SIDE")
print("-" * 100)

display(winner_distribution_4d3)


# --------------------------------------------------------------------------------------
# 9. Starting-side × evaluated-side × winner audit
# --------------------------------------------------------------------------------------

starting_side_audit_4d3 = (
    audit_4d3
    .groupby(
        [
            "evaluated_agent_side",
            "starting_side",
            "winner",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)

print()
print("EVALUATED SIDE × STARTING SIDE × WINNER")
print("-" * 100)

display(starting_side_audit_4d3)


# --------------------------------------------------------------------------------------
# 10. Baseline × evaluated-side × winner audit
# --------------------------------------------------------------------------------------

baseline_winner_audit_4d3 = (
    audit_4d3
    .groupby(
        [
            "baseline_name",
            "evaluated_agent_side",
            "winner",
        ],
        dropna=False,
    )
    .size()
    .reset_index(
        name="matches"
    )
)

print()
print("BASELINE × EVALUATED SIDE × WINNER")
print("-" * 100)

display(baseline_winner_audit_4d3)


# --------------------------------------------------------------------------------------
# 11. Confirm the extreme Opponent-side pattern
# --------------------------------------------------------------------------------------

player_rows_4d3 = (
    audit_4d3[
        audit_4d3[
            "evaluated_agent_side"
        ] == "Player"
    ]
    .copy()
)

opponent_rows_4d3 = (
    audit_4d3[
        audit_4d3[
            "evaluated_agent_side"
        ] == "Opponent"
    ]
    .copy()
)


player_win_count_4d3 = int(
    (
        player_rows_4d3[
            "winner"
        ].astype(str)
        ==
        "Player"
    ).sum()
)


opponent_win_count_4d3 = int(
    (
        opponent_rows_4d3[
            "winner"
        ].astype(str)
        ==
        "Opponent"
    ).sum()
)


opponent_side_player_winner_count_4d3 = int(
    (
        opponent_rows_4d3[
            "winner"
        ].astype(str)
        ==
        "Player"
    ).sum()
)


print()
print("EXTREME SIDE-ASYMMETRY CHECK")
print("-" * 100)

print(
    "R3 Player-side wins   :",
    player_win_count_4d3,
    "/",
    len(player_rows_4d3),
)

print(
    "R3 Opponent-side wins :",
    opponent_win_count_4d3,
    "/",
    len(opponent_rows_4d3),
)

print(
    "Player winner when R3 is Opponent:",
    opponent_side_player_winner_count_4d3,
    "/",
    len(opponent_rows_4d3),
)


# --------------------------------------------------------------------------------------
# 12. Section 4D.3 validation
# --------------------------------------------------------------------------------------

section4d3_validation_df = pd.DataFrame(
    [
        {
            "validation":
                "300 authoritative benchmark rows audited",
            "observed":
                len(audit_4d3),
            "expected":
                300,
            "passed":
                len(audit_4d3) == 300,
        },
        {
            "validation":
                "winner attribution agrees for every match",
            "observed":
                int(
                    audit_4d3[
                        "winner_mapping_agrees"
                    ].sum()
                ),
            "expected":
                300,
            "passed":
                bool(
                    audit_4d3[
                        "winner_mapping_agrees"
                    ].all()
                ),
        },
        {
            "validation":
                "150 Player-side evaluations",
            "observed":
                len(player_rows_4d3),
            "expected":
                150,
            "passed":
                len(player_rows_4d3) == 150,
        },
        {
            "validation":
                "150 Opponent-side evaluations",
            "observed":
                len(opponent_rows_4d3),
            "expected":
                150,
            "passed":
                len(opponent_rows_4d3) == 150,
        },
        {
            "validation":
                "Player-side R3 wins reconstructed",
            "observed":
                player_win_count_4d3,
            "expected":
                27,
            "passed":
                player_win_count_4d3 == 27,
        },
        {
            "validation":
                "Opponent-side R3 wins reconstructed",
            "observed":
                opponent_win_count_4d3,
            "expected":
                0,
            "passed":
                opponent_win_count_4d3 == 0,
        },
        {
            "validation":
                "all Opponent-side R3 matches recorded Player winner",
            "observed":
                opponent_side_player_winner_count_4d3,
            "expected":
                150,
            "passed":
                opponent_side_player_winner_count_4d3 == 150,
        },
        {
            "validation":
                "exact mirrored card pairs required",
            "observed":
                len(both_sides_pairs_4d3),
            "expected":
                "not required",
            "passed":
                True,
        },
    ]
)


print()
print("SECTION 4D.3 VALIDATION")
print("-" * 100)

display(section4d3_validation_df)


assert section4d3_validation_df[
    "passed"
].all(), (
    "Section 4D.3 forensic validation failed."
)


print()
print("=" * 100)
print("✅ SECTION 4D.3 FORENSIC AUDIT COMPLETE")
print("✅ 300 / 300 WINNER ATTRIBUTIONS VERIFIED")
print("✅ 150 PLAYER-SIDE EVALUATIONS VERIFIED")
print("✅ 150 OPPONENT-SIDE EVALUATIONS VERIFIED")
print("✅ EXACT MIRRORED CARD PAIRS ARE NOT PART OF THE LOCKED SCHEDULE CONTRACT")
print()
print(
    "R3 Player-side wins   :",
    player_win_count_4d3,
    "/ 150",
)
print(
    "R3 Opponent-side wins :",
    opponent_win_count_4d3,
    "/ 150",
)
print()
print("⚠️ ALL 150 MATCHES WITH R3 AS OPPONENT RECORDED PLAYER AS WINNER")
print("⚠️ THIS IS NOW A CONFIRMED FORENSIC SIGNAL, NOT A 4D.2 COUNTING ERROR")
print()
print("➡️ NEXT: AUDIT THE TOURNAMENT ADAPTER / STATE ORIENTATION")
print("=" * 100)

====================================================================================================
SECTION 4D.3 — SIDE-ORIENTATION FORENSIC AUDIT
====================================================================================================

AUTHORITATIVE AUDIT INPUT
----------------------------------------------------------------------------------------------------
Rows: 300
Columns available: 26

WINNER ATTRIBUTION CHECK
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,all stored R3 outcomes agree with winner + eva...,300,300,True

SIDE-LEVEL WINNER ATTRIBUTION
----------------------------------------------------------------------------------------------------

,evaluated_agent_side,matches,player_winners,opponent_winners,stored_r3_wins,reconstructed_r3_wins,win_reconstruction_agrees
0,Opponent,150,150,0,0,0,True
1,Player,150,27,123,27,27,True

FIRST 20 ORIENTATION RECORDS
----------------------------------------------------------------------------------------------------

,match_id,player_card,opponent_card,starting_side,evaluated_agent_side,winner,r3_outcome
0,1,Pikachu,Charmander,Player,Player,Player,WIN
1,2,Charmander,Eevee,Player,Opponent,Player,LOSS
2,3,Squirtle,Charmander,Opponent,Player,Opponent,LOSS
3,4,Bulbasaur,Eevee,Opponent,Opponent,Player,LOSS
4,5,Eevee,Charmander,Player,Player,Opponent,LOSS
5,6,Meowth,Eevee,Player,Opponent,Player,LOSS
6,7,Pikachu,Charmander,Opponent,Player,Opponent,LOSS
7,8,Charmander,Eevee,Opponent,Opponent,Player,LOSS
8,9,Squirtle,Charmander,Player,Player,Opponent,LOSS
9,10,Bulbasaur,Eevee,Player,Opponent,Player,LOSS
10,11,Eevee,Charmander,Opponent,Player,Opponent,LOSS
11,12,Meowth,Eevee,Opponent,Opponent,Player,LOSS
12,13,Pikachu,Charmander,Player,Player,Player,WIN
13,14,Charmander,Eevee,Player,Opponent,Player,LOSS
14,15,Squirtle,Charmander,Opponent,Player,Opponent,LOSS
15,16,Bulbasaur,Eevee,Opponent,Opponent,Player,LOSS
16,17,Eevee,Charmander,Player,Player,Opponent,LOSS
17,18,Meowth,Eevee,Player,Opponent,Player,LOSS
18,19,Pikachu,Charmander,Opponent,Player,Player,WIN
19,20,Charmander,Eevee,Opponent,Opponent,Player,LOSS

CARD PAIR × EVALUATED SIDE COUNTS
----------------------------------------------------------------------------------------------------

  player_card opponent_card evaluated_agent_side  matches
0   Bulbasaur         Eevee             Opponent       51
1  Charmander         Eevee             Opponent       51
2       Eevee    Charmander               Player       48
3      Meowth         Eevee             Opponent       48
4     Pikachu    Charmander               Player       51
5    Squirtle    Charmander               Player       51

CARD PAIRS AVAILABLE ON BOTH EVALUATED SIDES
----------------------------------------------------------------------------------------------------

Empty DataFrame
Columns: [player_card, opponent_card, evaluated_side_count]
Index: []

FORENSIC SAMPLE — R3 EVALUATED AS PLAYER
----------------------------------------------------------------------------------------------------

,match_id,baseline_name,player_card,opponent_card,starting_side,evaluated_agent_side,winner,r3_outcome,r3_score_reconstructed,fallback_count
0,1,Random Baseline,Pikachu,Charmander,Player,Player,Player,WIN,1.0,0
2,3,Random Baseline,Squirtle,Charmander,Opponent,Player,Opponent,LOSS,0.0,3
4,5,Random Baseline,Eevee,Charmander,Player,Player,Opponent,LOSS,0.0,3
6,7,Random Baseline,Pikachu,Charmander,Opponent,Player,Opponent,LOSS,0.0,0
8,9,Random Baseline,Squirtle,Charmander,Player,Player,Opponent,LOSS,0.0,3
10,11,Random Baseline,Eevee,Charmander,Opponent,Player,Opponent,LOSS,0.0,1
12,13,Random Baseline,Pikachu,Charmander,Player,Player,Player,WIN,1.0,0
14,15,Random Baseline,Squirtle,Charmander,Opponent,Player,Opponent,LOSS,0.0,3
16,17,Random Baseline,Eevee,Charmander,Player,Player,Opponent,LOSS,0.0,2
18,19,Random Baseline,Pikachu,Charmander,Opponent,Player,Player,WIN,1.0,0
20,21,Random Baseline,Squirtle,Charmander,Player,Player,Opponent,LOSS,0.0,3
22,23,Random Baseline,Eevee,Charmander,Opponent,Player,Opponent,LOSS,0.0,4

FORENSIC SAMPLE — R3 EVALUATED AS OPPONENT
----------------------------------------------------------------------------------------------------

,match_id,baseline_name,player_card,opponent_card,starting_side,evaluated_agent_side,winner,r3_outcome,r3_score_reconstructed,fallback_count
1,2,Random Baseline,Charmander,Eevee,Player,Opponent,Player,LOSS,0.0,1
3,4,Random Baseline,Bulbasaur,Eevee,Opponent,Opponent,Player,LOSS,0.0,2
5,6,Random Baseline,Meowth,Eevee,Player,Opponent,Player,LOSS,0.0,1
7,8,Random Baseline,Charmander,Eevee,Opponent,Opponent,Player,LOSS,0.0,4
9,10,Random Baseline,Bulbasaur,Eevee,Player,Opponent,Player,LOSS,0.0,1
11,12,Random Baseline,Meowth,Eevee,Opponent,Opponent,Player,LOSS,0.0,2
13,14,Random Baseline,Charmander,Eevee,Player,Opponent,Player,LOSS,0.0,2
15,16,Random Baseline,Bulbasaur,Eevee,Opponent,Opponent,Player,LOSS,0.0,3
17,18,Random Baseline,Meowth,Eevee,Player,Opponent,Player,LOSS,0.0,2
19,20,Random Baseline,Charmander,Eevee,Opponent,Opponent,Player,LOSS,0.0,2
21,22,Random Baseline,Bulbasaur,Eevee,Player,Opponent,Player,LOSS,0.0,1
23,24,Random Baseline,Meowth,Eevee,Opponent,Opponent,Player,LOSS,0.0,2

WINNER DISTRIBUTION BY EVALUATED-AGENT SIDE
----------------------------------------------------------------------------------------------------

  evaluated_agent_side    winner  matches
0             Opponent    Player      150
1               Player  Opponent      123
2               Player    Player       27

EVALUATED SIDE × STARTING SIDE × WINNER
----------------------------------------------------------------------------------------------------

  evaluated_agent_side starting_side    winner  matches
0             Opponent      Opponent    Player       75
1             Opponent        Player    Player       75
2               Player      Opponent  Opponent       64
3               Player      Opponent    Player       11
4               Player        Player  Opponent       59
5               Player        Player    Player       16

BASELINE × EVALUATED SIDE × WINNER
----------------------------------------------------------------------------------------------------

             baseline_name evaluated_agent_side    winner  matches
0  Depth-6 Search Baseline             Opponent    Player       50
1  Depth-6 Search Baseline               Player  Opponent       33
2  Depth-6 Search Baseline               Player    Player       17
3   Greedy Damage Baseline             Opponent    Player       50
4   Greedy Damage Baseline               Player  Opponent       50
5          Random Baseline             Opponent    Player       50
6          Random Baseline               Player  Opponent       40
7          Random Baseline               Player    Player       10

EXTREME SIDE-ASYMMETRY CHECK
----------------------------------------------------------------------------------------------------
R3 Player-side wins   : 27 / 150
R3 Opponent-side wins : 0 / 150
Player winner when R3 is Opponent: 150 / 150

SECTION 4D.3 VALIDATION
----------------------------------------------------------------------------------------------------

,validation,observed,expected,passed
0,300 authoritative benchmark rows audited,300,300,True
1,winner attribution agrees for every match,300,300,True
2,150 Player-side evaluations,150,150,True
3,150 Opponent-side evaluations,150,150,True
4,Player-side R3 wins reconstructed,27,27,True
5,Opponent-side R3 wins reconstructed,0,0,True
6,all Opponent-side R3 matches recorded Player w...,150,150,True
7,exact mirrored card pairs required,0,not required,True

====================================================================================================
✅ SECTION 4D.3 FORENSIC AUDIT COMPLETE
✅ 300 / 300 WINNER ATTRIBUTIONS VERIFIED
✅ 150 PLAYER-SIDE EVALUATIONS VERIFIED
✅ 150 OPPONENT-SIDE EVALUATIONS VERIFIED
✅ EXACT MIRRORED CARD PAIRS ARE NOT PART OF THE LOCKED SCHEDULE CONTRACT

R3 Player-side wins   : 27 / 150
R3 Opponent-side wins : 0 / 150

⚠️ ALL 150 MATCHES WITH R3 AS OPPONENT RECORDED PLAYER AS WINNER
⚠️ THIS IS NOW A CONFIRMED FORENSIC SIGNAL, NOT A 4D.2 COUNTING ERROR

➡️ NEXT: AUDIT THE TOURNAMENT ADAPTER / STATE ORIENTATION
====================================================================================================

In [7]:
# ======================================================================================
# SECTION 4D.4 — TOURNAMENT ADAPTER / STATE-ORIENTATION SOURCE AUDIT
# ======================================================================================
#
# PURPOSE
# -------
# Investigate the confirmed side-asymmetry discovered in Section 4D.3:
#
#     R3 evaluated as Player   : 27 / 150 wins
#     R3 evaluated as Opponent :  0 / 150 wins
#
# This section DOES NOT:
#   - retrain R3
#   - modify the frozen model
#   - modify the benchmark
#   - rerun the 300 matches
#   - modify production source code
#
# It only locates and inspects the tournament execution/orientation code.
# ======================================================================================

from pathlib import Path
import re


# --------------------------------------------------------------------------------------
# 1. Project root
# --------------------------------------------------------------------------------------

project_root_4d4 = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

assert project_root_4d4.exists(), (
    f"Project root not found: {project_root_4d4}"
)

print("=" * 100)
print("SECTION 4D.4 — TOURNAMENT ADAPTER / STATE-ORIENTATION SOURCE AUDIT")
print("=" * 100)

print()
print("Project root:")
print(project_root_4d4)


# --------------------------------------------------------------------------------------
# 2. Search Python source files
# --------------------------------------------------------------------------------------

source_roots_4d4 = [
    project_root_4d4 / "src",
    project_root_4d4 / "scripts",
]

python_files_4d4 = []

for source_root in source_roots_4d4:

    if source_root.exists():

        python_files_4d4.extend(
            source_root.rglob("*.py")
        )

python_files_4d4 = sorted(
    set(python_files_4d4)
)

print()
print("Python source files discovered:", len(python_files_4d4))


# --------------------------------------------------------------------------------------
# 3. Search for high-value tournament/orientation symbols
# --------------------------------------------------------------------------------------

search_terms_4d4 = [
    "R3TournamentAgentAdapter",
    "run_tournament_match",
    "evaluated_agent_side",
    "starting_side",
    "player_agent",
    "opponent_agent",
    "agent_result",
    "winner",
    "predict",
    "predict_proba",
    "feature",
]


hits_4d4 = {
    term: []
    for term in search_terms_4d4
}


for py_file in python_files_4d4:

    try:

        text = py_file.read_text(
            encoding="utf-8",
            errors="replace",
        )

    except Exception:

        continue

    lines = text.splitlines()

    for line_number, line in enumerate(
        lines,
        start=1,
    ):

        for term in search_terms_4d4:

            if term.lower() in line.lower():

                hits_4d4[term].append(
                    {
                        "file": str(
                            py_file.relative_to(
                                project_root_4d4
                            )
                        ),
                        "line": line_number,
                        "text": line.strip(),
                    }
                )


# --------------------------------------------------------------------------------------
# 4. Print high-priority symbol locations
# --------------------------------------------------------------------------------------

priority_terms_4d4 = [
    "R3TournamentAgentAdapter",
    "run_tournament_match",
    "evaluated_agent_side",
]


print()
print("=" * 100)
print("HIGH-PRIORITY SYMBOL LOCATIONS")
print("=" * 100)


for term in priority_terms_4d4:

    print()
    print(f"[{term}]")

    term_hits = hits_4d4.get(
        term,
        [],
    )

    if not term_hits:

        print("  NOT FOUND")
        continue

    for hit in term_hits[:30]:

        print(
            f"  {hit['file']}:{hit['line']}"
        )

        print(
            f"      {hit['text']}"
        )


# --------------------------------------------------------------------------------------
# 5. Identify likely adapter / tournament source files
# --------------------------------------------------------------------------------------

candidate_files_4d4 = set()


for term in [
    "R3TournamentAgentAdapter",
    "run_tournament_match",
]:

    for hit in hits_4d4.get(
        term,
        [],
    ):

        candidate_files_4d4.add(
            hit["file"]
        )


candidate_files_4d4 = sorted(
    candidate_files_4d4
)


print()
print("=" * 100)
print("CANDIDATE EXECUTION FILES")
print("=" * 100)


if candidate_files_4d4:

    for candidate in candidate_files_4d4:

        print(candidate)

else:

    print(
        "No direct adapter/tournament source file "
        "was found under src/ or scripts/."
    )


# --------------------------------------------------------------------------------------
# 6. Print source context around critical definitions
# --------------------------------------------------------------------------------------

def print_source_context_4d4(
    relative_file,
    target_terms,
    context_before=20,
    context_after=80,
):

    full_path = (
        project_root_4d4
        /
        relative_file
    )

    if not full_path.exists():

        print(
            f"Missing source file: {full_path}"
        )
        return

    text = full_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    lines = text.splitlines()

    matching_indices = []

    for idx, line in enumerate(lines):

        if any(
            term.lower() in line.lower()
            for term in target_terms
        ):

            matching_indices.append(idx)

    if not matching_indices:

        return

    # Avoid printing dozens of overlapping blocks.
    selected_indices = []

    for idx in matching_indices:

        if not selected_indices:

            selected_indices.append(idx)

        elif (
            idx - selected_indices[-1]
            >
            context_after
        ):

            selected_indices.append(idx)

    for idx in selected_indices[:10]:

        start = max(
            0,
            idx - context_before,
        )

        end = min(
            len(lines),
            idx + context_after + 1,
        )

        print()
        print("=" * 100)
        print(
            f"SOURCE CONTEXT: {relative_file}"
        )
        print(
            f"AROUND LINE: {idx + 1}"
        )
        print("=" * 100)

        for line_idx in range(
            start,
            end,
        ):

            marker = (
                ">>>"
                if line_idx == idx
                else "   "
            )

            print(
                f"{marker} "
                f"{line_idx + 1:5d}: "
                f"{lines[line_idx]}"
            )


for candidate in candidate_files_4d4:

    print_source_context_4d4(
        candidate,
        target_terms=[
            "R3TournamentAgentAdapter",
            "run_tournament_match",
            "evaluated_agent_side",
        ],
    )


# --------------------------------------------------------------------------------------
# 7. Search specifically for player/opponent state-selection patterns
# --------------------------------------------------------------------------------------

orientation_patterns_4d4 = [
    r"\[\s*[\"']player[\"']\s*\]",
    r"\[\s*[\"']opponent[\"']\s*\]",
    r"\.player\b",
    r"\.opponent\b",
    r"player_state",
    r"opponent_state",
    r"player_card",
    r"opponent_card",
    r"current_player",
    r"active_player",
    r"agent_side",
    r"side\s*==",
    r"side\s*!=",
]


orientation_hits_4d4 = []


for relative_file in candidate_files_4d4:

    full_path = (
        project_root_4d4
        /
        relative_file
    )

    text = full_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    for line_number, line in enumerate(
        text.splitlines(),
        start=1,
    ):

        if any(
            re.search(
                pattern,
                line,
                flags=re.IGNORECASE,
            )
            for pattern in orientation_patterns_4d4
        ):

            orientation_hits_4d4.append(
                {
                    "file": relative_file,
                    "line": line_number,
                    "text": line.strip(),
                }
            )


print()
print("=" * 100)
print("PLAYER / OPPONENT ORIENTATION REFERENCES")
print("=" * 100)


if orientation_hits_4d4:

    for hit in orientation_hits_4d4[:150]:

        print(
            f"{hit['file']}:{hit['line']}"
        )

        print(
            f"    {hit['text']}"
        )

else:

    print(
        "No explicit player/opponent orientation "
        "references found in candidate files."
    )


# --------------------------------------------------------------------------------------
# 8. Search for adapter class definitions anywhere in project Python source
# --------------------------------------------------------------------------------------

class_definition_hits_4d4 = []


for py_file in python_files_4d4:

    text = py_file.read_text(
        encoding="utf-8",
        errors="replace",
    )

    for line_number, line in enumerate(
        text.splitlines(),
        start=1,
    ):

        stripped = line.strip()

        if (
            stripped.startswith("class ")
            or
            stripped.startswith("def ")
        ):

            if any(
                token.lower() in stripped.lower()
                for token in [
                    "adapter",
                    "tournament",
                    "agent",
                    "match",
                    "feature",
                    "state",
                ]
            ):

                class_definition_hits_4d4.append(
                    {
                        "file": str(
                            py_file.relative_to(
                                project_root_4d4
                            )
                        ),
                        "line": line_number,
                        "definition": stripped,
                    }
                )


print()
print("=" * 100)
print("RELEVANT CLASS / FUNCTION DEFINITIONS")
print("=" * 100)


for hit in class_definition_hits_4d4[:200]:

    print(
        f"{hit['file']}:{hit['line']} "
        f"{hit['definition']}"
    )


# --------------------------------------------------------------------------------------
# 9. Audit conclusion
# --------------------------------------------------------------------------------------

adapter_found_4d4 = (
    len(
        hits_4d4[
            "R3TournamentAgentAdapter"
        ]
    )
    > 0
)

runner_found_4d4 = (
    len(
        hits_4d4[
            "run_tournament_match"
        ]
    )
    > 0
)


print()
print("=" * 100)
print("SECTION 4D.4 SOURCE-DISCOVERY SUMMARY")
print("=" * 100)

print(
    "R3TournamentAgentAdapter found :",
    adapter_found_4d4,
)

print(
    "run_tournament_match found     :",
    runner_found_4d4,
)

print(
    "Candidate execution files      :",
    len(candidate_files_4d4),
)

print(
    "Orientation references found   :",
    len(orientation_hits_4d4),
)


print()
print("IMPORTANT:")
print(
    "This section performed READ-ONLY source inspection."
)
print(
    "No R3 model, source file, benchmark artifact, "
    "or tournament result was modified."
)


print()
print("=" * 100)

if (
    adapter_found_4d4
    or
    runner_found_4d4
):

    print(
        "✅ SECTION 4D.4 SOURCE DISCOVERY COMPLETE"
    )

    print(
        "➡️ REVIEW THE PRINTED ADAPTER / MATCH-RUNNER "
        "SOURCE BEFORE MAKING ANY CORRECTION"
    )

else:

    print(
        "⚠️ DIRECT ADAPTER SYMBOLS WERE NOT FOUND "
        "UNDER src/ OR scripts/"
    )

    print(
        "➡️ DO NOT MODIFY ANYTHING YET — "
        "EXPAND SOURCE DISCOVERY FIRST"
    )

print("=" * 100)

====================================================================================================
SECTION 4D.4 — TOURNAMENT ADAPTER / STATE-ORIENTATION SOURCE AUDIT
====================================================================================================

Project root:
D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge

Python source files discovered: 143

====================================================================================================
HIGH-PRIORITY SYMBOL LOCATIONS
====================================================================================================

[R3TournamentAgentAdapter]
  NOT FOUND

[run_tournament_match]
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2696
      def run_tournament_match(
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3008
      smoke_result = run_tournament_match(
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3458
      result = run_tournament_match(

[evaluated_agent_side]
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2703
      evaluated_agent_side: str,
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2711
      if evaluated_agent_side not in {
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2716
      "evaluated_agent_side must be "
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2800
      if evaluated_agent_side == "Player":
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:2863
      elif winner == evaluated_agent_side:
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3027
      evaluated_agent_side=
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3391
      "evaluated_agent_side":
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3483
      evaluated_agent_side=
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3485
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3502
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3504
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3556
      "evaluated_agent_side":
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3558
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:3750
      "evaluated_agent_side",
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4184
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4508
      "evaluated_agent_side":
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4511
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4634
      "evaluated_agent_side",
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4668
      "evaluated_agent_side":
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4726
      "evaluated_agent_side"
  scripts\48_tournament_evaluation_and_elo_benchmarking.py:4733
      "evaluated_agent_side"
  scripts\49_side_balanced_search_guided_self_play.py:1265
      "evaluated_agent_side",
  scripts\49_side_balanced_search_guided_self_play.py:1404
      side_column = "evaluated_agent_side"
  scripts\49_side_balanced_search_guided_self_play.py:5257
      "evaluated_agent_side",
  scripts\49_side_balanced_search_guided_self_play.py:5335
      "evaluated_agent_side"
  scripts\49_side_balanced_search_guided_self_play.py:6141
      "evaluated_agent_side",
  scripts\49_side_balanced_search_guided_self_play.py:6446
      "evaluated_agent_side",

====================================================================================================
CANDIDATE EXECUTION FILES
====================================================================================================
scripts\48_tournament_evaluation_and_elo_benchmarking.py

====================================================================================================
SOURCE CONTEXT: scripts\48_tournament_evaluation_and_elo_benchmarking.py
AROUND LINE: 2696
====================================================================================================
     2676: @dataclass
     2677: class TournamentMatchResult:
     2678:     match_id: int
     2679:     agent_name: str
     2680:     baseline_name: str
     2681:     player_card: str
     2682:     opponent_card: str
     2683:     starting_side: str
     2684:     winner: str | None
     2685:     turns: int
     2686:     stop_reason: str | None
     2687:     agent_result: float
     2688:     fallback_count: int
     2689:     elapsed_seconds: float
     2690:
     2691:
     2692: # ------------------------------------------------------------
     2693: # 3.11 â€” Run one simulator match
     2694: # ------------------------------------------------------------
     2695:
>>>  2696: def run_tournament_match(
     2697:     match_id: int,
     2698:     evaluated_agent: Any,
     2699:     baseline_agent: Any,
     2700:     player_card: dict[str, Any],
     2701:     opponent_card: dict[str, Any],
     2702:     starting_side: str,
     2703:     evaluated_agent_side: str,
     2704:     max_turns: int =
     2705:         MAX_TURNS_PER_MATCH,
     2706:     search_depth: int =
     2707:         SIMULATOR_SEARCH_DEPTH,
     2708:     verbose: bool =
     2709:         VERBOSE_MATCHES,
     2710: ) -> TournamentMatchResult:
     2711:     if evaluated_agent_side not in {
     2712:         "Player",
     2713:         "Opponent",
     2714:     }:
     2715:         raise ValueError(
     2716:             "evaluated_agent_side must be "
     2717:             "'Player' or 'Opponent'."
     2718:         )
     2719:
     2720:     initial_state = (
     2721:         create_tournament_state(
     2722:             player_card=
     2723:                 player_card,
     2724:
     2725:             opponent_card=
     2726:                 opponent_card,
     2727:
     2728:             starting_side=
     2729:                 starting_side,
     2730:         )
     2731:     )
     2732:
     2733:     class SideAwareAgent:
     2734:         def __init__(
     2735:             self,
     2736:             player_agent: Any,
     2737:             opponent_agent: Any,
     2738:         ) -> None:
     2739:             self.player_agent = (
     2740:                 player_agent
     2741:             )
     2742:
     2743:             self.opponent_agent = (
     2744:                 opponent_agent
     2745:             )
     2746:
     2747:             self.fallback_count = 0
     2748:
     2749:         def choose_move(
     2750:             self,
     2751:             state: Any = None,
     2752:             depth: int | None = None,
     2753:             battle_state: Any = None,
     2754:             **kwargs: Any,
     2755:         ) -> Any:
     2756:             resolved_state = (
     2757:                 state
     2758:                 if state is not None
     2759:                 else battle_state
     2760:             )
     2761:
     2762:             if resolved_state is None:
     2763:                 raise ValueError(
     2764:                     "A battle state is required."
     2765:                 )
     2766:
     2767:             side = str(
     2768:                 resolved_state
     2769:                 .current_player
     2770:             )
     2771:
     2772:             selected_agent = (
     2773:                 self.player_agent
     2774:                 if side == "Player"
     2775:                 else self.opponent_agent
     2776:             )

====================================================================================================
SOURCE CONTEXT: scripts\48_tournament_evaluation_and_elo_benchmarking.py
AROUND LINE: 2800
====================================================================================================
     2780:                 .choose_move(
     2781:                     state=
     2782:                         resolved_state,
     2783:
     2784:                     depth=
     2785:                         depth,
     2786:                 )
     2787:             )
     2788:
     2789:             if bool(
     2790:                 getattr(
     2791:                     decision,
     2792:                     "fallback",
     2793:                     False,
     2794:                 )
     2795:             ):
     2796:                 self.fallback_count += 1
     2797:
     2798:             return decision
     2799:
>>>  2800:     if evaluated_agent_side == "Player":
     2801:         side_agent = SideAwareAgent(
     2802:             player_agent=
     2803:                 evaluated_agent,
     2804:
     2805:             opponent_agent=
     2806:                 baseline_agent,
     2807:         )
     2808:
     2809:     else:
     2810:         side_agent = SideAwareAgent(
     2811:             player_agent=
     2812:                 baseline_agent,
     2813:
     2814:             opponent_agent=
     2815:                 evaluated_agent,
     2816:         )
     2817:
     2818:     start_time = time.perf_counter()
     2819:
     2820:     simulation = simulate_ai_battle(
     2821:         initial_state=
     2822:             initial_state,
     2823:
     2824:         agent=
     2825:             side_agent,
     2826:
     2827:         search_depth=
     2828:             search_depth,
     2829:
     2830:         max_turns=
     2831:             max_turns,
     2832:
     2833:         verbose=
     2834:             verbose,
     2835:     )
     2836:
     2837:     elapsed_seconds = (
     2838:         time.perf_counter()
     2839:         - start_time
     2840:     )
     2841:
     2842:     winner = getattr(
     2843:         simulation,
     2844:         "winner",
     2845:         None,
     2846:     )
     2847:
     2848:     turns = getattr(
     2849:         simulation,
     2850:         "turns",
     2851:         [],
     2852:     )
     2853:
     2854:     stop_reason = getattr(
     2855:         simulation,
     2856:         "stop_reason",
     2857:         None,
     2858:     )
     2859:
     2860:     if winner is None:
     2861:         agent_result = 0.5
     2862:
     2863:     elif winner == evaluated_agent_side:
     2864:         agent_result = 1.0
     2865:
     2866:     else:
     2867:         agent_result = 0.0
     2868:
     2869:     return TournamentMatchResult(
     2870:         match_id=
     2871:             int(match_id),
     2872:
     2873:         agent_name=
     2874:             str(
     2875:                 getattr(
     2876:                     evaluated_agent,
     2877:                     "name",
     2878:                     type(
     2879:                         evaluated_agent
     2880:                     ).__name__,

====================================================================================================
SOURCE CONTEXT: scripts\48_tournament_evaluation_and_elo_benchmarking.py
AROUND LINE: 3008
====================================================================================================
     2988: # ------------------------------------------------------------
     2989:
     2990: smoke_test_results = []
     2991:
     2992: smoke_player_card = (
     2993:     TOURNAMENT_CARD_TEMPLATES[0]
     2994: )
     2995:
     2996: smoke_opponent_card = (
     2997:     TOURNAMENT_CARD_TEMPLATES[1]
     2998: )
     2999:
     3000: for smoke_index, baseline_agent in enumerate(
     3001:     [
     3002:         random_baseline_agent,
     3003:         greedy_baseline_agent,
     3004:         search_baseline_agent,
     3005:     ],
     3006:     start=1,
     3007: ):
>>>  3008:     smoke_result = run_tournament_match(
     3009:         match_id=
     3010:             smoke_index,
     3011:
     3012:         evaluated_agent=
     3013:             competitive_tournament_agent,
     3014:
     3015:         baseline_agent=
     3016:             baseline_agent,
     3017:
     3018:         player_card=
     3019:             smoke_player_card,
     3020:
     3021:         opponent_card=
     3022:             smoke_opponent_card,
     3023:
     3024:         starting_side=
     3025:             "Player",
     3026:
     3027:         evaluated_agent_side=
     3028:             "Player",
     3029:
     3030:         max_turns=
     3031:             20,
     3032:
     3033:         search_depth=
     3034:             SIMULATOR_SEARCH_DEPTH,
     3035:
     3036:         verbose=False,
     3037:     )
     3038:
     3039:     smoke_test_results.append(
     3040:         dataclasses.asdict(
     3041:             smoke_result
     3042:         )
     3043:     )
     3044:
     3045:
     3046: smoke_test_df = pd.DataFrame(
     3047:     smoke_test_results
     3048: )
     3049:
     3050:
     3051: # ------------------------------------------------------------
     3052: # 3.14 â€” Save adapter report
     3053: # ------------------------------------------------------------
     3054:
     3055: MATCH_ADAPTER_REPORT_FILE = (
     3056:     NOTEBOOK48_REPORT_DIR
     3057:     / "tournament_match_adapter_summary.json"
     3058: )
     3059:
     3060: match_adapter_report = {
     3061:     "competitive_agent":
     3062:         competitive_tournament_agent.name,
     3063:
     3064:     "baselines": [
     3065:         random_baseline_agent.name,
     3066:         greedy_baseline_agent.name,
     3067:         search_baseline_agent.name,
     3068:     ],
     3069:
     3070:     "simulator_signature":
     3071:         str(
     3072:             inspect.signature(
     3073:                 simulate_ai_battle
     3074:             )
     3075:         ),
     3076:
     3077:     "smoke_tests":
     3078:         smoke_test_results,
     3079:
     3080:     "all_smoke_tests_completed":
     3081:         bool(
     3082:             len(smoke_test_results)
     3083:             == 3
     3084:         ),
     3085:
     3086:     "fallbacks":
     3087:         int(
     3088:             smoke_test_df[

====================================================================================================
SOURCE CONTEXT: scripts\48_tournament_evaluation_and_elo_benchmarking.py
AROUND LINE: 3391
====================================================================================================
     3371:                 second_card_index + 1
     3372:             ) % card_count
     3373:
     3374:         player_card = (
     3375:             TOURNAMENT_CARD_TEMPLATES[
     3376:                 first_card_index
     3377:             ]
     3378:         )
     3379:
     3380:         opponent_card = (
     3381:             TOURNAMENT_CARD_TEMPLATES[
     3382:                 second_card_index
     3383:             ]
     3384:         )
     3385:
     3386:         schedule.append(
     3387:             {
     3388:                 "baseline_name":
     3389:                     baseline_name,
     3390:
>>>  3391:                 "evaluated_agent_side":
     3392:                     evaluated_side,
     3393:
     3394:                 "starting_side":
     3395:                     starting_side,
     3396:
     3397:                 "player_card":
     3398:                     player_card,
     3399:
     3400:                 "opponent_card":
     3401:                     opponent_card,
     3402:             }
     3403:         )
     3404:
     3405:     return schedule
     3406:
     3407:
     3408: full_schedule = []
     3409:
     3410: for baseline_name in (
     3411:     baseline_factories
     3412: ):
     3413:     full_schedule.extend(
     3414:         build_balanced_schedule(
     3415:             baseline_name=
     3416:                 baseline_name,
     3417:
     3418:             match_count=
     3419:                 TOURNAMENT_MATCHES_PER_BASELINE,
     3420:         )
     3421:     )
     3422:
     3423:
     3424: # ------------------------------------------------------------
     3425: # 4.6 â€” Run tournament
     3426: # ------------------------------------------------------------
     3427:
     3428: tournament_rows = []
     3429:
     3430: tournament_failures = []
     3431:
     3432: tournament_start = time.perf_counter()
     3433:
     3434: for global_match_index, scheduled_match in enumerate(
     3435:     full_schedule,
     3436:     start=1,
     3437: ):
     3438:     baseline_name = (
     3439:         scheduled_match[
     3440:             "baseline_name"
     3441:         ]
     3442:     )
     3443:
     3444:     try:
     3445:         evaluated_agent = (
     3446:             create_competitive_agent()
     3447:         )
     3448:
     3449:         baseline_agent = (
     3450:             baseline_factories[
     3451:                 baseline_name
     3452:             ](
     3453:                 TOURNAMENT_RANDOM_SEED
     3454:                 + global_match_index
     3455:             )
     3456:         )
     3457:
     3458:         result = run_tournament_match(
     3459:             match_id=
     3460:                 global_match_index,
     3461:
     3462:             evaluated_agent=
     3463:                 evaluated_agent,
     3464:
     3465:             baseline_agent=
     3466:                 baseline_agent,
     3467:
     3468:             player_card=
     3469:                 scheduled_match[
     3470:                     "player_card"
     3471:                 ],

====================================================================================================
SOURCE CONTEXT: scripts\48_tournament_evaluation_and_elo_benchmarking.py
AROUND LINE: 3483
====================================================================================================
     3463:                 evaluated_agent,
     3464:
     3465:             baseline_agent=
     3466:                 baseline_agent,
     3467:
     3468:             player_card=
     3469:                 scheduled_match[
     3470:                     "player_card"
     3471:                 ],
     3472:
     3473:             opponent_card=
     3474:                 scheduled_match[
     3475:                     "opponent_card"
     3476:                 ],
     3477:
     3478:             starting_side=
     3479:                 scheduled_match[
     3480:                     "starting_side"
     3481:                 ],
     3482:
>>>  3483:             evaluated_agent_side=
     3484:                 scheduled_match[
     3485:                     "evaluated_agent_side"
     3486:                 ],
     3487:
     3488:             max_turns=
     3489:                 MAX_TURNS_PER_MATCH,
     3490:
     3491:             search_depth=
     3492:                 SIMULATOR_SEARCH_DEPTH,
     3493:
     3494:             verbose=False,
     3495:         )
     3496:
     3497:         result_row = dataclasses.asdict(
     3498:             result
     3499:         )
     3500:
     3501:         result_row[
     3502:             "evaluated_agent_side"
     3503:         ] = scheduled_match[
     3504:             "evaluated_agent_side"
     3505:         ]
     3506:
     3507:         result_row[
     3508:             "baseline_result"
     3509:         ] = (
     3510:             1.0
     3511:             - float(
     3512:                 result.agent_result
     3513:             )
     3514:         )
     3515:
     3516:         result_row[
     3517:             "draw"
     3518:         ] = bool(
     3519:             float(
     3520:                 result.agent_result
     3521:             )
     3522:             == 0.5
     3523:         )
     3524:
     3525:         result_row[
     3526:             "competitive_win"
     3527:         ] = bool(

In [8]:
# ======================================================================================
# SECTION 4D.5 — COMPETITIVE POLICY / ACTOR-PERSPECTIVE SOURCE AUDIT
# ======================================================================================
#
# PURPOSE
# -------
# Section 4D.3 confirmed:
#
#     R3 as Player   : 27 / 150 wins
#     R3 as Opponent :  0 / 150 wins
#
# Section 4D.4 confirmed that run_tournament_match() explicitly routes:
#
#     evaluated_agent -> Player slot   when evaluated_agent_side == "Player"
#     evaluated_agent -> Opponent slot when evaluated_agent_side == "Opponent"
#
# Therefore, before modifying the tournament runner, inspect the next layer:
#
#   1. create_tournament_state()
#   2. CompetitivePolicyAgent
#   3. CompetitivePolicyAgent.choose_move()
#   4. encode_state()
#   5. actor-relative feature encoding
#   6. current_player handling
#
# READ ONLY:
#   - no source files modified
#   - no model modified
#   - no retraining
#   - no benchmark rerun
# ======================================================================================

from pathlib import Path
import re


project_root_4d5 = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

assert project_root_4d5.exists()


print("=" * 100)
print("SECTION 4D.5 — COMPETITIVE POLICY / ACTOR-PERSPECTIVE SOURCE AUDIT")
print("=" * 100)


# --------------------------------------------------------------------------------------
# 1. Critical source files identified by 4D.4
# --------------------------------------------------------------------------------------

critical_files_4d5 = [
    project_root_4d5
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py",

    project_root_4d5
    / "scripts"
    / "47_competitive_policy_training.py",

    project_root_4d5
    / "scripts"
    / "46_competitive_policy_dataset_generation.py",
]


print()
print("CRITICAL SOURCE FILES")
print("-" * 100)

for path in critical_files_4d5:
    print(
        f"{path.relative_to(project_root_4d5)} "
        f"[exists={path.exists()}]"
    )


# --------------------------------------------------------------------------------------
# 2. Helper — print source around exact definitions
# --------------------------------------------------------------------------------------

def print_definition_context_4d5(
    file_path,
    search_patterns,
    before=15,
    after=140,
):
    if not file_path.exists():
        return

    text = file_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    lines = text.splitlines()

    found_indices = []

    for idx, line in enumerate(lines):

        stripped = line.strip()

        if any(
            re.search(
                pattern,
                stripped,
                flags=re.IGNORECASE,
            )
            for pattern in search_patterns
        ):
            found_indices.append(idx)

    for idx in found_indices:

        print()
        print("=" * 100)
        print(
            "SOURCE:",
            file_path.relative_to(
                project_root_4d5
            )
        )
        print(
            "MATCH LINE:",
            idx + 1
        )
        print("=" * 100)

        start = max(
            0,
            idx - before,
        )

        end = min(
            len(lines),
            idx + after + 1,
        )

        for line_idx in range(
            start,
            end,
        ):

            marker = (
                ">>>"
                if line_idx == idx
                else "   "
            )

            print(
                f"{marker} "
                f"{line_idx + 1:5d}: "
                f"{lines[line_idx]}"
            )


# --------------------------------------------------------------------------------------
# 3. Inspect tournament-state construction
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT A — TOURNAMENT STATE CONSTRUCTION")
print("=" * 100)

print_definition_context_4d5(
    critical_files_4d5[0],
    [
        r"^def create_tournament_state\s*\(",
    ],
    before=20,
    after=120,
)


# --------------------------------------------------------------------------------------
# 4. Inspect CompetitivePolicyAgent
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT B — COMPETITIVE POLICY AGENT")
print("=" * 100)

print_definition_context_4d5(
    critical_files_4d5[1],
    [
        r"^class CompetitivePolicyAgent\b",
    ],
    before=20,
    after=260,
)


# --------------------------------------------------------------------------------------
# 5. Inspect encode_state()
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT C — POLICY STATE ENCODING")
print("=" * 100)

print_definition_context_4d5(
    critical_files_4d5[1],
    [
        r"^def encode_state\s*\(",
    ],
    before=20,
    after=220,
)


# --------------------------------------------------------------------------------------
# 6. Inspect actor-relative encoding from Notebook 46
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT D — ACTOR-RELATIVE TRAINING ENCODING")
print("=" * 100)

print_definition_context_4d5(
    critical_files_4d5[2],
    [
        r"^def encode_actor_relative_state\s*\(",
    ],
    before=20,
    after=240,
)


# --------------------------------------------------------------------------------------
# 7. Inspect current-player feature logic
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT E — CURRENT-PLAYER FEATURE LOGIC")
print("=" * 100)

print_definition_context_4d5(
    critical_files_4d5[2],
    [
        r"^def section9_current_player_feature\s*\(",
    ],
    before=20,
    after=140,
)


# --------------------------------------------------------------------------------------
# 8. Search critical files for perspective-sensitive expressions
# --------------------------------------------------------------------------------------

perspective_terms_4d5 = [
    "current_player",
    "player_state",
    "opponent_state",
    "player_card",
    "opponent_card",
    "actor",
    "perspective",
    "relative",
    "Player",
    "Opponent",
    "encode_state",
    "encode_actor_relative_state",
]


print()
print("=" * 100)
print("AUDIT F — PERSPECTIVE-SENSITIVE REFERENCES")
print("=" * 100)


for file_path in critical_files_4d5:

    if not file_path.exists():
        continue

    text = file_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    lines = text.splitlines()

    matches = []

    for line_number, line in enumerate(
        lines,
        start=1,
    ):

        if any(
            term.lower()
            in line.lower()
            for term in perspective_terms_4d5
        ):

            matches.append(
                (
                    line_number,
                    line.strip(),
                )
            )

    print()
    print(
        file_path.relative_to(
            project_root_4d5
        )
    )

    print("-" * 100)

    for line_number, line in matches[:250]:

        print(
            f"{line_number:5d}: {line}"
        )

    print(
        f"Perspective-sensitive references found: "
        f"{len(matches)}"
    )


# --------------------------------------------------------------------------------------
# 9. Specifically inspect choose_move definitions near CompetitivePolicyAgent
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("AUDIT G — CHOOSE_MOVE DEFINITIONS")
print("=" * 100)


for file_path in critical_files_4d5:

    if not file_path.exists():
        continue

    text = file_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    lines = text.splitlines()

    for idx, line in enumerate(lines):

        if re.search(
            r"^\s*def choose_move\s*\(",
            line,
        ):

            start = max(
                0,
                idx - 15,
            )

            end = min(
                len(lines),
                idx + 130,
            )

            print()
            print("=" * 100)

            print(
                file_path.relative_to(
                    project_root_4d5
                ),
                "choose_move around line",
                idx + 1,
            )

            print("=" * 100)

            for line_idx in range(
                start,
                end,
            ):

                marker = (
                    ">>>"
                    if line_idx == idx
                    else "   "
                )

                print(
                    f"{marker} "
                    f"{line_idx + 1:5d}: "
                    f"{lines[line_idx]}"
                )


# --------------------------------------------------------------------------------------
# 10. Read-only conclusion
# --------------------------------------------------------------------------------------

print()
print("=" * 100)
print("SECTION 4D.5 AUDIT STATUS")
print("=" * 100)

print("✅ Tournament state construction inspected")
print("✅ CompetitivePolicyAgent source inspected")
print("✅ Policy state encoder inspected")
print("✅ Actor-relative training encoder inspected")
print("✅ Current-player feature logic inspected")
print("✅ Perspective-sensitive references enumerated")

print()
print(
    "NO SOURCE CODE WAS MODIFIED."
)

print(
    "NO MODEL WAS RETRAINED OR MODIFIED."
)

print(
    "NO BENCHMARK MATCHES WERE RERUN."
)

print()
print(
    "➡️ NEXT DECISION DEPENDS ON WHETHER THE POLICY "
    "ENCODER IS ACTOR-RELATIVE OR PLAYER-ABSOLUTE."
)

print("=" * 100)

====================================================================================================
SECTION 4D.5 — COMPETITIVE POLICY / ACTOR-PERSPECTIVE SOURCE AUDIT
====================================================================================================

CRITICAL SOURCE FILES
----------------------------------------------------------------------------------------------------
scripts\48_tournament_evaluation_and_elo_benchmarking.py [exists=True]
scripts\47_competitive_policy_training.py [exists=True]
scripts\46_competitive_policy_dataset_generation.py [exists=True]

====================================================================================================
AUDIT A — TOURNAMENT STATE CONSTRUCTION
====================================================================================================

====================================================================================================
SOURCE: scripts\48_tournament_evaluation_and_elo_benchmarking.py
MATCH LINE: 2591
====================================================================================================
     2571:             },
     2572:             {
     2573:                 "Move Name":
     2574:                     "Fury Swipes",
     2575:                 "damage_numeric":
     2576:                     60,
     2577:                 "energy_cost":
     2578:                     2,
     2579:                 "Effect Explanation":
     2580:                     None,
     2581:             },
     2582:         ],
     2583:     },
     2584: ]
     2585:
     2586:
     2587: # ------------------------------------------------------------
     2588: # 3.9 â€” Build deterministic initial battle state
     2589: # ------------------------------------------------------------
     2590:
>>>  2591: def create_tournament_state(
     2592:     player_card: dict[str, Any],
     2593:     opponent_card: dict[str, Any],
     2594:     starting_side: str = "Player",
     2595:     player_energy: int = 3,
     2596:     opponent_energy: int = 3,
     2597: ) -> BattleState:
     2598:     player_card_copy = copy.deepcopy(
     2599:         player_card
     2600:     )
     2601:
     2602:     opponent_card_copy = copy.deepcopy(
     2603:         opponent_card
     2604:     )
     2605:
     2606:     return BattleState(
     2607:         player=PlayerState(
     2608:             active=PokemonState(
     2609:                 card=
     2610:                     player_card_copy,
     2611:
     2612:                 current_hp=float(
     2613:                     player_card_copy[
     2614:                         "hp"
     2615:                     ]
     2616:                 ),
     2617:
     2618:                 attached_energy=int(
     2619:                     player_energy
     2620:                 ),
     2621:
     2622:                 status=None,
     2623:
     2624:                 damage=0.0,
     2625:
     2626:                 is_active=True,
     2627:             ),
     2628:
     2629:             bench=[],
     2630:
     2631:             prize_cards_remaining=1,
     2632:
     2633:             hand_size=7,
     2634:         ),
     2635:
     2636:         opponent=PlayerState(
     2637:             active=PokemonState(
     2638:                 card=
     2639:                     opponent_card_copy,
     2640:
     2641:                 current_hp=float(
     2642:                     opponent_card_copy[
     2643:                         "hp"
     2644:                     ]
     2645:                 ),
     2646:
     2647:                 attached_energy=int(
     2648:                     opponent_energy
     2649:                 ),
     2650:
     2651:                 status=None,
     2652:
     2653:                 damage=0.0,
     2654:
     2655:                 is_active=True,
     2656:             ),
     2657:
     2658:             bench=[],
     2659:
     2660:             prize_cards_remaining=1,
     2661:
     2662:             hand_size=7,
     2663:         ),
     2664:
     2665:         turn_number=1,
     2666:
     2667:         current_player=
     2668:             starting_side,
     2669:     )
     2670:
     2671:
     2672: # ------------------------------------------------------------
     2673: # 3.10 â€” Match result structure
     2674: # ------------------------------------------------------------
     2675:
     2676: @dataclass
     2677: class TournamentMatchResult:
     2678:     match_id: int
     2679:     agent_name: str
     2680:     baseline_name: str
     2681:     player_card: str
     2682:     opponent_card: str
     2683:     starting_side: str
     2684:     winner: str | None
     2685:     turns: int
     2686:     stop_reason: str | None
     2687:     agent_result: float
     2688:     fallback_count: int
     2689:     elapsed_seconds: float
     2690:
     2691:
     2692: # ------------------------------------------------------------
     2693: # 3.11 â€” Run one simulator match
     2694: # ------------------------------------------------------------
     2695:
     2696: def run_tournament_match(
     2697:     match_id: int,
     2698:     evaluated_agent: Any,
     2699:     baseline_agent: Any,
     2700:     player_card: dict[str, Any],
     2701:     opponent_card: dict[str, Any],
     2702:     starting_side: str,
     2703:     evaluated_agent_side: str,
     2704:     max_turns: int =
     2705:         MAX_TURNS_PER_MATCH,
     2706:     search_depth: int =
     2707:         SIMULATOR_SEARCH_DEPTH,
     2708:     verbose: bool =
     2709:         VERBOSE_MATCHES,
     2710: ) -> TournamentMatchResult:
     2711:     if evaluated_agent_side not in {

====================================================================================================
AUDIT B — COMPETITIVE POLICY AGENT
====================================================================================================

====================================================================================================
SOURCE: scripts\47_competitive_policy_training.py
MATCH LINE: 4757
====================================================================================================
     4737:
     4738:
     4739: @dataclass
     4740: class CompetitivePolicyDecision:
     4741:     move: Any
     4742:     confidence: float
     4743:     selected_move_name: str | None
     4744:     probabilities: list[float]
     4745:     logits: list[float]
     4746:     move_names: list[str]
     4747:     fallback: bool
     4748:
     4749:     # Required by the production battle simulator.
     4750:     score: float = 0.0
     4751:     search_depth: int = 0
     4752:     nodes: int = 0
     4753:
     4754:     reason: str | None = None
     4755:
     4756:
>>>  4757: class CompetitivePolicyAgent:
     4758:     def __init__(
     4759:         self,
     4760:         checkpoint_path: str | Path,
     4761:         device: str | None = None,
     4762:         name: str = "Competitive Policy Agent",
     4763:     ) -> None:
     4764:         self.name = name
     4765:
     4766:         self.policy_engine = (
     4767:             CompetitivePolicyEngine(
     4768:                 checkpoint_path=
     4769:                     checkpoint_path,
     4770:
     4771:                 device=device,
     4772:             )
     4773:         )
     4774:
     4775:         self.last_decision: (
     4776:             CompetitivePolicyDecision
     4777:             | None
     4778:         ) = None
     4779:
     4780:     def choose_move(
     4781:         self,
     4782:         state: Any = None,
     4783:         depth: int | None = None,
     4784:         battle_state: Any = None,
     4785:         **kwargs: Any,
     4786:     ) -> CompetitivePolicyDecision:
     4787:         resolved_state = (
     4788:             state
     4789:             if state is not None
     4790:             else battle_state
     4791:         )
     4792:
     4793:         if resolved_state is None:
     4794:             raise ValueError(
     4795:                 "A battle state must be supplied."
     4796:             )
     4797:
     4798:         legal_moves = (
     4799:             get_current_legal_moves(
     4800:                 resolved_state
     4801:             )
     4802:         )
     4803:
     4804:         if not legal_moves:
     4805:             self.last_decision = (
     4806:                 CompetitivePolicyDecision(
     4807:                     move=None,
     4808:
     4809:                     confidence=0.0,
     4810:
     4811:                     selected_move_name=None,
     4812:
     4813:                     probabilities=[],
     4814:
     4815:                     logits=[],
     4816:
     4817:                     move_names=[],
     4818:
     4819:                     fallback=True,
     4820:
     4821:                     score=0.0,
     4822:
     4823:                     search_depth=int(
     4824:                         depth or 0
     4825:                     ),
     4826:
     4827:                     nodes=0,
     4828:
     4829:                     reason=
     4830:                         "No legal moves available.",
     4831:                 )
     4832:             )
     4833:
     4834:             return self.last_decision
     4835:
     4836:         result = (
     4837:             self.policy_engine
     4838:             .score_moves(
     4839:                 battle_state=
     4840:                     resolved_state,
     4841:
     4842:                 legal_moves=
     4843:                     legal_moves,
     4844:             )
     4845:         )
     4846:
     4847:         self.last_decision = (
     4848:             CompetitivePolicyDecision(
     4849:                 move=
     4850:                     result[
     4851:                         "selected_move"
     4852:                     ],
     4853:
     4854:                 confidence=float(
     4855:                     result[
     4856:                         "confidence"
     4857:                     ]
     4858:                 ),
     4859:
     4860:                 selected_move_name=
     4861:                     result[
     4862:                         "selected_move_name"
     4863:                     ],
     4864:
     4865:                 probabilities=list(
     4866:                     result[
     4867:                         "probabilities"
     4868:                     ]
     4869:                 ),
     4870:
     4871:                 logits=list(
     4872:                     result[
     4873:                         "logits"
     4874:                     ]
     4875:                 ),
     4876:
     4877:                 move_names=list(
     4878:                     result[
     4879:                         "move_names"
     4880:                     ]
     4881:                 ),
     4882:
     4883:                 fallback=bool(
     4884:                     result[
     4885:                         "fallback"
     4886:                     ]
     4887:                 ),
     4888:
     4889:                 score=float(
     4890:                     result[
     4891:                         "confidence"
     4892:                     ]
     4893:                 ),
     4894:
     4895:                 search_depth=int(
     4896:                     depth or 0
     4897:                 ),
     4898:
     4899:                 nodes=0,
     4900:
     4901:                 reason=None,
     4902:             )
     4903:         )
     4904:
     4905:         return self.last_decision
     4906:
     4907:     def select_move(
     4908:         self,
     4909:         state: Any = None,
     4910:         depth: int | None = None,
     4911:         battle_state: Any = None,
     4912:         **kwargs: Any,
     4913:     ) -> CompetitivePolicyDecision:
     4914:         return self.choose_move(
     4915:             state=state,
     4916:             depth=depth,
     4917:             battle_state=battle_state,
     4918:             **kwargs,
     4919:         )
     4920:
     4921:     def act(
     4922:         self,
     4923:         state: Any = None,
     4924:         depth: int | None = None,
     4925:         battle_state: Any = None,
     4926:         **kwargs: Any,
     4927:     ) -> CompetitivePolicyDecision:
     4928:         return self.choose_move(
     4929:             state=state,
     4930:             depth=depth,
     4931:             battle_state=battle_state,
     4932:             **kwargs,
     4933:         )
     4934:
     4935:     def get_last_decision(
     4936:         self,
     4937:     ) -> CompetitivePolicyDecision | None:
     4938:         return self.last_decision
     4939: '''
     4940:
     4941:
     4942: # ------------------------------------------------------------
     4943: # 7.4 â€” Package initializer source
     4944: # ------------------------------------------------------------
     4945:
     4946: package_init_source = r'''
     4947: from src.competitive.competitive_policy_agent import (
     4948:     CompetitivePolicyAgent,
     4949:     CompetitivePolicyDecision,
     4950: )
     4951:
     4952: from src.competitive.competitive_policy_engine import (
     4953:     CompetitivePolicyEngine,
     4954:     CompetitivePolicyNetwork,
     4955:     actor_and_defender,
     4956:     encode_move,
     4957:     encode_state,
     4958:     move_name,
     4959: )
     4960:
     4961: __all__ = [
     4962:     "CompetitivePolicyAgent",
     4963:     "CompetitivePolicyDecision",
     4964:     "CompetitivePolicyEngine",
     4965:     "CompetitivePolicyNetwork",
     4966:     "actor_and_defender",
     4967:     "encode_move",
     4968:     "encode_state",
     4969:     "move_name",
     4970: ]
     4971: '''
     4972:
     4973:
     4974: # ------------------------------------------------------------
     4975: # 7.5 â€” Write production files
     4976: # ------------------------------------------------------------
     4977:
     4978: POLICY_MODULE_FILE.write_text(
     4979:     textwrap.dedent(
     4980:         policy_module_source
     4981:     ).lstrip(),
     4982:     encoding="utf-8",
     4983: )
     4984:
     4985: AGENT_MODULE_FILE.write_text(
     4986:     textwrap.dedent(
     4987:         agent_module_source
     4988:     ).lstrip(),
     4989:     encoding="utf-8",
     4990: )
     4991:
     4992: PACKAGE_INIT_FILE.write_text(
     4993:     textwrap.dedent(
     4994:         package_init_source
     4995:     ).lstrip(),
     4996:     encoding="utf-8",
     4997: )
     4998:
     4999:
     5000: # ------------------------------------------------------------
     5001: # 7.6 â€” Confirm generated source parses
     5002: # ------------------------------------------------------------
     5003:
     5004: for source_file in [
     5005:     POLICY_MODULE_FILE,
     5006:     AGENT_MODULE_FILE,
     5007:     PACKAGE_INIT_FILE,
     5008: ]:
     5009:     source_text = (
     5010:         source_file.read_text(
     5011:             encoding="utf-8"
     5012:         )
     5013:     )
     5014:
     5015:     ast.parse(
     5016:         source_text
     5017:     )

====================================================================================================
AUDIT C — POLICY STATE ENCODING
====================================================================================================

====================================================================================================
SOURCE: scripts\47_competitive_policy_training.py
MATCH LINE: 4214
====================================================================================================
     4194:     if current_player == "player":
     4195:         return (
     4196:             battle_state.player,
     4197:             battle_state.opponent,
     4198:             "Player",
     4199:         )
     4200:
     4201:     if current_player == "opponent":
     4202:         return (
     4203:             battle_state.opponent,
     4204:             battle_state.player,
     4205:             "Opponent",
     4206:         )
     4207:
     4208:     raise ValueError(
     4209:         "Unsupported current_player value: "
     4210:         f"{getattr(battle_state, 'current_player', None)!r}"
     4211:     )
     4212:
     4213:
>>>  4214: def encode_state(
     4215:     battle_state: Any,
     4216: ) -> np.ndarray:
     4217:     actor, defender, actor_side = (
     4218:         actor_and_defender(
     4219:             battle_state
     4220:         )
     4221:     )
     4222:
     4223:     actor_active = actor.active
     4224:     defender_active = defender.active
     4225:
     4226:     actor_hp_ratio = (
     4227:         _safe_float(
     4228:             actor_active.current_hp
     4229:         )
     4230:         / _card_max_hp(
     4231:             actor_active
     4232:         )
     4233:     )
     4234:
     4235:     defender_hp_ratio = (
     4236:         _safe_float(
     4237:             defender_active.current_hp
     4238:         )
     4239:         / _card_max_hp(
     4240:             defender_active
     4241:         )
     4242:     )
     4243:
     4244:     features = np.asarray(
     4245:         [
     4246:             np.clip(
     4247:                 actor_hp_ratio,
     4248:                 0.0,
     4249:                 1.0,
     4250:             ),
     4251:
     4252:             np.clip(
     4253:                 _safe_float(
     4254:                     actor_active
     4255:                     .attached_energy
     4256:                 )
     4257:                 / 10.0,
     4258:                 0.0,
     4259:                 1.0,
     4260:             ),
     4261:
     4262:             np.clip(
     4263:                 _safe_float(
     4264:                     actor
     4265:                     .prize_cards_remaining
     4266:                 )
     4267:                 / 6.0,
     4268:                 0.0,
     4269:                 1.0,
     4270:             ),
     4271:
     4272:             np.clip(
     4273:                 defender_hp_ratio,
     4274:                 0.0,
     4275:                 1.0,
     4276:             ),
     4277:
     4278:             np.clip(
     4279:                 _safe_float(
     4280:                     defender_active
     4281:                     .attached_energy
     4282:                 )
     4283:                 / 10.0,
     4284:                 0.0,
     4285:                 1.0,
     4286:             ),
     4287:
     4288:             np.clip(
     4289:                 _safe_float(
     4290:                     defender
     4291:                     .prize_cards_remaining
     4292:                 )
     4293:                 / 6.0,
     4294:                 0.0,
     4295:                 1.0,
     4296:             ),
     4297:
     4298:             np.clip(
     4299:                 _safe_float(
     4300:                     battle_state.turn_number
     4301:                 )
     4302:                 / 50.0,
     4303:                 0.0,
     4304:                 1.0,
     4305:             ),
     4306:
     4307:             (
     4308:                 1.0
     4309:                 if actor_side == "Player"
     4310:                 else 0.0
     4311:             ),
     4312:         ],
     4313:         dtype=np.float32,
     4314:     )
     4315:
     4316:     if features.shape != (
     4317:         STATE_DIM,
     4318:     ):
     4319:         raise ValueError(
     4320:             "Unexpected encoded state shape: "

In [9]:
# ======================================================================================
# SECTION 4D.5A — TARGETED ACTOR-PERSPECTIVE CONTRACT EXTRACTION
# ======================================================================================
#
# PURPOSE
# -------
# Reduce the very large Section 4D.5 source dump to the exact source fragments
# needed to determine whether R3 policy features are:
#
#     A. ACTOR-RELATIVE
#        or
#     B. FIXED PLAYER/OPPONENT ABSOLUTE
#
# READ ONLY:
# - no source modification
# - no model modification
# - no retraining
# - no benchmark execution
# ======================================================================================

from pathlib import Path
import ast
import re


PROJECT_ROOT_4D5A = Path(
    r"D:\02_AI_and_Data\Kaggle-AI-Agents\PTCG_AI_Battle_Challenge"
)

SCRIPT_46_4D5A = (
    PROJECT_ROOT_4D5A
    / "scripts"
    / "46_competitive_policy_dataset_generation.py"
)

SCRIPT_47_4D5A = (
    PROJECT_ROOT_4D5A
    / "scripts"
    / "47_competitive_policy_training.py"
)

SCRIPT_48_4D5A = (
    PROJECT_ROOT_4D5A
    / "scripts"
    / "48_tournament_evaluation_and_elo_benchmarking.py"
)

for path in [
    SCRIPT_46_4D5A,
    SCRIPT_47_4D5A,
    SCRIPT_48_4D5A,
]:
    assert path.exists(), path


print("=" * 100)
print("SECTION 4D.5A — TARGETED ACTOR-PERSPECTIVE CONTRACT EXTRACTION")
print("=" * 100)


# ======================================================================================
# Helper: recover exact function/class source by AST
# ======================================================================================

def source_for_symbol_4d5a(
    path: Path,
    symbol_name: str,
):
    text = path.read_text(
        encoding="utf-8-sig",
        errors="replace",
    )

    tree = ast.parse(text)

    lines = text.splitlines()

    matches = []

    for node in ast.walk(tree):

        if isinstance(
            node,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
                ast.ClassDef,
            ),
        ):

            if node.name == symbol_name:

                start = node.lineno

                end = getattr(
                    node,
                    "end_lineno",
                    node.lineno,
                )

                matches.append(
                    (
                        start,
                        end,
                        "\n".join(
                            lines[
                                start - 1:
                                end
                            ]
                        ),
                    )
                )

    return matches


def print_symbol_4d5a(
    path: Path,
    symbol_name: str,
    max_lines: int = 260,
):
    matches = source_for_symbol_4d5a(
        path,
        symbol_name,
    )

    print()
    print("=" * 100)
    print(
        f"{path.name} :: {symbol_name}"
    )
    print("=" * 100)

    if not matches:
        print("NOT FOUND")
        return []

    for match_number, (
        start,
        end,
        source,
    ) in enumerate(
        matches,
        start=1,
    ):

        source_lines = source.splitlines()

        print(
            f"Occurrence {match_number}"
        )
        print(
            f"Lines {start} - {end}"
        )
        print("-" * 100)

        for offset, line in enumerate(
            source_lines[:max_lines],
            start=start,
        ):
            print(
                f"{offset:5d}: {line}"
            )

        if len(source_lines) > max_lines:
            print(
                f"... truncated after "
                f"{max_lines} lines ..."
            )

    return matches


# ======================================================================================
# A. Training-time actor-relative encoder
# ======================================================================================

actor_relative_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_46_4D5A,
        "encode_actor_relative_state",
        max_lines=220,
    )
)


# ======================================================================================
# B. Training current-player feature
# ======================================================================================

current_player_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_46_4D5A,
        "section9_current_player_feature",
        max_lines=160,
    )
)


# ======================================================================================
# C. Production/training policy encode_state
# ======================================================================================

encode_state_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_47_4D5A,
        "encode_state",
        max_lines=240,
    )
)


# ======================================================================================
# D. CompetitivePolicyAgent
# ======================================================================================

policy_agent_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_47_4D5A,
        "CompetitivePolicyAgent",
        max_lines=320,
    )
)


# ======================================================================================
# E. Tournament state builder
# ======================================================================================

tournament_state_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_48_4D5A,
        "create_tournament_state",
        max_lines=180,
    )
)


# ======================================================================================
# F. Tournament runner
# ======================================================================================

runner_matches_4d5a = (
    print_symbol_4d5a(
        SCRIPT_48_4D5A,
        "run_tournament_match",
        max_lines=260,
    )
)


# ======================================================================================
# G. Compact keyword evidence
# ======================================================================================

print()
print("=" * 100)
print("COMPACT ORIENTATION KEYWORD EVIDENCE")
print("=" * 100)


keyword_patterns_4d5a = [
    r"current_player",
    r"actor",
    r"player_state",
    r"opponent_state",
    r"player_card",
    r"opponent_card",
    r"current_side",
    r"side_mode",
    r"evaluated_agent_side",
    r"encode_actor_relative_state",
    r"encode_state",
]


for path in [
    SCRIPT_46_4D5A,
    SCRIPT_47_4D5A,
    SCRIPT_48_4D5A,
]:

    print()
    print(
        f"FILE: {path.name}"
    )
    print("-" * 100)

    text = path.read_text(
        encoding="utf-8-sig",
        errors="replace",
    )

    lines = text.splitlines()

    evidence_count = 0

    for line_number, line in enumerate(
        lines,
        start=1,
    ):

        if any(
            re.search(
                pattern,
                line,
                flags=re.IGNORECASE,
            )
            for pattern in keyword_patterns_4d5a
        ):

            print(
                f"{line_number:5d}: "
                f"{line.strip()}"
            )

            evidence_count += 1

            if evidence_count >= 120:
                print(
                    "... evidence capped at "
                    "120 lines for this file ..."
                )
                break


# ======================================================================================
# H. Diagnostic status only — no correction yet
# ======================================================================================

print()
print("=" * 100)
print("SECTION 4D.5A STATUS")
print("=" * 100)

print(
    "encode_actor_relative_state found:",
    bool(actor_relative_matches_4d5a),
)

print(
    "section9_current_player_feature found:",
    bool(current_player_matches_4d5a),
)

print(
    "encode_state found:",
    bool(encode_state_matches_4d5a),
)

print(
    "CompetitivePolicyAgent found:",
    bool(policy_agent_matches_4d5a),
)

print(
    "create_tournament_state found:",
    bool(tournament_state_matches_4d5a),
)

print(
    "run_tournament_match found:",
    bool(runner_matches_4d5a),
)

print()
print("NO SOURCE FILE WAS MODIFIED.")
print("NO MODEL WAS MODIFIED.")
print("NO RETRAINING WAS PERFORMED.")
print("NO BENCHMARK MATCH WAS EXECUTED.")

print()
print(
    "➡️ NEXT: determine whether the live R3 encoder "
    "matches the actor-relative training contract."
)

print("=" * 100)

====================================================================================================
SECTION 4D.5A — TARGETED ACTOR-PERSPECTIVE CONTRACT EXTRACTION
====================================================================================================

====================================================================================================
46_competitive_policy_dataset_generation.py :: encode_actor_relative_state
====================================================================================================
Occurrence 1
Lines 6052 - 6167
----------------------------------------------------------------------------------------------------
 6052: def encode_actor_relative_state(
 6053:     state: BattleState,
 6054: ) -> list[float]:
 6055:     actor, defender, actor_side = (
 6056:         get_actor_and_defender(state)
 6057:     )
 6058:
 6059:     actor_active = actor.active
 6060:     defender_active = defender.active
 6061:
 6062:     actor_hp_ratio = (
 6063:         safe_float(
 6064:             actor_active.current_hp
 6065:         )
 6066:         / get_card_max_hp(
 6067:             actor_active
 6068:         )
 6069:     )
 6070:
 6071:     defender_hp_ratio = (
 6072:         safe_float(
 6073:             defender_active.current_hp
 6074:         )
 6075:         / get_card_max_hp(
 6076:             defender_active
 6077:         )
 6078:     )
 6079:
 6080:     actor_side_indicator = (
 6081:         1.0
 6082:         if actor_side == "Player"
 6083:         else 0.0
 6084:     )
 6085:
 6086:     features = [
 6087:         float(
 6088:             np.clip(
 6089:                 actor_hp_ratio,
 6090:                 0.0,
 6091:                 1.0,
 6092:             )
 6093:         ),
 6094:
 6095:         float(
 6096:             np.clip(
 6097:                 safe_float(
 6098:                     actor_active
 6099:                     .attached_energy
 6100:                 )
 6101:                 / 10.0,
 6102:                 0.0,
 6103:                 1.0,
 6104:             )
 6105:         ),
 6106:
 6107:         float(
 6108:             np.clip(
 6109:                 safe_float(
 6110:                     actor
 6111:                     .prize_cards_remaining
 6112:                 )
 6113:                 / 6.0,
 6114:                 0.0,
 6115:                 1.0,
 6116:             )
 6117:         ),
 6118:
 6119:         float(
 6120:             np.clip(
 6121:                 defender_hp_ratio,
 6122:                 0.0,
 6123:                 1.0,
 6124:             )
 6125:         ),
 6126:
 6127:         float(
 6128:             np.clip(
 6129:                 safe_float(
 6130:                     defender_active
 6131:                     .attached_energy
 6132:                 )
 6133:                 / 10.0,
 6134:                 0.0,
 6135:                 1.0,
 6136:             )
 6137:         ),
 6138:
 6139:         float(
 6140:             np.clip(
 6141:                 safe_float(
 6142:                     defender
 6143:                     .prize_cards_remaining
 6144:                 )
 6145:                 / 6.0,
 6146:                 0.0,
 6147:                 1.0,
 6148:             )
 6149:         ),
 6150:
 6151:         float(
 6152:             np.clip(
 6153:                 safe_float(
 6154:                     state.turn_number
 6155:                 )
 6156:                 / 50.0,
 6157:                 0.0,
 6158:                 1.0,
 6159:             )
 6160:         ),
 6161:
 6162:         actor_side_indicator,
 6163:     ]
 6164:
 6165:     assert len(features) == STATE_DIM
 6166:
 6167:     return features

====================================================================================================
46_competitive_policy_dataset_generation.py :: section9_current_player_feature
====================================================================================================
Occurrence 1
Lines 5526 - 5534
----------------------------------------------------------------------------------------------------
 5526: def section9_current_player_feature(
 5527:     state_features: list,
 5528: ) -> float:
 5529:     if len(state_features) <= 7:
 5530:         return float("nan")
 5531:
 5532:     return float(
 5533:         state_features[7]
 5534:     )

====================================================================================================
47_competitive_policy_training.py :: encode_state
====================================================================================================
NOT FOUND

====================================================================================================
47_competitive_policy_training.py :: CompetitivePolicyAgent
====================================================================================================
NOT FOUND

====================================================================================================
48_tournament_evaluation_and_elo_benchmarking.py :: create_tournament_state
====================================================================================================
Occurrence 1
Lines 2591 - 2669
----------------------------------------------------------------------------------------------------
 2591: def create_tournament_state(
 2592:     player_card: dict[str, Any],
 2593:     opponent_card: dict[str, Any],
 2594:     starting_side: str = "Player",
 2595:     player_energy: int = 3,
 2596:     opponent_energy: int = 3,
 2597: ) -> BattleState:
 2598:     player_card_copy = copy.deepcopy(
 2599:         player_card
 2600:     )
 2601:
 2602:     opponent_card_copy = copy.deepcopy(
 2603:         opponent_card
 2604:     )
 2605:
 2606:     return BattleState(
 2607:         player=PlayerState(
 2608:             active=PokemonState(
 2609:                 card=
 2610:                     player_card_copy,
 2611:
 2612:                 current_hp=float(
 2613:                     player_card_copy[
 2614:                         "hp"
 2615:                     ]
 2616:                 ),
 2617:
 2618:                 attached_energy=int(
 2619:                     player_energy
 2620:                 ),
 2621:
 2622:                 status=None,
 2623:
 2624:                 damage=0.0,
 2625:
 2626:                 is_active=True,
 2627:             ),
 2628:
 2629:             bench=[],
 2630:
 2631:             prize_cards_remaining=1,
 2632:
 2633:             hand_size=7,
 2634:         ),
 2635:
 2636:         opponent=PlayerState(
 2637:             active=PokemonState(
 2638:                 card=
 2639:                     opponent_card_copy,
 2640:
 2641:                 current_hp=float(
 2642:                     opponent_card_copy[
 2643:                         "hp"
 2644:                     ]
 2645:                 ),
 2646:
 2647:                 attached_energy=int(
 2648:                     opponent_energy
 2649:                 ),
 2650:
 2651:                 status=None,
 2652:
 2653:                 damage=0.0,
 2654:
 2655:                 is_active=True,
 2656:             ),
 2657:
 2658:             bench=[],
 2659:
 2660:             prize_cards_remaining=1,
 2661:
 2662:             hand_size=7,
 2663:         ),
 2664:
 2665:         turn_number=1,
 2666:
 2667:         current_player=
 2668:             starting_side,
 2669:     )

====================================================================================================
48_tournament_evaluation_and_elo_benchmarking.py :: run_tournament_match
====================================================================================================
Occurrence 1
Lines 2696 - 2937
----------------------------------------------------------------------------------------------------
 2696: def run_tournament_match(
 2697:     match_id: int,
 2698:     evaluated_agent: Any,
 2699:     baseline_agent: Any,
 2700:     player_card: dict[str, Any],
 2701:     opponent_card: dict[str, Any],
 2702:     starting_side: str,
 2703:     evaluated_agent_side: str,
 2704:     max_turns: int =
 2705:         MAX_TURNS_PER_MATCH,
 2706:     search_depth: int =
 2707:         SIMULATOR_SEARCH_DEPTH,
 2708:     verbose: bool =
 2709:         VERBOSE_MATCHES,
 2710: ) -> TournamentMatchResult:
 2711:     if evaluated_agent_side not in {
 2712:         "Player",
 2713:         "Opponent",
 2714:     }:
 2715:         raise ValueError(
 2716:             "evaluated_agent_side must be "
 2717:             "'Player' or 'Opponent'."
 2718:         )
 2719:
 2720:     initial_state = (
 2721:         create_tournament_state(
 2722:             player_card=
 2723:                 player_card,
 2724:
 2725:             opponent_card=
 2726:                 opponent_card,
 2727:
 2728:             starting_side=
 2729:                 starting_side,
 2730:         )
 2731:     )
 2732:
 2733:     class SideAwareAgent:
 2734:         def __init__(
 2735:             self,
 2736:             player_agent: Any,
 2737:             opponent_agent: Any,
 2738:         ) -> None:
 2739:             self.player_agent = (
 2740:                 player_agent
 2741:             )
 2742:
 2743:             self.opponent_agent = (
 2744:                 opponent_agent
 2745:             )
 2746:
 2747:             self.fallback_count = 0
 2748:
 2749:         def choose_move(
 2750:             self,
 2751:             state: Any = None,
 2752:             depth: int | None = None,
 2753:             battle_state: Any = None,
 2754:             **kwargs: Any,
 2755:         ) -> Any:
 2756:             resolved_state = (
 2757:                 state
 2758:                 if state is not None
 2759:                 else battle_state
 2760:             )
 2761:
 2762:             if resolved_state is None:
 2763:                 raise ValueError(
 2764:                     "A battle state is required."
 2765:                 )
 2766:
 2767:             side = str(
 2768:                 resolved_state
 2769:                 .current_player
 2770:             )
 2771:
 2772:             selected_agent = (
 2773:                 self.player_agent
 2774:                 if side == "Player"
 2775:                 else self.opponent_agent
 2776:             )
 2777:
 2778:             decision = (
 2779:                 selected_agent
 2780:                 .choose_move(
 2781:                     state=
 2782:                         resolved_state,
 2783:
 2784:                     depth=
 2785:                         depth,
 2786:                 )
 2787:             )
 2788:
 2789:             if bool(
 2790:                 getattr(
 2791:                     decision,
 2792:                     "fallback",
 2793:                     False,
 2794:                 )
 2795:             ):
 2796:                 self.fallback_count += 1
 2797:
 2798:             return decision
 2799:
 2800:     if evaluated_agent_side == "Player":
 2801:         side_agent = SideAwareAgent(
 2802:             player_agent=
 2803:                 evaluated_agent,
 2804:
 2805:             opponent_agent=
 2806:                 baseline_agent,
 2807:         )
 2808:
 2809:     else:
 2810:         side_agent = SideAwareAgent(
 2811:             player_agent=
 2812:                 baseline_agent,
 2813:
 2814:             opponent_agent=
 2815:                 evaluated_agent,
 2816:         )
 2817:
 2818:     start_time = time.perf_counter()
 2819:
 2820:     simulation = simulate_ai_battle(
 2821:         initial_state=
 2822:             initial_state,
 2823:
 2824:         agent=
 2825:             side_agent,
 2826:
 2827:         search_depth=
 2828:             search_depth,
 2829:
 2830:         max_turns=
 2831:             max_turns,
 2832:
 2833:         verbose=
 2834:             verbose,
 2835:     )
 2836:
 2837:     elapsed_seconds = (
 2838:         time.perf_counter()
 2839:         - start_time
 2840:     )
 2841:
 2842:     winner = getattr(
 2843:         simulation,
 2844:         "winner",
 2845:         None,
 2846:     )
 2847:
 2848:     turns = getattr(
 2849:         simulation,
 2850:         "turns",
 2851:         [],
 2852:     )
 2853:
 2854:     stop_reason = getattr(
 2855:         simulation,
 2856:         "stop_reason",
 2857:         None,
 2858:     )
 2859:
 2860:     if winner is None:
 2861:         agent_result = 0.5
 2862:
 2863:     elif winner == evaluated_agent_side:
 2864:         agent_result = 1.0
 2865:
 2866:     else:
 2867:         agent_result = 0.0
 2868:
 2869:     return TournamentMatchResult(
 2870:         match_id=
 2871:             int(match_id),
 2872:
 2873:         agent_name=
 2874:             str(
 2875:                 getattr(
 2876:                     evaluated_agent,
 2877:                     "name",
 2878:                     type(
 2879:                         evaluated_agent
 2880:                     ).__name__,
 2881:                 )
 2882:             ),
 2883:
 2884:         baseline_name=
 2885:             str(
 2886:                 getattr(
 2887:                     baseline_agent,
 2888:                     "name",
 2889:                     type(
 2890:                         baseline_agent
 2891:                     ).__name__,
 2892:                 )
 2893:             ),
 2894:
 2895:         player_card=
 2896:             str(
 2897:                 player_card[
 2898:                     "name"
 2899:                 ]
 2900:             ),
 2901:
 2902:         opponent_card=
 2903:             str(
 2904:                 opponent_card[
 2905:                     "name"
 2906:                 ]
 2907:             ),
 2908:
 2909:         starting_side=
 2910:             str(
 2911:                 starting_side
 2912:             ),
 2913:
 2914:         winner=winner,
 2915:
 2916:         turns=
 2917:             len(turns),
 2918:
 2919:         stop_reason=
 2920:             stop_reason,
 2921:
 2922:         agent_result=
 2923:             float(
 2924:                 agent_result
 2925:             ),
 2926:
 2927:         fallback_count=
 2928:             int(
 2929:                 side_agent
 2930:                 .fallback_count
 2931:             ),
 2932:
 2933:         elapsed_seconds=
 2934:             float(
 2935:                 elapsed_seconds
 2936:             ),
 2937:     )

====================================================================================================
COMPACT ORIENTATION KEYWORD EVIDENCE
====================================================================================================

FILE: 46_competitive_policy_dataset_generation.py
----------------------------------------------------------------------------------------------------
  259: "current_player",
 1413: field.default_factory
 1416: default_value = "<default_factory>"
 1529: "current_player",
 1795: # Inspect how AdvancedSearchEngine uses current_player
 1823: "current_player",
 1932: current_player_type = repr(
 1954: if name == "current_player_adapter":
 1957: if "current_player" in name:
 1975: if "current_player" in source:
 2000: resolved_current_player_fn = None
 2017: == "current_player_adapter"
 2029: resolved_current_player_fn = getattr(
 2041: / "current_player_adapter_resolution.json"
 2046: / "current_player_adapter_sources.txt"
 2050: "current_player_type":
 2051: current_player_type,
 2151: current_player_type,
 2228: assert resolved_current_player_fn is not None, (
 2233: resolved_current_player_fn
 2237: resolved_current_player_fn
 2269: == "current_player_adapter"
 2315: current_player_adapter,
 2420: player_state = PlayerState(
 2427: opponent_state = PlayerState(
 2440: player=player_state,
 2441: opponent=opponent_state,
 2443: current_player="Player",
 2700: def player_state_key(
 2748: player_state_key(
 2756: player_state_key(
 2775: "current_player",
 2950: current_player=
 2951: current_player_adapter,
 2965: root_player = current_player_adapter(
 3083: "current_player":
 3084: selected_state.current_player,
 3171: "current_player":
 3172: next_state.current_player,
 3226: selected_state.current_player,
 3415: current_player_adapter,
 3885: "current_player",
 3986: current_player_value = (
 3989: state.current_player
 4070: current_player_value,
 4220: player_card, opponent_card = (
 4227: player_card = copy.deepcopy(
 4228: player_card
 4231: opponent_card = copy.deepcopy(
 4232: opponent_card
 4236: player_card["hp"]
 4240: opponent_card["hp"]
 4264: card=player_card,
 4281: card=opponent_card,
 4330: current_player=(
 4355: current_player=
 4356: current_player_adapter,
 4490: current_player_adapter(
 4666: "current_player":
 4669: .current_player
 5130: "current_player",
 5227: # ## Section 9 â€” Actor-Perspective Dataset Quality Audit
 5241: # SECTION 9 â€” ACTOR-PERSPECTIVE DATASET QUALITY AUDIT
 5264: / "actor_perspective_dataset_audit.json"
 5269: / "actor_perspective_suspicious_records.csv"
 5406: "current_player"
 5417: "current_player"
 5501: "current_player",
 5526: def section9_current_player_feature(
 5538: "encoded_current_player"
 5542: section9_current_player_feature
 5546: "current_player_feature_valid"
 5553: "encoded_current_player"
 5559: "encoded_current_player"
 5631: "current_player_feature_valid"
 5701: "current_player_feature_failures":
 5705: "current_player_feature_valid"
 5743: "Regenerate the dataset using actor-relative "
 5768: "NOTEBOOK 46 â€” ACTOR-PERSPECTIVE DATASET AUDIT"
 5911: "ACTOR-PERSPECTIVE CORRECTION REQUIRED"
 5920: # ## Section 10 â€” Actor-Relative Expert Dataset Regeneration
 5926: # ##### - `actor` means the side whose turn it is;
 5928: # ##### - HP, energy, prizes, move effects, knockout status, and damage are calculated relative to the actor;
 5938: # SECTION 10 â€” ACTOR-RELATIVE EXPERT DATASET
 5956: ACTOR_TARGET_RECORDS = 1000
 5958: ACTOR_SEARCH_DEPTH = 4
 5960: ACTOR_MAX_TURNS = 20
 5962: ACTOR_PROGRESS_INTERVAL = 100
 5964: ACTOR_RANDOM_SEED = 4610
 5966: ACTOR_DATASET_FILE = (
 5968: / "actor_relative_search_expert_dataset.parquet"
 5971: ACTOR_JSONL_FILE = (
 5973: / "actor_relative_search_expert_dataset.jsonl"
 5976: ACTOR_SUMMARY_FILE = (
 5978: / "actor_relative_search_expert_summary.json"
 5981: ACTOR_FAILURE_FILE = (
 5983: / "actor_relative_search_failures.json"
 5986: random.seed(ACTOR_RANDOM_SEED)
 5987: np.random.seed(ACTOR_RANDOM_SEED)
 5991: # 10.4 â€” Resolve actor and defender
 5994: def get_actor_and_defender(
 5997: current_player = str(
 5998: state.current_player
 6001: if current_player == "player":
 6008: if current_player == "opponent":
 6016: "Unknown current_player value: "
 6017: f"{state.current_player!r}"
 6049: # 10.5 â€” Actor-relative state encoder
 6052: def encode_actor_relative_state(
 6055: actor, defender, actor_side = (
 6056: get_actor_and_defender(state)
 6059: actor_active = actor.active
 6062: actor_hp_ratio = (
 6064: actor_active.current_hp
 6067: actor_active
 6080: actor_side_indicator = (
 6082: if actor_side == "Player"
 6089: actor_hp_ratio,
 6098: actor_active
 6110: actor
... evidence capped at 120 lines for this file ...

FILE: 47_competitive_policy_training.py
----------------------------------------------------------------------------------------------------
   10: # Train a variable-action neural policy using the actor-relative,
   27: # #### Load the actor-relative expert dataset from Notebook 46, verify its schema, and prepare deterministic training, validation, and test splits.
  137: / "actor_relative_search_expert_dataset.parquet"
  144: / "actor_relative_search_expert_summary.json"
  187: "The Notebook 46 actor-relative dataset "
  258: "actor_relative",
  351: "actor_relative"
  546: "actor_relative":
  644: "actor_side",
  645: "actor_name",
  669: # #### Convert the actor-relative expert records into PyTorch tensors.
 2445: "actor_relative":
 2901: "actor_relative":
 3280: "actor_side":
 3283: "actor_side"

In [ ]:
# ======================================================================================
# SECTION 4D.5B-PREFLIGHT — VERIFY RESTORED LIVE R3 NAMESPACE
# ======================================================================================

required_4d5b = [
    "R3LivePolicyEngine",
    "r3_policy_engine_3c2",
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "R3_NUMERIC_FEATURES",
    "R3_CATEGORICAL_FEATURES",
    "R3_ENCODED_FEATURE_NAMES",
]

print("=" * 90)
print("SECTION 4D.5B-PREFLIGHT — LIVE R3 NAMESPACE")
print("=" * 90)

all_ready = True

for name in required_4d5b:
    available = name in globals()

    print(
        f"{name:<38} : "
        f"{'READY' if available else 'MISSING'}"
    )

    if not available:
        all_ready = False

print("-" * 90)

if all_ready:
    print("✅ LIVE R3 NAMESPACE RESTORED")
    print("✅ SAFE TO RERUN SECTION 4D.5B")
else:
    print("❌ LIVE R3 NAMESPACE IS STILL INCOMPLETE")
    print("DO NOT RERUN SECTION 4D.5B YET")

print("=" * 90)

In [10]:
# ======================================================================================
# SECTION 4D.5B — ACTUAL LIVE R3 ENCODER / ORIENTATION CONTRACT AUDIT
# ======================================================================================
#
# PURPOSE
# -------
# Section 4D.5A established that CompetitivePolicyAgent / encode_state are NOT
# the live frozen-R3 policy path used by Notebook 60.
#
# The actual live path recovered from Notebook 59 is:
#
#   R3LivePolicyEngine
#       -> score_moves()
#       -> build_model_matrix()
#       -> build_legality_aware_feature_row()
#       -> encode_r3_feature_row()
#       -> frozen 46-feature RandomForestClassifier
#
# This section inspects that exact live path.
#
# READ ONLY:
#   - no model changes
#   - no retraining
#   - no source modification
#   - no benchmark execution
# ======================================================================================

import inspect
import ast
import textwrap
import pandas as pd


print("=" * 110)
print("SECTION 4D.5B — ACTUAL LIVE R3 ENCODER / ORIENTATION CONTRACT AUDIT")
print("=" * 110)


# ======================================================================================
# 1. Required live objects
# ======================================================================================

required_live_objects_4d5b = [
    "R3LivePolicyEngine",
    "r3_policy_engine_3c2",
    "build_legality_aware_feature_row",
    "encode_r3_feature_row",
    "R3_NUMERIC_FEATURES",
    "R3_CATEGORICAL_FEATURES",
    "R3_ENCODED_FEATURE_NAMES",
]


live_object_rows_4d5b = []

for object_name in required_live_objects_4d5b:

    available = object_name in globals()

    obj = (
        globals().get(object_name)
        if available
        else None
    )

    live_object_rows_4d5b.append(
        {
            "object":
                object_name,

            "available":
                available,

            "object_type":
                (
                    type(obj).__name__
                    if available
                    else "MISSING"
                ),
        }
    )


live_object_status_4d5b = pd.DataFrame(
    live_object_rows_4d5b
)


print()
print("LIVE R3 OBJECT STATUS")
print("-" * 110)

display(
    live_object_status_4d5b
)


assert live_object_status_4d5b[
    "available"
].all(), (
    "One or more live R3 encoder objects are missing. "
    "Do not continue until the existing Notebook 59 R3 namespace is restored."
)


# ======================================================================================
# 2. Exact frozen R3 engine contract
# ======================================================================================

r3_engine_4d5b = r3_policy_engine_3c2


print()
print("LIVE FROZEN R3 ENGINE")
print("-" * 110)

print(
    "Engine type       :",
    type(r3_engine_4d5b).__name__,
)

print(
    "Policy name       :",
    getattr(
        r3_engine_4d5b,
        "name",
        None,
    ),
)

print(
    "Model type        :",
    type(
        r3_engine_4d5b.model
    ).__name__,
)

print(
    "Model features    :",
    int(
        r3_engine_4d5b.model.n_features_in_
    ),
)

print(
    "Classes           :",
    list(
        r3_engine_4d5b.model.classes_
    ),
)


assert int(
    r3_engine_4d5b.model.n_features_in_
) == 46


# ======================================================================================
# 3. Source helper
# ======================================================================================

def print_live_source_4d5b(
    title,
    obj,
    max_lines=300,
):

    print()
    print("=" * 110)
    print(title)
    print("=" * 110)

    try:

        source = inspect.getsource(
            obj
        )

    except Exception as exc:

        print(
            "SOURCE UNAVAILABLE:",
            type(exc).__name__,
            str(exc),
        )

        return None

    source_lines = source.splitlines()

    for line_number, line in enumerate(
        source_lines[:max_lines],
        start=1,
    ):

        print(
            f"{line_number:4d}: {line}"
        )

    if len(source_lines) > max_lines:

        print(
            f"... truncated after {max_lines} lines ..."
        )

    return source


# ======================================================================================
# 4. Inspect exact live policy methods
# ======================================================================================

source_build_matrix_4d5b = (
    print_live_source_4d5b(
        "R3LivePolicyEngine.build_model_matrix()",
        R3LivePolicyEngine.build_model_matrix,
        max_lines=260,
    )
)


source_score_moves_4d5b = (
    print_live_source_4d5b(
        "R3LivePolicyEngine.score_moves()",
        R3LivePolicyEngine.score_moves,
        max_lines=360,
    )
)


source_choose_move_4d5b = (
    print_live_source_4d5b(
        "R3LivePolicyEngine.choose_move()",
        R3LivePolicyEngine.choose_move,
        max_lines=180,
    )
)


# ======================================================================================
# 5. Inspect exact feature-building functions
# ======================================================================================

source_legality_row_4d5b = (
    print_live_source_4d5b(
        "build_legality_aware_feature_row()",
        build_legality_aware_feature_row,
        max_lines=360,
    )
)


source_encoder_4d5b = (
    print_live_source_4d5b(
        "encode_r3_feature_row()",
        encode_r3_feature_row,
        max_lines=420,
    )
)


# ======================================================================================
# 6. Function-global dependency extraction
# ======================================================================================

def true_global_references_4d5b(
    fn,
):

    try:

        source = textwrap.dedent(
            inspect.getsource(fn)
        )

        tree = ast.parse(
            source
        )

    except Exception:

        return []

    local_names = set()

    loaded_names = set()

    for node in ast.walk(tree):

        if isinstance(
            node,
            ast.arg,
        ):

            local_names.add(
                node.arg
            )

        elif isinstance(
            node,
            ast.Name,
        ):

            if isinstance(
                node.ctx,
                ast.Store,
            ):

                local_names.add(
                    node.id
                )

            elif isinstance(
                node.ctx,
                ast.Load,
            ):

                loaded_names.add(
                    node.id
                )

    builtin_names = set(
        dir(__builtins__)
    )

    globals_used = sorted(
        name
        for name in loaded_names
        if (
            name not in local_names
            and
            name not in builtin_names
        )
    )

    return globals_used


dependency_targets_4d5b = {
    "build_legality_aware_feature_row":
        build_legality_aware_feature_row,

    "encode_r3_feature_row":
        encode_r3_feature_row,

    "R3LivePolicyEngine.build_model_matrix":
        R3LivePolicyEngine.build_model_matrix,

    "R3LivePolicyEngine.score_moves":
        R3LivePolicyEngine.score_moves,
}


dependency_rows_4d5b = []

for function_name, function_object in (
    dependency_targets_4d5b.items()
):

    references = (
        true_global_references_4d5b(
            function_object
        )
    )

    for reference in references:

        dependency_rows_4d5b.append(
            {
                "function":
                    function_name,

                "global_reference":
                    reference,

                "available":
                    reference
                    in globals(),

                "object_type":
                    (
                        type(
                            globals()[
                                reference
                            ]
                        ).__name__
                        if reference
                        in globals()
                        else "MISSING"
                    ),
            }
        )


dependency_df_4d5b = pd.DataFrame(
    dependency_rows_4d5b
)


print()
print("=" * 110)
print("LIVE ENCODER GLOBAL DEPENDENCIES")
print("=" * 110)

display(
    dependency_df_4d5b
)


# ======================================================================================
# 7. Search source text for side-sensitive vocabulary
# ======================================================================================

side_terms_4d5b = [
    "current_player",
    "current_side",
    "player_card",
    "opponent_card",
    "active_card",
    "inactive_card",
    "player_energy",
    "opponent_energy",
    "player_damage",
    "opponent_damage",
    "acting_energy",
    "defending_energy",
    "actor",
    "side_mode",
    "FLIP",
    "PRESERVE",
]


sources_to_scan_4d5b = {
    "build_legality_aware_feature_row":
        source_legality_row_4d5b,

    "encode_r3_feature_row":
        source_encoder_4d5b,

    "build_model_matrix":
        source_build_matrix_4d5b,

    "score_moves":
        source_score_moves_4d5b,
}


side_reference_rows_4d5b = []


for source_name, source_text in (
    sources_to_scan_4d5b.items()
):

    if source_text is None:
        continue

    for line_number, line in enumerate(
        source_text.splitlines(),
        start=1,
    ):

        matched_terms = [
            term
            for term in side_terms_4d5b
            if term.lower()
            in line.lower()
        ]

        if matched_terms:

            side_reference_rows_4d5b.append(
                {
                    "source":
                        source_name,

                    "line":
                        line_number,

                    "matched_terms":
                        ", ".join(
                            matched_terms
                        ),

                    "text":
                        line.strip(),
                }
            )


side_reference_df_4d5b = pd.DataFrame(
    side_reference_rows_4d5b
)


print()
print("=" * 110)
print("SIDE-SENSITIVE REFERENCES IN THE LIVE R3 PATH")
print("=" * 110)

if len(
    side_reference_df_4d5b
):

    display(
        side_reference_df_4d5b
    )

else:

    print(
        "No explicit side-sensitive vocabulary "
        "was detected in recovered live source."
    )


# ======================================================================================
# 8. Inspect feature contract itself
# ======================================================================================

print()
print("=" * 110)
print("R3 FEATURE CONTRACT")
print("=" * 110)

print()
print("NUMERIC FEATURES")
print("-" * 110)

for index, feature in enumerate(
    R3_NUMERIC_FEATURES,
    start=1,
):

    print(
        f"{index:02d}. {feature}"
    )


print()
print("CATEGORICAL RAW FEATURES")
print("-" * 110)

for index, feature in enumerate(
    R3_CATEGORICAL_FEATURES,
    start=1,
):

    print(
        f"{index:02d}. {feature}"
    )


print()
print("ENCODED FEATURES")
print("-" * 110)

for index, feature in enumerate(
    R3_ENCODED_FEATURE_NAMES,
    start=1,
):

    print(
        f"{index:02d}. {feature}"
    )


print()
print(
    "Numeric count     :",
    len(
        R3_NUMERIC_FEATURES
    ),
)

print(
    "Categorical count :",
    len(
        R3_CATEGORICAL_FEATURES
    ),
)

print(
    "Encoded count     :",
    len(
        R3_ENCODED_FEATURE_NAMES
    ),
)


# ======================================================================================
# 9. Explicit orientation-contract keyword tests
# ======================================================================================

combined_live_source_4d5b = "\n".join(
    source
    for source in [
        source_legality_row_4d5b,
        source_encoder_4d5b,
        source_build_matrix_4d5b,
        source_score_moves_4d5b,
    ]
    if source is not None
)


orientation_keyword_tests_4d5b = {
    "mentions current_player":
        "current_player"
        in combined_live_source_4d5b,

    "mentions side_mode":
        "side_mode"
        in combined_live_source_4d5b,

    "mentions FLIP":
        "FLIP"
        in combined_live_source_4d5b,

    "mentions PRESERVE":
        "PRESERVE"
        in combined_live_source_4d5b,

    "mentions acting_energy":
        "acting_energy"
        in combined_live_source_4d5b,

    "mentions defending_energy":
        "defending_energy"
        in combined_live_source_4d5b,

    "mentions player_card":
        "player_card"
        in combined_live_source_4d5b,

    "mentions opponent_card":
        "opponent_card"
        in combined_live_source_4d5b,
}


orientation_test_df_4d5b = pd.DataFrame(
    [
        {
            "test":
                key,

            "observed":
                value,
        }
        for key, value
        in orientation_keyword_tests_4d5b.items()
    ]
)


print()
print("=" * 110)
print("LIVE ORIENTATION KEYWORD TESTS")
print("=" * 110)

display(
    orientation_test_df_4d5b
)


# ======================================================================================
# 10. Status
# ======================================================================================

print()
print("=" * 110)
print("SECTION 4D.5B STATUS")
print("=" * 110)

print(
    "✅ Actual live frozen-R3 engine inspected"
)

print(
    "✅ Actual build_model_matrix() inspected"
)

print(
    "✅ Actual score_moves() inspected"
)

print(
    "✅ Actual build_legality_aware_feature_row() inspected"
)

print(
    "✅ Actual encode_r3_feature_row() inspected"
)

print(
    "✅ Frozen 46-feature contract enumerated"
)

print()
print(
    "NO MODEL WAS MODIFIED."
)

print(
    "NO SOURCE FILE WAS MODIFIED."
)

print(
    "NO RETRAINING WAS PERFORMED."
)

print(
    "NO BENCHMARK MATCH WAS EXECUTED."
)

print()
print(
    "➡️ NEXT: compare the actual live R3 encoding "
    "against the actor-relative training contract."
)

print("=" * 110)

==============================================================================================================
SECTION 4D.5B — ACTUAL LIVE R3 ENCODER / ORIENTATION CONTRACT AUDIT
==============================================================================================================

LIVE R3 OBJECT STATUS
--------------------------------------------------------------------------------------------------------------

                             object  available object_type
0                R3LivePolicyEngine      False     MISSING
1              r3_policy_engine_3c2      False     MISSING
2  build_legality_aware_feature_row      False     MISSING
3             encode_r3_feature_row      False     MISSING
4               R3_NUMERIC_FEATURES      False     MISSING
5           R3_CATEGORICAL_FEATURES      False     MISSING
6          R3_ENCODED_FEATURE_NAMES      False     MISSING

AssertionError: One or more live R3 encoder objects are missing. Do not continue until the existing Notebook 59 R3 namespace is restored.